### ISSUE TITLE
Note 4 display keeps switching on

### ISSUE THREAD

**Issue by Vangelo51** [thunderbird/thunderbird-android#1024]
Display on my new Note 4 would keep switching on for no reason. Finally discovered K9 was causing issue if email saved to draft...............when draft deleted, issue stopped.

**Comment by cketti** [comment]
It seems unlikely that having a message in the Drafts folder would be causing this.

Can you provide detailed instructions on how to reproduce this behavior? What K-9 Mail version are you running? What Android version?

**Comment by Vangelo51** [comment]
I know....weird...but I just copied your email to draft folder, went back to home screen and turned display off...a few seconds later it was on again. Delete draft and its fine. 

Running 5.007, android 5.1.1 on Samsung note 4. 

On 17 January 2016 07:37:28 GMT+00:00, cketti <notifications@github.com> wrote:
>It seems unlikely that having a message in the Drafts folder would be
>causing this.
>
>Can you provide detailed instructions on how to reproduce this
>behavior? What K-9 Mail version are you running? What Android version?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1024#issuecomment-172298537

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cketti** [comment]
Did you maybe configure K-9 Mail to notify for new messages in the Drafts folder?

**Comment by Vangelo51** [comment]
Not intentionally.... How can I check?

On 17 January 2016 07:46:08 GMT+00:00, cketti <notifications@github.com> wrote:
>Did you maybe configure K-9 Mail to notify for new messages in the
>Drafts folder?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1024#issuecomment-172298809

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cketti** [comment]
Well, do you see a notification in the status bar when there's a new message in the Drafts folder? What is displayed on the screen when it turns on?

**Comment by Vangelo51** [comment]
No....there is no notification in status bar. 
It reverts to the same screen I switch the display off in. 

I gather you can't duplicate? Something in K9 is triggering the effect. 

On 17 January 2016 08:00:05 GMT+00:00, cketti <notifications@github.com> wrote:
>Well, do you see a notification in the status bar when there's a new
>message in the Drafts folder? What is displayed on the screen when it
>turns on?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1024#issuecomment-172299160

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cketti** [comment]
There's no code in K-9 Mail to turn on the screen. To the best of my knowledge the only thing that could trigger that is a notification. 
Having the screen turn on when there's a message in the Drafts folder is not a common issue, otherwise we would have heard of it before. I'm afraid without detailed instructions on how to reproduce this, there's nothing we can do.

You could try asking for help on the [mailing list](http://groups.google.com/group/k-9-mail). Maybe someone has an idea what is going on exactly.

**Comment by Vangelo51** [comment]
I reinstalled and its not doing it now. 

On 17 January 2016 08:18:24 GMT+00:00, cketti <notifications@github.com> wrote:
>There's no code in K-9 Mail to turn on the screen. To the best of my
>knowledge the only thing that could trigger that is a notification. 
>Having the screen turn on when there's a message in the Drafts folder
>is not a common issue, otherwise we would have heard of it before. I'm
>afraid without detailed instructions on how to reproduce this, there's
>nothing we can do.
>
>You could try asking for help on the [mailing
>list](http://groups.google.com/group/k-9-mail). Maybe someone has an
>idea what is going on exactly.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1024#issuecomment-172299647

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
