### ISSUE TITLE
Message Send Failed "Signing requested, but no key selected!"

### ISSUE THREAD

**Issue by adamsmd** [thunderbird/thunderbird-android#1050]
On the current git HEAD, on a device without any PGP apps installed, composing and then sending a message fails with a toast saying "Signing requested, but no key selected!".  The effect of this is that e-mails can't ever be sent.

Looking at the code this seems to be due to [line 51 of RecipientPresenter.java
](https://github.com/k9mail/k-9/blob/8ceaf13648ff1eaab88c022923c68cab352bb8f8/k9mail/src/main/java/com/fsck/k9/activity/compose/RecipientPresenter.java#L51) which checks `isMissingSignKey()` which is true when `signingKeyId` is `null` in the current `cryptoStatus`.  If no PGP app is installed that value will always be `null`.

I think the proper solution would be to have `isMissingSignKey()` also check if `cryptoStatus.cryptoMode` is `CryptoMode.DISABLE` and also set the `currentCryptoMode`, which currently defaults to `CryptoMode.OPPORTUNISTIC`, to default to `CryptoMode.DISABLE` as users without OpenPGP can't even open the menu to change modes.

The following commit shows what I propose: https://github.com/adamsmd/k-9/commit/1067f1b905bf90a49fe8adc6599d394df56b33f5

I didn't see anywhere that the current code saves a preference for `currentCryptoMode`.  So I assume this is a feature still in development, but this change will allow users without OpenPGP to continue using and testing HEAD.

**Comment by don59** [comment]
I have the same problem. Have you fix it?

**Comment by Valodim** [comment]
Did you try on current master?
