### ISSUE TITLE
Resync messages on UIDVALIDITY changes (IMAP)

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#1074]
When the UIDVALIDITY value of a folder changes all previous UIDs are invalid. We currently don't handle this situation. The easiest way would be to throw away all messages and redownload.

Servers don't usually change the UIDVALIDITY value which is why this is rarely an issue. But e.g. changing from one server to another will cause problems.

**Comment by rhari991** [comment]
I'd like to work on this.

**Comment by DasWookie** [comment]
This happens to me frequently as many of my folders are renamed in the backend for archive, and new ones are created as messages are delivered or saved to that location.

I can always clear the folder via the folders view, and force a new download, but it does get a little annoying when I forget it's after the first and those folders are using some cached content.
