### ISSUE TITLE
Opening no-more-existent mail crashes K9

### ISSUE THREAD

**Issue by gunterkoenigsmann** [thunderbird/thunderbird-android#1079]
Did delete a Mail from my IMAP account while my device running K9 had no internet connection. Then (once the device was connected to the internet again) tried to open this Mail => Crash.

Might this be the root cause of Bug #814?
### Expected behaviour

If I try to open a no-more existing mail I would expect to be returned to the current thread and, if the current thread does no more exist, as well, to the inbox.
### Actual behaviour

K9 sometimes (about 10% of the time) crashes
### Steps to reproduce
1. Use an IMAP account 
2. Make sure that K9 cannot see immediately that an e-mail has been deleted
3. Delete an E-Mail from outside K9
4. Try to open this E-Mail using K9.
### Environment

K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

Thanks a lot,
and kind regards,

```
 Gunter
```

**Comment by cketti** [comment]
Can you please provide a debug log containing a stack trace of the crash. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by gunterkoenigsmann** [comment]
Seems to be no more reproducible => Closing this bug.
