### ISSUE TITLE
Messages turn blank when opened while doing imap server search

### ISSUE THREAD

**Issue by protostork** [thunderbird/thunderbird-android#1097]
When doing a server-side imap search, while search results are being loaded and the search is ongoing, if you click on one of the search resuts, it usually opens a blank screen instead of the message (presumably because the server can't take two connections at the same time while searching?).

Something similar also happens while k9 is downloading new emails from the server and when you click on a message where the header has been retrieved but not the body. 

If you try to open the same un-downloaded message several times, sooner or later the message will turn into a complete blank subject line and sender, that you can never open again from k9 (without flushing the cache, etc), even after all messages have downloaded.

Not sure if this is fixable or simply a problem with IMAP protocols, but thought would flag it here anyway in case it's something easy to fix.

**Comment by cketti** [comment]
This should be fixed.
