### ISSUE TITLE
Notification stays after reading e-mail

### ISSUE THREAD

**Issue by FeuRenard** [thunderbird/thunderbird-android#1110]
### Expected behaviour

Notification disappears after reading an e-mail.
### Actual behaviour

The notification stays after reading the e-mail, when the e-mail was received by refreshing the inbox out of the inbox.
### Steps to reproduce
1. Go to the inbox, where you expect to get an e-mail in.
2. Refresh the inbox, so you receive the e-mail.
3. Click on the new e-mail to read it.
4. (optional) Go back to the inbox by any back button. You see the e-mail is definitely marked unread.
5. Press the home button to leave K-9.
### Environment

K-9 Mail version: 5.008

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by gdt** [comment]
I think I have seen this too.   Do you have push, or is this poll only?

My theory is that the notification is withdrawn when the local impression of the server state changes to read, rather than the local state.   But I have not read the code to be able to support this theory.

**Comment by FeuRenard** [comment]
I don't know whether I have push enabled in any way. But at the moment I only receive my e-mails by manually refreshing my accounts or folders.
