### ISSUE TITLE
K9 automatically deleting email

### ISSUE THREAD

**Issue by mthomas10** [thunderbird/thunderbird-android#1152]
I receive emails, read them, close application, open application…and all my emails are gone. Please help!
### Environment

K-9 Mail version: 5.008

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by philipwhiuk** [comment]
Do you have a debug log? Are you using a free email provider that it might be possible for us to test against?

**Comment by mthomas10** [comment]
Don’t know how to retrieve a debug log. My email is hosted by 1and1.com

**Comment by philipwhiuk** [comment]
There's information here on debug logs. https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by delgado92651** [comment]
I started getting a similar behavior, after I load new messages, previous messages are deleted.

**Comment by philipwhiuk** [comment]
@delgado92651 Are they actually being deleted on the server. There's an option to only display the last X messages and the last X messages since the date the last poll occurred.

**Comment by p9141au** [comment]
I am also having this problem.
K9 version 5.008
Android version 5.1

For me it is only happening with a free yahoo mail account, all other account messages stay.
Messages are not removed from server and are re-downloaded next sync. I have not been able to recreate it on demand, it just happens randomly several times a day, new message received/read/deleted or not.

Sorry for the long log, i left it logging all day and it happened two times that i noticed.
Hope this helps.
[k9-log.txt](https://github.com/k9mail/k-9/files/175546/k9-log.txt)

**Comment by philipwhiuk** [comment]
Ok I'll probably set-up a free Yahoo account then to test this.

But if you're using Yahoo Mail in IMAP mode then it's probably a "feature", not a bug. See: [Sync Messages From](https://github.com/k9mail/k-9/wiki/Manual-accountsettings#sync-messages-from)

**Comment by delgado92651** [comment]
Not using Yahoo using Cox. The problem just started a couple of days ago, everything was fine before that.

 

Thanks,

 

Al

**Comment by p9141au** [comment]
I see that setting, but have it set as always to "any time".
I have another IMAP email, Gmail, but i don't experience any problems with that account.
The POP3 usually works fine, it was incorrectly set up as I had reset the app then reconfigured to see if it helps, to no avail.
The problem has only started occurring since the last update on Play Store, and only with Yahoo mail using IMAP.
I will run that same IMAP account for a while with POP3 and let you know how it goes.

**Comment by WhiteSites** [comment]
I had a client call me today saying every email in their inbox was just deleted.  The strange thing is they were not even working with their email.  I have his email setup on two devices. A windows PC using Outlook, and his Android Cell phone using K9 Mail.  The phone was sitting on his desk, not being used.  outlook was open, but he was working on other applications at the time.  Then he noticed all the messages in outlook disappeared.  I checked the mail server logs and noticed the EXPUNGE command being sent to all the messages in his inbox.  The command was sent from a T-Mobile IP which leads me to his cell phone.  He hadn't touched his phone at all.  Hopefully you can find the cause of this.  I unfortunately don't have any logs from his device that I could provide.  Let me know how to setup logging for K9 Mail in case this can be of us in the future if this happens again.

**Comment by Ra-Na** [comment]
I have the same issue. It happend several times now. Reading a message, app is closed or crashes, the message is deleted even from the server, which is not the default behavior. 

Version 5.600 on Android 8.1.0.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem in K-9 Mail 5.7xx.
