### ISSUE TITLE
Select all is broken

### ISSUE THREAD

**Issue by BumbleBernie** [thunderbird/thunderbird-android#1176]
### Expected behaviour

Select all in inbox should mark all emails as selected
### Actual behaviour

K-9 mail crashes
### Steps to reproduce
1. Select all
   2.Crash
   3.
### Environment

K-9 Mail version:
5.008
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by philipwhiuk** [comment]
Depending on the type of crash (and whether you installed it from an AppStore), we might be able to resolve this from the AppStore provided crash logs. However, if not, and it's reproducible, it would be useful to see the debug logs. See:  [Logging Errors](https://github.com/k9mail/k-9/wiki/LoggingErrors)

**Comment by BumbleBernie** [comment]
K-9 has been installed from the Amazon App-Store. It is running on a Sony Xperia Z4 tablet.
I have the developer mode on in Android, I habe adb.exe running on my Windows 10 64 bit PC, but I get stuck in connecting the device (connected via USB)
I downloaded the driver as described but it does not seem to work with 64 bit.
I am not a programmer but certainly willing to help.
Regards,
Bernie
