### ISSUE TITLE
Issue when deleting recipient "chip"

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#1204]
### Expected behaviour

Pressing backspace on (soft) keyboard should remove recipient "chip".
### Actual behaviour

Still seeing the `toString()` output  (see PR #1202).
### Steps to reproduce
1. Add two recipients
2. Move focus to different input field
3. Move focus back to "To" field
4. Press backspace
5. See `toString()` output for second recipient
### Environment

K-9 Mail version: b586522ca11b190717c24e4abea2583be7ff9043
Android version: 6.0.1

**Comment by Valodim** [comment]
taking care of the upstream bug

**Comment by cketti** [comment]
If that's taking too long we could implement a `toString()` that returns the email address as a stopgap measure.

**Comment by philipwhiuk** [comment]
Linking a (closed) upstream issue that discusses it https://github.com/splitwise/TokenAutoComplete/issues/202

**Comment by Valodim** [comment]
it's a simple fix, and the maintainer seems active. submitted a PR ( https://github.com/splitwise/TokenAutoComplete/pull/212)
