### ISSUE TITLE
Duplicate folder entries in the database

### ISSUE THREAD

**Issue by ghostrider72** [thunderbird/thunderbird-android#1220]
I installed the latest k9 mail version taken from the play store on both my identical phones (two elephone trunks with Android 5.1) but in one of them k9 is showing a very strange behavior:
in fact, there are two trash folders and even if I check on Gmail desktop via web, everything is normal. 
So I don't know what's causing this issue and need your help. 
Thanks and happy Easter!

**Comment by philipwhiuk** [comment]
I found this. I don't know what causes it, but what happens is we get back two entries for the same `LocalFolder` when fetching the list.

I added a temporary fix to my dev code here: https://github.com/philipwhiuk/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/activity/FolderList.java#L780

I don't really want to push it because it's not actually fixing the problem, just hiding it.

It looks like `localStore.getPersonalNamespaces(false)` is returning duplicates.

And that just does a DB query, so there's a database duplication issue somewhere. That's hard to easily debug, so there's some investigation to do.

**Comment by ghostrider72** [comment]
Thanks for the help but I must admit I understood nothing. Said in other words: is it a known problem? Is there any idea why it appears in one phone and not in the other? 
Any way to fix it? 
Thanks

**Comment by philipwhiuk** [comment]
It's a problem I was vaguely aware of but hadn't written a bug for (mainly because I often hit bugs which are only present in unreleased code).

The analysis was mainly for me / another person who wants to try and fix it at some point (e.g. before the next stable release).

As for why it happens in only one phone, I don't know. It may be luck. It may be just a matter of time. Heck it may be possible you'll get three eventually :( 

I think if you delete the account or possibly just 'Recreate data' the extra entries should go. 

Can't promise they won't come back at some point until I know why it's being dupe'd though.

**Comment by ghostrider72** [comment]
Ok, thanks. Would you please tell me where the "recreate data"  is?

**Comment by philipwhiuk** [comment]
Long-tap on the account in the accounts list.

**Comment by ghostrider72** [comment]
Thanks a lot! It worked! Thank you so much! 
I wish you a very pleasant day!

**Comment by philipwhiuk** [comment]
In terms of fixing this:

We are clearly creating the same folder in the DB twice. `folders.name` should be a unique field. If it were enforced in the DB we'd throw an SQLException when the duplication occurs. We could add this and then fix based on the inevitable crashes but that's kind of bad UX.

There are two calls to create a DB entry, MessagingController.doRefreshRemote and LocalFolder.create. Both do check for pre-existence, but outside a DB lock.

I think the only reason this can occur is that they are running simultaneously. However there's lots of calls to create making it very difficult to work out exactly why this is.

One solution is just do a second check while we have the DB lock and silently return if it exists. We could optionally also log a stack of where this occurring for debugging purposes, but unless we add something like ACRA we're never going to know for 99% of cases that it's occurring.

**Comment by cketti** [comment]
We could make the code only throw for debug builds (use `BuildConfig.DEBUG`). That way we at least have a chance to catch it during development.

**Comment by lazarus477** [comment]
Could this be triggered by the Import settings feature?

**Comment by CEB1970** [comment]
Importing the same account settings twice can cause this problem. I just had the problem occur after importing my account settings twice. There were duplicate Outbox and Trash folders. I fixed it by deleting the account and then importing the account settings just once.

**Comment by chrisrapson** [comment]
I had 2 copies of the Outbox folder in a Gmail account. Recreate data warns that it is a "last resort", so I decided to just change the Folder Display Class to hide it instead.

**Comment by PCZeroNet** [comment]
Will we ever see this fixed?  The recreate data does not help.  As soon as mail is fetched the next time after doing so the duplicates re-appear.

**Comment by NicoPL** [comment]
Same for me. Same issue on 3 different phones, with 3 different mailboxes when:
- creating a new account to sync in imap
- having the K9 app in French
- on the server side, 5 folders named: Inbox, Drafts, Sent, Trash, spam

I get 12 folders, and only the Inbox seems to be correctly used:
- Archive (Archive)
  -> folder in K9 only
- Brouillons (Brouillons)
  -> means 'draft', folder in K9 only, used by K9
- Corbeille (Corbeille)
  -> means 'trash', folder in K9 only, emails deleted in K9 end up in there
- Envoyés (Envoyés)
  -> means 'sent', folder in K9 only, emails sent with K9 end up in there
- Boîte de réception
  -> the real 'Inbox' folder on the server side, both used on the server side and by K9
- Boîte d'envoi
  -> means 'sending box'
- Pourriel (Pourriel)
  -> means 'spam', folder in K9 only
- Drafts
  -> the real 'draft' folder on the server side, not used by K9
- Junk
  -> no idea, not in the server side, not used by K9
- Sent
  -> the real 'sent' folder on the server side, not used by K9
- spam
  -> the real 'spam' folder on the server side, not used by K9
- Trash
  -> the real 'trash' folder on the server side, not used by K9

I believe it's an error when mapping the folders, and may appear on translated versions of K9 only?

**Comment by cketti** [comment]
I believe this is no longer an issue with `master`.

**Comment by wiz0u** [comment]
Had the problem with version 5.600
"Recreate data" solved it.

**Comment by nyetwurk** [comment]
![Screenshot_20200801-141750.png](https://user-images.githubusercontent.com/1088639/89110653-cf86df80-d401-11ea-9b37-e26b18944195.png)

**Comment by nyetwurk** [comment]
After recreate data:

![Screenshot_20200801-141946.png](https://user-images.githubusercontent.com/1088639/89110688-1aa0f280-d402-11ea-9c17-60dee81fb335.png)

**Comment by nyetwurk** [comment]
had to force quit and do it a third time
5.600
