### ISSUE TITLE
"impossible to send some message" with no message to send

### ISSUE THREAD

**Issue by crystalfp** [thunderbird/thunderbird-android#1236]
### Expected behaviour

I expect this message should be generated when I'm sending messages and there is an actual problem with the server.
### Actual behaviour

During a periodic poll, 
Sometimes it shows the following error (truncated because there is no way to read it outside the notification area):
"Unable to send some message
negative SMTP reply 501 5.1.3 invalid ...

Without any message to send.

Also I have two POP3 and one IMAP accounts configured and the message does not say from which of them it generates.
### Steps to reproduce

Wait for new mail polling. It seems not to happen if I ask for a manual update.
### Environment

K-9 Mail version: 5.008 (the problem was not happening with a previous version of K-9, I think was the 4.x serie

Android version: 5.0 (Galaxy Note 3)

Account type (IMAP, POP3, WebDAV/Exchange): See above

**Comment by philipwhiuk** [comment]
Can you enable debug logging in the settings and provide the full log (which should be put in the K9mail-errors folder) please? 5.1.3 is apparently invalid address. Unless you have a messaged still in an Outbox - when you send a mail we put it in the Outbox and enqueue a Send task to be run asynchronously - I'm not sure why you're getting the error.

**Comment by crystalfp** [comment]
OK, thanks!
Logging enabled, now waiting for the problem to happen again.
BTW, all the Outboxes seems absolutely empty.
See you!
		mario

On 31-Mar-16 11:14, Philip wrote:
> Can you enable debug logging in the settings and provide the full log
> (which should be put in the K9mail-errors folder) please? 5.1.3 is
> apparently invalid address. Unless you have a messaged still in an
> Outbox - when you send a mail we put it in the Outbox and enqueue a Send
> task to be run asynchronously - I'm not sure why you're getting the error.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/k9mail/k-9/issues/1236#issuecomment-203838462>
>

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS)
v. Trevano 131, 6900 Lugano, Switzerland
Tel: +41 (91) 610.82.60

**Comment by crystalfp** [comment]
Dear Philip,
obviously for the Murphy Law the problem has not happened again...

But I have a possible explanation that maybe could help.

In my family we have two shared POP3 mailboxes. From my laptop, when 
some other family member check these mailboxes from their smartphones, I 
receive the error "Mailbox in use" when periodically polling them. This 
could be the reason of the random appearance of the error in K9.

So now the problem become the error message itself. It should be related 
to checking (or otherwise accessing) the mailbox, NOT sending a message. 
Compare this to checking the mailbox without a working connection. I 
don't receive any notification (or error) for this.

Last, I suggest the notification should mention the mailbox that failed.

Thanks again!
		mario

P.S.: if Murphy will help me, I will send the error log...

On 31-Mar-16 11:14, Philip wrote:
> Can you enable debug logging in the settings and provide the full log
> (which should be put in the K9mail-errors folder) please? 5.1.3 is
> apparently invalid address. Unless you have a messaged still in an
> Outbox - when you send a mail we put it in the Outbox and enqueue a Send
> task to be run asynchronously - I'm not sure why you're getting the error.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/k9mail/k-9/issues/1236#issuecomment-203838462>
>

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS)
v. Trevano 131, 6900 Lugano, Switzerland
Tel: +41 (91) 610.82.60

**Comment by philipwhiuk** [comment]
SMTP errors will not be caused by failing to poll the inbox. So no, I don't think it's relevant.

**Comment by crystalfp** [comment]
OK, tanks!

Other trivial hypothesis: setting the logging of errors inhibits the 
error to happen or to be reported. If in the next two days nothing will 
be logged, I will disable it and see.

Anyway, thanks for your time.
					mario


On 04-Apr-16 14:05, Philip wrote:
> SMTP errors will not be caused by failing to poll the inbox. So no, I
> don't think it's relevant.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/k9mail/k-9/issues/1236#issuecomment-205265921>
>

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS)
v. Trevano 131, 6900 Lugano, Switzerland
Tel: +41 (91) 610.82.60
