### ISSUE TITLE
Improper HTML rendering

### ISSUE THREAD

**Issue by uruiamme** [thunderbird/thunderbird-android#1244]
### Expected behaviour

I get emails chock full of HTML, pictures, and formatting from Home Depot. On my desktop client, Thunderbird, everything renders fine.
### Actual behaviour

I cannot see all of the content in the body of the email in K9. There is also no way to scroll to the right where the information is located.
### Steps to reproduce
1. Get a Home Depot email
2. Notice you cannot pan images to the right and see content
3. See this message:
   [INBOX)42260.txt](https://github.com/k9mail/k-9/files/198946/INBOX.42260.txt)
### Environment

K-9 Mail version:
5.008
Android version:
5.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Do you have Display->Auto-fit messages selected.

In the meantime I signed up for their spam, so if they send another broken e-mail I'll have a go at debugging it.

**Comment by uruiamme** [comment]
I tried both settings and it didn't change

**Comment by uruiamme** [comment]
I can forward you the offending message and you can hopefully see it. If I get an actual email from you privately I can do that. I think it would help to see the rendering issue firsthand. In the one I am thinking of, there is a coupon to the right of a promotion image. The coupon cannot be seen or clicked on. Other things to the right are also invisible.

**Comment by philipwhiuk** [comment]
Huh, this looks like a HtmlCleaner issue in light of recent stuff.

Assigning to @cketti as he's looking at using JSoup.

**Comment by cketti** [comment]
We have made quite a few changes related to HTML rendering. Please create a new issue if this is still a problem.
