### ISSUE TITLE
Reply flag is not set anymore when replying to a mail

### ISSUE THREAD

**Issue by msebald** [thunderbird/thunderbird-android#1250]
### Expected behaviour

Reply flag is set when replying to a mail.
### Actual behaviour

When replying to a mail I do not see a reply flag for the original mail I replied to. When checking the account with a different client (web/Thunderbird) I do not see a flag, too. So it is no frontend bug, the flag is not set anymore, beginning with 5.108.
### Steps to reproduce

See above.
### Environment

K-9 Mail version: 5.108

Android version: CM 12.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Removed by https://github.com/k9mail/k-9/commit/99503960e557ec39f31603965966ebe4cccf8dfc#diff-048e1d4d2faf1c98b0b515ebad5dca98L1203

I don't think there was a particular reason for this, just an oversight when it was refactored.

**Comment by msebald** [comment]
Thank you! I just checked, a forwarded flag is also not set anymore. But as you wrote "message reference flags" it should include all flags. Just wanted to make extra sure. ;-)

**Comment by philipwhiuk** [comment]
Yep it will.
