### ISSUE TITLE
App crashed by typing address in the address field when composing a message

### ISSUE THREAD

**Issue by webratte** [thunderbird/thunderbird-android#1251]
### Expected behaviour

Should be possible typing addresses into the address field.
### Actual behaviour

App crashed by typing address in the address field
### Steps to reproduce
1. Click the compose icon
2. Try to type a address into the "To:" field
### Environment

K-9 Mail version: 
5.108 (current alpha)

Android version:
5.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Valodim** [comment]
does this happen for any address? After how many typed characters?  What keyboard app do you use?

**Comment by webratte** [comment]
It happens by typing the second charter.

I use the standard Xperia Keyboard (https://play.google.com/store/apps/details?id=com.sonyericsson.textinput.uxp)
on a Sony Xperia M4 Aqua.

**Comment by Valodim** [comment]
Ok, thanks. did you report the crash?

@cketti any stack trace for this?

**Comment by webratte** [comment]
What do you mean with "Report"?
I'm just a User without developer skills.

BTW. 
By click on the reply Button to answere the Github mail, K9 chrashed also.

**Comment by philipwhiuk** [comment]
You should have got a dialog like this (but for K-9 obviously)
 
![image](https://cloud.githubusercontent.com/assets/1316415/14232265/2de79dca-f99c-11e5-90fc-b37dded3da3f.png)

**Comment by webratte** [comment]
No, the K9 window disappear immediately after start typing the second character or press the reply button.

**Comment by philipwhiuk** [comment]
The activity window will disappear but you ought to get a follow-up dialogue telling you K-9 has crashed similar to above. If not the phone is doing something very odd and given we won't be able to get a stack trace as a result, there's not much we can do until someone else can reproduce it.

Given it seems to happen in other cases (like just clicking reply) I'd suggest re-installing the app (remember to export your settings).

**Comment by philipwhiuk** [comment]
See #1253 but @webratte talked about K-9 crashing just by clicking Reply.

**Comment by webratte** [comment]
I have just reinstalled the App.
Now only the compose window is closing by typing the second character. 
The App stay open.

And no window for create/send a logfile.

**Comment by cketti** [comment]
Please follow these steps to record a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by webratte** [comment]
If I have a little bit more time I will check it out.
Probably next Weekend.

**Comment by ouafnico** [comment]
Same problem on this version. 
It happens when creating a new mail.
I can get over it clicking the 3 dots and chose "add from contacts".

**Comment by webratte** [comment]
I have just created a log (a few seconds after crash)

Is there a mail address where I can send this (particular makes anonymous) Log file?
I don't know if there still sensible informations into the file. So I don't like to make it public.

If you check (and maybe clean it from sensible data), feel free to post it here.

**Comment by philipwhiuk** [comment]
You can email it me - philip@whiuk.com - I'll look through it.

Unless you enabled sensitive logging there shouldn't be anything. But I'll clean anything up if there is :)

**Comment by webratte** [comment]
Done.
I hope it helps. :-)

**Comment by philipwhiuk** [comment]
Stack trace :)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Loader android.app.LoaderManager.restartLoader(int, android.os.Bundle, android.app.LoaderManager$LoaderCallbacks)' on a null object reference
04-21 19:37:34.905 E/AndroidRuntime( 9726): 	at com.fsck.k9.view.RecipientSelectView.performFiltering(RecipientSelectView.java:253)
04-21 19:37:34.905 E/AndroidRuntime( 9726): 	at android.widget.MultiAutoCompleteTextView.performFiltering(MultiAutoCompleteTextView.java:101)
04-21 19:37:34.905 E/AndroidRuntime( 9726): 	at android.widget.AutoCompleteTextView.doAfterTextChanged(AutoCompleteTextView.java:783)
04-21 19:37:34.905 E/AndroidRuntime( 9726): 	at android.widget.AutoCompleteTextView$MyWatcher.afterTextChanged(AutoCompleteTextView.java:748)
04-21 19:37:34.905 E/AndroidRuntime( 9726): 	at android.widget.TextView.sendAfterTextChanged(TextView.java:7720)
....
```

So the loaderManager is obviously null, which means either:

1) onAttachedToWindow is never called
2) getContext() returns something that isn't an Activity.

Per this http://stackoverflow.com/questions/3901590/get-activity-object-while-in-view-context/3901704#3901704 we should probably switch to injecting the LoaderManager from the activity into the View rather than hoping we get the Activity back.
