### ISSUE TITLE
v5.009 does not use default and chosen language

### ISSUE THREAD

**Issue by marutosi** [thunderbird/thunderbird-android#1254]
I have two Android.
On Android 4.4.4, v5.008 uses **Japanese** as default language. But v5.009 uses **English**.
I try set Japanese explicitly, but no effect.

On Android 4.1.2, v5.009 uses Japanese.

**Comment by philipwhiuk** [comment]
In what scenario - the UX or for e-mail composition or for both?

**Comment by marutosi** [comment]
UX.
![screenshot_2016-04-04-21-51-51](https://cloud.githubusercontent.com/assets/200784/14248785/601de23e-fab1-11e5-9e54-d33c34636def.png)

**Comment by marutosi** [comment]
v5.008 from https://github.com/k9mail/k-9/releases/download/5.008/k9-5.008-release.apk
![screenshot_2016-04-04-22-33-32](https://cloud.githubusercontent.com/assets/200784/14249742/258e47d0-fab6-11e5-8402-f472bfe9f31f.png)

**Comment by philipwhiuk** [comment]
This seems to work for me - both overriding the System default and using the system default with a non-English language. Nor are there any changes affecting language

However you do have to quit the application after so it recreates the activity with the new settings. Did you try that?

**Comment by jmzama** [comment]
Same here. I used k9mail in Spanish, but after last update (5.009), everything is in English. Settings-Global-Display-Language is, as always, in "System Default" but changing to Spanish has no effect; it remains in English.

**Comment by philipwhiuk** [comment]
Have you quit and restarted the app since changing the language - the old windows will keep the old language. On my device I installed 5.009 and this works fine.

**Comment by cketti** [comment]
Can you please check if 5.010 fixes your problem. Available here: https://github.com/k9mail/k-9/releases/tag/5.010

**Comment by marutosi** [comment]
5.010 works fine. Thanks!

**Comment by jmzama** [comment]
After updating to 5.010 everything works fine. Thanks.
