### ISSUE TITLE
Thread listed multiple times in the message list

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#1275]
Sometimes threads are listed more than once in the message list.

This is because of a bug in the query to create the threaded message list in `EmailProvider`. Usually the latest message in a thread is displayed. But when multiple messages have the same timestamp all of them are displayed.
### Environment

K-9 Mail version: 5.108

![k9mail_threaded_list_display_error](https://cloud.githubusercontent.com/assets/218061/14440220/33400930-002f-11e6-9f6c-59a4df444576.png)

**Comment by cketti** [comment]
I reverted the fix because of #1293

**Comment by philipwhiuk** [comment]
I think this is probably now fixed given #1307 was merged.
