### ISSUE TITLE
Recipient box background colour not changed in dark theme when composing.

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#1277]
### Expected behaviour

The recipient box with the real name/email in it should be themed to be dark when the user has a dark theme enabled.
### Actual behaviour

The background stays the same colour, but the text is themed to be lighter. This makes the background and foreground very similar, making the box hard to read.
### Steps to reproduce
1. Enable dark theme
2. Enter any recipient in the "To: " box
### Environment

K-9 Mail version: 5.108

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Screenshot

![image](https://cloud.githubusercontent.com/assets/1316415/14456807/b2de39d6-009e-11e6-9f46-7607ed7739d4.png)
