### ISSUE TITLE
ImapFolder.executeSimpleCommand is not synchronized and doesn't check for a connection

### ISSUE THREAD

**Issue by philipwhiuk** [thunderbird/thunderbird-android#1283]
### Expected behaviour

Should throw an MessagingException if there's no connection available, but should probably actually try and open a new one if connection is null.
### Actual behaviour

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(java.lang.String, boolean, com.fsck.k9.mail.store.ImapStore$UntaggedHandler)' on a null object reference
    at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:862)
    at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3151)
    at java.lang.Thread.run(Thread.java:818)
```
### Steps to reproduce

> I Have several IMAP push folders (around 15) and often k9 is not able to send messages.
> One workaround is to shut down data and turn it on after a few seconds.
> I see also in the status a SetFlagBulk 0/1 in the folders status.
> 
> Seems to me stuck trying to do something.
> I do not see any error in catlog.
### Environment

K9-Mail version: 5.010
Device make: LGE
Device model: Nexus 5X
Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by lbdroid** [comment]
This glitch has been present in k9mail since 2008 or 2009. It is VERY frustrating.

**Comment by cketti** [comment]
I believe this is no longer an issue.
