### ISSUE TITLE
Subject appear twice

### ISSUE THREAD

**Issue by frederiiiic** [thunderbird/thunderbird-android#1326]
### Expected behaviour

In Settings / Global settings / Display, i've plugged "Correspondent above subject".
### Actual behaviour

Correspondent disappear, and the subject appear twice. 
### Environment

K-9 Mail version:
5.010
Android version:
5.1
Account type (IMAP, POP3, WebDAV/Exchange):
Gmail, IMAP

UP: sorry for the last issue in french, i've just made it too fast, was thinking of french dev...
Thanks for anderstanding, nothing against you.

**Comment by madduck** [comment]
Here's a screenshot with "Correspondent above subject" enabled:

![enabled](https://user-images.githubusercontent.com/195073/28916491-adbc1f8c-7842-11e7-9d53-f6445e9e381d.png)

And here's one with the setting disabled:

![two](https://user-images.githubusercontent.com/195073/28916505-bc065c42-7842-11e7-80f5-9bd90222566e.png)

As you can see, with the setting disabled, the subject is just repeated at the start of the preview, where I'd now expect to see the correspondent appear.

**Comment by cketti** [comment]
This only happens when switching the setting and returning to the message list. The list will be displayed properly if the message list screen is closed and reopened.

**Comment by cketti** [comment]
This should be fixed in recent beta versions (5.7xx).
