### ISSUE TITLE
Answer acts like answer all

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#1369]
### Expected behaviour

Only the sender is copied to the reciever field on the compose screen.
### Actual behaviour

All the email addresses in the original email are copied to the reciever fields on the compose screen.
### Steps to reproduce
1. open a recieved mail with multiple recievers
2. Click on the answer icon button and then on answer in the popup
### Environment

K-9 Mail version: v5.108

Android version: 6.0.1; Security Patch: 1. March 2016)

Device: Nexus 5X

**Comment by philipwhiuk** [comment]
We should be passing in the action that we have here: https://github.com/k9mail/k-9/blob/9d55b6c95717cd2195621b46e9cf8b0fc049e7e7/k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java#L1531

to the replyToPresenter here: https://github.com/k9mail/k-9/blob/9d55b6c95717cd2195621b46e9cf8b0fc049e7e7/k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java#L1580

and then only adding the right ones here: https://github.com/k9mail/k-9/blob/9d55b6c95717cd2195621b46e9cf8b0fc049e7e7/k9mail/src/main/java/com/fsck/k9/activity/compose/RecipientPresenter.java#L129

I guess this was reworked when crypto stuff was added?
