### ISSUE TITLE
K9 crash try attaching files

### ISSUE THREAD

**Issue by ShakurGit** [thunderbird/thunderbird-android#1394]
### Expected behaviour

Adding attachment and browising files whit Amaze or other files manager I would like to attach a file
### Actual behaviour

K9 crash when I select the files whit Amaze or other files manager (process "com.fsck.k9" stop); if I select files from stock image gallery app or stock audio library app it works fine.
Downgrading K9 to v5.008 everything works fine
### Steps to reproduce

1.Create new email
2.Add attachment
3.Select a file whit Amaze or any other files manager
### Environment

K-9 Mail version:
5.010
Android version:
4.0.4
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Please provide a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by ShakurGit** [comment]
Tanx for reply, I don't know if I'm doing right, sorry. Anyway, here's the log file

**Comment by Valodim** [comment]
"Here" where?

**Comment by ShakurGit** [comment]
[alogcat.2016-05-29-09-48-48+0200.txt](https://github.com/k9mail/k-9/files/288334/alogcat.2016-05-29-09-48-48.0200.txt)
Probably I made some mistake, is it ok now?

**Comment by Valodim** [comment]
it's a SafeContentResolver issue, interesting..

**Comment by ShakurGit** [comment]
additional information: my device is rooted and files manager has root exploring enabled, rom is stock ICS 4.0.4

**Comment by philipwhiuk** [comment]
```
05-29 09:47:58.000 E/AndroidRuntime( 9042): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load os-compat: findLibrary returned null
05-29 09:47:58.000 E/AndroidRuntime( 9042): 	at java.lang.Runtime.loadLibrary(Runtime.java:365)
05-29 09:47:58.000 E/AndroidRuntime( 9042): 	at java.lang.System.loadLibrary(System.java:535)
05-29 09:47:58.000 E/AndroidRuntime( 9042): 	at de.cketti.safecontentresolver.Os.<clinit>(Os.java:21)
```

Looks like it's failing to find the native library that safe content resolver uses. 

What device are you using - maybe it's not running one the supported ABIs??

https://github.com/cketti/SafeContentResolver#native-code

**Comment by ShakurGit** [comment]
It's an old LG P990 also known as Optimus X2 Dual runnig stock ICS 4.0.4 rooted: I don't really know how to check if it's not running one the supported ABIs. To be honest I do not know what it is an ABIs, sorry I am completely ignorant in this regard

**Comment by cketti** [comment]
@ShakurGit: Please try uninstalling, then reinstalling.

Might be related to this: https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db

**Comment by ShakurGit** [comment]
just done, everything is not changed, same error. I've used F-Droid repository to reinstall

**Comment by ShakurGit** [comment]
Update: I tried other file manager and with "OI File Manager" from F-Driod there are no problems. I hope this information will be useful

**Comment by canary5** [comment]
I can confirm this. I have tried native file manage, amaze, es explorer. All crashing k9. The only old "OI" working.
Cm11, v5.010

**Comment by Paviluf** [comment]
I have this issue too. I use the default file manager from cyanogenmod.

Motorola razri (x86) CM11
[Logcat.txt](https://github.com/k9mail/k-9/files/367851/2016-07-17-15-26-02.txt)

**Comment by Paviluf** [comment]
Thanks !!!
