### ISSUE TITLE
Eating outgoing mail (in Android N)

### ISSUE THREAD

**Issue by bkph** [thunderbird/thunderbird-android#1408]
### Expected behaviour

mail should be sent, or an error message saying it cannot be sent
### Actual behaviour

mail is not sent, yet disappears from outgoing folder
### Steps to reproduce
1. install Android N
2. install K-9
3. send email
### Environment

K-9 Mail version: 5.010

Android version: Android N

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please record a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by aldeano** [comment]
I've got the same problem, and this is what the log says when i'm sendind an email:
`6-11 20:25:50.851 I/k9      (20486): Sending message with UID K9LOCAL:abe23503-f33c-44aa-bbd5-fa21881dc1c1
06-11 20:25:50.853 D/k9      (20486): SMTP >>> QUIT
06-11 20:25:54.487 D/k9      (20486): SMTP <<< 220 Openmailbox smtp server ready.
06-11 20:25:54.988 D/k9      (20486): SMTP >>> EHLO [10.156.70.195]
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-mail.openmailbox.org
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-PIPELINING
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-SIZE 4194304000
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-VRFY
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-ETRN
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-AUTH PLAIN LOGIN
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-AUTH=PLAIN LOGIN
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-ENHANCEDSTATUSCODES
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250-8BITMIME
06-11 20:25:55.464 D/k9      (20486): SMTP <<< 250 DSN
06-11 20:25:55.469 D/k9      (20486): Tried to parse 4194304000 and get an int
06-11 20:25:55.469 D/k9      (20486): java.lang.NumberFormatException: Invalid int: "4194304000"
06-11 20:25:55.469 D/k9      (20486): 	at java.lang.Integer.invalidInt(Integer.java:138)
06-11 20:25:55.469 D/k9      (20486): 	at java.lang.Integer.parse(Integer.java:413)
06-11 20:25:55.469 D/k9      (20486): 	at java.lang.Integer.parseInt(Integer.java:367)
06-11 20:25:55.469 D/k9      (20486): 	at java.lang.Integer.parseInt(Integer.java:334)
06-11 20:25:55.469 D/k9      (20486): 	at com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:319)
06-11 20:25:55.469 D/k9      (20486): 	at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:504)
06-11 20:25:55.469 D/k9      (20486): 	at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:495)
06-11 20:25:55.469 D/k9      (20486): 	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3563)
06-11 20:25:55.469 D/k9      (20486): 	at com.fsck.k9.controller.MessagingController$20.run(MessagingController.java:3314)
06-11 20:25:55.469 D/k9      (20486): 	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
06-11 20:25:55.469 D/k9      (20486): 	at java.lang.Thread.run(Thread.java:818)
06-11 20:25:55.470 D/k9      (20486): SMTP >>> *sensitive*
06-11 20:25:56.087 D/k9      (20486): SMTP <<< 235 2.7.0 Authentication successful
06-11 20:25:56.087 D/k9      (20486): SMTP >>> MAIL FROM:<email.accountA@openmailbox.org> BODY=8BITMIME
06-11 20:25:56.417 D/k9      (20486): SMTP <<< 250 2.1.0 Ok
06-11 20:25:56.417 D/k9      (20486): SMTP >>> RCPT TO:<email.accountB@gmail.com>
06-11 20:25:57.047 D/k9      (20486): SMTP <<< 250 2.1.5 Ok
06-11 20:25:57.047 D/k9      (20486): SMTP >>> DATA
06-11 20:25:57.371 D/k9      (20486): SMTP <<< 354 End data with <CR><LF>.<CR><LF>
06-11 20:25:57.377 D/k9      (20486): SMTP >>> 

06-11 20:25:57.377 D/k9      (20486): .
06-11 20:25:59.608 D/k9      (20486): SMTP <<< 250 2.0.0 Ok: queued as 7A0F92096E9
06-11 20:25:59.608 D/k9      (20486): SMTP >>> QUIT
06-11 20:25:59.927 D/k9      (20486): SMTP <<< 221 2.0.0 Bye
06-11 20:25:59.940 V/k9      (20486): LockableDatabase: Transaction ended, took 11ms / com.fsck.k9.mail.store.LocalStore$LocalMessage.setFlag(LocalStore.java:3733)
06-11 20:25:59.948 V/k9      (20486): LockableDatabase: Transaction ended, took 6ms / com.fsck.k9.mail.store.LocalStore$LocalMessage.setFlag(LocalStore.java:3733)
06-11 20:25:59.950 I/k9      (20486): Moving sent message to folder 'Sent' (-1) 
06-11 20:25:59.952 D/k9      (20486): Updating folder_id to 15 for message with UID K9LOCAL:abe23503-f33c-44aa-bbd5-fa21881dc1c1, id 708 currently in folder K9MAIL_INTERNAL_OUTBOX
06-11 20:26:00.056 I/k9      (20486): Moved sent message to folder 'Sent' (15) 
06-11 20:26:00.096 V/k9      (20486): LockableDatabase: Transaction ended, took 26ms / com.fsck.k9.mail.store.LocalStore$LocalMessage.destroy(LocalStore.java:3832)
06-11 20:26:00.098 I/k9      (20486): Background Command 'sendPendingMessages' completed
06-11 20:26:00.098 I/k9      (20486): Running Background command 'processPendingCommands', seq = 36
06-11 20:26:00.099 D/k9      (20486): Processing pending command 'com.fsck.k9.MessagingController.append: , Sent, K9LOCAL:883f2a24-110a-4460-b7dc-0490ea153b46'
06-11 20:26:00.102 V/k9      (20486): conn45990039>>> 9 NOOP

06-11 20:26:07.300 D/k9      (20486): Decoding identity: !l=0&o=150&fo=1299&pl=0&po=0&qs=HEADER&f=HTML&s=--%20%0D%0ASent%20from%20my%20Android%20device%20with%20K-9%20Mail.%20Please%20excuse%20my%20brevity.&m=!%3ANDljMGIwNDgtZWFiMy00OTJjLTliOGMtYzU5YWU5NzBlNTY5%3ARW52aWFkb3M%3D%3AMw%3D%3D%3AFORWARDED&p=0&q=SHOW
06-11 20:26:07.301 D/k9      (20486): Decoded identity: {QUOTED_TEXT_MODE=SHOW, CURSOR_POSITION=0, OFFSET=150, PLAIN_OFFSET=0, SIGNATURE=-- 

06-11 20:26:07.301 D/k9      (20486): Sent from my Android device with K-9 Mail. Please excuse my brevity., MESSAGE_FORMAT=HTML, QUOTE_STYLE=HEADER, FOOTER_OFFSET=1299, LENGTH=0, ORIGINAL_MESSAGE=!:NDljMGIwNDgtZWFiMy00OTJjLTliOGMtYzU5YWU5NzBlNTY5:RW52aWFkb3M=:Mw==:FORWARDED, PLAIN_LENGTH=0}
06-11 20:26:07.301 D/k9      (20486): Thawed MessageReference{accountUuid='49c0b048-eab3-492c-9b8c-c59ae970e569', folderName='Sent', uid='3', flag=FORWARDED}
06-11 20:26:07.307 D/k9      (20486): Loading message with offset 150, length 0. Text length is 1306.
06-11 20:26:07.345 D/k9      (20486): Loading message with offset 0, length 0. Text length is 828.
06-11 20:26:07.418 V/k9      (20486): LockableDatabase: Transaction ended, took 278ms / com.fsck.k9.mail.store.LocalStore.doBatchSetSelection(LocalStore.java:4298)
06-11 20:26:07.428 V/k9      (20486): LockableDatabase: Transaction ended, took 0ms / com.fsck.k9.mail.store.LocalStore.doBatchSetSelection(LocalStore.java:4298)
06-11 20:26:07.457 V/k9      (20486): old attachment.size: 1131489
06-11 20:26:07.457 V/k9      (20486): new attachment.size: 1131489
06-11 20:26:07.471 V/k9      (20486): old attachment.size: 1226252
06-11 20:26:07.471 V/k9      (20486): new attachment.size: 1226252
06-11 20:26:07.486 V/k9      (20486): Saving attachment to /data/user/0/com.fsck.k9/cache/attachment-1124680461.tmp
06-11 20:26:07.486 V/k9      (20486): Saving attachment to /data/user/0/com.fsck.k9/cache/attachment-647012807.tmp
06-11 20:26:13.455 D/k9      (20486): Decoding identity: !l=0&o=150&fo=1299&pl=0&po=0&qs=HEADER&f=HTML&s=--%20%0D%0ASent%20from%20my%20Android%20device%20with%20K-9%20Mail.%20Please%20excuse%20my%20brevity.&m=!%3ANDljMGIwNDgtZWFiMy00OTJjLTliOGMtYzU5YWU5NzBlNTY5%3ARW52aWFkb3M%3D%3AMw%3D%3D%3AFORWARDED&p=0&q=SHOW
06-11 20:26:13.455 D/k9      (20486): Decoded identity: {QUOTED_TEXT_MODE=SHOW, CURSOR_POSITION=0, OFFSET=150, PLAIN_OFFSET=0, SIGNATURE=-- 

06-11 20:26:13.455 D/k9      (20486): Sent from my Android device with K-9 Mail. Please excuse my brevity., MESSAGE_FORMAT=HTML, QUOTE_STYLE=HEADER, FOOTER_OFFSET=1299, LENGTH=0, ORIGINAL_MESSAGE=!:NDljMGIwNDgtZWFiMy00OTJjLTliOGMtYzU5YWU5NzBlNTY5:RW52aWFkb3M=:Mw==:FORWARDED, PLAIN_LENGTH=0}
06-11 20:26:13.455 D/k9      (20486): Thawed MessageReference{accountUuid='49c0b048-eab3-492c-9b8c-c59ae970e569', folderName='Sent', uid='3', flag=FORWARDED}
06-11 20:26:13.459 D/k9      (20486): Loading message with offset 150, length 0. Text length is 1306.
06-11 20:26:13.467 D/k9      (20486): Loading message with offset 0, length 0. Text length is 828.
06-11 20:26:13.505 V/k9      (20486): old attachment.size: 1226252
06-11 20:26:13.505 V/k9      (20486): new attachment.size: 1226252
06-11 20:26:13.512 V/k9      (20486): old attachment.size: 1131489
06-11 20:26:13.512 V/k9      (20486): new attachment.size: 1131489
06-11 20:26:13.537 V/k9      (20486): Saving attachment to /data/user/0/com.fsck.k9/cache/attachment-284166987.tmp
06-11 20:26:13.543 V/k9      (20486): Saving attachment to /data/user/0/com.fsck.k9/cache/attachment-903729385.tmp
06-11 20:26:23.721 D/k9      (20486): MessageView displaying message MessageReference{accountUuid='49c0b048-eab3-492c-9b8c-c59ae970e569', folderName='K9mail-errors', uid='K9LOCAL:73056452-66ea-4071-b170-0b8555b5dd5f', flag=null}
06-11 20:26:23.753 V/k9      (20486): LockableDatabase: Transaction ended, took 16ms / com.fsck.k9.mail.store.LocalStore.doBatchSetSelection(LocalStore.java:4298)
06-11 20:26:23.761 V/k9      (20486): LockableDatabase: Transaction ended, took 4ms / com.fsck.k9.mail.store.LocalStore.doBatchSetSelection(LocalStore.java:4298)
06-11 20:26:23.761 D/k9      (20486): No external images.`

Like bkph says, the mail isn't sent and there's no error message.

**Comment by cketti** [comment]
@aldeano: Looks like the email was properly delivered to the SMTP server. If your provider is not sending the email or reporting an error, that's a bug on their side.

**Comment by philipwhiuk** [comment]
```
06-11 20:25:55.469 D/k9 (20486): Tried to parse 4194304000 and get an int
06-11 20:25:55.469 D/k9 (20486): java.lang.NumberFormatException: Invalid int: "4194304000"
06-11 20:25:55.469 D/k9 (20486): at java.lang.Integer.invalidInt(Integer.java:138)
06-11 20:25:55.469 D/k9 (20486): at java.lang.Integer.parse(Integer.java:413)
06-11 20:25:55.469 D/k9 (20486): at java.lang.Integer.parseInt(Integer.java:367)
06-11 20:25:55.469 D/k9 (20486): at java.lang.Integer.parseInt(Integer.java:334)
06-11 20:25:55.469 D/k9 (20486): at com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:319)
06-11 20:25:55.469 D/k9 (20486): at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:504)
06-11 20:25:55.469 D/k9 (20486): at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:495)
06-11 20:25:55.469 D/k9 (20486): at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3563)
06-11 20:25:55.469 D/k9 (20486): at com.fsck.k9.controller.MessagingController$20.run(MessagingController.java:3314)
06-11 20:25:55.469 D/k9 (20486): at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
06-11 20:25:55.469 D/k9 (20486): at java.lang.Thread.run(Thread.java:818)
```

We should probably fix this though. I guess we have to switch to BigDecimal or something?

**Comment by cketti** [comment]
It's not like we currently support creating messages of that size. The fallback of ignoring the value seems appropriate here.

**Comment by aldeano** [comment]
I've rechecked and it was a problem with the spam filter, so for me this isn't a bug, K9 works perfectly. Sorry for the inconveniences!

**Comment by bkph** [comment]
While frustrating the three times that it occurred, I has not happened again more recently. 
May have been an Android N issue that got fixed through upgrades to the system. 
Thanks.
