### ISSUE TITLE
Leading signature enters are not converted to "<br>" in HTML message, so they are stripped!

### ISSUE THREAD

**Issue by ghsrcgh** [thunderbird/thunderbird-android#1431]
### Expected behaviour

When I configure my signature, I may write a few enters from beginning (leading enters). For example:
" 

My Signature" (without quotes).

In the settings editor it shows as written above (i.e. enters are shown).
### Actual behaviour

But after mail composing and sending... leading enters will be stripped in any browser/viewer/mail-browser. Leading signature enters are not converted to "&lt;br&gt;" in HTML message, so they are stripped!
### Steps to reproduce
1. Create signature with one, two or more leading enters.
2. Try to create and send an HTML message with such signature.
3. Receive such message and see what you really got.
### Environment

K-9 Mail version: 5.0.10

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by cketti** [comment]
This is probably the same issue as #1430
