### ISSUE TITLE
crash when trying to create new mail (marshmallow)

### ISSUE THREAD

**Issue by kerlerm** [thunderbird/thunderbird-android#1434]
### Expected behaviour

I would expect to see the "new mail" dialogue.
### Actual behaviour

The app crashes.
### Steps to reproduce
1. start k-9 mail
2. select new mail icon
3. crash
### Environment

K-9 Mail version: 5.109

Android version: Android 6.0 marshmallow, huawei style (EMUI)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
### Thoughts on this:

Could this result from a permission problem? K-9 requests access rights for "contacts" and "storage", which are granted. Four additional permissions show up in a subfolder (read email attachments, read emails, delete emails, k-9 remote control). Everytime I manually grant those, the slider is back to "off" when I revisit this tab...

Does k-9 fail in requesting those rights at installation time?
### logcat: generated as described in HOWTO:

```
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--------- beginning of main
06-05 11:30:42.296 I/k9      ( 3371): Committing preference changes
06-05 11:30:42.358 I/k9      ( 3371): Preferences commit took 62ms
06-05 11:30:46.704 I/k9      ( 4596): Loading preferences from DB into Storage
06-05 11:30:46.723 I/k9      ( 4596): Preferences load took 19ms
06-05 11:30:46.768 I/k9      ( 4596): Registered: unmount receiver
06-05 11:30:46.771 I/k9      ( 4596): Registered: shutdown receiver
06-05 11:31:05.784 I/k9      ( 4596): Committing preference changes
06-05 11:31:05.794 I/k9      ( 4596): Preferences commit took 10ms
06-05 11:31:08.781 I/k9      ( 4690): Loading preferences from DB into Storage
06-05 11:31:08.798 I/k9      ( 4690): Preferences load took 17ms
06-05 11:31:08.837 I/k9      ( 4690): Registered: unmount receiver
06-05 11:31:08.839 I/k9      ( 4690): Registered: shutdown receiver
06-05 11:31:16.667 I/k9      ( 4690): Committing preference changes
06-05 11:31:16.710 I/k9      ( 4690): Preferences commit took 43ms
```

**Comment by kerlerm** [comment]
Seems to be similar problem as reported here: issue #1112 and #1627

**Comment by philipwhiuk** [comment]
The log you provided shows the preference changes but not the actual crash.

Are you running a rooted version of Android which modifies the UI (as cketti asks in #1112 ).

What phone is this - ideally it'd be nice to be able to emulate this version of Android...

**Comment by kerlerm** [comment]
Unfortunately this is not a rooted device, but a Huawei P8 lite (model number ALE-L21) running the EMUI 4.0 Android 6 (build ALE-L21C432B574). Any chance to get a useful logcat out of this phone?

**Comment by kerlerm** [comment]
I finally got an exception out of this huawei device.

**Comment by kerlerm** [comment]
[k9-crash_new_message.log](https://github.com/k9mail/k-9/files/1385006/k9-crash_new_message.log)

**Comment by kerlerm** [comment]
Bug is still present in version 5.208

**Comment by cketti** [comment]
A couple of app components are disabled by default. That's so K-9 Mail e.g. doesn't show up in the Share dialog when no accounts have been set up.
It looks like the mechanism to enable those components doesn't properly work on your device. Given that it works for almost everyone I'd say it's likely this is a bug in the Android version on your device.

**Comment by kerlerm** [comment]
You are right. I updated to latest Andriod EMUI, removed and reinstalled k9 and it works now.
