### ISSUE TITLE
Previously read messages are re-syncing as unread after deleting another email.

### ISSUE THREAD

**Issue by arday** [thunderbird/thunderbird-android#1454]
I have an email account synced to K-9 with POP3, and with setting 'Local folder size=100 messages'.   The Inbox is sorted by date, with newest at the top.   I'm not using the Unified Inbox.

When I delete an email or emails, it/they disappears from K-9 account's Inbox.   There are then less than 100 emails in the Inbox.  
On the next sync, K-9 realizes that there are less than 100 emails, and downloads older email(s), previously read and removed from the inbox because of the 100 messages limit, to add to the bottom of the list to bring the number of emails back to 100 messages.
### Expected behaviour

I can think of two possible solutions:

Option 1: these older emails, previously synced and removed because of the 100 message limit, and now re-synced because there is now less than 100 messages, need to be set to the same Read/Unread status as before being removed.   

Option 2: K-9 should recognize that these older emails have been previously removed because of the 100 message limit, and so accept that there should be less than 100 messages rather than re-sync these old emails.   Obviously, any newer emails should to be synced. 

Thinking about this, option 1 would fit in better if it were to also apply when requesting to "Load up to 100 more".
### Actual behaviour

What happens now is these older emails, previously synced and removed because of the 100 message limit, and now re-synced because there was less than 100 messages, are marked as "Unread".    
### Steps to reproduce
1.  Setup an email account using POP3, and also set  Local folder size=100 messages under account settings > Fetching mail.  Set sorting by date, with newest at the top.
2.  after first sync, "Mark all as read" (or at least mark the older emails at the bottom of the list as read).   Check that there are now 100 emails in the Inbox.
3.  send (from another account) one or more emails to this account, and sync K-9 so they appear in the Inbox.   Check the bottom of the Inbox to see that the oldest email(s) (ie those > 100) have now been removed from the Inbox.
4.  delete one or more emails from the Inbox and re-sync (assuming that no more new emails are received)
5.  Notice that the count of Unread emails has increased.   Check the bottom of the Inbox to see emails, previously read and then removed because of the 100 message limit, are now re-synced and are marked as "Unread".  
### Environment

K-9 Mail version:  5.010 

Android version:  6.0.1       security patch level:  1 May 2016

Account type (IMAP, POP3, WebDAV/Exchange):  POP3

**Comment by cketti** [comment]
Obsolete because of #4974
