### ISSUE TITLE
Unable to use gmail account - IOException: readStringUnti

### ISSUE THREAD

**Issue by andrixnet** [thunderbird/thunderbird-android#1455]
### Expected behaviour

I've got K9 on several Android devices, all with the same accounts.
On one device, Allview P5Quad, running Android 4.2.1; K9 5.010 I have the following problem: 

I have 2 gmail accounts (via IMAP). One of them fails to update INBOX (load new messages, update read status, update deleted  on server, etc)
Once recreating data restored it into working order. However the problem reappeared and was unable to fix it. 
The problem happens with all folders, not just INBOX.
The problem happens with one account, not the second.
The problem happens on one device, not on 2 other (same K9, different versions of Android, both older and newer)
- one gmail account does not work.
- clearing data does not help
- recreating data does not help
- exporting settings; removing account; importing settings - does not help
- removing account; manually creating the account - does not help (using detected settings for GMail)
- device is rooted, but I've been unable to create/obtain logs with aLogCat or CatLog.

**Comment by cketti** [comment]
Without a debug log there's nothing we can do. Try connecting the device to your computer and use `adb` to get the log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by andrixnet** [comment]
I am still trying to get debug info from it. Meanwhile I can report that it got some mail, but that was intermittent functioning only.

**Comment by andrixnet** [comment]
`java.io.IOException: readStringUntil(): end of stream reached`

Debug log obtained with `adb` attached:
[k9-log.txt](https://github.com/k9mail/k-9/files/969592/k9-log.txt)

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with the current K-9 Mail version.
