### ISSUE TITLE
[Bug: Regression] Upgrading from K-9 Mail 5.008 to 5.010 breaks its Share functionality under AlienDalvik (AOSP 4.1.2): K-9 always crashes

### ISSUE THREAD

**Issue by Olf0** [thunderbird/thunderbird-android#1473]
Upgrading from K-9 Mail 5.008 to 5.010 breaks its Share functionality when attaching a file to an email under AlienDalvik (based on AOSP 4.1.2) in Jolla's SailfishOS 2.0.1.11 
K-9 always crashes, a pop up window is displayed stating, "Unfortunately the application com.fsck.k9 has stopped. [OK]". By clicking on [OK], K-9 restarts, and saves the message in the Drafts folder, but without the file being attached. 

I checked the following: 
- Using the Share functionality between other applications works: I tested between Amaze, OpenKeychain, TurboEditor and a few native SailfishOS applications.  
- Using the Share functionality in other Android applications in order to send a file to K-9 Mail always crashes K-9 in exactly the same way (as described above), no matter if K-9 was running or not. 
- Sharing data (not a file) does not crash K-9 Mail, but seems to exhibit another bug: a handle (?) is inserted into the mail body, not the data sent, e.g. with data sent from BarcodeScanner: 
  [Subject] Barcode Scanner - Plain text
  [Body] market://details?id=com.fsck.k9
  I will file a separate bug report, when sufficiently tested to write up something more comprehensive.
- It also makes no difference, which Android application is picked, when using the Share functionality from within K-9 Mail for attaching a file to an email: K-9 always crashes.  Tested with Amaze file manager and TurboEditor.  
- Only when I pick SailfishOS' native Gallery application (which is the third application offered besides Amaze and TurboEditor when attaching a file in K-9 Mail on my Jolla Phone), K-9 does not crash and the file is indeed attached.  But it is not Android's internal Share mechanism being used here, instead the still somewhat fragile Share functionality between Android and SailfishOS applications provided by Jolla's SailfishOS 2 is utilised.  In this specific case (attaching a file to an email in K-9) it even works consistently stable, but unfortunately SailfishOS' native Gallery app allows to select picture file formats (e.g. jpg, png), only. 
- After downgrading from K-9 Mail 5.010 to 5.008, the Share functionality works fine, again. 

I am sure willing to make further tests, checks and balances, when provided with instructions how to. 
Please do try to fix that, as the inability to attach arbitrary files to emails in K-9 Mail renders the beautiful and feature laden K-9 useless as a generic email client. 

Cheers and Kudos for maintaining and enhancing the best mobile email client I am aware of.  And I am really looking forward to the progress on PGP/MIME. 

P.S.: I suspect the MIME handling changes introduced in K-9 Mail 5.009 to be the cause.  From K-9's changelog on https://k9mail.github.io/k-9/changelog_5.0-MAINT_branch.xml: 

5.010
[...]
5.009
[...]
Improved MIME type handling when other apps share files to K-9 Mail
[...]

**Comment by Valodim** [comment]
can you try it this behaviour changed with the latest alpha? there have been a lot of changes all over the place since the latest stable, and this doesn't seem like a bug worth backporting

**Comment by cketti** [comment]
This might be caused by the introduction of SafeContentResolver.
If the app crashes, a stack trace should be logged somewhere. Please provide that.

**Comment by Olf0** [comment]
@Valodim:
- I obtain K-9 Mail from the F-Droid repository.  The latest version offered there is 5.010, alpha and beta versions do not seem to be uploaded there. 
Do you mean to address the most recent master / unstable / development release (currently K-9 Mail v5.109 (alpha)) in <https://github.com/k9mail/k-9/releases> with, "the latest alpha"?
- Depending on how long you plan to maintain the K-9 5.0xx current / stable / maintenance branch, it may be unfortunate not to fix it in this branch as well. 
- Anyway, I am sure willing to test a K-9 5.1xx (alpha), if necessary: Will I be able to downgrade from a recent K-9 5.1xx to 5.008 flawlessly?  Or do I have to expect configuration breakage etc., when doing so?

@cketti:
I am not at all an Android expert.  Can you please provide a bit more concise description, where I may find that "stack trace [which] should be logged somewhere.", and  a hint, what file name (components) I shall be looking for.

**Comment by Olf0** [comment]
@cketti:
Well, I found <http://android.stackexchange.com/a/27892>, so I did: 
<code>
[root@Jolla nemo]# find / -name 'tombstone*'
find: /proc/10560: No such file or directory
/opt/alien/data/tombstones
/opt/alien/data/tombstones/tombstone_00
/opt/alien/data/tombstones/tombstone_01
/opt/alien/data/tombstones/tombstone_02
/opt/alien/data/tombstones/tombstone_03
/opt/alien/data/tombstones/tombstone_04
/opt/alien/data/tombstones/tombstone_05
/opt/alien/data/tombstones/tombstone_06
/opt/alien/data/tombstones/tombstone_07
/opt/alien/data/tombstones/tombstone_08
/opt/alien/data/tombstones/tombstone_09
/data/tombstones
/data/tombstones/tombstone_00
/data/tombstones/tombstone_01
/data/tombstones/tombstone_02
/data/tombstones/tombstone_03
/data/tombstones/tombstone_04
/data/tombstones/tombstone_05
/data/tombstones/tombstone_06
/data/tombstones/tombstone_07
/data/tombstones/tombstone_08
/data/tombstones/tombstone_09
/tombstones
[root@Jolla nemo]#
</code>
Those three directories contain the same files (supposedly as SailfishOS loves bindmounts; did not research that any further):
<code>
[root@Jolla nemo]# ls -la /data/tombstones/
total 1676
drwxrwx--x 1 system system    284 2015-12-20 17:49 .
drwxrwx--x 1 system system    458 2016-06-25 15:31 ..
drwxrwx--x 1 system system      0 2015-05-25 18:40 dsps
drwxrwx--x 1 system system      0 2015-05-25 18:40 lpass
drwxrwx--x 1 system system      0 2015-05-25 18:40 mdm
drwxrwx--x 1 system system      0 2015-05-25 18:40 modem
-rw------- 1 system system 227222 2016-05-28 21:21 tombstone_00
-rw------- 1 system system      0 2015-12-20 17:50 tombstone_01
-rw------- 1 system system 201557 2016-01-08 15:49 tombstone_02
-rw------- 1 system system 362660 2016-01-20 21:54 tombstone_03
-rw------- 1 system system 213583 2016-02-04 02:13 tombstone_04
-rw------- 1 system system 146031 2016-05-24 00:14 tombstone_05
-rw------- 1 system system 132933 2016-05-24 00:14 tombstone_06
-rw------- 1 system system 136861 2016-05-24 00:16 tombstone_07
-rw------- 1 system system      0 2015-12-20 17:49 tombstone_08
-rw------- 1 system system 275665 2016-01-07 22:35 tombstone_09
drwxrwx--x 1 system system      0 2015-05-25 18:40 wcnss
[root@Jolla nemo]#
</code>
None of the <code>tomstone_</code><em>nn</em> files are from June 2016!?! 
Any ideas?

**Comment by cketti** [comment]
The instructions for Android can be found here: https://github.com/k9mail/k-9/wiki/LoggingErrors
You have to figure out on your own how to get the same information on SailfishOS.

**Comment by Olf0** [comment]
O.K, it took me a while to comprehend local logging (via aLogcat root / Ghost Log / Catlog) and that one simply picks the tombstone file, whose timestamp correlates with an crash  (right?).
