### ISSUE TITLE
DiskFull problem when saving attached file is not taken into account 

### ISSUE THREAD

**Issue by liar666** [thunderbird/thunderbird-android#1476]
### Expected behavior

Tell us what should happen
1. be in an email with attached file
2. ask to saved attached file
3. having no more space on the sd card

K9 should warn that the file could not be saved
### Actual behavior

Tell us what happens instead

K9 just creates an empty file!
### Environment

K-9 Mail version:
Probably latest... I don't see any entry in any K9 menus to get this information...

OK found it in Android's menus: 5.01, but remark above still relevant: this info should be easily accessible from _within_ K9 

Android version: 4.4.2

**Comment by GoneUp** [comment]
Looks file the pr fixed the issue, I think this can be closed also.
