### ISSUE TITLE
"To" field does not convert typed email addresses to tokens on send

### ISSUE THREAD

**Issue by dschuermann** [thunderbird/thunderbird-android#1495]
### Expected behavior

Autocomplete address field "To" should convert typed email addresses to tokens when clicking send
### Actual behavior

It does not, shows "Recipient field contains incomplete input!"
### Steps to reproduce
1. compose mail
2. write body subject and in the last step write email address into "To" field without selecting an email address from the dropdown
3. click send
### Environment

K-9 Mail version: 5.110

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by fexofenadine** [comment]
this is happening again in the thunderbird 11.0b1 beta

**Comment by kewisch** [comment]
The 'Recipient field contains incomplete input' issue was fixed in #9113. Please test again on daily builds or the upcoming 11.0b2.
