### ISSUE TITLE
Webdav (Exchange) sending email is broken since v5.109 (alpha)

### ISSUE THREAD

**Issue by markusb68** [thunderbird/thunderbird-android#1500]
Android version: 6.01

Using K-9 Mail v5.010 (stable) i could send emails using my old WEBDAV account.
But never delete emails on the server.
Then Updated to K-9 Mail v5.109 (alpha) / and also to K-9 Mail v5.110 (alpha).
Now I can delete emails on the server, but I can not send emails any more.
They end up on the outgoing folder.
Sorry I can't tell you the error message. The message text is too long so it's truncated...

Then Downgraded (titanium Backup / also the database) and sending emails is working again.

**Comment by philipwhiuk** [comment]
> Sorry I can't tell you the error message. The message text is too long so it's truncated...

The error should be in K9mail-errors.

Without even a partial error trace this will be impossible to fix :(

**Comment by markusb68** [comment]
Sorry,

you could make a diff and see what has been changed from v5.010 to v5.109
I went back to v5.110 and made a screenshot.
besides it tells me that the host can't be resolved the host IS correct.
I can receive mails and haven't changed the host at all.
K9mail-errors is empty. see 2nd screenshot.

Setting the incoming server does close the dialog without an error.
Trying to set the outgoing server doesn't open the dialog at all.
I could also send the mails using SMTP, but K9 won't let me configure SMTP for a WEBDAV account.

![screenshot_20160714-175649](https://cloud.githubusercontent.com/assets/20417704/16846719/d20acd68-49ed-11e6-8f4f-4a76e3e15c29.jpg)
![screenshot_20160714-175735](https://cloud.githubusercontent.com/assets/20417704/16846720/d213b0e0-49ed-11e6-887e-8a2cd538791f.jpg)

**Comment by philipwhiuk** [comment]
> Sorry, I thought you could easily make a diff and see what has been changed from v5.010 to v5.109

We can but your original error was so vague. 5.110 did work for my email server (we've moved to Exchange recently).

The app won't be throwing an UnknownHost unless it actually can't resolve the hostname.... So I'm unsure quite what is going on here right now.

**Comment by markusb68** [comment]
so what can I do to help finding?

**Comment by markusb68** [comment]
Hope this helps....

**Comment by cketti** [comment]
@philipwhiuk That looks like the code is using a local UID (K9LOCAL…) when trying to access a message in the server's Drafts folder. The issue is probably not the WebDAV code but something that hands a local message UID to a remote store.

**Comment by markusb68** [comment]
What can I do to help you to fix this bug?

**Comment by philipwhiuk** [comment]
Hmm, no it is a WebDav store bug:

It's taking a List<? extends Message> and calling message.getUid()

I guess I'll look how IMAP handles this.

**Comment by markusb68** [comment]
Still now working in K-9 Mail v5.204:
![screenshot_20170224-133307](https://cloud.githubusercontent.com/assets/20417704/23306243/ebeaa1f2-faa2-11e6-92fb-686d5adeec65.png)

The last version I could SEND emails with is 5.010.
All later Versions broke WEBDAV-Exchange Email sending.

Can't you just check what has been changed since 5.010 in that part of code and roll it back ?

Is it possible to use SMTP for sending emails?
The (sending) Server Settings don't open in the DEVDAV account.
