### ISSUE TITLE
Cannot Paste into "To" field

### ISSUE THREAD

**Issue by dschuermann** [thunderbird/thunderbird-android#1504]
### Expected behavior

Paste context dialog should come up when long clicking into "to" field.
### Actual behavior

Nothing happens
### Steps to reproduce
1. Long click into "to" field
### Environment

K-9 Mail version: 5.110

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by webratte** [comment]
It seems it's related to:
App crashed by typing address in the address field when composing a message #1251

**Comment by Valodim** [comment]
This is an upstream issue of TokenAutoComplete, see https://github.com/splitwise/TokenAutoComplete/issues/95. I'll run some tests to see what happens if I just `setLongClickable(true)`

**Comment by Valodim** [comment]
I reenabled long click in #1520, since it works "good enough". There may be some quirks left (see link above), but the common use case of pasting a single email address is fixed. Will get back to this at some point.
