### ISSUE TITLE
Regression: With Office 365, read messages become unread upon next sync

### ISSUE THREAD

**Issue by twildfarmer** [thunderbird/thunderbird-android#1505]
### Expected behavior

When configured to use IMAP with Office 365, if I read a message in k-9 mail or mark it as read:
- It should stay "read"
- It should show as "read" in my other email clients.
### Actual behavior

The message stays "read" until it syncs again, after which it becomes unread again.
- This is a regression. It used to work perfectly. 
- Changed in the last week or so.
- My Thunderbird client does not exhibit this behavior for the same account.
- My other, non-Office-365, IMAP accounts do not exhibit this behavior in k-9 mail.
### Steps to reproduce
1. Configure k-9 mail as directed under MS Outlook Office 365 Options:Mail:Accounts page:
   
   **IMAP**
   Server name: outlook.office365.com
   Port: 993
   Encryption method: SSL (Using SSL/TLS)
   
   **SMTP**
   Server name: smtp.office365.com
   Port: 587
   Encryption method: TLS (Using STARTTLS)
2. Read an email message (with k-9 configuration set to mark viewed emails as read)
3. Close message - Message appears greyed (read)
4. Re-sync with Office 365
5. Message appears white (unread)
### Environment

K-9 Mail version: 5.010
Battery optimization is disabled for k-9 mail

Android Version: 6.0

Security patch level: May 1, 2016

Configuration version: L14.MOT.XT1585.0

Kernel version: 
3.10.84-perf-g4efa46e
hudsoncm@ilclbld85 #1
Tue Jun 21 12:05:08 CDT 2016

System version:
24.14.16.kinzie_verizon.verizon.en.US

Build number: MCK24.78-13.16

Hardware:
Verizon DROID Turbo2
**Software updated to 24.14.16.en.US
Applied - July 01, 2016 at 13:51   <----------------??**

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please provide a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by twildfarmer** [comment]
[k9-log.txt](https://github.com/k9mail/k-9/files/369890/k9-log.txt)

**Comment by twildfarmer** [comment]
Any word on this?

**Comment by twildfarmer** [comment]
Based on something I saw in the logs, I decided to remove the account from k9mail and that seems to have fixed it.
