### ISSUE TITLE
Unable to View Messages

### ISSUE THREAD

**Issue by geekalert** [thunderbird/thunderbird-android#1507]
### Expected behavior

When I tap on a message, I should be able to read that message. 
### Actual behavior

The message opens, but the message contents are missing. 
### Steps to reproduce
1. Tap on Google email message.
2. Message opens. 
3. There is no message.
4. Rinse and repeat for each Google email account.
5. Try uninstalling and reinstalling. No change.
### Environment

K-9 Mail version: 5.110

Android version: 5.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please attach the source of the message that doesn't show and/or record a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors
