### ISSUE TITLE
No Subject/No Text

### ISSUE THREAD

**Issue by DoobDawg** [thunderbird/thunderbird-android#1541]
### Expected behavior

Tell us what should happen

I expect email to properly sync or at the least fix themselves after a new sync.
### Actual behavior

Tell us what happens instead

Today is the first time in a while it's happened, but I ended up with 4 emails in one screenshot getting this error.  They are real emails on the server side I can see fine.  This problem is only corrected by deleting the real emails and then syncing in k-9 to get rid of them.  I can't find a way to get the actual email to sync up.
### Steps to reproduce
1.  Just manual syncing and checking emails since I don't push/force sync.
   2.
   3.
### Environment

K-9 Mail version:

5.010

Android version:

5.0

Account type (IMAP, POP3, WebDAV/Exchange):

IMAP - yahoo

![screenshot_2016-08-03-13-13-16](https://cloud.githubusercontent.com/assets/15825729/17375079/8c498ff4-597d-11e6-93e2-ed9fb4ea9c4a.jpg)

I just enabled debug logging.  When it happens again I'll update with the log.

**Comment by cketti** [comment]
Can you please provide the message source of such an email?

**Comment by DoobDawg** [comment]
Are you asking where the emails are coming from or the actual details of the emails?  Just had it happen to two again today so I'd be able to do either.  It's happened to varied emails, no real connection.  This time I deleted these emails in K9 but instead of deleting and disappearing, they turned to this no Subject/no text issue

**Comment by philipwhiuk** [comment]
Closing this as we've fixed lots of cases like this since August. If this is still happening, open a new issue, providing the raw message source (ie. the message headers and contents) as well as the usual version of K-9 etc.
