### ISSUE TITLE
Quick double-tap on Font size settings' sub-items leads to UI inconsistency

### ISSUE THREAD

**Issue by wwp** [thunderbird/thunderbird-android#1543]
Double tapping an entry which has subentry in the settings entry should not do anything but what single tapping does. It may not even be allowed.

Currently, doing a quick double tapping on some of the settings show an unexpected behaviour of the UI.

Steps to reproduce:
- Open K-9, enter the global settings. Go in the Display / Font size menu.
- Super-quickly double-tap on Account list or another item in this list. See it's then displayed flickering?
- Now press Back. You're _not_ back to the Font size but you see an empty list.
- Back again and you reach the expected Font size menu.

K-9 Mail version: 5.010

Android version: Marshmallow 6.0.1 on a Samsung Galaxy A3 2016.

**Comment by cketti** [comment]
No longer an issue in `master`.
