### ISSUE TITLE
Wrong SMTP server when sending mail

### ISSUE THREAD

**Issue by jomo** [thunderbird/thunderbird-android#1547]
### Expected behavior

k9 should use the SMTP server of the associated account.
### Actual behavior

k9 uses the SMTP server of a different account.
### Steps to reproduce

Unfortunately I'm not exactly sure how to reproduce this.

I have multiple accounts configured in k9. For the sake of simplicity let's assume these are `default@example.com` and `other@example.net`. I composed a new mail and changed the sender from my default account to the other one at the top, wrote the body and pressed send. The sender address was now correctly set to my other account but k9 tried to deliver it using my default account's SMTP server. The mail couldn't be send.

I was able to grab logcat output when the mail was attempted to be re-sent.
Naturally, the SMTP server rejected a mail that's not coming from the associated sender address: 

```
Negative SMTP reply: 553 5.7.1 <other@example.net>: Sender address rejected: not owned by user default@example.com
```

Full trace:

```
I k9      : Committing preference changes
I k9      : Preferences commit took 10ms
E k9      : Failed to send message
E k9      : com.fsck.k9.mail.MessagingException: Unable to send message
E k9      :  at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:539)
E k9      :  at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:495)
E k9      :  at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3563)
E k9      :  at com.fsck.k9.controller.MessagingController$20.run(MessagingController.java:3314)
E k9      :  at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
E k9      :  at java.lang.Thread.run(Thread.java:818)
E k9      : Caused by: com.fsck.k9.mail.transport.SmtpTransport$NegativeSmtpReplyException: Negative SMTP reply: 553 5.7.1 <other@example.net>: Sender address rejected: not owned by user default@example.com
E k9      :  at com.fsck.k9.mail.transport.SmtpTransport.checkLine(SmtpTransport.java:649)
E k9      :  at com.fsck.k9.mail.transport.SmtpTransport.executeSimpleCommand(SmtpTransport.java:690)
E k9      :  at com.fsck.k9.mail.transport.SmtpTransport.executeSimpleCommand(SmtpTransport.java:654)
E k9      :  at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:524)
E k9      :  ... 5 more
```

I later found the mail in the 'Outbox' folder of my default account.
### Environment

K-9 Mail version: 5.010

Android version: 6.0.1, Cyanogenmod 13.0

Account type (IMAP, POP3, WebDAV/Exchange):
Both involved accounts use IMAP and SMTP.

**Comment by duncan-SF** [comment]
I'm seeing the same behavior with K-9 version 5.206 under Android 4.4.4 (Samsung/TMobile stock).

If I reach a message from the Universal Inbox, start a reply and then change the selected identity during composition, the message, when sent or saved, is sent to the server associated with the original identity but with the address from the chosen identity. 

This is always the wrong choice.  Mail is either rewritten by the server on the way through to reflect an identity I didn't choose (gmail's behavior) or passed through intact and then thrown away by the receiver for having come from a rogue mailhost.

**Comment by duncan-SF** [comment]
An example, step by step. 

In my contacts list I have some email addresses which allow email-to-sms to work through Google Voice. I chose one of those from the contact list today, changed the sender to match the Google account connected with the GV account, composed and sent the messsge.

K9 submitted the message using the wrong credentials and Google replied with a bounce messsge to the wrong Google user telling me the recipient did not exist. 

> Address not found
> Your message wasn't delivered to 1aaapppxxxx.1aaapppxxxx.CnQ7ZbSDkr@txt.voice.google.com because the address couldn't be found. Check for typos or unnecessary spaces and try again.

(phone numbers obscured.)

The same action sequence has worked in the past.  The problem is k9 not fully respecting the change of identity.

**Comment by duncan-SF** [comment]
In the example cited above, further digging reveals k9 used the wrong credentials.  The message was sent with the name from the selected identity but the credentials from the default identity.  Both identities in this case were configured to use the same server.

The mismatched names appear on the From: line of the copy automatically dropped into Google's "Gmail/Sent Mail" folder in, of course, the wrong account.

Saving a message as a draft before sending it usually solves this... but not always: sometimes the message is saved to the Drafts folder of the wrong account.

Saving a message as a draft before sending is generally a good idea on k9.  Unrelated to this bug I've found plenty of cases where messages are discarded if send is pressed before save.  That happens most when k9 is launched from the sharing menu on Gallery or hiq-mp3 recorder.  I suspect it's being killed as a heavy background user immediately after trying to give focus back to the calling app.

**Comment by cketti** [comment]
The K-9 Mail version this bug was reported against is very old by now. Please create a new issue if this is still a problem with recent beta versions of K-9 Mail (5.7xx).
