### ISSUE TITLE
Message text obscured when successful decryption

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#1575]
### Expected behavior

Using open keychain with k9 on android, When opening an e-mail thread where I have signed and not encrypted but the replying party has not signed/ encrypted, the entire message thread should be displayed and arguably no confirmation successful decryption and valid signature.
### Actual behavior

The most recent reply from other party is not shown and message regarding decryption is shown.

The most recent contribution to the email thread is not signed and so I question whether decryption/key checking should be activated.

The signature checking seems to cut off any message above the start of the most recent signing block.

An email thread might look something like this:

Unsigned reply

> signed reply enclosed in inline pgp block sent from desktop mail program
> 
> > unsigned reply to original mail
> > 
> > > signed message enclosed in inline pgp block sent from desktop mail program.

What actually happens looks like this:

x unsigned reply (not shown)
Signed reply sent from desktop mail app. Pgp signing block not visible (parsed by k9/open keychain?)

> unsigned reply
> 
> > signed original message with pgp signature block.

Additionally, if I reply all parts of the thread are visible in the quoted reply so the content is still there.
### Steps to reproduce
1. Set up open keychain with k9
2. Send email to someone with inline signature block
3. Get reply with no signature
4. Reply with signature block
5. Get another reply without signature
### Environment

K-9 Mail version: 5.010

Android version: 6.0.1 (Chroma ROM) / was also happening with 5.1.1 stock android.

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
@Valodim: This should already be fixed in the current development version, right?

**Comment by Valodim** [comment]
I think so, yes

**Comment by thehouseorgan** [comment]
Okay cool, is this the:

* Fixed replying to and forwarding of encrypted messages

in version 5.111?

I'll give it a trial run.
