### ISSUE TITLE
Android Nougat: Email Context Menu at Wrong Position

### ISSUE THREAD

**Issue by MortenMacFly** [thunderbird/thunderbird-android#1581]
### Expected behavior

If I long tap on a message the context menu should appear besides the finger position.
### Actual behavior

The context menu appears at the lower end of the screen and is only 1-2 lines in size.
### Steps to reproduce
1. Select a message
2. Long tap
3. See what happens
### Environment

K-9 Mail version: 5.010

Android version: Nougat (7) Release

Account type (IMAP, POP3, WebDAV/Exchange): All (type independent)

**Comment by cketti** [comment]
This is probably a bug in Android Nougat. We'll have to find a way to work around it.

**Comment by cketti** [comment]
I reported the bug to AOSP: https://code.google.com/p/android/issues/detail?id=221643
