### ISSUE TITLE
HTML/formatting stripped when forwarding HTML emails

### ISSUE THREAD

**Issue by gadgetfan10** [thunderbird/thunderbird-android#1604]
**Expected behavior**
Forwarding an HTML email should result in the recipient receiving an HTML email with all contents intact.

**Actual behavior**
Forwarded message is plain-text only

**Steps to reproduce**
1. Receive HTML email
2. Forward HTML email
3. Review email received by recipient

**Environment**
K-9 Mail version: 5.111
Android version: 6.0
Account type: IMAP

I checked a fresh install/setup of 5.010 and this problem did not occur, but a fresh install/setup of 5.111  with the same settings brought it back.

**Comment by cketti** [comment]
Did you configure K-9 Mail to send plain text only messages? (Account settings > Sending Mail > Message Format = Plain Text)

**Comment by cketti** [comment]
Nevermind, I was able to reproduce this with 'Message Formt = HTML'.

**Comment by gadgetfan10** [comment]
I don't recall if this happened when it was set to HTML or automatic, but it was definitely not plain text.

Thanks.

**Comment by philipwhiuk** [comment]
Caused by #1625 I think. I loaded #1678 on and it's fixed it.

**Comment by cketti** [comment]
I'm guessing it's the same as #1613.
