### ISSUE TITLE
Bad parsing of attachments with semi-colons in the filename

### ISSUE THREAD

**Issue by philipwhiuk** [thunderbird/thunderbird-android#1619]
### Expected behavior

Attachment shown with title: `ABCD; EFG.pdf`

This behaviour works as expected on Roundcube
### Actual behavior

Attachment shown with title: `"ABCD`
### Steps to reproduce

Recieve an email with an attachment that has a semi-colon in the name.

```
Content-Type: application/pdf;
    name="ABCD; EFG.pdf"`
Content-Description: ABCD; EFG.pdf
Content-Disposition: attachment; filename="ABCD; EFG.pdf"; size=101336;
    creation-date="Mon, 09 May 2016 15:19:15 GMT";
    modification-date="Thu, 05 May 2016 14:59:33 GMT"
```
### Environment

K-9 Mail version: A fairly recent build of `master`

Android version: 6.0.1 (September '16 patches)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
## Test case

```
        result = MimeUtility.getHeaderParameter("name=\"ABC; DEF.pdf\"", "name");
        assertEquals("ABC; DEF.pdf", result);
```

**Comment by ivanesko** [comment]
I have problem with utf-8 encoded file names from thunderbird:
`Content-Type: appliaction/pdf;
 name="=?UTF-8?Q?CP_grafick=c3=bd_n=c3=a1vrh_bannerov=2c_Innovation_Media_s?=
 =?UTF-8?Q?.r.o..pdf?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename*0*=utf-8''%43%50%20%67%72%61%66%69%63%6B%C3%BD%20%6E%C3%A1%76%72;
 filename*1*=%68%20%62%61%6E%6E%65%72%6F%76%2C%20%49%6E%6E%6F%76%61%74%69;
 filename*2*=%6F%6E%20%4D%65%64%69%61%20%73%2E%72%2E%6F%2E%2E%70%64%66`

mail client display only first filename without decoding.

**Comment by philipwhiuk** [comment]
See: https://github.com/k9mail/k-9/pull/1526/files for ideas on how to fix this.
