### ISSUE TITLE
Wrong order for multipart/alternative children

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#1625]
We create `multipart/alternative` parts with a `text/html` part as first child and `text/plain` as second child. This isn't what other clients do. And it seems to confuse Thunderbird which then only displays the `text/plain` part.

Affected version: 5.111

**Comment by philipwhiuk** [comment]
Relevant RFC here is RFC1341 (key part bolded):

> 7.2.3 The Multipart/alternative subtype

> The multipart/alternative type is syntactically identical to multipart/mixed, but the semantics are different. In particular, each of the parts is an "alternative" version of the same information. User agents should recognize that the content of the various parts are interchangeable. The user agent should either choose the "best" type based on the user's environment and preferences, or offer the user the available alternatives. **In general, choosing the best type means displaying only the LAST part that can be displayed.** This may be used, for example, to send mail in a fancy text format in such a way that it can easily be displayed anywhere:
