### ISSUE TITLE
Server search only works sometimes when using Gmail

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#1651]
The feature is now working.

**Comment by philipwhiuk** [comment]
I've just attempted several searches on my Gmail account and they seem to work fine.

Are you able to provide device logs during a search to help us diagnose this?

**Comment by catFreeAndroid** [comment]
10-01 12:53:33.262 I/k9      ( 1487): Running command 'getFolderUnread:Gmail:[Gmail]/Todo o correio', seq = 6(foregroundpriority)
10-01 12:53:33.278 I/k9      ( 1487):  Command 'getFolderUnread:Gmail:[Gmail]/Todo o correio' completed
10-01 12:53:44.442 I/ActivityManager(27195): START u0 {act=android.intent.action.SEARCH flg=0x10000000 cmp=com.fsck.k9/.activity.Search (has extras)} from uid 10180 on display 0
10-01 12:53:44.598 I/ActivityManager(27195): Displayed com.fsck.k9/.activity.Search: +129ms
10-01 12:53:45.927 I/k9      ( 1487): searchRemoteMessages (acct=fcb4c074-76ac-49c1-9bc3-dd1cf7b83277, folderName = [Gmail]/Todo o correio, query = david simões)
10-01 12:53:45.933 V/k9      ( 1487): conn74955334>>> 105 NOOP
10-01 12:53:46.079 V/k9      ( 1487): conn74955334<<<#105# [OK, Success]
10-01 12:53:46.080 V/k9      ( 1487): conn74955334>>> 106 UID SEARCH OR SUBJECT "david simões" FROM "david simões"
10-01 12:53:46.242 V/k9      ( 1487): conn74955334<<<#106# [BAD, Could not parse command]
10-01 12:53:46.244 E/k9      ( 1487): Could not complete remote search
10-01 12:53:46.244 E/k9      ( 1487): com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID SEARCH OR SUBJECT "david simões" FROM "david simões"; response: #106# [BAD, Could not parse command]
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:122)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:626)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:612)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.mail.store.imap.ImapFolder.access$000(ImapFolder.java:42)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.mail.store.imap.ImapFolder$5.search(ImapFolder.java:1493)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.mail.store.imap.ImapFolder.search(ImapFolder.java:621)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.mail.store.imap.ImapFolder.search(ImapFolder.java:1503)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.controller.MessagingController.searchRemoteMessagesSynchronous(MessagingController.java:610)
10-01 12:53:46.244 E/k9      ( 1487): 	at com.fsck.k9.controller.MessagingController$7.run(MessagingController.java:581)
10-01 12:53:46.244 E/k9      ( 1487): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
10-01 12:53:46.244 E/k9      ( 1487): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-01 12:53:46.244 E/k9      ( 1487): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-01 12:53:46.244 E/k9      ( 1487): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-01 12:53:46.244 E/k9      ( 1487): 	at java.lang.Thread.run(Thread.java:818)
10-01 12:53:46.292 V/k9      ( 1487): LockableDatabase: Transaction ended, took 15ms / com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1181)

**Comment by philipwhiuk** [comment]
Ah. I wonder if it only fails for non-ASCII characters. I suspect there's an encoding issue to be resolved here.

**Comment by cketti** [comment]
See #1140
