### ISSUE TITLE
K-9 fails to parse From header and thus sync fails

### ISSUE THREAD

**Issue by michaelof** [thunderbird/thunderbird-android#1653]
### Expected behavior

All messages in INBOX should be shown in K9-Mail
### Actual behavior

Some mesages are mit shown/hidden. When K9-mail syncs, it says CORRECTLY "n of m" messages. But if you e.g. "Select all" messages in Inbox, only m-x messages are selected. 
FYI the messages for sure exists. Android AOSP email client shows them, also Mozilla Thunderbird, also Roundcubemal webmail client. 
It's my private mail server, with dovecot.

Error persists even after drop and recreation if the complete account. Always the same msgs missing.
### Steps to reproduce
1. Sync IMAP account.
2. Keep an eye on # of synced msgs
3. Check # of "select all" selected msgs
### Environment

K-9 Mail version: 5.010

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP, dovecot running on mail server. Startssl secured.

**Comment by michaelof** [comment]
Typos, German autocorrect :-S

"Some mesages are mit shown/hidden" should be "NOT shown"

"only m-x messages are selected" should be "are available to be selected"

**Comment by philipwhiuk** [comment]
Are these older messages - by default K-9 only shows the messages from last 30 days or so.

**Comment by michaelof** [comment]
No, not older . 

In fact I've recognized this error first for a brandnew email,  received same day.

**Comment by cketti** [comment]
Please record a debug log while attempting to download messages. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by michaelof** [comment]
Hi K9 Team,

just (finally) made the requested log. 

What I did to narrow down the issue:

- verified, that bug still exists: it does, n msgs in Thunderbird, n-1 msgs in K9
- created imap folder in Thunderbird.
- marked all msgs in K9 "inbox" and moved via K9 into new temp folder
- ALTHOUGH only 1 msg difference, now 11 msgs remain unmoved and now "unshown" by K9 in inbox, Thunderbird is showing all of them

K9 adb log also detects them, all 11

11-18 12:54:56.897 D/k9      ( 4628): SYNC: Have 11 unsynced messages
11-18 12:54:56.898 D/k9      ( 4628): SYNC: About to fetch 11 unsynced messages for folder INBOX

but gets errors for them, e.g.

11-18 12:54:57.082 V/k9      ( 4628): Stored uid '352' for msgSeq 7 into map 
11-18 12:54:57.085 E/k9      ( 4628): MimeException in Address.parse()
11-18 12:54:57.085 E/k9      ( 4628): org.apache.james.mime4j.field.address.ParseException: Encountered "<" at line 1, column 33.
11-18 12:54:57.085 E/k9      ( 4628): Was expecting one of:
11-18 12:54:57.085 E/k9      ( 4628):     <EOF> 
11-18 12:54:57.085 E/k9      ( 4628):     "," ...
11-18 12:54:57.085 E/k9      ( 4628):     "." ...
11-18 12:54:57.085 E/k9      ( 4628):     <DOTATOM> ...
11-18 12:54:57.085 E/k9      ( 4628):     "." ...
11-18 12:54:57.085 E/k9      ( 4628):     <DOTATOM> ...
11-18 12:54:57.085 E/k9      ( 4628):     
11-18 12:54:57.085 E/k9      ( 4628): 	at org.apache.james.mime4j.field.address.AddressListParser.generateParseException(AddressListParser.java:966)
11-18 12:54:57.085 E/k9      ( 4628): 	at org.apache.james.mime4j.field.address.AddressListParser.jj_consume_token(AddressListParser.java:848)
11-18 12:54:57.085 E/k9      ( 4628): 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList0(AddressListParser.java:86)
11-18 12:54:57.085 E/k9      ( 4628): 	at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList(AddressListParser.java:38)
11-18 12:54:57.085 E/k9      ( 4628): 	at org.apache.james.mime4j.field.address.AddressBuilder.parseAddressList(AddressBuilder.java:71)
11-18 12:54:57.085 E/k9      ( 4628): 	at org.apache.james.mime4j.field.address.AddressBuilder.parseAddressList(AddressBuilder.java:75)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.mail.Address.parse(Address.java:158)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.mail.internet.MimeMessage.getFrom(MimeMessage.java:275)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController$10.messageFinished(MessagingController.java:1527)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.fetch(ImapStore.java:1575)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.fetchUnsyncedMessages(MessagingController.java:1492)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1329)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1141)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
11-18 12:54:57.085 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)

or 

11-18 12:54:57.108 V/k9      ( 4628): Batch writing 5 messages
11-18 12:54:57.196 V/k9      ( 4628): LockableDatabase: Transaction ended, took 15ms / com.fsck.k9.mail.store.LocalStore$LocalFolder.appendMessages(LocalStore.java:2507)
11-18 12:54:57.197 E/k9      ( 4628): Error while storing downloaded message.
11-18 12:54:57.197 E/k9      ( 4628): java.lang.NullPointerException
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.Address.getHostname(Address.java:97)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.internet.MimeMessage.generateMessageId(MimeMessage.java:326)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.internet.MimeMessage.getMessageId(MimeMessage.java:317)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.store.LocalStore$LocalFolder.doMessageThreading(LocalStore.java:3307)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.store.LocalStore$LocalFolder.access$3400(LocalStore.java:1343)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.store.LocalStore$LocalFolder$15.doDbWork(LocalStore.java:2553)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.store.LocalStore$LocalFolder$15.doDbWork(LocalStore.java:2507)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.store.LockableDatabase.execute(LockableDatabase.java:283)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.store.LocalStore$LocalFolder.appendMessages(LocalStore.java:2507)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.store.LocalStore$LocalFolder.appendMessages(LocalStore.java:2437)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.writeUnsyncedMessages(MessagingController.java:1581)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.access$500(MessagingController.java:111)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController$10.messageFinished(MessagingController.java:1539)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.fetch(ImapStore.java:1575)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.fetchUnsyncedMessages(MessagingController.java:1492)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1329)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1141)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
11-18 12:54:57.197 E/k9      ( 4628): 	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
11-18 12:54:57.197 E/k9      ( 4628): 	at java.lang.Thread.run(Thread.java:841)


and finally

11-18 12:54:57.585 E/k9      ( 4628): Failed synchronizing folder michael@domain.de:INBOX @ Fri Nov 18 12:54:57 MEZ 2016
11-18 12:54:57.585 I/k9      ( 4628): Background Command 'synchronizeMailbox' completed


PROBLEM for me is that this log files contains a lot of personal information like private email rcpt addresses etc. which I don't want to post to public. Are the error messages above enough for you to trace the bug, or do you still need the complete log. If so, any chance for a private email containing the log instead of uploading?

Regards,
Michael

**Comment by philipwhiuk** [comment]
Ok so we have a few issues here:

1. Apache MIME4J fails to parse the message From header
2. Possibly as a result of this the From hostname of a message is null causing an error storing messages locally.
3. Sync fails continuously

## Bad From header

Either the From header is malformed or Apache MIME4J has a bug. Difficult to tell without the actual From header from the email. If the header line could be emailed to me we can determine this

## Null hostname

This needs some investigation. It's probably due to the above though

## A single email blocks syncing an account.

I feel like we should able to sync more intelligently to avoid this behaviour. If one message fails for some reason it would be nice if we could report that, skip it and sync the rest.

**Comment by GoneUp** [comment]
I got news to the invalid header issue. I found the same error in my debug log today. In my case the mail address got an exclamation mark at the end of the to address. 
K9 did handle the error very well. Sync continued, I had to search the specific mail after I saw the error. It was correctly displayed, expect the malformed To field.


```
01-09 15:02:27.045 15456-15473/com.fsck.k9 E/k9: MimeException in Address.parse()
                                                 org.apache.james.mime4j.field.address.ParseException: Encountered "<EOF>" at line 1, column 48.
                                                 Was expecting one of:
                                                     ":" ...
                                                     "<" ...
                                                     <DOTATOM> ...
                                                     "\"" ...
                                                     <DOTATOM> ...
                                                     "\"" ...
                                                     
                                                     at org.apache.james.mime4j.field.address.AddressListParser.generateParseException(AddressListParser.java:966)
                                                     at org.apache.james.mime4j.field.address.AddressListParser.jj_consume_token(AddressListParser.java:848)
                                                     at org.apache.james.mime4j.field.address.AddressListParser.address(AddressListParser.java:186)
                                                     at org.apache.james.mime4j.field.address.AddressListParser.address_list(AddressListParser.java:110)
                                                     at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList0(AddressListParser.java:85)
                                                     at org.apache.james.mime4j.field.address.AddressListParser.parseAddressList(AddressListParser.java:38)
                                                     at org.apache.james.mime4j.field.address.AddressBuilder.parseAddressList(AddressBuilder.java:71)
                                                     at org.apache.james.mime4j.field.address.AddressBuilder.parseAddressList(AddressBuilder.java:75)
                                                     at com.fsck.k9.mail.Address.parse(Address.java:142)
                                                     at com.fsck.k9.mail.internet.MimeMessage.getRecipients(MimeMessage.java:198)
                                                     at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1313)
                                                     at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1223)
                                                     at com.fsck.k9.mailstore.LocalFolder$15.doDbWork(LocalFolder.java:1218)
                                                     at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
                                                     at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1218)
                                                     at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1145)
                                                     at com.fsck.k9.controller.MessagingController.loadMessageRemoteSynchronous(MessagingController.java:2734)
                                                     at com.fsck.k9.controller.MessagingController.access$1200(MessagingController.java:115)
                                                     at com.fsck.k9.controller.MessagingController$19.run(MessagingController.java:2676)
                                                     at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
                                                     at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
                                                     at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
                                                     at java.lang.Thread.run(Thread.java:761)
```


Mail header: 
```
X-K9mail-Identity: !l=214&o=0&pl=198&po=0&qs=PREFIX&f=HTML&s=&p=194&q=NONE
Subject: 
From: Henry <x@htwg-konstanz.de>
Date: Fri, 26 Jun 2015 17:53:20 +0200
To: felix-bloginput@fefe.de! 
Message-ID: <A68DBA82-BBED-409C-B4A6-09F091F8DE39@htwg-konstanz.de>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----OGPQFKBKV89SGRWZNUOZCUVQFP3VQD"
Content-Transfer-Encoding: 7bit
```

**Comment by philipwhiuk** [comment]
The difference in your case is that the `To` address is malformed. We don't care so much about the `To` address, only the `From` address.

The sync crash is still present.

**Comment by cketti** [comment]
See #1261
