### ISSUE TITLE
Notifications raised incorrectly with multiple accounts

### ISSUE THREAD

**Issue by philipwhiuk** [thunderbird/thunderbird-android#1660]
If you have multiple accounts for K-9 and you get new email in them you should get one notification per account. 

What actually happens is that new emails are listed under the wrong notification. 

For example if I have account A and account B. 
1. I get an email from A
2. A notification is created for A. This is correct. 
3. I get an email from B.
4. A new notification is created for B. This is also correct. 
5. The notification for A is updated with the email from B turning it into a multi-line notification. This is incorrect.

Seen on: 

K-9: master branch

Android: Nougat (7.0)

Nexus 6P

**Comment by levinus** [comment]
Same on Nexus 5X with Android 7.0
