### ISSUE TITLE
All of the preview is same

### ISSUE THREAD

**Issue by pinehallnick** [thunderbird/thunderbird-android#1663]
### Expected behavior

with different mail and the preview should not same.
### Actual behavior

all of previews is same,but actually they are different.
### Steps to reproduce
1. 
   2.
   3.
### Environment

K-9 Mail version:?

Android version:6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
The preview is extracted from the `text/plain` part while most of the time the `text/html` part is displayed when the message is opened. If your emails all contain some placeholder `text/plain` part the preview will be the same. 
But with the little information in your report there's no way to tell what's actually going on. Please attach a screenshot and find out what K-9 Mail version you're running. See https://github.com/k9mail/k-9/wiki/GetVersionNumber

**Comment by zhangxiaofan918** [comment]
I know they are from the text/html part. when I open one of the messages and i found the message content is right ,back to mail list,the content is still wrong.
With debug mode,I see the method which called appendMessages return wrong result.I mean the preview and the details of message is not matching.

**Comment by cketti** [comment]
I don't understand your report. Can you please describe in more detail what you believe is going wrong.

**Comment by zhangxiaofan918** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/9679253/26274114/5882dbc2-3d74-11e7-8507-19b1652b2d63.png)

K9 version:4.409
Android version:5.1.1
