### ISSUE TITLE
No dark app / editor theme in v5.112

### ISSUE THREAD

**Issue by wweich** [thunderbird/thunderbird-android#1665]
### Expected behavior

App keeps dark theme / black background after upgrading to v5.112
### Actual behavior

After upgrading to v5.112, the app theme is always light.
### Steps to reproduce
1. Upgrade to / install v5.112
2. Try setting the dark app theme

I tried setting the theme to light, restarting the app, setting it back to dark and restarting it again. Doesn't help.

Same problem with editor theme.
### Environment

K-9 Mail version: v5.112
Android version: 6.0.1
Account type: IMAP

**Comment by cketti** [comment]
Same cause as #1666
