### ISSUE TITLE
Switching from dark to light theme (or vise versa) inside message doesn't work

### ISSUE THREAD

**Issue by wweich** [thunderbird/thunderbird-android#1666]
### Expected behavior

When `fixed message theme` option is disabled, switching the theme when viewing a message should switch the theme immediately.
### Actual behavior

After switching the theme inside the message, the message view reloads but the theme stays the same. I need to leave the message and open it again to get the other theme.
### Steps to reproduce
1. Disable `fixed message theme` option
2. Open message and switch to dark / light theme
### Environment

K-9 Mail version: v5.111 + v5.112 (iirc, before v5.111 I didn't have this problem)
Android version: 6.0.1
Account type : IMAP

**Comment by wweich** [comment]
This isn't fixed in 5.113.
Switching the theme, changes the background color of the header part and the empty space of the message part, but not the background (and color) of the message content.

---

#### I did a test with screenshots
Starting with dark theme for app and message:
<img src="https://cloud.githubusercontent.com/assets/1026763/19170687/b6f6a510-8c19-11e6-9fc0-293489b13065.png" width="200" />

After switching to light theme inside the message view, the message content is still in "dark mode":
<img src="https://cloud.githubusercontent.com/assets/1026763/19170780/07679e82-8c1a-11e6-83d9-481bb1192983.png" width="200" />

After switching opening the message again (back to list + open again or next message + prev message), colors are correct:
<img src="https://cloud.githubusercontent.com/assets/1026763/19170856/4cbcb9e0-8c1a-11e6-8e5f-13ca7cef3cf0.png" width="200" />

After switching to back to dark theme, the text is "gone":
<img src="https://cloud.githubusercontent.com/assets/1026763/19170892/705939be-8c1a-11e6-8c9d-0ce74b805449.png" width="200" />

... but only, because it is no black text on black background:
<img src="https://cloud.githubusercontent.com/assets/1026763/19170920/8b53e624-8c1a-11e6-9b35-6ca583e1eaca.png" width="200" />

---

I normally use dark theme for app + message. But sometimes I get messages (mostly html), which needs light theme to have correct background and especially text color, to be viewable; so I often switch from dark to light.

**Comment by cketti** [comment]
I misunderstood the original report. It looks like the WebView isn't properly reinitialized.

**Comment by Valodim** [comment]
This is probably caused by 773600c717f8bf79810b1a3ddd03e3c153a68fcb, which initializes the html for display as part of message extraction. I quite specifically cache all of that stuff in MessageLoaderHelper, but destroying that part on changing configurations should not be much overhead, I don't think it's even worth making it sensitive to theme changes.
