### ISSUE TITLE
account sync frequency ignored 

### ISSUE THREAD

**Issue by michaelof** [thunderbird/thunderbird-android#1667]
### Expected behavior

Several imap accounts defined. Some if them fetch frequency of every 5 minutes. Some of them, e.g. spam "catch all" addresses, set to "fetch every 12 hours". Expected is to "respect" the set frequency.
### Actual behavior

All accounts are refreshed based on the settings if the account with the highest frequency. Every 5 minutes in my case instead if of every 12 hours.
### Steps to reproduce
1. Create at least 2 accounts
2. Refresh frequency set different for both accounts
3. Resulting refresh rate is the higher one.
### Environment

K-9 Mail version: 5.010 F-Droid Version

Android version: 4.4.2 KitKat

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (dovecot)

**Comment by cketti** [comment]
The refresh rate was never wrong. But we made it look like the account was being checked. We no longer do so.
