### ISSUE TITLE
Message list footer sometimes empty

### ISSUE THREAD

**Issue by zoff99** [thunderbird/thunderbird-android#1690]
### Actual behavior

using dark theme:
when opening the inbox, and there are no emails in the inbox.
then there is an empty horizontal line.
when you pull down, suddenly it says "loading messages ..." in the empty row.
when loading is finished, the row is strange emtpy again
### Steps to reproduce

use dark theme
goto inbox with no emails in inbox
### Environment

K-9 Mail version: 5.113 f-driod

Android version: 6

**Comment by werano** [comment]
i'm back on 5.010
but be careful, when trying to import a backup made under 5.113 that is not possible. i had to rearrange all my settings on newly installed 5.010

**Comment by Valodim** [comment]
I tried using the dark theme and going to an empty inbox, didn't see anything out of place. Does this happen in all empty folders?

**Comment by zoff99** [comment]
most of the time. sometimes its gone. that new version is strangly filled with bugs.
hope this can be solved

**Comment by werano** [comment]
not only the 5.113, also the 5.112, 5.111

**Comment by Valodim** [comment]
can you please make a screenshot of this? I still cannot get this problem to appear on my device.

**Comment by zoff99** [comment]
![screenshot_20161007-231553](https://cloud.githubusercontent.com/assets/6833516/19214405/1d573cce-8d83-11e6-9fa7-be4d5ef40977.png)

**Comment by zoff99** [comment]
i am guessing the text is not written, or written in background color?

**Comment by zoff99** [comment]
when i do "clear local messages" on inbox then the text "load up to 25 more" is displayed there and onClick is doing something.
but after i press the button and loading is finished, the row is empty again and does NOT react to clicks anymore.

**Comment by michael-dev** [comment]
Affects me as well with normal theme, except i have 3 out of 40 messages above the empty line.

**Comment by cketti** [comment]
This should be fixed in K-9 Mail 5.7xx.
