### ISSUE TITLE
Updating database forever

### ISSUE THREAD

**Issue by Natureshadow** [thunderbird/thunderbird-android#1697]
I updated K-9 to 5.113 and now it is busy updating some database, and has been for the last two hours.

It is draining battery faster than I can recharge and has by now filled up 6 GiB of storage.

**Comment by Natureshadow** [comment]
OK, well, after almost five hours, it finally crashed and started all over.

**Comment by cketti** [comment]
Please record a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Natureshadow** [comment]
@cketti 5 hours long?

**Comment by cketti** [comment]
Well, the most important thing would be the stack trace that is logged when the app crashes. Otherwise you didn't provide much information we can work with.

**Comment by Natureshadow** [comment]
I got a many thousands of lines long log, then had to remove K-9 to make my device usable again.

Will see to find the relevant parts.

**Comment by philggithub** [comment]
same thing for me since noon. K9mail stuck for hours.

**Comment by jsokol** [comment]
I have been having this issue today as well.  It has been running since at least 8 AM (almost 5 hours) saying "Upgrading database of account 'X'".  I haven't tried killing it or anything, but it drained my battery down to 37% in a very short period of time.  I have my phone plugged in now and it is re-charging, but the upgrade process does not seem to be working.

**Comment by philggithub** [comment]
I uninstalled K9mail a short while after I posted my message. Now I wonder if I should re-install it, or wait for the next version. Anyone uninstalled k9mail and re-installed it? Does it work? or should we wait for a fix? K9mail is so great that it is really a pain not to be able to use it.

**Comment by cketti** [comment]
If you uninstalled, the data is gone. There is no database to be upgraded on a fresh install.

**Comment by jsokol** [comment]
I did not uninstall mine.  It still says it is upgrading.

**Comment by Valodim** [comment]
We finally found the problem in #1947, will release a fix soon. If you didn't reinstall, your data should be fine when we fix the migration.
