### ISSUE TITLE
Quick Actions don't get displayed on Android 7.0

### ISSUE THREAD

**Issue by lbdroid** [thunderbird/thunderbird-android#1741]
### Expected behavior

Obviously, when this setting is enabled for "single" or "all", the delete button should appear for the appropriate number of messages being present.
### Actual behavior

Notification appears, WITHOUT the delete button
### Steps to reproduce
1. Enable notification delete button
2. Exit k9
3. receive an email
### Environment

K-9 Mail version: 5.114

Android version:
7.0 (Nexus 6) or 7.1 (Pixel).

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP / not applicable.

**Comment by philipwhiuk** [comment]
Yep notifications changed in 7.0. We fixed one issue but we need to address this too #1726

@cketti and I were discussing whether this should block a 5.200 release.

**Comment by Valodim** [comment]
Did this work in 5.0? If it didn't, it's not a blocker.

**Comment by philipwhiuk** [comment]
I doubt it. I think we agreed it should be fixed afterwards. We could always do it as a 5.201 release if we wanted.

**Comment by lbdroid** [comment]
It will be broken functionality for anyone upgrading their phones currently. I don't use the feature myself, but the first thing my wife noticed when I handed her a new Pixel was that it wasn't working anymore. She's non-tech, so that's the kind of person who needs to be considered.

**Comment by philipwhiuk** [comment]
Sure, it's definitely a bug. But it's not worse than the current release on the app store is the point.

**Comment by cketti** [comment]
The current stable version probably works fine on Android 7.0/7.1 because it only uses a single (summary) notification, not individual notifications. I guess we should fix this before releasing a new stable.
