### ISSUE TITLE
Notification not cleared when deleting message(s) from notification

### ISSUE THREAD

**Issue by mittwinter** [thunderbird/thunderbird-android#1762]
### Expected behavior

When I choose to "Delete" a message or messages from a notification, the notification should be cleared afterwards.
### Actual behavior

While the mail is correctly deleted, i. e. moved to trash on server, the notification is still displayed.
### Steps to reproduce
1. Send a test mail to one of the configured accounts.
2. Select "Delete" from the notification
### Environment

K-9 Mail version: 5.114

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (self-hosted dovecot as well as mailbox.org)

**Comment by philipwhiuk** [comment]
Fixed for me after the merge of #1755

**Comment by philipwhiuk** [comment]
Also duplicate of #1588
