### ISSUE TITLE
Move/Copy emails from local(?) folder

### ISSUE THREAD

**Issue by michaelof** [thunderbird/thunderbird-android#1765]
### Expected behavior

Added IMAP account (freenet.de) to K9. As I didn't change, it seems that K9 has created local folders e.g. "Sent", to store sent items. I earliest recognized this "local" creation when these folders are not existing e.g. in Thunderbird, where I've added the IMAP account a while later.
To store these sent items in a central place, I tried to copy/move them to a "real" IMAP folder (INBOX.sent). 
Expected behaviour is that this move, at least a copy, should work. Workaround would be ok, as this is one time only.
### Actual behavior

After selecting all messages in local folder k9 says (translated from German) "messages, which are not synced with the server, could not be copied or moved"
### Steps to reproduce

1.add freenet.de account to k9
2.sent some mails
3.try to copy sent items
### Environment

K-9 Mail version:5.010

Android version:4.4.2 kitkat

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (FREENET.DE)

**Comment by philipwhiuk** [comment]
We shouldn't be creating local folders that aren't copies of remote folders until we support them. This is really a combination of #648 and bad configuration of special folders.

**Comment by michaelof** [comment]
Hi Philip,


Not sure what I might have misconfigured. I fact as I didn't change anything aside the default settings. 

As the bug only appears on a freenet.de account, and immediately happens after initially adding the account to k9, I've created a (free :)) account just for this bug. Just for you to test.

No IMAP server names ports etc. needed, k9 resolves them automatically.

Regards,
Michael

**Comment by michaelof** [comment]
P.S.: to avoid spamming, I'll send the details per email

**Comment by philipwhiuk** [comment]
Okay, so we definitely create folders in K-9. Which I was surprised about. I think we shouldn't be creating special folders if they don't exist - because it's an indication we just have them wrong.

@cketti and I discussed sync the other day and there's lots of work to do here unfortunately - which will include this ticket.

**Comment by davewood** [comment]
I ran into the same problem with my work IMAP, how do I fix this?
I need to create an email with attachment and continue editing from another device. The draft doesnt get synced and I cant move it either.

**Comment by cketti** [comment]
K-9 Mail 5.7xx should no longer create local folders.

**Comment by dwmw2** [comment]
Is there a way to recover? I have just discovered that the "Sent" folder that K9 was saving mail to is not the actual "Sent" folder on the IMAP server, but on trying to move or copy the messages I get the same error described above about "messages which are not synced with the server cannot be moved or copied".
