### ISSUE TITLE
Notification font color does not contrast

### ISSUE THREAD

**Issue by cygnus-dawn** [thunderbird/thunderbird-android#1797]
Not a real issue because UI normally has white backgrounds on devices that aren't rooted and modified.

### Expected behavior
Tell us what should happen
Font color should contrast with UI notification color on devices that have changed the system UI's background color through means of a theme manager or mod (Xposed or theme flash through recovery)
### Actual behavior
Tell us what happens instead
In android's UI with a black background (not in k9), K9 notifications show the subject line font color that doesn't contrast with notification background color whereas the message contents does that just fine. The subject line remains in black font and cannot be read due to both colors of Android UI and subject line being the same.
### Steps to reproduce
1. Install an Xposed module (notifyclean by defim) that can change color of UI. Or use Substratum with a dark theme installed.
2. Set notifications to a black background. On Substratum, set the system UI and Android system to be applied with a dark theme.
3. Have k9 mail display notification

### Environment
K-9 Mail version:
5.113 f-droid build
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP personal

**Comment by Damdan** [comment]
Here's a screenshot to accurately show what I meant. I was using an overlay app called substratum, not Xposed.
https://drive.google.com/file/d/0Bw-bC7Bt0CjfZUxoQWNFTmRnX00/view?usp=drivesdk

**Comment by philipwhiuk** [comment]
This is in `v21/styles.xml`

If someone from @TeamSubstratum knows the right thing to set it to so it's black on normal devices and something sensible on Substratum I'd be happy to test the standard case.

Currently it's

<item name="android:textColor">?android:textColorPrimaryInverse</item>

**Comment by Damdan** [comment]
Another case is also with Xposed using the notifyclean module by defim to set notifications a darker color (not completely black). Subject font color still remains black.  Also I would have to contact the theme creator that used substratum framework to add an overlay edit for the k9 mail app, not an issue with substratum at all.

**Comment by philipwhiuk** [comment]
I'm not suggesting we change the theme. I'm suggesting we find a better constant to use to set the textColor. I thought Substratum would know that. But if the theme editors know that's fine too. It should be the colour that notification titles are set to.

**Comment by piggyslasher** [comment]
Still happening on many dark themes.

**Comment by isleshocky77** [comment]
This is now an issue on Galaxy S10 which has night mode on Android 9. While night mode is enabled you're unable to read the text of the k9 notification.

**Comment by bbtdev** [comment]
Same on Note 9

**Comment by psychowood** [comment]
The problem (at least for me, S9+) happens only when I have multiple notifications, and only when collapsed:

- Multiple notifications, collapsed

![multiple-collapsed](https://user-images.githubusercontent.com/115389/62146556-ee85f980-b2f5-11e9-90dc-d08780af36c7.jpg)

- Multiple notifications, exploded

![multiple-exploded](https://user-images.githubusercontent.com/115389/62146568-f34aad80-b2f5-11e9-89ee-689d3e3dc447.jpg)

- Single notifications, collapsed

![single-collapsed](https://user-images.githubusercontent.com/115389/62146581-f80f6180-b2f5-11e9-9c11-c203dc9a9520.jpg)
