### ISSUE TITLE
Forwarded icon disappeared

### ISSUE THREAD

**Issue by pinehallnick** [thunderbird/thunderbird-android#1864]
### Expected behavior
Forwarded icon not disappeared

### Actual behavior
Forwarded icon disappeared,but the reply signs are always in

### Steps to reproduce
1.Forward a mail and the forwarded Icon is displayed
2.Pull To refresh
3.Forwarded icon disappeared

### Environment
K-9 Mail version:Latest version

Android version:5.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by zhangxiaofan918** [comment]
@philipwhiuk do you know how to fix this bug?

**Comment by philipwhiuk** [comment]
I marked it as a bug from initial review. I'm not quite running 5.200 on my device right now. But my guess is that the actual problem might be that your email provider doesn't support flagging messages as Forwarded. What email provider are you using?

**Comment by zhangxiaofan918** [comment]
@philipwhiuk Any email provider. Maybe I did not describe the problem clearly,I refer to the forwarding identifier of the mailing list page.The weird thing is the email marked after the first forwarded can be shown,but drop down on the refresh and the marked icon is gone

**Comment by philipwhiuk** [comment]
Yes, I understood the issue. The reason, I believe is that when the email is re-synced, the mail on the server doesn't have the Forwarded flag listed. This means your email provider doesn't support syncing IMAP flags. Hence why I asked which provider to confirm if this was the case.

**Comment by zhangxiaofan918** [comment]
@philipwhiuk  163.com
