### ISSUE TITLE
Cc/Bcc expander barely visible in dark theme 

### ISSUE THREAD

**Issue by jhoc2000** [thunderbird/thunderbird-android#1893]
### Expected behavior
K-9 Mail version 5.115 used to provide the option of choosing a TO, CC or BCC recipient in the selection field at the very top of the compose an email window. This is no longer available in version 5.2. There should also be the option to choose a To, CC or BCC recipient in the pull down list 

### Actual behavior
When composing an email one can't select a CC nor BCC recipient unless one has checked "Always show Cc/Bcc" in the settings for each email account. 

### Steps to reproduce
1. Compose an email 
2. Can't select Cc nor Bcc recipients for the email 

### Environment
K-9 Mail version:
5.2
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
POP.

**Comment by Valodim** [comment]
Hit the down arrow on the To field, then the Cc and Bcc fields will expand. This is the same design as in the GMail app.

**Comment by jhoc2000** [comment]
There is no down arrow in the To: field. I'm using the dark view. If there is a black down arrow, it can't be seen in the dark view.

**Comment by jhoc2000** [comment]
This shouldn't be closed because there is no down arrow in the To: field in the dark view.
