### ISSUE TITLE
can't decrypt MIME encoded message, error from OpenKeychain

### ISSUE THREAD

**Issue by klic** [thunderbird/thunderbird-android#1901]
Sorry, I don't know whether this belongs here, but somewhere I have to begin ...

I have an encrypted mail, in m

ulti-part message MIME format, text, html and an (unencrypted) pdf attachment. 
K9 mail (5.200) tries to decrypt it with OpenKeychain, but fails and displays the MIME text unchanged.
This is what I get from logcat:

```D/k9      (28235): MessageView displaying message MessageReference{accountUuid='941dcfeb-a9f6-49cb-8056-94b66ecba3e1', folderName='INBOX', uid='107910', flag=null}
D/k9      (28235): Creating new local message loader
D/k9      (28235): OpenPGP API decryptVerify result code: 2
D/OpenGLRenderer(27929): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
V/WindowManager( 2638): Adding window Window{10174949 u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.remote.ui.RemotePassphraseDialogActivity} at 13 of 19 (after Window{29f4167a u0 com.fsck.k9/com.fsck.k9.activity.MessageList})
I/OpenGLRenderer(27929): Initialized EGL, version 1.4
D/OpenGLRenderer(27929): Enabling debug mode 0
V/k9      (28235): conn63347625<<<#null# [OK, Still here]
V/k9      (28235): Got async response: #null# [OK, Still here]
V/k9      (28235): conn634925872<<<#null# [OK, Still here]
V/k9      (28235): Got async response: #null# [OK, Still here]
D/k9      (28235): OpenPGP API decryptVerify result code: 1
D/k9      (28235): Creating new decode message loader
D/k9      (28235): No external images.
D/skia    (28235): --- SkImageDecoder::Factory returned null
D/skia    (28235): --- SkImageDecoder::Factory returned null
D/OpenPgp API(28235): Stopped writing due to broken pipe (other end closed pipe?)
D/OpenPgp API(28235): Stopped writing due to broken pipe (other end closed pipe?)
```

Unfortunately, I can't upload a privatized version of that mail. WIll be available at request

### Environment
K-9 Mail Version 5.2.00

Android version:
Fairphone Open Os 5.1 (based on AOSP 5.1)

Account type is IMAP

**Comment by Valodim** [comment]
mail to me please -> look@my.amazin.horse

**Comment by Valodim** [comment]
Got the message. It's not pgp/mime encoded, it's a multipart/mixed message with a text/plain part that contains pgp/inline data, and an unencrypted attachment... quite the bastard of a message.

What's the background of generating such a message, if I may ask?

**Comment by cketti** [comment]
Sounds pretty standard. Is that not how we are generating inline encrypted messages with attachments?

**Comment by Valodim** [comment]
It used to be, but half encrypting messages like that is just haphazard behavior. Right now we simply don't support attachments in PGP/INLINE mode.

**Comment by philipwhiuk** [comment]
We might prohibit sending them but we ought to handle receipt...
