### ISSUE TITLE
Cannot zoom HTML messages properly if at all

### ISSUE THREAD

**Issue by MartyMacGyver** [thunderbird/thunderbird-android#1908]
### Expected behavior
HTML mail should pinch zoom as it always has

### Actual behavior
In 5.201 I tried zooming a few HTML emails. Nether would pinch zoom (though double tapping made them a tiny bit bigger). At least once this led to a crash of the app.

I reverted to 5.010 and zoom works just fine with the same mail - in fact, it never had any such issue so I'm not upgrading until this is fixed.

### Steps to reproduce
Open html email e.g. from Xbox.com
Pinch zoom
Either nothing happens, it moves a tiny bit, or it ends up crashing.

### Environment
K-9 Mail version:
5.201 is broken for this. Works fine in 5.010

Android version:
7.0 on Nexus 6

IMAP

**Comment by HarlemSquirrel** [comment]
I can confirm this issue on 5.200 as well

**Comment by aahzpy** [comment]
I am also seeing this behavior in plain-text messages.  Both Galaxy 7 and Note 10.

**Comment by N-ik05** [comment]
I found out how to correctly scroll in K-9, the pinch gesture does not seem to work.

Put two fingers on the screen at the same time and then keep one of the fingers very still and move the other away or to the former.

**Comment by naturat** [comment]
Definitely not working even though just received email from them saying it does work

**Comment by MartyMacGyver** [comment]
Sometimes pinch zooming would also cause a tiny variation in the zoom level (0.1x difference at most, usually not at all), but it was inconsistent and virtually inconsequential beyond that small range, no matter how much more you tried.

I noticed a friend using K9 on another phone a couple of days ago - while I don't have details on their exact Android version (it's a Samsung from the last couple of years) I asked them to try the same zooming and the problem was exactly the same: 5.201 was equally broken compared to the previous K9 version on their phone.

**Comment by Valodim** [comment]
This is an issue with the `NonLockingScrollView` layout. We'll look into it, sorry for the inconvenience.

Also, sign up for our [alpha channel](https://play.google.com/apps/testing/com.fsck.k9) if you want to contribute to catching these kinds of regressions before we release :)

**Comment by MartyMacGyver** [comment]
Glad it's a verified bug (I wasn't sure if there was still a question if it was reproducible).

I'll consider the alpha channel for the future - I did subscribe to the beta channel via Google Play FWIW, but have held off updates of any kind until this is resolved and things stabilize (besides this, K9 crashed twice in the very short time I tried 5.201, but it seemed related to the zoom thing so I didn't dig into them further).

**Comment by nicolas-joubert** [comment]
Same problem for me, neither 5.202 nor 5.201/5.200 cannot zoom properly. On previous release (5.115) all working well.

Android 4.1.2 / Wiko Cink five legacy

**Comment by naturat** [comment]
Saw they just pushed out a new version this am... still not working.  ver 5.202

**Comment by aahzpy** [comment]
naturat: Milestone got moved to 5.203 on 1/4 (four days ago as of now)

I don't know the k-9 development community, but I notice that there's no assignee, might not get fixed until someone owns the issue

**Comment by reetp** [comment]
5.202 / Galaxy S6 not working

Serious regression in usability due to quantity of html mail. Makes reading html mail almost impossible.

**Comment by naturat** [comment]
This is not fixed on my end.  I don't see any updates to the app, and the current build still isn't working.

**Comment by Valodim** [comment]
Did you build from master? Since no release happened in the last three hours, obviously this fix hasn't landed in a release yet.

**Comment by Rickerr** [comment]
I upgraded to the latest a couple of days ago.  I have been experiencing it since the last upgrade.  I don't have time or the programming experience to try to fix this myself.  I'm starting to have the nearness issue with sight, so I really hope someone fixes this.

**Comment by FlyGuyUK** [comment]
Can we please get an intermediate fix release??, it's making K9 impossible to use without pinch to zoom.
