### ISSUE TITLE
message subject no longer shown on message view

### ISSUE THREAD

**Issue by Monkboon** [thunderbird/thunderbird-android#1915]
### Expected behavior
the message subject should be shown in the message view

### Actual behavior
the message view no longer shows the message subject

### Steps to reproduce
1. open a message
2. try to read the message subject in the message view

### Environment
K-9 Mail version: 5.201

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by jmccabe** [comment]
Same here, and I noticed someone else has posted a screenshot devoid of subject text in their issue on missing message text.

**Comment by cketti** [comment]
The subject should be displayed in the action bar. If it is too long to fit there it'll be displayed in the message header.

If that's not the case for you please post a screenshot.

**Comment by jmccabe** [comment]
I'm using a tablet (1280x800 I think), mostly in portrait mode, with split screen mode always on, and opening to the unified inbox. The message list panel is way too small to show the full subject but, when I select a message and it's shown in the right panel, it's copied into neither the action bar nor the header area. I can't do a screenshot at the moment.

**Comment by Monkboon** [comment]
The subject is only missing in split view, irrespective of orientation

![screenshot_20170103-220611](https://cloud.githubusercontent.com/assets/24877962/21631460/1122eb5c-d201-11e6-9194-19c5387d0cc7.png)
![screenshot_20170103-220647](https://cloud.githubusercontent.com/assets/24877962/21631459/1122c5b4-d201-11e6-873d-5083197e8207.png)
![screenshot_20170103-220717](https://cloud.githubusercontent.com/assets/24877962/21631461/11259afa-d201-11e6-8684-1f1737f4f89e.png)
![screenshot_20170103-220600](https://cloud.githubusercontent.com/assets/24877962/21631458/11220eee-d201-11e6-87e6-3f8a2c24466a.png)
