### ISSUE TITLE
ImapResponseParser.parseLiteral timeout error

### ISSUE THREAD

**Issue by reittila** [thunderbird/thunderbird-android#1919]
[k9-log.txt](https://github.com/k9mail/k-9/files/681130/k9-log.txt)
### Expected behavior
Tell us what should happen
K9 should be able to read IMAP mail
### Actual behavior
Tell us what happens instead
It logs in the IMAP account but doesn't read the mail box.
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.201
Android version:
6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Valodim** [comment]
Hm, there are 23 messages in INBOX, only one of which isn't present in the local mailbox. This message doesn't sync, which seems to be caused by a SocketTimeoutException during `UID FETCH 3 (UID BODY.PEEK[])`. Can you describe more precisely what is going on, e.g. how many mails are displayed or missing?

**Comment by reittila** [comment]
What happens is that K9 stops when it's trying to sync INBOX i.e. the "circle" on upper left corner of the phone goes around and around. No error messages. After a while the "circle" just disappears and new messages stay unsynced.

**Comment by reittila** [comment]
Ok. I moved all the messages from INBOX to archive with a Windows IMAP client and now K9 seems to work. So propably the message you mentioned was the cause for this issue ?

**Comment by Valodim** [comment]
That's possible I guess. The message has subject "Epson Connect - Printer Email Address (Printer Registered)" from and is October 21st in 2015. If that message isn't secret and you can send it to me, I could see if it causes any problems if I have it in a mailbox :) (-> send to look@my.amazin.horse )

**Comment by reittila** [comment]
Sent it to you...

**Comment by cketti** [comment]
Looks like a bug in the parser. In `parseLiteral()` we call `ImapResponseCallback.foundLiteral()`. The callback returns `null` and we skip over the unread data. Then we try to read the literal data again and the read blocks until the socket times out because there's not enough data to read.

**Comment by cketti** [comment]
Rather than returning `null` the callback most likely throws an exception while parsing the message.
