### ISSUE TITLE
Black text in quotation in replies

### ISSUE THREAD

**Issue by rugk** [thunderbird/thunderbird-android#1930]
### Expected behavior
When replying to a mail the quoted part should be shown in white, also when the black design is used.

### Actual behavior
![](https://i.imgur.com/R8hP2I3h.jpg)

### Steps to reproduce
~~Additionally you may need to use a black design in Cyanogenmod.~~
The pre-5.0 version the quote was shown correctly.

### Environment
K-9 Mail version: 5.20

Android version: CM 13

**Comment by cketti** [comment]
If you're messing with system themes, you're on your own. Have you tried simply using K-9 Mail's dark theme?

**Comment by rugk** [comment]
I am using k9 mail darks theme and I just reproduced it with the System theme of CM.
Actually I saw the mail itself is the issue.

**Comment by rugk** [comment]
The original mail was from GitHub support, in case you care to reproduce it.

However I could also reproduce it by sending a plain-text mail to myself. You can directly send it from K9 mail. When replying this time the issue is not just that the font is black, but also that the font size is 8 pt or so, at least it is pretty small.

**Comment by cketti** [comment]
I see. We're not doing the same HTML preprocessing in the compose screen like we do in the message view screen.

**Comment by rugk** [comment]
But it's different…

**Comment by LeftPinkie** [comment]
I have same problem. I would need to edit the reply section if I want to view it properly.

**Comment by rugk** [comment]
> I would need to edit the reply section if I want to view it properly.

Yes, this works here too. It basically just converts the screen to text.

**Comment by rugk** [comment]
Nice that this issue was fixed, but one problem still remains: https://github.com/k9mail/k-9/issues/2106
