### ISSUE TITLE
After v5.201 upgrade, stopped receiving email

### ISSUE THREAD

**Issue by jnoye** [thunderbird/thunderbird-android#1934]
### Expected behavior
Prior to the upgrade, during inbox polling, if new messages exist, a copy of the new messages will down load to my phone.

### Actual behavior
After the upgrade to v5.201, during polling, it just says loading for a very long time and then stops.  No new messages are dowe loaded eventhough 

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
Please record a debug log while trying to fetch messages. Instructions here: https://github.com/k9mail/k-9/wiki/LoggingErrors
Also, please fill out information about your environment (Android version, account type).

**Comment by jnoye** [comment]
Sorry accidently hit submit button... no new messages are downloaded eventhough new messages exist on server.
K9 version - v5.201
Android version - v6.01
POP3 account

**Comment by jnoye** [comment]
Sorry, unable to provide error log.  Having issues with Internet at home...

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by cketti** [comment]
Unfortunately, there's nothing we can do without more information.
