### ISSUE TITLE
BCC not working as expected

### ISSUE THREAD

**Issue by AlexBaranowski** [thunderbird/thunderbird-android#1938]
### Expected behavior
I wrote the mail with BBC on my Android 6.0.1.
So other people from CC shouldn't know that there are e-mail on BBC

### Actual behavior
All were able to read that there was bbc

### Steps to reproduce
1. Write mail with BBC
2. See their smiling faces when they discovers that boss e-mail is on BBC.

### Environment
K-9 Mail version: 5.201

Android version:6.0.1.

Account type (IMAP, POP3, WebDAV/Exchange): IMAP and SMTP on zoho.com

**Comment by Valodim** [comment]
I just tested this and bcc doesn't show up in the headers of the To recipient. Can you test explicitly and see if this is reproducible for you?

**Comment by frojack** [comment]
I too tested this and bcc-recipients do not see other bcc addresses.

This whole issue is still widely misunderstood and mishandled by some old smtp servers.
See http://www.emaildiscussions.com/showthread.php?t=71889

My tests, using my own smtp server (postfix) and sending one mail to one recipient and 2 BCC-recipients, shows that K-0 sends one mail with three recpts to the smpt server, and the smtp server breaks that out into three separate emails, none of which carry more than one address, and no other addresses appear in the CC header.

My second test was with one to address and  two CC addresses, and again k-9 sent one email, the postfix smtp server broke that out and sent three emails but added the CC header as expected. 

My tests only prove that K-9 and postfix appear to do everything correctly.  Other SMTP servers may not handle BCCs responsibly.

**Comment by cketti** [comment]
K-9 Mail removes the BCC header before handing over the message to the SMTP server. So if a BCC header shows up at the recipients it's because the server synthesizes one. That'd be quite unusual. But nothing surprises me when it comes to corporate email setups.

**Comment by cketti** [comment]
@AlexBaranowski Please try sending a message with BCC recipients using another account. Then check if the recipients also see the BCC recipients.

**Comment by Valodim** [comment]
I don't know how an smtp server could even do that, the bcc mails are sent separately from non-bcc ones, so the mail that is sent to regular recipients doesn't carry the info at all.

**Comment by kj8749** [comment]
I am also having this problem. Since installing the new version of K9, everyone can see the BCC recipients. I've tried sending it to multiple people and e-mail addresses and it happens every time.

**Comment by cketti** [comment]
@Valodim: We only send one message to the user's SMTP server for all recipients. The server could compare the SMTP recipients with the ones in the To And Cc header lines and put the remaining ones in a synthesized Bcc header line.

@kj8749: Are you sure? The message that is uploaded to your Sent folder will contain the Bcc header line. That does not mean the recipients will also see it.

**Comment by kj8749** [comment]
Yes, all of my friends that I have sent the e-mails to are telling me they can see the BCC address now. This only started happening with the new version of K9 and I never had a problem with the previous version. I have also tried e-mailing with other apps and they are fine. The problem only occurs with the new version of K9.

**Comment by Valodim** [comment]
And that, ladies and gentlemen, is why we need more beta testers, to catch this kind of breakage before we release it to the general public :) [Sign up here](https://play.google.com/apps/testing/com.fsck.k9).

**Comment by frojack** [comment]
Again, this is NOT happening for me, and it depends on the capabilities of the smtp server.
I'm not convinced k-9 is doing anything wrong.

Any postfix version handles this correcty - since well over 10 years.
Gmail smtp handles this correctly.
This is a long solved problem of the mid 90's.

We need those who are seeing this to tell us what SMPT server they are connecting to, which you can glean by looking at headers, or just tell us the smtp server from your settings.

**Comment by frojack** [comment]
So, why does it work for me?

**Comment by Valodim** [comment]
The MUA should not leave this data in the headers. It's nice if MTAs catch this, but they shouldn't have to.
