### ISSUE TITLE
K9 5.201 crashing...

### ISSUE THREAD

**Issue by gitfve** [thunderbird/thunderbird-android#1940]
### Expected behavior
A nice and stable app is going real unstable and bad. It start crashing, and response slow.
-Update of db is ok with success.
-Normal day use it crash some time when it receive a mail. 
### Environment
K-9 Mail version:
-5.201
Android version:
-6.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
-IMAP
-Start crashing after latest update, have runned for years!

**Comment by cketti** [comment]
Make sure to click "Report" on the dialog that tells you the app crashed.

Your report doesn't contain any specific information that would allow us to find and fix the bug. If you can please record a debug log. Instructions can be found here: https://github.com/k9mail/k-9/wiki/LoggingErrors
If not, please close this issue. We're looking at all reported crashes and will get to yours eventually.

**Comment by philipwhiuk** [comment]
No debug log - several fixes since then. @gitfve if you have time to provide a debug log feel free to comment on this and we'll re-open it.
