### ISSUE TITLE
Cannot view attached image with Gallery app

### ISSUE THREAD

**Issue by LeftPinkie** [thunderbird/thunderbird-android#1951]
When attempting to view attached images with the default Android gallery app... all I get is a blank screen. I would have to save the attachment first then use the Gallery app externally. Other image viewer apps work just fine & Gallery wasn't having a problem before v5.201.

K-9 Mail version:
5.201

**Comment by philipwhiuk** [comment]
:( @Valodim :(

**Comment by ar-** [comment]
Reading this, I'm just wondering if it is the same as #1721 ?

**Comment by philipwhiuk** [comment]
Yeah it definitely feels like #1769 didn't work in all cases.

**Comment by Valodim** [comment]
I have no idea what's going on, and I can't reproduce this problem. Opening images with the gallery app works fine for me since #1769 .

@LeftPinkie Does this happen for all mails with attachments, or just some? Also, can you try to record a debug log for this?

**Comment by LeftPinkie** [comment]
@Valodim ,
Sorry it took me so long to get back to you. Yes, this happens on all emails with image attachments.  I don't know if the debug will show anything because the Gallery app launches fine but Gallery displays nothing. While other image viewer apps will display the image correctly.  I have enabled the debug... but where would the debug file be located on my phone?

**Comment by cketti** [comment]
Sorry, if it works with other image viewers please use one of them. We don't have the resources to dig into all reported issues. This one seems easily mitigated.
