### ISSUE TITLE
Search fails to find email when searching by partial address / partial contact name

### ISSUE THREAD

**Issue by dsghub** [thunderbird/thunderbird-android#1956]
### Expected behavior
Messages should be found, for example by the sender's email address (or part thereof)

### Actual behavior
Messages are often not found

Example: Having received an email from Alice Doe, adoe@example.com, I can find the email manually, but the search function does not find it when I search for "adoe" or "Alice". The search function does find (some?) emails that contain "adoe" or "Alice" in the body.

Also, it seems that the search is now slower than before the most recent update.

### Steps to reproduce
1. open a folder
2. search for a string

### Environment
K-9 Mail version: 5.201

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by drayzen** [comment]
Currently have same issue using Android v5.600.

**Comment by cketti** [comment]
This should no longer be an issue.
