### ISSUE TITLE
PGP message doesn't decrypt in 5.201, but does in 5.010

### ISSUE THREAD

**Issue by boskamp** [thunderbird/thunderbird-android#1960]
### Expected behavior
Open PGP encrypted message in inbox, get prompted for PGP passphrase and enter it, then see the decrypted message text. This is also the actual behavior up to and including 5.010.

### Actual behavior
Open PGP encrypted message in inbox, get prompted for PGP passphrase and enter it, but the text displayed remains the PGP ASCII armor, i.e. the data starting with "-----BEGIN PGP MESSAGE-----" and ending with "-----END PGP MESSAGE-----". No cleartext message is displayed.

### Steps to reproduce
This seems to be related to the encoding of the incoming PGP message. The messages who cause the issue are MIME messages with two parts: one is the ASCII armor with content type text/plain. The second part is also the ASCII armor, but with some additional HTML markup and content type text/html.

I've attached the full SMTP message, stripped from most headers, for your reference. As you can see from the headers, the user agent of the sender is Thunderbird. I've also attached the k9 debug log.

[message.txt](https://github.com/k9mail/k-9/files/684846/message.txt)
[k9-log.txt](https://github.com/k9mail/k-9/files/684847/k9-log.txt)

### Environment
K-9 Mail version: 5.201

Android version: 4.4.4 (CM 11-20141115-SNAPSHOT-M12-i9100)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment]
Thanks for the detailed report. We tried to pin behavior more with the new release, to avoid e.g. interpreting quotes as encrypted content. This is likely a legitimate format we missed, will look into it.

**Comment by aalbert10** [comment]
I have a similar problem with the same environment, but found that K-9 mail could not find my APG app, in setting->Account settings->Cryptography No OpenPGP app installed.
It was working with the previous version of K-9

**Comment by boskamp** [comment]
@aalbert10 As far as I can see, the [changelog](https://k9mail.github.io/k-9/changelog_5.2-MAINT_branch.xml) says that support for AGP has been removed in 5.200-RC1

**Comment by aalbert10** [comment]
My mistake, I should read the changelog. Thanks

**Comment by alanthehat** [comment]
This is not fixed in v5.203 but fine in v5.010. 
Messages that I have are 1) from facebook or 2) using a password rather than a key. 
Sorry, I cannot post screenshot with this browser.

**Comment by Valodim** [comment]
The bug reported here has not been released yet, it will be in v5.204.
