### ISSUE TITLE
K9 Unread Widget Size is 1x2 or 2x2 instead of 1x1

### ISSUE THREAD

**Issue by McNetic** [thunderbird/thunderbird-android#1981]
I first noticed this on my wifes klte with CM12 - for some reason (unexplicable to mee), the unread widget has the size 2x2 instead of 1x1 for at least a year now (uninstall and reinstall of k9 didn't help).

Now, since I updated to K9 5.2, it also happened on my klte with CM13.0, but the size is now 1x2 (as you can see in the attached screenshot). The widget is not resizable after added to a homescreen.
![k9widgetsize](https://cloud.githubusercontent.com/assets/1324685/21683079/10683ec6-d358-11e6-8d65-0f01595bc357.png)

### Expected behavior
The widget should always be 1x1 in size, as it was before.

### Actual behavior
On some devices, the size is off - 1x2 or 2x2 on two of my devices.

### Steps to reproduce
Can't reproduce - can get rid of, either, by uninstalling/reinstalling. Also did a wipe of K9 data once on my wifes phone, to no avail.

### Environment
K-9 Mail version: 5.201 currently, was already for some months before on one device.

Android version: 5.0/6.0 (CM 12/13)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ahoh77** [comment]
i just got my new honor 8 and i have the same problem. The available widget size depends on my homescreen adjustement: if i set the homescreen to 4x5 grid everything is fine, the k9-unread-widget is at size 1x1. But if i set my homescreen to a 5x5-grid (or 5x4) then the widget size is 2x2. it seems to be an issue with the screen resolution and/or grid scaling...
