### ISSUE TITLE
Lost old emails after update

### ISSUE THREAD

**Issue by non0815** [thunderbird/thunderbird-android#1988]
Hi,

I use 5 different email accounts on my K9 app. I have download a copy of my email on my phone since 2013. One in the week I use Outlook on my laptop and download all emails from the server (gmx.de). After the download the emails are not available on the server.

For all email accounts are the localStorageProvider = ExternalStorage. So i can find the files under Android/data/com.fsck.k9/files

This path includes normaly:
5x folder with the account uuid ending ".db_att" 
5x file with the account uuid ending ".db" (file size min 85.000 KB max 475.000KB)
5x file with the account uuid ending ".db-journal"
1x file name ".nomedia"

2 of 5 accounts were empty (all old emails not shown) after update. The other 3 accounts updated correct and all old emails available.

I have look at the path after update which included two new folder:
2x account uuid ending ".db_attach-"  and 13 digit number
2 of 5 files with the account uuid ending ".db" (has a low file size < 17.000KB)
3 of 5 files with the account uuid ending ".db" (file size > 115.000KB)

### Steps to reproduce
1. Download update via Play Store
2. Start App
3. App show "database update for emailadress" (or somthing like that)
4. Wait until the email accounts are shown (takes a lot of time)

### Environment
K-9 Mail version: I'm not sure. Update was yesterday 04. Jan 2017 midday. I installed the new version 5.202 today 

Android version: 6.0.1 (Samsung S7)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP gmx.net accounts

**Comment by metalbo** [comment]
Hi, I have probably the same issue:
I do not see my old (about 3000 emails) anymore since around new year. 
Android 5.0.1
Samsung Galaxy S4
K9-mail v5.202
Issue probably already happened about two updates ago.
Can they be restored?

**Comment by metalbo** [comment]
Additional information:
I use only POP3. 
Emails are not deleted from the mail account by K9. I empty the account regularly when there are about 100 emails on it by using a PC.

**Comment by philipwhiuk** [comment]
Presumably this is a database upgrade failure and there's likely nothing we can do. Sorry.

There's also no log (unsurprisingly) so I don't know that we are going to be able to fix the specific case.

Personally I wonder whether we should remove the check and always crash the app if we can't upgrade properly @cketti ?

**Comment by gdriskell** [comment]
I had the same issue upgrading to version 5.202.
From the log:
01-09 23:13:06.816 E/k9      (32655): Exception while upgrading database. Resetting the DB to v0
01-09 23:13:06.816 E/k9      (32655): java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
01-09 23:13:06.816 E/k9      (32655): 	at android.database.CursorWindow.nativeGetLong(Native Method)
01-09 23:13:06.816 E/k9      (32655): 	at android.database.CursorWindow.getLong(CursorWindow.java:524)
01-09 23:13:06.816 E/k9      (32655): 	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.mailstore.migrations.MigrationTo51.db51MigrateMessageFormat(MigrationTo51.java:79)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.mailstore.migrations.Migrations.upgradeDatabase(Migrations.java:58)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.mailstore.StoreSchemaDefinition.upgradeDatabase(StoreSchemaDefinition.java:60)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.mailstore.StoreSchemaDefinition.doDbUpgrade(StoreSchemaDefinition.java:36)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.mailstore.LockableDatabase.openOrCreateDataspace(LockableDatabase.java:381)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.mailstore.LockableDatabase.open(LockableDatabase.java:354)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.mailstore.LocalStore.<init>(LocalStore.java:210)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.mailstore.LocalStore.getInstance(LocalStore.java:235)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.Account.getLocalStore(Account.java:1278)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.controller.MessagingController.setupPushing(MessagingController.java:4322)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.service.MailService.setupPushers(MailService.java:349)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.service.MailService.reschedulePushers(MailService.java:338)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.service.MailService.access$100(MailService.java:24)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.service.MailService$1.run(MailService.java:194)
01-09 23:13:06.816 E/k9      (32655): 	at com.fsck.k9.service.CoreService$1.run(CoreService.java:315)
01-09 23:13:06.816 E/k9      (32655): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-09 23:13:06.816 E/k9      (32655): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-09 23:13:06.816 E/k9      (32655): 	at java.lang.Thread.run(Thread.java:818)
01-09 23:13:06.826 I/k9      (32655): Upgrading database from version 0 to version 55
01-09 23:14:08.586 I/k9      (32655): No folders are configured for pushing in account Greg
01-09 23:14:08.586 V/k9      (32655): Pusher refresh interval = -1
01-09 23:14:08.586 D/k9      (32655): CoreService (com.fsck.k9.service.MailService) completed Runnable 235798985 with startId 1
01-09 23:14:08.586 V/k9      (32655): TracingWakeLock for tag CoreService execute / id 2: releasing after 277109 ms, timeout = 60000 ms
01-09 23:14:08.596 V/k9      (32655): ***** MailService *****: onDestroy()
01-09 23:14:08.596 I/k9      (32655): CoreService: com.fsck.k9.service.MailService.onDestroy()
01-09 23:14:11.136 I/k9      (32655): DatabaseUpgradeService stopped
01-09 23:14:11.136 V/k9      (32655): TracingWakeLock for tag DatabaseUpgradeService / id 5: releasing after 279579 ms, timeout = 600000 ms

**Comment by tanz82** [comment]
I have had the exact same issue. All of my old emails are gone. I have made copies of the files themselves as i used to move them from phone to phone. Is there any way of access the files. Can this be done through a program on the pc?

**Comment by lazycodeninja** [comment]
I also lost my emails after in upgrade, although in my case it was the content ID replacement in the `MigrationTo51` that was the problem.  I've fixed the issue, and will be submitting a pull request soon.
