### ISSUE TITLE
Nothing in main body of Mail since latest update

### ISSUE THREAD

**Issue by orac1111** [thunderbird/thunderbird-android#1992]
Shows subject line and sender but does show anything in the main body see attachment.  This is the same for new emails or old already downloaded emails

### Environment
K-9 Mail version:5.202

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

![screenshot_2017-01-06-09-24-21](https://cloud.githubusercontent.com/assets/17318437/21713563/75e39940-d3f2-11e6-8202-67cb0c27e7be.jpg)

**Comment by thelexon** [comment]
I have the same problem when the body of the email there is a list. The email was sent from Outlook 2010 (before the last update I read them without problems)

**Comment by yoshimo** [comment]
I am sure it would be helpfull to at least attach a sample email so they can analyse the issue.

**Comment by jimimaseye** [comment]
+1 I also have this occasionally.  Also, often the email body takes a while to 'appear' (whereas before it was more or less as instant as you would expect.

(I also have 2 or 3 other problems with this latest update.  Seriously disappointed - it was a faultless product before and not I have random problems.  Dont worry, I will be reporting them if I can find a way of showing the problem on screenshots - something I cant show in the case of slow responses such as the body appearances).

**Comment by orac1111** [comment]
Tablet was rebooted because of another issue and seems to have fixed the problem so I can now see the email body as well as header.

**Comment by openbrian** [comment]
I have this issue on all emails with an attachment.  This account t is using IMAP.

**Comment by openbrian** [comment]
I have this issue on all emails with an attachment.  This account t is using IMAP.  A reboot did not help.

**Comment by openbrian** [comment]
I have 5.20 installed.

**Comment by openbrian** [comment]
The body of old emails with attachments do appear.  All new emails with attachments do not appear correctly.  But also one new email without an attachment does not appear correctly.  Most are fine.  This one email I mentioned is an automated email from drupal to remind.me to upgrade. Where do I look for error messages?

**Comment by jimimaseye** [comment]
Brian, 2 things:

1,  THe oroginal poster has closed this thread.  If you want your issue to be heard I suggest you start a new one with FULL details.

2,  I Identified a problem in that this new version is not fully accepting of 'all things HTML'.  MY example is this (bear with me and follow this to the end - it is relevant):

An email body of the following body source:

```
<table border='0'> 
<tr><td><!==><!==>Hmailserver service shutdown:</td><td><!==><!==>Ok</td></tr> 
<tr><td><!==><!==>Spamassassin service shutdown:</td><td><!==><!==>Ok</td></tr> 
<tr><td><font color="red"><b>Spam Assassin Def Update:</td><td><font color="red"><b>Failed</td></tr> 
<tr><td><!==><!==>Spam Assassin Service startup: </td><td><!==><!==>Ok</td></tr> 
<tr><td><!==><!==>Hmailserver service startup:</td><td><!==><!==>Ok</td></tr> 
<tr><td><font color="black"></b>Zip:</td><td><font color="black"></b>Ok</td></tr> 
<tr><td><font color="black"></b>Email Cleardown Script: </td><td><font color="black"></b>Ok</td></tr> 
<tr><td><br></td></tr></table>See attached log file below for details. 
```


In the OLD version used to appear correctly as

> 
> Hmailserver service shutdown:	Ok
> Spamassassin service shutdown:	Ok
> **Spam Assassin Def Update:	Failed**
> Spam Assassin Service startup: 	Ok
> Hmailserver service startup:	Ok
> Zip:	Ok
> Email Cleardown Script: 	Ok
> 
> See attached log file below for details. 

(Where the bold is actually in red text)


However, now in the new version it appeared as:

> **Spam Assassin Def Update:	Failed**
> 
> See attached log file below for details. 

Note the missing lines (compared to the correct version).

I needed to change the source to replace the **<!==>** tags with "**<font color="black"></b>**" to make it all appear correctly.

ie,
`<tr><td><font color="black"></b>Hmailserver service shutdown:</td><td><font color="black"></b>Ok</td></tr>
.....`


Now some could argue that <!==> may not be official html tags and that causes the problem (which clearly they do in this new version).  My argument to this is that if they are unofficial HTML tags then they should be ignored and no attempt to interpret them should be made and therefore not alter the display in any way.....which is exactly what happened in previous version.

So this version is not accepting of certain HTML formatting in some way - they have broken something and I suspect that it is this same change that is causing you problems with HTML emails (not necessarily with them containing <!==> tags but who can know what else this version doesnt like rightly or wrongly)
