### ISSUE TITLE
K-9 Mail not showing inline images since last two updates

### ISSUE THREAD

**Issue by ralphsims** [thunderbird/thunderbird-android#1997]
### Expected behavior
Inline images should be displayed

### Actual behavior
Inline images are not displayed
![screenshot_20170106-070121](https://cloud.githubusercontent.com/assets/24960837/21721703/56084c2e-d3de-11e6-9c13-8c8680a98799.png)

Should look like this (snip from outlook):
![capture](https://cloud.githubusercontent.com/assets/24960837/21721977/7b0a27b2-d3df-11e6-8022-cd5043e3c11b.JPG)

### Steps to reproduce
1. Download new email
2. View email
3. Scratch head
4. File issue

### Environment
K-9 Mail version:

Android version:
K-9 Mail 5.201 and 5.202 
android 6.0.1, Samsung Note 5.

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by philipwhiuk** [comment]
There's something weird about the email causing this I assume. It would be useful to get the raw email source to allow us to diagnose it.

**Comment by cketti** [comment]
No additional information provided.

**Comment by Valodim** [comment]
Is the email perhaps a sole image/png file with no other content?
