### ISSUE TITLE
Clipped message text on view

### ISSUE THREAD

**Issue by k9ska** [thunderbird/thunderbird-android#2016]
### Actual behavior
at the bottom of all(?) text/plain messages and some HTML messages lines get clipped from view, one cannot scroll any further down. 

### Steps to reproduce
1. Install K9-Mail since v5.2 (worked before)
2. few attached messages (taken from Maildir, viewed via IMAP)
3. Compare to screenshots

### Environment
K-9 Mail version: v5.202

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

[clipped_messages.zip](https://github.com/k9mail/k-9/files/692267/clipped_messages.zip)

**Comment by cketti** [comment]
Same as #1984?

**Comment by philipwhiuk** [comment]
Looked more like the WebView wasn't being expanded enough to me. Plausible though.

**Comment by cketti** [comment]
Is this still an issue with the latest K-9 Mail version?
