### ISSUE TITLE
Clicking one contact in To selects all contacts

### ISSUE THREAD

**Issue by dllud** [thunderbird/thunderbird-android#2033]
### Steps to reproduce
1. Compose a message.
2. Add several recipients.
3. Click one of the recipients.

### Expected behavior
The full contact info should be shown and cursor should be placed next to the contact. Like this:

![contact-full-info](https://cloud.githubusercontent.com/assets/1716156/21820499/d151d242-d767-11e6-8fd5-657fd1ffe4f0.png)

### Actual behavior
All contacts, i.e. all text in the input box, becomes selected and the the keyboard is shown. The clicked contact's info stays hidden bellow the keyboard.

![keyboard-hides-info](https://cloud.githubusercontent.com/assets/1716156/21820651/776f0d20-d768-11e6-8c63-774710e1a4e8.png)

This bug seems to come from the usage of a text input box. Perhaps that's not the best input box to handle these new contact tokens.
Usually we can select all text in a text input box with a long click. However, here that happens with a simple click, something is odd.

### Environment
K-9 Mail version: 5.202
Android version: 4.2.2

**Comment by luckyluke885** [comment]
I confirm. Same happening to me after last update. I don't like new contacts tokens.

K-9 Mail version: 5.202
Android version: 5.0.2

**Comment by cketti** [comment]
This should be fixed in K-9 Mail 5.7xx.
