### ISSUE TITLE
Can't get rid of folder with umlaut in folder name

### ISSUE THREAD

**Issue by grmblgrmbl** [thunderbird/thunderbird-android#2034]
### Expected behavior
I have changed the folder for drafts to "Drafts" instead of "Entwürfe", and have deleted the "Entwürfe" folder on the server. I have refreshed the folder list on the phone, The folder should now be gone forever.

### Actual behavior
When re-starting K-9, the old "Entwürfe" folder re-appears, and I get sync errors for it (because it does no longer exists on the server). 

`(NegativeImapResponseException: Command: EXAMINE "Entw&APw-rfe"; response: #4# [NO, Mailbox doesn't exist: EntwÃ¼rfe (0.000 secs).])`

When refreshing the folder list, the folder is gone until I restart K-9 again, and then "Entwürfe" is back, etc.

### Steps to reproduce
1. Create folder with umlaut in name
2. Delete folder on server
3. Refresh folder list on phone
4. restart K-9

### Environment
K-9 Mail version: 5.202

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Go to 'Account settings > Folders > Drafts folder' and select your new drafts folder.

**Comment by grmblgrmbl** [comment]
I have done that, as I've said above. I have a "Drafts" folder that is used for drafts, and a un-dead "Entwürfe" folder.

**Comment by cketti** [comment]
Can you please [export the settings](https://k9mail.github.io/documentation/settings/import_export.html) and check if the file contains any reference to the old folder name?

**Comment by grmblgrmbl** [comment]
Yup:

`        <folder name="Entwürfe">
          <value key="inTopGroup">false</value>
          <value key="integrate">false</value>
        </folder>
`

**Comment by grmblgrmbl** [comment]
I've tested this on my tablet, and it's even worse there. Even folders without special characters stay there forever, and after refreshing the folders from the server, I sometimes get three identical inbox folders.

Android 6.0.1
K-9 5.202
IMAP

**Comment by grmblgrmbl** [comment]
I've now gone back to the server, and the deleted folders also reappeared there, even though I have definately deleted them there before. Did K-9 recreate these folders from its configuration?

I've then changed the server to fix the folders there and not accept new folders from clients. Now finally after refreshing the folders in the client, the unwanted folders are gone for good.
