### ISSUE TITLE
Add contact to email shows wrong photo

### ISSUE THREAD

**Issue by kentrob** [thunderbird/thunderbird-android#2057]
### Expected behavior
I click + to add addressee and start typing a name, eg "GU". I have multiple contacts whose name contains those letters. 

### Actual behavior
Addressees are matched but ones with no photos are shown with photos taken from other contacts. Appears to be random.

### Steps to reproduce
1. As above
2.
3.

### Environment
K-9 Mail version:
K-9 Mail Version: 5.202

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
Pop3

**Comment by kentrob** [comment]
I have a screenshot to demonstrate if you email me.

**Comment by philipwhiuk** [comment]
Reproduced on my device.

**Comment by w20151222** [comment]
Reproduced on my device too

**Comment by dschuermann** [comment]
I have the same issue. 

Screenshot where Alice A wrongly uses the photo of Alice B:
![screenshot_20170206-224043](https://cloud.githubusercontent.com/assets/321888/22668549/5b2235fc-ecc1-11e6-8035-927b93f8214b.png)

**Comment by cketti** [comment]
The fact that we're using two image loaders is the most likely cause for this issue.

Scenario:
1. View V is created
2. Image loader X is instructed to load an image for V
3. View V is recycled (different content)
4. Image loader Y is instructed to load an image for V
5. Image loader Y sets image for V
6. Image loader X sets image for V (the corresponding request should have been canceled in step 4)

The best solution is to only use one image loader. That way we avoid having to manually cancel old requests.

**Comment by daquexian** [comment]
@cketti Among the two image loaders, is it better to use Glide or `ContactPictureRetrievalTask`?

**Comment by philipwhiuk** [comment]
Hopefully fixed in #2315 which was released in 5.403
