### ISSUE TITLE
k-9 send to much copies of the same e-mail, because of 'auto save draft' when composing

### ISSUE THREAD

**Issue by jcsantosx** [thunderbird/thunderbird-android#2060]
### Expected behavior
k-9 should replace the old draft already saved with the new one, and not just append to a list and send all together

### Actual behavior
I'm composing an e-mail, then when I switch screen orientation or minimize k-9 to grab a link to insert in that e-mail, 'auto save draft is triggered', click in send e-mail, and send many drafts of this e-mail as he created

### Steps to reproduce
1. Create a new e-mail, then switch screen orientation, because keyboard or to read something not fitted in screen -->> 'auto save'
2. Minimize k-9/Switch to another App --> 'auto save'
3. Send the finished e-mail -->> send previous 'auto save' e-mails + the intended one

### Environment
K-9 Mail version:
last available

Android version:
5.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP @ hotmail

I can't find nothing in settings to change this, but's weird don't find here this issue already reported

**Comment by cketti** [comment]
Overwriting drafts is not possible with IMAP. We create a new one and delete the old draft. It's possible that there's a problem when deleting drafts. But even then only one message is generated when you press the Send button.
Did you actually confirm with the recipient that K-9 Mail is sending out multiple messages? Or does it only look like that when you check your Sent folder using the web interface?

**Comment by jcsantosx** [comment]
Thanks for the quick reply!
On the web interface always shows up a few different instances of the same e-mail on send folder, and on k9 @ android have copies as well, but not from the tests I made today.
What I mean is, the last time I have a record(more than one sent) of this, happened on 11.Jan.2017

I don't know if is relevant, but I have 'auto synchronization of emails/data' disabled.
There's any way I can test the 'deleting of old drafts' to help you out?

**Comment by mhz089** [comment]
This same bug is still present in version 5.600, android version 10, imap @ Gmail.
