### ISSUE TITLE
Server certificate exception not persisted

### ISSUE THREAD

**Issue by ryanammons** [thunderbird/thunderbird-android#2071]
### Expected behavior
Once a certificate exception is accepted, it should remain accepted. 

### Actual behavior
Every server fetch requires re-accepting the certificate as an exception. 

### Steps to reproduce
1. Fetch mail from server using invalid TLS certificate. 
2. Accept the server certificate as an exception. 
3. Fetch mail again. 

### Environment
K-9 Mail version:5.202

Android version:6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
POP

**Comment by tallus** [comment]
Just nothing this effects IMAP accounts as well.

**Comment by DarkerSideUK** [comment]
@ryanammons - so I can check I have the same thing: by certificate exception, do you mean the popup box "Unrecognized certificate", with starting text "The server presented an invalid SSL certificate...."?

To provide some context for others, this is cropping up if you've got email from a custom domain hosted by a hosting provider (Dreamhost, in my case). The SSL certificate is for mail.dreamhost.com, and K-9 is expecting something for customdomain.com. Throws warning, which can be accepted, but the exception doesn't persist.

This wasn't the case before version 5.2.

**Comment by cketti** [comment]
Note: Add logging to `SecureX509TrustManager` and `LocalKeyStore` to figure out what's going on.
