### ISSUE TITLE
Icon to remove a recipient in compose screen is almost invisible in dark theme

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#2083]
Dark theme with "X" button almost invisible:
![k9mail_delete_recipient_dark_theme](https://cloud.githubusercontent.com/assets/218061/22044833/e95da528-dd16-11e6-987f-104c4b972b32.png)

Light theme for comparison:
![k9mail_delete_recipient_light_theme](https://cloud.githubusercontent.com/assets/218061/22044832/e95a1d0e-dd16-11e6-8dcd-89682005bb06.png)

**Comment by mordakk** [comment]
Please reopen. Issue still exists in newest update.

**Comment by cketti** [comment]
The fix will be included in v5.204
