### ISSUE TITLE
Database size is still increasing

### ISSUE THREAD

**Issue by korelstar** [thunderbird/thunderbird-android#2103]
Unfortunately, the fix #2005 is not sufficient for the issue #1917: After updating from 5.202 to 5.203, the database of my IMAP account decreased only a little bit from 3.5MB to 3.4MB. Compressing the account still doesn't change anything and all local messages were deleted before. In 5.0xx, the database has never gone over 1MB.

### Environment
K-9 Mail version: 5.203
Android version: 6.0.1 (CyanogenOS 13.1.5)
Account type: IMAP

**Comment by pmontrasio** [comment]
Maybe it's OK adding a comment to the original issue. I did that just now. See https://github.com/k9mail/k-9/issues/1917#issuecomment-274345233

**Comment by Valodim** [comment]
Versions before 5.2XX didn't save the actual structure of messages but just a rendered html blob. This was done for performance reasons, but imposed severe limitations and made many features actually impossible, like PGP/MIME, moving messages between accounts or even just saving a message into a file. We also use SQLite FTS tables now for fulltext-search, which takes additional space.

Factor three still seems like a lot, but it's not impossible that there is no bug here.

**Comment by korelstar** [comment]
I understand that the new structure consumes more space. But when a message is deleted, all this space has to be freed. But it seems that this is not the case as the following example shows.

Just before I'm writing this, one of my accounts was 2.7MB large. Then I delete all local messages of all folders (Lokale Nachrichten löschen). The account size decreases to 2.5MB. Then I download the messages from the server (still same count and content) and the account is now 2.9MB.

If I repeat this, its going from 2.9MB to 2.7MB and then to 3.1MB. Its increasing every time while the content stays the same! This really looks like a bug, since it never stops.

**Comment by Valodim** [comment]
Oh, that is indeed a bug! Deleting all messages doesn't reproduce this for me :\

**Comment by korelstar** [comment]
My device is not rooted, but I've found the databases under `/storage/emulated/0/Android/data/com.fsck.k9/files/` and analyzed them using the app [aSQLiteManager](https://f-droid.org/repository/browse/?fdid=dk.andsen.asqlitemanager). Before, I deleted the local messages from all folders of that account. Here are the interesting parts of the database. I'm providing row counts *before* and *after* I've re-downloaded the messages (30 items) and deleted all local message. In my understanding, these values should be equal. 

- Table `messages` is empty.
- Table `message_parts`: *before* 1012 rows, *after* 1080 rows.
- Tables `messages_fulltext`, `messages_fulltext_content` and `messages_fulltext_docsize`: *before* 135 rows, after *165* rows.
- Table `messages_fulltext_segments`: *before* 39 rows, *after* 47 rows.

I'm also wondering if the table structure is correct:

- The `fts4` table `messages_fulltext` has only the column `fulltext` but no primary key (e.g. `docid`, which does not exists here!).
- The table `messages_fulltext_content` has columns `docid` and `c0fulltext` but is not of type `fts4`.
- Except for the missing `docid` column, the tables `messages_fulltext` and `messages_fulltext_content` have the same content (i.e. the text of my messages, regardless whether they are deleted).

**Comment by cketti** [comment]
We have database triggers that should delete entries from `message_parts` when messages are deleted from the `messages` table. We delete entries from the fulltext search tables in code. It's odd that both mechanisms seem to fail in your case. Maybe something is up with your database. Can you please try a fresh install?

**Comment by Valodim** [comment]
No wait, can you do in the console:
`sqlite3 yourlongaccountid.db`
then in sqlite:
`select * from sqlite_master where type = 'trigger';`

that lists all triggers, so we might be able to tell a little better what's going on.

**Comment by cketti** [comment]
It looks like we don't clear the `message_fulltext` table when "Clear local messages" is used. So at least that mystery is solved.

**Comment by korelstar** [comment]
I found three triggers: `set_thread_root`, `delete_folder` and `set_message_part_root`. The trigger `delete_message` is missing!

Btw.: is this intended that `MigrationTest.createV50Database()` and `StoreSchemaDefinition.dbCreateDatabaseFromScratch()` both creates a trigger named `delete_message` but with different content?

**Comment by cketti** [comment]
Oh fun. We never created/updated the trigger in the migration :(

**Comment by korelstar** [comment]
Wouldn't it be the best to let the trigger `delete_message` to remove also from `message_fulltext`?

With that database upgrade I (and others) would get this trigger (back) and you could add a deletion for `message_parts` and `message_fulltext` like in https://github.com/philipwhiuk/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/mailstore/migrations/MigrationTo56.java

**Comment by pmontrasio** [comment]
I see you guys are doing a great job towards providing a solution.
As a side note, I can't access ```/storage/emulated/``` either on Android 6 and 7, a Samsung tablet and a Sony phone, both unrooted. I do have an ```Android/data/``` directory in my home but no ```com.fsck.k9/``` in there. It's probably at ```/data/data/com.fsck.k9/``` which is protected. korelstar has CyanogenOS so maybe it stores application data in different locations. Good for us because it makes it easier to debug.

**Comment by korelstar** [comment]
There is still a problem with the fix (but it can be easily fixed). See https://github.com/k9mail/k-9/pull/2137#pullrequestreview-20463252.

**Comment by gcalzo** [comment]
On 5.206 the database is still not cleared completely on my MotoG2 too...
So far I force a "recreate data" on the account to start fresh (IMAP account...)
