### ISSUE TITLE
K9 does not delete message from Server

### ISSUE THREAD

**Issue by nanuit** [thunderbird/thunderbird-android#2117]
### Expected behavior
deleting a message on K9 shoudld elete the message from the server as is configured in the accounts Fetching mail options

### Actual behavior
messages are not deleted from the server but remain there. the local message is deleted
This occurs only with my google account

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by seguri** [comment]
I don't know if this is opened in another issue, anyway:

Expected
Deleting a message should move it to [Gmail]/Trash folder

Actual
K-9 created [Imap]/Trash folder and moved the message there.

Environment
K-9 Mail 5.203
Android 6.0

**Comment by philipwhiuk** [comment]
Probably caused by #752

**Comment by cketti** [comment]
@nanuit: Please record a debug log while trying to delete a message. https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by nanuit** [comment]
[k9-log.txt](https://github.com/k9mail/k-9/files/753647/k9-log.txt)

This log should cover the deltetion process

The error does only occur with one of my gmail accounts. The other (gmail and others) are working fine.
When i delete a mail in my desktop mail client it is deleted in the server also

**Comment by cketti** [comment]
The log ends right before K-9 Mail is attempting to move the message to the Trash folder. The important part is missing.

**Comment by nanuit** [comment]
the command "adb logcat -d -v time k9:V '*:S' AndroidRuntime:E > k9-log.txt" is stop writing at this point and exits.

But i found the problem: the trash Folder (also the other Span, ...) was set to Trash and there is no corresponding Label in my google account. I set it to [Google Mail]\Bin and now it works
Maybe it has to do with the fact, the this is a google apps account and not a gmail
In my Gmail Account there is the [Gmail]\Bin Folder set as Trash and there was no problem
