### ISSUE TITLE
Erroneous "+0 more" messages on Notifications.

### ISSUE THREAD

**Issue by jimimaseye** [thunderbird/thunderbird-android#2121]
### Expected behavior
Since 5.202 occasionally the notifications can show "+0".  This never as witnessed in 5.200 and before.

### Actual behavior
Notifications will show a "+X" number in the expanded notification where the X is the number of new messages exceeding that of the notification displayed messages.

### Steps to reproduce
Cannot reproduce at will - Ive not actually tried to work out how.  However, see screenshots:

Note it says **6 new messages**, yet only displays 5 and then "**+0** more":

![image](https://cloud.githubusercontent.com/assets/15649182/22204164/78efb05a-e168-11e6-87dd-52a601d1e362.png)

![image](https://cloud.githubusercontent.com/assets/15649182/22204193/8d7cba9a-e168-11e6-8d58-bd1a3eb253be.png)

### Environment
K-9 Mail version: 5.203

Android version:  4.2.1

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by philipwhiuk** [comment]
Whether we display the strap line depends on `hasAdditionalMessages()`. Getting them uses `getAdditionalMessagesCount()`.

You'd think these would reference the same list and so this would be fine. But it doesn't.

```
    public boolean hasAdditionalMessages() {
        return activeNotifications.size() > MAX_NUMBER_OF_MESSAGES_FOR_SUMMARY_NOTIFICATION;
    }

    public int getAdditionalMessagesCount() {
        return additionalNotifications.size();
    }
```

This wants reworking.
