### ISSUE TITLE
Response to authentication failure due to password

### ISSUE THREAD

**Issue by jamnew** [thunderbird/thunderbird-android#2134]
### Expected behavior
A user correctly sets up an email account in K9. User changes their password on the email system K9 is connecting to. User has not updated the password set in the K9 account settings.

When an authentication failure occurs due to password, notify the user that the password is incorrect and provide them with a dialog to update the password in K9 account settings.

Don't continually try to authenticate with the server thus potentially triggering account lockouts due to multiple authentication failures in a short span of time.

### Actual behavior
When an authentication failure occurs due to password, no prompt or error is displayed for the user.

Continually attempts to authenticate with server and in our system triggers the account lockout.

### Steps to reproduce
1.Setup an email account in K9
2.Change password in email system
3.Refresh inbox in K9
4.Observe no errors or prompts about incorrect password being displayed
5.Monitor audit log of mail system for authentication failures and lockout

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

[k9-log-extract.txt](https://github.com/k9mail/k-9/files/728243/k9-log-extract.txt)

**Comment by philipwhiuk** [comment]
Your system doesn't appear to be rejecting the login. The only errors in the log are for a loss of network connection. Do you have an IMAP trace showing K-9 getting an Authentication Failure IMAP response code?

We definitely notify the user if we get an IMAP authentication failure.

**Comment by jamnew** [comment]
Thanks for your quick response. Just a bit more information before I attempt to redo the trace to try to capture what you need.

I have performed the test with two other mail clients, Thunderbird (45.3.0) and standard Mail client on iOS and both detect an invalid password and prompt the user to update the password.

At my organisation we manage approximately 110 smartphones of which 95 are Android with K-9 deployed. From my experience I haven't seen K-9 prompt the user for a new password after their password is changed, but I'd love to be proven wrong!

During the trace I collected I was monitoring the server side logs and multiple authentication errors occurred for the test account with reason invalid password, which leads to the other half of this problem where by K-9 will keep trying to login after password failure. Our mail server (Zimbra 8.7) is configured to lockout accounts that have a number of a authentication failures within a period of time. So in our case K-9 is causing accounts to be locked out within moments of the user changing their password.

To make matters worse, even if the user has the initiative to go into K-9 account settings and manually update their password, at this point their account is inevitably locked out, which means when K-9 goes to verify the password they've input it reports the password as incorrect to the user.

Another thing I noticed when I was testing this issue was in between the user updating their password in the email system and them manually clicking the refresh button on the folder view in K-9, K-9 would eventually display a light grey "IOException: readStringUntil(): end of stream reached" under the Inbox, and put an entry in the K9mail-errors (attached).

[k9-ioexception.txt](https://github.com/k9mail/k-9/files/733905/k9-ioexception.txt)

**Comment by cketti** [comment]
We try the `AUTHENTICATE PLAIN` command and when that fails we fall back to using the `LOGIN` command. It looks like by the time K-9 Mail tries to read the response to the `LOGIN` command the connection has already been closed by the server. That causes us to treat this as a connection failure rather than an authentication failure.
