### ISSUE TITLE
Clear local messages -> freeze

### ISSUE THREAD

**Issue by thany** [thunderbird/thunderbird-android#2143]
### Expected behavior
"Clear local messages" should clear the locally stored messages, allowing one to re-download the messages from the server.

### Actual behavior
Freeze.

### Steps to reproduce
1. Have a folder with some large amount of messages. A few hundred should suffice.
2. Make sure it's NOT up-to-date with the server
3. Clear its local messages.

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
If this is reproducible then if you can generate a debug log that might be useful.

**Comment by cketti** [comment]
That shouldn't be necessary. We perform the database operation in the UI thread, which is what causes the freeze.

**Comment by thany** [comment]
A progress indicator might be a good idea then?

**Comment by philipwhiuk** [comment]
No it's just bad design is @cketti's point.
