### ISSUE TITLE
Display of random "MSO" formatting text in HTML

### ISSUE THREAD

**Issue by jimimaseye** [thunderbird/thunderbird-android#2148]
Sorry for the title - I didnt know how best to say it.  I am also guessing at the cause.  The best thing I can do is show you screen shots.

The preface:

I received an email.  On my K9 it looks awful but the same email when view using, for example Thunderbird, it displays all just fine.

I have taken the source of the email, removed non-necessary headers (put there by Yahoo upon delivery), and redacted some links and detail for my privacy (hopefully!).  This attachment, when renamed to being .EML, shows the email as it was received.  (How you get this to display in your K9 test app I dont know but Im sure you have your ways).

[MSOtest.txt](https://github.com/k9mail/k-9/files/737088/MSOtest.txt)

### Expected behavior
Display clean HTML-based email.  As displayed in Thunderbird:

![image](https://cloud.githubusercontent.com/assets/15649182/22399114/0d252c4a-e58e-11e6-8c46-2dd116623912.png)

### Actual behavior
As displayed in K9 Mail:

Part 1:
![image](https://cloud.githubusercontent.com/assets/15649182/22399133/66318aa4-e58e-11e6-8503-e2296677150e.png)

scroll down a bit, part 2:

![image](https://cloud.githubusercontent.com/assets/15649182/22399135/81e76d68-e58e-11e6-9116-56beafbb6549.png)

You can see it is full of .lines such as "**mso-line-height-rule:exactly;line-height:20px; color:#666666;**"

### Steps to reproduce
1.  Get an email to display on your K9 Mail that contains the same message source as the attachment above.

I make no judgement on the cause - you guys know more than me.

### Environment
K-9 Mail version:  5.203

Android version:  4.2.1

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by cketti** [comment]
Looks like HtmlCleaner breaks apart constructs like this:

```html
<td style="font-size:18px <!--[if (gte mso 9)|(IE)]>!important;  <![endif]-->mso-line-height-rule:exactly;line-height:20px;"> </td>
```

**Comment by jimimaseye** [comment]
(Pardon my ignorance) So what happens next in these situations?

**Comment by philipwhiuk** [comment]
Three options:

1. Get HtmlCleaner (upstream project) to handle (i.e. drop) comments inside style attributes before parsing. This is pretty broken HTML that Sky is producing here but they could do better with it. 
2. Branch HtmlCleaner (it's on SourceForge which tells you something about the project) and fix it ourselves. We use a specific configuration on every e-mail so we could get rid of a lot and make it do what we want for our specific use case.
3. Remove HtmlCleaner and just accept that WebKit knows how to handle all this crap anyway so just let it.

**Comment by cketti** [comment]
The HTML5 validator I checked didn't have any objections regarding the attribute value.

I propose for 5.2-MAINT we configure HtmlCleaner with `allowHtmlInsideAttributes` set to `true`. This encoded the angle brackets for me. But I guess that's better than breaking the attribute apart.

For master I'd like us to switch to [JSoup](https://jsoup.org/). I'm using it in another project and like it better than HtmlCleaner.

**Comment by philipwhiuk** [comment]
I would be happy moving to JSoup.
