### ISSUE TITLE
Notification count incorrect.

### ISSUE THREAD

**Issue by jimimaseye** [thunderbird/thunderbird-android#2160]
Whilst running in the background, K9 checks or receives (PUSH) new mail and displays the count in the notification area.  In that area, it used to say the exact number of NEW emails received since the last active user check was performed.

### Expected behavior
Notification shows exact number. 

eg,  It says (for example) 9 NEW MESSAGES and when tapping to display them within K9, 9 new messages would show.

### Actual behavior
This X NEW MESSAGES number often doesnt correspond to the _actual_ number of new messages.  I have noticed this almost every day and carefully applied a test to prove it.  See the following screenshots:

This shows a Thunderbird email client proving how many emails are to be expected on the phone (the test was started at 16:00)

![image](https://cloud.githubusercontent.com/assets/15649182/22480782/8401533a-e7ea-11e6-875d-6b6d6b29bb04.png)

This is the notification as it appears.  Despite there being 9 new messages, it actually says only 5:

![image](https://cloud.githubusercontent.com/assets/15649182/22480860/c5fc9416-e7ea-11e6-832a-3c9c5edf2843.png)

Tapping the notification to display the new messages does show the expected 9 (matching that as reported by Thunderbird):

The first (most recent) 6:

![image](https://cloud.githubusercontent.com/assets/15649182/22480588/d12d42c8-e7e9-11e6-92ec-91bc0a40d8f4.png)

and a scroll down to display the other 3  (below the 17:33 timed email):

![image](https://cloud.githubusercontent.com/assets/15649182/22480900/ee4af52a-e7ea-11e6-8175-0695dfd4b6cc.png)

### Steps to reproduce
1.  Look at k9 - take note of your last email, then leave it alone (running in background/service)
2.  Wait for a number of emails to come in.
3.  After a while, check your phone and see the notifications say X NEW MESSAGES but upon entering you see X+MORE actual new messages have arrived.

NOTE:  This did not happen in version 5.200.

### Environment
K-9 Mail version:  5.203

Android version:  4.2.1

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP

**Comment by jimimaseye** [comment]
As means of extra proof, I waited for the usual incorrect notification to occur overnight (as they do).  The following screen shots once again demonstrate.

Note:  the last MANUAL CHECK in K9 was at midnight.  So all new incoming emails **since midnight** should then show in the notification count.

So, at 8:19 I check the phone. These are the notifications.  Note they say just 1 single email has come in for each of the 3 accounts (Im going to show the first 2 accounts):

![image](https://cloud.githubusercontent.com/assets/15649182/22501243/e0b7e952-e85f-11e6-91a6-e2dc25b4336a.png)


Account 1 - 6 new emails (despite notifications saying and displaying the LAST 1.

![image](https://cloud.githubusercontent.com/assets/15649182/22501344/50d47eda-e860-11e6-958c-3fe89d25bd91.png)


Account 2 - also 6 new emails . Again, the notification shows only the last email.  **INTERESTINGLY - as with the other, the TIME displayed in the notification ("6:51") is not the same time as the actual last email ("6:50").**  This time is more likely the 'incoming time' rather than the actual email date/time as displayed in the emial.  (I will log another issue about this).


![image](https://cloud.githubusercontent.com/assets/15649182/22501477/e2afc45e-e860-11e6-8ad6-a07ebdad39a2.png)

**Comment by cketti** [comment]
This is most likely because the K-9 Mail process is killed at some point and we lose track of which messages are "new".

**Comment by jimimaseye** [comment]
It certainly isnt being killed by me or any 'process killers' on my phone.  So yes it is definitely a bug. (It didnt happen in 5.200)

If it helps there are other erroneous 'notification' problems that happen too.  I will log them separately.

**Comment by cketti** [comment]
Implementing issue #5566 should fix this.
