### ISSUE TITLE
K-9 sometimes does not send a complete MIME header

### ISSUE THREAD

**Issue by svenberkvens** [thunderbird/thunderbird-android#2188]
### Expected behavior
K-9 should send a correct MIME email message.

### Actual behavior
The message contains the MIME stuff (boundaries, headers, etc) in the mail content, but _does not_ send the "MIME-Version" header nor the "Content-Type" header in the email's header part.

### Steps to reproduce
1. Click on the "New message" icon
2. Choose a receiver (yourself if you're testing)
3. Paste a text from a web page into the _Subject_ line of the mail that includes formatting (for example, a text from a &lt;h1&gt;...&lt;/h1&gt;); the text will look formatted in the input box (which I doubt it should, subjects cannot contain formatting)
4. Type an arbitrary body text
5. Send the message

### Environment
K-9 Mail version: 5.203

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### Sent email (source view)
```
Return-Path: <sven@berkvens.net>
X-Original-To: sven@berkvens.net
Delivered-To: sven@localhost
Received: from SvensNote3.dynamic.berkvens.net (whiskers.berkvens.net [80.100.221.128])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mail.csaw.nl (Postfix) with ESMTPSA id 6C702340136;
	Sun,  5 Feb 2017 14:51:37 +0100 (CET)
Date: Sun, 05 Feb 2017 14:51:35 +0100
Subject: Some formatted text
To: Sven Berkvens-Matthijsse <sven@berkvens.net>
From: Sven Berkvens-Matthijsse <sven@berkvens.net>
Message-ID: <5D3A2FF3-A1C6-45CA-80F6-732C87E04424@berkvens.net>
X-SpamProbe: GOOD 0.0351478 7a76b3a682e10d01f73efc258f2dc661

------2LNBJIVCUUGCF2F3DBHG6IYX800DH3
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

Test
------2LNBJIVCUUGCF2F3DBHG6IYX800DH3
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

Test
------2LNBJIVCUUGCF2F3DBHG6IYX800DH3--
```

### Extra information
As you can see above, the email is lacking certain headers that it should have had, as discussed above.

Not sure whether this is related, and I could investigate further if anyone wants me  to, but I use MessagEase as a keyboard. This keyboard allows pasting directly from the keyboard itself. It doesn't matter whether I paste using that function or simply by long-pressing the _Subject_ line and then choosing _PASTE_ from the context menu.

I copied the text from this site: http://www.marktplaats.nl/a/huis-en-inrichting/bureaus-en-bureaustoelen/a1009985199-bureaustoel-bock-burostoel-zwart-verstelbare-armleggers.html . For example, copy the _Bureaustoel Bock_ part of the page.

**Comment by svenberkvens** [comment]
I used Google Chrome to copy the text into the cut-and-paste-buffer, by the way. Perhaps it makes a difference if that browser stores the copied text in some special format and other browsers don't.

**Comment by philipwhiuk** [comment]
This seems interesting. I would not expect the contents of the email to affect whether we send the version header..

**Comment by svenberkvens** [comment]
Isn't the issue in this case caused by the fact that the _Subject_ input field in the UI allows formatted input? Shouldn't it be a plain text input field, as the _Subject_ header in an email cannot contain formatting, even in HTML emails?

**Comment by philipwhiuk** [comment]
If you set the subject as (for example): `<b>Some text</b>` I'd expect us to send and render exactly that (not bold text). If you try and paste formatted text in the subject I'd expect Android to ignore it and give us the plain text when we ask for it.

Looking at the code we call:

`subjectView.getText().toString()`. I wonder if that actually returns encoded HTML...
