### ISSUE TITLE
Non-ASCII sender decoding failed and shown in RAW.

### ISSUE THREAD

**Issue by pingu8007** [thunderbird/thunderbird-android#2222]
### Expected behavior
Show decoded non-ASCII sender in Header section. (Not the [menu/show headers] one.)

### Actual behavior
Shown in RAW.

### Steps to reproduce
1. Send a mail with header formatted in "From:" + BODY prefix something other than space, 
like this: 
`From:=?UTF-8?B?WWFob28h44OA44Kk44Os44Kv44OI44Kq44OV44Kh44O8?= <directoffer-master@mail.yahoo.co.jp>`
or this (I'm not sure if this one meets the RFC requirement):
`From: "=?UTF-8?B?WWFob28h44OA44Kk44Os44Kv44OI44Kq44OV44Kh44O8?= "<directoffer-master@mail.yahoo.co.jp>`
2. Open mail on K-9

### Environment
K-9 Mail version: 5.203

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
Any

**Comment by philipwhiuk** [comment]
This confuses me. It ought to work. `Address.parse()` handles it correctly - decoding it to: 
`Yahoo!ダイレクトオファー`

Even the quoted version works there.

I'm not quite sure why it's not being picked up correctly in the UI. Still investigating.

**Comment by philipwhiuk** [comment]
Fixed in https://github.com/k9mail/k-9/pull/2725
