### ISSUE TITLE
LED blinking is work only when there is sound notification (Android 7.1.1)

### ISSUE THREAD

**Issue by spymorass** [thunderbird/thunderbird-android#2331]
### Expected behavior
There should be LED notification when new mail arrives, even if the ringtone is set to none.

### Actual behavior
There is no LED notification when the ringtone is set to none. If I set it to something, there will be LED notification.

Same settings on Android 6.0.1 work as expected.

### Steps to reproduce
1. Set Blink LED, set Ringtone to None. -> at new mail arrival, no LED notification
2. Set Ringtone to something. -> at new mail arrival, there will be sound and LED notification
3. Set Ringtone back to None -> at new mail arrival, no LED notification

### Environment
K-9 Mail version: 5.203

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by daquexian** [comment]
I couldn't reproduce it on 7.1.1 (PureNexus ROM on Nexus 5) and the same app version

**Comment by spymorass** [comment]
Well... I don't know why, but after a few days it started to work suddenly. I didn't set anything, but the expected setting (no ringtone, led blinking) after the reporting, and now, it works. I couldn't reproduce the false behavior now.

**Comment by lkuchenb** [comment]
Same problem here - BQ Aquaris X Pro stock Android 7.1.1. K-9 5.207 from F-Droid.

LED only blinks when vibration / sound is enabled, otherwise the light won't blink.

**Comment by spymorass** [comment]
@cketti: Can you reopen this issue? I have a new phone (OP5, 7.1.1), and I can't have the LED blinking without vibration and sound notification. If you or somebody could guide me, I will happily debug it! Thanks!
