### ISSUE TITLE
New feature proposal: Show new mail instead of unread mail (notification)

### ISSUE THREAD

**Issue by ProfPh** [thunderbird/thunderbird-android#2414]
### Expected behavior
If I have K9mail check for new messages every 60 mins, it comes back every 60 mins saying 100 unread messages. I would have thought the expected/desired behaviour is to say 1 new message (since last sync) or don't notify if 0 new messages since last sync.

### Actual behavior
There is no such button.

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

**Comment by rishsethia** [comment]
Hi , I want to work on this !

**Comment by ProfPh** [comment]
@rishsethia great!

**Comment by cketti** [comment]
Duplicate of #2018
