### ISSUE TITLE
PGP block sent as HTML is not recognised by K-9 as encrypted data

### ISSUE THREAD

**Issue by iminderN** [thunderbird/thunderbird-android#2422]
When an email encrypted using symantec encryption desktop is send via outlook (by copying and pasting the pgp block), the k-9 client cannot decrypt it because it fails to recognize the data as a pgp block. If we click "Send as plain text" in outlook while sending the same pgp block, it is recognised correctly. Please find attached screenshots for same:
![screenshot_20170321-160337](https://cloud.githubusercontent.com/assets/22820969/24174910/a484597c-0e50-11e7-874a-fa057a38dbaa.png)
![screenshot_20170321-160047](https://cloud.githubusercontent.com/assets/22820969/24174911/a49b66d0-0e50-11e7-9c00-48df6219a72a.png)

**Comment by philipwhiuk** [comment]
I think this is OpenKeychain not supporting the Encryption Desktop version.

**Comment by Valodim** [comment]
Hi! Parsing pgp blobs out of html is not something we do right now, but it might make sense to do so. Can you please send an affected mail to me? -> `look@my.amazin.horse`, pgp `0xdeadfa11`. Thanks.

**Comment by pshem** [comment]
I'm fairly sure I ran into another instance of this bug: encrypted Facebook notifications. 
If you have NOT activated cryptography on your account and get such a message, the message will appear blank and won't give you a chance to do anything with it. There will be a 69B noname.pgp attachment that can't be decrypted even when you have the right private key in OpenKeychain. 
This should give you an easy way to replicate the bug: make a new email address, get a PGP key and a Facebook account on it, try to add notifications.

**Comment by kivadiu** [comment]
I see the exact same message ("Error decrypting email. No encrypted data...") with messages sent from thunderbird. The messages are multipart messages like the one attached to this message.

[encrypted_email.txt](https://github.com/k9mail/k-9/files/1420950/encrypted_email.txt)

**Comment by te0006** [comment]
any news regarding this issue? It is rather unfortunate as Symantec Encryption Desktop is quite widely used on Windows, and HTML mail is often set as the default in the Outlook mail client.

**Comment by minj** [comment]
This is annoying me every second time when sending from Thunderbird.

@cketti is needs-info still valid on this issue?

Is help needed? I could try solving this provided it's not a huge undertaking and I get some pointers.
