### ISSUE TITLE
Downloading complete message removes star

### ISSUE THREAD

**Issue by dalb8** [thunderbird/thunderbird-android#2475]
K9 5.205 
If I star message then press the button to download the complete message the star disappears

**Comment by philipwhiuk** [comment]
Probably related to #697 - I think 'Download Complete Message' doesn't use the MessagingController.

**Comment by Prabashi** [comment]
K-9 mail version: 5.207
The same incident happened to me. But it was only in some instances, in the other instances I checked, the star still appeared. Is that possible? I would like to work on this, why I'm interested to know.Thank you.

**Comment by philipwhiuk** [comment]
It's almost certainly a race condition as to whether you see it or not.

**Comment by Prabashi** [comment]
I checked again and it seemed to be random and therefore your comment is certainly the answer. Thank you for the comment.
I also noticed that, the star keeps disappeared only until the refreshing is done. After refreshing it is starred again.
The star disappears in both views; near the topic when entered into the message body to download it, and near the title when moved back to the inbox. 
So, is the **expected behaviour** : It keeps starred in both views after pressing 'Download Complete Message' ?
I would like to work on this, if there's anything I should be knowing, please let me know. Thank you.

**Comment by philipwhiuk** [comment]
Yes. Downloading the message shouldn't affect whether it appears starred.

As I said above the fix is more than like to use the MessagingController's task processing system for downloading the complete message,

**Comment by Prabashi** [comment]
[https://github.com/k9mail/k-9/pull/2801](url)

**Comment by Trogel** [comment]
This way I can reliably reproduce this issue:

1. Turn off automatic sync, for example set "Poll folders" and "Push folders" to "None". (This avoid that automatic sync repairs the error before it can be observed.)
2. Have an unstarred, large mail in some IMAP folder.
3. Go to the folder list, long-tap the folder, and do "Clear local messages".
4. Open the folder, manually check mail, and open the unstarred, large mail.
5. Click the star to make the message starred.
6. Click "Download complete message". -> The star is lost, which is bad.
7. Go back to the message list. -> The star is missing here, as well, which is also bad.
8. Manually check mail. -> The star appears, which is good.

**Comment by Trogel** [comment]
@philipwhiuk, @Prabashi, it seems that "Download complete message" already uses the `MessagingController`: The button calls the method `downloadCompleteMessage` of the `MessageLoaderHelper` that in turn (via some other methods) calls `loadMessageRemote` of the `MessagingController`. This runs `loadMessageRemoteSynchronous` in the background. So, this should be fine.

However, I found something else that could explain this bug. When called from the "Download complete message" button, `loadMessageRemoteSynchronous` essentially does [this](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java#L2341):

    FetchProfile fp = new FetchProfile();
    fp.add(FetchProfile.Item.BODY);
    remoteFolder.fetch(Collections.singletonList(remoteMessage), fp, null);
    localFolder.appendMessages(Collections.singletonList(remoteMessage));

Note that the `FetchProfile` does not contain `Item.FLAGS`. Thus, after `remoteFolder.fetch` the `remoteMessage` contains no flags at all. Then `localFolder.appendMessages` updates the message in the local store from `remoteMessage` and deletes all its flags, accordingly. (By the way, it also deletes the `read` flag, but few lines later this is set again, at least if "Mark as read when opened" is checked.)

The message in the local store gets "repaired" on the next sync, as @Prabashi already observed.

**Comment by Trogel** [comment]
A possible fix would be to insert `fp.add(FetchProfile.Item.FLAGS);` in the above code. I tried it and it seems to do the right thing. As a side-effect, it also seems to fix issue #697. Please see the upcoming pull request.

**Comment by cketti** [comment]
Fixed by #2808
