### ISSUE TITLE
Error decrypting email

### ISSUE THREAD

**Issue by nuntius35** [thunderbird/thunderbird-android#2479]
I received an email which I can decrypt with Thunderbird/Enigmail but K-9 Mail fails saying `error decrypting email`. How to find out what's wrong? The email looks like this.

```
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_47_423025285.1491209971352"
X-ASIC-VIRUSCHECKED: YES

------=_Part_47_423025285.1491209971352
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

-----BEGIN PGP MESSAGE-----
Version: Cryptix OpenPGP 0.20050418
```

Some data...

```
-----END PGP MESSAGE-----

------=_Part_47_423025285.1491209971352
Content-Type: application/octet-stream; 
	name="Some File Name.pdf.pgp"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; 
	filename="Some File Name.pdf.pgp"
```

A lot of data...

```
------=_Part_47_423025285.1491209971352--
```

### Environment
K-9 Mail version: 5.206
OpenKeychain version: 4.2.4

Android version: 4.2.2

Account type: IMAP

**Comment by Valodim** [comment]
Hm, from looking at it this could be various things. I've never heard of cryptix openpgp either.

Would you be able to send such a message to me? -> look@my.amazin.horse, pgp 0xdeadfa11

**Comment by Valodim** [comment]
Got the mail, gonna investigate when I have time. Thanks!

**Comment by nuntius35** [comment]
My issue was the same as described in [Openkeychain Issue No 2413](https://github.com/open-keychain/open-keychain/issues/2413). Unfortunately I got the emails by a different company.

**Comment by nuntius35** [comment]
Sorry, the reason I gave for closing the issue was perhaps misleading. In the original issue the reason for the failed encryption was a missing MDC. It is only that I got a new mail of the same kind, and here the issue is OKC 2413. Anyway, the debug messages from Openkeychain now contain enough information that I was able to figure out the problem in each case.
