### ISSUE TITLE
Export settings  does not export 'Support signing of unecrypted mail' setting

### ISSUE THREAD

**Issue by aelmahmoudy** [thunderbird/thunderbird-android#2503]
If I set 'Support signing of unecrypted mail' option, then export the settings, then clear K9 mail app. data, then import the settings, the 'Support signing of unecrypted mail' option does not get set.

**Comment by GoneUp** [comment]
Found the bug. 'openpgpSupportSignOnly' in GlobalSettings vs. 'openPgpSupportSignOnly' in K9. Is it safe to just edit the GlobalSetting without bumping the version?

**Comment by aelmahmoudy** [comment]
This issue still persists in version 5.208

**Comment by philipwhiuk** [comment]
It's not been backported to the 5.2x branch.
