### ISSUE TITLE
Attachment disappears after downloading complete message

### ISSUE THREAD

**Issue by JohnVeness** [thunderbird/thunderbird-android#2543]
### Expected behavior
While viewing a message with an attachment larger than the maximum size of a downloaded message, after clicking the "Download complete message" button, the attachment stays visibly listed.

### Actual behavior
The attachment is no longer showing after the message body.

### Steps to reproduce
1. Ensure account settings are set to download, say, up to 32KB of a message
2. Send yourself a message with an attachment larger than 32KB
3. View the message in K-9
4. Observe that if you try to forward the message, you get a toast saying that non-downloaded attachments won't be forwarded - this confirms that the attachment hasn't been downloaded yet
5. Click "Download complete message"
6. Observe that the attachment disappears

Note: this does not happen every time, so it may be something specific to the message. I have a particular message to which this reproducibly happens, but I don't want to post it in public. If a developer is willing to work on this, I can send it to them.

### Environment
K-9 Mail version: 5.206

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
Please fill out the rest of the template. Also, please provide the device logs - see https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by JohnVeness** [comment]
Sorry, I created the issue on my phone and the template didn't appear. I have now filled it in. I will try to obtain the debug log later.

**Comment by cketti** [comment]
Is this still happening with the latest K-9 Mail version?

**Comment by JohnVeness** [comment]
I can't say I've seen this problem recently, so it may be fixed. Probably worth closing for now.
