### ISSUE TITLE
Cannot fetch contents of old mail from IMAP server

### ISSUE THREAD

**Issue by wtobi** [thunderbird/thunderbird-android#2552]
### Expected behavior
When I search for an older email which is not on my device but on the IMAP server, I'd expect to be able to find and read it.

### Actual behavior
The mail is found, and its subject and other info is shown. But when I open it, then no content is displayed. When I hit reply, there is an animated "waiting circle" at the top, and still no contents.

It works with other mail apps and programs, so I doubt it is an issue with my mail provider.

### Steps to reproduce
1. Search for mail.
2. Hit search on server.
3. Click on mail.

### Environment
K-9 Mail version: 5.206

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
[k9-log.txt](https://github.com/k9mail/k-9/files/1032679/k9-log.txt)

**Comment by rhari991** [comment]
Related to issue #699

**Comment by cketti** [comment]
The message is not processed further because it falls outside of the configured time window. We need to ignore that for messages we fetch outside of a regular sync.

**Comment by cociweb** [comment]
Still the same on 5.303.
Android 5.1
Imap - gsuite (formerly google apps): imap.gmail.com

**Comment by philipwhiuk** [comment]
Closing in favour of #3111 where I show the call stack and got the same conclusion as @cketti
