### ISSUE TITLE
New email screen stays open (when sharing from another app)

### ISSUE THREAD

**Issue by MrM40** [thunderbird/thunderbird-android#2568]
The new-mail-screen stays open in the background, even when the mail is sent successfully.
But this only happens when creating a new mail from another app, e.g. the photo app (share a picture and select K-9). When the mail is sent and you push the switch-open-apps-button you will see the new-mail-screen is still open and you will not be able to close it until you discard the new mail.

### Expected behavior
The new-mail-screen should close when the mail is sent

### Actual behavior
The new-mail-screen stays open in the "background" when pushing the "switch-open-apps" button (showing all open apps).

### Steps to reproduce
1. From e.g. Photos select a picture, push "share it" and select K-9
2. Insert To, Subject, Body and sent
3. Push the "switch-open-apps" button
4. The new-mail-screen did close

### Environment
K-9 Mail version: k.206
Android version: 7.0
Phone: Moto G4 plus (Motorola's Android phones are just as clean as the Nexus)

Account type (IMAP, POP3, WebDAV/Exchange): POP3 setup

**Comment by csomesh** [comment]
Hey, I wish to work on this issue.
Will you assign this to me.

**Comment by philipwhiuk** [comment]
GitHub doesn't allow you to assign it to a non-project member. But feel free to work on it and submit a PR.
