### ISSUE TITLE
A lot of crashes with android 7.0

### ISSUE THREAD

**Issue by Xwang1976** [thunderbird/thunderbird-android#2569]
I have k9 installed on some devices, but the only one with android 7.0 suffers of crashes which do not happen in android 4.4.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:5.206

Android version:7.0

Account type (IMAP, POP3, WebDAV/Exchange):imap

**Comment by cketti** [comment]
Please record a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by rogerval** [comment]
I'm having this problem too with a new Moto G5 with android 7; the crash happens fairly randomly while I'm reading an email, and then going back to the list of emails in a folder.
I've attached a debug log and a screenshot showing my firmware version.
[k9-log_170715.txt](https://github.com/k9mail/k-9/files/1150130/k9-log_170715.txt)
![about moto g5 phone](https://user-images.githubusercontent.com/28846333/28237218-a74e95b8-697d-11e7-8241-d541590bf94d.png)
Hopefully this is some help in finding the bug.
Thanks for your help,
Roger V.

**Comment by rogerval** [comment]
[debug 170716.txt](https://github.com/k9mail/k-9/files/1150578/debug.170716.txt)

**Comment by cketti** [comment]
Closing because no further information was provided.
