### ISSUE TITLE
List loses selection after rotating display

### ISSUE THREAD

**Issue by meetthemeat** [thunderbird/thunderbird-android#2605]
### Expected behavior
When I select (by swiping the elements left) one or more EMails in the "unified inbox" or "all messages" list view the items should be still selected also when I rotate the display/screen so that I can execute an action.

### Actual behavior
When I select (by swiping the elements left) one or more EMails in the "unified inbox" or "all messages" list view the selected items are no longer selected when I rotate the device screen from portrait to landscape view. 

### Steps to reproduce
1. Open K9 Mail while holding the device in portrait view
2. In the accounts overview tap on Unified Inbox
3. Select on or more EMails by swiping them to the left
4. Rotate the device into landscape view
5. the selection gets lost

### Environment
K-9 Mail version: 5.206

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP, SMTP

**Comment by marwendoukh** [comment]
Could someone please assign me to this issue . I have started working on it .

**Comment by philipwhiuk** [comment]
Can't assign issues to non-project members.

**Comment by marwendoukh** [comment]
My PR has been closed , please remove the "being worked on" label .

**Comment by madduck** [comment]
This issue can be closed.
