### ISSUE TITLE
SQLiteDiskIOException: disk I/O error (code 1802) when querying DB from MessageController Thread

### ISSUE THREAD

**Issue by rogerval** [thunderbird/thunderbird-android#2627]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
K9 should open emails and allow them to be read and change folders to read other emails without suddenly stopping

### Actual behavior
After reading an email, K-9 will occasionally (at least once a day) crash for no apparent reason, and I have to re-start it.

### Steps to reproduce
1. Tap on K-9 icon to open it
2. Navigate to a folder
3. Open an email
4. Use phone's back button to exit email; K-9 may crash at this point.
5. Use phone's back button again to change to another account; K-9 may crash at this point (if not before). This behaviour isn't consistent, unfortunately.

### Environment
K-9 Mail version: 5.206

Android version: 7.0 on Moto G5 phone

Account type (IMAP, POP3, WebDAV/Exchange): pop3 (six accounts in all)

See attached screen shot for more Android info; also see attached debug log.

Thanks for reading this report,
Kind regards,
Roger V.
![about moto g5 phone](https://user-images.githubusercontent.com/28846333/28242315-7f7e1e46-69eb-11e7-8f76-98dbf5c93666.png)
[debug 170716.txt](https://github.com/k9mail/k-9/files/1150587/debug.170716.txt)

**Comment by rogerval** [comment]
Upgraded to version 5.207 yesterday just in case it fixed the crash; unfortunately the problem still persists. (I realise this crash wasn't in the change log. :-) )

**Comment by rogerval** [comment]
Did further testing today with version 5.208, and noticed that I can sometimes provoke a crash by this sequence of events (but like my original report, this isn't consistent.) :
1 Tap on k9 icon
2 Long press on an account 
3 Select Settings
4 Tap on Fetching Mail
5 Change "Folder Poll Frequency" to another time interval (or "Never")
6 Tap back button twice to go back to Accounts screen
k9 may crash at this point (but not always).
I've got all accounts set to "Never" at the moment, as I've been using Blue Mail to read my mail over the last few months. (It's not perfect either.)
I've attached a log file in case this helps diagnose the crash.
Kind regards,
Roger V.
[Text of bug report for k-9 email 171222.txt](https://github.com/k9mail/k-9/files/1580433/Text.of.bug.report.for.k-9.email.171222.txt)

**Comment by rogerval** [comment]
Hi everyone,
Just started using version 5.400 and I'm sorry but the crash is still happening. I've attached a log file in case this helps with diagnostics.
Kind regards,
Roger V.
[Text of bug report for k-9 email 171230.txt](https://github.com/k9mail/k-9/files/1593824/Text.of.bug.report.for.k-9.email.171230.txt)

**Comment by cketti** [comment]
Probably a hardware defect.
