### ISSUE TITLE
If From & To "to long" it show "null" instead of the e-mail/name 

### ISSUE THREAD

**Issue by yabba** [thunderbird/thunderbird-android#2717]
If From & To string might be "to long" it shows "null" instead of the e-mail/name.
Also if "invalid" e-mail-strings like "Domains <@info>" were used.

So far I can see:
From: Length of 75 character shows, with 78 character -> null
To: Total length with 63 characters shows "null".

This happens in e-mail overview listing and at the single e-mail view ()

Android 7.0, K9 5.207

### Expected behavior
at least shortened String. of existing From/To

### Actual behavior
If From & To string might be "to long" it shows "null" instead of the e-mail/name.

So far I can see:
From: Length of 75 character shows, with 78 character -> null
To: Total length with 63 characters shows "null".

### Steps to reproduce
Open e-mail in overview and detail.

### Environment
K-9 Mail version: K9 5.207

Android version: Android 7.0 (Samsung)

Account type (IMAP, POP3, WebDAV/Exchange):
Independent from Account Type.

**Comment by cketti** [comment]
Can you provide the raw headers of such a message?

**Comment by yabba** [comment]
Well, no. I will not post on public or to unknown persons full headers of real e-mails or real e-mail addresses of persons I have no permission to publish their e-mail. You should know that this no good idea. Sorry. :)

I know of my own experience it is hard for a programmer to believe. Check it out with the information I gave in the description. I tried and tested those parameters. Check it yourself: Create an e-mail-address of those length, send test-mails to yourself and you should see the result. :)

If you have other questions I try to help as far I can.

best regards,
Stefan

**Comment by philipwhiuk** [comment]
```
From: Philip Whitehouse <philip@whiuk.com>
To: Test <@info>
```

This works fine on master

**Comment by yabba** [comment]
Well, _not_ only 36 Character. The effect happen, like I wrote:

> From: Length of 75 character shows, with 78 character -> null
> To: Total length with 63 characters shows "null".

Example:
`From: "asdfg.hjksłfg fgr.htśzufeńrhtz, dfjghkężutfuz, dhfj.dfjg, ftgk" <aname.blablub@anydomain.com.us>`

I got another shorter one today with non ASCII characters and a bit shorter:
`From: "Mirosław Grzęda, Blabla A.C." <mimimi@somewhere.org>`

or something like:
`From: "dcztjt efcwdeecdäöñwd" <aname.blablub@anydomain.com.us>, "gcldgclçgcls gkd sdÖü" <aname.blablub@anydomain.com.us>`

I just installed Version 5.208
Are there differences through that and master?

**Comment by philipwhiuk** [comment]
There are many differences - master will become 5.300 - only a few bugfixes got ported to 5.208. I don't think this particular bit of code has changed that much though.

I'll try the ones you gave.

**Comment by cketti** [comment]
K-9 Mail doesn't yet support [RFC 6532](https://tools.ietf.org/html/rfc6532) that allows usage of non-ASCII characters in email headers. If the "personal" part of an email address contains non-ASCII text that is not using 'encoded word' encoding K-9 Mail won't be able to correctly handle it.

This fails to properly decode as well:
```
"ł" <a@b.c>
```

This valid encoded-word variant of the example above is decoded fine by K-9 Mail:
```
=?UTF-8?B?xYI=?= <a@b.c>
```

We already have an issue to add support for internationalized email support (#2633) so I'm closing this one.
