### ISSUE TITLE
S/MIME signed emails in sent folder misleadingly shown as PGP encrypted mails

### ISSUE THREAD

**Issue by luckyrings** [thunderbird/thunderbird-android#2776]
### Expected behavior

I am using S/MIME to sign e-mails on my computer. When I open sent mails in k9 mail app on my smartphone the mail body is shown correctly, I can read the sent message, because it is just signed. I also see the attachment (signature file" smime.p7s") there.

### Actual behavior

Since last update the S/MIME signed mails are shown correctly in AutoPreview (I see text there), but after clicking on them to open the mail and read the full message. Instead a message "this mail is encrypted / This e-mail is with OpenPGP encrypted. To read it you need compatible OpenPGP-App installed and configured / Choose OpenPGPG app" appeaers and I have no chance to read the message.

### Steps to reproduce
1. use a s/mime to sign e-mails from your computer
2. open the sent mail on your smartphone with k9 mail app
3. then this message appears

### Environment
K-9 Mail version: 5.300 (installed 11th Sept. 2017)

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by luckyrings** [comment]
Message header of example mail in sent folder. Mail is just signed, not encrypted:

To: xxxx xxxxxx <xxxx@xxxxxx.xx>
From: xxxxxxxxxx <xxxxxxxxx@xxxxxxxx.xxx>
Subject: Source Code
Message-ID: <78524ee3-4568-0c75-3cc7-392cd43c484f@xxxxxxxxx.xxx>
Date: Fri, 9 Jun 2017 23:30:09 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.1.1
MIME-Version: 1.0
Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-256; boundary="------------ms060504040203090201030403"

**Comment by Valodim** [comment]
I see the issue, that is indeed a bug. Thanks for your report! :+1:

**Comment by legoktm** [comment]
Just noting that I'm also seeing a similar issue, but with PGP signed messages that aren't encrypted. I assume it's the same cause, but just wanted to make sure that the proposed fix will also cover PGP signed messages.
