### ISSUE TITLE
original message is missing on forward and changed from:

### ISSUE THREAD

**Issue by gshollingsworth** [thunderbird/thunderbird-android#2784]
### Expected behavior
The orignial message text should be included when forwarding and changing the from: address. This is what happens when forwarding without changing the from: address.
### Actual behavior
The original message is missing from the forwarded email.
### Steps to reproduce
1.have two gmail accounts setup
2.forward a message but change the from: address to the other account 
3.type in message text
4.send
5.get reply from confused recipient about missing original message referenced in forward email.

### Environment
K-9 Mail version:
5.208
Android version:
7.0 August 1, 2017 security update applied
Account type (IMAP, POP3, WebDAV/Exchange):
gmail default config IMAP

**Comment by cketti** [comment]
Is this still an issue with the latest K-9 Mail version?

**Comment by gshollingsworth** [comment]
This is no longer an issue with the latest K-9 Mail version. I just tested it.
