### ISSUE TITLE
Graphic bug when opening an email thread while polling the folder

### ISSUE THREAD

**Issue by hallexander** [thunderbird/thunderbird-android#2788]
### Expected behavior
The list of messages in the selected thread should appear

### Actual behavior
The list of messages in the selected thread shows up *behind* the original message listing. 

### Steps to reproduce
1. Enable threaded view in global settings
2. Enter a folder that has threaded messages in them. 
3. Swipe down to initiate a folder poll.
4. *While the folder is being polled*, tap a threaded entry to show the complete message list for the thread.

### Environment
K-9 Mail version: 5.300

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by dbpruett2004** [comment]
Fuck pff

**Comment by Trogel** [comment]
The same happens when doing "More from this sender" while the refresh animation is running. Both cases are caused by same Android bug: https://issuetracker.google.com/issues/37008170
