### ISSUE TITLE
Opening a message while sort-by unread moves message from previous view

### ISSUE THREAD

**Issue by SevereOverfl0w** [thunderbird/thunderbird-android#2812]
### Expected behavior

When using sort-by unread, opening a message and pressing next/prev will use the same ordering I saw before clicking on the message.

### Actual behavior

Opening the message causes the order to shift, and next/prev no longer make much sense. The message moves as it is now read. Unfortunately this makes viewing a few messages in the middle of a thread very difficult.

### Steps to reproduce
1. Change ordering to sort-by unread
2. Open Message
3. Click next/previous arrow doesn't go to where it was previously

### Environment

K-9 Mail version: 5.208

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP/SMTP

**Comment by cketti** [comment]
Opening the message marks it as read, which changes the position of the current message in the message list.

**Comment by cketti** [comment]
Fixed by #6271
