### ISSUE TITLE
Time zone unknown parsed as UTC

### ISSUE THREAD

**Issue by softArgenton** [thunderbird/thunderbird-android#2814]
in the Date: mime header 
UTC itself appears as +0000; −0000 means the time zone essentially unknown.

### Expected behavior
Dates with -0000 should not be converted to UTC

### Actual behavior
For example i've received two messages one after the other
first one: Date: Wed, 27 Sep 2017 11:41:18 -0000 
second one: Date: Wed, 27 Sep 2017 11:42:40 +0200

I live in italy and the first one results in K9 received at 13.41 that is wrong,

### Environment
K-9 Mail version: last

Android version: all supported

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by softArgenton** [comment]
excuse the first message (the one with -0000) is not from Italy 
i enclose part of the mime header....

Received: from mta05.email.it ([127.0.0.1])
	by localhost (mta05.email.it [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id na9pejxgK551 for <operations@argenton.com>;
	Fri, 29 Sep 2017 11:54:30 +0200 (CEST)
Received: from stewns1.skyfile-access.com (stewns1.skyfile-access.com [193.252.234.132])
	by mta05.email.it (Postfix) with ESMTP id 1095F264194
	for <operations@argenton.com>; Fri, 29 Sep 2017 11:54:16 +0200 (CEST)
Received: by mailer.les-raisting.de (SkyFile);
	Fri, 29 Sep 2017 09:54:15 -0000 (GMT)
Date: Fri, 29 Sep 2017 11:55:01 -0000
Message-ID: <000001d33919$c839e780$58adb680$@transocean.atseamail.com>
X-Mailer: Microsoft Outlook 14.0
Thread-Index: AdM5GcMtdNoMI4woTuiCmUfGQC5JEw==
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="--PART--573875248-M-"

**Comment by philipwhiuk** [comment]
I think this is caused by 

https://github.com/apache/james-mime4j/blob/7a54eebe73a582ee9ead995a4e783d3e190fcf47/dom/src/main/javacc/org/apache/james/mime4j/field/datetime/DateTimeParser.jj#L271 

making no special allowance for -0000

**Comment by cketti** [comment]
Related: #1356

**Comment by schlagi123** [comment]
Hi,

https://tools.ietf.org/html/rfc5322#section-3.3
> [...] Though "-0000" also indicates Universal Time, it is used to indicate that the time was generated on a system that may be in a local time zone other than Universal Time and that the date-time contains no information about the local time zone. [...]

I understand the specification so, that -0000 means UTC, but can also because the system do not know the timezone. In this case I think the only meaningful interpretation is UTC.

Here is another [discussion ](https://github.com/chronotope/chrono/issues/102) about this toppic, with the [result](https://github.com/chronotope/chrono/issues/102#issuecomment-557846963), that -0000 is interpreted as UTC.

For my understanding, the ticket is then ready and can be closed, if there is no need for further discussion.

**Comment by cketti** [comment]
Sounds reasonable.

@schlagi123: Thanks for the research.
