### ISSUE TITLE
PGP mails signed with wrong key

### ISSUE THREAD

**Issue by rugk** [thunderbird/thunderbird-android#2815]
### Expected behavior
When encrypting & signing a mail, K9 mail should use the key for the sender's mail (specified in "From:").

### Actual behavior
K9mail may use the wrong key – without any user feedback.

### Steps to reproduce
1. Add multiple private keys to OpenKeyChain.
2. Create new mail, change identity (sender) mail.
3. Mail may still be signed with the main PGP key for another identity/mail used.

### Environment
K-9 Mail version: 5.208

Android version: LineageOS 14

### Possible solution
* short-term (bug fix): Get mail from senders field and use correct key (-> the purpose of this issue)
* long-term: https://github.com/k9mail/k-9/issues/2510 and https://github.com/k9mail/k-9/issues/942

/cc @Valodim

**Comment by cketti** [comment]
Is this still an issue with the latest K-9 Mail version?

**Comment by rugk** [comment]
I have not noticed it again, but I also do not have multiple private keys anymore in OpenKeyChain.

**Comment by cketti** [comment]
Thanks. Chances are it has been fixed since then. If not, someone else will eventually run into it and open a new issue. Closing this one.
