### ISSUE TITLE
Bug leaks sensitive content: account email addresses shown on locked phones

### ISSUE THREAD

**Issue by mfc** [thunderbird/thunderbird-android#2823]
### Expected behavior
When the phone settings are set to "Settings > Configure notifications > On the lock screen: Hide sensitive notification content", K-9 Mail should not display any sensitive content about accounts or emails. It should just say `Contents hidden`.

### Actual behavior
Even though the phone settings are set to "Hide sensitive notification content", K-9 Mail displays the different email addresses set up through K-9 Mail as it checks for new messages with each account. This is leaking sensitive content about the user of the phone (ah they have this email address, that email address, etc). It would be the equivalent of a chat app displaying the username in the Notifications when they get a new message even if they have told the app to hide sensitive content on notifications. Or their phone number when receiving a phone call, etc.

### Steps to reproduce
1. Set up multiple email accounts in K-9 Mail
2. Set up phone to hide sensitive notification content
3. Lock phone
3. Watch K-9 Mail check for new mail and reveal account addresses

### Environment
K-9 Mail version: v5.208

**Comment by mfc** [comment]
i'm going to change the title to better reflect the bug, maybe will help with getting a response and some labels.

**Comment by mfc** [comment]
for any others who encounter this, a workaround is to disable these default-on notifications:
1. go to each account you have in k-9 mail
1. Settings > Account settings
2. Notifications > disable "Sync notifications"

**Comment by DJCrashdummy** [comment]
IMHO the best solution to solve this issue would be to hide the account address but still somehow show the account color to still indicate the account for the device owner who (sooner or later) knows the corresponding accounts.
