### ISSUE TITLE
5.301 plain-text body rendering issues

### ISSUE THREAD

**Issue by njeyaakili** [thunderbird/thunderbird-android#2856]
It appears that somewhere between 5.208 and 5.301 some issues were
introduced in the rendering the body of (single-part) plain-text messages. 

For instance, a message that ends with:

     Davide

     ------------------------------------------------------------------------------
     Check out the vibrant tech community on one of the world's most
     engaging tech sites, Slashdot.org! http://sdm.link/slashdot
     _______________________________________________
     Bacula-users mailing list
     Bacula-users@lists.sourceforge.net
     https://lists.sourceforge.net/lists/listinfo/bacula-users

is displayed in 5.301 as:

     DavideCheck out the vibrant tech community on one of the world's most
     engaging tech sites, Slashdot.org! http://sdm.link/slashdotBacula-users mailing list
     Bacula-users@lists.sourceforge.net
     https://lists.sourceforge.net/lists/listinfo/bacula-users

If I forward the message from a 5.301 client the bottom text block is displayed correctly in the draft.

There additionally appears to be a problem with hyperlinking. If the "http://" or "https://"" starts in column one it is not hyperlinked. If it starts in column 2+ it is.

In 5.208 the message renders correctly and all "http://" and "https://" urls are hyperlinked regardless of their column start position.

**Comment by cketti** [comment]
Thanks for reporting this. But in the future please create one GitHub issue per problem you discovered.

I created issue #2861 for the linkify issue.

**Comment by njeyaakili** [comment]
Thanks. 5.302 seems to have cleared up the issues I reported.
