### ISSUE TITLE
Emails with attachments can get sent multiple times

### ISSUE THREAD

**Issue by kbehel** [thunderbird/thunderbird-android#2858]
### Expected behavior
Email should only be sent once

### Actual behavior
Email gets sent about five times

### Steps to reproduce
1. Send an email with an attachment
2. 
3.

### Environment
K-9 Mail version: 5.208

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange):
Pop3

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by kbehel** [comment]
Update - after some testing it appears to also happen with emails without an attachment.

However I do something unusual which could be the cause - I bcc myself on all emails sent from my phone (don't ask - it works for me). I also see a random number of duplicates. I speculate that the number of duplicates relates to the quality of the internet connection (reliable vs. flaky) and the bbc operation.

I will post a debug log.

**Comment by kbehel** [comment]
Close this issue.  
I did some checking with Earthlink - they say its an issue with their servers. Let's see if it gets fixed soon or reappears for people with other providers.
