### ISSUE TITLE
URL at the beginning of a line in plain text body isn't linkified

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#2861]
This happens because we first convert the plain text to HTML and end up with something like:

```html
<br>http://uri.example.org<br>
```

But right now only supported schemes preceded by a space, a newline, or an opening parenthesis are candidates for linkifying.

https://github.com/k9mail/k-9/blob/27bc562ebe37bc139b84c13142681dbfe5640688/k9mail/src/main/java/com/fsck/k9/message/html/UriLinkifier.java#L16

**Comment by torantal** [comment]
![img_20180315_131909](https://user-images.githubusercontent.com/6267029/37462853-9d165cf8-2853-11e8-87ec-b7b2b7a9fbf8.png)
I seem to have a similar issue with URLs not linkified, or why would the < > enclosed URLs not be clickable?
