### ISSUE TITLE
Notification dissapears mid marking items as unread (when polling?)

### ISSUE THREAD

**Issue by TheBlueMatt** [thunderbird/thunderbird-android#2872]
I love the per-mail detail view on notifications, and often use it to mark things unread that I don't care about one at a time. However, occasionally, after marking one (or more) messages as unread, the remainder of the notification dissapears (though the mails are still there/marked unread). It doesn't happen reliably, but maybe about 10-20% of the time I dont get through more than one or two emails before the rest dissapear. I at some point started assuming it happened when a different new mail comes in at the same time, or during poll, but now I just have that cached and not sure that I have any real evidence of that.

Haven't seen any correlation with Wifi/LTE/switching networks, etc.

Server is my own courier-imap server.

K-9 v 5.208 (though also have seen the issue roughly since the per-mail detail notification thing was added).
Latest Android (Pixel 2, though also on my 5X, and since the per-mail notifications were added).

**Comment by cketti** [comment]
This should be fixed by implementing #5566
