### ISSUE TITLE
notification area opens account instead of inbox

### ISSUE THREAD

**Issue by voxspox** [thunderbird/thunderbird-android#2917]
After new mails have been received there is an entry in the notification area (upper left). Pulling the notification area down I can see K9-Mail, account name and mail subjects. When I tap on this, K9-Mail is opened and the folder list of this account is shown. I expect to see the inbox here.

## Environment
K-9 Mail version: 5.208

Android version: 7.1.2 (LineageOS 14.1)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by aucklander** [comment]
Same on 8.1 on pixel stock, pressing on the notification takes me to the the folder view, not inbox.
But some email accounts work normally and i cant find the setting anywhere.
I recall this has been an issue for a long time now.

**Comment by elem089** [comment]
Just observed the same on my rather new OnePlus 6 / OOS 9 (Android Pie)
Not really serious, but are there any news on that topic?
