### ISSUE TITLE
Missed translation resources for 2 strings

### ISSUE THREAD

**Issue by bboa** [thunderbird/thunderbird-android#2941]
Hi, seems that translation missed for this (or related) string in K-9 builds ("Cryptography"). https://imgur.com/a/8AHyJ
Also, probably missed localization string in caption (More from this sender -> "From") for this or related string: https://imgur.com/a/khhlR

Please add the resources that we can translate with Transifex. Regards

K-9 Mail version: 5.304
Android version: 4.4
Account type (IMAP):

**Comment by philipwhiuk** [comment]
Thanks for reporting it!

I've raised PRs to fix both of these :)

**Comment by cketti** [comment]
PRs merged.
