### ISSUE TITLE
NPE in ImapConnection following settings import

### ISSUE THREAD

**Issue by khwolf** [thunderbird/thunderbird-android#2968]
https://github.com/k9mail/k-9/blob/1a12b18f0c4a452b74941340179735f0383bd1fb/k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapConnection.java#L525

When no password is set (e.g. after import of settings) a nullpointer exception is thrown. That is not very helpful for the user.

**Comment by philipwhiuk** [comment]
I have to say I thought we just didn't try at all if the password wasn't set. But it's a pretty simple fix.

**Comment by MJ10** [comment]
@philipwhiuk I would like to work on this. Can you tell me how to reproduce this? Will help in fixing the issue.

**Comment by philipwhiuk** [comment]
@MJ10 Try following the steps @khwolf gave - export account settings, import them and see if ImapConnection throws an NPE. Then write a unit test that reproduces the error. Then fix it.

**Comment by cketti** [comment]
Please open a new issue if this is still a problem in K-9 Mail 5.7xx.
