### ISSUE TITLE
Email with different font colours not displaying correctly

### ISSUE THREAD

**Issue by rancidfrog** [thunderbird/thunderbird-android#2983]
Email which uses different coloured text, i.e. to mark distinction between answer and/or response...
Are displayed all with same colour.

Also,
Colours in body of html email are rendered differently depending on theme, light theme displays font colour correctly, dark theme always same colours displayed

**Comment by philipwhiuk** [comment]
If you don't change the colours in dark theme it's likely that the text will be invisible.

You say "which uses different coloured text, i.e. to mark distinction between answer and/or response... are displayed all with same colour."

But are you sure the actual email uses different colours. 

Some email software shows indented ( `>` ) text in a different colour even when there's no actual colour change in the email itself.

We could start doing that. But that's not the same as not showing the colours that do exist.

**Comment by rancidfrog** [comment]
Yes, the email uses different colours for some texts. But, k9 displays font as black all the time for normal mails in light theme. And, white font colour for dark theme.
Thunderbird displays email correctly with both coloured fonts with no issues.
K9 does not display font colour regardless of app theme. 
Unless it is specifically html where in light theme displays correct background colours and fonts.
However, dark theme does not display html format colours correctly. 

Also, there is an issue with setting: "Display settings | Fixed message theme"
It ways displays "Message view theme" regardless of checkbox, making checkbox useless; i.e. I set Message view as dark then uncheck checkbox and app theme is light but still message view is dark. So why is message view disabled when it is still being followed,
![](https://i.imgur.com/CDbt6S0.png)
As seen above in image, unable to change message view setting even though whatever is selected is being displayed in message view.

In all cases, font colour is only followed when message view is light theme and email is specifically **html** 
- Can we have an html render button to view emails as html so that font and background displayed correctly regardless of theme?
Something like the button Switch to dark|light theme in menu for message view -> switch to html view ?

**Comment by philipwhiuk** [comment]
> As seen above in image, unable to change message view theme setting even though whatever is selected is being displayed in message view. 
> In the case above message view is displayed as dark because that is what was selected before unchecking setting.

This is because you've unchecked the box above which allows you to select a theme every time you view a message.

**Comment by rancidfrog** [comment]
Yes, but if it is not fixed then why is it still following the disabled setting.
you can test it, enable checkbox, change to light, disable checkbox, now message view is light.
My point is what should it follow if unchecked, app theme?
currently it follows whatever was set before unchecking

**Comment by philipwhiuk** [comment]
If you uncheck it, it may default to the last selected item. But it's changeable every time you load a message, so changing the value makes little sense.

**Comment by cketti** [comment]
Please attach the HTML source of such a message.

**Comment by rancidfrog** [comment]
Is there way a save copy of email to internal storage, sdcard?
As I only seem to be able to show headers and not view source in app

**Comment by rancidfrog** [comment]
Using thinderbird view source, the email had an html part with <font> tags for each change in font colour,
```
<div><font color=3D"#26282a" style=3D"font=
-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-siz=
e: 13px;">=C2=BFWhat happened to photography? </font><font style=3D"font-fa=
mily: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: =
13px;" color=3D"#440062">I still snap one or two when there are&nbsp;</font=
><font face=3D"Helvetica Neue, Helvetica, Arial, sans-serif"><span style=3D=
"font-size: 13px;"><font color=3D"#440062">incentives (traveling, etc. </fo=
nt><font color=3D"#26282a">)</font></span></font><br><font color=3D"#26282a=
" style=3D"font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-=
serif; font-size: 13px;">
And, =C2=BFLenses? </font><font style=3D"font-family: &quot;Helvetica Neue&=
quot;, Helvetica, Arial, sans-serif; font-size: 13px;" color=3D"#440062">No=
 more lenses </font><br>
<br><font color=3D"#26282a" style=3D"font-family: &quot;Helvetica Neue&quot=
;, Helvetica, Arial, sans-serif; font-size: 13px;">
Oh.</font>
```

There is both `Content-Type: text/plain; charset="UTF-8"` and afterwards `Content-Type: text/html; charset="UTF-8"` where the above example is taken from.

**Comment by cketti** [comment]
Thanks. We currently strip the `color` attribute from `<font>` tags.

This will be fixed in the next K-9 Mail version.

**Comment by rgpublic** [comment]
Hm. Just to understand better: Why was this closed? If I enable the dark theme, no background-colors are shown. I'd say this is a bug. Why can't I see e.g. a green background-color of some table cell if I'm not using the light theme? Should I file a new bug?

**Comment by cketti** [comment]
It's already fixed in the development version. But there hasn't been a public release with that change yet.

**Comment by rgpublic** [comment]
Okay. I've created #4198 as a follow-up. Thanks for the clarification.
