### ISSUE TITLE
Crash opening mail from mailing list

### ISSUE THREAD

**Issue by coogor** [thunderbird/thunderbird-android#2990]
I'm subscribed to the cups.org mailing list. Quite often K9 crashes when opening a mail from the list

### Expected behavior
Well...it should display the mail :-)

### Actual behavior
Crash

### Steps to reproduce
1. open mail
2. it starts to render, suddenly K9 is crashed
3.

### Environment
K-9 Mail version: 5.208

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

I attach on ot the mails that causes a crash

**Comment by coogor** [comment]
file:///home/docb/Dokumente/[cups] Brother HL-3140CW started printing misaligned pages.mbox

**Comment by coogor** [comment]
Hm, looks like attaching a mail does not work. Drop me a PM so I will send one mail

**Comment by philipwhiuk** [comment]
You can attach it using the GitHub web interface or forward it to the address on my GitHub profile.
