### ISSUE TITLE
Body in decrypted mails empty by reply or forwarding

### ISSUE THREAD

**Issue by webratte** [thunderbird/thunderbird-android#3004]
### Expected behavior
If I click reply or forward, the body of the original mail should be filled with the whole original text and maybe attachments by forwarding .

### Actual behavior
There is only the header (Mailadress and so on) and the subject line of the original mail

### Steps to reproduce
1. Receive a encrypted mail
2. Decrypt this mail
3. Click reply or forward
4. See there is no quote and no attachment (by forwarding) 

### Environment
K-9 Mail version: 5.400

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please provide the message source of an email that doesn't show up as quoted text when replying.

**Comment by webratte** [comment]
Hi,

what exactly do you need?
I can offer:

-The sendet mail (encrypted and decrypted) from the senders device (e.g. my PC with Thunderbird and enigmail)
-The received mail (encrypted and decrypted) from the receivers device (my phone with k9 mail)
-The encrypted mail after reply from the senders device (my phone with k9 mail)
-The received mail (encrypted and decrypted) from the receivers device (e.g. my PC with Thunderbird and enigmail)

I can reproduce it every time.

And where can I send this message source.
I don't want make my mails public ;-)

**Comment by webratte** [comment]
Hi,
is there anybody out there? ;-)

**Comment by mnieke** [comment]
I have the same issue but I don't know how message sources can help, as their content is encrypted.
I can also reproduce it with two different mail accounts and PGP keys.
It does not happen for me when mails are not encrypted.

**Comment by webratte** [comment]
Hi, 
are you interested in my offer?
Please let me know if I can help and what exactly you need (as I said before)

This issue is really important I think.

**Comment by Valodim** [comment]
Sorry about the radio silence. Put this in my todo list, I'll look into it when I have time

**Comment by webratte** [comment]
Hi, no hurry.
I know you work hard on this great App and I never want nerve.

Thank you for your reply.

**Comment by Valodim** [comment]
Found it. It was a rather stupid bug, sorry about the inconvenience. Thanks for reporting :+1:

**Comment by webratte** [comment]
Thanks,
great to read it's fixed now 😀

**Comment by webratte** [comment]
Hi, 
is there a chance to see this release (maybe as Beta version) very soon.

I miss a working reply function.

It would be great.
Thank you for your great work.
