### ISSUE TITLE
Images in body of YouTube e-mail notifications are no longer displayed

### ISSUE THREAD

**Issue by xbarbie** [thunderbird/thunderbird-android#3006]
### Expected behavior
Images in e-mail body should be displayed. 

### Actual behavior
Images are not displayed. As far as I know, this is issue with YouTube e-mail notifications only. Everything worked fine until the last update. Now, also the older messages (received before the update) are affected by this bug. Deleting K9's cache and restarting device did not help.

### Steps to reproduce
1. Open the e-mail message
2. Images are blank, as seen here:

![1514642673241](https://user-images.githubusercontent.com/232523/34455901-6d6da2f4-ed89-11e7-96df-c30c151d8178.png)

### Environment
K-9 Mail version: 5.400

Android version: 5.0.1 (tablet), 5.1.1 (smartphone)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Can you please attach the message source of such an email.

**Comment by xbarbie** [comment]
OK, here it is:
[original_msg.txt](https://github.com/k9mail/k-9/files/1601067/original_msg.txt)

**Comment by cketti** [comment]
The email uses a `table` tag with a (long deprecated) `background` attribute to display the images :(
Our HTML sanitation step currently throws away the `background` attribute and that's why the images aren't showing.

The next K-9 Mail version should include a fix for this.
