### ISSUE TITLE
"Strip signature on reply" not always applied

### ISSUE THREAD

**Issue by Meteor0id** [thunderbird/thunderbird-android#3009]
### Expected behavior
When replying on e-mail back and forth, my signature is added each time. I expect the option "strip signature on reply" to prevent this from happening.

### Actual behavior
After replying to an email, my signature is added. The other side replies, and I reply again, now the email has my signature in it twice. And with every reply from my side another signature is added.

### Steps to reproduce
1. create a signature, either for an identity or in composition default
2. turn on strip signature on reply in account settings
3. send a message and send it back and forth by replying to it a few times.

### Environment
K-9 Mail version:
5.400

Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by Meteor0id** [comment]
please rename this bug report "strip signature on reply doesn't seem to be working" for clarity.

**Comment by cketti** [comment]
The description of the setting reads "Signatures will be removed from quoted messages". So this is completely unrelated to the signature that is added (or not, depending on your identity config) when composing the reply.

Works as intended.
