### ISSUE TITLE
Prefer To over X-Original-To when determining recipient identity

### ISSUE THREAD

**Issue by Meteor0id** [thunderbird/thunderbird-android#3011]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
reply to the e-mail with the identity the email was send to
(note: this is not the same as always replying with the identity which has highest priority, that woudl also be acceptable, but rplying with the identity which received the email would be best)

### Actual behavior
the inital account is selected by default, instead of the identity which received the email. Even the identity priority is ignored.

### Steps to reproduce
1. create account
2. add new identity
3. prioritise new identity over inital identity
4. send email to newest identity
5. attempt to reply to received email (and notice the wrong identity is assumed)

### Environment
K-9 Mail version:
5.400

Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
The ordering of the list is just an ordering. Aside from the top one it's just a convenience thing I think. 

I agree that if an email is sent to an identity it's reasonable to expect that it should default to replying on that identity. (Not everyone will agree possibly).

#935 has more ideas on this.

**Comment by teicher** [comment]
I'm pretty sure identity selection was better in 4.x
Only since the upgrade to 5 a few days ago, I have to always manually select the correct identity.

**Comment by teicher** [comment]
(sorry got something wrong with the version numbers. let's just say it stopped working a week or so ago)

**Comment by philipwhiuk** [comment]
It's definitely supposed to do what you suggest: 

https://github.com/k9mail/k-9/blob/d0c8cc3b57a26bfc9c722075bdf041ab7c4a649c/k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java#L1261-L1267

Not quite sure why it doesn't right now.

**Comment by teicher** [comment]
Ok, so this change:
https://github.com/k9mail/k-9/commit/06e5f790bb11c1f48a75ed0e4f31deef423120dc#diff-553a50174a36e41b6232be8ab196b42d
puts "X_ORIGINAL_TO" over "TO"

But for me this is wrong. I have multiple addresses that are all directed to the same inbox, and I see in the message source that the MTA ("ESMTPS (Nemesis)") puts a "X_ORIGINAL_TO" with the mailbox name, regardless of the "TO".

So, as I see it, the fix would be to reverse the order of "X_ORIGINAL_TO" and "TO" check in IdentityHelper.getRecipientIdentityFromMessage()

Skol, Tom.

**Comment by philipwhiuk** [comment]
This was from #1407

The ordering was a user request. I don't know enough about X-Original-To to know what the right behaviour is:

@Kyoshiro-san do you care if we put To before X-Original-To?

**Comment by Kyoshiro-san** [comment]
Hi,

No it's alright to prioritize To over X-Original-To headers, my request was for K9mail to be able to detect configured identities using X-Original-To along with To/Cc headers when replying so it's all good :)

Cheers

**Comment by huehnerlady** [comment]
Hi,

I have the same problem that I have to manually select the identities.
I can see it is fixed. when can we expect to be able to get that update via google play?

Thanks
