### ISSUE TITLE
Bad <hr> detection causes emails to appear empty

### ISSUE THREAD

**Issue by Metaspace2** [thunderbird/thunderbird-android#3018]
Some emails displayed empty, despite there is text in the email body. 
Note: Email preview in notification window shows (part) of body; but email body seems empty in K9.

This behavior has been introduced with the latest K9 update a few days ago.

### Expected behavior
Email displayed correctly.

### Actual behavior
Email shown empty. When using "Reply" on the mail, no email body is shown, the wait cursor is shown indefinitely.

### Steps to reproduce
Not sure why some emails get not displayed. I could provide the emails not correctly shown if needed.

### Environment
K-9 Mail version: 5.400

Android version:
7.1.1 and also 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by Schwefelholz** [comment]
I am experiencing this issue as well. Actually recognized it with mail from Amazon. I can also confirm mails being shown empty when replying or forwarding.

**Comment by ennorehling** [comment]
I have the same problem. Sometimes it manifests as an empty email body, sometimes entire folders being shown as empty, even though they contain dozens of messages, in which case force-killing and restarting K9 sometimes works. I'm providing an example email here:
https://gist.github.com/ennorehling/419c876cccb6cb96d5b68c6b150e9751

**Comment by DPTJKKVH** [comment]
I experience the same bug, when replying to a message.

**Comment by cketti** [comment]
Thanks to the message provided by @ennorehling I was able to reproduce this. Expect this bug to be fixed in K-9 Mail 5.401.

**Comment by Metaspace2** [comment]
Great news, thank you for your effort!

@enno: Small world. I used to play "your" Eressea for a few years :-)


Cheers guys,

-Roman

-----------------------
Dipl.Ing. Roman Benesch
Roman.Benesch@chello.at
+43-699-12-60-80-90

**Comment by ennorehling** [comment]
I can confirm that this is now fixed for me. Thank you for the quick response!

**Comment by DPTJKKVH** [comment]
For me the bug still exists after upgrading to 5.401. When I reply to an email the quoted email is empty.

**Comment by cketti** [comment]
@DPTJKKVH: Then it's most likely a different problem. In any case please open a new issue and provide a message that triggers this behavior. Otherwise there's no way we can fix the bug.

**Comment by Metaspace2** [comment]
For me as well, fixed. Thank you very much! That was amazingly fast! :)

On January 3, 2018 11:29:15 PM GMT+01:00, Enno Rehling <notifications@github.com> wrote:
>I can confirm that this is now fixed for me. Thank you for the quick
>response!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/3018#issuecomment-355145929

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
