### ISSUE TITLE
Text in Action Bar cut off with larger than normal system font size

### ISSUE THREAD

**Issue by Canonshooter** [thunderbird/thunderbird-android#3047]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
The text should be visible 

### Actual behavior
Tell us what happens instead
The text is overlaid by box below the text

### Steps to reproduce
1. Open any folder 
2. Error is beside the k9 mail icon on top of screen 
3.

### Environment
K-9 Mail version:
5.402
Android version:
7.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Can you provide a screenshot of the display bug?

**Comment by Canonshooter** [comment]
https://www.dropbox.com/s/0z5wctuav2e8rdb/Screenshot_20180105-115901.jpg?dl=0

**Comment by Canonshooter** [comment]
Cketti
Link to Dropbox added.

**Comment by cketti** [comment]
This is no longer an issue in `master`.
