### ISSUE TITLE
<center> doesn't stretch to full width

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#3052]
k9
![screenshot_20180106-033959](https://user-images.githubusercontent.com/5685512/34635717-d4895604-f293-11e7-95ab-aaec8f5dc186.png)

thunderbird
![thunderbird_2018-01-06_03-40-05](https://user-images.githubusercontent.com/5685512/34635722-e2c9625e-f293-11e7-90bd-7ecbeff533a1.png)

Of course this is due to the fact, that mail uses more than one center tag, but still:
if one container stretches the viewport, then other containers like center should also reach that width.

**Comment by Djfe** [comment]
totally forgot to add the .eml file ^^
[mail.zip](https://github.com/k9mail/k-9/files/1608435/mail.zip)

**Comment by philipwhiuk** [comment]
We're stripping the center tag. I've added a fix to my PR to improve Html Parsing - #3051

**Comment by Djfe** [comment]
also: do you know, why the one table is being pushed into the next line?
It should be next to the image (all in one line)

![screenshot_20180121-094955](https://user-images.githubusercontent.com/5685512/35192356-f5fd50fc-fe90-11e7-8aa2-99a048f661c6.png)

**Comment by philipwhiuk** [comment]
I'm not sure about the new line thing. But we've fixed the table bug in f69ac0662aa96eb1081c781c8ffdf37c637ea09c
