### ISSUE TITLE
Confusing "Inbox" which is not the Inbox, when tapping on notification of multiple new mails

### ISSUE THREAD

**Issue by Rhialto** [thunderbird/thunderbird-android#3092]
I have several folders. Most are set to be polled (second class for push), just one, the Inbox, is set to be pushed (1st class for push). In the "Fetching mail" settings I have "Poll folders" set to "1st &2nd" (only 2nd isn't possible) and Push folders to "only 1st". At least I hope I set this correctly. No mailbox is set to be shown in the "unified inbox".

When K9 puts up a notification that there are several new mails, and I tap on it, then...

### Expected behavior
I expect that the Inbox is opened, or possibly, a mailbox corresponding to one of the messages from the notification. (There are also notifications of single emails, which open the particular email directly. The issue does not pertain to this case.)

### Actual behavior
However, I seem to get a sort of unified inbox of ALL unread messages (not just the new ones since last notification) from all polled and pushed mailboxes alike (or maybe from just the mailboxes that contain new messages; this is difficult to see). The heading however is Inbox. This is very confusing, because many of these messages are not actually in the Inbox.

When I leave this "Inbox" by tapping on the < top-left, and then tap on Inbox, I do get the Inbox as I expected it.

### Steps to reproduce
1. See above, basically

### Environment
K-9 Mail version: 5.403 (ok, my own variant with the old icons, from https://github.com/Rhialto/k-9/releases )

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Now tracked under #5565
