### ISSUE TITLE
"message too large server" not shown

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#3119]
If I attach a file over the attachment menu (document handler of android), I get this helpful error message, when the message ends up again in drafts after sending a mail with a 60mb attachment.
But when I attach it by sharing a file from whatsapp to k9, then it ends up in drafts without any error message.

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
