### ISSUE TITLE
Subject only decoded in part .

### ISSUE THREAD

**Issue by kodomoyeh** [thunderbird/thunderbird-android#3125]
I got raw subject like 
Subject: =?UTF-8?B?W+aWsOioguWWrl0g6aGn5a6iOiB4eHhAeHh4LmNvbSDmnInmlrDoqILllq46ICMyMDE4MA==?=
                                                                   	=?UTF-8?B?MTE4MTIzNDU2Nzg=?=

It separate in 2 lines , k9 only parse the first line
### Expected behavior
K9 should parse all lines

### Actual behavior
Tell us what happens instead
 k9 only parse the first line
### Steps to reproduce
1. Use Gmail to send mail to address used in k9
2. In Subject , paste [新訂單] 顧客: xxx@xxx.com 有新訂單: #2018011812345678
3. Send it out.

### Environment
K-9 Mail version:

master branch 
commit 63010dd4deea64a323de0036d97ef15fca3277ff

**Comment by philipwhiuk** [comment]
Hmm really? That's annoying. I thought I fixed this in #2725

**Comment by philipwhiuk** [comment]
On my build I can't reproduce the bug - K-9 decodes: 

```
Subject: =?UTF-8?B?W+aWsOioguWWrl0g6aGn5a6iOiB4eHhAeHh4LmNvbSDmnInmlrDoqILllq46ICMyMDE4MA==?=
    =?UTF-8?B?MTE4MTIzNDU2Nzg=?=
```

correctly.

**Comment by kodomoyeh** [comment]
3r3wr

2018-01-23 11:50 GMT+08:00 Kodomo Yeh <kodomoyeh@gmail.com>:

**Comment by kodomoyeh** [comment]
I add some dummy code to verify this :
In  \k9mail-library\src\main\java\com\fsck\k9\mail\internet\DecoderUtil.java

public static String decodeEncodedWords(String body, Message message) {

    body = "=?UTF-8?B?W+aWsOioguWWrl0g6aGn5a6iOiB4eHhAeHh4LmNvbSDmnInmlrDoqILllq46ICMyMDE4MA==?=
=?UTF-8?B?MTE4MTIzNDU2Nzg=?=";

the function return "[新訂單] 顧客: xxx@xxx.com 有新訂單: #20180"

But if you paste the enceded String in http://dogmamix.com/MimeHeadersDecoder/

You will get [新訂單] 顧客: xxx@xxx.com 有新訂單: #2018011812345678

In the function decodeEncodedWords , it only parse the first part


2018-01-23 11:50 GMT+08:00 Kodomo Yeh <kodomoyeh@gmail.com>:

**Comment by kodomoyeh** [comment]
I've check the  patch commit f88c3594fca933014cc64b1168c60856cc0091bd
is it ok to combined 2 encoded string like below ?
word.encodedText = previousWord.encodedText + word.encodedText;

**Comment by philipwhiuk** [comment]
Wow I'm an idiot. Clearly 3am coding. I did get the bug.

Yes recombining them should be fine (in fact it fixed a bad bit of behaviour from some clients). I'll look why it's not providing the second part.

**Comment by kodomoyeh** [comment]
I dont think recombination is rational .
base64 regenerate an word for every 6 bit , and will add zero bite if nncessary.
That means 123 =>(base64 encode)  MTIz
456=>NDU2
123456 => MTIzNDU2 recombining  works ONLY when 1st String with length %3 = 0
An failed case is like 
12 => MTI=
34 =>MzQ=
1234 => MTIzNA==

**Comment by philipwhiuk** [comment]
The reason for re-combination is when you get:

1234 => =?UTF-8?B?MTI?= =?UTF-8?B?zNA==?=

instead of
1234 => =?UTF-8?B?MTIzNA==?=

**Comment by kodomoyeh** [comment]
i think they are separatly encoded.
1234 => =?UTF-8?B?MTI=?= =?UTF-8?B?MzQ=?=
and it doesn't work to combined before decode as MTIMzQ=
At least the original case you paste could prove that.
=?UTF-8?B?W+aWsOioguWWrl0g6aGn5a6iOiB4eHhAeHh4LmNvbSDmnInmlrDoqILllq46ICMyMDE4MA==?=
=?UTF-8?B?MTE4MTIzNDU2Nzg=?=
it's able to decode W+aWsOioguWWrl0g6aGn5a6iOiB4eHhAeHh4LmNvbSDmnInmlrDoqILllq46ICMyMDE4MA==
and
MTE4MTIzNDU2Nzg=
at https://www.base64decode.org/
But it doesn't work for 
W+aWsOioguWWrl0g6aGn5a6iOiB4eHhAeHh4LmNvbSDmnInmlrDoqILllq46ICMyMDE4MA==MTE4MTIzNDU2Nzg=

**Comment by philipwhiuk** [comment]
We saw this in: https://github.com/k9mail/k-9/issues/2499#issuecomment-326541951 which @cketti pointed out in: #2719

**Comment by kodomoyeh** [comment]
I guess the case in #2499 is out of spec RFC2047

**Comment by philipwhiuk** [comment]
Yeah - I spent quite a lot of time adding tests for everything in the spec and also making it work on the non-compliant case - hence grumpy that's it's still broken in some way.
