### ISSUE TITLE
twitter background image - td element

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#3138]
the background images (for previewing videos in the twitter e-mails) aren't displayed for some reason.

[twitter.zip](https://github.com/k9mail/k-9/files/1667936/twitter.zip)

Could you pls take a look? :)

Regards,
Djfe

**Comment by philipwhiuk** [comment]
```
<td background=3D"https://pbs.twimg.com/amplify_video_thumb/956232701509492=
736/img/5S41cqa34QBAVBKm.jpg:large" class=3D"playable" style=3D"padding:0px=
;padding:0px;background-color:#ffffff;background-repeat:no-repeat;backgroun=
d-size:100%;">
```

Looks like we need to add `background` to `td`.

The JSoup relaxed whitelist is way too restrictive :(

**Comment by Djfe** [comment]
yep, atm. only table has background on the whitelist, but not td.
Just an assumption: Is JSoup's default whitelist optimized for html5 or so, so that they didn't think all these "legacy" attributes aren't neccessary anymore?

**Comment by cketti** [comment]
Maybe we shouldn't. Not adding every deprecated attribute will probably increase the pressure on senders to fix their ancient HTML templates.

**Comment by philipwhiuk** [comment]
`td background` isn't even deprecated. It's not in the HTML 4 spec. https://www.w3.org/TR/html4/index/attributes.html

Bad form @twitter

**Comment by Djfe** [comment]
I fear, k9 isn't big enough for that sadly (pressure).
K9 should support features other mail clients support as well. (IMHO)
But it's definitely not the ideal way :/

Some people tried in the past to establish some standards, which kind of helped, I think.
Those minimal sets, don't include stuff like background as it's own attribute, only as part of the css.
https://www.email-standards.org/acid-test/index.html

Is there a way to kindly tell/ask twitter? (nvm you mentioned them ^^, let's see, maybe they'll reply and be kind enough to take a look)

**Comment by Djfe** [comment]
Twitter isn't alone, YouTube also uses the background attribute on ``` <table> ``` tags to show the thumbnail in livestream announcements.
