### ISSUE TITLE
Bug in k-9 mail app setup new account section which leads app to crash.

### ISSUE THREAD

**Issue by iamank1t** [thunderbird/thunderbird-android#3204]
#### Expected behavior
When i enter invalid email format while setting up a new account on app, app needs to show me error of invalid email format instead of creating my account.

#### Actual behavior
On setup new account section of app i entered invalid email format(i used .@iamankit.com) in email address field and the app created my account with that invalid email format without giving me error. Creating account with invalid email format is the first bug and second bug is app crashed when i try to compose a email after account setup.

#### Proof that email format i used is invalid 
![Screen Shot 2018-02-19 at 11.19.55 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519062677/bzbfzrzn0jwxch2j7w5p.png)

#### How to reproduce
To reproduce the the bugs follow the steps :-
- Open app and go to set up a new account section of app.
- In email address field enter this email address <pre>.@something.com</pre>
- Type your password and click next button.
- Select account type as IMAP in next screen. After selecting you came to internal server settings screen. (I suggest you to see recording of bug for better understanding of reproduce the bug steps.)
- Now just press back button two times, pressing back button two times close the app. Open app again and you see your account is set with invalid email format. 
- Now try to compose mail and you see when you click on compose mail button the app got crashed.

<pre><code>* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v5.403
</code>
</pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=Purx3ZIldSI

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/bug-in-k-9-mail-app-setup-new-account-section-which-leads-app-to-crash">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by philipwhiuk** [comment]
This is the rule:

>  period (".") may also appear, but may not be used to start or end the
   local part, nor may two or more consecutive periods appear.

**Comment by MJ10** [comment]
Hey @philipwhiuk what should be the correct behaviour? I would like to fix this issue

**Comment by philipwhiuk** [comment]
We should both prevent that invalid email address format from being created and fix the crash.

**Comment by MJ10** [comment]
Okay. Thank you @philipwhiuk I'll try fixing it and send a PR

**Comment by cvoges12** [comment]
I have this as well. I'm on LineageOS nightly and this is a new install with no google services. I'm not sure if google services are required so I'm wondering if that will be helpful information. It worked fine on my device before I switched from Android to LineageOS.

**Comment by cvoges12** [comment]
I found that manual installation worked over IMAP and POP3, but automated install (so far tested with gmail) makes the application crash.

**Comment by cketti** [comment]
The new account setup currently available in K-9 Mail 6.711 doesn't have this problem anymore.
