### ISSUE TITLE
Systematic crash on composing on teclast T10

### ISSUE THREAD

**Issue by EricV** [thunderbird/thunderbird-android#3230]
I've been a happy user of K9mail for years, and installed it on all my android devices, and even family devices. Unfortunately K9mail on my brand new teclast T10 tablet crash systematically and immediately without reporting any error when trying to hit compose or  reply button (https://forum.xda-developers.com/general/general/teclast-master-t10-thread-t3722138 for hardware description).

I can read mail from imap account without problem and configured K9MAIL using the save/restore configuration feature from another working tablet (and even manually when I discovered it failed to be sure it was not a config import problem).

What can I do to help diagnose the problem? I've been forced to switch to bluemail for sending email in the meantime...

I enabled the debug and trace, but I can see anything printed. I can hook an usb cable and know how to use adb if needed.

### Environment
K-9 Mail version: 5.403, even tried the new 5.501 beta yesterday.

Android version: 7.0

Account type : IMAP

**Comment by philipwhiuk** [comment]
An adb debug log of the crash would be useful yes.

**Comment by EricV2** [comment]
adb logcat -d --pid=10606 > k9-log.txt
more k9-log.txt 
--------- beginning of main
03-11 18:08:07.347 10606 10606 I StorageEditor: Committing preference changes
03-11 18:08:07.386 10606 10606 I StorageEditor: Preferences commit took 39 ms
03-11 18:08:08.607 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=13780 ref=0
03-11 18:08:08.608 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=13779 ref=0
03-11 18:08:08.608 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=13778 ref=0
03-11 18:08:13.278 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75f9fe60 ID=14123 fd=62 ref=1
03-11 18:08:14.466 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75f9faa0 ID=14124 fd=69 ref=1
03-11 18:08:14.483 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa0540 ID=14125 fd=73 ref=1
03-11 18:08:15.073 10606 10606 I StorageEditor: Committing preference changes
03-11 18:08:15.079 10606 10606 I StorageEditor: Preferences commit took 5 ms
03-11 18:08:15.091 10606 10624 I MessagingController: Running command 'getFolderUnread:eric.valette@free.fr:INBOX', seq = 3 (foreground priority)
03-11 18:08:15.097 10606 10624 I MessagingController:  Command 'getFolderUnread:eric.valette@free.fr:INBOX' completed
03-11 18:08:15.172 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75f9fdc0 ID=14130 fd=75 ref=1
03-11 18:08:15.181 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa0cc0 ID=14141 fd=77 ref=1
03-11 18:08:15.195 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14125 ref=0
03-11 18:08:15.195 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14124 ref=0
03-11 18:08:15.195 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14123 ref=0
03-11 18:08:16.380 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75f9fe60 ID=14142 fd=62 ref=1
03-11 18:08:16.837 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14142 ref=0
03-11 18:08:16.838 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14141 ref=0
03-11 18:08:16.838 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14130 ref=0
03-11 18:08:19.785 10606 10624 I MessagingController: Running command 'getFolderUnread:eric.valette@free.fr:INBOX', seq = 4 (foreground priority)
03-11 18:08:19.796 10606 10624 I MessagingController:  Command 'getFolderUnread:eric.valette@free.fr:INBOX' completed
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{4f90021 V.E...... ......ID 0,0-2560,19
6} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{a69fccc V.E...... ......ID 0,197-2560,
391} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{53c8b93 V.E...... ......ID 0,392-2560,
586} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{5f065a6 V.E...... ......ID 0,587-2560,
781} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{7fba7f5 V.E...... ......ID 0,782-2560,
976} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{7dc0e30 V.E...... ......ID 0,977-2560,
1173} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{c5989c7 V.E...... ......ID 0,1174-2560
,1370} during layout: running second layout pass
03-11 18:08:19.927 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa0d60 ID=14180 fd=63 ref=1
03-11 18:08:19.971 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa05e0 ID=14187 fd=66 ref=1
03-11 18:08:19.983 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{4c9e6d2 V.ED..... ........ 2,0-2412,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.983 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{6b773a3 V.ED..... ........ 2412,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.983 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{8513391 V.ED..... ........ 2,0-2412,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{b6f52f6 V.ED..... ........ 2412,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{ccc30fc V.ED..... ........ 2,0-2412,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{8c5d385 V.ED..... ........ 2412,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{3ef7f83 V.ED..... ........ 2,0-2412,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{8256500 V.ED..... ........ 2412,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{3f38456 V.ED..... ........ 2,0-2388,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{185bcd7 V.ED..... ........ 2388,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{d477865 V.ED..... ........ 2,0-2388,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{13b393a V.ED..... ........ 2388,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{e76360 V.ED..... ........ 2,0-2388,56 #7f0
d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{f0cc019 V.ED..... ........ 2388,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:20.004 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa0e00 ID=14188 fd=70 ref=1
03-11 18:08:21.914 10606 10606 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-11 18:08:21.923 10606 10606 E AndroidRuntime: FATAL EXCEPTION: main
03-11 18:08:21.923 10606 10606 E AndroidRuntime: Process: com.fsck.k9, PID: 10606
03-11 18:08:21.923 10606 10606 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.fsck.k9/co
m.fsck.k9.activity.MessageCompose}; have you declared this activity in your AndroidManifest.xml?
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4224)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4183)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4507)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4475)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.fsck.k9.activity.compose.MessageActions.actionCompose(MessageActions.java:25)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onCompose(MessageList.java:1284)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onCompose(MessageListFragment.java:775)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.java:805)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.onMenuItemSelected(Activity.java:3204)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1217)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:76
1)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:152)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.view.View.performClick(View.java:5609)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:22262)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6077)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by EricV2** [comment]
`more k9-log.txt 
--------- beginning of main
03-11 18:08:07.347 10606 10606 I StorageEditor: Committing preference changes
03-11 18:08:07.386 10606 10606 I StorageEditor: Preferences commit took 39 ms
03-11 18:08:08.607 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=13780 ref=0
03-11 18:08:08.608 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=13779 ref=0
03-11 18:08:08.608 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=13778 ref=0
03-11 18:08:13.278 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75f9fe60 ID=14123 fd=62 ref=1
03-11 18:08:14.466 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75f9faa0 ID=14124 fd=69 ref=1
03-11 18:08:14.483 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa0540 ID=14125 fd=73 ref=1
03-11 18:08:15.073 10606 10606 I StorageEditor: Committing preference changes
03-11 18:08:15.079 10606 10606 I StorageEditor: Preferences commit took 5 ms
03-11 18:08:15.091 10606 10624 I MessagingController: Running command 'getFolderUnread:eric.valette@free.fr:INBOX', seq = 3 (foreground priority)
03-11 18:08:15.097 10606 10624 I MessagingController:  Command 'getFolderUnread:eric.valette@free.fr:INBOX' completed
03-11 18:08:15.172 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75f9fdc0 ID=14130 fd=75 ref=1
03-11 18:08:15.181 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa0cc0 ID=14141 fd=77 ref=1
03-11 18:08:15.195 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14125 ref=0
03-11 18:08:15.195 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14124 ref=0
03-11 18:08:15.195 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14123 ref=0
03-11 18:08:16.380 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75f9fe60 ID=14142 fd=62 ref=1
03-11 18:08:16.837 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14142 ref=0
03-11 18:08:16.838 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14141 ref=0
03-11 18:08:16.838 10606 10627 D IMGSRV  : gralloc_unregister_buffer:1708: ID=14130 ref=0
03-11 18:08:19.785 10606 10624 I MessagingController: Running command 'getFolderUnread:eric.valette@free.fr:INBOX', seq = 4 (foreground priority)
03-11 18:08:19.796 10606 10624 I MessagingController:  Command 'getFolderUnread:eric.valette@free.fr:INBOX' completed
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{4f90021 V.E...... ......ID 0,0-2560,19
6} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{a69fccc V.E...... ......ID 0,197-2560,
391} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{53c8b93 V.E...... ......ID 0,392-2560,
586} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{5f065a6 V.E...... ......ID 0,587-2560,
781} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{7fba7f5 V.E...... ......ID 0,782-2560,
976} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{7dc0e30 V.E...... ......ID 0,977-2560,
1173} during layout: running second layout pass
03-11 18:08:19.904 10606 10606 W View    : requestLayout() improperly called by android.widget.LinearLayout{c5989c7 V.E...... ......ID 0,1174-2560
,1370} during layout: running second layout pass
03-11 18:08:19.927 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa0d60 ID=14180 fd=63 ref=1
03-11 18:08:19.971 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa05e0 ID=14187 fd=66 ref=1
03-11 18:08:19.983 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{4c9e6d2 V.ED..... ........ 2,0-2412,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.983 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{6b773a3 V.ED..... ........ 2412,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.983 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{8513391 V.ED..... ........ 2,0-2412,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{b6f52f6 V.ED..... ........ 2412,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{ccc30fc V.ED..... ........ 2,0-2412,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{8c5d385 V.ED..... ........ 2412,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{3ef7f83 V.ED..... ........ 2,0-2412,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{8256500 V.ED..... ........ 2412,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{3f38456 V.ED..... ........ 2,0-2388,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{185bcd7 V.ED..... ........ 2388,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{d477865 V.ED..... ........ 2,0-2388,56 #7f
0d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{13b393a V.ED..... ........ 2388,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{e76360 V.ED..... ........ 2,0-2388,56 #7f0
d0087 app:id/subject} during second layout pass: posting in next frame
03-11 18:08:19.984 10606 10606 W View    : requestLayout() improperly called by android.widget.TextView{f0cc019 V.ED..... ........ 2388,10-2536,66
 #7f0d00c9 app:id/date} during second layout pass: posting in next frame
03-11 18:08:20.004 10606 10627 D IMGSRV  : gralloc_register_buffer:1583: hnd=0x7e75fa0e00 ID=14188 fd=70 ref=1
03-11 18:08:21.914 10606 10606 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-11 18:08:21.923 10606 10606 E AndroidRuntime: FATAL EXCEPTION: main
03-11 18:08:21.923 10606 10606 E AndroidRuntime: Process: com.fsck.k9, PID: 10606
03-11 18:08:21.923 10606 10606 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.fsck.k9/co
m.fsck.k9.activity.MessageCompose}; have you declared this activity in your AndroidManifest.xml?
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4224)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4183)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4507)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4475)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.fsck.k9.activity.compose.MessageActions.actionCompose(MessageActions.java:25)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onCompose(MessageList.java:1284)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onCompose(MessageListFragment.java:775)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.java:805)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.Activity.onMenuItemSelected(Activity.java:3204)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1217)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:76
1)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:152)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.view.View.performClick(View.java:5609)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:22262)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6077)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
03-11 18:08:21.923 10606 10606 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by cketti** [comment]
The `MessageCompose` activity and a couple of other components are disabled by default, so K-9 Mail doesn't show up e.g. as a share target when no account has been set up. As soon as an account has been set up the components are enabled. This is checked on every app start. But it looks like that check doesn't work properly on your device and the component remains disabled.
I'm not sure what to do about that. This is probably a bug in your Android version.

**Comment by EricV** [comment]
On the other hand, blue mail for example does something to explcitely register account, like Gmail, Skype,WebEx,.  I can select those application when creating  a new account. I do not see k9mail there.

**Comment by EricV** [comment]
And effectively k9mail does not appear when I want to share something whereas multiple other apps do including blue mail

**Comment by EricV** [comment]
Please note that the trace applies to 5.501 beta version and not 5.403. I had no reason to retest old version as it also crashed (maybe the crash root cause is different but).

**Comment by ildar** [comment]
I this too on LineAgeOS 7.1:
> 12-20 08:36:30.590 31692 31692 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.fsck.k9/com.fsck.k9.activity.MessageCompose}; have you declared this activity in your AndroidManifest.xml?

Is this the LOS bug?

**Comment by EricV2** [comment]
I have no clue. This tablet is indeed runing Android 7.1 but it is a chinese home-brewed version but it could be based on LineageOS code...

**Comment by ildar** [comment]
I doubt that OS code is defective. Is there a possibility that K-9 doesn't
enable some components under certain circumstances?

**Comment by EricV2** [comment]
Well, on the same tablet bluemail works perfectly so indeed K9mail code could be modified/enhanced to cope with this.

**Comment by cketti** [comment]
Please open a new issue if this is still a problem with K-9 Mail 5.7xx.

**Comment by EricV** [comment]
Just tested 5.721 same problem
