### ISSUE TITLE
Rejected message not stored by or in k9mail

### ISSUE THREAD

**Issue by jult** [thunderbird/thunderbird-android#3239]
### Expected behavior
The message I was trying to send was rejected by the server (554 5.1.1) and should therefore be stored in the Outbox.

### Actual behavior
Said message entirely disappeared! Can't find it anywhere. Not in drafts, not in Outbox. No idea where k9 stored it, but after the rejected notification (554 5.1.1, the To: address was not in virtusertable) it just got thrown out. Pretty bad, if I say so myself. First in my 30 year email sending career!

### Steps to reproduce
1. Just compose and send an email like normal
2. use a nonexistentalias@somedomainonserver.nl to send it to 
3. See the Rejected notification, and lose the composed message!

### Environment
K-9 Mail version: latest from playstore

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (secure)

If there's a folder somewhere I don't know about, where k9 stores rejected sent messages, I can't find it in the UI or within the Account it was sent by.

**Comment by cketti** [comment]
Messages that fail to send are moved to the Drafts folder. However, they are not uploaded to the server and it's possible that message was removed when synchronizing the Drafts folder.

We already changed the code that handles send failures in `master`. The next stable version will include this fix.
