### ISSUE TITLE
Missing emails inside folder

### ISSUE THREAD

**Issue by tezeb** [thunderbird/thunderbird-android#3262]
### Expected behavior
All emails inside a folder shall be visible inside the same folder in K9.

### Actual behavior
Updating folder does not download all (new) emails. It silently skipped two emails, but later emails from the same thread were included. When checking the same account on PC, emails are visible.

The behaviour is permanent(ie. "hidden" emails don't appear even when polled again and again). I have not tried resetting folder cache yet. Please let me know if I can provide any more info.

### Steps to reproduce
1. Pull down inside a folder to poll server
2. New emails arrive
3. Verify emails list with emails on another device

### Environment
K-9 Mail version: 5.208

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please use the latest (stable) version of K-9 Mail and provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
