### ISSUE TITLE
`dir` attribute not respected?

### ISSUE THREAD

**Issue by arist0tl3** [thunderbird/thunderbird-android#3265]
This is reported from someone testing our emails, so I apologize for the screenshots. 

### Expected behavior
Render order changes based on the `dir` attribute of the parent element.

### Actual behavior
Render order doesn't change.

### Steps to reproduce
1. Wrap nested content with different `dir` values:

```
<table>
  <tbody>
    <tr>
      <td dir="ltr">
        <div class="column">
          <!-- nested table -->
        </div>
        <div class="column">
          <!-- nested table -->
        </div>
     </td>
    </tr>
  </tbody>
</table>
```
should appear reversed:
```
<table>
  <tbody>
    <tr>
      <td dir="rtl">
        <div class="column">
          <!-- nested table -->
        </div>
        <div class="column">
          <!-- nested table -->
        </div>
     </td>
    </tr>
  </tbody>
</table>
```

Rendered correctly in most* clients:
![image](https://user-images.githubusercontent.com/9328541/37492222-d1bceaf8-285d-11e8-88d9-5951ccaa60ea.png)

Rendered in k9:
![image](https://user-images.githubusercontent.com/9328541/37492234-da98485c-285d-11e8-9b9c-c1dcdbd269f7.png)

After seeing #2506 I assume this is based on an automatic interpretation of the `dir` attribute?

*Most clients = ~80 combinations on EmailOnAcid

I honestly don't know enough about this project to know whether this is inside/outside of the scope of your goals.

**Comment by philipwhiuk** [comment]
I think it's more likely it's being stripped but I'll investigate.

**Comment by arist0tl3** [comment]
Great, thanks for the quick response!
