### ISSUE TITLE
crash: reply to encrypted mail

### ISSUE THREAD

**Issue by voxspox** [thunderbird/thunderbird-android#3266]
### Expected behavior
open new mail screen.

### Actual behavior
K9 displays new mail screen and crashes.

03-16 12:15:32.187 E/AndroidRuntime(31412): java.lang.NullPointerException: Attempt to invoke interface method 'com.fsck.k9.mail.Body com.fsck.k9.mail.Part.getBody()' on a null object reference

This seems related to I have no encryption add-on installed.

### Steps to reproduce
1. open encrypted mail (info: install add-on to view decrypted content)
2. press reply button
3. crash

### Environment
K-9 Mail version: 5.403

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Is this still an issue with the latest K-9 Mail version?

**Comment by voxspox** [comment]
yes, still in 5.600
