### ISSUE TITLE
Deleted Mail gets lost on its Way into the Trash Folder

### ISSUE THREAD

**Issue by d-t-o** [thunderbird/thunderbird-android#3281]
### Expected behavior
A deleted mail should disappear from the inbox and appear in the trash folder.

### Actual behavior
In step 5. below, the deleted mail disappears from the trash folder listing again. it is now neither visible in the inbox nor in the trash.

checking with a separate mail client reveals that the mail actually is not in the trash folder but still in the inbox (and can still be opened from there). K9 does not show the mail in the inbox either, even upon resynch.

### Steps to reproduce
1. mark a mail in my inbox
2. select the trash icon
3. the mail disappears from inbox
4. go to the trash folder and see the mail there
5. select synch for the trash folder

### Environment
K-9 Mail version: 5.403
Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (gmx.com)

**Comment by philipwhiuk** [comment]
Odd.

1. Is this reproducible reliably for you?
2. Any chance of debug logs?

**Comment by d-t-o** [comment]
1. Yes
2. Sure. Can I put/send the log file somewhere specific so my account details are not visible to the whole internet? :)

**Comment by d-t-o** [comment]
Here's a log of the above situation. I just cleaned out mail addresses and mail subjects, the rest is the original logcat output.
[k9.log](https://github.com/k9mail/k-9/files/1863518/k9.log)

**Comment by bluepineapplegroup** [comment]
I opened issue 3370 and am curious if perhaps my lost emails may also still be there but not visible. How did you locate the invisible emails?

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
