### ISSUE TITLE
selecting key from openkeychain fails

### ISSUE THREAD

**Issue by m1027** [thunderbird/thunderbird-android#3289]
k-9 does not accept the cryptographic key from openkeychain.

The key has been created newly by openkeychain using plain defaults from the
wizzard, except for uploading to the internet being off (as these are tests
yet only).

Steps in detail:

In k-9, after selecting the key from the list, the app takes a short breath
for about 1 sec. and then simply behaves as if it was newly started. Looks
like a quick app restart after a crash or so (but there is no crash message).
When entering the menu Cryptography / My key, there is still "no key
selected".

Tried with K-9/OpenKeyChain 5.502/4.9.2 as well as 5.403/4.9.

Android version: 7.1.2 / LineageOS. Security options were off for both
for both apps.

**Comment by cketti** [comment]
Sounds like the app's process is killed. Please record a debug log without filtering for the PID. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by m1027** [comment]
Thanks, here the log.

FYI: Upon reproducing this error I received a crash dialog this time, no silent
restart.

[k9-log.txt](https://github.com/k9mail/k-9/files/1857537/k9-log.txt)

**Comment by m1027** [comment]
Sorry, you wanted without pid filter. Here another log file.

[k9-log-no-pid-filter.txt](https://github.com/k9mail/k-9/files/1857612/k9-log-no-pid-filter.txt)

**Comment by cketti** [comment]
Odd. Looks a bit like K-9 Mail's process was killed while in the background and it can't be restored from the saved state.

**Comment by cketti** [comment]
I was able to reproduce the issue. 

To work around the bug make sure "Don't keep activities" in Android's "Developer options" is not checked. Also "Background process limit" should be set to "Standard limit". You basically need to avoid the K-9 Mail process getting killed in the background.

**Comment by m1027** [comment]
> To work around the bug make sure "Don't keep activities" in Android's "Developer options" is not checked. 

Great, disabling that option fixed the issue! Thank you so much

**Comment by steko** [comment]
I'm sorry to report that I found this issue with K-9Mail 5.700 on Android 8 (EMUI). The proposed workaround doesn't fix the problem.
