### ISSUE TITLE
Error message shows password (plain text, readable)

### ISSUE THREAD

**Issue by pixelverbieger** [thunderbird/thunderbird-android#3293]
I tried to connect to an existing mailbox with wrong credentials (old password) stored in K-9.
As a result, K-9 says "Username or Password wrong. (Command: LOGIN "user.name@mailbox.tld" "password-in-plain-text"; response: #2# [NO, [AUTHENTICATIONFAILED], Authentication failed.])"

### Expected behavior
Error message should not show the (readable) plain text password.

### Actual behavior
Error message does show the (readable) plain text password.

### Steps to reproduce
1. In K-9, set up an account using correct credentials
2. Change the password for the mailbox.
3. In K-9, try to connect to the mailbox again.

### Environment
K-9 Mail version:
5.403

Android version:
5.0.2
Kernel 3.4.0+

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
This should only happen if 'Global Settings > Debugging > Log sensitive information' is checked (it's disabled by default).

**Comment by pixelverbieger** [comment]
I can confirm this option is/was enabled. (Default or not? Can't tell …)

When disabling it, the error message says:
_… Command: \*sensitive\*; response …_

**Comment by pixelverbieger** [comment]
much better :)

thanks for your info!
