### ISSUE TITLE
"Disable notifications" during Quiet Time isn't working

### ISSUE THREAD

**Issue by festolz** [thunderbird/thunderbird-android#3303]
### Expected behavior
if a quiet time is set and it is also checked that notifications during quiet times are to be completely disabled, no notifications should show up when new mails arrive

### Actual behavior
with described setting: when new mails arrive no sound is played (as should be), but the notification is still shown

### Steps to reproduce
1. send mail
2. see notification

### Environment
K-9 Mail version: 5.403

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Quiet time doesn't disable notifications. It only skips configuring sound, vibration and notification light. There is no setting to not create notifications during quiet time.

**Comment by festolz** [comment]
The checkmark "Quiet Time" has the description "disable ringing, buzzing and flashing at night". Okay. 

But directly underneath is the checkmark  "disable notifications" with the description "completely disable notifications during quiet time". 

If this does not disable notifications, it should be rephrased.

**Comment by cketti** [comment]
I was wrong. We do have that setting. And like described in the original report it's currently not working.

**Comment by marktiptop** [comment]
When will this be fixed?

**Comment by Tobias-Fischer** [comment]
@cketti unfortunately I still receive notifications during quiet time. Is there another bug somewhere?

**Comment by cketti** [comment]
@Tobias-Fischer: This fix is only available in 5.7xx beta versions. See https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68

If you are using such a version and it still doesn't work, please create a new issue and provide all the information asked for in the issue template.

**Comment by Tobias-Fischer** [comment]
Thank you, that's good to know!
