### ISSUE TITLE
Crash when saving "noname" file from email

### ISSUE THREAD

**Issue by jscott0** [thunderbird/thunderbird-android#3308]
I subscribe to a lot of mailing lists, and K-9 doesn't seem to like them.

I've been able to reproduce a crash by opening what should be an ordinary email, and instead of seeing the text, there is a "noname" attachment. Trying to open it with an application, as far as I can tell, sends no data to the application in question. Attempting to save the file causes K-9 to crash. I've included a GIF to show this (the email I'm opening is [here](https://lists.debian.org/debian-mate/2018/04/msg00018.html)), and I've also included some output I got from my first time using `adb`.

![crash](https://user-images.githubusercontent.com/8465972/38395758-8b857d7e-3902-11e8-8809-8ba0ce61f1e3.gif)

```
04-05 18:27:54.853 16062 17459 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
04-05 18:27:54.853 16062 17459 E AndroidRuntime: Process: com.fsck.k9, PID: 16062
04-05 18:27:54.853 16062 17459 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:318)
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:3$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecut$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecu$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
04-05 18:27:54.853 16062 17459 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: mimeType can't be null
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at android.app.DownloadManager.validateArgumentIsNonEmpty(DownloadMan$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at android.app.DownloadManager.addCompletedDownload(DownloadManager.j$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at android.app.DownloadManager.addCompletedDownload(DownloadManager.j$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at com.fsck.k9.ui.messageview.AttachmentController.addSavedAttachment$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at com.fsck.k9.ui.messageview.AttachmentController.saveAttachmentWith$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at com.fsck.k9.ui.messageview.AttachmentController.access$900(Attachm$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at com.fsck.k9.ui.messageview.AttachmentController$SaveAttachmentAsyn$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at com.fsck.k9.ui.messageview.AttachmentController$SaveAttachmentAsyn$
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:304)
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-05 18:27:54.853 16062 17459 E AndroidRuntime:        ... 3 more

```

I've been having this issue for a while now, probably with several different versions, but right now, I'm on K-9 Mail 5.503 and Android 7.0.

And by the way, even though this is on a mailing list, I have OpenPGP encryption enabled with my email provider (they'll use my public key to encrypt emails that aren't encrypted already), so it is encrypted with PGP/MIME. I don't think that has anything to do with it, but that's just a disclaimer. The email decrypts and displays fine in Thunderbird + Enigmail.

**Comment by Valodim** [comment]
Looks like a simple bug, we should default to a mime type of `application/octet-stream` if we don't know what it actually is. We *could* try to be smarter about it, e.g. make it `text/plain` if it's small and contains only printable characters. Do you know what the content of this attachment is?

**Comment by Valodim** [comment]
@JohnScott623 could you forward such a message to me as attachment? -> look@my.amazin.horse

**Comment by JohnScott623** [comment]
@Valodim Sorry I haven't been keeping up; I haven't been getting GitHub's emails for some reason (I'll investigate that). I've forwarded it now, and thank you.

**Comment by JohnScott623** [comment]
@Valodim Did you get the email?

**Comment by JohnScott623** [comment]
@Valodim Is there anything I can help with? This issue breaks using K-9 for most of my day-to-day work, and I'm concerned that progress on this issue has stalled.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
