### ISSUE TITLE
No notification in secondary account

### ISSUE THREAD

**Issue by sketet** [thunderbird/thunderbird-android#3338]
### Intro
Hello, I use an email account with alias addresses and filters that move the messages in several folders. For this I've created 2 accounts in K-9 for 2 alias, one for the main and its related folder (INBOX) and the secondary for alias and its related folder (alias folder).
(I made this because I want the sent messages in the same folder I receive messages, since K-9 don't permit to choose the sent folder for every alias, I had to create a secondary account to have a different sent folder from the main one).

### Expected behavior
I want notifications for new messagese from the alias folder in the secondary account.

### Actual behavior
In the secondary account (account for alias address) I have not notifications, I set the folder as first class (all options) and notifications from first class folder... but nothing.

I set so:
- Main account: Notification from first class folder
INBOX (first class all options) -> notifications works
Alias Folder (second class all option) - no notifications

- Secondary account:  Notification from first class folder
INBOX (second class all options) -> no notifications
Alias Folder (first class all options) -> no notifications

I hope I explained, I don't understand why I have not notifications in the secondary account.

### Environment
K-9 Mail version: 5.403

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (mail.com)

**Comment by calvin-hc** [comment]
I have the same issue, where email received only on the secondary account does not generate notifications.

Also, messages received on the secondary account DO NOT get grouped together by conversation (threaded view) - this is turned on AND messages received by the primary account are getting grouped.

**Comment by cketti** [comment]
I was not able to reproduce this issue with K-9 Mail 5.803.
