### ISSUE TITLE
Non-RFC-822 email format causes crash rendering email

### ISSUE THREAD

**Issue by sporkwitch** [thunderbird/thunderbird-android#3351]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Email should download and open body

### Actual behavior
Application CTD

### Steps to reproduce
1. Tap to open suspect email

### Environment
K-9 Mail version: 5.503

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Specifically, this is an obvious phishing email in my gmail spam folder, accessed via imap.  Email that triggers the issue is attached.  Other emails in spam folder open fine.  Interestingly, there doesn't seem to be anything actively broken or malicious that I can see, though it's obvious phishing and none of the security (e.g. SPF) checks out.

[phishing.txt](https://github.com/k9mail/k-9/files/1933168/phishing.txt)

**Comment by philipwhiuk** [comment]
Thanks for the example email and info!

Managed to combine the email with crash reports for Android 8.1.0 

We don't like this:

`Sender: The Google Accounts <contact@virginpulse.com>@stlig.vivastreet.org.uk`

It's not valid to have `<` or `>` in an email unless it's quoted (and even then it's really rare).

We expect something like one of the following:

```
Sender: "The Google Accounts" <contact@virginpulse.com>
Sender: The Google Accounts <contact@virginpulse.com>
Sender: contact@virginpulse.com
Sender: contact@virginpulse.com
```


As a result we generate an `Address` object with a null email. We then try and show that email address when we render it and as a result we throw an NPE.

```
java.lang.NullPointerException: 
  at android.text.SpannableStringBuilder.append (SpannableStringBuilder.java:269)
  at com.fsck.k9.helper.MessageHelper.toFriendly (MessageHelper.java:147)
  at com.fsck.k9.view.MessageHeader.populate (MessageHeader.java:314)
  at com.fsck.k9.ui.messageview.MessageTopView.setHeaders (MessageTopView.java:210)
```

This particular error is responsible for a bunch of crashes so it's great we now have an idea why.

We currently parse the address as entirely being the name with no email address. Then we throw an exception trying to render an Address without an email.

Not quite sure if we should handle Addresses without emails, skip over the address entirely or what.

**Comment by sporkwitch** [comment]
@philipwhiuk It almost seems like it's a result of the sloppiness of the phishing attempt; probably worth just handling it gracefully and reporting an error (and possibly a warning), rather than actually making it work and open it (since, presumably, a non-malicious email would be set up correctly; few legitimate emails come from mailservers that badly misconfigured).

**Comment by philipwhiuk** [comment]
Yeah, I'm not too concerned about trying to extract an email address you can reply to.

**Comment by trogau** [comment]
Apologies for bumping this old issue but I had my first ever crash in K-9 (after several years of faithful service!) today and I think it's a similar issue to this, so thought I'd just add the (spam) email I received. 

Looks like the same problem with a malformed Sender, although I thought it could also be the encoded blob (I had a quick look at it and it looks like just the usual HTML spam gibberish).  Raw email text attached. 

[crash.txt](https://github.com/k9mail/k-9/files/3681338/crash.txt)

**Comment by stephenostermiller** [comment]
The following email crashes the k-9 client:

```
Date: 18 Nov 2019 21:08:52 -0500
From: Tester <tester@example.com>
Sender: testing.example.com
Subject: Test crash 10
Content-Type: text/plain

Hello World
```

One of my financial institutions (Discover card, discover.com, discovercard.com) sends email with just a domain name in the `Sender` header and I can never their email on my phone because of the crash.

**Comment by cketti** [comment]
This should no longer be an issue in K-9 Mail 5.7xx.
