### ISSUE TITLE
Duplicate recipient issue

### ISSUE THREAD

**Issue by RonCohen1** [thunderbird/thunderbird-android#3356]
If I attempt to send an email with duplicated recipients (as often happens when "replying all" to an email from someone who cc'ed him/herself), the email gets sent with no subject and no body, and is accompanied by an error message "Failed to send some messages, Recipient already specified".  Also, the email shows up in neither Sent Messages or Drafts -- so no way to recover and try again.   

Expected (desired) behavior:  the duplicate addressee is filtered out and then message sent as normal.

Acceptable (but much less desirable) behavior: the error message appears, the message is not sent, but remains in drafts.

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This should be fixed in K-9 Mail 5.7xx.
