### ISSUE TITLE
Encrypted drafts created by Thunderbird are annihilated

### ISSUE THREAD

**Issue by nuntius35** [thunderbird/thunderbird-android#3393]
### Expected behavior
You should be able to open, edit and send an encrypted draft message created with Thunderbird. If opening the draft is not possible, the draft should be left untouched. Under no circumstances should the draft be lost.

### Actual behavior
You can easily loose a long draft that took half an hour of careful composing. 

### Steps to reproduce
1. Create a draft in Thunderbird with Enigmail installed. The draft is encrypted and uploaded to the drafts folder. If you reopen the draft in Thunderbird, you are asked for the passphrase of your private key. Then you can continue to edit the draft.
2. Instead, try to open the draft in K-9. Then, the OpenKeychain dialog pops up and asks you about your passphrase. There is no error message but the text of the draft is now empty (and the subject line is: "Encrypted message")!
3. At this point, I found no way to recover: If I press the back button, I have the options to either reject or save the draft. In both cases the original text is lost. 😡

### Environment
K-9 Mail version: 5.403

Android version: 6.0.1

Account type: IMAP

**Comment by JohnScott623** [comment]
> (and the subject line is: "Encrypted message")!

The subject lines are never encrypted though, so failing to encrypt/decrypt a message should have no effect on it. @nuntius35 Could you have been using TorBirdy with Thunderbird, which replaces subject lines with "Encrypted message" by default? It's probably an Enigmail option, but TorBirdy hardens the former and turns that setting on.

**Comment by nuntius35** [comment]
@JohnScott623 No, I'm not using TorBirdy, I'm using just Enigmail 2.07. Since Eingimail 2.0 there is an advanced setting if you want to hide the subject line. But this option does not affect my problem. Even if the subject line is not replaced, the body of the message is gone.
My initial bug report was not totally accurate, though, you can recover the message from the trash folder if you hit the reject option on the first time. But if you let K-9 save the draft, the original text is lost.

**Comment by doak** [comment]
Duplicate of #2860?
Anyway, is this solved by new version *v5.7xx* which use encrypted drafts by itself (if enabled)?

**Comment by nuntius35** [comment]
Issue is fixed for me in 5.701. (I didn't test 5.700)
