### ISSUE TITLE
Cannot search Japanese words in mail body

### ISSUE THREAD

**Issue by onuralparslan** [thunderbird/thunderbird-android#3404]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
Search function should find and list the emails

### Actual behavior
Tell us what happens instead
When I search a Japanese keyword (kanji or kana)  to find emails in an account, K9 lists only the mails that have the keyword in the email title. If the keyword is only in the email body, K9 does not list those mails in the results. K9 used to find also those emails in the previous versions.

### Steps to reproduce
1. Search a japanese word
2.
3.

### Environment
K-9 Mail version:
5.403
Android version:
8.03
Account type (IMAP, POP3, WebDAV/Exchange):
Pop3

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
