### ISSUE TITLE
Wrong email opens

### ISSUE THREAD

**Issue by ssdv80** [thunderbird/thunderbird-android#3408]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
I touch the (first) email in the sent folder and this email will be opened, and I can see this emails content.

### Actual behavior
I touch the fist email in the sent folder and a totally different email dispays.

I mean that I have observed this in other folders before, but I could only reproduce it in the sent folder.

### Steps to reproduce
1. open sent folder
2. touch first email in the folder
3.

### Environment
K-9 Mail version: 5.403 from F-droid

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by HoWilgh** [comment]
Can confirm this on one of two android phones. 
I see the same problem on a fresh installation on android 8.0.
On the second phone with an older but updated installation of k-9 on android 6.0.1 everything works fine. 
Different accounts (and therefore a different number of mails) are used on both phones. 
BR

**Comment by wasmith108** [comment]
Just started not more than 2 weeks ago.  Samsung S7 Android 7.0. Stripped all apps out, still happens.  Attempt to select new mail to open or to delete, results I  emails other than the one selected opens. No recognizable pattern on the one that actually opens.

**Comment by cketti** [comment]
I'm not able to reproduce this. I don't see us being able to track this down without having an affected device. But I'm leaving this issue open so other people who are affected by this can find it and share their observations.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
