### ISSUE TITLE
throw AuthenticationFailedException but password is right

### ISSUE THREAD

**Issue by pinehallnick** [thunderbird/thunderbird-android#3411]
Added two mailboxes to switch mailboxes back and forth through the sidebar. An exception will be reported after a while. when debug and found method saslAuthPlain throws AuthenticationFailedException.
Actually, I want to remember a status every time when the password is error. I judged it by an AuthenticationFailedException exception message( message is "response: #2# [NO, AUTHENTICATE failed.]) As long as I reported this abnormality, I would think that it was a wrong password. However, when I switch accounts, the password of the account is right, the result throws this AuthenticationFailedException, and then I also think that the password is wrong.So this situation is wrong.
Could you please answer it, thank you very much.

My question is :
1.How to accurately determine the password is wrong, rather than judged by abnormal information?
2.Why the normal switching account will report AuthenticationFailedException?

### Expected behavior
Can switch normally

### Actual behavior
 throws AuthenticationFailedException

### Steps to reproduce
1.Added two Accounts
2.Switch back and forth between these two accounts

### Environment
K-9 Mail version: K-9 Mail v5.501 （The latest version also has this problem）

Android version:Android 7.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment]
> How to accurately determine the password is wrong, rather than judged by abnormal information?

We can’t - if we get a failure from an AUTH action the best we can do is present the message to the user.

**Comment by lich1011** [comment]
I had a similar problem. When i first time entered wrong password, i get alert. Than i went back to change password. However, it still show wrong password alert. I traced the code, found that, the ImapStore was still the old one. The password hasn't been chaneged
