### ISSUE TITLE
[Oreo] K-9-mail-app crashes when pressing  button "New E-mail"

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#3427]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
A new empty e-mail form should be displayed.

### Actual behavior
The app shuts down with error

### Steps to reproduce
1. Open K-9-Mail
2. press on button "new email"
3. App is closed. Android-system message " re-open App? / Give feedback"

### Environment
K-9 Mail version: 5.403

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP and POP3
![screenshot_20180604-202921](https://user-images.githubusercontent.com/39924082/40935681-230ced66-6839-11e8-89c9-17899b830670.png)

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
