### ISSUE TITLE
Crash on attempt to display a message

### ISSUE THREAD

**Issue by gshollingsworth** [thunderbird/thunderbird-android#3431]
### Expected behavior
Message should display without crashing.

### Actual behavior
App crashes without displaying message.

### Steps to reproduce
1.  Select message from list.
2.  Crash, "K-9 Mail has stopped."
3. feedback sent

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

[original_msg.txt](https://github.com/k9mail/k-9/files/2078299/original_msg.txt)

**Comment by gshollingsworth** [comment]
I have performed some further analysis. The problem messages have a multipart boundary string beginning with an equal sign.

**Comment by cketti** [comment]
The issue was probably the value of the `Sender` header. This bug is already fixed in the `master` branch. The provided message displays fine with my development version.
