### ISSUE TITLE
max-height of img tag not used 

### ISSUE THREAD

**Issue by edwh** [thunderbird/thunderbird-android#3434]
Love K-9, used it for years.

Before pictures are loaded, I have mails which have an img with a with a height attribute on an img tag.  

`<img width="600" height="155" style="width:600px;height:155px" src="blah">`

These seem to render square, which I wouldn't expect.

**Comment by limeblack** [comment]
I see no `max-height` under style.  Should `height:155px` be `max-height:155px.`

**Comment by edwh** [comment]
Apologies, I meant just height, not max-height.  I've edited.

**Comment by limeblack** [comment]
@edwh  the title still says max-height also I would add a picture

**Comment by cketti** [comment]
Is this still an issue with K-9 Mail version 5.600?

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
