### ISSUE TITLE
Remove messages when deleted on server - does not seem to work

### ISSUE THREAD

**Issue by JesperKick** [thunderbird/thunderbird-android#3450]
### Expected behavior
Mails deleted on the server should automatically be deleted in the K9 mail client 
Due to check mark in  "Sync serve deletions:  Remove messages when deleted on server"

### Actual behavior
Mails are not deleted in K9, when deleted on server.
I have around 50 mails in my inbox on the mail server, but 1000 i my K9 Inbox.

### Steps to reproduce
1. Send mail to mail box.
2. See it in K9 Mail
3. Delete it with another client
4. Go back to K9 and check about also it is delted there

### Environment
K-9 Mail version: 5.403

Android version:
8.0.0 
One Plus 3 phone

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by dilyanpalauzov** [comment]
On the one side you have the `Expunge` operation on the mailbox/folder, and on the other the ability to synchronize events.

So if you delete a message, it is possibly marked as deleted on server, then it needs to be expunged by any client and then you need to resynchronize the currently selected mailbox/folder.

Do you tell k9 to syncrhonze with the server and are you sure the messages are expunged (not just marked as \\Deleted and therefore hidden in the other client)?

**Comment by JesperKick** [comment]
They mails are expunged on the server (checked with two different clients).
But if I manually use the function "Expunge" in K9 then the inbox show the correct mails.
Is there a way where I can set this Expunge to work automatically?

**Comment by dilyanpalauzov** [comment]
Under Settings > Account Settings > Fetching mails you see 'When I delete a message' and 'Erase deleted messages on server'.  Play with them.

**Comment by dilyanpalauzov** [comment]
I don't know, play with the settings.

**Comment by qtron** [comment]
Why cant K9 read .eml files?? Baffled!
Please fix. Also cant find the mystical sync setting to auto poll for new mail. Looked at every setting..

**Comment by cketti** [comment]
Please record a debug log while syncing the Inbox. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by qtron** [comment]
ok

**Comment by SpaceObserver** [comment]
I can also confirm the behaviour of myself, is there a solution in the meantime? 

**My Environment**

K-9 Mail version: 5.600

Android version:
9.0.0
One Plus A6003 phone

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by SpaceObserver** [comment]
I can also confirm the behaviour of myself, is there a solution in the meantime?

K-9 Mail version: 5.600
Android version: 9.0.0
One Plus A6003 phone
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx. Don't forget to include a debug log!
