### ISSUE TITLE
Wrong sent folder when switching accounts

### ISSUE THREAD

**Issue by WinAuthFan** [thunderbird/thunderbird-android#3496]
### Expected behavior
I have two accounts, `A` and `B`. Email arrives in account `A`. I reply to it. In the `From:` field, I change from `A` to `B`. I expect the email to be saved in the Sent folder of account `B`. Instead, it is saved in the sent folder of account `A`. 

### Actual behavior
The email is saved in the sent folder of account `A`. 

### Steps to reproduce
See above. 

### Environment
K-9 Mail version: 5.403

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by lucasreddinger** [comment]
i think i had something similar happen with a draft that i switched between identities (two different accounts). i'll try to post more details soon, like a proper pr.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
