### ISSUE TITLE
Incoming server settings can not change imap server

### ISSUE THREAD

**Issue by lich1011** [thunderbird/thunderbird-android#3515]
### Expected behavior
I change imap sever in the Incoming server settings Activity, the imap server should be change, if I enter an wrong imap server, it should not be able to connect.

### Actual behavior
Iamp sever didnt change, it still use old one to connect

### Steps to reproduce
![_20180720161001](https://user-images.githubusercontent.com/23086291/42991192-79551f82-8c37-11e8-98e2-ec1bdc1c428e.png)
![_20180720161023](https://user-images.githubusercontent.com/23086291/42991194-7b01e964-8c37-11e8-94b2-d6c38df58f03.png)
![_20180720161028](https://user-images.githubusercontent.com/23086291/42991198-7bfab97c-8c37-11e8-9f1c-b95168093f93.png)
![_20180720161031](https://user-images.githubusercontent.com/23086291/42991200-7d6512d0-8c37-11e8-8186-1e4fb79652f7.png)

### Environment
K-9 Mail version: github master branch

Android version: API level 27

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
The issue is that `BackendManager` never discards a `Backend` for an account once it has been created. We have to tie the cached instance to the account's server settings.
