### ISSUE TITLE
Special folder settings do not survive export/import cycle

### ISSUE THREAD

**Issue by madduck** [thunderbird/thunderbird-android#3517]
Due to performance issue, I deemed it a worthy try to backup my settings, delete the account, and import from the backup. This all worked very nicely, except the special folder settings (Sent, Drafts, Trash, Spam, Archive) had reverted to their defaults.

This is using K9 5.403 from F-Droid, running on Android 7.

**Comment by cketti** [comment]
This should no longer be an issue in K-9 Mail 5.7xx.
