### ISSUE TITLE
K-9 Crashes went starting a new email beginning with da, like dave.

### ISSUE THREAD

**Issue by gtalge** [thunderbird/thunderbird-android#3540]
Strange behavior: Using person's last name to call up email address works as expected.

Submitted report with logs to Google Play Store.

### Expected behavior
Bring up enail address from contact list.

### Actual behavior
K-9 crashes

### Steps to reproduce
1. Initiate email starting with da or Da.
2.
3.

### Environment
K-9 Mail version:5.403

Android version:5.1.1

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by gtalge** [comment]
Also crashes on send to: ad.
If you enter the person's last name, k-9 will load the correct email address and work ok.

Exampe: Send to: Dave Smith crashes after entering Da, but Don Smith works ok.

Also,  typing Smith, a label will come up with Dave Smith. Tap on Dave Smith and everything works fine.

**Comment by gtalge** [comment]
Update: Works ok if you type ave Smith for Dave Smith.

Same behavior on the cc: line.

**Comment by mhgithb** [comment]
I can confirm the general behaviour. However, the address book entries leading to a crash differ (no problems with the entry "Dave Test", for example). The problem seems to occur only when the 'problematic string' is at the beginning of an address book entry (i.e. 'ti...' crashes, but 'ina' will bring up 'tina...' and work). So far, the crash has always occurred with the second letter typed in.  
Thank you for your efforts, m

K9Mail 5.403, Android 6.01, FairphoneOpen

**Comment by gtalge** [comment]
If you go to contact phone list first to the name Dave, then tap email, up will come K-9 mail without a problem.

However, if you are already in K-9 mail and type "Da" for Dave, K-9 will crash on the "a", but if you type "ave", up will come "Dave" from the contact list and you can tap on it without a problem.

I haven't seen this in other letter combinations. I only noticed it because I added "Dave" to my contact list. Before there was no one on the list whose name started with "Da".


On August 18, 2018 7:50:24 AM PDT, mhgithb <notifications@github.com> wrote:
>I can confirm the general behaviour. However, the address book entries
>leading to a crash differ (no problems with the entry "Dave Test", for
>example). The problem seems to occur only when the 'problematic string'
>is at the beginning of an address book entry (i.e. 'ti...' crashes, but
>'ina' will bring up 'tina...' and work). So far, the crash has always
>occurred with the second letter typed in.  
>Thank you for your efforts, m
>
>K9Mail 5.403, Android 6.01, FairphoneOpen
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/3540#issuecomment-414063132

-- 
Deo Vindice
PGP : AA32DFCC (2023/07/14)

**Comment by cketti** [comment]
Is this still an issue in the latest K-9 Mail version?

If so, please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by gtalge** [comment]
No. They fixed it in one of the last updates.

On March 7, 2019 7:20:14 PM PST, cketti <notifications@github.com> wrote:
>Is this still an issue in the latest K-9 Mail version?
>
>If so, please provide a debug log. See
>https://github.com/k9mail/k-9/wiki/LoggingErrors
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/3540#issuecomment-470790344

-- 
Deo Vindice
PGP : AA33DFCC (2023/07/14)
