### ISSUE TITLE
Can't send mail -  Error: need RCPT command

### ISSUE THREAD

**Issue by JesperKick** [thunderbird/thunderbird-android#3568]
### Expected behavior
When I try to send a mail, it should actually be send to the receiver

### Actual behavior
When I try to send a mail it keeps staying in the Drafts folder.
And I get the error "Failed to send some messages. Error: need RCPT command"

### Steps to reproduce
1. Create new mail
2. Send it
3. Check in Drafts / go to receiver mailbox

### Environment
K-9 Mail version: 5.403

Android version: 8.0.0 (OxygenOS Version 5.0.4)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Phone is OnePlus 3.

**Comment by cketti** [comment]
Please provide a debug log recorded while trying to (re)send that message. See https://github.com/k9mail/k-9/wiki/LoggingErrors
