### ISSUE TITLE
No reset of entry for recipient when suggested contact from address book is selected causes next recipient entry to begin with first letters of previous one

### ISSUE THREAD

**Issue by shining-cat** [thunderbird/thunderbird-android#3577]
Have been a faithful user of K9 for a long time, and couldn't thank you guys enough for that great piece of software!
this issue may be linked to #3578 

### Expected behavior

1. I start typing a contact name as recipient for my message, say "will"
2. The suggestion popup on the recipients field opens with contacts from my address book
3. I select the one I intended: "William"
4. When I start typing the name of the next recipient,  say "geo", I expect the suggestion popup to offer me "George" to select

### Actual behavior
Step 4 : When I start typing the name of the next recipient, "geo", the first letters I had entered for the previous one ("will" for William) are still there in the field, so no contact with the letters "willgeo" will be found, obviously...

### Steps to reproduce

1. create a new message and start typing a name from your addressbook
2. select the proposed contact from the suggestion popup
3. type an other name for a second recipient, the name will begin with the letters you have entered for the first recipient and continue with what you're typing now.

### Environment
K-9 Mail version: 5.403

Android version: same behavior on both 

- Android 7.0 on Archos Phone
- Android 5.0 on Asus Tablet

Account type (IMAP, POP3, WebDAV/Exchange): I can see no link with this but I have multiple IMAP accounts

**Comment by cketti** [comment]
Is this still an issue with the latest K-9 Mail version?

**Comment by shining-cat** [comment]
@cketti Hello,
I'm on version 5.600 + Android 7.0, and the bug is still present.

**Note that there are 2 different contact suggestions** : 
the one from K9, just below the address field, and the one from the keybord auto-completion
(in my case Gboard 7.9.7.230658658-release-arm64v8a)
When starting to type a known recipient's address, I am presented with a suggestion from both apps.

If I select the K9 suggestion, everything is fine, and I can start typing the next recipient's address
The problem only arises if I select the keyboard's suggestion, in which case the address added by the auto-completion seems to not be recognized by K9 as a valid address anymore
In that case, if I start typing the next recipient's address, a space is added in the address field after the previous (completed) address (just as the auto-completion works everywhere), but the next address is not recognized as such by K9, because something other than a space is needed between two email addresses in an email address field (I would guess a semi-column or a comma)

Hope I gave every details needed :)
have a good day!

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
