### ISSUE TITLE
Gmail refuses email to multiple gmail recipients, claiming From: field is missing

### ISSUE THREAD

**Issue by axelsimon** [thunderbird/thunderbird-android#3616]
Hi,
On Monday (5 days ago) answered a group email where most (all but two of the 24 of the 30 ish) recipients where gmail addresses.
I immediately got an "Undelivered Mail Returned to Sender" return from my email provider's mailer daemon, with this, for each gmail user:

```
<user@gmail.com>: host gmail-smtp-in.l.google.com[64.233.184.26]
said: 550-5.7.1 [217.70.183.201 11] Our system has detected that this
message is 550-5.7.1 not RFC 5322 compliant: 550-5.7.1 'From' header is
missing. 550-5.7.1 To reduce the amount of spam sent to Gmail, this message
has been 550-5.7.1 blocked. Please visit 550-5.7.1
https://support.google.com/mail/?p=RfcMessageNonCompliant 550 5.7.1 and
review RFC 5322 specifications for more information. o6-v6si12588343wmb.167
- gsmtp (in reply to end of DATA command)
```
I tried to check if the From: field was indeed empty when sending email from K9, but saw this in my sent message's source:
`From: axx | axel simon <redacted@redacted.net>`
I tried to remove the pipe '|' in case that was throwing Gmail's filters but, no difference. I tried again a few days later, in case it was very temporary issue, but still the same error.
I also tried to send an email to only one gmail contact, it went through fine.

On the other hand, I also investigated with my email provider, and they suggested to try sending via they webmail, which worked.
So the situation is a bit weird. It might be a transient issue with gmail, but I thought it was worth reporting.

### Expected behavior
Gmail should accept and deliver the email.

### Actual behavior
Gmail throws back a en error complaining the message doesn't conform to RFC 5322

### Steps to reproduce
1. Reply all to a message with multiple gmail users

### Environment
K-9 Mail version: 5.403 (Fdroid)

Android version: 5.1.1 (I know…)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Is this still an issue with the latest K-9 Mail version?

**Comment by axelsimon** [comment]
I haven't seen this in a while, but also haven't sent any emails to groups of gmail users. So hard to say, sorry.

**Comment by cketti** [comment]
It's probably not the `From` header, but the `To` header that got incorrectly wrapped.
See issue #822
