### ISSUE TITLE
missing folders in Yahoo mail

### ISSUE THREAD

**Issue by blub4747** [thunderbird/thunderbird-android#3626]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior

I added my yahoo mail account to K9 and only the main folders are visible.
Like Inbox,Outbox,trash and spam.

### Actual behavior
Any other of my personally created folder are not visible.

### Steps to reproduce
I let K9 auto detect the server settings for my yahoo.

### Environment
K-9 Mail version:
5.600
Android version:
8.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP
imap.mail.yahoo.com
SSL/TLS Port 993, normal password

SMTP
smtp.mail.yahoo.com
SSL/TLS Port 465, normal password

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
