### ISSUE TITLE
"Bcc all messages to"-setting is ignored in IMAP accounts

### ISSUE THREAD

**Issue by Marinho96** [thunderbird/thunderbird-android#3631]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Send all mails automatically to BCC recipients who are named in the related account setting (Sending mail > Composition defaults > Bcc all messages to).

### Actual behavior
In case of IMAP, mails are only sent to recipients who are named in the mail itself. The further adress in BCC setting is ignored. It works for POP3, but not for IMAP. It works with IMAP in privous versions also.

### Steps to reproduce
1. Use an IMAP account and set a BCC mail in the account setting of an email adress (Sending mail > Composition defaults > Bcc all messages to)
2. Send an email from this email-adress to another email adress
3. See that the mail was not send to the BCC adress

### Environment
K-9 Mail version: 5.6

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by d-tamm** [comment]
I can confirm this behaviour. Using K9 version 5.600

**Comment by d-tamm** [comment]
Does actually not even work when setting up as POP. Anyway, sending is done via SMTP...
Setting BCC on individual messages does work, though.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
