### ISSUE TITLE
Unified Inbox does not include any email from a particular account

### ISSUE THREAD

**Issue by samandiriel** [thunderbird/thunderbird-android#3634]
### Expected behavior
When viewing the unified inbox, I should see email from all three accounts.

### Actual behavior
I only see email from two of the three accounts.

### Steps to reproduce
1.  Add three GSuite accounts to K9
2.  Open unified inbox.
3.  All emails from first added account do not appear.

This has been a problem since I got a new phone and installed K9.  It has not cleared up despite reboots and both OS and app updates.  Going into the affected account's inbox's folder settings shows that the "Unify" checkbox is indeed checked.

### Environment
K-9 Mail version:  5.6.00

Android version:  8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by KristianWedberg** [comment]
I'm seeing the same bug since about a month ago - Unify enabled on two account inboxes, but only one of them included in a Unified Inbox. It worked fine before this.

Any ideas?

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
