### ISSUE TITLE
K9 traffic exploded

### ISSUE THREAD

**Issue by mtw171** [thunderbird/thunderbird-android#3642]
### Expected behavior
The last months, K9 did use around 200 MB for traffic. 

### Actual behavior
In the last 3 weeks K9 did generate 3600 MB traffic! I did not change any of the settings, neither in K9 nor at my Mail-Server, I did not change my behaviour using K9 and I did get as many mails as usual -what happens here?

### Steps to reproduce
I do not know

### Environment
K-9 Mail version: 5.600

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by njeyaakili** [comment]
under an account, go to:
  - settings
    - account settings
      - fetching mail
        - fetch messages up to

set the value to something small.  I think the default may be something like 32kb. then pulling the whole of these messages is your choice.

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by lifespeed1** [comment]
I am also having this problem, K-9 mail can consume as much as 15GB in a month!  Our family has 4 phones with K-9, but only one is exhibiting this problem.  I have tried obvious settings adjustments like limiting automatic download size and polling only when connecting for push, but to no avail.  At the moment the offending phone has background data disabled for K-9 in an attempt to mitigate the problem.  I will try enabling background data and posting a log.

**Comment by IVData** [comment]
I am having this issue too only the last few months. K9 uses ~800 MB per month, but I get very few emails on my accounts. Data usage has changed recently and was never an issue before. k9 version 5.600.

Here is a debug log, over which about 5-10MB was used: https://i.ivdata.net/selif/8uznbrjz.txt

**Comment by cketti** [comment]
@IVData: It looks like you're using Push with a lot of folders. It also looks like K-9 Mail is configured to do a sync once a Push connection has been established. This can cause lots of syncs to happen if the network drops out and comes back a lot.
You're syncing Trash folders which see a lot of changes. This will cause lots of messages to be downloaded. Later newly deleted messages will be downloaded and the previously downloaded ones will be removed again because of the local message limit. You probably want to disable automatic syncing of Trash folders because of this.
Then there's a folder that contains some messages with invalid recipient headers. This will prevent the messages from being saved to the message database. Unfortunately, we currently don't remember these errors and download such messages again during the next sync.

The latest beta version should ignore invalid recipient headers and store the messages anyway.

**Comment by IVData** [comment]
> @IVData: It looks like you're using Push with a lot of folders.

I have 3 accounts in K9 and with only the default folders (Archive, Drafts, Inbox, Outbox, Sent, Spam, Trash). I haven't created any folders at all.

> It also looks like K-9 Mail is configured to do a sync once a Push connection has been established. This can cause lots of syncs to happen if the network drops out and comes back a lot.

How can I stop it from doing this? I've just noticed I had the poll frequency set to 10 mins, I've made that 'never' for all of my accounts for now.

> You're syncing Trash folders which see a lot of changes. 

These folders shouldn't see a lot of changes. I get maaaybee 5 emails a day. I've made trash folders second class and set all the accounts to only sync first class folders which should fix this anyway.

> Then there's a folder that contains some messages with invalid recipient headers. This will prevent the messages from being saved to the message database. Unfortunately, we currently don't remember these errors and download such messages again during the next sync.

Can you tell me which folder that is?

Thanks

**Comment by mafgh** [comment]
Just now, my k9 (v5.600) also used up a lot of data.

I also noticed that checking for new mail was really slow, and the displayed counters were way of: f.e. 0/231 Drafts, when there were only 4 mails in the Drafts folder.

In the past I did experience the slowdown problem a couple of times. The only fix that would speed up k-9 again for me was long-press on the account, recreate data.

**Comment by lifespeed1** [comment]
I had to uninstall K-9 from all our phones after nearly a decade of use.  I can't deal with an email app that can consume 15GB of mobile data due to a bug that has not been addressed to this day!  I use Aquamail now.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
