### ISSUE TITLE
Crash on open certain messages

### ISSUE THREAD

**Issue by Grokenberger** [thunderbird/thunderbird-android#3652]
Certain spam messages, not detected by German email provider GMX (false negative), causing k-9 to crash.

### Expected behavior
On tapping a message from folder list, the message should appear in detailed view.

### Actual behavior
On tapping a message from folder list, k-9 crashes

### Steps to reproduce
1. Try getting a spam message from GMX.
2. Account type doesn't matter.
3. Try to open the message.

### Environment
K-9 Mail version: 5.600

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP/POP3

### Additional information
When opening the same message with Thunderbird, a blank page appears. The source view contains some crude HTML code. If needed, I can link the body's content.

Hope I hit the relevant error from **logcat**:

[logcat_10-08-2018_09-49-44.txt](https://github.com/k9mail/k-9/files/2455144/logcat_10-08-2018_09-49-44.txt)

**Comment by pfaucon** [comment]
Do you have the raw message itself? It looks like the issue is that the address (or list of addresses) is null and that might not be handled properly internally.

**Comment by Grokenberger** [comment]
@pfaucon Nothing special about the header. The "From:" and "To:" lines exist and are properly formatted. Only one line looks conspicuous to me:

`Require-Recipient-Valid-Since: my.mailadress@gmx.net Sat, 06 Oct 2018 07:49:28 -0400`

Missing quotes and brackets, maybe?
