### ISSUE TITLE
Stacked notifications on K9>=5.108 & android<7 & NOT Android Wear

### ISSUE THREAD

**Issue by Dook1** [thunderbird/thunderbird-android#3657]
On the phone (not Android Wear device) with android 4.0.4, I get stacked notifications (one summary with a total number of new emails and a separate notifications for each email). Why?
K9<5.108 - everything is ok - only one summary notification without stacked notifications .

**Comment by cketti** [comment]
The next K-9 Mail version won't support Android 4.0.4 any longer. So this will no longer be an issue.
