### ISSUE TITLE
Widget labels do not persist

### ISSUE THREAD

**Issue by paulshedley** [thunderbird/thunderbird-android#3663]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Widget to add single mailbox shortcut to Android screen allows selections of mailbox and displays an icon labelled with the name of that inbox.

### Actual behavior
Initially, labels appear correctly, but those labels do not persist leaving all mailbox icons labelled as k9-Mail

### Steps to reproduce
1.  Add mailbox access widget with label
2.  wait, using phone normally
3.

### Environment
K-9 Mail version:  5.600

Android version:  Android 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):  multiple IMAP accounts

**Comment by cketti** [comment]
What kind of phone and what launcher are you using?
