### ISSUE TITLE
Dark theme cutting off txt

### ISSUE THREAD

**Issue by starsaa** [thunderbird/thunderbird-android#3668]
Tell us what happens instead
Dark theme cuts off bottom of hanging letters in certain styles of txt.
![capture _2018-10-18-16-02-09 1](https://user-images.githubusercontent.com/44275203/47184206-a7db8b80-d2ef-11e8-8ae8-a42f1a5321dc.png)
This has been the same for several years on 3 different phones (Galaxy S6, S7E and currently XCharge) all have been through resets and updates  to both OS and Mail, I was hoping a fix would come out on its own but not yet so I will mention it. Did a search and it looks like it may be only me for some reason. Also it is not all type faces or point sizes just some and seems like bold or some kind of highlight. 

### Environment
K-9 Mail version: 5.6

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Are you sure this is related to the dark theme?

**Comment by starsaa** [comment]
I may have have done it wrong but I replied to the e-mail I received. Here is what I typed into the reply:

Just rechecked and the hanging letters do show up in the light theme. I used the same e-mail to test as I posted in the message for the dark.

Sorry if I did it the wrong way, I'm an old stye techie that doesn't usually need to ask for help. Still getting used to "wiki things" :)

**Comment by cketti** [comment]
The improvements discussed in #4198 will probably fix this.
