### ISSUE TITLE
Adding Exchange account throws NPE

### ISSUE THREAD

**Issue by leaumar** [thunderbird/thunderbird-android#3669]
### Expected behavior
Adding an Exchange account should just work or give meaningful error messages.

### Actual behavior
Adding an Exchange account prints a literal java NPE message on the screen.

### Steps to reproduce
Censored because reasons, I can give the actual text to the devs in private if they need me to. It doesn't matter if or what I fill out in the 3 advanced fields.

![screenshot_20181020-202946](https://user-images.githubusercontent.com/3950300/47259316-16634980-d4a8-11e8-963c-b4156c600e64.png)

![screenshot_20181020-202937](https://user-images.githubusercontent.com/3950300/47259303-da2fe900-d4a7-11e8-88ec-396abeb3b557.png)

### Environment
K-9 Mail version: 5.600
Android version: Lineageos 7.1.2

**Comment by rogers1106** [comment]
Please read this. Maybe it will help.
https://github.com/k9mail/k-9/wiki/K9MailAndExchange

**Comment by cketti** [comment]
Obsolete because WebDAV support will be removed. See #4251.
