### ISSUE TITLE
XXE in WebDavStore

### ISSUE THREAD

**Issue by prodigysml** [thunderbird/thunderbird-android#3681]
# The Issue
An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occurred
The following code snippets display the usage of `saxparserfactory` without securely disabling entities:
https://github.com/k9mail/k-9/blob/18aee1b92c902dc5e98d89045e09919adf483b4a/mail/protocols/webdav/src/main/java/com/fsck/k9/mail/store/webdav/WebDavStore.java#L943

# Remediation
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet

**Comment by cketti** [comment]
Obsolete because WebDAV support will be removed. See #4251.
