### ISSUE TITLE
POP3 Cannot - "Download Complete Message" - Connection Error

### ISSUE THREAD

**Issue by Krammig** [thunderbird/thunderbird-android#3683]
### Expected behavior
Tapping "Download Complete Message" should download the full message including images. 
Email contents and attachments should be available to view same as IMAP
Attachments should be listed but are not. 

### Actual behavior
Images are not seen (expected as set in settings) however they cannot be retrieved either
Attachments are not listed so no notification of attachments exist
Tapping "Download Complete Message" shows a soap message "Connection Error"
despite the emails immediately prior being received Ok. 
It seems only certain basic info comes though for a POP message. 

### Steps to reproduce
1.  Create a POP3 account - in my case a corporate account
2.  Send an email to that POP3 account including images and attachments
3.  Receive the email and notice missing attachments and content and error message
4.  Not using SSL

### Environment
K-9 Mail version:   5.6  Build #  3679

Android version:   7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):    POP3

**Comment by cketti** [comment]
> K-9 Mail version: 5.6 Build # 3679

Did you download a development version from Cloudbees?

**Comment by Krammig** [comment]
Sorry for the delay in replying, I didn't see this. 

Nope it was just via  k-9/releases

**Comment by cketti** [comment]
Obsolete because of #4974
