### ISSUE TITLE
Selecting multi emails selects an email down 1 or 2 from the selected email

### ISSUE THREAD

**Issue by BushTrocity** [thunderbird/thunderbird-android#3690]
### Expected behavior
When selecting multiple emails it should highlight the ones i select.

### Actual behavior
When selecting multiple emails it sometimes highlights 1 or 2 emails down from the one i selected.

### Steps to reproduce
I can not get it to act up every time but it seems to just happen when there is more then 7 emails in my unified inbox.

### Environment
K-9 Mail version: 5.600

Android version: Version 9 build PPR2.181005.003

Phone Model; Google Pixel 2XL

Account type (IMAP, POP3, WebDAV/Exchange): 3 IMAP emails

**Comment by cketti** [comment]
Might be related to #3408

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
