### ISSUE TITLE
broken wrapping of quotes 

### ISSUE THREAD

**Issue by traut21** [thunderbird/thunderbird-android#3692]
### Expected behavior
When I do edit a quote, the indention and line wraps should not be broken.

### Actual behavior
A quoted text like
> > 12345 12345 12345 12345
> > 12345 12345 12345 12345
> 67890 67890 67890 67890
> 67890 67890 67890 67890

may be rewrapped to
> > 12345 12345 12345 
> 12345
> > 12345 12345 12345 
> 12345
> 67890 67890 67890 
> 67890
> 67890 67890 67890 
> 67890

I guess it does appear especially for quotes with at least two quote levels.

Either DO NOT rewrap quotes.
Or make sure to use proper rewrapping (see RFC 3676) 

### Steps to reproduce
1. take a message with multilevel quotes for several lines and reply to it
2. choose to edit the message
3. enter your own answer, then send it

### Environment
K-9 Mail version: 5.600

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3

**Comment by joelagnel** [comment]
Really would love for this to be fixed. Thanks.

**Comment by cketti** [comment]
This seems to no longer be an issue with K-9 Mail 6.303.
