### ISSUE TITLE
prefer-encrypt: mutual header is not sent

### ISSUE THREAD

**Issue by b3yond** [thunderbird/thunderbird-android#3703]
### Expected behavior
If I chose the autocrypt mutual mode in the settings, the prefer-encrypt: mutual header should be sent.

### Actual behavior
in sent emails there is no prefer-encrypt: mutual header

### Steps to reproduce
1. choose PGP key in OpenKeyChain/K9 account cryptography settings
2. choose mutual mode in the account cryptography settings
3. send a test mail
4. look at the source code in the recipient's mailbox, see that there is no header

### Environment
K-9 Mail version: 5.600

Android version: Android 7.1.2, Lineage 14.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

CC @d24phant

**Comment by cketti** [comment]
Works for me with K-9 Mail 5.710. Can you please test the current beta version and let us know if this fixes the issue for you? https://github.com/k9mail/k-9/releases
