### ISSUE TITLE
Message shown as attachment if sent by Enigmail/pEp

### ISSUE THREAD

**Issue by Fabian-G** [thunderbird/thunderbird-android#3715]
I'm actually not sure if this is more like a bug report, a feature request for pEp support or the wrong repo, because it might be OpenKeyChains fault. 

### Expected behavior
K9 should directly show the message text of a message sent by Enigmail in "force pEp" mode.

### Actual behavior
K9 shows the actual message as an attachment "msg.txt", if the message was encrypted by Enigmail in pEp mode(without pEp everything works fine).

Decrypting the message using the thunderbird+Enigmail and then viewing the decrypted message in k9 works as expected though.

### Steps to reproduce
1. Configure an E-Mail client to use pEp
2. Send an encrypted E-Mail
3. Decrypt and view the message in K9

### Environment
K-9 Mail version: 5.600

Android version: 8.10 (Lineage OS 15.1)

OpenKeyChain version: 5.2

Enigmail version: 2.0.8

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

### The Message in question (Unnecessary headers + addresses stripped)
```
Return-Path: <>
Delivered-To: 
To: 
From: 
Date: Thu, 15 Nov 2018 18:48:10 +0100
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101
 Thunderbird/60.3.1
MIME-Version: 1.0
Subject: pEp
X-Pep-Version: 2.0
Content-Type: multipart/encrypted;
	boundary="150a7cd267c4ed92eaa7dd02ad00a18";
	protocol="application/pgp-encrypted"

--150a7cd267c4ed92eaa7dd02ad00a18
Content-Type: application/pgp-encrypted

Version: 1
--150a7cd267c4ed92eaa7dd02ad00a18
Content-Type: application/octet-stream
Content-Transfer-Encoding: 7bit
Content-Disposition: inline; filename="msg.asc"

-----BEGIN PGP MESSAGE-----

hQEMAzbLe+pMYVSbAQgAnjMYVX2VgmYrRg8P1RYZcx+k8t1FSIputpffaaR4CrzF
[......]
PvnkhO5B1cmZhWNVNeIyoRBwUiAn4cZWCDM87Fzre5z1d75f5G48QFsfm8Wi90iP
PcSID2M1gdCx1HKSWpaY
=f29a
-----END PGP MESSAGE-----

--150a7cd267c4ed92eaa7dd02ad00a18--

```
## Same message, but decrypted using enigmail
```
Return-Path: <>
Delivered-To: 
To: 
From: 
Date: Thu, 15 Nov 2018 18:48:10 +0100
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101
 Thunderbird/60.3.1
Mime-Version: 1.0
Subject: pEp
X-Pep-Version: 2.0
Content-Type: multipart/mixed; boundary="150a7cd267c4ed92eaa7dd02ad00a18"

This is a multi-part message in MIME format.
--150a7cd267c4ed92eaa7dd02ad00a18
Content-Type: multipart/mixed; boundary="7bb0013084157eec16748313b23cfd"
MIME-Version: 1.0

--7bb0013084157eec16748313b23cfd
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

Subject: Test

plain test


--7bb0013084157eec16748313b23cfd
Content-Type: application/pgp-keys
Content-Disposition: attachment; filename="pEpkey.asc"

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFvtr1MBCACZGrv6ayKguiJoWVp9Oc7vU7IgHg5ae/XJabrxm9pqJHfoZmh9
[...]
JYpUhtESDWvVAUZaQZu29fJvVvxlzNmHsFnb/TK3KwdmUyzt9bdwMcsuWBhFdfCt
uPh8G+lWIh6e
=KCtZ
-----END PGP PUBLIC KEY BLOCK-----

--7bb0013084157eec16748313b23cfd--


--150a7cd267c4ed92eaa7dd02ad00a18--
```

**Comment by cketti** [comment]
@Valodim: Could you please look into this when you find some time?

**Comment by Valodim** [comment]
That message doesn't look too off to me, at least it's not the "pep message format" I saw a while back that didn't make any sense to me. This might be caused by the redundant multipart/mixed in there, but I'm not sure. Could you send such a message to me for investigation? -> look@my.amazin.horse, key ends with 0xdeadfa11

**Comment by pravi** [comment]
![Screenshot_20210801-153455_K-9_Mail](https://user-images.githubusercontent.com/708222/127767142-d9d3ddc4-c9ec-4f14-9eae-c034ce547c49.png)

@Valodim I have sent a sample mail from pep to your email address shared earlier.

**Comment by cketti** [comment]
@Valodim: Any updates on this?

**Comment by Valodim** [comment]
no idea. the sample mail that I got from earlier wasn't encrypted in any way, so I'm not sure what to investigate there.

Enigmail/pEp is also no longer a thing, since Enigmail is no longer a thing, so not sure what exactly the report here refers to. There are pEp email clients for different platforms, but I have never seen an email from any of them and I don't know if they all behave the same. All in all, not an actionable issue :shrug:

**Comment by cketti** [comment]
Thanks. Sounds like this issue can be closed.
