### ISSUE TITLE
Dates in saved emails out of order

### ISSUE THREAD

**Issue by chonorof** [thunderbird/thunderbird-android#3731]
### Expected behavior
Dates are in a sequential order. Of ALL received emails

### Actual behavior
Received emails are out of order. Emails go from 11/17/2018 back April 17 and then jump up to today and includes all new emails are listed before that date.

### Steps to reproduce
1. Just get new emails
2.
3.

### Environment
K-9 Mail version: 5.6. Most current

Android version:
8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):
POP

**Comment by cketti** [comment]
Did you maybe change the sort criteria from date to something else?

**Comment by chonorof** [comment]
Changed it to something else and then back and all is now okay.


-------- Original Message --------
