### ISSUE TITLE
Reattaching signature if sending failed

### ISSUE THREAD

**Issue by jatoko** [thunderbird/thunderbird-android#3781]
If sending of a message fails, K9 places the email in Drafts but does not strip off the signature, what results in an continous addition of signatures. An example is given below.
### First time error:
<img src="https://user-images.githubusercontent.com/17083784/49339851-d01d1080-f637-11e8-934c-60ac09a2cfc0.jpg" width="300">

### Second time error:
<img src="https://user-images.githubusercontent.com/17083784/49339852-d1e6d400-f637-11e8-94ea-a4bcb1f69f88.jpg" width="300">

### Expected behavior
K9 should remove signature when error occurs before it is stored in drafts OR should not reattach signature if it is already present in the message.

### Actual behavior
K9 keeps attaching signatures.

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): SMTP, IMAP

**Comment by cketti** [comment]
Messages that failed to send are no longer moved to the Drafts folder in K-9 Mail 5.7xx.
