### ISSUE TITLE
Newly created accounts all have -1 as accountNumber

### ISSUE THREAD

**Issue by morckx** [thunderbird/thunderbird-android#3787]
This was probably introduced in cd01aec9d8097eb97d593800f95e35ee603580cb

To verify:

1. Set a breakpoint here https://github.com/k9mail/k-9/blob/1552c151a565f5ff44a46d2becd35c9033d6bb3b/app/core/src/main/java/com/fsck/k9/Preferences.java#L208
2. Create a new account

**Comment by Valodim** [comment]
Thanks for doing testing like this, it's very helpful! :1st_place_medal:
