### ISSUE TITLE
K9 does not delete message from IMAP Server

### ISSUE THREAD

**Issue by gorky** [thunderbird/thunderbird-android#3801]
### Expected behavior
When deleting emails from IMAP, they should be deleted on the server (or at least moved to Trash).

### Actual behavior
Emails are marked on the server as "READ".

### Steps to reproduce
1. Account Settings - Fetch Mail
 "Sync server deletions": Checked
 "When I delete a message": Delete from Server
 "Erase deleted message on server": Immediately
2. Delete a message from the INBOX
3. Check INBOX on server.  Message is still present

### Environment
K-9 Mail version:
5.600

Android version:
8.1.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Possibly a duplicate of or related to  #2117 and/or #2118

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by gorky** [comment]
Sorry about taking so long to get this.
Btw, it only looks like deleting a message while open doesn't work.  Selecting messages to delete does appear to work (although a bit painful to read a message, then have to close it, then delete it).

I read and deleted 4 emails in this run (last 4 actions that I took, not sure about background activity).

File is attached:
[k9-log.txt](https://github.com/k9mail/k-9/files/2658311/k9-log.txt)

**Comment by mhoran** [comment]
I'm seeing this as well. While the messages show as deleted in K9, they still show up on other devices and in my mail store. They do *not* show up in my trash folder.

**Comment by N1mu3h** [comment]
I have the same issue on 2 devices, Samsung Tab A + Honor View 10, both running an Oreo custom rom. If I check Gmail in a browser then the "deleted" emails from K9 are still in the inbox. The only way to actually remove them is from the browser or when I sync them on my PC with Thunderbird.
Pretty sure that's not the expected behaviour?

**Comment by takiainen** [comment]
I've had this same issue for years as well. Deleting mails from trash doesn't actually delete them from server, and after a while the same emails get downloaded back again.

**Comment by toum1** [comment]
Same problem with IMAP/POP on Android 8.1 (this is quite new for me, 2 weeks max)
Deleted message do not appear any more locally but remains untouched on server. Quite painful.

**Comment by toum1** [comment]
> Same problem with IMAP/POP on Android 8.1 (this is quite new for me, 2 weeks max)
> Deleted message do not appear any more locally but remains untouched on server. Quite painful.

Today it is working perfectly... Nothing changed. I don't understand why.

**Comment by C-Cur** [comment]
Using K-9 Mail version 5.600 on Android version 6 on Samsung Galaxy S5 smartphone.
Deleting mail from Trash folder on smartphone does not remove emails from Trash folder on GMX mail server.

Any solution ???

TIA

**Comment by CueHD** [comment]
> Using K-9 Mail version 5.600 on Android version 6 on Samsung Galaxy S5 smartphone.
> Deleting mail from Trash folder on smartphone does not remove emails from Trash folder on GMX mail server.
> 
> Any solution ???
> 
> TIA

Check #3605 for this.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.

**Comment by georg-x** [comment]
This comment is just as an update for anyone who searches for the problem.
I had exactly the described problem with the current version.
Removing and freshly adding the GMX account solved the problem for now.
