### ISSUE TITLE
Subject is not shown when sending new mail

### ISSUE THREAD

**Issue by jjuyeon** [thunderbird/thunderbird-android#3811]
### Expected behavior
The subject I wrote when I created a new mail appears well in the sent mail.

### Actual behavior
The subject I wrote when composing new mail is not sent well

### Steps to reproduce
1. Move compose menu.
2. Write new subject and message. (ex. test subject / test message)
3. Send email
4. result ((no subject) / test message)
![image](https://user-images.githubusercontent.com/33437655/49729113-e706d700-fcb7-11e8-9276-32ab2701a884.png)

### Environment
K-9 Mail version: 5.600

Android version: 8.0.0

Account type (IMAP, POP3, ##WebDAV/Exchange):

**Comment by wiktor-k** [comment]
Interesting, I had the same issue on a debug build from master branch yesterday but it disappeared on itself so I thought it was just temporary glitch...

**Comment by morckx** [comment]
For me it's reproducible. Oops, not surprisingly. This here should be the other way around, I guess:

https://github.com/k9mail/k-9/blob/4160a1b4ee7b5761dfed945df0ac54b8bcf58065/app/ui/src/main/java/com/fsck/k9/activity/MessageCompose.java#L1512

**Comment by wiktor-k** [comment]
It appears when no cryptography provider is set the subject is empty, adding OpenKeychain even *without encrypting message* fixes subject. Also, once I set OKC I cannot unset it as the application crashes when exiting settings with:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.openintents.openpgp.util.OpenPgpApi.executeApiAsync(android.content.Intent, java.io.InputStream, java.io.OutputStream, org.openintents.openpgp.util.OpenPgpApi$IOpenPgpCallback)' on a null object reference
	at org.openintents.openpgp.util.OpenPgpKeyPreference.apiRetrievePendingIntentAndKeyInfo(OpenPgpKeyPreference.java:139)
```

Good find @morckx!

**Comment by artbristol** [comment]
I saw this too locally on master

**Comment by morckx** [comment]
Was there any motivation behind setting the subject to null when no cryptography is set?
