### ISSUE TITLE
"PGP Sign-Only" is making the emails blank for the recipients

### ISSUE THREAD

**Issue by life777eternal** [thunderbird/thunderbird-android#3816]
The "PGP Sign-Only" option is making the emails blank or nothing for the recipients.

Also would like to see a "checkbox" beside "Read Receipt" & "Delivery Status Notification" is not even there.   

A quicker way to switch email accounts would be great, in the stead of having to tap the "Dog" icon twice. K-@ Mail has a drop-down menu for changing accounts. 

Thank you. 

### Expected behavior
Recipients should be able to read the message. 

### Actual behavior
Emails are blank, nothing 

### Steps to reproduce
1. Start a new email or forward an email 
2. Enable "PGP Sign-Only" 
3. Add Recipients 
4. Send the email 
5. Ask your recipients through a secure channel of communication if they were able to read the email (something with End-to-End Encryption) 

Wire [https://Wire.com], Tox [https://Tox.chat] or Signal [https://Signal.org] 

### Environment
K-9 Mail version: 5.600

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by anonymous73** [comment]
Hi please excuse my noobiness but I am just wondering if i can sign an email with my private key if OpenKeychain doesn't have that particulr email address listed as an identity on the key. That is, if one day i publish the public key to key servers i dont want to disclose ALL my email addresses for example. I realise that is is a different question. In this situation what do people do? I don't like the idea of creating a key for each email, i think that is a bit overkill.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
