### ISSUE TITLE
Inconsistent selection of messages shown

### ISSUE THREAD

**Issue by ANEast** [thunderbird/thunderbird-android#3848]
I use an IMAP connection with sync'd messages.  I have 50 messages to be displayed in all folders, which K9 dutifully does.  However, it does not show the most recent 50 messages!  Some are not shown at all, and then occassionally really old messages will be "selected" to fill the list.  There is no log that I can easily attach for this, although the poll log is attached if it helps.  I don't know why K9 "chooses" the messages it does - maybe an incorrect assumption about the way the server numbers it's messages?

I have attached the screenshot from K9 and the screenshot from Thunderbird (on Windows 10) taken at the same time.  In all, the timespan showed in K9 should cover 68 messages, not the 8 shown....!! There does not appear to be any rhyme or reason to the issue.  This happens across many, many folders.

### Expected behavior
50 most recent messages displayed

### Actual behavior
50, mainly most recent messages, with some old ones shown and newer ones missed

### Steps to reproduce
1. IMAP connection with 50 messages

### Environment
K-9 Mail version: 5.600
Android version: 6.0.1
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

[k9log1812231756.txt](https://github.com/k9mail/k-9/files/2712633/k9log1812231756.txt)

![screenshot_20181223-183106_redacted](https://user-images.githubusercontent.com/25244435/50483913-baf09300-09e5-11e9-9264-da0c8ef2c795.png)

![thunderbird_20181223-183106_redacted](https://user-images.githubusercontent.com/25244435/50483914-bb892980-09e5-11e9-9c9b-3863e9276210.png)

**Comment by ANEast** [comment]
This is probably a duplicate of #1422 that hasn't been solved for 2 1/2 years.....

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
