### ISSUE TITLE
Fix ImapStore.listFolders() when SPECIAL-USE extension is present

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#3862]
`LIST (SPECIAL-USE) …` only lists special folders, not special folders and regular folders.

We probably want to switch back to using a regular LSUB/LIST, then querying the special folders and adding them to our list afterwards. That way we'll get to use a special folder, even if it wasn't included in the result list of the previous LIST command (because the user isn't subscribed to it or it's outside of the subtree specified by the IMAP path prefix).

**Comment by cketti** [comment]
We add the path prefix to all folder names :disappointed:.  So for now we'll just change the extended LIST command to return all folders, including special-use attributes.

**Comment by philipwhiuk** [comment]
Yeah the way we convert between names and paths sucks - see #2729
