### ISSUE TITLE
Sync doesn't obey setting anymore

### ISSUE THREAD

**Issue by guessit-dev** [thunderbird/thunderbird-android#3866]
### Expected behavior
k9 shouldn't sync if never is selected as background sync setting. 

### Actual behavior
k9 still syncs regardless of setting. 

### Steps to reproduce
1. Just turn off background sync
2. It will still sync

### Environment
K-9 Mail version: master branch

Android version: 7.1.2

Account type: IMAP

I think this happens since merge of #3763 

This issue describes the bug mentioned in #3853 better/explicitly.

**Comment by artbristol** [comment]
I have reproduced this on master so I'll try to fix it

**Comment by artbristol** [comment]
@cketti I assume the fix is to change some of the classes in `com.fsck.k9.job` to check `CoreService.isMailSyncDisabled` ?
