### ISSUE TITLE
IMAP sync delete does not remove messages from Hotmail Server account

### ISSUE THREAD

**Issue by Krammig** [thunderbird/thunderbird-android#3903]
### Expected behavior
Messages deleted in K9 should also be deleted at the mail server end, if the appropriate settings have been made in both K9 and in this case Hotmail. 

This is not the case for IMAP Hotmail, nor for a POP account I have set up on a corporate server for testing. 

I have set up a couple of IMAP accounts on Hotmail and carefully stepped through testing of deleting messages on the Server end and deleting messages in K9. 
In doing so I have also made sure that all settings in Hotmail (sync settings) and in K9 have been correctly set. 

Deleting a message on the server side (Hotmail) Does delete it in K9
However deleting a message in K9 - Does Not - delete the message on the Server for IMAP (Hotmail) nor for a test POP corporate account I set up. 

### Actual behavior
Emails being deleted in K9 are not being deleted at the server end for both IMAP specifically and POP. 

### Steps to reproduce
Watching an open Hotmail account page
Apply all settings for Sync and Immediate delete etc within K9
Apply settings in Hotmail to allow devices to delete messages
Select a message in K9 and select Delete. 
Message is deleted in K9
Message is Not deleted at the server
Refresh server page - still nothing
Delete message out of Deleted folder in K9
Still nothing at server - message remains

### Environment
K-9 Mail version:  5.6  with latest updates as at today. 

Android version:  5.1 and 7.1

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP   POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:   NONE

**Comment by cketti** [comment]
Please record a debug log while trying to delete a message. See https://github.com/k9mail/k-9/wiki/LoggingErrors
