### ISSUE TITLE
Setting autocrypt-mutual to 'on' does not survive reboot or application shut down

### ISSUE THREAD

**Issue by optimumpr** [thunderbird/thunderbird-android#3938]
### Expected behavior
With properly generated and integrated PGP key, setting autocrypt-mutual to 'On' should survive reboot or application shut down.

### Actual behavior
Instead, after reboot or app shut down, autocrypt mutual returns to 'unchecked'

### Steps to reproduce
1. Generate PGP keys, integrate them to K9, go to account settings/cryptography and select autocrypt mutual ('On')
2. Reboot the phone, and the setting resets to 'unchecked'
3. Same behavior when K9 is killed (by kill button)

### Environment
K-9 Mail version: latest

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
I can't reproduce this with 5.710. The bug might have been fixed when the settings screen was rewritten.
