### ISSUE TITLE
Freeze for seconds after delete IMAP-email and empty trash.

### ISSUE THREAD

**Issue by tachtler** [thunderbird/thunderbird-android#3944]
Hi K9-Mail-Team,

### Expected behavior
When I delete a message (I'm using IMAP) and the message was deleted to the trash folder, and I choose empty trash, the K9-Mail refresh immediately.

**Was o.k with Samsung Galaxy S8 and Android version 8.0 Oreo.**

### Actual behavior
When I delete a message (I'm using IMAP) and the message was deleted to the trash folder, and I choose empty trash, the K9-Mail app freeze for a few (5) seconds

**Seen as I update my Samsung Galaxy S8 to Android version 9.0 Pie.**

### Steps to reproduce
1. Delete a (IMAP) email to the trash folder
2. Do empty trash folder (choose "empty trash" from the dot menu)
3. ...wait...

### Environment
K-9 Mail version: **5.600**

Android version: Samsung Galaxy S8 (stock image) **9** (Pie) 

Account type (IMAP, POP3, WebDAV/Exchange): **IMAP** (dovecot)

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: **not done, because there are  no errors**.

Thank you for your help!
Klaus.

**Comment by gdt** [comment]
Logs contain all sorts of information about what is going on and why.   The lack of an error shown in the UI is not a reason to skip looking at logs.

**Comment by cketti** [comment]
What exactly do you mean by freeze? Are the folder contents not showing or is the whole app not responding to any input?

**Comment by tachtler** [comment]
Hi gdt,
hi cketti,

I'm trying to connect my **Samsung Galaxy S8 with the PC** and the Device will be shown as plugged (Linux CentOS 7) I've already installed the `android-tools` with `adb`, but when I type `adb devices `nothing will be shown:
```
# adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached 
```
I've already enabled inside K9-Mail | Einstellungen (settings) | Globale Einstellungen (global settings) | Fehlersuchvorgang (Error search ?!?) | Fehlersuchprotokoll (Error protocol ?!?) **TRUE**.

When I talk about "freeze" I mean, always if I use the Papierkorb leeren (empty trash) the **K9-Mail wait 5 to 10 sec. and then the program continue to work as expected**. No error message was shown.

This start first with the Android 9.0 (Pie) update, with the Android 8.0 (Oreo) everything was fast.

Thank you for your patience with me!
Klaus.

**Comment by tachtler** [comment]
Hi gdt,
hi cketti,

after a view Android updates in the last days, the problem was gone.
The "**empty trash**" function is as fast as expected.

Thank you, this issue can be closed.
Klaus.
