### ISSUE TITLE
swipe-to-select doesn't work

### ISSUE THREAD

**Issue by mruwek** [thunderbird/thunderbird-android#3957]
### Expected behavior
Swiping on a message in message-list view should select it with visible highlight and entering "select mode".

### Actual behavior
Nothing happens.

### Steps to reproduce
1. Try to select a message with swipe

### Environment
K-9 Mail version: debug build of master branch: 3e1a8da32a7e2bbb55441acf6e5de26e707ac878
Android version: 9.0

Logs don't show anything, but I bisected the problem wit git-bisect and first bad commit is:
4fe8c417adb6037845232d026c863b12a733dc11 so this is probably conflict with navigation drawer which also listens for swipe movement.

[bisect-log-swipe_to_select.txt](https://github.com/k9mail/k-9/files/2948300/bisect-log-swipe_to_select.txt)

**Comment by aqeelparpia** [comment]
Hello @mruwek could I work on this bug?

**Comment by skironDotNet** [comment]
Production from playstore works for me. Nokia 8, Android 9

**Comment by jvandenbroek** [comment]
Same issue after updating to latest beta today. Now I realise how important such basic functionality is in my workflow :)

**Comment by marcelser** [comment]
Could stress that enough and now with the public release of 5.700 I got struck by this too and it drives me nuts. I really hope it doesn't take weeks or months to get this fixed in public version
