### ISSUE TITLE
Lost draft text after process death

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#3970]
ok, so I just wrote an e-mail and lost the text while switching between applications. sad times :'(

it saved it in drafts successfully several times.

but then, I switched back to k9 again, added even more images (in the end there were 20 attachments), I looked down and my text was just gone.
the attachments were all still there, even my change to the signature was still there.
but the text was gone.

one possible cause could be the unreliable mobile network connection I was running on at that point. (it had a few hiccups, before it got stable again), I was riding a train and right after I left it, gone

anyways I would be glad (in the name of every user) if you could take a look at what could have caused this at some point, thank you :)

I won't get the mail back and that is fine, just sad
I won't try to reproduce this with logging enabled. (too exhausting and too many possible causes)

I'm running a oneplus 3T, stock firmware but not up to date, Android 7.0

one possible cause: sometimes my phone randomly kills background applications that use too much power (not the usual android way, a custom thing by oneplus)
it's something I can't disable sadly
maybe they removed it in a newer version

If you can't think of a reason for the data loss, then you should give up. but I think it's more likely a bug in the app that can be fixed :)

Regards

**Comment by Djfe** [comment]
and now the attachments are gone as well... :/

**Comment by profplump** [comment]
This could be issue 2581 -- that would explain the existence of attachments even as the body text is lost

**Comment by garrettboone** [comment]
I'm on LineageOS 16, Android Pie, and when I intentionally save drafts, while having the app set to not be optimized with battery use, I only occasionally lose all draft content.

It was like this before I switched to 16.

I have multiple accounts, and it does not seem to be a domain issue vs domain with sudomain addressing.

It does not appear to involve the use of the clipboard.

It's a glitchy problem. Maybe there is something running async that shouldn't be. I cannot make it happen.

**Comment by garrettboone** [comment]
Not sure if it helps but here are Log Files from dovecot on my server:
```
Jul 30 07:49:47 mx dovecot: imap-login: Login: user=<support@education.domain.org>, method=PLAIN, rip=192.168.10.2, lip=10.0.40.3, mpid=29855, TLS, **session=<4uICm+SOJ+LAqAoC>**
Jul 30 07:49:48 mx dovecot: imap-login: Login: user=<support@education.domain.org>, method=PLAIN, rip=192.168.10.2, lip=10.0.40.3, mpid=29859, TLS, **session=<qWoFm+SOKOLAqAoC>**
```
Are the above two instances of connections normal like this for imap? I was on OpenVPN.

Started the message:
```
Jul 30 07:51:04 mx dovecot: imap(support@education.domain.org): delete: box=Drafts, uid=16, msgid=<4662E43D-E956-4E57-A666-7FB56E6D1B24@education.domain.org>, size=1487, from=<support@education.domain.org>, subject=Trouble Logging into Education
Jul 30 07:51:04 mx dovecot: imap(support@education.domain.org): expunge: box=Drafts, uid=16, msgid=<4662E43D-E956-4E57-A666-7FB56E6D1B24@education.domain.org>, size=1487, from=<support@education.domain.org>, subject=Trouble Logging into Education
```
Switched to grab a URL and came back, entered the URL:
```
Jul 30 07:51:30 mx dovecot: imap(support@education.domain.org): delete: box=Drafts, uid=17, msgid=<**F9C2CB1C-B42B-48CA-B048-6666D081E3E1**@education.domain.org>, size=1229, from=<support@education.domain.org>, subject=Trouble Logging into Education
Jul 30 07:51:30 mx dovecot: imap(support@education.domain.org): expunge: box=Drafts, uid=17, msgid=<**F9C2CB1C-B42B-48CA-B048-6666D081E3E1**@education.domain.org>, size=1229, from=<support@education.domain.org>, subject=Trouble Logging into Education
```
The I switched again and came back but it was empty. So I deleted in. Online, I found it in the trash and message **F9C2CB1C-B42B-48CA-B048-6666D081E3E1** confirmed to not have text, but has html:
```

------1VZ85MG2AP5NPY3WPTMI4HXLNTUFKR
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable


------1VZ85MG2AP5NPY3WPTMI4HXLNTUFKR
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hi Bob,<br><br>Our records indicate [the rest of content removed]<br><br>Thanks!
------1VZ85MG2AP5NPY3WPTMI4HXLNTUFKR--
```

**Comment by Djfe** [comment]
Will close this.
Open a new issue, in-case you are still experiencing issues like these. (for me it was a one time thing)
