### ISSUE TITLE
Spam folder with spaces not recognized or opened

### ISSUE THREAD

**Issue by tlhackque** [thunderbird/thunderbird-android#3974]
I am new to K-9, but install & setup seemed to go OK.  Almost. 

I selected 'Train As Spam' as my (IMAP) Spam folder.  The name has spaces, but not the quotes.  The folder exists on the server (and has quite a few messages!)  It is accessible from Thunderbird IMAP.

I expect it to enable the Spam filing icon, and to be able to open the folder.  Neither happens.

I have no trouble accessing other folders - including folders with spaces in their names.  So it seems to be an issue with the "Spam" "special" folder.

If I look at the folder list, I see:
````
Sent (Sent)
Spam
(faint text) Command: EXAMINE "Spam";re
Trash
````
If I open the Spam folder, it appears to be empty, but says "Load up to 25 more".
Click on that, and all I get is the same message.  No messages are listed.

There is no spam icon or menu item if I open a message.  Nor a Spam option if I long-press a message.

My best guess is that the spaces in the folder name are confusing K-9.

I am running Android 9 (on a Moto X-4) PPWS29.69-26-5, security patch level 1-feb-19
K-9 verson 5.600
 
I managed to enable debug logging & retrieve a log while trying to view the Spam folder: neither "spam" nor "Spam" appears in the log.  So I don't think it's useful.

Unfortunately, I can't change the folder name on the server.

**Comment by cketti** [comment]
Please record a debug log while refreshing the folder list. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by tlhackque** [comment]
Here are the relevant pieces.  The log contains responses for a complete folder list; many of the names are sensitive.  I redacted all folder responses except those  for 'Train as Spam" and those on either side. of each  

[k9-log-redacted.txt](https://github.com/k9mail/k-9/files/2989201/k9-log-redacted.txt)

I have the full log - if you need anything else, let me know.

Also, here is a screenshot of the folder list showing the "EXAMINE" command. ![Screenshot_20190320-011618](https://user-images.githubusercontent.com/332018/54703701-aa951380-4b0f-11e9-9096-9cb75d3386fb.png)

I have rebooted the phone since the initial report.  This symptom is gone, as is the inabiity to load from the folder.  

However, there is still no spam icon or spam option if I longpresss a message in the inbox, or if I open a message and open the 3-dot menu.

**Comment by tlhackque** [comment]
For what it's worth, the log shows:
````
03-20 12:11:28.609  9685  9702 V ImapResponseParser: conn55621190<<<#null# [LIST, [\NoInferiors, \UnMarked], /, Train As Spam]
````
But RFC 3501 (IMAP) says:
> **atom-specials**   = "(" / ")" / "{" / **SP** / CTL / list-wildcards /
>                  quoted-specials / resp-specials

and in **section 5.1 Mailbox naming**:

There are certain client considerations when creating a new mailbox
   name:

   1)    Any character which is one of the **atom-specials** (see the Formal
         Syntax) will require that the mailbox name be represented as a
         **quoted string or literal**.


So it looks to me as though (assuming the log is accurate), the folder name should be quoted or expressed as a {count} literal in the LSUB (and any other) command.

Thunderbird does quote whenever a name includes an atom-special:
````
2019-03-20 22:52:23.328000 UTC - [24100:Unnamed thread 3274DEB0]: I/IMAP 339AE800:imap.example.net:A:CreateNewLineFromSocket: * LIST (\Subscribed \NoInferiors) "/" "Train As Spam"
````
In theory, it would be harmless to always quote folder names.

Whether this would resolve matters is an open question, but it seems like a step in the right direction.

**Comment by cketti** [comment]
K-9 Mail logs the already parsed version of IMAP responses. It looks like "Train As Spam" is properly recognized as folder name. I don't know what's up with the "Spam" entry in the folder list. The one you should be looking for should be displayed as "Train As Spam (Spam)". If you only find "Train As Spam" then you haven't selected that folder to act as Spam folder under 'Account settings > Folders > Spam Folder'.

**Comment by tlhackque** [comment]
Yes, I have selected the Spam folder.  It was one of the first things I did when I installed K-9 Mail.  Below are screenshots showing that I set "Train as Spam" as the "Spam Folder".

On the server, there are only two folders with 'Spam' in their names:
````
 find . -name '*Spam*'
./Train As Spam
./New Spam
./.imap/Train As Spam
./.imap/New Spam
````
(note that the ./.imap/ are dovecot indicies for the corresponding mbox files.

There are quite a few folders:
````
find .  | grep -v '\.imap' | wc -l
206
````
I did notice that "Spam" is the default name for the "Spam" folder, which does not exist on the server.  Perhaps the apparent command fragment was K-9 Mail looking for it?  This was a first time install on a phone that never used any MUA previously.  GMail app came with the device, but was never used and is disabled.  That artifcat disappeared after a reboot (power off, on) or two.

Also, screenshot showing that there is no spam icon when I open an-email.  And (not shown) if I longpress a message in INBOX, I get [subject], Select, Reply all, Reply, Send Again, Forward.  No 'Spam'.


![Screenshot_20190320-203544](https://user-images.githubusercontent.com/332018/54727832-68d88d00-4b50-11e9-8284-8696747f521e.png)
![Screenshot_20190320-203517](https://user-images.githubusercontent.com/332018/54727836-6c6c1400-4b50-11e9-9c98-31fca5b023d6.png)
![Screenshot_20190320-212315](https://user-images.githubusercontent.com/332018/54729040-88bf7f00-4b57-11e9-96e5-be4a98a2fdb3.png)

**Comment by cketti** [comment]
The "Spam" action is located inside the "Refile…" menu.

**Comment by tlhackque** [comment]
Well, that makes me feel dumb.  I looked there before, didn't find it.  But it's there now.  Like the Spam examine indicator, must be something that gets re-initialized on a reboot.

Probably won't see this issue again - "you're only a new user once".

Would be nice if Spam and Move were at the same level as "refile" - at least for me, they're as common as "Mark unread", and there does seem to be room on the screen.

Thanks for your help.  I hope that you are able, at some point, to figure out the initial odd behaviors.  The screenshots show that I wasn't imagining the errors.

**Comment by cketti** [comment]
The next K-9 Mail version won't attempt to create special folders if they don't exist on the server. And we do have plans to improve the user experience.
