### ISSUE TITLE
Trash deletion

### ISSUE THREAD

**Issue by delgado92651** [thunderbird/thunderbird-android#4008]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
The emails in the trash folder will delete.
### Actual behavior
Tell us what happens instea
 The emails in the trash folder will not delete to reproduce
1.
2.
3.

### Environment
K-9 Mail version:

Android version:
V10
Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
