### ISSUE TITLE
Sending attachments fails

### ISSUE THREAD

**Issue by diesocke** [thunderbird/thunderbird-android#4017]
Every time I add an attachment to outgoing mails K-9 doesn't send it. I rechecked the SMTPs, but regardless of what account I use - mails without attachments get sent, mails with attachmentd won't.

**Comment by d-g** [comment]
diesocke wrote:
> Every time I add an attachment to outgoing mails K-9 doesn't send it. I rechecked the SMTPs, but regardless of what account I use - mails without attachments get sent, mails with attachmentd won't.

Could not reproduce it.

**Comment by cketti** [comment]
@diesocke: Please fill out the issue template and record a debug log.

**Comment by diesocke** [comment]
Version number ist 5.6000. Will post the debug log, once I find time to connect my phone to a windows PC.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
