### ISSUE TITLE
Lock screen notifications do not display on Android Q Beta 2

### ISSUE THREAD

**Issue by mamarley** [thunderbird/thunderbird-android#4037]
### Expected behavior
When an email is received and notifications are configured appropriate, a notification of the new message should appear on the lock screen.

### Actual behavior
When only one new email has been received, nothing is displayed on the lock screen.  If two or more new emails are received, the lockscreen notifications work as normal.

### Steps to reproduce
1. Install and configure K9 on an Android Q device or emulator
2. Receive a mail
3. Go to the lock screen and see that no notification is displayed
4. Receive another mail
5. Go to the lock screen and see that notifications are displayed normally

### Environment
K-9 Mail version: 5.600

Android version: Q beta 2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Probably no longer an issue with K-9 Mail 5.800 or newer.
