### ISSUE TITLE
Forwarding a message using another account uses wrong bcc

### ISSUE THREAD

**Issue by leilich** [thunderbird/thunderbird-android#4039]
### Expected behavior
I am using two accounts a@a.de and b@ b.de. a is configured to store sent mail in sent folder, b is configured not to store in a folder, but to bcc b@b.de. If I forward an e-mail from account a, switching identity to account b, no sent folder should be used, but bcc. If I forward an email from account but, switching to identity a, sent folder should be used and no bcc.

### Actual behavior
Case 1: no sent folder is used and no bcc.
Case 2: sent folder is used and bcc.

### Steps to reproduce
Set up IMAP-email accounts, send emails a to b and b to a, forward them changing identities.

### Environment
K-9 Mail version:
5.600
Android version:
8, Huawei Mate Lite 10
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by MonikaJethani** [comment]
@cketti Can I work on this?

**Comment by cketti** [comment]
This should be fixed in K-9 Mail 5.7xx.
