### ISSUE TITLE
Inbox not sorted after deletion/return to inbox

### ISSUE THREAD

**Issue by cyberpac9** [thunderbird/thunderbird-android#4048]
### Expected behavior
After reading an email and selecting to delete the message, I should get the next message in the list. When backing out of the message to the inbox, messages should be sorted newest to oldest. 

### Actual behavior
After deletion I get a message from the middle of my inbox, message 35 out of 100, for example. A message from 2 weeks ago. When I back out to the inbox the messages are not sorted. The message selected as "next" (35 in my example) is the first message in my list. Others may be out of order as well. 

### Steps to reproduce
1. Read new message 
2. Click delete 
3. Next message you get is from 2 weeks ago, from middle of inbox. 
4. Return to inbox, messages out of order. 

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
[k9-log.txt](https://github.com/k9mail/k-9/files/3174832/k9-log.txt)

**Comment by cketti** [comment]
Are messages displayed in the expected order if you open the message list? Or do you go from a notification to the message view, delete the message and only then end up in the message list?

It sounds like you accidentally changed the sort order of the message list. You can adjust the sort order in the "sort by" menu (icon with three horizontal lines of descending length) of the message list.

If that's not it, try uninstalling, then reinstalling K-9 Mail.
