### ISSUE TITLE
inline IMG not displaying with all-caps SRC attribute

### ISSUE THREAD

**Issue by bigbyfindrake** [thunderbird/thunderbird-android#4050]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
HTML inline images should display regardless of case of tags and/or attributes.
HTML parsing of tags and attribute names should be case-insensitive.

### Actual behavior
HTML inline Images aren't displayed when SRC attribute is uppercase.

### Steps to reproduce
Send yourself an HTML e-mail with some code like this:

```html
<TABLE BORDER=5>
<TR><TD>img src</TD><TD><img src="http://www.ephemeron.org/~bigby/small.jpg"></TD></TR>
<TR><TD>img SRC</TD><TD><img SRC="http://www.ephemeron.org/~bigby/small.jpg"></TD></TR>
<TR><TD>IMG src</TD><TD><IMG src="http://www.ephemeron.org/~bigby/small.jpg"></TD></TR>
<TR><TD>IMG SRC</TD><TD><IMG SRC="http://www.ephemeron.org/~bigby/small.jpg"></TD></TR>
</TABLE>
```

2. Observe non-uniform output.

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): (I've only tested with) IMAP.

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Can you please provide the full HTML of such a message?

**Comment by cketti** [comment]
I can't reproduce this with K-9 Mail 5.720. 

Our HTML sanitization step normalizes the all of these IMG elements to 
`<img src="http://www.ephemeron.org/~bigby/small.jpg">`.
