### ISSUE TITLE
New mail notification vibrates even though vibration is disabled

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#4081]
I disabled "Vibrate / Vibrate when mail arrives" in Account Settings > Notifications. I also set "New mail ringtone" in Account Settings > Notifications to "None", as indicated as possibly required by https://k9mail.github.io/documentation/settings/account.html and https://github.com/k9mail/k-9/issues/835 but new mail notifications still cause a vibration.

In the notification settings of Android where this normally can be disabled (I have Android 8.1) there are no options available other than disabling notifications altogether, which I don't want. (I rely on the visual notifications, I just need them to be silent)

No other app I have on this system has the same issue, so this appears to be K-9 related

### Expected behavior
no vibration on new mail notification

### Actual behavior
vibration on new mail notification

### Steps to reproduce
1. Disable vibration in Account Settings / Notifications
2. Disable new mail sound in Account Settings / Notifications
3. Keep K-9 notifications in general enabled (such that they visually pop up)
4. Set system ringtone volume to vibrate
5. Receive new e-mail

### Environment
K-9 Mail version: 5.600

Android version: 8.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

I have no Android SDK installed on this machine right now

**Comment by cketti** [comment]
Probably no longer an issue with K-9 Mail 5.800+.
