### ISSUE TITLE
Remove placeholder in database when message deletion on server is finished

### ISSUE THREAD

**Issue by basilgello** [thunderbird/thunderbird-android#4100]
The "Clear messages (Dangerous!)" option in mailbox action popup menu suggests that ALL messages are deleted (either for privacy or to recreate corrupted mail-queue). However the placeholders are not deleted - exposing potentially sensitive information about deleted conversations.

I dont know if the clear() method here is used only by "Remove messages (dangerous!)" sub-menu so I decided to open an issue rather than simply removing "deleted = 0" from here:

https://github.com/k9mail/k-9/blob/c053964fefe1c758251aeab902563f8ec7dc454c/app/core/src/main/java/com/fsck/k9/mailstore/LocalStore.java#L327

**Comment by basilgello** [comment]
The issue arises from Gmail IMAP servers glitch which can be reproduced as follows:

1. Retrieve one (or more) messages from Gerrit
2. Do not read them, but select all unread messages and delete them.
3. Clear the trash folder of Gmail mailbox
4. Clear all messages and see 132.5kB size instead of 124.4kB size AND several messages in "messages" table with deleted attribute set to 1.

**Comment by cketti** [comment]
We create a placeholder to avoid the message being downloaded again if we sync before the actual delete operation has been performed on the server. 
What we should do, is remove the placeholder after the delete operation was successful. I believe right now the placeholders will only be removed if you sync the folder they're in.

"Clear messages" is not functionality meant to be used by end-users. In future versions it'll be only available in debug builds, if at all.
