### ISSUE TITLE
Import of account containing an identity with an empty email address fails the whole account import

### ISSUE THREAD

**Issue by SimonDeltic** [thunderbird/thunderbird-android#4138]
### Expected behavior
I export my settings from one phone's K9 instance, copy the exported settings file to another phone then import them into K9 there. I expect the import to be successful.

### Actual behavior
Moving K9 from one phone to another via Export / Import settings, I found that my main email account would consistently fail to import with "Import failed. Failed to import any settings from <FILE>"

Re-exporting and importing didn't fix the problem.

### Steps to reproduce
The reason is a chain of potential issues:

1) I managed to create an identity with no settings on my exporting phone
Run up K9, go into an account and select "..." Settings -> Account Settings -> Sending Mail -> Manage Identities -> "..." -> New identity
Then, without entering any identity details, press the Android back button.
This creates an identity with all settings empty. It shows on the identity screen as:
"From: <>"
(Note that the "email address" field is marked as "Required", but the form is still saved with it empty).

2) Export settings
This exports the identity, complete with invalid empty email address:
```java
        <identity>
          <name></name>
          <email></email>
          <description></description>
          <settings>
            <value key="signature"></value>
            <value key="signatureUse">false</value>
          </settings>
        </identity>
```

3) Attempt import
The importer reads this identity, attempts to validate the email address which fails, so it throws InvalidSettingValueException which causes the whole account import to fail.
...
SettingsImporter: Setting 1ab45183-b2db-4ff5-b9da-f89a0e17f6bd.name.3=
SettingsImporter: Encountered invalid setting while importing account "ACCOUNT NAME"
SettingsImporter: com.fsck.k9.preferences.Settings$InvalidSettingValueException
SettingsImporter: 	at com.fsck.k9.preferences.SettingsImporter.importIdentities(SettingsImporter.java:526)
...

###

I realise that I shouldn't have created an identity with an empty email address but I think I did it accidentally by starting to create one, getting distracted by a notification then hitting back a few times to go see the new email.
The import fail is non-intuitive and I had to look at the debug log to work out what I'd done.

A simple fix might be to modify the export code to skip any identities with invalid email addresses.
That would ensure that the export never created a data field that couldn't be imported.

### Environment
K-9 Mail version: 5.6.00

Android version: 8.0.0 for export, 9 for import. Both Samsung phones.

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by supervisitor** [comment]
It depends not only on empty email address!

My first try was to export my settings from Motorola Android 6.01 with K-9 Mail v5.800 to Samsung Android 6.01 with K-9 Mail v5.804... is was not working, I got the error message: "Failed to read settings file".

To be sure I rename the file (could be helping), first it was: "settingsk9.k9s"... later: "settings5800.k9s" no changes. And I export from every version a new settings file!

So I update the Apps in small steps:
source | destination | result | settings file
5.800 | 5.800 | reading error | "settings5800.k9s"
5.800 | 5.801 | reading error | same from above
5.801 | 5.801 | reading error | "settings5801.k9s"
5.801 | 5.802 | reading error | same from above
5.802 | 5.802 | reading error | "settings5802.k9s"
5.802 | 5.803 | reading error | same from above
5.803 | 5.803 | reading error | "settings5803.k9s"
5.803 | 5.804 | reading error | same from above
5.804 | 5.804 | reading error | "settings5804.k9s"

- the way I transfer my settings is: K-9 => export setting => compress with Amaze => send with Blitz Mail => save it from desktop Client to disk => upload ZIP to web server => download it with Lightning Browser to device => extract it with Amaze => check file with Acode => want to import settings with K-9... get error message!

The result for today: I have to use my Moto for Mail, as long as export/import of settings is not working... I don't want to do this manually! ;o} If I can do any to support you to fix this bug... I will do my best...

**Comment by cketti** [comment]
@supervisitor: Please create a new issue and make sure to provide the information asked for in the issue template. https://github.com/k9mail/k-9/issues/new/choose

**Comment by cketti** [comment]
PR #6696 changed the app so the user can no longer create invalid identities.

I created #6955 to skip invalid identity entries in the settings file.
