### ISSUE TITLE
Cannot sync on long subject

### ISSUE THREAD

**Issue by BBR-U22** [thunderbird/thunderbird-android#4167]
### Expected behavior
K9 should sync emails from remote server

### Actual behavior
When there are messages with long subjects (please see example attached
[message.txt](https://github.com/k9mail/k-9/files/3515464/message.txt)
) it cannot sync

### Steps to reproduce
1. Get email with such subject
2. ???
3. Profit!

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type: POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: I have no android SDK :(

**Comment by cketti** [comment]
Works for me. Can you provide a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors)?
