### ISSUE TITLE
K9 not moving/copying multiple mails to SPAM folder

### ISSUE THREAD

**Issue by Cactus-World** [thunderbird/thunderbird-android#4169]
[k9-log.txt](https://github.com/k9mail/k-9/files/3529539/k9-log.txt)

Hi, 
just encountered a bug in k9:

### Expected behavior
Multiple selected messages should be moved to designated SPAM folder when using menu item 'SPAM' (holds true for copying/moving as well)
### Actual behavior
Messages are shown locally as been moved/copied, but are never synced to IMAP server (no messages there). It works though when only selecting one mail. When having multiple selected mails, the operation also leads to k9 jumping out of folder view and displaying account's overview.

### Steps to reproduce
1. Select multiple mails.
2. Use menu item "SPAM" to move them to designated spam folder (or use copy/move to send them to other folders).
3. Sync respective folders.
4. Check folders on IMAP server, they do not contain the messages.
### Environment
K-9 Mail version:
5.600
Android version:
9.0 Pie
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (Courier IMAP Server via SSL)

**Comment by Cactus-World** [comment]
Log file added.
[k9-log.txt](https://github.com/k9mail/k-9/files/3529540/k9-log.txt)

**Comment by cketti** [comment]
This should no longer be an issue in K-9 Mail 5.7xx.
