### ISSUE TITLE
IMAP: mail duplicates shown, others missing

### ISSUE THREAD

**Issue by Rayn0r** [thunderbird/thunderbird-android#4175]
I am using K9 mail to access my emails provided by courierimap via ssl.

### Expected behavior
K9 Mail should display the contents of my Inbox correctly.

### Actual behavior
K9 Mail shows some emails several times, while others are missing. 
When opening a duplicate email which is supposedly big enough, there is a chance of a button that allows to download the complete email. Once this button is pressed, the correct email is being downloaded and even the inbox list is being corrected.
If the emails are small enough, I have found no way to remedy the problem.

This is what K9 shows:
![Screenshot_20190830-075125_K-9 Mail_small](https://user-images.githubusercontent.com/4147858/63997565-281d7080-caff-11e9-8a74-8fa4ad09eb79.jpg)

This is Thunderbird's view of the same Inbox:
![Thunderbird-Screenshot](https://user-images.githubusercontent.com/4147858/63997487-f1dff100-cafe-11e9-8091-c395d2cb3455.JPG)

### Steps to reproduce
1. Use a server running courierimap via ssl
2. wait for emails to come in

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
What is 'Account settings > Fetching mail > Fetch messages up to' set to?

Can you please try to record a debug log when fetching new messages? See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Rayn0r** [comment]
I set "Fetch messages up to" to "any size (no limit)" a few weeks ago. It was no improvement over the 32kb setting I had before.

I was able to catch a duplicate entry at 6:17 am this morning. Attached is the log with all sensitive data removed and two screenshots. One shows K9, the other is taken from Thunderbird a few minutes later...
![Screenshot_20191014-064002_K-9 Mail_s2](https://user-images.githubusercontent.com/4147858/66734551-d6893500-ee63-11e9-9e15-a4fe54e11aef.png)
![Thunderbird](https://user-images.githubusercontent.com/4147858/66734558-dbe67f80-ee63-11e9-9599-e6e49c9f7948.PNG)
[k9-log1-private-data-removed.txt](https://github.com/k9mail/k-9/files/3723342/k9-log1-private-data-removed.txt)

**Comment by cketti** [comment]
From the log it looks like it's an issue with your IMAP server. K-9 Mail downloads two copies of the "Chefkoch" message from the server. Each copy has a unique UID, which means they are different messages on a protocol level.
From the timestamps it looks like the second copy should have been the "Logwatch" message. But for some reason the contents of the previous message have been transmitted. I don't know why things seem to work fine with Thunderbird.

**Comment by Rayn0r** [comment]
It seems like it really was caused by the IMAP Server. I switched to dovecot and there have not been any duplicates for over a day now.
I'd say it's safe to close the issue.

Thank you very much.
