### ISSUE TITLE
K9 is not respecting notification config

### ISSUE THREAD

**Issue by lupa18** [thunderbird/thunderbird-android#4211]
### Expected behavior
When having 2 or more accounts, you should receive notifications according time, configured in Account -> Account Settings -> Email check -> Check Frecuency

### Actual behavior
I have several accounts, most of them with frequency set to "never" and one with "each 10 minuts", but I receive notifications on all of them. 

I have configured netwotk -> background sync to " -> When ‘Auto-sync’ is checked

### Steps to reproduce
1. Configure 2 or more accounts
2. Configure notification settings as explained above

### Environment
K-9 Mail version: 5.600

Android version: 8.1.0 (LineageOS 15)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by justdave** [comment]
Do you have "push" enabled on any folders in those accounts?  If so it'll maintain an open connection to the mail server and actually get push notifications from the IMAP server as mail arrives, regardless of your check frequency setting.

**Comment by lupa18** [comment]
I never access that settings. Isn't supposed that if I set "Don't check" for the account is expected nothing arrive for whole account? Why other lower level configurations change this behaviour?

For each folder, I found a "Folder type with push" setting. What should I put there? That "class" setting is quite confusing. 

thanks!

**Comment by cketti** [comment]
See [How to configure Push?](https://forum.k9mail.app/t/how-to-configure-push/1102)
