### ISSUE TITLE
master branch crashes on start when trying to add an IMAP account

### ISSUE THREAD

**Issue by mmueller-kaffeeschluerfercom** [thunderbird/thunderbird-android#4248]
### Expected behavior
k9 should allow to create an IMAP account without crashing

### Actual behavior
After entering the details for the incoming server, the screen for outgoing server settings appears shortly, but then k9 crashes with following errors:

```
E/AndroidRuntime: FATAL EXCEPTION: MessagingController
    Process: com.fsck.k9.debug, PID: 24126
    java.lang.AssertionError: Tried to create folder 'Junk' that already exists in the database as 'Junk' (8)
        at com.fsck.k9.mailstore.LocalStore$19.doDbWork(LocalStore.java:897)
        at com.fsck.k9.mailstore.LocalStore$19.doDbWork(LocalStore.java:880)
        at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:273)
        at com.fsck.k9.mailstore.LocalStore.createFolders(LocalStore.java:880)
        at com.fsck.k9.mailstore.K9BackendStorage.createFolders(K9BackendStorage.kt:41)
        at com.fsck.k9.backend.imap.CommandRefreshFolderList.refreshFolderList(CommandRefreshFolderList.kt:25)
        at com.fsck.k9.backend.imap.ImapBackend.refreshFolderList(ImapBackend.java:112)
        at com.fsck.k9.controller.MessagingController.refreshRemoteSynchronous(MessagingController.java:454)
        at com.fsck.k9.controller.MessagingController$5.run(MessagingController.java:444)
        at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:222)
        at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
        at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:165)
        at java.lang.Thread.run(Thread.java:761)
```

### Steps to reproduce
1. Clone git repository, open the project in Android studio, Build, start debug, wait for the start screen ("welcome to K-9 Mail) to appear
2. Click on "Next", then the screen "Set up a new account" shows up
3. enter email address and Password
4. Click on "MANUAL SETUP", then "Account type" shows up
5. click on "IMAP", then "Incoming server settings" shows up
6. Enter your server details
7. Click on "NEXT", then a screen appears with "checking incoming server settings..."
8. When the outgoing server settings screen appears, the app crashes

### Environment
K-9 Mail version: 5.700-SNAPSHOT, master on 2019-11-12

Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by mmueller-kaffeeschluerfercom** [comment]
ok, I can prevent the crash when commenting out the lines LocalStore.java:889-904 (it is `if(K9.DEVELOPER_MODE)`). But then I get two "Junk" folders and two "Sent" folders in the account. Is this a known problem?

**Comment by mmueller-kaffeeschluerfercom** [comment]
maybe related to #1220 ?

**Comment by cketti** [comment]
If you test against `master` please try to create actionable issues. I can't reproduce the issue with my server. The stacktrace is only helpful to learn what happened, but not why. A debug log might help with the why.

When you open issues against `master` please include the commit hash, not the date when you pulled the branch.

**Comment by mmueller-kaffeeschluerfercom** [comment]
here is the debug log. [k9-log.txt](https://github.com/k9mail/k-9/files/3864500/k9-log.txt)

Thank you for the note about the commit hash. I didn't know, I'm quite new here... :-)

**Comment by cketti** [comment]
Looks like your server returns multiple LIST responses for some folders.

```
>>> 3 LIST "" "*"
<<<#null# [LIST, [\HasNoChildren], /, Archive]
<<<#null# [LIST, [\HasChildren], /, Conversation History]
<<<#null# [LIST, [\HasChildren], /, Trash]
<<<#null# [LIST, [\HasNoChildren], /, Trash/Trash]
<<<#null# [LIST, [\HasNoChildren], /, Deleted Messages]
<<<#null# [LIST, [\HasNoChildren], /, Drafts]
<<<#null# [LIST, [\HasNoChildren], /, INBOX]
<<<#null# [LIST, [\HasNoChildren], /, Junk]
<<<#null# [LIST, [\HasNoChildren], /, Junk]
<<<#null# [LIST, [\HasChildren], /, Unsent Messages]
<<<#null# [LIST, [\HasNoChildren], /, Unsent Messages/VoiceOutbox]
<<<#null# [LIST, [\HasNoChildren], /, Sent]
<<<#null# [LIST, [\HasNoChildren], /, Sent]
<<<#null# [LIST, [\HasNoChildren], /, Sent Messages]
<<<#null# [LIST, [\HasChildren], /, Sync Issues]
<<<#null# [LIST, [\HasNoChildren], /, Sync Issues/Conflicts]
<<<#null# [LIST, [\HasNoChildren], /, Sync Issues/Local Failures]
<<<#null# [LIST, [\HasNoChildren], /, Sync Issues/Server Failures]
<<<#null# [LIST, [\HasNoChildren], /, Trash]
<<<#null# [LIST, [\HasNoChildren], /, Working Set]
<<<#3# [OK, LIST completed]
```

I'll look into it.

**Comment by cketti** [comment]
Can you please check if my change actually fixed your issue?

**Comment by mmueller-kaffeeschluerfercom** [comment]
yes, tested, it fixed the issue! Thanks a lot!

**Comment by cketti** [comment]
Thanks for reporting and providing the debug log :+1:
