### ISSUE TITLE
Umlaut Chars garbled

### ISSUE THREAD

**Issue by marcelser** [thunderbird/thunderbird-android#4298]
The new release of K9 shows garbled Umlauts in German mails

### Expected behavior
Correct Display of latin1, utf-8 depending on charset

### Actual behavior
Charsets are not properly honored and non ascii chars are garbled 

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.700

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
Logs are not needed in this case. It's ab obvious bug

**Comment by cketti** [comment]
Can you please attach a message that isn't decoded properly.

**Comment by marcelser** [comment]
I'm very sorry to have opened this bug. It seems the message also shows garbled on other mail clients. Obviously the message itself is broken.
