### ISSUE TITLE
Download Complete Message-Connection Error

### ISSUE THREAD

**Issue by wcthorne** [thunderbird/thunderbird-android#4304]
Version 5.7, Android 10 Build QP1A.191105.003
On a POP3 SSL connection, a message with attachments displays the Download Complete Message as this email has always done (daily click report with attached CSV and PDF files that are not that large).  

New with 5.7: touching the Download Complete Message button results in  small rounded pop-up message stating "Connection Error".  Connected to both wifi and network.

Thanks for 5.7 looking great so far...
### Expected behavior
Spends a few seconds downloading and I touch the PDF to view the report.

### Actual behavior
Displays connection error pop-up

### Steps to reproduce
1. Open a moderate size email with a CSV and PDF attachment
2. Touch the Download Complete Message 

### Environment
K-9 Mail version:
5.7
Android version:
10 Build QP1A.191105.003
Account type (IMAP, POP3, WebDAV/Exchange):
POP3 SSL

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
Sorry not at PC, let me know if this defies simple repro and I can get you the trace...

**Comment by gena01** [comment]
Functionality wise this a major thing that broke for me in 5.700 release. Is there anything needed from the user side to get this sorted out?

**Comment by wcthorne** [comment]
gena01, fyi, work-around is to increase the size of your message auto-receive in settings on the account (sorry for the vague description, but just find where you set how big to retrieve...).

I know this isn't always practical for real-big stuff, but it did work for me and most of my messages are not that big anyway so it has streamlined access to my daily attachments...

**Comment by ChrisPHL** [comment]
Hey folks,

I just wan't to confirm the bug and add some line from the log while the error happens:
```
12-11 19:23:20.707  1069  1092 I MessagingController: Running command 'loadMessageRemote', seq = 10 (foreground priority)
12-11 19:23:20.711  1069  1092 E MessagingController: Error while loading remote message
12-11 19:23:20.711  1069  1092 E MessagingController: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fsck.k9.mail.store.pop3.Pop3Connection.executeSimpleCommand(java.lang.String)' on a null object reference
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.mail.store.pop3.Pop3Folder.fetchBody(Pop3Folder.java:496)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.mail.store.pop3.Pop3Folder.fetch(Pop3Folder.java:364)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.backend.pop3.CommandFetchMessage.fetchMessage(CommandFetchMessage.kt:16)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.backend.pop3.Pop3Backend.fetchMessage(Pop3Backend.kt:102)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.controller.MessagingController.loadMessageRemoteSynchronous(MessagingController.java:1328)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.controller.MessagingController.access$1000(MessagingController.java:113)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.controller.MessagingController$18.run(MessagingController.java:1293)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:220)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:113)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
12-11 19:23:20.711  1069  1092 E MessagingController: 	at java.lang.Thread.run(Thread.java:764)
12-11 19:23:20.713  1069  1092 I MessagingController:  Command 'loadMessageRemote' completed
```

Hope that helps to fix the bug soon. :-)
Feel free to contact me in case you need further information or testing.

Have a nice day!
Christian
