### ISSUE TITLE
Folder updates interfere with drawer operation

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#4333]
### Steps to reproduce
1. Open drawer
2. Expand account list
3. Close drawer
4. Refresh message list
5. Open drawer

After step 5 the drawer shows the (updated) folder list, then the account list.

**Comment by cketti** [comment]
@mikepenz: This seems to be a MaterialDrawer issue. Do you have a suggestion on how we can work around it?

**Comment by mikepenz** [comment]
Thanks for the info. I'll check it out and get back to you as soon as I can.
