### ISSUE TITLE
5.701: Double display of inbox

### ISSUE THREAD

**Issue by gunterkoenigsmann** [thunderbird/thunderbird-android#4340]
On deleting the mail I currently read I sometimes return to a inbox that is drawn twice: once unscrolled and with the deleted mail and once in its current state:
![Screenshot_K-9_Mail_20191204-073520](https://user-images.githubusercontent.com/5041537/70119066-c0307600-1669-11ea-8642-77885e2c5b5c.png)
Both inboxes appear to be drawn one over the other.

### Steps to reproduce
1. Click on an e-mail
2. Delete it
3. Sometimes the bug happens. Switching tasks on android devices seems to help trigger it sometimes.

### Environment
K-9 Mail version:

Android version: 5.791

Account type: IMAP

**Comment by gunterkoenigsmann** [comment]
I  unchecked "fixed message theme" in the settings. Now k9 no more shows this problem.

**Comment by cketti** [comment]
I doubt "fixed message theme" is related to this issue.

**Comment by cketti** [comment]
#4452 contains instructions to reproduce the issue. Closing this one.
