### ISSUE TITLE
Attempting to create new identity crashes app

### ISSUE THREAD

**Issue by scripple** [thunderbird/thunderbird-android#4359]
K-9 mail configured with single IMAP account with just the default identity.  Attempting to add a new identity crashes the app and brings up "K-9 Mail keeps stopping" dialog box.

### Expected behavior
Settings->Account->Sending Mail->Manage Identities->New identity should allow adding a new identity.

### Actual behavior
Click the New Identity button once brings you back to Sending Mail page.  Going into "Manage Identities" and clicking new identity again brings up the  "K-9 Mail keeps stopping" dialog box.

### Steps to reproduce
See above

### Environment
K-9 Mail version: 5.701

Android version:  10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Tobias-B-Besemer** [comment]
I guess I have the same issue...

I added a second account (IMAP) to K-9 and now, if I try to switch to this account, K-9 crash.

I tried to create a debug log, aLogcat shows me nothing - IDK what I'm doing wrong! But maybe because I haven't rooted this device, yet... (???)

**Comment by cketti** [comment]
@Tobias-B-Besemer: Your issue doesn't sound the same at all. Please create a new issue and provide a debug log (the issue template contains instructions on how to do that).

**Comment by Tobias-B-Besemer** [comment]
@cketti, as I wrote:
> I tried to create a debug log, aLogcat shows me nothing - IDK what I'm doing wrong! But maybe because I haven't rooted this device, yet... (???)

And I used aLogcat because I have read the K-9 doc about make a debug log... ;)

**Comment by cketti** [comment]
> And I used aLogcat because I have read the K-9 doc about make a debug log... ;)

I suggest you read it again. The document doesn't mention aLogCat anymore because the last Android version that supports reading the log without root is 4.0.

**Comment by Tobias-B-Besemer** [comment]
> > And I used aLogcat because I have read the K-9 doc about make a debug log... ;)
> 
> I suggest you read it again. The document doesn't mention aLogCat anymore because the last Android version that supports reading the log without root is 4.0.

I read this doc:
https://k9mail.github.io/documentation/debugging.html
And installed this version of aLogCat that _only_works_with_Android_above_4.1_:
https://play.google.com/store/apps/details?id=rs.pedjaapps.alogcatroot.app

But my mistake seems to be, that I understood the doc wrong!
I thought that I have to use ADB _or_ aLogCat, but using ADB seems to be step 1...

Will try to use ADB, soon...

**Comment by Tobias-B-Besemer** [comment]
Does the K-9 Project have nightly builds to e.g. test if this fix fixes my issue, too?
