### ISSUE TITLE
5.701: Long subjects are truncated

### ISSUE THREAD

**Issue by timonegk** [thunderbird/thunderbird-android#4360]
### Expected behavior
When receiving a mail with a long subject, it should be possible to view the full subject, either immediately or by clicking on the subject. 

### Actual behavior
The subject is truncated after two lines. 

### Steps to reproduce
1. Receive a mail with a long subject
2. Open it

### Environment
K-9 Mail version: 5.701

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ZJaume** [comment]
Please, fix it.
