### ISSUE TITLE
Switching apps doesn't keep read position anymore

### ISSUE THREAD

**Issue by Bubu** [thunderbird/thunderbird-android#4393]
Since version 5.700 k9 always jumps to the top of the opened email when switching to another app and back to k9. This was previously only happening when the activity was killed and restarted. Now it's always happening.

**Comment by cketti** [comment]
This seems to be different than the issue fixed with #4390.

**Comment by Bubu** [comment]
This annoyingly also happens when the screen turns off while reading a long email.
