### ISSUE TITLE
Localized strings fail

### ISSUE THREAD

**Issue by iriman** [thunderbird/thunderbird-android#4407]
Persian translation is fully done via transifex and it works properly while device language is set to Persian. But when device language is set to English and app language is set to Persian, some strings still are English.

### Expected behavior
Regardless of device language, all strings be in Persian (selected via app setting)

### Actual behavior
Some strings are English and some Persian.

### Steps to reproduce
1. Set device language to English.
2. Set app language to Persian.
3. Exit app.
4. Open app.
5. Some strings are english. For example:
5.1. "load up to 10 more" at bottom of screen
5.2. "inbox" and "outbox" in left menu
5.3. try to compose a new mail, then title "Compose" is in English. Also tap 3 dots menu, all items under it are English.
5.4. tap back to leave compose. Then tap pencil icon to open "compose" again.  It's now in Persian.
5.5. Go to settings. Choose an account setting. Go to Fetch mail. Then go to incoming server setting. Title of dialog is English.

### Environment
K-9 Mail version: 5.703

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Please take some time to retrieve logs and attach them here.

For steps 5.3 - 5.4:

[K9log.txt](https://github.com/k9mail/k-9/files/4002776/K9log.txt)

**Comment by sedrubal** [comment]
For me I switched the **system** to **Spanish** and **k-9** (Version 5.717) to **English** (which should not make a difference) and can reproduce some of the issues except 5.2, 5.3 and 5.4. Additionally I found more issues:

- 5.6: when you reply to a mail, the introduction (`On <date> <sender> wrote:`) is in the language configured in the system and not in the language configured in k-9
- 5.7: when you forward a mail, the mail header (`From:`, `To:`, ...) is in the language configured in the system and not in the language configured in k-9

**Comment by poldi171254** [comment]
My system language is set to english and k-9 language is german and everything seems to be working as expected on 5.732-SNAPHOT.

**Comment by cketti** [comment]
Activity titles are cached and not updated when we manually change the configuration. See https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758

The easiest way to work around this is to set all activity titles programmatically. Activities that use the navigation component already do this. Also `MessageList` and `MessageCompose`.
