### ISSUE TITLE
Many crashes

### ISSUE THREAD

**Issue by Sakitatu** [thunderbird/thunderbird-android#4423]
Since some months the app doesn't work at all. It crashes, with the message "the app unexpectedly closed".
### Environment
K-9 Mail version: 5.205

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by realmain** [comment]
You need to provide logs

**Comment by realmain** [comment]
You're using K-9 v5.205 which is from 2017...

Please use v5.700, or if you want to try out the new UI, use v5.703.

**Comment by cketti** [comment]
If "5.205" was a typo and you're using a recent version of the app please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
