### ISSUE TITLE
Do not save unmodified new message as draft

### ISSUE THREAD

**Issue by toreanderson** [thunderbird/thunderbird-android#4435]
### Expected behavior

After having pressing the compose new message button, the compose view opens. If you close/background the app at this point, without changing/inputting anything at all, K-9 should not have saved the message as a draft.

### Actual behavior
The empty new message is saved as a draft.

### Steps to reproduce
1. From the accounts view, press the compose new message button near the bottom centre of the screen (envelope icon with a little plus sign).
2. Background the app and wait for Android to terminate it, or close it from app selection screen.
3. Check drafts folder. An empty draft has been stored (i.e., no subject, no text, no recipients).

### Environment
K-9 Mail version: 5.600

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

I do not believe attaching error logs is necessary in this case since this is not an application error per se, more of a UI issue.

The reason why the current behaviour is an annoyance is that the compose new button is placed so that it is easy to press it when what you want to do is to change to another app. This is because the Android 10 gesture for switching between apps is to swipe up from the bottom of the screen, and the compose new button is placed at the centre near the bottom. Thus I seem to end up accidentally entering the new message view quite frequently. If I then re-try the swipe gesture successfully immediately after, i.e., when the new message view has opened, I end up with an empty draft being saved. Because of this my drafts folder is accumulating a number of these empty drafts over time.

To me it does not seem to be any value in saving empty/unmodified drafts, so the solution is simple: just don't.

**Comment by cketti** [comment]
Unmodified drafts are discarded by default. However, it seems that setting 'Bcc all messages to' on an identity automatically marks the message as modified.

**Comment by toreanderson** [comment]
I can confirm I'm using the «Bcc all messages to» feature. Nice catch.
