### ISSUE TITLE
Contact pictures not shown

### ISSUE THREAD

**Issue by sedrubal** [thunderbird/thunderbird-android#4472]
### Expected behavior
If a mail comes in from a contact with a picture in address book and the option "show contact picture" is set, the **picture from the address book should be displayed**.

### Actual behavior
Only a generic first-letter-of-name picture is displayed in the mail. If you click on it, the correct contact in contact app will be opened. **k9 has the contact permission**. I suppose the **contact is correctly linked** to the address, **but the picture wont show up**.

### Steps to reproduce
1. Add a contact to the address book with mail and picture
2. Receive a mail from that contact
3. Open the message list

### Environment
K-9 Mail version: 5.703

Android version: 9 (lineageos 16)

Account type: IMAP

*There was no usable information in the debug log.*

**Comment by cketti** [comment]
@sedrubal: Can you please check if PR #4474 fixes the issue for you.

**Comment by sedrubal** [comment]
Thanks @cketti. Yes this fixes the issue :+1:
