### ISSUE TITLE
Notification and message loading errors related to old messages

### ISSUE THREAD

**Issue by JumpOverWires** [thunderbird/thunderbird-android#4481]
### Expected behavior
When there's a notification for messages, K9 should show the specific message when I call up the notification link.

### Actual behavior
Calling up the notification link sometimes results in an empty K9-Window with the hint "Message loading error". It seems that this only happens with older messages, which I can't find when I search in K9-App, but they are still shown in Thunderbird on my Laptop.

### Steps to reproduce
1. Pull down the status bar to show notification list on my phone.
2. Clicking on notification link(s) to open the K9-Mail-Client.
3. Some messages (especially older ones) are not displayed, instead an empty window appears with the note "Message loading error".

### Environment
K-9 Mail version: 5.600 (German language)

Android version: 10 (crDroid 6.2)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

[k9-log.txt](https://github.com/k9mail/k-9/files/4117619/k9-log.txt)

**Comment by meneken17** [comment]
The error occures also when the message is moved into a different folder (e.g. by a filter in the desktop mail program)

**Comment by cketti** [comment]
Notifications should have been removed when the message is no longer available locally. Implementing #5566 should fix this.
