### ISSUE TITLE
youtube loads in the message window

### ISSUE THREAD

**Issue by J4CKED** [thunderbird/thunderbird-android#4498]
### Expected behavior
When opening a message from a subscribed youtube channel and after pressing the video thumbnail or link, a popup should appear asking you which application to use to open the video link.

### Actual behavior
The video loads in the message window.

### Steps to reproduce
1. Open the message with the youtube link
2. Click on the thumbnail or video link

### Environment
K-9 Mail version: 5.704

Android version: 5.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Can you please check if 5.705 fixes this issue for you?

**Comment by FliegendeWurst** [comment]
Version 5.705 did not fix the issue for me.
