### ISSUE TITLE
Widgets always launch to default account inbox

### ISSUE THREAD

**Issue by patricktokeeffe** [thunderbird/thunderbird-android#4502]
### Expected behavior

When users create a widget (aka desktop shortcut or launcher), they select which account the widget is associated with. Pressing that widget opens the corresponding account inbox (or default folder). Multiple widgets can be created, each associated with a different account. 

### Actual behavior

Upon creation, widgets work as expected. However, after an indeterminate length of time, all widgets will open the default account inbox (instead of their previously associated accounts). 

### Steps to reproduce

1. Update to new Material UI version, if using old interface
2. Create multiple widgets 
3. Place widgets in same folder (<-- possibly optional step)
4. Wait several days 

### Environment

K-9 Mail version: 5.704 from Google Play Store 

Android version: 8.0.0 

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

> *sorry not available atm*

**Comment by cketti** [comment]
1. What do you mean by widget? "K-9 Accounts" or "K-9 Unread"?
2. Did you create the widget/launcher shortcut using K-9 Mail 5.704 or an earlier version?
3. What launcher are you using?
