### ISSUE TITLE
Mails not deleted from server bluewin.ch

### ISSUE THREAD

**Issue by Maetts** [thunderbird/thunderbird-android#4512]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Mail should be deleted from server when deleted in app on @bluewin.ch account

### Actual behavior
Mail not deleted on server when deleted in app on @bluewin.ch account

### Steps to reproduce
1. Setup mail account via imap/ smtp in k9
2. Receive mail
3. Delete mail
4. Check availability of the mail on the server

### Environment
K-9 Mail version: 5.705 (sice 5.704, before it worked) 

Android version: Android 10

Account type (IMAP, POP3, WebDAV/Exchange):

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Maetts** [comment]
Any chance providing logs without a computer and directly from the phone?

Freundliche Grüsse
Benjamin Mathys


-------- Original Message --------

**Comment by Maetts** [comment]
Any chance providing logs without a computer and directly from the phone?

**Comment by cketti** [comment]
Not at the moment. Without the log we can't really fix the underlying bug. But chances are you'll be able to make things work by removing the account and adding it again. You can use the import/export functionality to make this relatively painless.

**Comment by Maetts** [comment]
Awesome, thanks a lot, issue resolved:) is it somehow possible to set the unified inbox at app startup as default?

**Comment by Maetts** [comment]
It was gone after new installation of the app - now it's here again.

**Comment by Maetts** [comment]
After another deinstall and re setup it seems to work now. Thank you.
