### ISSUE TITLE
folder setting "show in top group" has no effect

### ISSUE THREAD

**Issue by flxbt** [thunderbird/thunderbird-android#4538]
As I am at it, I'd like to report a minor bug:

#### Expected behavior
Under "manage folders", when checking the "show in top group" option for one or more folders, I'd expect them to appear at the top of the menu / folder list.

#### Actual behavior
Folder setting "show in top group" has no effect at all.

#### Environment
K-9 Mail version: 5.703 (F-Droid)
Android version: 7.1.2 (/e/OS)
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
It should. The order is: Inbox, Outbox, special folders, top group, regular folders. Can you please check again to confirm the app is not sorting folders like this for you?

**Comment by flxbt** [comment]
I apologize: You are right. I have been expecting a different behavior (i.e. the marked folders being listed way further towards the top of the list) - this went so far, that I didn't even notice the most bottom folder moving up one position. I guess, that if it was easy to implement a "free" folder sort order, you'd already have done this. Once again sorry for the noise and thanks for this great piece of software!
