### ISSUE TITLE
IMAP Problem 

### ISSUE THREAD

**Issue by Bang1970** [thunderbird/thunderbird-android#4599]
### Expected behavior
Pull E-Mail from my Servers via IMAP

### Actual behavior
Does not work at all with 5.707. With 5.705 it seemed to work. Unfortunately I can not install 5.705 anymore.

### Steps to reproduce
Don't know - after updating I could not get my Mails

### Environment
K-9 Mail version: 5.707

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by ArslanAKhan** [comment]
Here is one. I have the same problem with the latest version. IMAP idle doesnt seem to work.

[logcat_03-20-2020_09-38-01.txt](https://github.com/k9mail/k-9/files/4358801/logcat_03-20-2020_09-38-01.txt)

**Comment by cketti** [comment]
@ArslanAKhan: Push has been temporarily disabled in 5.7xx; see #4253 and #4258. Your log does not contain any useful information, presumably because you forgot to enable debug logging inside the app.

**Comment by karpfenhai** [comment]
Hey there, by any chance, will imap push be re-enabled anytime soon?

It's just not working and the setting for idle just doesn't exist anymore, I'm willing to assist by testing if required.

Regards.
