### ISSUE TITLE
Grouped folders

### ISSUE THREAD

**Issue by galantra** [thunderbird/thunderbird-android#4603]
### Expected behavior
There should be groups for all folder categories – i.e., archive, trash, drafts, inbox. Like with the Thunderbird add-on Group Folders

### Actual behavior
There is a common view only for the inboxes.

### Environment
K-9 Mail version: 5.705

Account type: IMAP

PS: I like the latest redesign A LOT

**Comment by ivnmad** [comment]
Add more unified folders https://github.com/thunderbird/thunderbird-android/issues/6596

**Comment by cketti** [comment]
We'll be using #6596 to track this feature request.

Duplicate of #6596
