### ISSUE TITLE
IMAP: Handle error response when uploading a message

### ISSUE THREAD

**Issue by davidhedlund** [thunderbird/thunderbird-android#4622]
# Expected behavior

When a message is sent, it is copied to the Send directory locally and on the server. If a sync is issued on that folder, then the local Sent will reflect the changes of the server, including any recently sent messages.

# Actual behavior

The messages are copied to the local Sent directory but not the Sent directory on the IMAP account.

Steps to reproduce

* Send a message from K-9.
* Check the Sent directory in another email client.

# Environment

K-9 Mail version: 
Android version: 9
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by daniell1** [comment]
I've attached two logs. One with K-9 Mail 5.708 on Android 9 where the problem persists. One log with K-9 Mail version 5.705 on Android 7.1.2 where the problem does not occur. I've used the same account on both devices. Imho it is a very severe issue as one is not possible to export sent emails and lose them forever if the account is removed/added again etc.

[k9-log_5.705_Android 7.1.2.txt](https://github.com/k9mail/k-9/files/4499052/k9-log_5.705_Android.7.1.2.txt)
[k9-log_5.708_Android 9.txt](https://github.com/k9mail/k-9/files/4499053/k9-log_5.708_Android.9.txt)

**Comment by davidhedlund** [comment]
@daniell1 Thank you extremely much!

**Comment by cketti** [comment]
@daniel1: The server returned the error response: `NO [TOOBIG] Message is too big (0.000 + 0.000 secs).` (it was almost 70 MB large).

**Comment by daniell1** [comment]
@cketti : No, definitely not. I've sent the message to the inbox of the same account. The message's size is only a few kB. I only wrote Test into the Subject and my signature was automatically added to the body. Nothing else in the email, so I expect a bug in K-9 Mail.
BTW: I have another IMAP account on the phone which does not have the problem. And after I've read mails from the problematic account they are not marked as unread on the server and vice versa.

**Comment by daniell1** [comment]
I've just sent a new completely emtpy email (without subject and signature in body) and it's the same.

**Comment by cketti** [comment]
Can you please record a debug log while sending an almost empty message?

**Comment by cketti** [comment]
Oh, nevermind. The upload that failed is to the Trash folder.

```
04-19 14:15:17.858 26886 26903 V ImapConnection: conn6647058>>> 63 APPEND "INBOX.Trash" (\Seen) {69211209}
04-19 14:15:17.943 26886 26903 V ImapConnection: conn6647058<<<#63# [NO, [TOOBIG], Message is too big (0.000 + 0.000 secs).]
```

**Comment by daniell1** [comment]
You just made my day (or night... :D). I checked the trash on the mobile. I don't use the trash and it was empty on the server. However not on the mobile. Seems like there was something stuck. I deleted everything on the mobile and voila: all pending messages have been synced! Also marking them read/unread works again! @davidhedlund maybe the same for you? Is something stuck anywhere?
