### ISSUE TITLE
K9 crashes on every start, and crashes SystemUI with notification

### ISSUE THREAD

**Issue by Asperamanca** [thunderbird/thunderbird-android#4639]
Possibly the same as #4592, but that issue was closed without resolution.

### Expected behavior
K9 Mail starts

### Actual behavior
K9 Mail crashes on every start, even after rebooting

### Steps to reproduce
I am not sure how to reproduce at this point. But I will write all I know below, and maybe you can give me leads to follow on in order to pinpoint the issue

### Environment
K-9 Mail version: 5.6 (F-droid "Suggested") but also after upgrade to 5.707

Android version:
8.0.0 (ShiftOS with February 2020 update)

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

What I did:
1) Installed K9 fresh on a new phone from F-droid (that was 5.6)
2) Imported a backup from a previous phone
3) Provided account password and could receive email
4) Could open and use K9 mail multiple times
5) Put phone to airplane mode for the night
6) Disabled airplane mode in the morning
7) Received an email notification but dismissed it
8) Later tried to open K9 via shortcut in order to read email
9) Crash, also on retry
10) Rebooted phone
11) K9 keeps crashing
12) Updated to 5.707 (newest on F-droid)
13) K9 keeps crashing

Question: I can't find any data folder (searching for "K9" in storage, could not find info in FAQ), because I suspect that K9 hiccups on something in the data files, and I would like to rule that out. Obviously, I cannot enable debug logs.

**Comment by Asperamanca** [comment]
I have since tried a few more things:
1) Uninstalled and reinstalled K9 Mail. Imported the same account settings.
2) Retrieved the same emails. K9 crashed again.
3) Now the mail notification triggered a crash of the System UI
4) The crash would re-trigger, faster than I could dismiss the notification, until the Android system rebooted
5) In the recovery menu ("Try again" or "Factory reset") I choose try again
6) I switched to Airplane mode on startup, and could uninstall K9

It seems that a certain email message triggers a crash in a module that is used both in K9 (for displaying the message title and summary) and in the notification. Since the other issue was reported by another Shiftphone user, I suspect a somewhat strange signature of the Shiftphone support.

The only solution I could find on short notice was to install a different email client.

**Comment by Asperamanca** [comment]
I used the same account settings on a different Android 8.0 device (Samsung Galaxy Tab A) with the same emails without any crash. So there does seem to be something system-related.

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

Note that the instructions contain this sentence:
> If K-9 is crashing or you otherwise can't get to the settings screen, don't worry about about enabling debug logs.

**Comment by Asperamanca** [comment]
So it is crashing...what exactly do you expect me to do, and how?

**Comment by cketti** [comment]
Use `adb logcat` to record a debug log.
