### ISSUE TITLE
Number format exception for input string "Message"

### ISSUE THREAD

**Issue by djreiswig** [thunderbird/thunderbird-android#4642]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Mail should get sent

### Actual behavior
Error appears and mail goes back to drafts folder

### Steps to reproduce
1. Send a mail with several jpg attachments
2.
3.

### Environment
K-9 Mail version: Latest

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:. No PC available to retrieve the logs.  I did create them, though.

**Comment by djreiswig** [comment]
Version 5.600
How can I get the log without a PC?

**Comment by cketti** [comment]
> How can I get the log without a PC?

That's currently not supported. However, if you have root on your device you might be able to use one of the Android apps available. The search term to use for that is "logcat".

**Comment by djreiswig** [comment]
Guess I'll just figure out something else.
