### ISSUE TITLE
No background sync with Auto sync from V5.709 on

### ISSUE THREAD

**Issue by Maetts** [thunderbird/thunderbird-android#4705]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
App should automatically pull mails when auto sync is turned on

### Actual behavior
Mails are only snyced when app is opened, Issue was not there before V5.709 (5.708 works with same settings)

### Steps to reproduce
1. Set up account
2. Network settings to "only when autosync"
3. Wait

### Environment
K-9 Mail version: From 5.709 on

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by jensplixplox** [comment]
The same issue exists on my smartphone with Android 9.0 Pie with K9 Mail in version 5.600 (downloaded today from F-Droid). 

It is noticeable that in the list of apps which are granted the right to automatically synchronize accounts via the general Settings app, K9 Mail is not listed in this list in my smartphone.

**Comment by cketti** [comment]
Did you configure your accounts to periodically sync? Account settings > Fetching mail > Folder poll frequency?

**Comment by jensplixplox** [comment]
> Did you configure your accounts to periodically sync? Account settings > Fetching mail > Folder poll frequency?

Yes, this option in K9 Mail is set to "Every 5 minutes".

**Comment by cketti** [comment]
This was more a question for @Maetts. K-9 Mail 5.600 doesn't work too well with the energy saving mechanisms of modern Android versions. I doubt that the autosync setting makes a difference there.

A lot has changed in 5.7xx, though. So the autosync setting might have been broken accidentally. But looking through the code I can't find an obvious bug.

**Comment by Maetts** [comment]
Hi guys, sorry still working..

Yes, two accounts should fetch every hour, three only every 24 hours. I remember that I had also some Issues with a previous version (5.7xx), but not which exactly it was. With 5.708 it works as it should without any problem, even energy saving of Huawei is not a problem (which means something). I use Automate for periodically managing autosync and other settings on my phone.

The issue rised clearly with 5.709, why I tried also 5.710 but that was not successful why I went back to (for me stable) version 5.708.

**Comment by jensplixplox** [comment]
> This was more a question for @Maetts. K-9 Mail 5.600 doesn't work too well with the energy saving mechanisms of modern Android versions. I doubt that the autosync setting makes a difference there.
> 
> A lot has changed in 5.7xx, though. So the autosync setting might have been broken accidentally. But looking through the code I can't find an obvious bug.

It would like to ask you an off topic question, cketti: 

Today I downloaded and installed for the first time K9 Mail from F-DRUID. Version 5.600 got installed. 

I would like to use version Version 5.709 (27009), as currently specified at https://f-droid.org/de/packages/com.fsck.k9/ , but I do not know how to upgrade from version 5.600 to 5.709 using the F-DROID app. 

The F-DROID app does not offer me any K9 Mail app anymore for installation, because K9 Mail is already installed on my smartphone in version 5,600.

How can I upgrade to or install version 5.709 using the F-DROID-App?

**Comment by Maetts** [comment]
You can do it easy via https://github.com/k9mail/k-9/releases instead of F-Droid

**Comment by jensplixplox** [comment]
> You can do it easy via https://github.com/k9mail/k-9/releases instead of F-Droid

Thanks, Maetts. I will install the latest version from there, although I fear that if this version from this source is installed, I will not get any notifications about newer releases. Please note that I am owning my first smartphone since 7 days.

**Comment by Maetts** [comment]
Never mind, there will be a final/ official release, 5.70xx are still in dev mode and therefore only pre-releases. You can either check the page frequently or use google play store, there will be the official releases too. enjoy the "new" smart world then :)

**Comment by cketti** [comment]
This is not a discussion forum. It's an issue tracker that notifies everyone who is "watching" the repository about every comment. Currently that's 349 people.
Please keep the comments on this issue strictly to the bug originally reported.

Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests or discussions.

**Comment by jensplixplox** [comment]
Thanks for the information, Maetts. I do not want to use Google Play Store ;-) I will now install the apk file of version 5.710.

**Comment by cketti** [comment]
@Maetts: I can't reproduce the issue. "When 'Auto-sync' is checked" is the default value for the 'background sync' setting. So I'd expect a lot more reports if there was a general problem with it. I suspect it's something about your particular setup. Does it work as expected if you set 'background sync' to "always"?

**Comment by Maetts** [comment]
Sorry for spamming, just replied to the questions. Just tried again with 5.710, it doesn't help. The app pulls only when I open it. This is a different behavior then with 5.708.
When "always" is checked there is another issue (#4704).

**Comment by Maetts** [comment]
@cketti is there anything new or is there no further action on this?

**Comment by Maetts** [comment]
All new installed, everything set up new with exact same settings (approx the 10th time) and now it seems to work since yeserday 7pm with v 5.710

**Comment by Maetts** [comment]
Bad news. After some successful syncs, it does not work again. No changes in settings.

**Comment by Maetts** [comment]
Testing 5.713, first 12h it seems to be fixed. Will reopen if the issue is still here.

**Comment by Maetts** [comment]
Hi again. Now I see clearly a different behavior:
If network settings to "always": background sync works. 
If network settings to "only when autosync is active": background sync does not or only partially works. 

Tested with the latest beta on android 10.

**Comment by cketti** [comment]
I'm guessing it's some automatic energy saving measure of your Android version that disables "auto-sync". If things work with 'background sync' set to 'always', please configure K-9 Mail that way.
