### ISSUE TITLE
when replying to a message, original message is not quoted

### ISSUE THREAD

**Issue by eleith** [thunderbird/thunderbird-android#4742]
### Expected behavior

upon selecting "reply" or "reply all", i expect the original email to be quoted in the compose message interface.

(this was also the previous behavior before i updated to 5.711)

### Actual behavior

the compose message interface is empty and looks like crafting a new message.

### Steps to reproduce

1. receive an email
2. reply to that email

### Environment
K-9 Mail version: 5.711

Android version: 10

Account type: imap

**Comment by cketti** [comment]
Thanks for reporting. This is a bug, caused by what was included in the change log as "lots of internal changes" :)

**Comment by cketti** [comment]
Fixed in 5.713. Available here: https://github.com/k9mail/k-9/releases/tag/5.713

**Comment by eleith** [comment]
confirmed. it is fixed. awesome, appreciate the quick reaction.
