### ISSUE TITLE
5.713 crashes when switching to an Office365 account

### ISSUE THREAD

**Issue by Sredni-12** [thunderbird/thunderbird-android#4766]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior

Selecting an Office365 Outlook account opens normally.

### Actual behavior
After upgrading to 5.713 from 5.706, K9 would crash when I tried switching from the pop mail account I had open before upgrading to the Office365 Outlook account. Additionally, turning on the Unified folder wouldn't show messages from the Outlook account.

I accidentally found a fix when checking the Outlook server name in the receiving mail settings, preparatory to trying a different mail client. Without changing or editing anything, hitting next started the check server settings script, which seemed to work, and now I can use the Outlook account normally. Perhaps force a refresh when booting the upgrade for the first time?

### Steps to reproduce
1. Have a pre-existing Outlook Office365 account set up in K9 <5.713, as well as a pop account.
2. Prior to upgrading, be in the pop account.
3. Upgrade to 5.713 (I used F-Droid).
4. Open K9 and try to switch to the Outlook account.

### Environment
K-9 Mail version: 5.713

Android version: 6.0.1 on a One Plus E1003 running OxygenOS 3.1.4

Account type (IMAP, POP3, WebDAV/Exchange): WebDAV/Exchange

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
I wasn't able to reproduce this. 

Do you remember which version of K-9 Mail you originally installed? 5.600? Or did you start with a 5.7xx beta version and upgraded that to 5.706 and finally to 5.713?

**Comment by Sredni-12** [comment]
I started on this phone with 5.600 in April of last year, upgraded through the 5.7xx series as they were released on F-droid up to 5.706 (possibly 5.707, looking at release dates), then stopped checking for a few months until I made the jump to 5.713.

**Comment by cketti** [comment]
The log seems incomplete and doesn't contain any information about a crash. Please open a new issue if you're still running into this with the latest beta version. Make sure to include a debug log that captures the crash.
