### ISSUE TITLE
Crash when attachment file is changed while TC document picker dialog is open

### ISSUE THREAD

**Issue by Heineken** [thunderbird/thunderbird-android#4790]
### Expected behavior
error message "File not found"
or
Folder rescan when switching back to file picker (TC issue)

### Actual behavior
short glimpse of mail editor with attached file, then app crash

### Steps to reproduce
1. Compose mail
2. open file attachment dialog
3. select "Total Commander"
5. navigate to folder X
6. Switch to some file browser and rename file Y in folder X
7. Switch back to K-9, select file Y (under old filename), attach

- with "TotalCmd (file://url)" - nothing is attached
- same with Picasa 
- stock album or "Simple Gallery" manage to attach the image anyway, but under a generic number

### Environment
K-9 Mail version:
5.6
Android version:
7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
[k9-log.txt](https://github.com/k9mail/k-9/files/4688569/k9-log.txt)

**Comment by cketti** [comment]
Thanks for the bug report. PR #4795 will fix the crash. Part of what was reported might be covered by #4399.
