### ISSUE TITLE
Crash when adding hotmail.com account

### ISSUE THREAD

**Issue by totolanister** [thunderbird/thunderbird-android#4798]
### Expected behavior
No crash

### Actual behavior
The app crash during configuration
No bug on 5.6

### Steps to reproduce
1. Add an account hotmail.com
2. Crash

### Environment
K-9 Mail version: 5.715 debug

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

[k9-log.txt](https://github.com/k9mail/k-9/files/4702203/k9-log.txt)

**Comment by cketti** [comment]
Thanks for the bug report!
