### ISSUE TITLE
List of folders in the drawer doesn't show all

### ISSUE THREAD

**Issue by mruwek** [thunderbird/thunderbird-android#4804]
### Expected behavior
List of folders in "manage folders" and the one in the drawer should be the same.

### Actual behavior
List in the drawer is shorter - it doesn't show 1 or 2 last elements when list needs scrolling. Everything is fine if list is short enough to render it without scrolling. Bug was introduced in 5.715. I've checked again 5.714 and it clearly wasn't there.

### Steps to reproduce
1. Install 5.715
2. Set so much visible folders to enable scrolling in the drawer

### Screenshots
1. Manage folders: 
![Screenshot_20200531-095801~2](https://user-images.githubusercontent.com/500710/83347467-88a73b80-a325-11ea-8fac-f1592da0b66d.png)
2. List of folders in the drawer: 
![Screenshot_20200531-095752](https://user-images.githubusercontent.com/500710/83347475-96f55780-a325-11ea-8590-d32fa9c0dfe8.png)

### Environment
K-9 Mail version: 5.715
Android version: 10
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Hustensirup** [comment]
I can confirm that the bug was introduced with 5.715. I'm unable to scroll or otherwise select the folders if the screen size needs scrolling to show it...
