### ISSUE TITLE
Inbox - Mark all as read menu option doesn't work 

### ISSUE THREAD

**Issue by albansuser** [thunderbird/thunderbird-android#4811]
### Expected behavior
All messages in Inbox marked as read

### Actual behavior
Nothing

### Steps to reproduce
1. Within Inbox screen click on three dot menu, top right
2.Select "Mark all as read"

### Environment
K-9 Mail version: 5.715

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): POP3

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Works for me. Are you expecting messages to be marked as read on the server? This is not something that is supported by the POP3 protocol.

If messages are not marked as read in K-9 Mail, please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by albansuser** [comment]
Thanks for your response.

No, not expecting anything on the server to be changed. This function worked in the past (v5.6?)

**Comment by cketti** [comment]
Can you please check if this is still an issue with 5.717?

**Comment by albansuser** [comment]
The mark all as read works as intended in version 5.717

Thank you.
