### ISSUE TITLE
no new messages in shared inbox

### ISSUE THREAD

**Issue by mokkin** [thunderbird/thunderbird-android#4813]
### Expected behavior
Retrieval of all accounts in shared inbox.

### Actual behavior
No mails are coming, just the spinner is spinning endlessly. If I retrieve messages separately per account it works as expected.

### Steps to reproduce
1. Swipe down to pull messages from different accounts in shared inbox view.
2. No messages appear.

### Environment
K-9 Mail version: 5.715

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): 3x IMAP

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
