### ISSUE TITLE
Mutiple edits to draft isn't syncronised to IMAP (gmail)

### ISSUE THREAD

**Issue by mikini** [thunderbird/thunderbird-android#4871]
### Expected behavior
Performing multiple editing sessions on a draft message in K9 should synchronise all changes to IMAP, allowing to start a message in K9 while on mobile to continue and finish it using an IMAP desktop client.

### Actual behavior
The first draft saved from K9 is synchronised to IMAP, subsequent changes done using and present in K9 draft folder are not synchronised, the draft on IMAP remains the first saved.

Nothing I have attempted can trigger a message synchronisation, I have had IMAP drafts sitting stale for weeks; forcing K9 synchronisation, restarting K9, rebooting phone, resynchronising IMAP client. The remedy I resort to is either sending the mail to myself, or creating a new draft with copy-pasted contents.

This used to work but I have experienced this consistently since a recent K9 update (I remember upgrading from a release dated Nov 2019).

### Steps to reproduce
1. First edit; Write new mail with some contents (body="Body", subject="Subject"), see screenshot 1
2. Save as draft (back->Save as draft or menu->Save as draft), see screenshot 2
3. Second edit; Reopen draft message, write some more text ("Additional body"), see screenshot 3
4. Save as draft (back->Save as draft or menu->Save as draft), see screenshot 4
5. Observe that only the first edit of the message is present in IMAP folder (fx. Thunderbird IMAP client or gmail.com web interface), see screenshots 5 & 6

### Environment
* **K-9 Mail version**: 5.717, see screenshot 7
* **Android version**: 7.0, see screenshot 8
* **Account type (IMAP, POP3, WebDAV/Exchange)**: IMAP (gmail)
* **Phone model**: Samsung Galaxy S8, SM-G950F

### Screenshots
Done using Danish (dansk) locale.
Quick parlour;
* skrive = write
* fra = from
* til = to
* kladder = drafts

#### 1 - first edit
![Screenshot_20200708-200114](https://user-images.githubusercontent.com/1330166/86956594-a0aa8000-c159-11ea-8f6a-270b0aa13988.png)

#### 1 - saved first edit
![Screenshot_20200708-200128](https://user-images.githubusercontent.com/1330166/86956632-ae600580-c159-11ea-9743-ffa1133f6695.png)

#### 3 - second edit
![Screenshot_20200708-200231](https://user-images.githubusercontent.com/1330166/86956941-3ba35a00-c15a-11ea-9b51-b2130151ac68.png)

#### 4 - saved second edit
![Screenshot_20200708-200239](https://user-images.githubusercontent.com/1330166/86957555-2c70dc00-c15b-11ea-8344-d091902b1465.png)

#### 5 - IMAP Thunderbird
![Screenshot from 2020-07-08 20-04-57](https://user-images.githubusercontent.com/1330166/86957071-74dbca00-c15a-11ea-8f38-5e7ec19478a9.png)

#### 6 - IMAP gmail web interface
![Screenshot from 2020-07-08 20-03-39](https://user-images.githubusercontent.com/1330166/86957217-ac4a7680-c15a-11ea-836c-1d7feb34ffaf.png)

#### 7 - K9 version
![Screenshot_20200708-184339](https://user-images.githubusercontent.com/1330166/86952882-ec5a2b00-c153-11ea-95a2-f54a7c64c76d.png)

#### 8 - Android version
![Screenshot_20200708-191629](https://user-images.githubusercontent.com/1330166/86952893-f2e8a280-c153-11ea-98b0-f2bbffe9ce81.jpg)

### Log
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
[k9-log_redacted.txt](https://github.com/k9mail/k-9/files/4892544/k9-log_redacted.txt)

This was redacted from the plain log using: `sed -e s/example.com/"<redcated domain>"/g -e s/user/"<redacted user name>"/g k9-log.txt >k9-log_redacted.txt`

First edit start: 2020-07-08T19:59:55+02:00
Second edit end: ~2020-07-08T20:02:00+02:00
Activity thereafter shows another unrelated draft being composed (for screenshots transfer).

**Comment by hannesss** [comment]
I just updated from 5.6 to 5.717 and run into this issue. The behavior is exactly as described above. I'm using a different mail provider than gmail.

(Beside this, it is great to see all the improvements of the current beta version!:-)

**Comment by manne01** [comment]
Hello there, I use 5.721 on Andoid and I have the same issue. No chance to get the drafted content to the server. Is there anything I can help to figure out?

**Comment by mikini** [comment]
Yeah, this his is a daily frustration that makes me go looking for alternatives. Had the hopes that the log details I collected would make it easier to diagnose, but it doesn't seem so. Unfortunately, I'm unfamiliar with the K9 codebase and not daily into Java/Android, so haven't had the resources yet to dig into it personally,

**Comment by cketti** [comment]
I removed some code that I believed was unused. Turns out it was a very quirky mechanism that made replacing drafts on the server work. I'm not going to restore that code. Instead we'll do it "the right way". This is part of a larger effort and will take some time to complete.

**Comment by manne01** [comment]
Works since 5.724 - great work, thank you so much!
