### ISSUE TITLE
URLs in reopened drafts are bracket expanded not delimited (recursively)

### ISSUE THREAD

**Issue by mikini** [thunderbird/thunderbird-android#4872]
### Expected behavior
URLs in drafts are left as written or is delimited once according to common practice and recommendations ([RFC 3986, app. C](https://tools.ietf.org/html/rfc3986#appendix-C)).

The recommendation and long standing practice (tracing back to an [appendix of W3C's URL specification from 1994](https://www.w3.org/Addressing/URL/5.1_Wrappers.html) which the RFC builds upon) is to **delimit** URLs using angle brackets to allow a somewhat consistent interpretation (introduces some robustness to especially added line breaks).

### Actual behavior
Every URL present in a draft is expanded, not delimited, with a space and itself in angle brackets when it is reopened for editing. Such that fx. `http://example.com` becomes `http://example.com <http://example.com>`.

The expansion is even recursive, so when reopening a saved draft for the second time this occurs again for both the original URL and the URL in brackets such that fx. `http://example.com <http://example.com>` becomes `http://example.com <http://example.com> <http://example.com <http://example.com>>`, and this will continue.

This seems to me to be a misunderstanding trying to provide a rendered representative text for an URL, like the anchor text of a HTML anchor or a Markdown hyperlink. A bit like Markdown's ["autolink" which uses angle brackets](https://daringfireball.net/projects/markdown/syntax#autolink) as a shortcut to creating HTML hyperlinks with the URL as duplicate anchor text in the rendering. However, I think K9 is not intended to do any interpreting of the text here. And I'll be surprised if this has has anything to do with the IMAP store (gmail).

As a side note, it also looks like [Wordpress has been discussing the use of angle brackets in links being sent, and they lost](https://core.trac.wordpress.org/ticket/44589).

### Steps to reproduce
1. First edit; Write new mail containing an URL (body="Http://example.com"), see screenshot 1
2. Save as draft (back->Save as draft or menu->Save as draft), see screenshot 2
3. Second edit; Reopen draft message, observe the expanded URL yielding one duplicate, write some more text ("Test"), see screenshot 3
4. Save as draft (back->Save as draft or menu->Save as draft), see screenshot 4
5. Third edit; Reopen draft message, observe the two URLs each expanded yielding 3 duplicates, see screenshot 5
6. Continue editing, if this is your idea of fun ;)

### Environment
* **K-9 Mail version**: 5.717, see screenshot 6
* **Android version**: 7.0, see screenshot 7
* **Account type (IMAP, POP3, WebDAV/Exchange)**: IMAP (gmail)
* **Phone model**: Samsung Galaxy S8, SM-G950F

### Screenshots
Done using Danish (dansk) locale.
Quick parlour;
* skrive = write
* fra = from
* til = to
* kladder = drafts

#### 1 - first edit
![Screenshot_20200708-184809](https://user-images.githubusercontent.com/1330166/86967278-b70d0780-c16a-11ea-9d9b-75467731bab9.png)

#### 2 - saved first edit
![Screenshot_20200708-184821](https://user-images.githubusercontent.com/1330166/86967293-bd9b7f00-c16a-11ea-9cce-fa792a2ac8d5.png)

#### 3 - second edit
![Screenshot_20200708-184905](https://user-images.githubusercontent.com/1330166/86967310-c429f680-c16a-11ea-9a8d-49b6d7c6ad7b.png)

#### 4 - saved second edit
![Screenshot_20200708-184920](https://user-images.githubusercontent.com/1330166/86967326-c9874100-c16a-11ea-9568-5233040920e9.png)

#### 5 - third edit
![Screenshot_20200708-184930](https://user-images.githubusercontent.com/1330166/86967343-ce4bf500-c16a-11ea-867d-651a5b4f10ec.png)

#### 6 - K9 version
![Screenshot_20200708-184339](https://user-images.githubusercontent.com/1330166/86967367-d6a43000-c16a-11ea-98f5-2634cacafadc.png)

#### 7 - Android version
![Screenshot_20200708-191629](https://user-images.githubusercontent.com/1330166/86967385-dc017a80-c16a-11ea-9350-316884ca4d27.jpg)

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

Could do if it shows not to be easily reproducible.

**Comment by GNUDimarik** [comment]
@mikini I found place where happens dupliacating but I still have no correct fix for that.
Please tell me did you have any experience with duplicating another messages?

**Comment by mikini** [comment]
@GNUDimarik Dmitry, are you asking whether I have experienced this only once?

I see this happen consistently for every draft I start writing in K9 and then subsequently edit in K9.
If that is not your question, could you please elaborate?

I have just upgraded to [K9 5.718](https://github.com/k9mail/k-9/releases/tag/5.718), which does not change the behaviour.

Another test:
Start the message draft from another client (here: gmail web UI), including an URL in body, then edit the draft in K9.
This scenario **doesn't** seem to trigger the bracket delimitation attempt when entering edit mode, the mail body is left as is. Below screenshots depicts the identical message in Gmail and K9, which differs from the behaviour for a local draft described above where URLs are delimited. Besides that, the draft isn't stored correctly to IMAP on saving in K9, as described in #4871, maybe the differing behaviour is related to this?

![Screenshot_20200920-145103](https://user-images.githubusercontent.com/1330166/93712101-bd990180-fb53-11ea-9a13-622cc4835000.png)

**Comment by GNUDimarik** [comment]
No. Asked if another messages without URL was duplicated

**Comment by GNUDimarik** [comment]
@mikini I was wrong peviously. It's HTML => text conversion issue. Now It needs to be fixed correctly.

**Comment by cketti** [comment]
With the default settings K-9 Mail will create a draft containing both a `text/plain` part and a `text/html` part. When converting the user-entered text to HTML the app transforms URLs into clickable links. So `https://domain.example` will become `<a href="https://domain.example">https://domain.example</a>`.

When opening a draft that contains a `text/html` part K-9 Mail will use that to populate the compose UI. To do so the app has to convert the HTML back to plain text (because K-9 Mail does not support rich text editing). Right now this code converts links like `<a href="https://domain.example">link text</a>` to `link text <https://domain.example>`. That seems like a reasonable thing to do for links where the link text is different from the URL. Doing it for links where the link text is equal to the URL leads to the reported behavior.

Converting such links to just the URL (`<a href="https://domain.example">https://domain.example</a>` -> `https://domain.example`) should fix this issue. 
Other links like `<a href="https://domain.example">link text</a>` will still be converted to `link text <https://domain.example>`. And on saving as draft (or sending the message) to `link text &lt;<a href="https://domain.example">https://domain.example</a>&gt;`. But converting that to text again (with the proposed change) will again lead to `link text <https://domain.example>`.

**Comment by GNUDimarik** [comment]
Thanks. Will change the PR
