### ISSUE TITLE
Umlauts in encrypted headings 

### ISSUE THREAD

**Issue by muessjoeh** [thunderbird/thunderbird-android#4918]
When I sent a mail with the heading "Test verschlüsselt", it after receiving it read "?ISO-8859-1?Q?Test_verschl=FCsselt_?=".

**Comment by cketti** [comment]
Please don't just write one line when reporting bugs. The issue template is there so we have a decent chance to reproduce the bug, which is the first step towards fixing it. Not providing the necessary information slows down this process and/or will have us guessing at what's going wrong exactly.

- Please provide the exact version number of K-9 Mail.
- Please provide a step by step guide on how to reproduce the issue (How is K-9 Mail configured? What client is used to send the message? What client is used to read the message?)

**Comment by muessjoeh** [comment]
What is the preferred way to report a bug? I did it this way: In K9mail, I tapped the three lines at the top left, then "Preferences > About > Source code > Issues > +".
I am running K9mail 5.718 on Android 10.
The test message was created by and read with K9mail using an IMAP account.

**Comment by cketti** [comment]
This is the correct place to report bugs. When creating a new issue the text field is populated with the issue template that asks for the kind of information you should provide. It works fine for me both with a desktop browser and with a mobile browser. But in case it doesn't show for you, here's the template: https://github.com/k9mail/k-9/blob/master/.github/issue_template.md

Thanks for the additional information. I was able to reproduce the bug.
