### ISSUE TITLE
K9 Notification Sound

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#4930]
I changed the notification sound on my phone, K9 stuck with the previous sound while all other apps adopted the new one. My expectations are that the app respects the system-wide settings to do with notifications.

Unfortunately I cannot supply a log because I don't own a usb-c usb-a cable.

K9 version 5.600
Stock Android 10
Pixel 2 XL
The issue is app-wide

The notification setup initially was sound and vibration.
I changed the notification sound and K9 retained the previous sound along with vibration.
I tried these things and none fixed the issue:
Restarting the phone
Cleared cache
Removed accounts and cleared app data
Uninstalled, restarted the phone and re-installed app - The app persisted with the original sound + vibration once installed
Deleting the cache(?) of the previous notification sound 
![pic](https://user-images.githubusercontent.com/42522540/91685686-9352b600-eb4a-11ea-85df-f2e42d3a2879.jpeg)
This stopped K9 using the previous notification sound, instead silence and vibration remained
Switching off all notification sounds bar the ring-tone, switching off vibration too then switching them all back on again 
I checked the app was setup to notify me using sound
Currently, the app notifies using vibration only.

Just as an aside, the link to documentation provided in .github/CONTRIBUTING.md, * [User Manual](https://k9mail.github.io/documentation.html), 404's, it leads to https://k9mail.app/documentation.html, perhaps it should be https://k9mail.app/contribute#documentation?

Thank you

**Comment by cketti** [comment]
K-9 Mail 5.600 doesn't support the new notification channel system introduced with Android 8. Try using the latest beta version of K-9 Mail.

**Comment by condemnedmeat** [comment]
Oh I see! I hadn't realised the app hadn't been updated since 2018, shows how observant I am! Made more sense when I read this: https://k9mail.app/2020/06/01/Whats-Up-With-K-9-Mail.html

I'm using the beta, seems great, familiar but different. Notifications working as I would expect so closing this.

Thank you
