### ISSUE TITLE
Show all new mails in the common folder 

### ISSUE THREAD

**Issue by muessjoeh** [thunderbird/thunderbird-android#4934]
**Describe the bug**

I have among others a web.de mail folder. When I am fetching mail, only the ones in the main folders are listed. So, to look whether I have new mail in the 'Unbekannt' folder, I have to open it explicitly, which is very annoying. 

**To Reproduce**

1. Have a web.de mail account 
2. Receive a mail from an unknown account
3. In the common folder, swipe down
4. The mail is not displayed 

**Expected behavior**

It should be displayed

**Comment by cketti** [comment]
I assume by "common folder" you mean the Unified Inbox.

You can configure K-9 Mail to automatically sync the 'Unbekannt' folder by changing its 'folder poll class'. See https://k9mail.app/documentation/folders

You can include messages from the 'Unbekannt' folder in the Unified Inbox by checking the 'unify' checkbox in folder settings.

In the future please use the [forum](https://forum.k9mail.app/) for support requests.
