### ISSUE TITLE
User selected Account is lost on screen rotation

### ISSUE THREAD

**Issue by ufarooq** [thunderbird/thunderbird-android#4936]
**Describe the bug**
User-selected account is lost on screen rotation when setting up an 'unread widget'.

**To Reproduce**
1. Go to the home screen and create 'unread widget'.
2. Click on 'Account' and select user mail-box.
3. Rotate the device or any kind of config changes.
4. The selected account is lost.

**Expected behavior**
The app should retain the user-selected account.

**Screenshots**
![image](https://user-images.githubusercontent.com/1823376/92529936-47ee7680-f1e0-11ea-8866-09786d90a875.png)

**Environment (please complete the following information):**
 - K-9 Mail version:  5.6
 - Android version: 8.1.0
 - Device: Nexus 5X
 - Account type:  IMAP, POP3

**Comment by cketti** [comment]
The problem is that we're not saving state in `UnreadWidgetConfigurationFragment`. `selectedAccountUuid` and `selectedFolderId` should be saved in `onSaveInstanceState()` and restored in either `onRestoreInstanceState()` or `onCreatePreferencesFix()`.

**Comment by starboi02** [comment]
Can I work on this issue?

**Comment by cketti** [comment]
@starboi02: Sure. Go ahead.

**Comment by starboi02** [comment]
Thanks @cketti

**Comment by AlexKDawson** [comment]
@starboi02 I believe I have a working solution to this issue I was just going to PR, but if you prefer I can leave it and go find something else, let you implement 

Sorry I should have commented when I started looking at it!
