### ISSUE TITLE
word wrap on outgoing plaintext mail

### ISSUE THREAD

**Issue by frank-w** [thunderbird/thunderbird-android#4940]
**Describe the bug**
I send mails to mailinglists in plaintext-mode and need automatic wordwrap. Currently i have to do it manually.else i get long lines here. It is only visually wrapped (while writing),but not in the mail itself.

**To Reproduce**

1. Account-settings to plaintext
2. Create new mail with long line (>80chars). It is visually wrapped,but if you send it there is no hard wrap at ~80 chars

**Expected behavior**
Hard wordwrap on word-boundaries every <80 chars

**Screenshots**
None,but see my comment #5 here

https://patchwork.ozlabs.org/project/uboot/patch/20200831075312.15764-1-Chuanjia.Liu@mediatek.com/#2525619

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600
 - Android version: 9
 - Device: samsung s9
 - Account type: IMAP/smtp

**Additional context**
None

**Logs**
No error,it's missing function

**Comment by violoncelloCH** [comment]
why should there be a hard word wrap added by k9 to plaintext mails? If you have a screen at which 79 characters fit and have a hard wrap at 80chars you (or rather the reciever) gets every second line with only one char...Shouldn't this be the task of the displaying mail program to wrap lines dynamically (depending on the available screen space of course)?

**Comment by frank-w** [comment]
have you seen the Link to Patchwork? also i had some responses from linux/uboot-Maintainer wanting such wordwrap because it's easier to read on all devices not only on them which have a softbreak...

at least in Patchwork you have to scroll to show full text...and this on every line. not nice to read

**Comment by cketti** [comment]
K-9 Mail won't add support for automatically inserting line breaks. I consider clients that don't automatically wrap long lines when displaying an email to be broken. If you need to work with such software K-9 Mail is probably not the right app for you.

**Comment by andreyorst** [comment]
@cketti, maybe you could reconsider this?

I use K-9 Mail on my phone so I could send mail to Sourcehut mailing lists, and it specifically mentions this in their [Mailing list etiquette](https://man.sr.ht/lists.sr.ht/etiquette.md#wrap-lines):

> Please wrap lines in your email at 72 columns. Many people use email readers designed to faithfully display plaintext and won't break lines at a width that is comfortable for reading, or won't break lines at all, which is useful when reviewing patches. Some readers also have many things open in addition to their mail client, and may not allocate as much screen real-estate to email as you do.

Given that most mailing lists require or encourage the use of plain text emails, they also don't reflow plain text, as they consider it as a pre-formatted text, especially since reflowing deeply nested citations may break things. As a result, they display plain text emails as is, and this results in very long lines when messages are sent from the K-9 Mail app.

There's also a pretty well-known [useplaintext.email](https://useplaintext.email/#k-9) web page that hosts a comparison of various clients, and has a very similar note to the one on Sourcehut:

> Email writers are encouraged to wrap their text at 72 columns by inserting a newline and resuming your writing on the following line. The [recommended clients](https://useplaintext.email/#recommended-clients) will do this for you, as well as any client shown above with "Wraps text or uses format=flowed" checked. Don't worry about re-wrapping the quoted parts of message you're replying to unless you want to. If your client doesn't do this for you, it can easily be the most frustrating part of being a good email netizen, but it's very much appreciated by recipients.

Unfortunately, this makes K-9 Mail harder to use. Because K-9 Mail is a mobile application it is **extremely** uncomfortable to go and place linebreaks manually, given how imprecise touch screens are, and the lack of arrow buttons on the keyboard to correct your positioning. If the app supported a configurable option that would allow setting custom line break column, it would hugely help, but even a simple toggle that would always break at 72 chars would be all right.

I hope you see why this feature is important. Thanks!

Just as a demonstration, here's how you would have read my comment if it was sent to any of the mailing lists that I use, when sent from K-9 Mail:

```
@cketti, maybe you could reconsider this?

I use K-9 Mail on my phone so I could send mail to Sourcehut mailing lists, and it specifically mentions this in their [Mailing list etiquette](https://man.sr.ht/lists.sr.ht/etiquette.md#wrap-lines):

> Please wrap lines in your email at 72 columns. Many people use email readers designed to faithfully display plaintext and won't break lines at a width that is comfortable for reading, or won't break lines at all, which is useful when reviewing patches. Some readers also have many things open in addition to their mail client, and may not allocate as much screen real-estate to email as you do.

Given that most mailing lists require or encourage the use of plain text emails, they also don't reflow plain text, as they consider it as a pre-formatted text, especially since reflowing deeply nested citations may break things. As a result, they display plain text emails as is, and this results in very long lines when messages are sent from the K-9 Mail app.

There's also a pretty well-known [useplaintext.email](https://useplaintext.email/#k-9) web page that hosts a comparison of various clients, and has a very similar note to the one on Sourcehut:

> Email writers are encouraged to wrap their text at 72 columns by inserting a newline and resuming your writing on the following line. The [recommended clients](https://useplaintext.email/#recommended-clients) will do this for you, as well as any client shown above with "Wraps text or uses format=flowed" checked. Don't worry about re-wrapping the quoted parts of message you're replying to unless you want to. If your client doesn't do this for you, it can easily be the most frustrating part of being a good email netizen, but it's very much appreciated by recipients.

Unfortunately, this makes K-9 Mail harder to use. Because K-9 Mail is a mobile application it is **extremely** uncomfortable to go and place linebreaks manually, given how imprecise touch screens are, and the lack of arrow buttons on the keyboard to correct your positioning. If the app supported a configurable option that would allow setting custom line break column, it would hugely help, but even a simple toggle that would always break at 72 chars would be all right.

I hope you see why this feature is important. Thanks!
```

**Comment by cketti** [comment]
> Some readers also have many things open in addition to their mail client, and may not allocate as much screen real-estate to email as you do.

While this is probably meant to justify the "low" limit of 72 when modern computer screens can display much more characters than that, it's also the perfect argument on why you shouldn't use hard line breaks to wrap long lines. Some people use screens that can't display 72 characters in a line. Small screen devices are a thing now. And they have been for quite a while.

> Just as a demonstration, here's how you would have read my comment if it was sent to any of the mailing lists that I use, when sent from K-9 Mail: 
> [long lines forced to display without soft wraps, so horizontal scrolling is required]

This is very nice demonstration on why clients should soft-wrap when displaying long lines.

Yes, if you insist on using email like it's 1982, your life is going to be hard. No, that is not a good reason to add this "feature" to K-9 Mail.
