### ISSUE TITLE
Improve Singletons

### ISSUE THREAD

**Issue by martingrumbt** [thunderbird/thunderbird-android#4946]
**Description**

I analysed your project for design patterns.
The implementation of the Singleton pattern in some classes is not done in the common way.
The following classes can be improved:

- StorageManager
- Preferences
- TracingPowerManager
- MessageHelper

**Expected behaviour**

- Avoid public constructor
- Avoid forwarding parameters to getInstance-Method for Instantiation
- Only allow access via getInstance-Method
- Use volatile/synced variant to be thread safe
- Avoid Setter to change Instance

**Additional context**

Here are some blueprints for the Implementation that are all thread safe:

_Lazy Instantiation_

```java
public class LazySingleton {
    private static volatile LazySingleton instance;

    private LazySingleton() { /* ... */ }

   
    public static LazySingleton getInstance() {
        if (instance == null) {
            synchronized (LazySingleton.class) {
                if (instance == null) {
                    instance = new LazySingleton();
                }
            }
        }
        return instance;
    }

     /* other methods */
}
```

Pros:
- arguments can be forwarded on instantiation

_Enum Instantiation_

```java
public enum EnumSingleton {
    INSTANCE; 
 
    private EnumSingleton() {
        /* ... */ 
    }
 
    public EnumSingleton getInstance() {
        return INSTANCE;
    }
    
    /* other methods */
}
```

Cons:
- no forwarding of arguments to the constructor when used first time -> Setters needed

_Early Instantiation_

```java
public class EarlySingleton {
    public static final EarlySingleton INSTANCE = new EarlySingleton(); 

    private EarlySingleton() { /* ... */ }

    /* other methods */
}
```

Cons:
- instantiation when class is loaded
- no forwarding of arguments to the constructor when used first time -> Setters needed

**Comment by cketti** [comment]
@martingrumbt: Thanks for reporting this. Are you interested in fixing this yourself?

We are using [Koin](https://github.com/InsertKoinIO/koin) for dependency injection. It supports creating/managing singleton objects. I'd prefer that method over putting the singleton logic inside the classes.
