### ISSUE TITLE
Proper documentation need for sending email (OpenPGP)

### ISSUE THREAD

**Issue by rajib-raiyat** [thunderbird/thunderbird-android#4966]
Why is there no proper tutorial video or documentation for setting up K-9 Mail with OpenPGP?
I tried a lot to find a tutorial video or documentation to set up K9 Mail with OpenGPP. And I didn't get it. 

If there are any tutorial videos or documentation here, please let me know. And if not, then please make a tutorial video or write a  documentation. Please

**Comment by cketti** [comment]
https://k9mail.app/documentation/security/pgpmime_current

In the future please use the [forum](https://forum.k9mail.app/) for support requests.
