### ISSUE TITLE
Account name changes only refresh after app restart

### ISSUE THREAD

**Issue by thomasmstein** [thunderbird/thunderbird-android#4981]
Selecting an account and changing the 'Account name' under 'General settings' applies the change in the settings sections but it does not change the account name in the e.g. account and mailbox selector list or top section. Changes only appear correctly after app restart.

- K-9 Mail version: 5.719
 - Android version: 8.1
 - Device: Moto 5g+
 - Account type: IMAP, POP3

**Comment by iiitomo** [comment]
I can reproduce on 5.727.

**Comment by cketti** [comment]
This has been fixed.
