### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by davidj77** [thunderbird/thunderbird-android#4985]
Hi, the 5.719 crashes when I want to change my account new mail ringtone.

![Screenshot_2020-10-06-07-22-18-1](https://user-images.githubusercontent.com/71226185/95201152-1ea41480-07a5-11eb-835f-b5ee2205fbf0.png)
![Screenshot_2020-10-06-07-22-27](https://user-images.githubusercontent.com/71226185/95201172-2663b900-07a5-11eb-9a37-9277f1a333f6.png)

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by davidj77** [comment]
![Screenshot_2020-10-06-07-22-18-1](https://user-images.githubusercontent.com/71226185/95201512-adb12c80-07a5-11eb-9e80-c177a396614b.png)
![Screenshot_2020-10-06-07-15-54-1](https://user-images.githubusercontent.com/71226185/95201544-b7d32b00-07a5-11eb-9cfb-c015f037050c.png)

**Comment by davidj77** [comment]
I'm using android 5.1.1

**Comment by petrikoz** [comment]
I have this issue with version 5.805. My OS: Resurrection Remix LP v5.5.9. I tried make log by your instruction, but didn't. No option `--pid` in `adb logcat` in version 31.0.3-7562133

**Comment by petrikoz** [comment]
I still have this issue on version 5.806. I used hack for change ringtone:

* export settings to file. It has extension `.k9s` but really it is just a JSON
* open file in a text editor and change data on field `ringtone` for each account
* delete all data in the app on phone (this may be not necessary but without this created doubles of my accounts) and import edited file

Now I still have crashed when trying to change settings. But also have my liked ringtones :)
