### ISSUE TITLE
Mails with empty body text not sent

### ISSUE THREAD

**Issue by TheNitek** [thunderbird/thunderbird-android#4997]
**Describe the bug**
When creating a new mail, it is (quietly) not sent, when no text is entered for the body (even if attachments exist), using the latest beta from Play Store

**To Reproduce**
1. Create new mail
2. Enter recipient and subject
3. Do not enter a text in the body
4. Send mail
5. Email is not sent but no message is shown and mail disappears

**Expected behavior**
Mail is sent

**Environment (please complete the following information):**
 - K-9 Mail version: 5.719
 - Android version: 10
 - Device: MI Mix 3
 - Account type: IMAP/SMTP

**Comment by cketti** [comment]
Works for me. 

Please record a debug log while trying to send such a message. See https://github.com/k9mail/k-9/wiki/LoggingErrors
