### ISSUE TITLE
Email address too long for line

### ISSUE THREAD

**Issue by luf7** [thunderbird/thunderbird-android#5004]
**Describe the bug**
A mail address that is too long to fit on the display won't be accepted as one address but two (or more) addresses.

**To Reproduce**
Try to send an email to an address that is too long for your display width, for example `abcdefghijklmnopqrstuvwxyz@outlook.com`. The app will now display the address in two lines, in my case like this:
`abcdefghijklmnopqrstuvwxyz@outlook.
com`
The app will now see every line as single address and think you want to send mails to `abcdefghijklmnopqrstuvwxyz@outlook.` and `com`.

**Expected behavior**
The app should see the address as a single one, even after a new line.

**Environment**
 - K-9 Mail version: 5.721
 - Android version: 10
 - Device: Samsung Galaxy A9

**Comment by cketti** [comment]
Works for me. Can you provide a screenshot?

**Comment by ovz93br43v7** [comment]
Same problem here
![Screenshot_20201015-151104](https://user-images.githubusercontent.com/48738861/96131356-5cb5dc80-0ef9-11eb-8132-e7265325fce9.png)
![Screenshot_20201015-151114](https://user-images.githubusercontent.com/48738861/96131363-5de70980-0ef9-11eb-8683-37f7265d0714.png)

**Comment by ovz93br43v7** [comment]
@cketti I can also provide a video if it helps you?

**Comment by cketti** [comment]
It might help. I'm still not able to reproduce the issue.

**Comment by paulle** [comment]
I don't have this issue.
v 5.724 (from f-droid) android10 sony xperia5

**Comment by ovz93br43v7** [comment]
Here the video from Pixel 3, Android 11, 5.724 from F-Droid


[k9-2.mkv.zip](https://github.com/k9mail/k-9/files/5649566/k9-2.mkv.zip)

**Comment by paulle** [comment]
Cannot open or unzip your video seems corrupted. But I believe you your problem with with long email addresses.

I have no idea because it works on my phone and on yours.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
Now I have this issue too. Why i don't know, because I'm using the same version of k9 and android as before. v 5.724 (from f-droid) android10 sony xperia5 .
A little workaround is to put the phone in horizontal view when using a long mail address.

**Comment by iiitomo** [comment]
on v5.727, I reproduce when I hit the Send button while the cursor is active in the 'Subject' field or the 'Message text' field.
In other words, the bug doesn't appear if I hit the Send button while the cursor is active in the 'To' or 'Cc' or 'Bcc' field.
Hope that helps.

**Comment by paulle** [comment]
Thank you for the hint, I'm on v5.726 the v5.727 till now isn't available on fdroid. When I get the new version I will try. But it's a really annoying behaviour and it seems only happen to few people.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
No I've v5.727 installed, the trick with putting the cursor in the cc or bcc field don't work for me. I've to go horizontal view. But in horizontal view the key board is tapping nearly all.

Really annoying this.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by cketti** [comment]
Add a comma after the email address to work around this bug.

**Comment by paulle** [comment]
Thank you for the hint.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
Thank you, the trick with team comma worked.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
