### ISSUE TITLE
tree folder view

### ISSUE THREAD

**Issue by 532910** [thunderbird/thunderbird-android#5011]
The current flat folders view looks ugly and uninformative:

![image](https://user-images.githubusercontent.com/14617699/96226097-cc2fd880-0f9a-11eb-9a1a-f7d8ec8bbc66.png)

Compare with thunderbird for example:
![image](https://user-images.githubusercontent.com/14617699/96225911-79562100-0f9a-11eb-8fb2-887c0d875a20.png)

**Comment by cketti** [comment]
Duplicate of #630

**Comment by 532910** [comment]
Sorry, I missed it.
