### ISSUE TITLE
Unable to delete messages from inbox

### ISSUE THREAD

**Issue by jbfavre** [thunderbird/thunderbird-android#5026]
**Describe the bug**
When trying to delete messages, messages disappear, but are not moved into Trash directory.
When re-opening k-9, deleted messages still appear in inbox.

Please note that it could also happen with messages from other directory ( I didn't test it)

**To Reproduce**
1. Open k-9 (unified inbox in my case)
2. Select one or many messages
3. Delete them
4. Quit k-9
5. Re-open k-9
6. Messages are still in inbox

**Expected behavior**
Deleted messages should be visible in Trash directory and not in inbox anymore

**Environment (please complete the following information):**
 - K-9 Mail version: 5.722 (beta)
 - Android version: 11
 - Device: Google Pixel 4a
 - Account type: IMAP

**Additional context**

**Logs**
[k9-mail.log.txt](https://github.com/k9mail/k-9/files/5434913/k9-mail.log.txt)

**Comment by cketti** [comment]
Thanks for the debug log :+1:

The problem occurs when trying to move a message not containing a `Message-ID` header field.

**Comment by jbfavre** [comment]
Make sense: most, if not all, impacted messages are spam.

Thanks for the quick answer and fix ! :ok_hand:

**Comment by mapausch** [comment]
Is there already a plan when the next beta release will be published as this issue gets more and more annoying each day.
Many thanks in advance.

**Comment by mapausch** [comment]
Thanks for your work, @cketti :-)
