### ISSUE TITLE
Inbox list shows name of recipient

### ISSUE THREAD

**Issue by nu-fo** [thunderbird/thunderbird-android#5030]
**Describe the bug**
If same IMAP folder is selected for both Sent and Inbox folders then message list in Inbox shows recipient name.

**Expected behavior**
Inbox message list should always show sender name.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.722

**Comment by cketti** [comment]
To work around this please select another folder as Sent folder.

We'll probably prevent users from assigning multiple special roles to one folder in the future.

**Comment by nhfo** [comment]
Please do not go down that path. There is nothing wrong in having multiple roles assigned to one IMAP folder. I like to keep my sent email in inbox folder to keep all email of a thread in one place for example. And in one case I have Archive folder set to inbox, because I do not want to even accidentally archive emails.

It would suffice if Inbox message list would again display sender name.

**Comment by cketti** [comment]
Assigning multiple roles to the same folder has caused numerous problems in the past and has again just now. I understand that dropping features is really annoying to users. But I don't consider this one important. And there is a significant maintenance cost.

It sounds like just working around a missing feature of K-9 Mail. See #735.

Selecting 'None' under `Setttings > [Account] > Folders > Archive folder` will disable the archive functionality.

**Comment by nhfo** [comment]
> It sounds like just working around a missing feature of K-9 Mail. See #735.

Not really. K-9 is not the only email client I use, keeping sent messages in inbox is client agnostic. This is so basic that it can't be called a feature. As such I do not see any benefit of keeping sent emails in a separate folder. 

How about k-9 select what to display based on if and what special folder is selected and not base it on what IMAP folder is in use and if that is assigned sent or archive role?
