### ISSUE TITLE
App crashes when sending new mail from shared inbox

### ISSUE THREAD

**Issue by Maetts** [thunderbird/thunderbird-android#5035]
**Describe the bug**
When trying to write a new mail from the shared inbox view the app crashes. 

**To Reproduce**
1. Go to shared inbox 
2. Click on write new email
3. See error

**Expected behavior**
The app should not crash but open the mail editor 

**Screenshots**
N/A

**Environment (please complete the following information):**
 - K-9 Mail version: 5.723
 - Android version: 10
 - Device: Huawei P30 Pro
 - Account type: IMAP

**Additional context**
N/A

**Logs**
N/A

**Comment by frenchy82** [comment]
I can confirm this bug with a Huawei mediapad m5 lite but not with à xiaomi note 9 pro

**Comment by cketti** [comment]
Composing messages works fine for me. Are you sure it's not replying to messages that is broken?

**Comment by Maetts** [comment]
Yes it is definitely new message from the shared inbox.

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by cketti** [comment]
Nevermind. I found a matching crash in the Google Play Console.

**Comment by Maetts** [comment]
Just noticed that the error occurs also when replying to a mail in shared but also in account view.
