### ISSUE TITLE
Webview's BrowserMetrics should be regularly cleaned by K-9

### ISSUE THREAD

**Issue by basilgello** [thunderbird/thunderbird-android#5061]
**Describe the bug**

I noticed that K-9 Mail occupies 800MB of internal storage and decided to check what eats so much space.
Running `du -h /data/data/com.fsck.k9` revealed the WebView's `BrowserMetrics` uncontrollably grows.

The bug itself affects every app using webview, as shown on the following screenshot, however privacy-oriented apps like Bromite do delete the whole folder on exit.

Browser Metrics is a privacy-invasive "feature" anyway that is not used by K-9.

**To Reproduce**
1. As root, run `du -h /data/data/com.fsck.k9`
2. Enjoy the large number of tracking info collected about webpages rendered from your inbox :)

**Expected behavior**
Such invasive and space-consuming telemetry should be removed regularly to minimize privacy impact

**Screenshots**
![Screenshot_20201122-163202](https://user-images.githubusercontent.com/3913291/99906625-d0a98880-2ce0-11eb-8112-c4e0838e6850.png)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.724
 - Android version: 7
 - Device: Samsung armv7l
 - Account type: IMAP

**Comment by basilgello** [comment]
@cketti

**Comment by AlanTheLinuxGuy** [comment]
Can confirm experiencing the same issue with K-( using more than 1 GB of available storage space such that Google's Play Store would not download or install any apps or updates.  Deleting all the files com.fsk.k9/app_webview/BrowserMetrics resolved the problem (for now!)
![2020_12_18_16 32 08](https://user-images.githubusercontent.com/76230234/102665059-16c40180-4152-11eb-84e9-f13b4dfe6495.jpg)

**Comment by cketti** [comment]
Sounds like a platform issue to me. What Android ROMs are you using?

**Comment by AlanTheLinuxGuy** [comment]
I am using a custom-ROM for Android 9 from User MSe1969 on XDA Developers:

[ROM][Unofficial][9.0.0][signed]LineageOS 16.0 for Osprey
https://forum.xda-developers.com/t/rom-unofficial-9-0-0-signed-lineageos-16-0-for-osprey.4095453/

**Comment by basilgello** [comment]
@AlanTheLinuxGuy we (the group of people maintaining legacy LineageOS including MSE1969) resolved the problem by switching system webview to Bromite. But @cketti please consider adding the code to remove this folder (of if you have no time, let me do it!) because most K-9 users are not so tech-savvy to migrate system webview.

**Comment by AlanTheLinuxGuy** [comment]
@basilgello  Is the fix in LineageOS or in K-9?  I assume that without a fix in one of these, I will have to keep monitoring the BrowserMetrics folder and deleting the accumulating files.  Thanks for your assistance on this issue.

**Comment by basilgello** [comment]
The fix is neither there nor here yet. Please check https://bromite.org for instruction how to replace system webview with Bromite.

**Comment by woheller69** [comment]
I also had such Webview problems. They have been fixed in LineageOS in the meantime. Installing Webview Beta from Google Play also solved the problem.

**Comment by icarof0x** [comment]
> **Describe the bug**
> 
> I noticed that K-9 Mail occupies 800MB of internal storage and decided to check what eats so much space. Running `du -h /data/data/com.fsck.k9` revealed the WebView's `BrowserMetrics` uncontrollably grows.
> 
> The bug itself affects every app using webview, as shown on the following screenshot, however privacy-oriented apps like Bromite do delete the whole folder on exit.
> 
> Browser Metrics is a privacy-invasive "feature" anyway that is not used by K-9.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. As root, run `du -h /data/data/com.fsck.k9`
> 2. Enjoy the large number of tracking info collected about webpages rendered from your inbox :)
> 
> **Expected behavior** Such invasive and space-consuming telemetry should be removed regularly to minimize privacy impact
> 
> **Screenshots** ![Screenshot_20201122-163202](https://user-images.githubusercontent.com/3913291/99906625-d0a98880-2ce0-11eb-8112-c4e0838e6850.png)
> 
> **Environment (please complete the following information):**
> 
> * K-9 Mail version: 5.724
> * Android version: 7
> * Device: Samsung armv7l
> * Account type: IMAP
