### ISSUE TITLE
Download complete message shows 'Connection error'

### ISSUE THREAD

**Issue by raskinmaya** [thunderbird/thunderbird-android#5068]
**Describe the bug:**
Clicking 'download complete message' brings up a 'connection error' toast, but after going back to the folder and returning to the message, the complete message is shown.

**Environment (please complete the following information):**
K-9 Mail version: 5.725-SNAPSHOT
Android version: 7.0
Device: Android emulator
Account type: IMAP

**Comment by cketti** [comment]
Works for me. Can you provide a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors)?
