### ISSUE TITLE
the error message error

### ISSUE THREAD

**Issue by zyIsPig** [thunderbird/thunderbird-android#5076]
**Describe the bug**
when i try to send email, the receiver should not include Chinese, but the error message is error message.
**To Reproduce**
1. Go to 'send page'
2. Click on 'receiver'
3. Input the illegal address including Chinese character

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: [e.g. 5.718]
 - Android version: [e.g. 10]
 - Device: [e.g. Google Pixel 4]
 - Account type: [e.g. IMAP, POP3, WebDAV/Exchange]

**Additional context**

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Sorry, I don't really understand what this bug report is about. Can you please try to describe it in more detail? And provide a screenshot if possible.
