### ISSUE TITLE
unable to configure end to end key on Redmi Note 8T

### ISSUE THREAD

**Issue by tigernero79** [thunderbird/thunderbird-android#5080]
on a Xiaomi redmi note 8t device it is impossible to select which Key to use for a particular account.  in practice the openkeychain window does not appear when selecting openpgp support skills and then I click on configure end to end key, the window to select my private key does not appear.  on Samsung s10 plus and 2xl pixels everything works fine.  How to solve?

![16090157434673484165551376764835](https://user-images.githubusercontent.com/35575744/103158991-444d2280-47c4-11eb-80ef-15a58d3d2f10.jpg)

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/how-do-i-make-k-9-mail-work-with-openkeychain-on-xiaomis-miui/82

In the future please use the forum for support requests.

**Comment by tigernero79** [comment]
Thanks for all
