### ISSUE TITLE
certain messages reliably crash k9

### ISSUE THREAD

**Issue by teicher** [thunderbird/thunderbird-android#5081]
The message I am attaching here reliably crashes k9 (playstore latest 5.600 on Blackberyy Priv Android 6.0.1, IMAP postbox)
crash report also sent via app crash dialog.
Older messages from the same sender also managed this before.
It's just a regular newsletter from a guy who plays live piano to silent movies, so nothing except my email address needs to be treated confidential.

**Comment by teicher** [comment]
[k9crash.eml.zip](https://github.com/k9mail/k-9/files/5745007/k9crash.eml.zip)

**Comment by cketti** [comment]
Please provide the information asked for in the issue template. I don't want to have to guess which K-9 Mail version you're using.

**Comment by teicher** [comment]
already had added the missing info to the original post via edit, due to browser trouble, sorry.
seems editing does not send out mail notifies.

**Comment by cketti** [comment]
I can't reproduce the issue. The message displays fine for me both with K-9 Mail 5.600 and 5.726 (beta).

Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by teicher** [comment]
[k9crash.log](https://github.com/k9mail/k-9/files/5830742/k9crash.log)
here we go

**Comment by cketti** [comment]
The log doesn't contain a lot of information. But it looks like a crash in Chrome (which powers the system's WebView component that we use to display message contents). That code is not part of K-9 Mail, but your system. Try upgrading Chrome.

**Comment by teicher** [comment]
Chrome App is 87.0.4280.141
Android System Webview also 87.0.4280.141
(playstore latest)

Well, if it's not k9, there's not much we can do.
thanks for checking.

**Comment by cketti** [comment]
You could record an unfiltered log. That should contain information on where/why the Chrome code crashes. I'm sure the Chrome team would be grateful for a bug report containing that information.
