### ISSUE TITLE
Notifications bar background issue on dark/night theme

### ISSUE THREAD

**Issue by SingingFrog7** [thunderbird/thunderbird-android#5083]
Hello Guys, 

First, thanks for that nice open source app!

**Describe the bug**
If the phone is in dark/night mode and that there is more than one email notifications in the notifications bar, the background is no more dark and is clear instead. The text is still clear so it's unreadable

**To Reproduce**
1. Put your phone in dark/night mode (to get dark theme)
2. Wait to receive more than one email without clearing the notification
3. See error

**Expected behavior**
The notification background should stay dark with more than 1 email

**Screenshots**
![Screenshot_20201228-161146_PhoneTrack](https://user-images.githubusercontent.com/22401071/103243759-cf472d80-4928-11eb-91fe-48cb30368fd0.jpg)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.724 (from F-Droid)
 - Android version: Android 9, stock rom
 - Device: Samsung Galaxy S8+
 - Account type: IMAP

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by joe540** [comment]
It appears I was on version 5.600, suggested by F-Droid. Updating to the latest available version on F-Droid fixed the issue
