### ISSUE TITLE
The signature sent does not match his true identity

### ISSUE THREAD

**Issue by tigernero79** [thunderbird/thunderbird-android#5086]
I am using my private key with yubico token to which 5 identities are associated (5 different emails) if I send an encrypted email between them thunderbird reports me an error in the digital signature. this is because the signature sent is always that of the main identity and not that of the 5 used.

example if main identity is nero@pico.it and I have 2 other examples (bianco@pico.it and giallo@pinco.it)

if I send email between the last two he will always send the signature with nero@pico.it although I send it with another identity (binco@pico.it) of the same key.

![Immagine](https://user-images.githubusercontent.com/35575744/103348534-99c25180-4a9a-11eb-8189-ef9379774e7e.png)

but if I use one of my 5 identities to send encrypted emails to an identity that is not mine, the signature of the identity used must be sent correctly, it does not always use the main one

the problem is the choice of signatures when I send encrypted emails among my 5 identities, always use the signature of the main identity

**Comment by cketti** [comment]
Please provide instructions on how to reproduce the issue. Please be more specific when you talk about identity. Do you mean identities configured in K-9 Mail? Please also specify which K-9 Mail version you are using.

**Comment by tigernero79** [comment]
by identity I mean email.  On an openpgp key I entered 5 emails, when I send a rmail between them encrypted and signed in openpgp the signature regardless of which of the 5 emails I use for sending is always done with the main email.  if I send to a different email between k and 5 mine the signature is chosen correctly based on the email used.

use latest version k9mail 5.726

**Comment by cketti** [comment]
Please provide step by step instructions on what you're doing with as much detail as possible. I have no idea what you're doing with which email client and what the actual issue is.

**Comment by tigernero79** [comment]
Step 1

I configure 5 emails on k9mail v5.726

( email= nero79@email.it, nero79@msn.com and 3 more,, all 5 emails have a single openpgp reference key)
(main email appears to be **nero79@msn.com**) nero79@msn.com main identity openpgp

Step 2

(I send an encrypted email from one of my 5 emails to emails that are not mine, the signature is the correct one linked to the email) the recipient receives the item signed by nero79@msn.com or one of my other emails and here everything is ok

Step 3

Now if I try to send an encrypted email from nero79@email.it to nero79@msn.com, via k9mail and check the reception for example on thunderbird, the signature is made by nero79@msn.com while it should have been done by nero79 @ email.it

in practice k9mail chooses the right signature for emails not belonging to the same openpgp key, while always choose the main email as signature if you send between emails with the same openpgp key

**Comment by cketti** [comment]
Messages are signed by the key. The signature doesn't contain information on which "identity" was used to sign the message. All a receiving client can do is look at the sender address and check to make sure it's associated with the key used to sign the message.

Maybe this is a bug in Thunderbird. Have you checked other email apps?

**Comment by tigernero79** [comment]
@cketti tomorrow I will check better.  maybe it can be Thunderbird since I use Key openpgp on a yubikey 5 Nfc.  and they don't support openpgp smartcards from v78 onwards well
