### ISSUE TITLE
Mail stopped coming in or going out

### ISSUE THREAD

**Issue by yaomtc** [thunderbird/thunderbird-android#5096]
**Describe the bug**
Mail is not going out or coming in. Here is the notification I have:

> Failed to send some messages 
> Errnoexception: android_getaddrinfo failed: EPERM (Operation not permitted)

I noticed I haven't been getting emails in my K-9 inbox for 5 days, while I can see them fine in Thunderbird.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.726
 - Android version: 11
 - Device: Pixel 4a
 - Account type: IMAP

**Additional context**
I am using PrivateEmail.com.

**Logs**
[k9-log.txt](https://github.com/k9mail/k-9/files/5832228/k9-log.txt)

**Comment by cketti** [comment]
From the log: `java.lang.SecurityException: Permission denied (missing INTERNET permission?)`

Looks like the app doesn't have the internet permission. The app does request this permission. And on vanilla Android you can't deny/revoke this permission. So either you're using a custom ROM that provides this as a feature or your installation is somehow broken. In that case try uninstalling, then reinstalling the app.

**Comment by yaomtc** [comment]
Oh weird, it's somehow been denied Internet permissions (as well as Sensors)... even though it was working a week ago. Odd. Well, yes, I'm using GrapheneOS, forgot to mention that.

That solved my issue, thanks @cketti!
