### ISSUE TITLE
Unable to configure OpenPGP encryption keys

### ISSUE THREAD

**Issue by NRG-600** [thunderbird/thunderbird-android#5107]
**Describe the bug**
End to End encryption provided by Openkeychain is broken, unable to select my OpenPGP keys through account settings.

**To Reproduce**
1. Generate a new PGP key through Openkeychain
2. Select account settings
3. Scroll down to end to end encryption
4. Enable OpenPGP support
5. Select configure end to end keys

**Expected behavior**
According to your own documentations expected behaviour should be launch of Openkeychain whenever I try to configure my OpenPGP keys through account settings.
Here's the link of expected behaviour of K9 
https://k9mail.app/documentation/security/pgpmime_current

**Screenshots**
![IMG_20210126_105402](https://user-images.githubusercontent.com/37657519/105804143-0f034280-5fc5-11eb-9095-fde8d4e05f1e.jpg)

![IMG_20210126_105501](https://user-images.githubusercontent.com/37657519/105804213-3bb75a00-5fc5-11eb-9279-ab6528161f8b.jpg)

![Screenshot_2021-01-26-11-02-58-887_com fsck k9](https://user-images.githubusercontent.com/37657519/105804746-91d8cd00-5fc6-11eb-924a-5ffcb35f9444.png)

**Environment**
 - K-9 Mail version: [5.726]
 - Android version: [Android 7.1.2 Nougat]
 - Device: [Xiaomi Redmi 4A]
 - Account type: [IMAP]

**Additional context**

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Please see https://forum.k9mail.app/t/how-do-i-make-k-9-mail-work-with-openkeychain-on-xiaomis-miui/82
