### ISSUE TITLE
Active stars are difficult to identify in Dark theme

### ISSUE THREAD

**Issue by iiitomo** [thunderbird/thunderbird-android#5120]
When K9mail is in Dark mode, it's difficult to see which emails are starred (light blue star) or not (light grey star).

I recommend better contrast between active/inactive stars. For example the inactive star could be filled with black color instead of light grey, see mockup below:

![k9](https://user-images.githubusercontent.com/58949423/106881446-d7d81400-66dd-11eb-9ac8-97747a52421b.png)

Lineage 17.1 - Android 10, K9mail 5.600

**Comment by cketti** [comment]
Already fixed in the beta version.
