### ISSUE TITLE
'Reply all' is proposed despite only 1 contact

### ISSUE THREAD

**Issue by iiitomo** [thunderbird/thunderbird-android#5124]
'Reply all' appears in the action list even when there is only 1 contact (you are the unique recipient of the original message, and nobody in copy)

**To Reproduce**
1. Open a message where you are the only recipent and there is nobody in CC
2. Click on the arrow to make the action list appear
3. The list shows 'Reply', 'Reply all', 'Forward' ...

**Expected behavior**
The list should not show 'Reply all' in this (frequent) case.

**Screenshot**
![replyall](https://user-images.githubusercontent.com/58949423/107130985-12ef6880-68d3-11eb-9134-55178f5a63c8.png)

**Environment:**
 - K-9 Mail version: 5.727
 - Android version: 10  (Lineage 17.1)

**Comment by cketti** [comment]
Fixes by #6482
