### ISSUE TITLE
Mail no longer being received upon app upgrade

### ISSUE THREAD

**Issue by mandraid** [thunderbird/thunderbird-android#5148]
I was running the latest stable version (5.6) on GrapheneOS.  I then upgraded to 5.728 through F-Droid.  I noticed that I can no longer receive mail.

**Comment by cketti** [comment]
Probably the same issue as #5139. It's fixed in 5.730. But it'll probably take a few days before that is available on F-Droid.

What you could do is clear the app data and reimport your settings. Make sure to enter the server passwords in the import screen and **not** click the 'Later' button.
