### ISSUE TITLE
K-9 Mail size is heavy and it is impossible to reduce it

### ISSUE THREAD

**Issue by Massedil** [thunderbird/thunderbird-android#5155]
**Describe the bug**

K-9 app uses 676 Mo of user data on my phone. It is impossible to clear that data because it is not cached data.

I found that this data is mainly composed of an `app_webview/BrowserMetrics` folder (616Mo) that can't be deleted.

If it is email cached data, we need a way to clear that cache.

**To Reproduce**

1. Go to the application information menu in Android Parameters > Applications > K-9 Mail
2. In "Storage and cache", I can see that user data is big.

**Expected behavior**

If that data are email data, I expect them to be in the cache data of the app to have a way to clean it.
If that data in `BrowserMetrics` are just some metrics, I think that they can be automatically deleted or never stored. 

**Screenshots**

|||
|---|---|
|![1](https://user-images.githubusercontent.com/20357783/108388317-cf6bf700-720e-11eb-935b-4abdd1d3ce4c.png)|![Screenshot_20210218-144819_DiskUsage](https://user-images.githubusercontent.com/20357783/108388458-f32f3d00-720e-11eb-8524-cc39064c5517.png)|

**Environment**
 - K-9 Mail version: 5.729
 - Android version: 10
 - Device: Samsung Galaxy S5
 - Account type: IMAP

**Comment by cketti** [comment]
Are you by any chance using a custom ROM? See #5061

**Comment by Massedil** [comment]
Yes, I'm using LineageOS 17.1.

So I can delete the folder without problem ? 
And do you know if the bug is now corrected by LineageOS ?

**Comment by cketti** [comment]
Sorry, I don't know anything about it. Only that I'd like to see this bug fixed in the platform rather than having to work around it.

**Comment by Massedil** [comment]
For feedback, deleting the BrowserMetrics folder works for me. Thanks.
