### ISSUE TITLE
Home screen shows negative unread count

### ISSUE THREAD

**Issue by martinosorb** [thunderbird/thunderbird-android#5161]
**Describe the bug**
New email count shows negative number, as in the screenshot below.

**To Reproduce**
not sure whether it will be easy to reproduce, but this is what happened:
- I received two emails when I clicked on the update button
- I marked them as read _on my computer_
- K9 on my phone showed -2.
When I received another email, it showed -1 (i.e. the problem did not go away when reloading folders).

**Expected behavior**
Show 0.

**Screenshots**
![photo_2021-02-19_11-38-00](https://user-images.githubusercontent.com/11293950/108493739-f544da80-72a6-11eb-8201-c252f3c54d48.jpg)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600
 - Android version: 10
 - Device: Samsung A40
 - Account type: IMAP

**Logs**
Not an error.

**Comment by cketti** [comment]
This is no longer an issue with beta versions 5.7xx
