### ISSUE TITLE
title bar is flashing

### ISSUE THREAD

**Issue by FoxxiFox** [thunderbird/thunderbird-android#5172]
Hello, when I open an e-mail in k9-mail, the upper and lower status bars flash.  Only when I click on "Show pictures" does the flashing stop.  This error only occurs in k9-mail.  Many greetings.

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/header-and-footer-bar-flicker/623

Please feel free to create another issue if this is still a problem with the latest beta version. Make sure to provide all the information asked for in the issue template, especially which K-9 Mail version you're using.
