### ISSUE TITLE
Can't paste password when adding account

### ISSUE THREAD

**Issue by SeerLite** [thunderbird/thunderbird-android#5173]
**Describe the bug**
Can't paste into the password field when adding an account (e.g. when copying from a password manager)

**To Reproduce**
1. Copy anything to the clipboard
2. Start the process of adding a new account
3. Hold down on the password input field or invoke the "select/copy/paste" popup through other means.
4. Notice the "paste" option isn't available.

**Expected behavior**
The "paste" option should be available to easily copy and paste passwords when adding or logging in to accounts.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600
 - Android version: 9
 - Device: Xiaomi Redmi Note 8
 - Account type: IMAP

**Additional context**
I know using the clipboard for passwords is discouraged, but right now my device won't let me invoke the KeePassDX keyboard for some reason, so I'm falling back to using the clipboard.

KeePassDX also has an autofill function but K-9 won't let me use that one either, it completely ignores it. (should I create a separate issue for that?)

**Logs**
Can't add them from mobile :/. Let me know if they're necessary (doubt it) and I'll add them when I can

**Comment by Djfe** [comment]
This issue doesn't exist anymore. I can paste passwords just fine. Atleast in 6.712

**Comment by cketti** [comment]
Works for me, too.
