### ISSUE TITLE
Draging an account on the accounts screen crashes

### ISSUE THREAD

**Issue by poldi171254** [thunderbird/thunderbird-android#5175]
During testing of my fix for issue #4875 if found that if you try and drag any of the accounts listed
![Crash](https://user-images.githubusercontent.com/43848359/109459490-fb129b00-7ab2-11eb-9904-f64d5196cd73.png)
 on the accounts screen down (I appreciate that it makes no sense to do this here, but you can) it crashes; well actually it never finishes.

I'm running the K9 V 5.731 Beta on my tablet, and I observe the same behaviour in the Studio emulator for my forked repos of 5.732. Attached is the log from Studio
[crash.log](https://github.com/k9mail/k-9/files/6059511/crash.log)

**Comment by cketti** [comment]
The problem is that we change the UI from a background thread. The fix should be relatively straight-forward. 
What Android version(s) are you using for testing? I'm curious to learn why it's not crashing on my test device.
