### ISSUE TITLE
K9 Mail crashes with replicant 6

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#5176]
Hello,

When I first start K9 mail, it asks for mail, password. I  fill these fields, and when clicking next it freezes.

The K9-mail version is Version 5.731, from f-droid.

The replicant version is 6.0 0003

The phone is Samsung S3 i9300

**Comment by millerebonds** [comment]
I attached the output of adb logcat

[logcat.pdf](https://github.com/k9mail/k-9/files/6061187/logcat.pdf)

**Comment by cketti** [comment]
I don't think this is a bug in K-9 Mail. Please report this to the Replicant project.

**Comment by millerebonds** [comment]
?

Before, K9 Mail worked well.

If I downgrade, it works

**Comment by cketti** [comment]
K-9 Mail is triggering the bug in the OS, it is not causing it. It's working fine when not using Replicant. 
We're not going to work around a bug in an OS that a) can be easily updated and b) has a market share of approximately 0%.

**Comment by millerebonds** [comment]
It's the only OS which is supported by the free software foundation, and people who work on replicant are rather nice and hard-working (they work on newer versions).

I'm rather beginner, and try to help like I can.

I have some "difficulties" to hear that it's "approximately 0%".
Pinephone is approximately 0%, GrapheneOS is approximately 0%, Mobian and PostmarketOS are approximately 0%… but in the future?

**Comment by millerebonds** [comment]
The 5.400 version of K9 Mail works well with replicant, no crashes.

Download of attached files work too, with the replicant default download manager.
