### ISSUE TITLE
Clicking on "Add Account (NEW) comes up with a TODO item

### ISSUE THREAD

**Issue by poldi171254** [thunderbird/thunderbird-android#5182]
Latest beta version, in the settings screen, when I select 'Add Account (NEW) ' I get the attached.
What's the difference between 'Add Account' and 'Add Account (NEW)'?

Maybe not showing a function that has not been implemented would be better
![ToDo](https://user-images.githubusercontent.com/43848359/109607635-a50a2a00-7b7c-11eb-9f0c-90ef1f7bd0bf.png)

**Comment by cketti** [comment]
This is only included in debug builds. It was added because someone volunteered to work on the new setup UI.

Closing this issue because it's not affecting released versions.
