### ISSUE TITLE
A sent(?) message hasn't been synchronized with the server

### ISSUE THREAD

**Issue by birdie-github** [thunderbird/thunderbird-android#5183]
I'm running K-9 mail 5.731. Here's an issue.

Yesterday I _seemingly_ successfully sent an email (I used an already sent one and hit "Edit as new message") however today I've found out that it **only** exists in the Sent folder of my K-9 application, i.e. it's not on the server (I'm obviously using the IMAP protocol with plain TLS authentication, i.e. no Oauth2 or other shenanigans).

Now I've got a number of questions:
1. How can I know whether I've actually sent it or not? The message contains Message-ID (`<UUID@domain.com>`) but I've no idea whether the ID is generated by the app or was given to the app by the server. I do not want to sent the message again.
2. How can I actually save the message to my Sent folder? Whenever I hit Refile, I get, "Cannot copy or move a message which is not synchronized with the server".

I've already asked my email provider support whether they've actually sent the message or not but it's not certain whether they'll reply or confirm.

Today I've sent two test messages, first normally via "Compose" and then I sent an old one via "Edit as new" and everything works as expected, so I've no idea what the glitch was yesterday.

**Comment by cketti** [comment]
The local message is only moved from the local Outbox to the (local) Sent folder when the outgoing mail server has accepted the message. So the message was most likely sent.

It sounds like something went wrong during the upload to the Sent folder. Usually the upload is retried until it succeeds or a "permanent" error is returned by the server. Unfortunately this information is only printed to the (in-memory) log and is probably gone by now. Currently there's no way to instruct K-9 Mail to attempt uploading the message again :disappointed:

**Comment by birdie-github** [comment]
Looks like there's nothing that can be done but the remaining issue is that there's an inconsistency in what the app operates with and what's stored on the IMAP server. I hope the app will not start crashing randomly.
