### ISSUE TITLE
[Forwarding/Replying to Email] - Lost Email after Screen Autolocks (returns to the original email without saving a draft copy of the Email) [Pre-release version] 

### ISSUE THREAD

**Issue by life777eternal** [thunderbird/thunderbird-android#5190]
**Describe the bug**
After starting to compose a Forwarded Email, the email is lost if the screen is allowed to Autolock. 

**To Reproduce**
1. Open an email. 
2. Select Forward 
3. Add in email address(es) into the "To" "CC" or "BCC" field(s). 
4. Write 📝 something at the top 🔝. 
5. Wait for the screen to Autolock. 
6. Remember & return and unlock the screen. 
7. See the original email and wonder where your forwarded email went & feel like you've just wasted 🗑 your time ⌚. 

**Expected behavior**
A new email should autosave if the screen autolocks and still be there when the screen is unlocked again. 

This is also happening when replying to an email. Just recently I started writing a reply to an email, went back to a home screen or another app, and when I returned to K-9 Mail, my reply text was gone and the original email appeared again. 

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: [5.731, 5.732]
 - Android version: [10]
 - Device: [LG G7]
 - Account type: [IMAP]

**Additional context**

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
Works as expected on my devices. A draft is saved and the compose screen is still active when the device is unlocked.

Can you please try to reproduce the issue and record a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by life777eternal** [comment]
Ok, I see 👀, will try that later, it's happened several times already now.

**Comment by life777eternal** [comment]
> Works as expected on my devices. A draft is saved and the compose screen is still active when the device is unlocked.
> 
> Can you please try to reproduce the issue and record a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

Hey @cketti I have tried to get a bug report, though the cmd window is showing "> was unexpected at this time." ... when running the command on the 3rd step: "`adb logcat -d --pid=<PID> > k9-log.txt`" 

![-Administrator_ C__Windows_system32_cmd](https://user-images.githubusercontent.com/25623649/111375255-a3079700-8663-11eb-8f7b-b241ad144e1f.png)

**Comment by life777eternal** [comment]
Hey @cketti was able to get a log text file after a new email disappeared.

[k9-log-new-message-lost.txt](https://github.com/k9mail/k-9/files/6152166/k9-log-new-message-lost.txt)

Hope it helps.

**Comment by cketti** [comment]
None of the logs contain any relevant information. Please try recording an unfiltered log. Write down the time you lock the screen (or the screen autolocks, if that is important for triggering the issue). Write down the time you unlock the screen again. Ideally there will be some time between the screen locking and unlocking so the entries in the log can more easily be associated with one of the events.

**Comment by life777eternal** [comment]
Alright @cketti, though the logs contain my actual email address(es) and I'm not sure it's a good idea to share them with my email address(es) in them.

**Comment by cketti** [comment]
Feel free to redact the log. With "unfiltered" I meant you shouldn't filter using the process ID.

Use `adb logcat > k9-log.txt` to start logging. Then press CTRL-C to stop logging once you're done.

**Comment by life777eternal** [comment]
Ohhh now you tell me... that wasn't on the instruction link you sent before. 


> Works as expected on my devices. A draft is saved and the compose screen is still active when the device is unlocked.
> 
> Can you please try to reproduce the issue and record a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by life777eternal** [comment]
That log capture includes a lot of personal information, including email addresses, email names, actual email subject lines, some of the first lines of the body of the email, from email address for emails, all the folders under the inboxes. As well as info about other apps on the phone, and email on other apps. Which makes it take extra time to redact it when the text file is over 100,000 lines long. Even with `Replace All` on `Notepad++` it seems to be taking a long time to get through it all.

**Comment by life777eternal** [comment]
Hi @cketti was able to reproduce the problem yesterday though I had a screensaver set to come on when the screen locks, and before I disabled the screensaver, I tried it again and pressed the lock button after the screen autolocked with the screensaver on, though now I can't seem to reproduce that problem. ... Which process ID's do you need? The log file I have from yesterday is over 100,000 lines long.  Thank you.

**Comment by cketti** [comment]
Well, I don't think there's anything fundamentally wrong with how K-9 Mail is saving drafts. It works for me and many others.  Also, your previous logs don't show any errors logged by K-9 Mail.

It's probably that your device is doing something "strange". The hope is that the log will contain some hint on what is going on exactly. I don't know what I'm looking for, otherwise I'd explicitly ask for it.

**Comment by life777eternal** [comment]
Ok, then which process ID's are not needed? 

Because

`3828  4519 E InputMode: plaintext for ExternalViewNode(className=android.widget.TextView, inputMode=plaintext, id=com.fsck.k9:id-subject)/android.view.accessibility.AccessibilityNodeInfo@1876f; boundsInParent: Rect(0, 0 - 993, 85); boundsInScreen: Rect(284, 308 - 1277, 393); packageName: com.fsck.k9; className: android.widget.TextView; text:` is showing the email subject lines, and 

`3828  4519 E InputMode: plaintext for ExternalViewNode(className=android.widget.TextView, inputMode=plaintext, id=com.fsck.k9:id-preview)/android.view.accessibility.AccessibilityNodeInfo@1786b; boundsInParent: Rect(0, 0 - 1068, 121); boundsInScreen: Rect(256, 397 - 1324, 518); packageName: com.fsck.k9; className: android.widget.TextView; text: »` is showing the first portion of the email body.
((And there's even the gmail widget process showing other emails on gmail.))

Well K-9 Mail is now saving drafts it seems, now that I pressed the lock button after the screen autolocked with the screensaver on yesterday. Or the unsent emails still in the compose stage are not disappearing now after the screen autolocks.
