### ISSUE TITLE
K9 crashes when addressing a Domain with an emoji

### ISSUE THREAD

**Issue by dartmann** [thunderbird/thunderbird-android#5200]
When I want to paste an emoji email address, the activity crashes and I get back to the welcome screen. 

(sorry, I opened this issue via FastHub and the prefilled template data is missing here. I will complete it as soon as I get to a PC.)

**Comment by cketti** [comment]
Please provide more detailed steps on how to reproduce this issue. Also, which K-9 Mail version you're using.
