### ISSUE TITLE
Crash when sending to address with an umlaut

### ISSUE THREAD

**Issue by CrimsonFork** [thunderbird/thunderbird-android#5204]
I haven't done any variation testing, as I just finally found out. What I had was:

A contact which I accidentially typed an `ü` instead of `ue`, used the contact suggestion feature for recepient. As soon as I hit send, Android's "Application has stopped working" window popped up, after a restart it's as if nothing had happened.

Replacing the character in my contacts helped, but It took me probably a month to figure out what the issue was.

**Comment by cketti** [comment]
Please provide more detailed instructions on how to reproduce the error. Which field of the contact contains an umlaut? What version of K-9 Mail are you using?

**Comment by MrHeating** [comment]
The actual E-Mail address, before the @.

v5.732, aka latest from F-Droid
-- 
Sent with K-9 Mail. Please excuse my brevity.
