### ISSUE TITLE
Message body not shown

### ISSUE THREAD

**Issue by obo** [thunderbird/thunderbird-android#5212]
**Describe the bug**
Suddenly, a couple of days ago, K-9 stopped showing message body, only white area appears. The body is correctly received and known to K-9, because the 1-line preview in message list contains the text and both Forward and Reply correctly populate the new message with the received text. It is kind of annoying to have to pretend a reply just to read e-mails. :-)

**To Reproduce**
1. Click any message in the message list.
2. See the error: only the buttons and the header is shown, no message body.

Without any system update or app update, this issue suddenly affected all my 3 IMAP accounts and around at the same day also the cell phone of my wife (same hardware) with 2 totally different IMAP accounts.

**Expected behavior**
To see the message body.

**Screenshots**

K-9 knows the message body, "Warning: Job ..." in the screenshot:

![body-known-and-shown-in-preview](https://user-images.githubusercontent.com/192828/112225867-ba2f2180-8c2d-11eb-90ac-679e6ead1079.jpg)

Opening the message does not show it any more:

![missing-body](https://user-images.githubusercontent.com/192828/112225913-c6b37a00-8c2d-11eb-997c-87732475725f.jpg)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600 from the market as well as 5.733 installed from APK
 - Android version: 8.0.0
 - Device: Samsung Galaxy A3 (2017) SM-A320FL, Samsung Experience 9.0, last update Oct 30, 2020.
 - Account type: IMAP

**Additional context**

**Logs**
Sorry, I am not a regular Android developer, I'm considering an easier route of switching to FairMail. I can add the logs if convince me they can help at all.

**Comment by worraps** [comment]
about the same time as OP I can open NO messages without K-9 crashing.  No crash log seems to be generated even though I have the logging checkbox on.  
**To Reproduce**
Same as OP - 5 IMAP accounts - all crash on opening any message
No OS or app updates occurred.

**Environment**
- K-9 Mail version: 5.600 
- Android version: 9.0.0
- Device: Motorola e6
- Account type: IMAP

**Comment by cketti** [comment]
See https://www.androidpolice.com/2021/03/23/surprise-app-crashes-are-plaguing-tons-of-android-users-heres-how-to-fix-them/

**Comment by worraps** [comment]
problem vanished not 1 hour after this post!.... grrr the audacity ?!? (yes "they" manipulated my phone at will and "fixed" it ?!!? )

**Comment by cketti** [comment]
You could disable automatic updates for the Android WebView app and/or Chrome app to avoid surprises like this in the future. But keeping your browser updated is good security practice.
