### ISSUE TITLE
Mixed encoding personal name only displays part of the name

### ISSUE THREAD

**Issue by IBBoard** [thunderbird/thunderbird-android#5228]
**Describe the bug**
I've just received a phishing email that K-9 shows as being from "UPS(GB)". The spacing is wrong, but it's easy for someone to confuse it with a legitimate UPS email. Viewing it in Thunderbird, I see that the name is "(krumhqcx) UPS(GB) (neejeugsesjvdbymtb)". That is FAR easier to spot as a malicious email.

Looking at the headers, I see that the From address has an encoded UTF-8 block, which is the only bit that K-9 is showing:

```
From: (krumhqcx) =?utf-8?B?VVBTKEdCKQ==?= (neejeugsesjvdbymtb)
 <joracing@hotmail.it>
```

I don't know whether the spammers are intentionally triggering a common bug to have a longer unique name that spam filters ignore but that then only displays the short name to users, or whether it's just an accident.

**To Reproduce**
1. Use default "show friendly name" view
2. Receive email containing a mix of ASCII and encoded UTF-8 blocks in the friendly name part
3. Compare name in header versus name in K-9

**Expected behavior**
K-9 should show the full name from the header when displaying the header and not just a substring of it (as long as there is sufficient space)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600
 - Android version: 10
 - Device: OnePlus 5
 - Account type: IMAP

**Additional context**

Given how spammers/phishers operate, this is a security risk for users (even if it's not a security vulnerability in K-9 itself)

**Comment by cketti** [comment]
The text in parentheses are comments. They can appear in a lot of places in an email header. I don't think it's a good idea to associate them with a particular email address or display them at all. Maybe open a bug with Thunderbird instead.

The issue would be the same if the header was
```
From: "UPS(GB)" <joracing@hotmail.it>
```

Duplicate of #1119

**Comment by IBBoard** [comment]
Thanks for the info. If that's what the standard says then I guess that makes some sense (and I fully agree that the other ticket would be the right behaviour IF it was just the string in quotes).

But when it comes to "people doing malicious things in headers to con users and bypass systems" then I'll take the Thunderbird behaviour any day of the week, even if it's not 100% standards compliant. So thanks for the suggestion, but I won't raise a bug with Thunderbird.
