### ISSUE TITLE
Headers are missing after fragment change

### ISSUE THREAD

**Issue by mpas97** [thunderbird/thunderbird-android#5237]
**Describe the bug**
Since the change of https://github.com/k9mail/k-9/pull/5152 we only see very few headers. Before the update the list contained much more than just From, To, Date, Subject. The ones I'm really interested in like Received, Authentication-Results, Disclaimer and many more have now disappered in k9, but are still there in all other clients.

**To Reproduce**
1. Open a message
2. Click "show headers"
3. The list of headers is now very short

**Expected behavior**
Show again the full header list, else it is almost not useful.

**Screenshots**
Current view:
![IMAGE 2021-04-08 17:17:03](https://user-images.githubusercontent.com/9994218/114052330-3eb8ab80-988e-11eb-9305-06cb681f58f7.jpg)

Same email as above, but before the update (or now with other clients):
<img width="84" alt="grafik" src="https://user-images.githubusercontent.com/9994218/114051935-d7026080-988d-11eb-801b-d2e6b95a73cb.png">

**Environment:**
 - K-9 Mail version: 5.733
 - Android version: 10
 - Device: Huawei P20 pro
 - Account type: IMAP, Exchange

**Comment by cketti** [comment]
Does this only happen with messages that haven't been downloaded completely?

**Comment by mpas97** [comment]
I just tried to hit that button, and it works. The list is much longer after downloading the whole message.
But I don't want this as I explicitly have to check for phishing etc before I download the whole thing...

**Comment by cketti** [comment]
The previous versions of K-9 Mail behaved the same. I created issue #5240 as a feature request for the behavior you want.

**Comment by mpas97** [comment]
I don't think so, as I never downloaded a message til now... And I surely saw those headers before too.

**Comment by cketti** [comment]
I tested this with 5.730 (before the "show headers" change) and with 5.600. The behavior didn't change.

Messages that are smaller than `Account settings > Fetching mail > Fetch messages up to` are downloaded completely (including all header fields). So if there's no "Download complete message" button, all headers will be available.

**Comment by mpas97** [comment]
Hmm, okay. Then I was just lucky til today. Thanks for clarifying!

**Comment by mpas97** [comment]
But what exactly is not downloaded if the message is bigger? Do you also cut the content after eg. the 32kb that are set in the fetch settings? Or is this only for attachments and things like header data?

**Comment by mpas97** [comment]
@cketti ? Would be really useful to demystify this setting.

**Comment by cketti** [comment]
It's an implementation detail that can change at any time. What use case do you have that requires exact knowledge of what is downloaded?

**Comment by mpas97** [comment]
The point is that this is an end user setting. But if that's so unclear of what's included there, why or how should we be able to choose an adequate size preference? I always saw this but I never knew what to choose as we don't even know of what will be affected by this... So that it apparently also affects and therefore cuts the downloaded header fields (which I would have expected to be shown completely or not at all), is quite intransparent. An image/attachment will probably also never be downloaded halfways. A more intuitive setting than this "fetch size" would be to only download eg. attachments of a given size. This is precisely defined and therefore easy to understand which in turn allows us to make a choice.
