### ISSUE TITLE
Crashing consistently when opening E-Mails on Oneplus 9 Pro

### ISSUE THREAD

**Issue by leomeinel** [thunderbird/thunderbird-android#5238]
**Describe the bug**
Crashing consistently when opening E-Mails 

**To Reproduce**
1. Open email
2. Crash

**Expected behavior**

**Environment (please complete the following information):**
 - K-9 Mail version: 5.733
 - Android version: 11
 - Device: Oneplus 9 Pro
 - Account type: Gmail (IMAP) with App password

**Additional context**
Netguard installed (K9 whitelisted)
Some other Services blacklisted or disabled through system settings

**Comment by TamrielNetwork** [comment]
using fdroid Version

**Comment by cketti** [comment]
Sounds like you're still affected by the WebView crash. See https://www.androidpolice.com/2021/03/23/surprise-app-crashes-are-plaguing-tons-of-android-users-heres-how-to-fix-them/

It it's a different problem please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
