### ISSUE TITLE
Downloaded messages are not sorted correctly

### ISSUE THREAD

**Issue by mpas97** [thunderbird/thunderbird-android#5239]
**Describe the bug**
After having downloaded two messages they both show on top of the unified mailbox instead on their place by date.

**To Reproduce**
1. Open a message
2. Click on 'download message'
3. Go to the list view
4. The message appears on top although it is older

**Expected behavior**
Downloaded messages should be correctly sorted in the list. Date of sending not downloading.

**Screenshots**
The first two items are downloaded ones and as you can see they should not be sorted there.
![IMAGE 2021-04-08 17:59:28](https://user-images.githubusercontent.com/9994218/114058920-29df1680-9894-11eb-9196-70f0d193e3b8.jpg)

**Environment:**
 - K-9 Mail version: 5.733
 - Android version: 10
 - Device: Huawei P20 pro
 - Account type: IMAP, Exchange

**Comment by cketti** [comment]
Are you sorting by "arrival" rather than "date"?

**Comment by mpas97** [comment]
I didn't see the actual selection, but I reselected "date" and it works now. Thanks!
