### ISSUE TITLE
update play store version

### ISSUE THREAD

**Issue by seiro22** [thunderbird/thunderbird-android#5254]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

If you are unsure whether or not you have found a bug please post to the support forum instead: https://forum.k9mail.app

**Describe the bug**
k-9 mail is a version from 2018 on play store, it needs update to match fdroid

https://play.google.com/store/apps/details?id=com.fsck.k9

**To Reproduce**
1. https://play.google.com/store/apps/details?id=com.fsck.k9

**Expected behavior**
play store version is updated

**Screenshots**
https://play.google.com/store/apps/details?id=com.fsck.k9

**Environment (please complete the following information):**
 - K-9 Mail version: [e.g. 5.718]
 - Android version: [e.g. 10]
 - Device: [e.g. Google Pixel 4]
 - Account type: [e.g. IMAP, POP3, WebDAV/Exchange]

**Additional context**

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
See https://k9mail.app/2020/06/01/Whats-Up-With-K-9-Mail
