### ISSUE TITLE
Opening zip-file launches the Zoom-App

### ISSUE THREAD

**Issue by wdherndon** [thunderbird/thunderbird-android#5269]
Trying to open an attached zip-file launches the Zoom-App. Presumably some other app if Zoom is not installed.

To Reproduce:
- Send yourself a zip file
- Open the email in K9 (Android version)
- Tap on the "Open" button for the attachment.
-> K9 launches Zoom
- Have a heart attack as you think K9 has executed the contents of a zip-file rather than letting you see the contents.

Expected behavior:
- Either: Let me choose the app to use to open the zip-file: I have no app for zip-files, but several generic viewers that show up whenever unknown extensions are found
- Or: list the contents of the zip-file in K9 itself and offer to open or download those files

Environment:
- K-9 Mail version: 5.600
- Android version: 9
- Device: BlackView 9900
- Account type: IMAP

Additional context:
Zoom is installed, of course.

Log file attached.
[k9-log.txt](https://github.com/k9mail/k-9/files/6360912/k9-log.txt)

**Comment by cketti** [comment]
When clicking an attachment K-9 Mail asks the system to open the file for viewing. It's up to the system to find a matching app. 
The behavior you're seeing is most likely caused by the Zoom app doing things it shouldn't do.
