### ISSUE TITLE
All other notifications disappears if i click on one

### ISSUE THREAD

**Issue by pingou2712** [thunderbird/thunderbird-android#5270]
Hi,

**Describe the bug**
if I have 5 notifications (5 new mails) on my phone. If I open one of them all other notifications disappears. 
I want only the one clicked to disappear.

**To Reproduce**
easy

**Expected behavior**
Just close the notification that i click on

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600
 - Android version: 11
 - Device: samsung s20+
 - Account type: IMAP

**Comment by cketti** [comment]
This should be fixed in K-9 Mail 5.909.
