### ISSUE TITLE
App crashes on opening mail with invalid Sender: header

### ISSUE THREAD

**Issue by jcbradfield** [thunderbird/thunderbird-android#5271]
**Describe the bug**
If a message with an invalid address of the form ...@...@... in the Sender: header is opened, the app crashes.

**To Reproduce**
1. Arrange for a message such as the following to be present in the IMAP folder:
-------------
From: julian@julianbradfield.org
Sender: jcb@julian@julianbradfield.org
To: jcb@julianbradfield.org
Message-Id: <atestmessage@julianbradfield.org>
Subject: test
Date: Fri, 23 Apr 2021 12:24:28 +0000

test
-------------

2. View the folder in k9mail and open the message.

**Expected behavior**
View the message as normal, either with the invalid address left alone, or corrected to (in this case) "jcb@julian"@julianbradfield.org

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600 
 - Android version: 8
 - Device: Xiaomi Redmi Go
 - Account type: IMAP

**Additional context**
The above mnwe is constructed - this arose in the live by messages sent from hostedemail.com on behalf of one of their customers. I have asked the customer to raise a bug report with hostedemail.com about their sending of invalid addresses. Nonetheless, k9mail should handle them gracefully!

**Logs**
application crashes, so no logs

**Comment by cketti** [comment]
This bug has already been fixed. The fix is included in recent beta versions. See [How do I become a beta tester?](https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68)
