### ISSUE TITLE
Date parser is case sensitive: "APR" should be parsed as April.

### ISSUE THREAD

**Issue by tomfitzhenry** [thunderbird/thunderbird-android#5285]
**Describe the bug**
https://github.com/k9mail/k-9/blob/a3d6fd7ab4ba1426f4fdf3ded51286219f5eeb10/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapList.java is missing a date format to match a `Date` field with a capitalised month, e.g. `Date: 26 APR 21 21:17:10 +0000`

**To Reproduce**
1. Sync an email with header `Date: 26 APR 21 21:17:10 +0000`
2. Observe that email's date as rendered in the k-9 UI

**Expected behavior**
The date is 2021-04-26 21:17:10.

**Actual behavior**
The date is now().

**Environment (please complete the following information):**
 - K-9 Mail version: 5.734
 - Android version: 11
 - Device: Google Pixel 4XL
 - Account type: IMAP

**Additional context**
https://tools.ietf.org/html/rfc2822#section-3.3 does consider a capitalised month "APR" to be invalid.

**Comment by tomfitzhenry** [comment]
Is https://docs.oracle.com/javase/9/docs/api/java/time/format/DateTimeFormatterBuilder.html#parseCaseInsensitive-- available to k9-mail?

**Comment by cketti** [comment]
> [`a3d6fd7`/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapList.java](https://github.com/k9mail/k-9/blob/a3d6fd7ab4ba1426f4fdf3ded51286219f5eeb10/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/ImapList.java) is missing a date format to match a `Date` field with a capitalised month, e.g. `Date: 26 APR 21 21:17:10 +0000`

`ImapList.parseDate()` is only used for IMAP's `INTERNALDATE` property, not the value of the `Date` header field.


> [tools.ietf.org/html/rfc2822#section-3.3](https://tools.ietf.org/html/rfc2822#section-3.3) does consider a capitalised month "APR" to be invalid.

Well, ABNF strings are case-insensitive. So I guess the parser should have been able to handle this. 

However, it's also using the [obsolete syntax](https://tools.ietf.org/html/rfc5322#section-4). Every implementation that generates such a date string in 2021 needs to be fixed. Please (also) try to get the sender to fix their message generation.

**Comment by tdboorman** [comment]
I have the same issue with an email that has the following in its message header:

date: 19 may 2022 17:14:33

**Comment by cketti** [comment]
> date: 19 may 2022 17:14:33

This is not a valid date value because it is missing the time zone offset. Time zone information has never been optional, i.e. even the obsolete syntax requires it.

Please contact the author of the message and ask them to fix the software they're using.

**Comment by tdboorman** [comment]
It is not an issue in Thunderbird or in FairEmail, so presumably UTC is assumed, or one of the other dates in the message header is used.

**Comment by cketti** [comment]
For "but it works with other clients", please see #1356.
