### ISSUE TITLE
v5.734 does not install on one mobile

### ISSUE THREAD

**Issue by Michas0206** [thunderbird/thunderbird-android#5286]
**Describe the bug**
Install of .apk from here closes with "app is not installed." after it asks "install update...?"

**To Reproduce**
Hard to say - I have 2 different mobiles, both with Lineage OS 18.1 - and on my second mobile I did exactly the same, where it installed without a problem.

Only difference I see atm is that mobile 1 (where it not works) is armv7 32bit and mobile 2 (where everything is fine) is armv8 64bit...not sure if thats the reason or something else in my setup or what I am doing.

**Expected behavior**
Should update fine

**Environment (please complete the following information):**
 - K-9 Mail version: [5.734]
 - Android version: [11]
 - Device: [Galaxy S5 klte]

Possibly I try to uninstall and simply do a fresh install to verify this better later today...

**Comment by cketti** [comment]
K-9 Mail versions from F-Droid are signed with a different key. Versions from GitHub or Google Play can't update a version installed from F-Droid and vice versa.
If that doesn't explain the issue you're seeing, it's probably a problem with Lineage OS.
