### ISSUE TITLE
Import not possible if host has self signed certificate (certpathvalidator exception)

### ISSUE THREAD

**Issue by Af0x** [thunderbird/thunderbird-android#5288]
Hello,

when you import an account, enter the password for imap and smtp the inbox does not fill up due to an error "certpathvalidator exception" if the server has self signed certificates.

Best regards,

Af0x

**Comment by cketti** [comment]
This should lead to an error notification. We're already tracking the missing notification under #3459.

To make it work go to `Settings > [Account] > Fetching mail > Incoming server` and press "Next". Same under `Settings > [Account] > Sending mail > Outgoing server`.
