### ISSUE TITLE
configured visible action do not match visible actions

### ISSUE THREAD

**Issue by MarcusWolschon** [thunderbird/thunderbird-android#5298]
**Describe the bug**
Einstellungen->Allgemeine Einstellungen->Anzeige->Sichtbare Nachrichtenaktionen
Englich: "visible message actions"(?)

is set to:
DELETE+ARCHIVE+MOVE+SPAM

The actually visible actions are:
ARCHIVE+DELETE+MARK (UN)REAT+PREVIOUS+NEXT

**To Reproduce**

should be obvious

**Expected behavior**

The 4 configured actions being visible and all other actions being in the menu, screen space permitting.
All visible actions actually being configurable. 
("mark as unreat" isn't a very often used action for me and would do well being in the menu. Navigating to next/prev I never, ever use.)

**Screenshots**
(trying to find out how to upload screenshots in the desktop browser version)

**Environment (please complete the following information):**
JMAP DEV

**Additional context**

**Logs**

**Comment by MarcusWolschon** [comment]
![3](https://user-images.githubusercontent.com/604692/118278539-640e8a00-b4ca-11eb-907c-16cbe619d0d9.png)
![2](https://user-images.githubusercontent.com/604692/118278543-64a72080-b4ca-11eb-9714-fdda30b76872.png)

**Comment by MarcusWolschon** [comment]
Trying to find out where this happens in the source code to propose a fix but I'm betting lost.

**Comment by cketti** [comment]
See `MessageList.configureMenu()`.

I created a new issue proposing a more generic solution to this problem: #5300
