### ISSUE TITLE
Attachments are not forwarded

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [thunderbird/thunderbird-android#5303]
**Describe the bug**
When forwarding an email with an attachment, the attachment is ignored.

**To Reproduce**
Forward an email with attachment

**Expected behavior**
The attachment should appear in the forwarded email

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600
 - Android version: 11
 - Device: Samsung Galaxy Note 12
 - Account type: IMAP

**Comment by cketti** [comment]
Duplicate of #3028
