### ISSUE TITLE
k-9 Mail does not show all Emails, search finds the email

### ISSUE THREAD

**Issue by logan82** [thunderbird/thunderbird-android#5310]
Hello,

I have the same/similar issue in K-9 Mail version 5.6 and version 5.734:
https://github.com/k9mail/k-9/issues/1422

I sent an Email to several recipients using roundcube Webmailer.
I see that have opened the Emails, I get a lot of "Read: ..." confirmations.

6 People answered, but no answers are displayed in K-9 income folder.
When I search in k9, the emails are displayed!

What I did: 
- Upgrade k9 from 5.6 to 5.743 (f-droid) as recommended in the Bug-Report, didn't help
- Changed number of messages from 25 to unlimited, didn't help as well

 - Android version: 8.1
 - Device: BQ Aquaris X
 - Account type:  IMAP

**Comment by cketti** [comment]
When you write "search finds the email", do you mean a server-side search?

**Comment by logan82** [comment]
The server-side search is disabled, so I guess it is a local search.

**Comment by cketti** [comment]
If local search finds the messages they have been downloaded. I believe that makes this problem different from #1422.

Are the messages maybe in a folder other than the Inbox?

**Comment by logan82** [comment]
No, Roundcube shows them like all other messages in the inbox-folder

**Comment by cketti** [comment]
Can you please disable `Settings > General settings > Display > Threaded view` and check if the messages are displayed then?

**Comment by logan82** [comment]
I disabled it, and now, all emails are shown.

**Comment by cketti** [comment]
Thanks. So it might be a threading issue.

Can you enable threading again and check all threads in the Inbox to see if the responses have been included in the wrong thread?

**Comment by logan82** [comment]
I enabled theads again and the messages are missing again. 
I also checked the sent-Folder as the incoming emails should belong to my sent email? 
Couldn't find it there as well. I think, it would be strange if I found it there....

**Comment by logan82** [comment]
sorry, correction: All Emails are integrated into one read confirmation email, that I got from one receipient. But the emails are from different senders!

**Comment by cketti** [comment]
Sounds like it's working as intended. A thread groups a message and all responses to it (read confirmations are just a special type of response). Whether or not those responses are from one sender or multiple senders doesn't matter.

**Comment by logan82** [comment]
Thank you!
