### ISSUE TITLE
k9-Mail v5.734 crashes on attempt to open email

### ISSUE THREAD

**Issue by mmsenxxx** [thunderbird/thunderbird-android#5322]
The app opens without issue but when an attempt is made to open an email the app restarts or closes.

**To Reproduce**
1. Open K9-Mail
2. Select an email from the Inbox (or unified inbox)
3. Watch the app crash :(

**Expected behavior**
To be able to view more than just the opening line of the email.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.734
 - Android 12
 - Google Pixel 4a
 - Account type: IMAP

**Additional context**

**Logs**
[20210531_k9-log.txt](https://github.com/k9mail/k-9/files/6571814/20210531_k9-log.txt)

**Comment by jikamens** [comment]
I'm seeing this as well, with a Pixel 3 XL, immediately after upgrading to the Android 12 beta. It was working fine before the upgrade to the beta.

**Comment by cketti** [comment]
The relevant lines from the log:

```
05-31 19:19:15.415 16185 16185 E WebViewFactory: Chromium WebView package does not exist
05-31 19:19:15.415 16185 16185 E WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
```

For some reason there's no `WebView` provider installed on your device. K-9 Mail (and I'm sure many other apps) won't work without one.

**Comment by mmsenxxx** [comment]
> The relevant lines from the log:
> 
> ```
> 05-31 19:19:15.415 16185 16185 E WebViewFactory: Chromium WebView package does not exist
> 05-31 19:19:15.415 16185 16185 E WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
> ```
> 
> For some reason there's no `WebView` provider installed on your device. K-9 Mail (and I'm sure many other apps) won't work without one.

Thanks. Any idea why android webview would suddenly go ghost? I didn't do anything besides install android 12.

**Comment by cketti** [comment]
https://issuetracker.google.com/issues/182802945

**Comment by mmsenxxx** [comment]
Just uninstalled Android SystemWebView. Then reenabled. Problem resolved. Thanks @cketti

**Comment by jikamens** [comment]
Thanks @cketti. Same fix worked for me. Also, I signed up for your Liberapay for $1 a month.
