### ISSUE TITLE
Can't search through subfolders

### ISSUE THREAD

**Issue by N1co93** [thunderbird/thunderbird-android#5326]
**Describe the bug**
The search in K9-Mail doesn't find any messages in subfolders. I also set "searchable folders" to "all"

**To Reproduce**
1. Click on the searchbar
2. Try to search an message from a subfolder
3. See an empty search result

**Expected behavior**
The search should also include the subfolders

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: 5.734
 - Android version: 10
 - Device: Huawei P20 Pro
 - Account type: IMAP

**Additional context**
Maybe i'm wrong and this is not a bug, but a feature request.

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: Are the logs already needed, because the app doesn't run into any errors. If the logs are needed I will provide them.

**Comment by cketti** [comment]
See #4514
