### ISSUE TITLE
Forum has a certificate issue

### ISSUE THREAD

**Issue by NNickey** [thunderbird/thunderbird-android#5328]
https://forum.k9mail.app/

Your connection is not private
Attackers might be trying to steal your information from forum.k9mail.app (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
forum.k9mail.app normally uses encryption to protect your information. When Google Chrome tried to connect to forum.k9mail.app this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be forum.k9mail.app, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit forum.k9mail.app right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by cketti** [comment]
Thanks for the report :+1:

For some reason the automatic certificate renewal didn't work and the TLS certificate expired.
I used this opportunity to upgrade the forum software and reboot the VM. After the reboot the certificate was automatically renewed. Things should be back to normal now.
