### ISSUE TITLE
Can't login using v5.734 and GMail(IMAP or POP3) on a fresh install

### ISSUE THREAD

**Issue by gbschenkel** [thunderbird/thunderbird-android#5331]
I have installed K-9 Mail v5.734 from F-Droid and was near 2h trying to login. Previous I tried use v5.600 but since it showed a message about not been compiled for my Android version and I was not been able to connect I upgraded to the last version.

Since a long time I know I need a App Password which I have generated before try, but the the K9 after I fill the user / pass and press to continue, it instantly refuse. I tried use Manual Config to see if some configuration was wrong, tried POP3 and still it was refusing. Have searched on web but didn't find anything related.

Well then I tried to uninstall and install the version 5.733, and voilà, it worked!
Just out of conscience I upgraded to 5.734 to see if it would still work, and yes, it did.

**To Reproduce**
1. Go to F-Droid and install K9 Mail v5.734
2. Create a new [App Password](https://myaccount.google.com/apppasswords) on your G.Account
3. Open the installed K9 Mail
4. Fill your G.Account username and the created app password.
5. Continue and see the error "unable to connect"

**Expected behavior**
To K9 Mail to be able to connect using G.Account on a fresh install using v5.734

**Environment (please complete the following information):**
 - K-9 Mail version: 5.734
 - Android version: 11
 - LineageOS version: 18.1
 - Device: OnePlus 5 (cheeseburger)
 - Account type: IMAP

**Logs**
If needed I will reset my the app and create a log.

**Comment by amir28** [comment]
What error did you get and did you enable [Less Secure mode](https://myaccount.google.com/lesssecureapps)?

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.

This thread might be relevant: https://forum.k9mail.app/t/gmail-setup-could-not-finish/650
