### ISSUE TITLE
Bouncing effect on receiving emails

### ISSUE THREAD

**Issue by williamdes** [thunderbird/thunderbird-android#5332]
**Describe the bug**
When I receive emails the process iterates over each of my folders and creates a bouncing effect on the notifications below

**To Reproduce**
1. Have an IMAP account with a lot of folders
2. Wait for an email to make your phone ring
3. Open the screen and start reading the email preview
4. Oh it's a notification email, let me mark it as read
5. Try to mark it as read as the notification goes up and down in rhythm with the changing folders

**Expected behavior**
You could use the same notification for each folder and just edit the contents

**Screenshots**

<will upload a video>

**Environment (please complete the following information):**
 - K-9 Mail version: latest
 - Android version: 9
 - Device: Honor P9 lite
 - Account type: IMAP

**Comment by cketti** [comment]
Work-around: Disable "sync notifications" under `Settings > [Account] > Notifications > Sync notifications`

**Comment by williamdes** [comment]
> Work-around: Disable "sync notifications" under `Settings > [Account] > Notifications > Sync notifications`

Thank you for the workaround ;)
I think I will not use it but I will keep that in mind

Do I still need to send a video or do you see what I am talking about ?

**Comment by cketti** [comment]
I think I know what you mean. But right now I'm more likely to remove the sync notification than to fix it :smile:

**Comment by williamdes** [comment]
> I think I know what you mean. But right now I'm more likely to remove the sync notification than to fix it

I can probably contribute, let me know if you are open to contributions ;)

This app is very very important in all my day and "it needs to work" so I would invest time if you agree

**Comment by cketti** [comment]
I don't see how this notification is useful. Why do you want to know when a folder is being checked?

**Comment by williamdes** [comment]
I need to know why my network is slow for example, when I am in nature I want to browse and need to know what app is using bandwidth.
Anyway, I need this notification and I am sure other users also do
It's important for me to see what folder r is getting pulled, etc..

Here is a screenshot of yesterday, the app pulling emails while I was walking and suddenly needed to lookup something

This example is a very small folder, of the ton of folders I have, I really need to know what folder it is on and how long it takes 

![Screenshot_20210609_225031_com.huawei.android.launcher.jpg](https://user-images.githubusercontent.com/7784660/121498784-0e4fd380-c9dd-11eb-8833-0f86ee1f7171.jpg)

**Comment by cketti** [comment]
I don't find that a very convincing argument for keeping the functionality. There's probably better tools to learn which apps are using network resources. The notification does nothing to help you control K-9 Mail's use of the network. You could turn on "data saver" to prevent apps from using the network in the background when you need the bandwidth.

So far everyone else I talked to doesn't use this feature (or doesn't like it and was grateful when I pointed out it can be disabled).

**Comment by williamdes** [comment]
You know, I understand your point. But I am very serious, please do not remove this feature !
If you need some help to maintain the app I can try help a bit

**Comment by rezazarchi** [comment]
I think this is necessary because on newer Android versions it should show notification and run as a foreground service.
