### ISSUE TITLE
immediate expunge doesn't expunge

### ISSUE THREAD

**Issue by AEaut** [thunderbird/thunderbird-android#5345]
If an imap account in v5.734 is configured with...:
- no folder for deleted/deleting messages
- on deleting (a) message(s), also delete it/them from the server
- immediate expunging after moving etc. of (a) messages(s)

then i would expect that...:
- first: the message(s) is/are marked as deleted (on server)
- second: displaying of the referred message(s) in k-9's UI as "is-marked-as-deleted" (if that is available at all?) being skipped
- third: the message(s) is/are physically deleted (from server and from k-9's cache)

but instead k-9 does not perform the last (expunge) step (at least not successfully. I didn't yet check a server logfile on whether expunging was tried but failed, or whether it was not tried at all. all imap servers, on which my accounts are run, are dovecot on ubuntu.).

However, if k-9's config is set to expunge-on-each-sync, then it's done successfully with the first manually triggered sync-command after the previous message-deletion-command.

That's why I guess that there is no basic expunge-compatibility-problem between k-9 and the servers, but instead a problem with k-9's execution of its immediate-expunge-setting.

**Comment by cketti** [comment]
Same thing happens when updating/replacing a draft. Will be fixed in 5.735.

**Comment by cketti** [comment]
Side note: In the future please use the issue template. Triaging is much easier if all reported issues follow the same structure.
