### ISSUE TITLE
Multiple Notifications (at least on Gmail Account) 

### ISSUE THREAD

**Issue by Maetts** [thunderbird/thunderbird-android#5365]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

If you are unsure whether or not you have found a bug please post to the support forum instead: https://forum.k9mail.app

**Describe the bug**
Push works not properly with Gmail. Multiple notifications for one mail and push works only when set to all or 1st and 2nd class folders. 

**To Reproduce**
1. Set up K9 with a Gmail Account 
2. Use IMAP push for all or 1st and 2nd class folders  (only 1st class mails don't come in) 
3. Wait for incoming mail
4. See multiple (three) notifications for one single mail

**Expected behavior**
One notification per mail and push working also with only 1st class folders (as ir does both for my other mail accounts in K9) 

**Screenshots**
See attached 
![Screenshot_20210625_074725](https://user-images.githubusercontent.com/57272390/123376345-9fe94480-d58a-11eb-8c47-8a3e1bdac5fc.jpg)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.736
 - Android version: 10
 - Device: Huawei P30 Pro New Edition 
 - Account type: IMAP push for all or 1st and 2nd class folders  (only 1st class mails don't come in)

**Additional context**
N/a

**Logs**
N/a

Thanks!

**Comment by cketti** [comment]
Sounds like a configuration issue. The default Push class of a folder is "2nd Class". By setting "Push folders" to "1st and 2nd Class folders" you enable Push for all folders. Gmail has the special "All mail" folder. When accessing a Gmail account via IMAP labels map to folders. So most messages will be downloaded twice or more (once for each label, and then from the "All mail" folder). K-9 Mail doesn't know all of these are actually the same message.
It looks like you sent a message to yourself. So from K-9 Mail's perspective there are new messages in the "Inbox", "Sent", and "All Mail" folders.

Set `Settings > [Account] > Fetching mail > Push folders` to `Only 1st Class folders` and set `Manage folders > [Folder] > Folder push class` to `1st Class`.

**Comment by Maetts** [comment]
Okay, this is plausible. Just one question that I really can test. Where do I find the push folders in [Folder]? 
![Screenshot_20210625_124317](https://user-images.githubusercontent.com/57272390/123413601-41848c00-d5b3-11eb-9c6a-9369b54e72c6.jpg)

**Comment by cketti** [comment]
"Manage folders" is an entry in the side drawer, right above "Settings". I used "[Folder]" as a placeholder for the folder name you want to configure.

<img src="https://user-images.githubusercontent.com/218061/123418370-46e4d500-d5b9-11eb-9b95-dd6a1b477994.png" alt="Manage folders screen" width=350> <img src="https://user-images.githubusercontent.com/218061/123418418-5106d380-d5b9-11eb-89ef-4a04342814cc.png" alt="Folder settings screen" width=350>

**Comment by Maetts** [comment]
Awesome, thank you! Wasn't aware of that. Works perfectly. I will support your work definitely.
