### ISSUE TITLE
5.736 no signs of life on Android 10 - huawei

### ISSUE THREAD

**Issue by gh-ix** [thunderbird/thunderbird-android#5367]
Installed 5.736 from GH apk download in secondary user account.  No error while installing.
Launching K-9 Mail doesn;t give _any_ feedback - no error, no action at all.
  
**Environment (please complete the following information):**
 - K-9 Mail version: 5.736
 - Android version: 10.1.0.182
 - Device: Huawei Mate Pad pro (MRX-W09)
 - Account type: n/a

**Comment by cketti** [comment]
Please record a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
Skip the filtering by PID and just do `adb logcat -d > k9-log.txt`
