### ISSUE TITLE
Introduced foreground service is bad for battery

### ISSUE THREAD

**Issue by hannesa2** [thunderbird/thunderbird-android#5372]
With https://github.com/k9mail/k-9/pull/5338 you introduce a foreground service. That's bad for battery optimizations !

* Why you don't use https://developer.android.com/reference/android/app/job/JobScheduler.html to do your stuff periodically ? 
* Are there any plans to remove this foreground service ? 

Normally I would make a pull request to solve this, but I learned, that it makes no sense to cleate pull requests here. That's why it relays on you.

K9 was a good email client, but from time to time it is "improved" to a worsened state 
* No overview of unread emails
* Keeps phone always on

**Comment by cketti** [comment]
Are you aware that you come across as very confrontational? When I read a message like this my willingness to answer questions drops to near zero. Usually I'm very happy to answer questions about the technical decisions I made.

K-9 Mail is only using a foreground service when using Push (IMAP IDLE). To be notified about changes using the IDLE command the app needs to keep a TCP connection open. To keep a TCP connection open, we need Android to not kill our process. The way to achieve that is to use a Service. With the restrictions on background services in recent Android versions, a foreground service seemed like the only way to go. 
A foreground service alone does not prevent the device from going to sleep. K-9 Mail does not hold a wake lock while waiting for data to be sent over the TCP connection. During this time the device can go to sleep. The OS will wake up the app once new data arrives. At this point K-9 Mail acquires a wake lock, does its thing, and then releases the wake lock again. 

For periodic polling K-9 Mail uses WorkManager and not a foreground service.

**Comment by hannesa2** [comment]
> a foreground service seemed like the only way to go

I don't agree. As I already wrote https://developer.android.com/reference/android/app/job/JobScheduler.html seems to be an alternative way

Current solution with forground services

* pro: easy to do
* con: a background notification is shown 👎

Solution with JobScheduler

* pro : no background notification 👍
* con : more coding

**Comment by cketti** [comment]
Using `JobScheduler` does not prevent your process from getting killed when there's low memory. It also does not prevent the OS from applying Doze restrictions when no Job is running. One of these restrictions is disabling all network traffic to the app. This would prevent data from the mail server arriving and waking up the app.

**Comment by hannesa2** [comment]
It's not a question of memory , it's a question of battery optimization.
`JobScheduler` de-bounces the wake ups of the device. And yes, there is more work to apply it.

**Comment by cketti** [comment]
You seem to ignore the main requirement that I outlined in my first comment. It's not a problem of doing periodic/scheduled work (i.e. what `JobScheduler` does). It's about keeping a TCP connection open in order to be notified about new messages.

**Comment by hannesa2** [comment]
Indeed that's the more work, I wrote about, to handle the lost connection

**Comment by schildbach** [comment]
On top of what @cketti said, JobScheduler/WorkManager limit the runtime of your workload to (I think) 20 minutes. If you have a long/endless running process, services are the only way to go.

**Comment by hannesa2** [comment]
If it's 20 minutes, it's not important, because you maybe trigger the job every minute.

I would love to read: "hmm, that's probably an issue, let's have a deeper look into it...." instead of explain, why it's like it is.

Sometimes it's better don't tell the solution, because someone want to find the solution by him self.

### Tell the story different: 

I observe K9 is the only communication app, which uses a foreground service. No WhatsApp, no Slack, no Telegram, no Signal, (10 more)..... uses such a foreground service with the same allways-on-issue.

Either all are using Firebase (which comes without this limitation) or all these apps are using something different ?

Happy Google searching !

**Comment by cketti** [comment]
I agree that having to display an ongoing notification is unfortunate. A way to avoid that would be very welcome. So far nobody I talked to was able to provide an alternative that works for K-9 Mail (i.e. something other than FCM).

You list a couple of communication apps. As far as I know all of them are using Firebase Cloud Messaging. Two of them are open source apps. So you could have checked for yourself ([Telegram](https://github.com/DrKLO/Telegram/blob/dd2b001b957520d1219775f7c347d640e4633d1d/TMessagesProj/src/main/java/org/telegram/messenger/GcmPushListenerService.java), [Signal](https://github.com/signalapp/Signal-Android/blob/62ee411901eadc870bbfbe125c08b395022072ae/app/src/main/java/org/thoughtcrime/securesms/gcm/FcmReceiveService.java)).

It doesn't feel like you're engaging in a good faith argument. So I'm closing this issue.

If anyone can come up with a prototype that reliably works without using a foreground service, I'm more than happy to change our implementation.

**Comment by gdt** [comment]
One can trivially configure the notification to "Low: No sound or visual interruption" so it is not displayed in the status bar, although it does show up in the pull-down list.   I currently have such notifcations for Conversations, Signal, and Fedilab.   I think it's totally reasonable for a Firebase refusenik to have one also for K-9.   And I think it's good that K-9 doesn't use non-Free privacy-problematic services like FCM.   I think it's pretty clear that any app which reliably and promptly (a few seconds) receives events in the background on recent Android is either using a foreground service or FCM.   At least so far I haven't seen a counterexample.  (On older Android without aggressive vendor app-killing, disabling battery optimization seems enough to keep 5.2xx K-9 from being killed, but I get it that this doesn't work on more recent Android versions.)

Longer term, and much harder, there is work on openpush/gotify, basically similar to FCM that you can self-host and point all your apps at.  I suspect that over the next year there will be code to steal and integration with dovecot, and this will be feasible, but it's a complementary approach, not a replacement for doing IMAP IDLE correctly.

I think I'm part of a large silent majority quietly cheering on cketti@ as IMAP IDLE support returns, not speaking up because I have nothing constructive to add.  To me, courtesy to fellow open source people means treading very lightly in taking up brain cycles.

-gdt (K-9 user since 2013)

**Comment by hannesa2** [comment]
If you all are happy with the current solution it's fine for you. But I'm not. 
Finally, I show you the recommendation from Google before we all accept that our phone is empty at the end of the day a little bit earlier.
 
### foreground-services
https://developer.android.com/guide/components/foreground-services
![image](https://user-images.githubusercontent.com/3314607/123993462-bc431200-d9cc-11eb-90f6-bacf75fa666f.png)

### background_tasks
https://developer.android.com/guide/background#categories_of_background_tasks
![image](https://user-images.githubusercontent.com/3314607/123993642-e5fc3900-d9cc-11eb-889c-1b89169dcc64.png)

### workmanager
Every task that is not directly connected to a user interaction and can run at any time in the future can be deferred. The recommended solution for deferred tasks is `WorkManager`.

https://developer.android.com/topic/libraries/architecture/workmanager

`Workmanager` under the hood
<img width="865" alt="image" src="https://user-images.githubusercontent.com/3314607/123994036-47bca300-d9cd-11eb-99a7-80c101b027b3.png">

I'm not sure if a repeat re-connect on scheduled task is a big issue (**This is the main question**). 
And yes, it could be that a email comes some minutes later, when you don't use your phone.

**Comment by MuntashirAkon** [comment]
After updating K-9 Mail yesterday, and its battery usage is already 42%. I've other apps (Signal, Telegram, etc.) which also use foreground service but I've never seen this kind of battery usage before. My device is Lineage OS running Android 11.

**Comment by cketti** [comment]
@MuntashirAkon: Please open a new issue and provide all the information asked for in the issue template, especially the debug log.

**Comment by MuntashirAkon** [comment]
> Please open a new issue and provide all the information asked for in the issue template, especially the debug log.

Okay, when I'm free. Do I need to install a debug build or something, assuming that the release versions do not produce any debug log?

**Comment by MuntashirAkon** [comment]
@cketti: The issue has been fixed in 5.802. Thanks.
