### ISSUE TITLE
"Listening for new emails" notification

### ISSUE THREAD

**Issue by birdie-github** [thunderbird/thunderbird-android#5375]
I haven't touched any K-9 settings yet after the latest update (5.737) I see this notification at all times. Of course I can hide it but I wonder why it was added in the first place.

And if it's really needed why clicking on it does nothing? At least add some functionality to it like e.g. opening the app.

I can also think of adding buttons like e.g. "Write an email", "Force recheck messages", "Open settings".

**Comment by cketti** [comment]
You're most likely seeing it because you had Push enabled in the past. See [How to configure Push?](https://forum.k9mail.app/t/how-to-configure-push/1102)

**Comment by life777eternal** [comment]
Is that "Listening for new emails" persistent notification now replacing the previous "checking for new email" notification that popped up and out repeatedly depending on now many email accounts setup, causing the notification drawer to scroll 📜 up 👆🏻 🆙 kind of by itself? Which was kind of annoying when looking through the notifications. 


![obscura1625875932673](https://user-images.githubusercontent.com/25623649/125146318-6a903b00-e0e2-11eb-8d32-16872f8c6860.jpg)

**Comment by cketti** [comment]
@life777eternal: It's not. See #5332.

Please use the [forum](https://forum.k9mail.app/) for support requests.
