### ISSUE TITLE
Search UI needs improvements in landscape mode

### ISSUE THREAD

**Issue by rezazarchi** [thunderbird/thunderbird-android#5384]
**Describe the bug**
there is an empty space right side of the search bar when we rotate the phone to landscape

**To Reproduce**
1. Click on the search icon
2. Rotate phone

**Expected behavior**
Search bar should be match parent

**Screenshots**
![Screenshot_1625561954](https://user-images.githubusercontent.com/8654398/124573938-3e18bc80-de5f-11eb-876d-541849474bd3.png)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.738-SNAPSHOT
 - Android version: 11
 - Device: Emulator and Samsung Galaxy
 - Account type: IMAP

**Comment by MasterBlaster99** [comment]
@cketti  can i pick this issue ?

**Comment by cketti** [comment]
@MasterBlaster99: Sure. But I doubt it's an easy fix. K-9 Mail is currently using this Android mechanism: https://developer.android.com/reference/android/app/Activity#startSearch(java.lang.String,%20boolean,%20android.os.Bundle,%20boolean)

**Comment by rezazarchi** [comment]
Yeah, that's right. I tried lots of solutions, and they didn't resolve this problem. But I replaced it with SearchView. I used ```xml app:actionViewClass="androidx.appcompat.widget.SearchView"``` for the search option. It has a little bit different implementation in MessageList class, but I can make a pull request if you are OK with that.

**Comment by cketti** [comment]
@rezazarchi: A pull request would be welcome.
