### ISSUE TITLE
Device not sleeping with Push enabled

### ISSUE THREAD

**Issue by N1mu3h** [thunderbird/thunderbird-android#5397]
Whenever I enable Push the device doesn't sleep at all. My awake time was 5 hrs 10 min at 15:40 today when I enabled Push again - now it’s 17:00 (an hour 20 min later) and the Awake time is 6 hrs 20 minutes.
Those previous 5 hrs+ were from over 5 days uptime without Push enabled, so it’s clearly not sleeping much at all now.
![k9smaller](https://user-images.githubusercontent.com/33838834/125101550-9e676280-e0da-11eb-9ab6-1c542d4aee86.png)

**To Reproduce**
1. Enable Push
2. Write down Awake Time from FKM
3. Wait an hour or 2
4. Check Awake time again

**Expected behavior**
Device should sleep in between getting emails

**Environment (please complete the following information):**
 - K-9 Mail version: Beta 5.738 and previous version
 - Android version: OOS 10
 - Device: OP 7
 - Account type: IMAP

**Logs**
[k9-log.txt](https://github.com/k9mail/k-9/files/6792367/k9-log.txt)

**Comment by cketti** [comment]
Thanks for the log.

It looks like an optimization that tries to minimize the number of wakelocks the app acquires doesn't work as intended on your device.

**Comment by cketti** [comment]
Can you please test if the following APK works better for you?

[k9mail-push-wakelock-fix.zip](https://github.com/k9mail/k-9/files/6792672/k9mail-push-wakelock-fix.zip)

**Comment by N1mu3h** [comment]
Of course, I'll let you know either later today or then tomorrow morning - thanks :)

**Comment by N1mu3h** [comment]
> 
> 
> Can you please test if the following APK works better for you?
> 
> [k9mail-push-wakelock-fix.zip](https://github.com/k9mail/k-9/files/6792672/k9mail-push-wakelock-fix.zip)

I've updated with the test version and enabled Push half an hour ago and so far the Awake Time hasn't changed ... I'm carefully optimistic that you've fixed it. I'll update you again tomorrow, but so far it's looking great!

Thank you sooooo much for the quick fix, have a great evening :)

**Comment by N1mu3h** [comment]
It's definitely fixed - I had 10 minutes awake time in over 12 hrs so it's back to normal.

Thanks again :)
