### ISSUE TITLE
"receiving mails" message remains visible

### ISSUE THREAD

**Issue by punk-t** [thunderbird/thunderbird-android#5402]
**Describe the bug**
Since version 5.739 a message about receiving mails stays visible. 
  - Forcibly closing and restating the app doesn't help
  - clearing cache doesn't help
  - reinstalling app doesn't help

**To Reproduce**

1. Install app
2. Configure account
3. Receive mails
4. Notice message staying visible

**Expected behavior**
Message should only be shown while receiving mails, disappear afterwards

**Screenshots**
![2021-07-11 16 21 00](https://user-images.githubusercontent.com/11180677/125199726-e7005680-e267-11eb-9ddd-c837397755a3.png)

**Environment (please complete the following information):**
 - K-9 Mail version:  5.739
 - Android version: old. Very old. Already used by Neanderthals (don't know better, sorry)
 - Device: Samsung Galaxy Note Pro (SM-P900)
 - Account type: IMAP

**Comment by cketti** [comment]
Looks like the German translation of that message should be improved. See https://forum.k9mail.app/t/how-to-configure-push/1102

**Comment by punk-t** [comment]
According to your information I tested turning off push folders. App killed and restarted, but notification is shown immediately after restarting.

**Comment by cketti** [comment]
Did you change `Einstellungen > [Konto] > E-Mails abrufen -> Push-Ordner` to `Keine Ordner` for all accounts?

**Comment by punk-t** [comment]
Yes, I did. I did it twice again and now behaves as expected. Who knows what I did first time.
But I also now (at last) read the whole article about those notifications. It is indeed an unlucky german translation from `listening ...` to `neue E-Mails abfragen` but I spontaneously havo no better ☺️

**Comment by cketti** [comment]
I changed the English text to "Waiting for new email" and left a note for translators to make it not appear like the app is doing active work when this notification is displayed.
