### ISSUE TITLE
Unread e-mails highlighted 

### ISSUE THREAD

**Issue by blub4747** [thunderbird/thunderbird-android#5411]
Hi community,
In my old version of K9 (5.600) unread e-mails used to be highlighted in grey or white.
Also in the overall folder view all unread e-mails across all folders used to be displayed with numbers of the unread e-mails.
Can I setup the new version of K9 to function like the  previous one ?
Thx, blub4747

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
