### ISSUE TITLE
Samsung s21

### ISSUE THREAD

**Issue by g270546a** [thunderbird/thunderbird-android#5416]
K9 will not work on a Galaxy S21

**Comment by hans109h** [comment]
It works fine on my Galaxy S21.  You're going to have to provide a lot more information.

State here:
https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by g270546a** [comment]
So it'll work if you set it up new.  It will not work if you import data from an S9 phone.  

On July 16, 2021 7:18:19 AM MDT, hans109h ***@***.***> wrote:
>It works fine on my Galaxy S21.  You're going to have to provide a lot
>more information.
>
>State here:
>https://github.com/k9mail/k-9/wiki/LoggingErrors
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/5416#issuecomment-881443597

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hans109h** [comment]
You should export your settings directly from K-9 on the S9.  Then install K-9 on the S21, then import your settings into K-9 on the S21.

**Comment by g270546a** [comment]
Yes that's what didn't work.  After importing K9 would no longer open on the S21

On July 16, 2021 7:55:57 AM MDT, hans109h ***@***.***> wrote:
>You should export your settings directly from K-9 on the S9.  Then
>install K-9 on the S21, then import your settings into K-9 on the S21.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/5416#issuecomment-881469101

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hans109h** [comment]
Could be a lot of things so you'll have to debug.  One thing recently was push getting turned back on.  Perhaps you have an older version of K-9 on your S9 and the settings have push turned on but the account doesn't work with push.  I understand that can cause a new version of K-9 to crash.  If that is the problem a fix would be to set folderPushMode to 'none'.

**Comment by cketti** [comment]
@g270546a: You went through all the trouble of creating a GitHub account and then didn't provide any information that could be useful to find and fix the bug you're experiencing. 
Please create a new issue and fill out the issue template for bugs. That information helps us to massively narrow down what the problem could be.
