### ISSUE TITLE
Crash upon deleting emails

### ISSUE THREAD

**Issue by dvlierop** [thunderbird/thunderbird-android#5420]
K9 mail crashes frequently, seemingly related to me deleting emails. The is sometimes a bit of delay though between deleting the emails and the crash. I've been able to reproduce this twice in the past few minutes, see the attached logs.

I'm running 5.738, Android 10, on a Nokia 7.2

**Comment by dvlierop** [comment]
[k9-log.txt](https://github.com/k9mail/k-9/files/6845942/k9-log.txt)

**Comment by dvlierop** [comment]
[k9-log2.txt](https://github.com/k9mail/k-9/files/6845946/k9-log2.txt)

**Comment by dvlierop** [comment]
Let me know if there's anything else that I can provide!

**Comment by dvlierop** [comment]
Duplicate of #5408?

**Comment by cketti** [comment]
A solution for #5408 should prevent the crash you're experiencing. But it wouldn't fix the underlying cause. The crash you're experiencing has been around for quite a while for a low percentage of users. But I have no idea what is causing it.

**Comment by dvlierop** [comment]
Good to know that I'm not the only one experiencing this bug. I'm sure this will get fixed some day. Keep up the good work!
