### ISSUE TITLE
Push-Notification constantly renewing

### ISSUE THREAD

**Issue by Bapf** [thunderbird/thunderbird-android#5421]
**Describe the bug**
Since the change to the "Waiting for new emails" notification in 5.740 the notification constantly get's triggered anew. It isn't noticeable on a phone, but when having a smartwatch connected to the phone, this watch shows the notifications multiple times a hour as new notification.
Up to version 5.739 this wasn't the case.

**To Reproduce**
1. Enable Push in K9
2. Connect a Smartwatch to your phone (in my case a Fossil Hybrid HR)
3. Enjoy (semi)constant vibrations on the watch.

**Expected behavior**
A notification the only changes when it's status changes (i.e. when connectivity is lost or restored) like it was up to version 5.739.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.740
 - Android version: 10
 - Device: OnePlus 5T & Fossil Hybrid HR
 - Account type: IMAP

**Additional Notes**
I know that is quite a "niche" problem. :(

**Comment by cketti** [comment]
It's probably a mistake that the notification ends up on the watch in the first place. 

It does feel like a problem not many people will have. So I'd rather release a new stable version first, then fix this bug afterwards. Fixing notification bugs will be a focus then anyway.

**Comment by glawrence** [comment]
I have sync set to manual. I can pull down to sync and get 5 new emails for example and more phone makes a ping or new mail sound, which is all good. When I press next message I get another ping sound and so get five ping sounds as I navigate through my messages. Could this be related?

**Comment by cketti** [comment]
@glawrence: No, that's a different type of notification. Please create a new issue.

**Comment by mnlipp** [comment]
This is definitely not a niche problem! I have a constant notification "@" regarding push being used on my tablet (couldn't check yet but it will probably be on my phone as well after the update). There is no way to get rid of it except disabling push, which is ridiculous, of course.

**Comment by cketti** [comment]
The notification is configured as ["local only"](https://github.com/k9mail/k-9/blob/591af9cdd552688dfefbfb278d5c0658f130d2ae/app/core/src/main/java/com/fsck/k9/notification/PushNotificationManager.kt#L68) which should prevent it from being displayed on the watch. Additionally it is set to [silent](https://github.com/k9mail/k-9/blob/591af9cdd552688dfefbfb278d5c0658f130d2ae/app/core/src/main/java/com/fsck/k9/notification/PushNotificationManager.kt#L66) (ignoring the sound/vibration settings of the notification channel).

The documentation says "local only" is only a hint. So I guess the notification showing up on the watch is not strictly a bug then. But it's unclear why the hint is ignored. I don't see any reason why the notification should create a vibration. You should report this as a bug in the Wear OS app.
The Wear OS app probably allows you to configure which notifications should be displayed on the watch. Check if you can disable the notification that way.

I don't know what else we could do to avoid the behavior you're seeing.
