### ISSUE TITLE
`format=flowed` is ignored in inbox (but works for the same e-mail in the sent folder)

### ISSUE THREAD

**Issue by MaxGyver83** [thunderbird/thunderbird-android#5424]
**Describe the bug**
I have sent an e-mail with the text example from @qwertfisch (issue #582) to myself (using _Thunderbird_). When I open this e-mail in _K-9 Mail_, it looks like this:
![image](https://user-images.githubusercontent.com/13970628/126558382-2cd2ca68-a2b2-4a6a-a719-6e71b24e1d57.png)
It looks like `format=flowed` is being ignored. The _Content-Type_ in the header is `text/plain; charset=utf-8; format=flowed`.

But this is strange: Since I sent this e-mail to myself, this e-mail is also in the _Sent_ folder. And there, it's displayed as expected:
![image](https://user-images.githubusercontent.com/13970628/126558986-a66dcc62-551d-4cb0-9f94-b7d98611cf8d.png)

Any idea why this e-mail in the inbox isn't displayed with `format=flowed`?

**To Reproduce**
See the mails attached (e-mail sources exported with Thunderbird).

**Environment:**
 - K-9 Mail version: 5.600
 - Android version: 9
 - Device: OnePlus 3T
 - Account type: IMAP

[sent-format-flowed-test.txt](https://github.com/k9mail/k-9/files/6860614/sent-format-flowed-test.txt)
[inbox-format-flowed-test.txt](https://github.com/k9mail/k-9/files/6860615/inbox-format-flowed-test.txt)

**Comment by MaxGyver83** [comment]
I made another test:
When I send the same e-mail from another account (hosted by Strato) to the mail address used above (web.de), the e-mail is displayed correctly in the inbox.

E-mail source:
[inbox-fomat-flowed-test-from-strato-account.txt](https://github.com/k9mail/k-9/files/6860708/inbox-fomat-flowed-test-from-strato-account.txt)

So I guess, it's not a bug in K-9 Mail. Does web.de corrupt my outgoing e-mails?

**Comment by cketti** [comment]
The message body in `inbox-format-flowed-test.txt` is encoded using `quoted-printable`, but the spaces at the end of the lines, necessary for format=flowed to work properly, have been stripped. So whoever applies this encoding is doing it wrong/does not support format=flowed. It's possible that Thunderbird is doing this when sending the message, but not when uploading to the Sent folder. web.de would be my first guess, though.

It's not a bug in K-9 Mail. You'll notice that Thunderbird doesn't display `inbox-format-flowed-test.txt` correctly either.

**Comment by MaxGyver83** [comment]
Thanks for you analysis and sorry for posting an issue not caused by K-9 Mail.

In case others have the same problem and find this issue:

I wanted to find out if my mails get corrupted because of a wrong setting in Thunderbird. I couldn't find a way of using `Content-Transfer-Encoding: 8bit` for my _web.de_ account. So tried it again, this time sending the mail via `msmtp` (command line) where I can write the e-mail header manually:

```
$ msmtp m...@web.de
Subject: format=flowed with msmtp using 8-bit
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

This is paragraph text that is meant to be flowed across several lines. 
However, the sending mailer is converting it to format=flowed text at a 
width of 79 characters, which causes it to look like this when shown on 
a smartphone with only 50 character lines. Non-ASCII: äöüß👍.
```

This e-mail was received with `Content-Transfer-Encoding: quoted-printable`, nevertheless. So it seems to be _web.de_ who decides over the _Content-Transfer-Encoding_ and they also seem to be those corrupting my e-mail content (because I don't think that both _Thunderbird_ and _msmtp_ mess up the mails on the client side).

**Comment by da2x** [comment]
@MaxGyver83 Did you send an email to another account? To check if they modify it on send or on arrival? Did you contact your email provider about the issue? Did they respond? I’m curious about your experience dealing with this email provider causing this kind of compatibility problem.

**Comment by MaxGyver83** [comment]
@da2x : Yes, same problem when I send an e-mail from web.de to an account at strato.de.

I just sent a message to the web.de support team. I'll update you about their response.

**Comment by MaxGyver83** [comment]
@da2x : Just FYI: The web.de support never answered.
