### ISSUE TITLE
Push not working with Yahoo IMAP mail ID

### ISSUE THREAD

**Issue by Ktn07** [thunderbird/thunderbird-android#5429]
Hello

I have setup my Yahoo IMAP account with push but new mail notifications are not recieved instantly.

I have already switched off all battery optimization on my device. 

Reduced the push folder number also have added folder with classes.

Still the push notification are received instantly, the notifications are received when pull happens after every 15 minutes.

Environment 

 - K-9 Mail version: 5.741
 - Android version: 10
 - Device: Redmi Note 7 Pro
 - Account Type : IMAP

Thank you.

@cketti : Thank you for developing and maintaining such a wonderful app. Appreciate all your efforts.

**Comment by cketti** [comment]
Yahoo does not support IMAP IDLE.

**Comment by Ktn07** [comment]
What to do then ?, it works with another android app Edison Email. But I want it to work with K 9 I just love it and dont want to leave it

**Comment by cketti** [comment]
Either use another app or switch to another email provider. I have no intention of adding support for a push mechanism that is not an open standard.

**Comment by Ktn07** [comment]
@cketti : Thanks for all your support will move to switch to another app
