### ISSUE TITLE
Support PEP's way of hiding mail subject in body

### ISSUE THREAD

**Issue by pravi** [thunderbird/thunderbird-android#5430]
**Is your feature request related to a problem? Please describe.**
Mail sent by pep always have pep in subject because the real subject is in message body.

**Describe the solution you'd like**

I think k9 mail should read the body and replace the subject locally with the subject in body.

**Describe alternatives you've considered**
Now the entire header is shown as body which is weird.

**Additional context**

The message body now has the following,

<pre class="k9mail" style="background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important; background-color: rgb(0, 0, 0); color: rgb(243, 243, 243); white-space: pre-wrap; overflow-wrap: break-word; font-family: sans-serif; margin-top: 0px; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">pEp-Wrapped-Message-Info: OUTER<br style="background: black !important; color: rgb(243, 243, 243) !important;"><br style="background: black !important; color: rgb(243, 243, 243) !important;"></pre><p style="background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important; background-color: rgb(0, 0, 0); color: rgb(243, 243, 243); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 2.5em; margin-bottom: 1em; border-bottom: 1px solid rgb(0, 0, 0);"></p>

From: | xxx
-- | --
Pirate Praveen
Fri Jul 23 18:28:24 GMT+05:30 2021
Re: ...

<pre class="k9mail" style="background-image: initial !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important; background-color: rgb(0, 0, 0); color: rgb(243, 243, 243); white-space: pre-wrap; overflow-wrap: break-word; font-family: sans-serif; margin-top: 0px; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">pEp-Wrapped-Message-Info: INNER<br style="background: black !important; color: rgb(243, 243, 243) !important;"></pre>

**Comment by kewisch** [comment]
There was recently a fix to show [...] for encrypted subjects, which I believe covers this. If you could try Thunderbird for Android Beta and see if it works well I'd appreciate.
