### ISSUE TITLE
Launcher icon lost between v5.600 and v5.800 (despite alias?)

### ISSUE THREAD

**Issue by ocram** [thunderbird/thunderbird-android#5432]
Congrats on reaching v5.800, and thanks for your work!

On a Motorola Moto G5 Plus (Android 8.1), after upgrading from v5.600 to v5.800 via Google Play, the launcher icon is gone.

But it seems you already have an `<activity-alias>` in place in `app/k9mail/src/main/AndroidManifest.xml`. Perhaps it needs a label? Could also be specific to the Android build by the manufacturer (for 8.1).

**Comment by philip-n** [comment]
I saw the same behavior on a Motorola G5+ (icon vanished from launcher). Cannot add further details, sorry.

**Comment by cketti** [comment]
Your launcher has probably deleted the shortcut when it detected it no longer worked. So changing the activity-alias now is unlikely to fix things. Closing this issue.
