### ISSUE TITLE
Add scrollbar to "Choose Folder" screen

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#5438]
The `RecyclerView` used to display the folder list in `ChooseFolderActivity` doesn't show a scrollbar, but it should.

**Comment by AvineshTripathi** [comment]
I want to try fixing the bug, can I work on this ?

**Comment by cketti** [comment]
@AvineshTripathi: Sure

**Comment by AvineshTripathi** [comment]
@cketti i m facing problem with building the project can you help me ?

**Comment by cketti** [comment]
@AvineshTripathi: I can try. Please post your problem/question in the discussions section: https://github.com/k9mail/k-9/discussions/categories/development-talk
