### ISSUE TITLE
Unified Inbox doesn't show unread count

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#5443]
There's no unread count displayed for the Unified Inbox in the drawer.

EDIT: The starred count (see #5519) is also missing.

**Comment by andrewfg** [comment]
In #5519 we still have a pending issue to add both starred and unread counts to the Unified Inbox display.

In this context, I would also like to suggest that the **Unified Inbox** drawer item should **not** be displayed in the navigation drawer **Folder View**, but rather it should be displayed in its "Account View" -- see mock up below.

Reason is that "Unified Inbox" is not specific to any one account, and rather has the character of an Account itself.

![image](https://user-images.githubusercontent.com/893994/130484922-831f5f77-8e97-453c-9573-cb693a4e951c.png)

**Comment by cketti** [comment]
@andrewfg: This is unrelated to the missing unread count. Please create a new issue for this feature request.

**Comment by andrewfg** [comment]
https://github.com/k9mail/k-9/issues/5614
