### ISSUE TITLE
Version 5.800 is not working on Android 12 Beta 3

### ISSUE THREAD

**Issue by ouafnico** [thunderbird/thunderbird-android#5446]
**Describe the bug**
After updating on 5.800, k9mail is not working correctly on Android 12 Beta 3
K9mail is showing the list of mails, without icons on it, and clicking on one of them is freezing the application.

The previous solution to remove updates of webview is not working anymore. I tried to remove updates, reboot the phone, it's always the same.
I will try to rollback k9mail version.

**To Reproduce**
1. You need to use android 12 beta 3
2. Open k9mail
3. Icons of emails are not shown correctly
4. Clic on an email
5. App should crash during animation on opening mail
6. Mail will not be shown, app is freezing

**Environment (please complete the following information):**
 - K-9 Mail version: 5.800
 - Android version: Android 12 Beta 3
 - Device: Google pixel 4a 5G
 - Account type: IMAP

**Comment by njeyaakili** [comment]
fwiw - i haven't seen any issues with 5.8 (or any of the recent 5.7x betas) with any of the android 12 betas on a pixel 3a and a 5 (5g).

**Comment by ouafnico** [comment]
After :
- uninstalling updates and disabling webview
- rebooting
- activating webview
- rebooting
- installing updates of webview

I successfully get back k9mail.
