### ISSUE TITLE
Broken multi inbox UI

### ISSUE THREAD

**Issue by lifebarier** [thunderbird/thunderbird-android#5452]
New UI is completely broken/useless for multiple inboxes:

I have multiple accounts and some of them are much less important than others. Old view allowed me to see if there are emails in important boxes and maybe check or ignore less important/more_spammy_ones.
Now I am forced to switch through all boxes to check them (unified box does not help since spammy boxes will bury important emails). And yes, switching to different inboxes is difficult - UI seems to accommodate 3 accounts that can be switched to fast-ish (circles in UI) while having more accounts means having to use drop-down.

https://forum.k9mail.app/t/old-presentation/1360

UI needs "unifued grouped inbox" where you can see number of new emails in each inbox with ability to refresh them all with one click.

This is bug not a feature request because it used to work well.

**Comment by scoder** [comment]
I don't agree that it's "completely useless", but it's certainly much less informative. I can now move between accounts by swiping from the left, ok, I figured that out, but the view doesn't tell me much about the accounts. Previously, all information was just there on the main entry page. Now it's just the account-name + what? number of unread messages? probably. Just getting back the old amount of information would be really nice.

**Comment by timw01** [comment]
Has significantly increased the user input required for normal operation of multiple accounts, even more so if you have more than 3 accounts. This is attracting a large number of negative comments in the Play Store so probably worth resolving.

**Comment by sebu06** [comment]
Hi,
I have to agree that it is in fact completely unusable. I just removed 5.8 and went back to 5.6. I really need the overview as stated by the first author. In addition, I think the UI redesign was a step back rather than an improvement - at least for me the old UI looked better (e.g. now the subject and message are separated less clearly and the dark colour ist greyish in the inbox view, but black in the message view) and made it easier to grasp information and to navigate. I really liked the slim view with the thin, subtle color bars at the side. Also, I use folders a lot and using them full width in the main window is way better than in the small sidebar. my default action was: 
Starting up K9 - see at a glance which account has new mails, select it by clicking the new message icon, resulting in all unread mails from this account from all folders (they are sorted in server side using sieve), ignoring the 10 new messages in my spammy account (total: 1 tap)

Now it is:
Starting up K9, opening side bar, opening the drop down, selecting the account (do this 5 times until I have the information for all accounts) scroll through the list of folders and select one by one -> 20 taps 

I will stick with 5.6 for now and most likely will, because the old UI might look a little bit outdated but provided a way better user experience.

**Comment by jult** [comment]
I disagree on anything looking outdated in v 5.6*. That is just something stubborn developers made up in order to greenwash this pathetic new UI. Nobody with a brain actually using email would prefer this garbage over the older look. It's over for k9. Someone should fork the older code, insert the back-end upgrades and release a truely new version, not this disaster of a 'redesign'.

**Comment by sebu06** [comment]
> I disagree on anything looking outdated in v 5.6*. 

I would completely agree with you, what I wanted to say is the obviously for some people (not me) it might seem to look a little bit outdated. I had exactly the same idea of forking and updating only the back end changes. However, since I don't know this project I have no idea regarding the complexity of this. But I cannot see myself using the new version, it simply looks like every other mail client and has lost all it well thought through advantages

**Comment by AndySchroder** [comment]
> Hi,
> I have to agree that it is in fact completely unusable. I just removed 5.8 and went back to 5.6. I really need the overview as stated by the first author. In addition, I think the UI redesign was a step back rather than an improvement - at least for me the old UI looked better (e.g. now the subject and message are separated less clearly and the dark colour ist greyish in the inbox view, but black in the message view) and made it easier to grasp information and to navigate. I really liked the slim view with the thin, subtle color bars at the side. Also, I use folders a lot and using them full width in the main window is way better than in the small sidebar. my default action was:
> Starting up K9 - see at a glance which account has new mails, select it by clicking the new message icon, resulting in all unread mails from this account from all folders (they are sorted in server side using sieve), ignoring the 10 new messages in my spammy account (total: 1 tap)
> 
> Now it is:
> Starting up K9, opening side bar, opening the drop down, selecting the account (do this 5 times until I have the information for all accounts) scroll through the list of folders and select one by one -> 20 taps
> 
> I will stick with 5.6 for now and most likely will, because the old UI might look a little bit outdated but provided a way better user experience.

Were you able to export your setting from the new version and import back to the old one or did you have to manually resetup all settings and mail accounts in the old version?

**Comment by Q8sHrewd** [comment]
Crash crash 5800 !

**Comment by yosus** [comment]
i would also say the unified inbox is unusable as it is showing old emails and random accounts. I have 5 accounts in it, and everytime I load the app, the unified inbox appears and I have to manually click a few times more (compared to the old app) before I can actually check those individual emails.

**Comment by AndySchroder** [comment]
I do like the new sidebar for viewing folders in the mail account that I'm already in, but agree it is a MAJOR setback having to use this sidebar as a method to select different accounts. If we could have the original startup page where you can select an account but still have this sidebar once an account were selected, I think it would be good.

**Comment by AndySchroder** [comment]
The other major nuisance with this new design is that every time you open and close k-9 mail, it reverts back to your default mail account rather than the last used mail account.

**Comment by scoder** [comment]
After now two weeks of ambitious usage I have to agree. The new design has very little advantage over the old one, but makes multi-account usage (probably K9's original key feature) really annoying. It now requires a whole bunch of look+scroll+aim+hit operations to see what's going at all, whereas previously hitting "back" a couple of times was a speedy operation that didn't even require moving the finger. I don't think the previous multi-account design had much room for improvement.

**Comment by j-mcdougall** [comment]
I agree.  I chose K-9 mail because of its ease of use with multiple accounts and that is now gone.  Please add an option to bring it back.  Thank you.

How do you install an old version of the app and are its settings backwards compatible?  Or does that require completely resetting up the accounts?

**Comment by rms-joe** [comment]
tbh, i am not affected by this problem.
but i noticed throughout the discussion on this topic that there are barely any constructive suggestions on how to improve the situation with the current design.
would maybe a badge and customizable icon help?

![image](https://user-images.githubusercontent.com/60735914/129332955-e7fccc3e-3ebb-4d7d-be59-50acc26261f6.png)


I have been using the beta for quite some time and would like to take this opportunity to thank you for your great work.

**Comment by lifebarier** [comment]
> but i noticed throughout the discussion on this topic that there are barely any constructive suggestions on how to improve the situation with the current design.

Seriously? "Please add old view back" is pretty constructive and clear I would say. It does not even mean to throw away current changes. Just one extra version of "unified inbox".
What you are suggesting does not address any problems. 
1. I would still not see all of my accounts 
1.1. They don't fit in that row of bubbles. So I would still need to click to show list on that sidebar
1.2. Not visible right away. I would still need to click to show that side bar on app start or after leaving one of accounts.
2. I would still need to click back and forth much more than I used to have.

Simply bring back old view where all accounts are visible as folders in main view with ammount of unread messages next to it. Clicking on it opens that account. Clicking back returns with main view with account list and unread count.

**Comment by rms-joe** [comment]
pardon me, i did not refer specifically to this issue, but to the situation across all information channels.
(and no "Please add old view back" is neither constructive nor clear to me :D
where is the button? how does navigation works in your extra unified inbox? how does it look like? etc, etc
but I do not really want to discuss this further)

**Comment by lifebarier** [comment]
> (and no "Please add old view back" is neither constructive nor clear to me :D

Old view is.. well old one. I do not know how to explain this without sounding like troll... It is the one that was before, so shokingly, developers and old users of K9 mail affected by this knows how it worked and looked. Linked issue even has screenshot. Combine it with my explanation, maybe download old version if you are really interested.
As you said - you are not affected so it is safe to presume you did not use that UI. Nor you want or need or would use it. So this issue does not affect you (by your own admission).

**Comment by timw01** [comment]
> tbh, i am not affected by this problem.
> but i noticed throughout the discussion on this topic that there are barely any constructive suggestions on how to improve the situation with the current design.
On the whole, what I've seen on this topic has been clear and constructive (with a few inevitable exceptions).
The multi-inbox start-up screen (no button to get here, it's just where you land on launch if you use it, the Android "back" button returns you here after viewing an inbox) has been removed in version 5.8 , and the simple streamlined workflow that it provided in version 5.6 and earlier has been lost. Many old and new users of K9 that work with multiple email accounts would like the developers to reinstate it as a configurable option; to them this was one of the features that differentiated K9 from almost every other Android email client out there.

I've not seen any reply from the devs about this yet, but I'm pretty sure they will understand what is being asked, and are capable of asking for clarification if they do not. 

> would maybe a badge and customizable icon help?
This suggestion does highlight that you're not affected by the problem. 

> I have been using the beta for quite some time and would like to take this opportunity to thank you for your great work.
I suspect many, like me, were totally unaware of the betas and were just users of a stable and very usable email client that every day just did the job we wanted. After many years of stability it came as a massive surprise when an unexpected update took away functionality we used all the time.

**Comment by rms-joe** [comment]
it is impossible that there will be a rollback of more than two years of development work. so if i wanted to contribute something to the improvement, i would think about about how to solve the problem with the new constraints.

**Comment by lifebarier** [comment]
> it is impossible that there will be a rollback of more than two years of development work. so if i wanted to contribute something to the improvement, i would think about about how to solve the problem with the new constraints.

Please read thread more carefuly. As I said:
> It does not even mean to throw away current changes. Just one extra version of "unified inbox".

Look at #5551 for screenshot of what it used to look like. Get old version to experience how it worked.
... If that is too difficult... See list of accounts when you click on dropdown on sidebar? Now put that list as if it is "unified inbox v2" with number of unreads and stars next to it. Put fake account above all avounts to open current unified inbox. When you click on account it opens that account (just like selecting that account from list in sidebar. Bonus points for ability to open folder view instead of inbox(stuff sidebar shows when you are in inbox currently)).

But seriuosly, if you intend to work on this please get old version to check how it used to work. There is no better explanation/documentation of how it should work than already implemented working version.

**Comment by cketti** [comment]
See #5570

**Comment by timw01** [comment]
> it is impossible that there will be a rollback of more than two years of development work. so if i wanted to contribute something to the improvement, i would think about about how to solve the problem with the new constraints.

Are you saying you are one of the developers? If not how do you know what is possible/impossible?

**Comment by lifebarier** [comment]
Seeing as this is not fixed and comments on linked https://github.com/k9mail/k-9/issues/5570 is locked this seems to be old good:
1. Push something users don't like
2. Say you will fix it
3. Wait till users gets used to it while waiting for fix
4. Claim you made everything better

**Comment by AndySchroder** [comment]
> Seeing as this is not fixed and comments on linked #5570 is locked this seems to be old good:
> 
>     1. Push something users don't like
> 
>     2. Say you will fix it
> 
>     3. Wait till users gets used to it while waiting for fix
> 
>     4. Claim you made everything better

Definitely agree with your feelings on how **stupid** these changes are to the UI but it's a little rude to insult volunteers who have created this software in the first place. They've released the source code to it, so the most respectful solution would be to fork the code and fix the problem peacefully. I understand your frustration because you (and I also) don't have the working knowledge of code to fix it in a practical amount of time, but at least we aren't working with the alternative of a closed code base where we don't even have an option to try and fix it. Also, you can always revert to an older version of the software and resetup all of your settings.

**Comment by lifebarier** [comment]
> > Seeing as this is not fixed and comments on linked #5570 is locked this seems to be old good:
> > ```
> > 1. Push something users don't like
> > 
> > 2. Say you will fix it
> > 
> > 3. Wait till users gets used to it while waiting for fix
> > 
> > 4. Claim you made everything better
> > ```
> 
> Definitely agree with your feelings on how **stupid** these changes are to the UI but it's a little rude to insult volunteers who have created this software in the first place. They've released the source code to it, so the most respectful solution would be to fork the code and fix the problem peacefully. I understand your frustration because you (and I also) don't have the working knowledge of code to fix it in a practical amount of time, but at least we aren't working with the alternative of a closed code base where we don't even have an option to try and fix it. Also, you can always revert to an older version of the software and resetup all of your settings.

I am calling out what I -suspect- am sure will happen (because I saw this happen multiple times).
Only way to decrease chance of this happening is to keep on pinging developers on this issue.
If reminding that this is still an issue is not "peaceful" and somehow "rude", well, good.

**Comment by lifebarier** [comment]
Hey version 6.202 is out. Wasn't #5570 planned for 6.200?
I AM GOING TO HAVE FUNCTIONAL UI AGAI... 
Milestone: K-9 Mail 6.400

Ah yes. Step 3 in progress.

**Comment by AndySchroder** [comment]
Not sure that your comments are productive.

One alternative, is there any way we can pay k-9 developers to bring the feature back in a modern release? Developers having to sort through many comments complaining is work for them. If we could pay them to add this back, it would be a clearer incentive.

I'm currently willing to pay 100,000 sats.

**Comment by lifebarier** [comment]
> Not sure that your comments are productive.

It is more productive than staying silent and thus sending devs message that everything is fine.

Normally I would agree that dropping some money might help, but not this time.

1. Developers shown their dislike for old UI where we even needed whole forum thread to point out advantages of old UI (created by devs more as a containment board rather than genuine need to read same advantages as was listed in other threads). So hey, old is bad, and modern pads your CV.

2. Isn't k-9 now part of thunderbird? Yah, forget pleasing your users. Time for corporate development by council.


Also, you might want to disable notifications on this thread. because I have on my calendar random events reminding me to go rant on here.

**Comment by lifebarier** [comment]
Hey version 6.4 is out. Wasn't https://github.com/thundernest/k-9/issues/5570 planned for 6.4?
I AM GOING TO HAVE FUNCTIONAL UI AGAI...
Milestone: No milestone 

Ah yes. Step 3 in progress.

Now you might think I am clairvoyant... No I am just old enough to have seen this before. Way too many times.

@cketti mind telling everyone I was right?

**Comment by cketti** [comment]
https://forum.k9mail.app/t/blog-post-donations-in-2022/5735/7

**Comment by lifebarier** [comment]
Called it.
