### ISSUE TITLE
K-9 Now Has A Gmail Problem?

### ISSUE THREAD

**Issue by GiantWaffle** [thunderbird/thunderbird-android#5455]
Hi,

I installed K-9 v5.8 today (a clean install, not an update) because I had read that with v5.8 there were some major changes and so I thought I'd check it out.

While it did accept my Zoho (IMAP) email accounts just fine, it will not accept my Gmail account.

I did check the docs and followed it and then checked the forum and did see that others are also having the same issue.  There's even a thread called;

"K-9 Doesn't Work with Gmail Anymore"

… so something's going on and I can't get Gmail to work either and so I'm thinking that maybe there is indeed a bug in v5.8 regarding Gmail accounts.

After putting in the correct info, it then errors out, saying;

"Setup could not finish
Username or password incorrect.
(AUTH PLAIN failed (Username
and Password not accepted."

I tried encrypted password mode, checked my settings against what Google says, as well as my other email app that the same account works fine in, etc..  No luck.

I verified the Domains, Ports and Password.  IMAP is Enabled in my Gmail account, I checked with my laptop.

I have no trouble with the email app I've been using for a while, nor with any other email app that I've ever set the account up in and as I said, I verified that the settings are the same between the two apps.

LG (H910A) V20
Android 7.0

Please look into this?

Thank You

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.

See https://support.google.com/mail/answer/7126229?hl=en especially the troubleshooting section

**Comment by GiantWaffle** [comment]
What the hell is wdong with you?!  I said I'm reporting what appears to be a BUG!

Try reading what's written first!  I know you didn't do that, because you tried to shoo me off to two places that I clearly stated that I'd already been (forum and Google support)!  That's how I found out it's a problem with your app!

TRY READING THIS TIME!

**Comment by cketti** [comment]
> Try reading what's written first!

Good advice. So you did read the issue template and provided step by step instructions on how to reproduce the issue?

I am very confident it's not a bug. If Gmail didn't work with K-9 Mail you wouldn't be the first one to notice.
However, Gmail puts a lot of hurdles in your way before you can use IMAP. Most of what you have to do is spelled out on the support page I linked to. Did you enable 'less secure apps'? If so, why didn't you include this information?

**Comment by njeyaakili** [comment]
There isn't a bug:

  > I'm reporting what appears to be a BUG!

Look at: <https://forum.k9mail.app/t/gmail-setup-could-not-finish/650> for some pointers.

Using that information, I just set up my gmail account on a new device that's using k9 5.8.

**Comment by GiantWaffle** [comment]
Hi,

Just to respond to the questions/comments:

1) I thought of it as a "bug", because I have never once had an issue setting up a Gmail account in any Androud app or PC program when I did have all of the info right.  Add to that the peolle in the forums having the exact same problem with v5.8 and on top of that, other accounts having no problem being added, plus looking thru the forums and the support link and seeing no one with a solution and knowing the info entered is absolutely correct and that leans one toward thinking "bug".

2) As for stating the exact method used, I didn't ignore that.  It simply wasn't necessary because once I stated that I had verified every single entry (which the Auto-Setup had right) and that I wasn't alone in this, then the "method" basically came down to; "Go ahead, try to add a Gmail account.  I dare ya!" <lol>

3) The link that you just provided (thank you), I had not seen.  And I did search the forum for "Gmail".

Now for my new comments:

1) I did follow the link and turned on "less secure" and now K-9 works with my Gmail account too! :-)

2) But isn't that still kind of a bug though?  I mean, why does K-9 require users to lower their security?  Especially for an email app?  I've never had to do that before, which is why it wasn't already set to "Allow Less Secure…..".

3) I'm going to post in the forum about this solution, but IMHO, if you haven't made this a "Sticky", then you definitely should.  As well as, in addition, have a message pop up in the app.  I.e., if they get the "Username/Password" error when trying to add a Gmail account, make it so that after they dismiss it, another box pops up telling them that if they've verified that their info is correct, to go to that link, etc..  Or even just a pop up warning when they first open the app or something.  And that would cut way down on the number of people posting about this issue in the forums, etc..  Because with all due respect, regardless of what you may think, this is not a normal thing.  If it were, most leople would know to go and do that and every email app would act that way with Gmail accounts.  But in fact, the opposite is true and it's the one account that just about every email app sets up with a couple of taps after entering you email address and password and has no trouble with.  Like yours normally does, but has this issue with Gmail accounts and IMO, 99.9% of users will not know to look at that setting and they key point is, nor should they have to try to figure out that iths some obscure setting that they've never heard and flip a switch they didn't even know existed.

My humble suggestion is to make it work without having to flip that switch.

3) Since I've already got your attention, I will, lastly, just add that I agree with the numerous people who are upset that you got rid of the screen that it used to open up to that showed the accounts and had various functions.  No one with multiple accounts wants their email app to open the way yours does now.  Yes, you can use the "Unified Inbox", but hardly anyone likes that, especially not with apps that "Reply" with the default account instead of the one that received it and even if it does it right, no one likes not knowing without having to examine the email (you don't always remember which account you sent it from).  And yes, you can bring out the Menu from the left side and switch accounts, but they all do that, yet people still want your old openjng screen back.  People simply don't want to have to keep pulling out that Menu and manually switch accounts that way.  They just don't and apps should adjust to what users are crying out for, as is happening now (see for yourselves).

Final Comment:

Thank you for providing that link.  I had not even thought of that as being a possible issue for an email app.  I run a business working with Android developers and so I have seen Google mess with apps over security, just never an email app.  But then I've only ever been an end user on those. :-)

Also, not having the app open to a main accounts screen is honestly (now that Gmail is working for me) one of only two things that are keeping me from switching over to K-9 and buying it (if there's an option for that).  Those two things are:

1) Doesn't open to Accounts screen.  If I uploaded my Screenshot of the app I've been using correctly, then this will be basically what I'm talking about.  And each account will tell you how many new emails it has waiting (none when I captured it).

2) Have to add Contacts into an email one at a time.  No multiselect like many other email apps.

Thanks Again!  It was appreciated!

![ZZZ](https://user-images.githubusercontent.com/24922367/127240755-71d7bd3f-125d-4dcd-b66d-8f1294d8cc3c.jpg)

**Comment by njeyaakili** [comment]
The issue with gmail (and more recently yahoo/aol mail) access is that google is now requiring that a 3rd party app either use OAUTH2 for authentication, or the user has to go the "less secure/app-specific password" route. I think that there is some work in progress to put OAUTH2 support into K9. So, this isn't a bug, just a feature that's not yet available. I believe that the OAUTH2 support in Fairmail is only in the paid-for version.

I'm not going to respond further on this in this forum as the (non-)bug issue has been addressed and the rest of the comments should go in the previously referenced user forum where those issues are being discussed.

**Comment by GiantWaffle** [comment]
Got your response.  I understand completely now.  I did read something about that coming, but I thought that wasn't for a little while yet.

P.S.: I created an account for the K-9 Forum, but I can't Log In (see below) to actually post there, so I had to write to you here (sorry).

The account was created fine:

User Name: Zeuszoos
Name: Dave
Email: zeuszoos@zoho.com

It said that it sent the Activation Email, but it did not arrive (verified that the email address is correct).  I tried resending it twice, but it still hasn't arrived and I cannot Log In without Activating the account using the link that I'm sure it would send in the email.

Maybe it just takes a while?  They usually arrive quickly, especially when you request a resend, so I thought I should let you know, just in case an issue has cropped up that you're not aware of.

In the mean time, could someone please Activate my account if it's not too much trouble?

Thank You! :-)

Dave
