### ISSUE TITLE
Current version not available in F-Droid 

### ISSUE THREAD

**Issue by Krawei** [thunderbird/thunderbird-android#5459]
Dear team,

when I take a look on google play store the current version is 5.800 in the F-Droid store the current version is 5.740.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by TheLastProject** [comment]
K-9 Mail 5.800 was submitted to F-Droid 3 days ago:

https://gitlab.com/fdroid/fdroiddata/-/commit/2b81a8b15b733d2acf0940bee7d4f3492a2ea03a

It was successfully built yesterday:

https://monitor.f-droid.org/builds/log/com.fsck.k9/28000

It will be included in the next F-Droid index update (which has to be signed by the F-Droid key on an airgapped system which only 1 person has access to). The delay is 100% on F-Droid's side, but it's only a matter of time. The K-9 Mail team did their part.

**Comment by michaelblyons** [comment]
5.802 build reports failure. Last line suggests its metadata is set to 5.801. It is unclear to me whether that's on your end or theirs.
