### ISSUE TITLE
K-9 mail  doesn't register in microG for push notifications

### ISSUE THREAD

**Issue by just-Nob** [thunderbird/thunderbird-android#5461]
**Description**
For receiving push notifications, K-9 mail have to register in Google's cloud messaging service.
When using microG, the framework is rebuild by microG. The user has the possibility to see which apps are registered, as well as to "unregister" those apps which had registered themselves but where the user don't want to have push notifications from.

Usually, all registered apps are displayed there (e.g. messangers like Signal/Whatsapp, Google Play Store, GitHub, Firefox, ebay etc.), either in the "active" or in the "disabled" section.
Unfortunately, K-9 isn't displayed there.

I also re-installed latest K-9 mail v.5.800 to ensure a proper registration to the push services, but with no success.

**To Reproduce**
1. Take a modded/rooted phone with microG installed instead of original Google framework, e.g. a phone with /e/ installed as OS.
2. Install latest K-9 mail v.5.800.
3. Import some email accounts.
4. Go to microG settings --> "cloud messaging" to see that K-9 hasn't registered itself.
5. In consequence, emails are only loaded manually, at least as long as you don't switch to polling.

**Expected behavior**
K-9 should be registered in microG / "cloud messaging" sheet installation.
A "self test" functionality for push messaging in the K-9 mail app would be also fine, if possible. :-)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.800
 - Android version: 11
 - Device: Xiaomi Poco X3, running ArrowOS (vanilla) with microG,
rooted with Magisk
 - Account type: IMAP (only one tested, others may be affected as well)

**Logs**
I guess they're not able to help, because I had to "capture" the push notification registration process - no idea how to do / how to force that.

**Comment by just-Nob** [comment]
Btw, v.5.740 seems to have thr same problem, i.e. that's not only an issue of the latest v.5.800.

**Comment by cketti** [comment]
> For receiving push notifications, K-9 mail have to register in Google's cloud messaging service.

No. We're using IMAP IDLE and directly connect to your mail server. There's no third party involved.
