### ISSUE TITLE
Per account sounds notification sounds have disappeared

### ISSUE THREAD

**Issue by NickJH** [thunderbird/thunderbird-android#5463]
**Describe the bug**
With the older version you could configure a different notification sound per account. This has now disappeared. Now only the system setting is used.

**Environment:**
- K-9 Mail version: 5.800
- Android version: 10 with EMUI 10.0.0.180
- Device: Honor 10 (COL-L29)
- Account type: IMAP with Inbox set for Push

**Additional context**
Could be considered related to #5118

**Comment by supertin** [comment]
+1
I'm finding the new app rather annoying in this regard. I'm getting dozens of default system notification sounds playing every hour. I previously had my email sound set to a quiet, short pop sound, which I was able to easily ignore if busy. Now I don't have a clue what's trying to tell me stuff, and I have to pull my phone out all the time to check.

**Comment by AndySchroder** [comment]
Seems like there is also no way to turn off the notification sound, but still keep notifications showing up on the lock screen? Seems like a total design bomb in my opinion. This bug as well as https://github.com/k9mail/k-9/issues/5452 have made the new k-9 mail totally unusable. Any idea what the latest version of k-9 mail is that I can downgrade to that does not have this notification bug?

**Comment by ByteHamster** [comment]
> Now only the system setting is used.

The system settings screen (that you can reach by pressing the last item in K-9's notification settings screen) allows setting a custom notification sound for each account.

**Comment by cremor** [comment]
> The system settings screen (that you can reach by pressing the last item in K-9's notification settings screen) allows setting a custom notification sound for each account.

That seems to not be the case for every Android version. For me - with EMUI 9.1 (based on Android 9) - that screen does not allow to change the notification sound. But if I open the apps notifications settings manually from the Android settings menu, I do get the option to configure a notification sound per account. With one big problem there: The screen doesn't show for which account I'm configuring that right now - all accounts have the same description texts. So it's trial and error.

**Comment by NickJH** [comment]
With EMUI 10, in `App notifications`, I only get the options to `Show notifications`, `Messages` and `Miscellaneous` per account. The account is named but there is no option to change the sound.

**Comment by ByteHamster** [comment]
Directly tap on the text "Messages".

**Comment by cremor** [comment]
> Directly tap on the text "Messages".

Ok, thanks. I'm feeling stupid now ☹️ 

That UI design is not very intuitive...

**Comment by NickJH** [comment]
Wow! No wonder I could not find it. Agree with:
> That UI design is not very intuitive...
I guess it makes the bug invalid, but anyone can raise another bug about the UI.

**Comment by AndySchroder** [comment]
> > I guess it makes the bug invalid, but anyone can raise another bug about the UI.

Is this confusing UI a k-9 UI or android UI? Hard to tell because I don't know if android is super customizable there and k-9 mail used the customization in a confusing way or if android forces it to be that confusing.

**Comment by ByteHamster** [comment]
It's confusing UI in Android. You get the same screen for all other apps, too, and K-9 can't do anything about it.

**Comment by supertin** [comment]
Seems the name "messages" is set by the app, as other apps appear to have other names for their notifications (eg qksms simply has "default", while Google Maps has things like "assistant driving mode", both of which have a notification sound option).
Perhaps some of the confusion could be avoided by renaming the notification type to "New Email" or something similar so it's clearer that this is what we need to press, since I personally assumed "messages" meant things the app was trying to tell me, like connection error or whatever.

**Comment by NickJH** [comment]
IMHO, the `Messages` text should not have a check box beside it if it is the entry point for a sub-menu. At least this would give a clue there is a sub-menu if you click on it. There is a feint separator between the `Messages` text and the check box but this is not intuitive.

Personally I'd remove the check box and use a slider at the top or the next menu.
