### ISSUE TITLE
Duplicate notification sounds in K9 5.8 on Android 8.1.0

### ISSUE THREAD

**Issue by tmelconian** [thunderbird/thunderbird-android#5465]
Hi! Since upgrading to k9 5.8, I now get duplicate audio notifications when each email comes in. This is fully reproducible and occurs on all my email accounts for every email message. The notifications occur in rapid sequence, such that the notification tone for the first one doesn't finish playing before the second one starts.

I assume if this were happening for everyone, you would have noticed already, so it must be something specific to my OS version.

Could you please advise what additional debugging/testing you would need me to do in order to diagnose this issue?

**Comment by Hendrik-H** [comment]
I have the same but am also on Android 8.1.0.

**Comment by JP95Git** [comment]
I am using Android 8.1 with several email accounts and for each new email I hear 2 notifications.

**Comment by jw1001** [comment]
I confirm this also on Android 8.1.0.  The Notifications Log shows only one entry per message.  Previously on the same device, I have had an issue, on two separate occasions, with notifications not appearing for k9 messages, or else appearing only briefly.  On those occasions, the log had two entries for each message - don't know if that could be linked to the double-ring.  
[#3205](https://github.com/k9mail/k-9/issues/3205)
Battery optimisation _may_ have been a factor.

**Comment by cketti** [comment]
This may be fixed by #5494, which should make it into K-9 Mail 5.802. Please test and report back once that version becomes available (sorry, I can't provide an ETA).

**Comment by Paulchen232** [comment]
very nice 5.802 go.

**Comment by tmelconian** [comment]
Also fixed for me in 5.802; thanks! Glad I stuck it out instead of downgrading. :)
