### ISSUE TITLE
List of all unread messages no longer available in 5.8

### ISSUE THREAD

**Issue by mueller-physics** [thunderbird/thunderbird-android#5466]
In the new design, the number of unread messages in an account is displayed next to its name in the account list.

However, tapping the number does not bring up the list (virtual folder?) of all unread messages, but switches to the folder view.

This is very inconvenient when using, for example, server-side rules to sort mails into non-inbox folders. Or when using read/unread status to keep track of emails.

**Comment by andrewfg** [comment]
Design proposal below..

![k9-quick-filter](https://user-images.githubusercontent.com/893994/127668961-035a8801-cd46-4ecc-b656-ba217b1ea2cf.png)

**Comment by andrewfg** [comment]
See https://github.com/k9mail/k-9/pull/5519

**Comment by Kyoshiro-san** [comment]
See my comment on #5467 as this issue seems to be the same (but once again a bit more than #5519)

**Comment by Kyoshiro-san** [comment]
Just an idea as a temporary workaround, if you're not using unified inbox, you can check "unify" in each folder's properties and go to unified inbox, sorted by read/unread status.

**Comment by cketti** [comment]
See #4330
