### ISSUE TITLE
"Waiting for new emails" notification constantly displayed

### ISSUE THREAD

**Issue by liotier** [thunderbird/thunderbird-android#5468]
On Android 7.7.1, ever since my k-9 upgraded to 5.8, the "Waiting for new emails" notification is constantly displayed. There is no way to dismiss it - apart from disabling IMAP push. I have found no option to disable it. Is the constant display really the desired behaviour ?

**Comment by Monkey-Matt** [comment]
Yes this is expected behaviour as android requires apps running in the background to show a notification. If you tap the notification it will take you to an explanation of why it's shown with a link to some details about how to hide the notification: https://forum.k9mail.app/t/how-to-configure-push/1102

**Comment by liotier** [comment]
Thank you for this explanation.

If the notification is required per Google policy, could a F-Droid build exist without it ? I mean in theory... Of course that would that be excessive complication.

It seems my Android version is too old to feature the notification permissions granularity described behind the link. Well, I'll upgrade eventually.

![Screenshot_20210728-223653](https://user-images.githubusercontent.com/1236393/127394105-507d0b90-07d0-4f12-b808-7b0c9cb561bf.png)

**Comment by Monkey-Matt** [comment]
The notification is required by the Android OS so the apk distributed on F-droid has the same restrictions. You're correct android 7 doesn't have the finite notification control so not much you can do apart from upgrade to a newer android version
