### ISSUE TITLE
"Spam" menu item hard to find on a tablet

### ISSUE THREAD

**Issue by justdave** [thunderbird/thunderbird-android#5469]
**Describe the bug**
On my phone, when viewing a message, the "Spam" option is right at the top of the menu.  On my tablet, with the same version of K-9, it's buried in the "refile" submenu, which makes it hard to find.

**To Reproduce**
1. Open a message
2. Click on the three-dots button to open the menu
3. Look for "Spam"

Repeat steps on both a phone and a tablet

**Expected behavior**
The menus should be similar on both types of hardware.

**Screenshots**
Tablet:
![Screenshot_20210728-144713.jpg](https://user-images.githubusercontent.com/307334/127379697-4ec1f0ee-e472-4bb3-a179-9e6d2f8be835.jpg)

Phone:
![Screenshot_20210728-144841_K-9 Mail.jpg](https://user-images.githubusercontent.com/307334/127379752-50a1a75c-d481-4e77-85fa-25ee61bb2c3f.jpg)

**Environment (please complete the following information):**
Phone:
 - K-9 Mail version: 5.800
 - Android version: 11
 - Device: Samsung Galaxy S10+
 - Account type: IMAP

Tablet:
 - K-9 Mail version: 5.800
 - Android version: 7
 - Device: Samsung Galaxy Tab S2
 - Account type: IMAP

**Additional context**

**Logs**

**Comment by cketti** [comment]
Could this be due to different configuration of `Settings > General settings > Display > Visible message actions`?

**Comment by ottlinger** [comment]
@cketti the default actions I see in my inbox (folderview) are
* Sort by
* Select all

Earlier versions had mark as spam as well ....

Thanks for providing the hint to above settings, which at least allows me to manually select a message for Spam.

I'd prefer to mark multiple messages and send them to the spam folder, but I'm not sure if this functionality exists. Thanks.

**Comment by ottlinger** [comment]
@justdave I know your problem. Are you in the folder view or are you looking for the "Spam" when inside a particular message? If you are in a message @cketti 's hint should do the trick.

**Comment by justdave** [comment]
This was inside a message, and @cketti was spot on. I don't recall having ever set that on the phone, but then again I've been using k9 for years and memory is fleeting.

**Comment by cketti** [comment]
Maybe you want to follow the issue to improve visible message actions: #5300

Closing this issue since it seem to be resolved.
