### ISSUE TITLE
Version 5.800 stopped recognizing user-installed CA

### ISSUE THREAD

**Issue by crosser** [thunderbird/thunderbird-android#5473]
**Describe the bug**
When using TLS with a a server whose certificate is signed by a non-mainstream CA, despite the CA certificate is installed in Android's CA store, K9 throws a dialog saying that the signer is unknown, and offering to accept server's certificate individually.

**To Reproduce**
1. Have a CA.
2. Have an SMTP / IMAP server that has certificate signed by the above CA.
3. Install certificate of the CA into Android's "trusted CA" store.
4. Verify that Chrome and Conversations (XMPP client) connect to web and jabber servers that use certificates signed by the above CA without warnings.
5. Try to configure K9 / have previous version configured to talk to an email server that uses certificate signed by the above CA.
6. Observe error message saying "Trust anchor for certification path not found", offering to accept or reject "key". 

**Expected behavior**
Like other TLS-capable Android applications, and like the previous version of K-9, TLS session with the server should be opened without complaint.

**Screenshots**
![Screenshot_20210728-235635](https://user-images.githubusercontent.com/1404921/127402407-29c83905-f80e-40b1-8e7e-1c8a8aae1f40.png)
![Screenshot_20210728-235827](https://user-images.githubusercontent.com/1404921/127402428-510da19e-b7a6-48c7-8051-856c7d6ae1f9.png)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.800
 - Android version: 10
 - Device: Sony H9436 (Xperia XZ-something)
 - Account type: IMAP

**Additional context**
**Logs**
Can provide upon request, I think it should easy to reproduce though.

**Comment by cketti** [comment]
We now probably need a custom network security configuration to support user-installed CAs. https://developer.android.com/training/articles/security-config

**Comment by cketti** [comment]
@crosser: Can you please check if the attached version restores support for user-installed CAs for you?

[k9mail-5.801-SNAPSHOT-network-security-config.zip](https://github.com/k9mail/k-9/files/6899590/k9mail-5.801-SNAPSHOT-network-security-config.zip)

**Comment by crosser** [comment]
Yes, it works now!
Thanks for such a quick reaction! :+1:

**Comment by cketti** [comment]
Thanks for the quick feedback. The fix will be included in 5.801.
