### ISSUE TITLE
Using my identity from phone for email name rather than one provided in identity

### ISSUE THREAD

**Issue by Globe51** [thunderbird/thunderbird-android#5474]
When sending an email from an identity with the email address my.name@my.domain, k9 somehow pulls the linked email domain from my contacts and prefixes the email sender with that identity so emails are being sent from

.My_Number<<my.name@domain.com>>

instead of just <my,name@domain.com>

Even when an identity has a prefix associated with it (ie Mr Person<<my.name@my.domain>>) this is being replaced with the value from my phone book

.My_Number<<my.name@domain.com>>

This is a serious issue which renders the application unusable in a professional or semi-professional environment,

**Comment by njeyaakili** [comment]
I think your report would be clearer if you had filled in the template provided when you filed this bug. 

When sending a message the sender's information - "name" and email address - come from the information that's found in:
  - [account]
    - settings
      - sending mail
        -- composition defaults or manage identities
   You can edit the information in either of those places. Be careful to put the name and email address in the fields so labeled.

If you select a recipient from your contacts the "identity" that you have associated with them will be the "name" part of the To:/Cc:, so there you do need to be careful how you identify your contacts in your addressbook, using what you want them to see, not what you might think of them.

If you enter a recipient address manually, what you enter is what they will see.

Note -- some email clients (e.g., outlook) will replace the "name" part of an entry on a message with what the recipient has in their addressbook for that email address. You will see this when they reply to you. If that is what you are seeing, this is an issue with their client, not with K9.  

If none of this clarifies the issue, please provide (minimally redacted) screenshots to show the issue clearly.
