### ISSUE TITLE
Push not working with Google Apps/Google Workspace

### ISSUE THREAD

**Issue by goduck777** [thunderbird/thunderbird-android#5483]
**Describe the bug**

I have tried the new push function for my personal Gmail account and it works fine. However, it does not work on my work Google Apps account. This account has the same IMAP server as Gmail, but uses the full email address to log in.

I wonder if K9 disable the push function if it found the email address does not end with gmail.com.

**To Reproduce**
1. Add a Google Apps email account in K-9 Mail, with IMAP server imap.gmail.com
2. Turn on Push and turn off poll
3. No email is received

**Expected behavior**
Push function should work like gmail

**Environment (please complete the following information):**
 - K-9 Mail version: 5.740
 - Android version: 11
 - Device: Oneplus 8
 - Account type: IMAP

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by goduck777** [comment]
I can provide a log, but there is nothing special in it. When I enable the push, it just says the Push Controller begins. But when new emails arrives, there is no notification and the log is empty. When using a personal gmail account, there is a notification and the some logs on it.

**Comment by goduck777** [comment]
My mistake. I forgot to set the push class to 1st class. The default value is 2nd.
