### ISSUE TITLE
"Share" picture proposes same contact multiple times, or never used contacts

### ISSUE THREAD

**Issue by beat** [thunderbird/thunderbird-android#5486]
**Describe the bug**
When sharing from any app, k9mail doesn't propose its "often used/last used" contacts properly:

When I want to share a picture on my phone, out of 4 "last used/often used" contacts, the same (often used in k9mail) contact is proposed 3 times by k9mail, the 4th is another app.

On another family member's phone (same model), sharing a picture proposes a k9mail contact that was never used as only k9mail contact, the 3 oither spots are another app, which are ok.

**To Reproduce**
1. Go to 'photo gallery' and to a photo
2. Click on 'Share' icon
3. See what contacts from k9mails are proposed. They can be repeated multiple times or have a contact never used.

**Expected behavior**
1. k9mail should propose each contact only once.
2. k9mail should not propose never used or seldomly used contacts
3. k9mail should not put its contacts as first priority compared to other apps

**Screenshots**
Available on request.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.800
 - Android version: 8.0.0 with standard Samsung Experience 9.9
 - Device: Samsung Galaxy S7
 - Account type: IMAP

**Additional context**
 - searched bugs in here but didn't find it reported, so opening this one. Sorry if already known.

**Logs**
- no error logs as no crash

**Comment by cketti** [comment]
Does the contact have three different email addresses?

**Comment by beat** [comment]
@cketti probably an interresting track: 

The contact in question that appears 3 times has 4 email addresses, of which I use 1 often to send emails, and 2 seldomly, and one never.

Ineed each contact should be proposed only once and with the last or most often used e-mail address.

For the other strange case from family member (not sure if related) the contact proposed was never used, while other contacts were used often.

**Comment by cketti** [comment]
We removed this feature because of problems like this. See https://github.com/thundernest/k-9/issues/6381#issuecomment-1284324637
