### ISSUE TITLE
Switching between accounts belonging to the same contact is confusing

### ISSUE THREAD

**Issue by leeN** [thunderbird/thunderbird-android#5501]
**Describe the bug**
I have multiple personal e-mail accounts integrated into k9 mail. Since the last update switching between them takes place via the sidebar. As they are all linked to my contact in the android address book, they all share my contact picture. This makes switching between accounts trial and error until you click the right one.

**Expected behavior**
A second indicator in the switch accounts view to distinguish between email accounts sharing the same contact picture.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.800
 - Android version: 9
 - Device: Xiaomi Mix 2s
 - Account type: Various

**Comment by protist** [comment]
I'm also finding this very hard to navigate. Here is a screenshot with the three identical pictures.

[<img src="https://user-images.githubusercontent.com/646668/127957209-2d2e03ce-ef4d-40b8-a21f-ed4330ba46b5.png" width="100">](https://user-images.githubusercontent.com/646668/127957209-2d2e03ce-ef4d-40b8-a21f-ed4330ba46b5.png)

Even more confusing is that each icon links to a different account depending on the situation. Ideally we could customise the picture displayed. Alternatively (or in addition), the icons could be differentiated by colour (as per the previous version of K-9).

**Comment by cketti** [comment]
I created issue #5509 with a proposed solution. Closing this issue.
