### ISSUE TITLE
k-9 5.800 causing vodafonemail.de to block the account

### ISSUE THREAD

**Issue by xss** [thunderbird/thunderbird-android#5503]
**Describe the bug**
After Update to k-9 5.800 on Android 6.0.1, due to k-9's changed Push notification handling, k-9 seems to "hammer" IMAP servers more than before. This causes one of my mail providers, Vodafonemail.de, to block my account automatically every day, and I have to manually mail their support to un-block my account. Only to have it blocked again the next day. Their explanation (plus loose translation):

"Dein Email-Account war ungewöhnlich aktiv. Zur Sicherheit haben wir ihn gesperrt."
"Your email account has been unusally active. For security reasons, we blocked it."

and:

"[...] unsere Analysesysteme haben festgestellt, dass Dein Passwort mit hoher Wahrscheinlichkeit von Fremden ausgelesen wurde [...]"
"[...] our analysis engines found that your password was very likely obtained by a (malicious) third-party [...]"

This is simply untrue, and it started right after k-9 was updated to 5.800 on my device by Play Store.

**To Reproduce**
1. On Android 6.0.1, install k-9 pre-5.800
2. Setup an IMAP account with vodafonemail.de, activating poll every 12 hours as well as push with "Refresh IDLE connection" every 12 minutes
3. Enjoy k-9 working just fine, as it has been working for years
4. Update k-9 to 5.800
5. Wait a day or two until all IMAP logins get rejected, then log in via web interface to find said mail from abuse@vodafonemail.de

**Expected behavior**
k-9 should access the IMAP server the way it did before 5.800, without triggering any security automatisms.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.800
 - Android version: 6.0.1
 - Device: OnePlus 2
 - Account type: IMAP/SMTP

**Additional context**
Other IMAP accounts (Yahoo, as well as my accounts on a shared hoster) do not seem to have issues, thus far.
Apparently, I'm not the only user affected by this:
* https://forum.k9mail.app/t/account-blocked-email-provider-authentication-failure-5-800/1992
* https://forum.vodafone.de/t5/MeinVodafone-MeinKabel-E-Mail/IMAP-Passwort-ge%C3%A4ndert-funktioniert-aber-nicht/m-p/2682469 (forum in German)

**Logs**
<strike>[Will attach relevant logs as soon as I have them]</strike>

**Comment by cketti** [comment]
Probably the same bug as #5487

**Comment by cketti** [comment]
It's very likely that this is the same bug as #5487. Closing this as duplicate.

Enabling Push in K-9 Mail when the server doesn't support the IDLE extension is what triggers this bug. Manually disabling Push for the affected account will avoid the problem. 
K-9 Mail 5.802 will automatically disable Push for an account when it detects that the server doesn't support the IDLE extension.

**Comment by xss** [comment]
Hello @cketti, thank you for the updates.

As Push and IDLE have worked for these accounts for many, many years in K-9 Mail pre-5.800 with no issues, isn't simply disabling it a step into the wrong direction?

I feel like loosing functionality for this account now, having to wait for the next Poll in order to be notified of new mails. Sure, I could increase the Poll frequency, but as I can't find any permitted access limits in Vodafonemail.de's help pages, I fear I might run into the same server-side block again if set too frequently.

**Comment by cketti** [comment]
From the logs I had access to, it appears that the servers don't support the IDLE extension. If that's true then Push didn't work with 5.600 either. It just wouldn't fail as spectacularly.
