### ISSUE TITLE
First account should be opened by default

### ISSUE THREAD

**Issue by deki** [thunderbird/thunderbird-android#5508]
**Describe the bug**
With the new K-9 Mail version the Accounts overview page does no longer exist (which is sad by the way). The Unified Inbox view is opened by default. However if disabled, it's currently not possible to select which account is opened. Although the list of accounts is sortable, K-9 Mail always opens a specific (for me unimportant) account, no matter where this is positioned in the account list.

**To Reproduce**
1. Add more than one account
2. Disable Show Unified Inbox
3. Sort accounts in settings view
4. Reopen K-9 Mail
5. Observ which account has been opened

**Expected behavior**
The first account in the list will be opened or add a setting to specify which account to open by default.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.801
 - Android version: 11
 - Device: Samsung S10e
 - Account type: IMAP

**Comment by cketti** [comment]
K-9 Mail opens the default account. You can select which one that is under *Settings > [Account] > General settings > Default account*.

There's already an issue to remove this setting and simply use the first account as default account. See #5419

**Comment by deki** [comment]
Thanks, I was looking through existing issues and forum threads but missed that one within all the other complaints :-) I can confirm it's working now.
