### ISSUE TITLE
External memory is not used

### ISSUE THREAD

**Issue by majokr** [thunderbird/thunderbird-android#5514]
**Description**
The external memory is not used, the program data remains at the system storage.

**To Reproduce**
1. Change the Android system settings of K-9 Mail and set the used storage type to external storage or SD card.
2. Create an E-Mail account with IMAP.
3. The data path is still on the system storage (system storage > Apps > K-9 Mail > data)

**Expected behavior**
After the storage type was changed to external storage, I expected the data directory on the SD card (external storage > Android > data > K-9 Mail), where the data of other apps were found too, with external data usage set.

**Environment**
 - K-9 Mail version: 5.801
 - Android version: 6.0.1
 - Device: Samsung Galaxy
 - Account type: IMAP

**Comment by cketti** [comment]
K-9 Mail now always stores data in its app-private directory. Whether Android keeps that on internal or external storage is not up to the app.
It sounds like *external storage > Android > data > K-9 Mail* is for data the app wishes to explicitly store on external storage. K-9 Mail never does that. 

For more details see https://developer.android.com/training/data-storage/app-specific

**Comment by majokr** [comment]
Thank you for the hint! The following Links helped me:

https://android.stackexchange.com/questions/146513/how-to-adopt-sd-card-as-internal-storage-on-samsung-devices?newreg=88b4b0d7c8654f068e598f9e9c912232

https://teching.nl/2017/04/solve-your-storage-problems-on-samsung-galaxy-s5-with-adoptable-storage/
