### ISSUE TITLE
Move to folder search handling of spaces

### ISSUE THREAD

**Issue by edemaine** [thunderbird/thunderbird-android#5524]
**Summary:** Searching for the folder "foo " (including trailing space) matches all folders. 

**Is your feature request related to a problem? Please describe.**
When moving a message to a folder, and then clicking the search button (something I do many times per day to navigate my 10,000 folders), I sometimes use SwiftKey's autocompletion to finish the name of the folder/keyword. When I do so, SwiftKey adds a space at the end of the word. Then K-9 matches all folders until I backspace to remove the space.

**Describe the solution you'd like**
At the least, I think the search field should be trimmed of leading and trailing whitespace. This is likely a one-line change. 

**Describe alternatives you've considered**
The current behavior seems to be to OR together substring matches for each word. I can't think of a use for this. Perhaps more natural would be to take an AND? Then this issue would disappear (though for efficiency, it'd still be a good idea to trim).

**Comment by cketti** [comment]
I can't remember why the app uses OR when filtering the folder list. The new version does so, because the old version did.
I'm not opposed to changing the behavior. If AND is more convenient to you, please open a new feature request just for that.

**Comment by edemaine** [comment]
Sounds good. I can't say I've ever really wanted to use multiple words before, but I'll think about it. The trailing space behavior is new though, so I agree with the bug label. (Sorry, I wasn't sure which was best.)

**Comment by cketti** [comment]
The fix for the trailing space bug should make it into K-9 Mail 5.803. See #5531.

**Comment by edemaine** [comment]
By the way, this has still never worked in any released version. When I have a space at the end of a search, it matches all folders. Not sure why; the diff in #5531 looked good.

**Comment by cketti** [comment]
Thanks for the feedback. #5531 was fixing the wrong screen. #6536 fixes the same problem in the move/copy screen.

**Comment by edemaine** [comment]
Thank you!
