### ISSUE TITLE
Crashes when selecting show images

### ISSUE THREAD

**Issue by churchthecat** [thunderbird/thunderbird-android#5525]
When selecting "show pictures" the app
crashes.
Pixel 3 XL Graphene OS

**Comment by cketti** [comment]
You probably have to grant the app the internet permission.

**Comment by cketti** [comment]
We should catch `SecurityException` here:

https://github.com/k9mail/k-9/blob/03fb2b953840a667f452c8a8d65ddb15f84b8348/app/ui/legacy/src/main/java/com/fsck/k9/view/MessageWebView.java#L48

**Comment by schlagi123** [comment]
I think, this issue should be cloused because of pull request https://github.com/k9mail/k-9/pull/5745
