### ISSUE TITLE
Missing link in K9

### ISSUE THREAD

**Issue by Chrischris69** [thunderbird/thunderbird-android#5529]
**Describe the bug**
The view in K9 and webmail is not exactly the same. In K9 2 links are missing in the body. Problem of message encoding or bug ?

See 

![Webmail laptop](https://user-images.githubusercontent.com/88533430/128486000-4233aada-5930-4c7f-b730-30c842a0f305.jpg)
![K9 mail](https://user-images.githubusercontent.com/88533430/128486893-f662c498-42c6-4f06-b3e6-1c410b596f36.jpg)
eml [Les occasions Norauto la route des vacances c'est cadeau !.zip](https://github.com/k9mail/k-9/files/6944443/Les.occasions.Norauto.la.route.des.vacances.c.est.cadeau.zip)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.801
 - Android version: 11
 - Device: Realme GT 5G
 - Account type: IMAP mailo.com

**Comment by cketti** [comment]
Not a bug in K-9 Mail. The creator of the email intended it this way. Some elements are hidden on small screens via this CSS rule:

```css
@media only screen and (max-width: 500px) {
  .hide { display: none !important; }
}
```
