### ISSUE TITLE
No vibration or sound when new mail arrives

### ISSUE THREAD

**Issue by alex-taylor** [thunderbird/thunderbird-android#5536]
Following the update to version 5.8, I no longer get sound or vibration notifications when new mail arrives.  The popup on the lock screen does not appear either.

I do not have Quiet Time enabled, and all K-9 notification settings and system notification settings are enabled.  

Other applications (SMS, WhatsApp etc) still buzz and play sounds, and K-9 Mail was also doing so prior to the update.

I have updated to 5.802 as suggested in https://github.com/k9mail/k-9/issues/5458 but this has not helped.

With settings as described above, wait for incoming mail to arrive.
I see the 'new mail' icon at the top of the screen, and the K-9 icon on my home screen shows the 'number of new emails' count, but that's it - no sound, no vibration or (if the phone is locked) popup on the lock screen.

Environment
 - K-9 Mail version: 5.802
 - Android version: 11
 - Device: Samsung Galaxy S10+
 - Account type: IMAP

**Comment by cketti** [comment]
What does your system notification settings screen look like?

<img src="https://user-images.githubusercontent.com/218061/128579422-a7094f30-7161-4640-af88-c38115ce3130.png" alt="k9mail_system_notification_settings" width=300>

**Comment by alex-taylor** [comment]
![Screenshot_20210807-120147_Settings](https://user-images.githubusercontent.com/5150717/128598256-700d25a5-b1f6-40f6-a727-cdb847e0c5d4.jpg)
![Screenshot_20210807-120204_Settings](https://user-images.githubusercontent.com/5150717/128598258-e39100e5-d687-4897-9ddd-463ba7d0e790.jpg)

**Comment by alex-taylor** [comment]
![Screenshot_20210807-120204_Settings](https://user-images.githubusercontent.com/5150717/128598288-19f1fefb-ff02-4894-822b-31bfb30c550a.jpg)

**Comment by alex-taylor** [comment]
I don't appear to have the "Notification category" screen available on my device

**Comment by cketti** [comment]
Tap the "Messages" text on the left. 

The vertical line indicates the text and the switch are two different user interface elements that can be tapped and perform different actions. In this case tapping the left part opens the sub screen where you can configure notifications of that type.

**Comment by alex-taylor** [comment]
Ah...dark grey on black.  Serious usability fail there :-(

Anyway:
![Screenshot_20210807-140147_Settings](https://user-images.githubusercontent.com/5150717/128601077-3edc6e55-76f2-49e8-a209-02ea350309e2.jpg)

**Comment by alex-taylor** [comment]
Small update.  An incoming mail a couple of hours ago did trigger the sound and vibration; however it was the only one to do so - all other email I've received today was silent.

**Comment by cketti** [comment]
How did you configure K-9 Mail to check for new messages? Polling, Push, manual sync?

**Comment by alex-taylor** [comment]
It's set to poll every 15 minutes.  There's no problem with it finding and downloading new mail, it's not missing anything.

**Comment by cketti** [comment]
I'm not able to reproduce this issue. Notification sound and vibration works fine for me on Android 11.

**Comment by alex-taylor** [comment]
I've had a few more working notifications now, so it's possible that this really is just an intermittent issue.

I'll continue to monitor things - if I find anything new I will update this bugreport :-)

**Comment by islam2hamy** [comment]
I have the same issue ( no notifications ,  ) And i have noted that , with manual mail refresh , the new mail arrives as readed

Android 11 , samsung

**Comment by cketti** [comment]
@islam2hamy: That's a different issue. Please see [this forum thread](https://forum.k9mail.app/t/android-10-notification-issues/50) if you don't get any notifications at all.

**Comment by islam2hamy** [comment]
I thing it is because i received the mail in another mail client (pc) ,but i didn't read it there

I will try again tomorrow at work and till you

**Comment by cketti** [comment]
@islam2hamy: The reporter of this issue is getting notifications. But sound/vibration doesn't work like it's supposed to. You say you're not getting any notifications at all. So please open a new issue and don't post to this issue.

**Comment by alex-taylor** [comment]
So far so good, notifications seem to be working normally again now.

I'll close this issue off; if it comes back, and I can work out the pattern, I'll open a new one :-)
