### ISSUE TITLE
F-Droid changelog link is outdated

### ISSUE THREAD

**Issue by Rult** [thunderbird/thunderbird-android#5542]
**To Reproduce**
1. Go to [the F-Droid page](https://f-droid.org/packages/com.fsck.k9)
2. Go to "Changelog"
3. Get [the outdated changelog](https://k9mail.app/k-9/changelog_5.6-MAINT_branch.xml)

**Expected behavior**
Get [Github Releases page](https://github.com/k9mail/k-9/releases) or [the updated changelog from the site](https://k9mail.app/k-9/changelog_5.8-MAINT_branch.xml)

**Comment by cketti** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9531
