### ISSUE TITLE
New mails are received but not displayed

### ISSUE THREAD

**Issue by Schnappi175** [thunderbird/thunderbird-android#5548]
Hello,
I've had version 5.802 for a few days. Since then, only the number of new mails is displayed, but not the mails themselves.
I only have one email account. It doesn't matter whether I go to the common inbox or inbox.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.802]
 - Android version: 10
 - Device: Huawei P20 pro
 - Account type:  IMAP

**Comment by njeyaakili** [comment]
I'm assuming you are seeing messages, just not the new ones (which are indicated by the count). In that case, check your mailbox sort order.

**Comment by Schnappi175** [comment]
Many Thanks. The problem was actually with the sorting.
