### ISSUE TITLE
Common inbox does not aggregate mails of different accounts

### ISSUE THREAD

**Issue by Coernel82** [thunderbird/thunderbird-android#5555]
might be realted to https://github.com/k9mail/k-9/issues/5548

The "common inbox" should display mails from aggregated from all accounts set up in the app however it just shows mails of the currently active account.

**To Reproduce**
Set up more then one mail account and check common inbox.

**Environment:**
 - K-9 Mail version: 5.800
 - Android version: 11 / LineageOS 18.1-20210805-NIGHLTY-dipper
 - Device: Xiamoi MI8
 - Account type: IMAP

**Logs**
I do not think that a log is necessary in this case. If you do need a log I will create one. Let me know.

**Comment by cketti** [comment]
Please don't assume that describing your setup in one sentence is enough to reproduce an issue.

Steps I've taken:
1. Fresh installation of 5.802 (this is the current version)
2. Set up an IMAP account (manually providing server settings)
3. Accept default configuration for the account (check every hour, 25 messages, notify for new messages)
4. Name the account "One"
5. Inbox of the account is displayed and messages are present
6. Go to *Settings > Add account*
7. Set up another IMAP account (manually providing server settings)
8. Accept default configuration for the account (check every hour, 25 messages, notify for new messages)
9. Name the account "Two"
10. Inbox of the account is displayed and messages are present
11. Switch to *Unified Inbox*
12. Messages from the Inboxes of both accounts are displayed

As you can see there's no problem when I set up two accounts. So something about your setup must be special. If you can't provide instructions on how to reproduce the issue, we can't fix the bug.

**Comment by fommio** [comment]
> might be realted to #5548
> 
> The "common inbox" should display mails from aggregated from all accounts set up in the app however it just shows mails of the currently active account.
> 
> **To Reproduce**
> Set up more then one mail account and check common inbox.
> 
> **Environment:**
> 
> * K-9 Mail version: 5.800
> * Android version: 11 / LineageOS 18.1-20210805-NIGHLTY-dipper
> * Device: Xiamoi MI8
> * Account type: IMAP
> 
> **Logs**
> I do not think that a log is necessary in this case. If you do need a log I will create one. Let me know.


Check if the **_Unify_** setting is enabled for the inbox that is not displayed in the Unified Inbox:

<img src="https://user-images.githubusercontent.com/67462955/131214194-c2543b20-420e-4aee-b00e-f32e8ba5ec41.jpg" height="600">

<img src="https://user-images.githubusercontent.com/67462955/131214195-ab59fa63-1872-4236-a5fd-777f26300d63.jpg" height="600">

<img src="https://user-images.githubusercontent.com/67462955/131214196-11866941-d2e7-4b6b-9a12-db7da5010cf7.jpg" height="600">

**Comment by Coernel82** [comment]
Indeed the "Unify" was missing. This might have been changed by the recent update.

Solved!
