### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by NickWick13** [thunderbird/thunderbird-android#5556]
**Describe the bug**
I got an e-mail today and the notification looks like in the screenshot. I guess that it is an e-mail

**Screenshots**
[
![1628620949819](https://user-images.githubusercontent.com/84130654/128917817-7bb3d5b6-f31c-414e-aead-6fdad8b27ae0.jpg)
](url)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.802
 - Android version: 11
 - Device: Mi Note 10
 - Account type: IMAP

**Comment by cketti** [comment]
That's probably not a bug. K-9 Mail uses the contents of the text/plain part of a message for the preview. Chances are in this message the text/plain part is a poorly converted version of the text/html part.

**Comment by xz-dev** [comment]
@cketti I also have this problem, and I can fix it, can I make a PR to fix it?

**Comment by cketti** [comment]
@xz-dev: PRs are welcome. See issue #5890.
