### ISSUE TITLE
Push folder configuration setting not accepted / persisted

### ISSUE THREAD

**Issue by gitflo** [thunderbird/thunderbird-android#5568]
I'm using v5.802 with two IMAP accounts on two different servers. Both servers support IMAP IDLE.
With the first account, Push is working perfectly. But with the second account, Push is not working, and the configuration always resets itself automatically.

Here are the steps to reproduce (I'm using the German UI):
1. Choose menu..Einstellungen
2. Choose the affected account for "Kontoeinstellungen"
3. Choose "E-Mails abrufen"
4. Choose "Push-Ordner" - it was set to "Keine Ordner" - select "Nur Hauptordner"
   Result: In the menu, it now shows correctly "Push-Ordner" "Nur Hauptordner"
5. Exit the menu
6. Choose again "E-Mails abrufen"
   Result: "Push-Ordner" has been reset to "Keine Ordner"

**Environment (please complete the following information):**
 - K-9 Mail version: v5.802
 - Android version: 8.0.0
 - Device: Samsung Galaxy A5 (2017)
 - Account type: IMAP (twice)

**Comment by cketti** [comment]
K-9 Mail automatically disables Push when the server doesn't support the IDLE extension or when using the IDLE command fails with an error.

**Comment by gitflo** [comment]
How to dig deeper then?
The CAPABILITY of the server lists IDLE, and with Thunderbird, an email arrives instantly, so I assume it's working correctly.
Both servers are Zimbra servers.

**Comment by cketti** [comment]
K-9 Mail's debug log contains the client/server communication. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by gitflo** [comment]
Please find the debug log attached.

Notes:
* The working, primary account is "holeczek.de", the non-working, secondary one is "BNV".
* Around 08:44, I've been performing the beforementioned steps to reconfigure the Push folders, followed by a refresh of the affected account's inbox, followed by checking the config setting again (and again it got reset).
[k9-log.txt](https://github.com/k9mail/k-9/files/6980524/k9-log.txt)

**Comment by cketti** [comment]
Thanks for the log. 

The server is sending an unexpected (but allowed) untagged response to the IDLE command when K-9 Mail expects a command continuation request response. The app currently fails to handle this situation, treats it like an error and disables Push.

The fix should make it into 5.804 and 5.900.

**Comment by gitflo** [comment]
Great news!

I found the behaviour quite surprising and confusing. Maybe it's possible to at least display an error message before disabling push automatically, or at least to document this behaviour somewhere.

**Comment by cketti** [comment]
Fix was merged into [5.8-MAINT](https://github.com/k9mail/k-9/tree/5.8-MAINT).
