### ISSUE TITLE
Please revert Icon change

### ISSUE THREAD

**Issue by SomeTroglodyte** [thunderbird/thunderbird-android#5575]
**Describe the bug**
Your choice of pink

**To Reproduce**
1. Update from 5.x to 5.8.x
2. All your desktop links are gone
3. Search for it in the app drawer
4. ... and ***puke***

**Expected behavior**
Do not remove your icon from people's screens just to recolour your icon so horribly

**Screenshots**
Better not or I might get innocents to puke as well

**Environment (please complete the following information):**
 - K-9 Mail version: 5.802
 - Android version: LOS 17.1
 - Device: irrelevant
 - Account type: irrelevant

**Comment by cketti** [comment]
We created activity-aliases so launcher shortcuts continue to work. This worked fine in tests. And only a handful of users have reported problems with this after upgrading. This leads me to believe you either created the shortcuts with a very old K-9 Mail version or that your launcher did something odd. This has nothing to do with the app icon, though.

Your dissatisfaction with the app icon has been registered.

**Comment by SomeTroglodyte** [comment]
Ironic - this would have netted you an increase in income _if_ Liberapay weren't using AWS. AWS -> the club's server I route through complains about SPF -> LP blacklists and re-routing helps not... Soap opera. Maybe next time...
