### ISSUE TITLE
App attempts to connect to accounts before password has been entered

### ISSUE THREAD

**Issue by petefoth** [thunderbird/thunderbird-android#5576]
**Describe the bug**
After importing account details and choosing not to enter passwords immediately, I believe the app will attempt to login with no password, triggering protective measures (e.g. fail2ban) at the server 

***Background***
My email provider (WebArchitects Co-op https://www.webarch.info/) started to refuse connections from my home Broadband. When I contacted them, they said this was because of repeated attempts to login using invalid credentials. Resetting my router would temporarily "fix" the problem, because it would be assigned a new (unbanned) IP address by my ISP. Connecting using the phone's mobile internet would also (temporarily) fix the problem.

I have been testing phone custom ROMs, and the devices I am testing all use K-9. To save time, I have exported all the account settings. The problem stated to occur after I had imported the settings on a new  installation, but chosen not to input account passwords immediately. I don't have logs, but what I assume is happening is that K-9 is repeatedly attempting to login to the email server without a valid password, ad eventually triggering fail2ban (or whatever else the provider uses to protect the server).

**To Reproduce**
1. Install K-9 and run it for the first time
2. Choose 'Import settings' and select a file containing one or more valid account details. In my case these are all IMAP accounts, configured for Push
3. When prompted to enter passwords, choose 'Later'
4. Leave the phone switched on
5. Some time (several hours?) later, try to connect to the email server - in my case using Thunderbird on a laptop, *or* using the server's webmail interface in a browser - from the same intenet connection as that used by the phone. Connections are refused by the email server

**Expected behavior**
It would be good if K-9 did not attempt to connect to an email server if no password has been set for an account

**Screenshots**
Sorry - none available

**Environment (please complete the following information):**
 - K-9 Mail version: 5.802. But the problem occurred previously on June 14 2021, though I didn't work out why, bit I was also testing phone custom ROMs around that time. I would have been using whatever 5.7nn beta was current at that time, maybe 
 5.734?
 - Android version: Note version dependent. Occurs on both Android 10/Q and 11/R
 - Device: Various Sony Xperia devices, including Z3, Z3 Compact and XZ1 Comact. All running Q or R builds of /e/ OS (https://e.foundation/e-os/)
 - Account type: [e.g. IMAP, POP3, WebDAV/Exchange]

**Logs**
Again, no logs available - sorry

**Comment by petefoth** [comment]
I'm pretty this issue did not emerge until 5.7 as I recall that with 5.6 I had to enter passwords immediately after importing the settings

**Comment by cketti** [comment]
The fix will be included in K-9 Mail 5.804.
