### ISSUE TITLE
Permanent notification "waiting for new emails"

### ISSUE THREAD

**Issue by red-lichtie** [thunderbird/thunderbird-android#5583]
I don't need a permanent "@" notification to tell me that an Email Client is waiting for emails.
It also appears on the lock screen and I have no idea if a new mail is there or not without unlocking the phone.

Seriously, is it really a "Notification" for things like "Waiting for new emails" or "Sleeping until background sync is allowed"? I have only the choice of these 2!!! That or "None"!!! Which is awesome for an Email client.

On Android 7 there is no option to turn this permanent Status notification off.

The App should have it's own notification management and not rely on some new feature of the latest and greatest version of the operating system. On Android 7 it is all or nothing, allow notifications or not.

There should be a list of notifications that the app provides and the ability to individually (de)select them. I know I would turning off the "I'm working as I should" **notification**!

**Comment by cketti** [comment]
See #5521
