### ISSUE TITLE
K9 emaile receive plugin for tasker doesn't work anymore

### ISSUE THREAD

**Issue by K9-711** [thunderbird/thunderbird-android#5586]
It seems this functionality got disabled. Tried to downgrade K9 app but issue persists. Any workaround for using the plugin?

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.

For this particular question, see:
https://forum.k9mail.app/t/tasker-k9-email-received-event-no-longer-working/1218
