### ISSUE TITLE
Client certificate login fails with no error, shows 'Authentication failed' notification

### ISSUE THREAD

**Issue by mgvx** [thunderbird/thunderbird-android#5590]
**Describe the bug**
Right after upgrading to 5.804, K-9 shows an 'Authentication failed' notification. Clicking it takes me to the incoming server settings screen, where clicking next succeeds without showing me an error. Trying to check new mail from the main screen loops forever, does not work.

**To Reproduce**
1. Set up an account using IMAP with client certificates, and no password
2. Try to get new messages, it should not work

**Expected behavior**
I expected client certificate authentication to work.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.804
 - Android version: 11
 - Device: Samsung Galaxy S10
 - Account type: IMAP with client certificate authentication

**Additional context**
I suspect this commit introduced the bug: https://github.com/k9mail/k-9/commit/46c4e6fd8d82e59073c70fe5027b19def91e3ebb
It skips connecting to the server when there is no password, which is bad for client-certificate-only authentication.

**Comment by cketti** [comment]
> I suspect this commit introduced the bug: 46c4e6f

Sorry about that. The fix will be included in 5.805. In the meantime you might want to downgrade to 5.803.

**Comment by mgvx** [comment]
No worries, thanks for the quick reply!
