### ISSUE TITLE
Replying to mail received via mailing list does not address author.

### ISSUE THREAD

**Issue by sfadschm** [thunderbird/thunderbird-android#5606]
**Describe the bug**
When receiving an email via a mailing list (bounce), the headers show:
From: sender@domain.com
To: listName@lists.domain.com

No reply-to header is set.
When using the simple `reply` button/menu, the reply will be sent to the mailing list instead of the sender which is quite inconvenient.

Desktop programs like Thunderbird and Outlook sent replies to the address in the `From` header, which is the correct way, I suppose.

**To Reproduce**
1. Receive mail via mailing list.
2. Open `send` menu and click `reply`.
3. The reply will have the mailing list address in the `To` field.

**Edit:**
There is also this header:
Sender: listName@lists.domain.com
Does K9 use this header to get the response address?

**Comment by sfadschm** [comment]
[RFC2822](https://www.rfc-editor.org/info/rfc2822) says on this topic:

>  In the absence of the "Reply-To:" field, replies SHOULD by default be sent to the mailbox(es) specified in the "From:" field unless otherwise specified by the person composing the reply.

**Comment by cketti** [comment]
It's probably because of the `List-Post` header. See #3738 (and #2588).

**Comment by sfadschm** [comment]
Correct, just found that header.
