### ISSUE TITLE
Error when sending mail on my gmail account

### ISSUE THREAD

**Issue by JunkyardCat** [thunderbird/thunderbird-android#5607]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

If you are unsure whether or not you have found a bug please post to the support forum instead: https://forum.k9mail.app

**Describe the bug**
error when sending email in gmail

**To Reproduce**
1. compose message
2. write subject: Test
3.  write email: <own email>
4. error in notification bar
Failed to send some messages
Application-specific password required. Learn more at https://support.google.com/mail/?p=invalidsecondfactor <not sure if its safe to paste the rest as i think this is some kind of hash or something>

**Expected behavior**
send email without error

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: 5.802
 - Android version: 6.0.1
 - Device: J7 Prime
 - Account type: IMAP enabled

**Additional context**

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
The error message is from Gmail and it's telling you exactly what the problem is: Application-specific password required.

See https://support.google.com/mail/answer/185833?hl=en
