### ISSUE TITLE
Notification not syncronized with emails status

### ISSUE THREAD

**Issue by Massedil** [thunderbird/thunderbird-android#5608]
Reproduce :
- Go to your email inbox and manually refresh it to receive a new email
- A new notification is then displayed for this new email 
- To be sure to reproduce : 
  - Go to the Android home app
  - Remove k9 from the opened apps
  - Open again k9
- Read this email and/or archive it

Expected : 

- The new email notification about this email disappears because the email is read

Actual : 

- The notification stays forever
- If you click on the notification and the email is already archived, a blank mail is displayed

---
- K9 5.804 from Fdroid.
- IMAP account
- Android 11 (LineageOS)
- Samsung Galaxy S5 (klte)

**Comment by cketti** [comment]
You didn't provide any of the information that could help to find and/or to reproduce this bug. What K-9 Mail version are you using? What account type are you using? How exactly do you "read this email and archive it"?

Next time please use one of the issue templates to create a new issue: https://github.com/k9mail/k-9/issues/new/choose

**Comment by Massedil** [comment]
Sorry !
- k9 5.804 from Fdroid. 
- IMAP account
- I open the email from the main k9 screen

**Comment by Massedil** [comment]
Blank screen opened from an unlinked notification :

![Screenshot_20210823-165531_Trebuchet](https://user-images.githubusercontent.com/20357783/130469941-2b0b64aa-e592-4758-bb2e-79422cf56e73.png)

**Comment by Massedil** [comment]
If I just send an email to myself, update my inbox and read the email immediately, the notification disappears immediately as expected. 

But if I send an email to myself, update my inbox, go to my home app, close k9 from the Android menu (the notification stays), then open k9 again, read the email, this time the notification stays as described.
