### ISSUE TITLE
K-9 (5.804 from F-Droid) unable to send email

### ISSUE THREAD

**Issue by rich123** [thunderbird/thunderbird-android#5613]
**Describe the bug**
K-9 mail was working to send emails.  Then F-Droid upgraded to 5.804.  Whereupon K-9 mail could no longer send emails and now posts an alert stating: "Authentication failed" / "Authentication failed for ____. Update your server settings".

**To Reproduce**
1. Go to Outbox (with an email waiting to send in the outbox)
2. Click on "Send messages"
3. See error appear.

**Expected behavior**
The email is sent.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.804 - latest F-Droid version
 - Android version: 7.1.1
 - Device: Moto E4
 - Account type: SMTP to local Postfix server, unauthenticated, on port 25
 - Outgoing server is set to my local network mail server DNS name (the IP is a 10.0.0.x local network IP) with security set to "none" port set to 25 and "require sign-in" unchecked.

**Logs**
The only debug log item that relates to "sending" a pending email are the following two lines:

08-23 22:26:33.428 23532 23552 I MessagingController: Running command 'sendPendingMessages', seq = 417 (background priority)
08-23 22:26:33.447 23532 23552 I MessagingController:  Command 'sendPendingMessages' completed

However, I did capture the SMTP session between K-9 and my computer that is running my Postfix server, it is below:

> Server data                                           
< K-9 data

>220 ___._____.___ ESMTP Postfix
<EHLO [127.0.0.1]
>250-d820.dp100.com
>250-PIPELINING
>250-SIZE 40960000
>250-VRFY
>250-ETRN
>250-ENHANCEDSTATUSCODES
>250-8BITMIME
>250-DSN
>250 SMTPUTF8
<QUIT

**Additional context**
Downgrading to K-9 5.803 via F-Droid results in emails being sent via the same server where 5.804 simply sends a QUIT, with no change other than to downgrade K-9.

**Comment by ckujau** [comment]
Happens here with 5.805 on Android 11 too. The "Authentication failed" message appears even when "require sign in" is disabled, and it appears *immediately* with *no* communication between K9 and the SMTP server according to `tcpdump`. The "checking outgoing server settings" **is** caught by `tcpdump`, but the sending attempt is not, so it must fail before even attempting to establish a network connection.

**Comment by simpz** [comment]
Yup still broken with 5.805 from F-droid. Can't send to an SMTP server that doesn't need authentication.

**Comment by cketti** [comment]
This is a bug introduced when trying to fix #5576. The fix will be included in K-9 Mail 5.806.

**Comment by mintsoft** [comment]
Can confirm this is fixed for me in 5.806

**Comment by simpz** [comment]
Yup working now for me too in 5.806
Thanks

**Comment by rich123** [comment]
Original reporter here - confirmed that 5.806 from F-Droid can send emails again.  So issue is fixed.
I'll hit close, since I opened this one.
