### ISSUE TITLE
Fixed width too large for low-end devices

### ISSUE THREAD

**Issue by ulrichloose** [thunderbird/thunderbird-android#5643]
**Describe the bug**
With my low-end smartphone with only 440 px x 960 px, mail attachments are cropped on the right and you cannot load them - the button is missing. I'm not a professional, but it seems to me that three places in the UI are working with fixed values - width 300 dp - and that's too much ...

This fixed specification occurs in three places:

message_compose_attatchment.xml
message_view_attatchment.xml
message view_attatchment_locked.xml

**Environment (please complete the following information):**
 - K-9 Mail version: [5.9xx]
 - Android version: [10]
 - Device: [ulefone note 8p]

https://github.com/ulrichloose/k-9/commit/e8c41ebc9e702234446696a38bf9368d5966f28a

**Comment by ByteHamster** [comment]
Thanks for digging into this. Would you be up for opening a pull request with your change? Then cketti can review and merge it directly :)

**Comment by ulrichloose** [comment]
I am a little perplexed now ...

According to my calculations dp ppi dpi 300 should be completely sufficient for a display with 442 pixels width and nothing should be cut off - but it will ...

I compiled the whole thing again, but beforehand I created a device ulefone with the current display pixels in the Android Studio. There, too, it shows in the preview that the 300 should fit - but they don't, with 300 the entire download / delete button is cut off.

If you change the 300 to 275 in the three places mentioned, then everything is displayed perfectly.

Maybe you could just replace the 300 with 275?

https://github.com/ulrichloose/k-9/commit/3587e4d9ea928b10bbf379cca04bea41154993d7

**Comment by cketti** [comment]
Maybe Android's *display size* setting on your device is set to something larger than *default*.

**Comment by ulrichloose** [comment]
I can now understand that in Android Studio. 442 x 960 with a 5 inch diagonal simulates the identical "error" ... With the screen resolution of 19.5: 9, 300dp cannot be displayed, a maximum of 270dp is possible. Personally, I don't find such fixed information particularly nice - I think my first "solution" is better - also at the price that the display field then fills the entire width in landscape format.

That is certainly not particularly important - I can easily change that for myself if there are important innovations.

**Comment by cketti** [comment]
Sounds like your screen falls between density buckets. According to gsmarena your display has a density of 192dpi. It's probably configured as an hdpi (240dpi) device when in reality it's closer to mdpi (160dpi). The effect is that all UI elements are displayed quite a bit larger than intended. Under normal circumstances an attachment box with a width of 300dp should be able to fit on a 5 inch screen just fine.

Still, we should support "small" screens. Android's resource system makes it easy to have different layouts. So we can fix the way attachments are displayed on your device without changing how the attachment boxes look on other devices (or in landscape orientation).

**Comment by cketti** [comment]
@ulrichloose: Can you please check if PR #5647 fixes the issue on your device.

**Comment by ulrichloose** [comment]
It works perfectly!
In landscape Mode as intended 300 dp and in normal mode it fills the horizontal without cutting anything off.

Thank you very much!
