### ISSUE TITLE
Excessive battery drain and data usage

### ISSUE THREAD

**Issue by EkriirkE** [thunderbird/thunderbird-android#5660]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

If you are unsure whether or not you have found a bug please post to the support forum instead: https://forum.k9mail.app

**Describe the bug**
About a month ago K9 has been spinning it's wheels in the background draining my batter and making my phone hot.  I've have to turn on battery optimisation and choose to restrict background to make it stop.  I noticed you've made some releases that relate to battery but haven't done anything to improve this new effect I'm seeing.
Also the biggest consumer of my data plan I K9.  And I only really use it to get main notifications with the summaries.  I do not actively open emails much less download attachments and it's consumed over 1GB this month! My whole email folder isn't even that big

**To Reproduce**
1. Go to turn on your phone
2. Click on the wake button
3. Scroll down to anything but K9

**Expected behavior**
Moderate to no battery or data usage in the background.

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: 5.896
 - Android version: 10
 - Device: OnePlus 7 Pro EU
 - Account type: IMAP

**Additional context**
I don't even have to launch K9, just a fresh boot and I get a hot short-lived phone

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

How many accounts do you have set up? How are they configured? Automatic polling (what interval)? Push?

**Comment by EkriirkE** [comment]
> Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

This is pretty short & unedited, but it happened today as I'm writing this - I only just managed to get home and plugged in to pull the log (2%)

https://pastebin.com/kmAT2vrz

> How many accounts do you have set up? How are they configured? Automatic polling (what interval)? Push?

1 IMAP account, Local size 100, Poll 15m, push & poll "only 1st class folders", 10 folders to push, refresh idle 24m.  Auto namepace, use compression

**Comment by EkriirkE** [comment]
If I do a live logcat `logcat | grep k9`, I see new one of these every 1-10s

09-12 17:10:36.165 22094 22107 I com.fsck.k9: Background concurrent copying GC freed 67740(67MB) AllocSpace objects, 0(0B) LOS objects, 46% free, 27MB/51MB, paused 126us total 126.675ms

**Comment by cketti** [comment]
It doesn't look like you've enabled debug logging inside the app.

**Comment by EkriirkE** [comment]
> It doesn't look like you've enabled debug logging inside the app.

It is, I just double checked

**Comment by cketti** [comment]
Please use the commands from the wiki page to grab the log. Using grep you'll only get the lines containing the string "k9".

**Comment by EkriirkE** [comment]
The pasebin was generated using the wiki steps verbatim (with PID replacement)

I only commented about grep secondarily (Oddly those dont capture to a file if I redirect output of grep...)

**Comment by cketti** [comment]
The "Background concurrent copying GC freed" messages are from the garbage collector, indicating that the app is doing something in the background. However, there definitely should be log messages from the app itself.

The "Failed to chmod(/data/user/0/com.fsck.k9/databases/preferences_storage): android.system.ErrnoException: chmod failed: EPERM (Operation not permitted)" messages are concerning. They indicate something goes wrong when accessing the database containing K-9 Mail's settings.

Unfortunately, this is not much to go on. I'm guessing there's some data corruption. My advice is to uninstall the app, then reinstall. This should ensure that a) all app data is removed and b) a fresh copy of the APK is fetched.

You should try exporting your settings first. If there's data corruption this might not work. But we do have checks in place to discard invalid settings on import. So trying to import (partially) corrupt settings after the re-installation shouldn't cause any problems.

**Comment by EkriirkE** [comment]
> You should try exporting your settings first. If there's data corruption this might not work. But we do have checks in place to discard invalid settings on import. So trying to import (partially) corrupt settings after the re-installation shouldn't cause any problems.

I did this, uninstalled and re-installed K9 and re-imported settings.  The data usage seems to have gone down, but the battery drain persists.   They might be related but I can't spare the data right now to test

**Comment by iwismer** [comment]
I'm having the same battery drain issue. I've followed the steps for getting a debug log and have attached it.
[k9-log.txt](https://github.com/k9mail/k-9/files/7558042/k9-log.txt)

**Comment by cketti** [comment]
@iwismer: Did you enable debug logging under *Settings > General settings > Debugging > Enable debug logging*? The log you attached doesn't seem to contain any of K-9 Mail's debug messages.

**Comment by iwismer** [comment]
Yes, debug logging has been enabled for the last few weeks, as I've been trying to get logs of this problem occurring. 
![Screenshot_20211120-103331_K-9 Mail](https://user-images.githubusercontent.com/10574297/142732150-6074fb90-1911-4a62-85aa-9d8180086106.jpg)

**Comment by cketti** [comment]
@iwismer: Strange. Can you please force stop the app and record a log when launching it again?

**Comment by iwismer** [comment]
Attached the log!
[k9-log2.txt](https://github.com/k9mail/k-9/files/7575380/k9-log2.txt)

**Comment by cketti** [comment]
Thanks. Unfortunately, in that log everything looks fine :disappointed: 

Are you able to keep your device connected to the PC and keep logging until the log only shows messages from the garbage collector (like in your first log)? Maybe the last K-9 log messages will give an indication of what is going on.

`adb logcat --pid=<PID> | tee k9-log.txt` should do the trick.

**Comment by iwismer** [comment]
I'll try to get another log of it when it's draining battery, but the issue is not consistent, and I haven't figured out a trigger for it yet.

**Comment by cketti** [comment]
Any updates on this? Is this still happening with the latest K-9 Mail version?

**Comment by iwismer** [comment]
I have not been able to reproduce it since, so seemingly it's fixed for me.
