### ISSUE TITLE
Attachment download with duplicate filename: adding number after extension prevents third-party file manager from recognising file type

### ISSUE THREAD

**Issue by ssb22** [thunderbird/thunderbird-android#5669]
K-9 Mail version 5.806 on Android 10.  Opened an email with an MP3 attachment, filename is recording.mp3, pressed ⤓ to download, saved as recording.mp3, tapped on it in Speed Software's Explorer v3.10.2 which opened it in VLC 3.3.4, so far no problem.  Back in K-9, opened a second email which also had an MP3 attachment, and the filename was also recording.mp3, pressed ⤓ to download, this time the suggested name was "recording.mp3 (1)" which I accepted without thinking, and now Explorer didn't recognise it as a file that should be opened in VLC until I manually renamed it to "recording (1).mp3" i.e. the "(1)" should come before the extension to make file managers still recognise the file type.

I did a quick search through the code to see if I could find which part handles the (1), (2) etc suffix, but it seems my 'grep' skills were not quite good enough to find it.

**Comment by cketti** [comment]
K-9 Mail is using system functionality to save attachments. It passes the original file name to the system and is not involved in the handling of duplicate file names at all. The Android versions on my devices add a number before the file extension, not at the end of the file name. If that doesn't work on your device, it's a bug in the Android version you're using.

**Comment by ssb22** [comment]
Thanks.  For the record (in case anyone is finding this via search), I'm on a Galaxy S9 (SM-G960F), OneUI 2.5, Android 10.  I seem to remember this behaviour did not occur a few months ago (when it did insert the number before the extension) so it must be a recent regression.  Or at least, I don't remember having this exact problem a few months ago, so if Android has not changed its file naming behaviour then perhaps Explorer has lost the ability to open files that have numbers after their extensions, although I can't think why they would drop such a feature.

Also I was slightly incorrect in my description: K-9 only prompted me to save the second recording as "recording.mp3", it was the system that then changed it to "recording.mp3 (1)" but not on-screen (I had to go into Explorer to see it had done this).
