### ISSUE TITLE
No more notification sounds since 5.9(ish)?

### ISSUE THREAD

**Issue by binarydad** [thunderbird/thunderbird-android#5679]
I'm currently using 5.901, though I'm not sure if the issue started in 5.900. I noticed that whenever email comes in, I get the notification popup, but no longer any sound. There was one time where it played part of the sound once, but that was it. 

The phone is a Galaxy S8 running Android 9. 

This used to work prior to this version. Thanks.

**Comment by cketti** [comment]
Seems like the first notification won't make a sound. If there's already a notification and a new message arrives, the notification sound is played.
