### ISSUE TITLE
All draft emails in gmail account are encrypted

### ISSUE THREAD

**Issue by goduck777** [thunderbird/thunderbird-android#5683]
**Describe the bug**
I have several Gmail and Gapps accounts. Recently I found that all the emails in Draft are shown as \*encrypted\*, and when I click it, the app just crashes.

**To Reproduce**
1. Open a Gmail account
2. Open Draft folder
3. Click one of the emails
4. App crashes

**Expected behavior**
Emails should be opened

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806
 - Android version: 11
 - Device: OnePlus 8
 - Account type: IMAP

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by changliu777** [comment]
It seems a thunderbird bug which encrypted all the drafts by default and there is no way to turn it off.

I will wait for thunderbird 91 and check again.

**Comment by goduck777** [comment]
This issue is resolved in Thunderbird 91.
