### ISSUE TITLE
Don't  subscribe server-specific imap folders

### ISSUE THREAD

**Issue by EpeR1** [thunderbird/thunderbird-android#5706]
When I select all folder in folder subscriptions, K9 automatically subscribes all folders in the imap server, inclusive the server-specific folders, like: "dovecot" and/or "sieve", which causes errors.

These folders are configured in the dovecot mailboxes.conf with like:

      mailbox dovecot.sieve {
         auto = no  
      }

There is no other configuration way in dovecot to hide them.
Other mail clients (Thunderbird, Evolution) are handling well these folders, but K9 subscribes them forcibly.

Tested with K9/5.806

**Comment by cketti** [comment]
By default K-9 Mail doesn't use IMAP's folder subscription mechanism. If you wish to do so, check *Settings > [Account] > Fetching mail > Incoming server settings > Show only subscribed folders*. 
K-9 Mail doesn't support changing the list of subscribed folders on the server. However, you can configure which folders to display in K-9 Mail. See https://k9mail.app/documentation/folders.

**Comment by EpeR1** [comment]
Ok, Thank You!
This is a feature, not a bug. :)

The Solution was the "Show only subscribed folders"  option, but I think, it can be the default option in imap mode.

**Comment by cketti** [comment]
I bet the majority of email users today don't know that server-side folder subscriptions are a thing. We're not going to make their life harder by using them by default.
