### ISSUE TITLE
Cannot implement intent for picking attachment

### ISSUE THREAD

**Issue by luisfl** [thunderbird/thunderbird-android#5714]
This is not a true bug report, but instead a feature request against the documentation.

I made a filemanager that could be used to pick files for K9. Yet, at certain point, the `android.intent.action.GET_CONTENT` intent stopped working for K9.

I went to the documentation, and it says very little, only that OI filemanager implemented it properly.

Could you please update the documentation (and post it here) telling how to properly build the intent for K9 to use?

**Comment by cketti** [comment]
This is not an Intent specific to K-9 Mail. If you implement it according to the [official documentation](https://developer.android.com/reference/kotlin/android/content/Intent#ACTION_GET_CONTENT:kotlin.String), things should work fine with K-9 Mail. Specifically, you'll have to return a `content:` URI, not a `file:` URI.

**Comment by luisfl** [comment]
> This is not an Intent specific to K-9 Mail. If you implement it according to the [official documentation](https://developer.android.com/reference/kotlin/android/content/Intent#ACTION_GET_CONTENT:kotlin.String), things should work fine with K-9 Mail. Specifically, you'll have to return a `content:` URI, not a `file:` URI.

Actually, the documentation you referred to is to ask for the content (like in the K9 source code), not to answer for it. I am doing something wrong in the Manifest, since my app is not answering K9 request.

**Comment by luisfl** [comment]
According to [this answer by @CommonsWare in StackOverflow](https://stackoverflow.com/questions/69442931/why-my-action-get-content-is-not-working-but-action-pick-works?noredirect=1#comment122741533_69442931), on modern versions of Android is handled purely by the OS. So it seems that we are forced to use what the OS wants with K9. What a pity.

**Comment by cketti** [comment]
ACTION_GET_CONTENT works just fine. Apps supporting this Intent will be displayed in the side drawer of the system file picker. 

Example of an app that supports ACTION_GET_CONTENT: https://github.com/cketti/AttachContact/blob/master/app/src/main/AndroidManifest.xml

**Comment by luisfl** [comment]
> ACTION_GET_CONTENT works just fine. Apps supporting this Intent will be displayed in the side drawer of the system file picker.

Yes. So you have to do perform extra clicks if you want to use your own app... My app handles that. I just wanted to bypass the system file picker completely. It seems this is no longer possible, and it was possible before.

**Comment by cketti** [comment]
I see. I believe the current behavior was introduced with Android 4.4. So it's not exactly a recent change.

**Comment by luisfl** [comment]
I don't know when it changed, but I used my File Manager with Android 6 (Lineage). But that is also an old OS.

Anyway, the information in [K9 documentation](https://k9mail.app/documentation/development/intents.html) is kind of misleading since it says that OI Filemanager handles the ACTION_GET_CONTENT. Only after you open the system file picker...

It would be nice if K9 also implements other intent to bypass the OS.

**Comment by cketti** [comment]
The documentation was outdated anyway. I've removed it from the website. See https://github.com/k9mail/k9mail.github.io/pull/155
