### ISSUE TITLE
Display/Count Error: Notifications

### ISSUE THREAD

**Issue by omexlu** [thunderbird/thunderbird-android#5715]
Hello,

If there are more than 3 unread mails the app shows that there are 4 mails but actually there are only 3 mails. Can also be with more mails but not tested yet. 

The last mail is then shown twice in the notification line and in the batch.

Current version and Android 11.

Is the problem known?

Thanks in advance.

**Comment by cketti** [comment]
>  the app shows that there are 4 mails

Where exactly?

> The last mail is then shown twice in the notification line and in the batch.

Can you provide a screenshot? Are you sure it's one message being displayed twice and not two different messages with the same content (e.g. a message that you send to yourself will show up in the Inbox and the Sent folder, those are two different messages).
Did you configure folders other than the Inbox to be automatically checked for new mail?

What K-9 Mail version are you using?

Next time please fill out the issue template.

**Comment by omexlu** [comment]
- In the notification-bar and counter-catch of the app.
- All messages are send from a external test-server to different email-adresses added in K9.
- I send the testmails from an account not inserted in K9.
- I sync all folders on the IMAP-Server.
- Here I send 3 seperate mails from one external Emailadresse to 3 seperate addresses inserted on K9, it shows some of them twice in the notification-bar and 4 instead of 3 in the batch.

Screenshots below:
![Screenshot_2021-10-01-20-18-44-667_com android chrome~2](https://user-images.githubusercontent.com/3801660/135668910-5857a1e7-f9ed-4c73-960d-7fdfa348bd57.jpg)
![Screenshot_2021-10-01-20-18-56-349_com teslacoilsw launcher~2](https://user-images.githubusercontent.com/3801660/135668926-b1cbfcf1-57a7-4cde-9b39-ef61078339b6.jpg)
![Screenshot_2021-10-01-20-18-44-667_com android chrome~2](https://user-images.githubusercontent.com/3801660/135668946-43500b03-1b93-4e77-a47b-8036078d688c.jpg)


I hope you can reconstuct this and understand what I mean, it definitely show false in notification bar and batch, inside the appapp only 3 are shown.

Thanks in advance.

**Comment by omexlu** [comment]
![Uploading Screenshot_2021-10-01-20-21-56-468_com.fsck.k9~2.jpg…]()

**Comment by omexlu** [comment]
![Screenshot_2021-10-01-20-21-56-468_com fsck k9~2](https://user-images.githubusercontent.com/3801660/135669464-51bd4652-3311-413b-9e33-d22b1bec13c6.jpg)

**Comment by cketti** [comment]
Is the account showing duplicate messages a Gmail account? If so, are you synchronizing the "All Mail" folder?

**Comment by omexlu** [comment]
No we are not talking about Gmail accounts either.
The emails only go to the inbox here.

Thanks a Lot.

**Comment by cketti** [comment]
To get a better understanding of what's going on we need more information. Please record a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by omexlu** [comment]
Sorry that unfortunately too cumbersome for me to make my time too short and detailed tests.

But the fact is unfortunately that there is a problem here and the problem can certainly be recreated with you.

Thanks anyway.

**Comment by cketti** [comment]
I can't reproduce the issue on any of my devices. And so far nobody else has reported such a problem. So chances are there's something special about your setup. Without more information there's not much we can do track down the bug.

Should you decide to record the debug log after all, please open a new issue.

**Comment by omexlu** [comment]
@cketti 

Could this perhaps be related to "frequency of email request" and push folder?

I have set 15 minutes for the first option.

Maybe these two get in each other's way?

Thank you.

**Comment by cketti** [comment]
It doesn't really make sense to use polling and push for the same folder. But the two should not interfere. Folders are not synchronized simultaneously.

**Comment by omexlu** [comment]
Hm, if they don't get in each other's way, then I don't know what the problem is, I don't have any unusual configuration now.
