### ISSUE TITLE
Why does fdroid have 5.903 while github has 5.806

### ISSUE THREAD

**Issue by Thewisem** [thunderbird/thunderbird-android#5716]
There is a changelog and apk for 5.806 in github. But fdroid has 5.903 which is weird? Where did fdroid get those versions?

**Comment by cketti** [comment]
K-9 Mail versions whose minor version number starts with an odd digit are beta versions. All of them are available on GitHub, too. See https://github.com/k9mail/k-9/releases and https://github.com/k9mail/k-9/wiki/ReleaseNotes

In the future please use the [forum](https://forum.k9mail.app/) for questions like this one.
