### ISSUE TITLE
"K-9 Accounts" widget stops working after device reboot

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#5738]
**Describe the bug**
A "K-9 Accounts" widget (launcher shortcut, really) configured to open a particular account, will open the default account or Unified Inbox after a device reboot.

**To Reproduce**
1. Drag the "K-9 Accounts" widget tile to the home screen
2. In the configuration screen select an account that is not the default account
3. Tap the newly created widget to confirm it is opening the configured account
4. Reboot the device
5. Tap the widget
6. It behaves like tapping the app icon: the default account or Unified Inbox is opened (depending on your configuration)

**Expected behavior**
The configured account should be opened after a device reboot.

**Environment:**
 - K-9 Mail version: 5.904
 - Android version: 11
 - Device: Pixel 2, Pixel launcher

I suspect it's because we serialize a `LocalSearch` instance in the launch Intent and deserialization fails after a reboot.

**Comment by UstedLoco** [comment]
+1, on Samsung S10 with Nova launcher

**Comment by sebastianries** [comment]
+1 (still valid)
K9-Mail: 6.200
OS: LineageOS 19 (19-20220618-NIGHTLY-alioth)

And: I saw this behavior without rebooting the phone.
It happens after 1 or 2 days but I did not find out when exactly.
