### ISSUE TITLE
K9 suddenly removed every settings - now no custom sound can be set anymore

### ISSUE THREAD

**Issue by Tagirijus** [thunderbird/thunderbird-android#5761]
**Describe the bug**
I shut off my mobile phone every night. This morning I started it and wanted to check mails, suddenly out of nothing K9 wanted me to set up everything, like I installed it freshly.

Now I tried to set up everything again, and now I cannot set up a custom notification sound for my two account. I know it was possible before ... I cannot even set up any sound at all. The notification settings always lead to the Androids ones. And there, I knew!, it was possible before to set up custom sounds for the accounts seperately ...

**To Reproduce**
Regarding the notificatoin thing: click on notification for an account so that it opens the Android settings ... no option for me to chose a sound at all.

**Expected behavior**
Regarding the first thing: I'd like K9 t not make this again ... removing all my settings out of nothing ... By the way: te last update via Google Play Stoe was on 1th Sep 2021. The problem suddenly occured this morning on 30th Oct 2021 ... so almost two month after this. I never update other app automatically. So I am 100% sure that I did not update any other app actively.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806
 - Android version: 8.0.0
 - Device: Huawei P8 Lite 2017
 - Account type: IMAP

**Comment by ByteHamster** [comment]
Could you please take a screenshot of the Android notification settings? They should have an option to select the sound. Note that you can touch the name of the notification channels, not just enable/disable them with the checkbox

**Comment by Tagirijus** [comment]
Hi! Thanks for your reply. I think I absolutely know what you mean and before this whole issue here, I remember that I was able to set up different notification sounds for the different notification channels, which even were labeled after my mail accounts. Now I can only see this screen in the notification settings:

![K9 notification settings](https://i.imgur.com/dLjUN7E.jpg)

Also sorry for the english / german mix. I switched my phone to english just for the screenshot, but apparently some texts are still german ... :D ...

Not sure if this screenshot may help. Also inside these categories you can see there there are only options for:

- Display in the status bar
- Banners
- Lock screen notification
- Priority display
- Ringtone
- Vibrate

But no account name there neither.

**Comment by ByteHamster** [comment]
Looks like your device vendor decided it's not important to show the account names. Man, why do vendors take a fully working operating system and then deliberately break random stuff...? It is so annoying to work around the crappy software that some vendors ship. I feel like this is getting more and more recently.

Each of the "Nachrichtenanzeige" channels belongs to one of your accounts. You can set the notification sound there. Because the device vendor broke the settings screen, you can either just experiment which one is which or you can use the link that is shown on K-9's notification settings screen of each account (if they didn't break that too).

**Comment by Tagirijus** [comment]
Hey there, thank you for your new reply on this. I totally did not recognize that there are two "Nachrichtnanzeige", wow ... the thing is, though: both do only allow to enable or disable things. I clicked multiple times on the ringonte ... no even on every single option on every position. I totally know what you mean: before this whole issue I could click the label instead of the checkbox and it opened up a sound-chooser or so. By the way, the notification management for both "Nachrichtenanzeige" look like this:

![Notification manageent](https://i.imgur.com/OKSOiX0.jpg)

The other thing is: I updated absolutely **nothing** before this all happened! Now I exported my K9 settings, deleted all the data, deinstalled it, cleared my unused files and installed K9 again, imported my settings and so on. Did not help.

I bet that it won't help if I contact Huawei on this, right? . . .

Thanks for your help. More and more I see that it might be a systems thing and not K9.

**Comment by ByteHamster** [comment]
> I bet that it won't help if I contact Huawei on this, right? . . .

I guess not... They probably messed this up deliberately.

> More and more I see that it might be a systems thing and not K9.

I don't have more ideas, sorry. At this point I would assume it's the device vendor's fault.

**Comment by Tagirijus** [comment]
Thanks for at least trying to help here, I really appreciate it.

The Huawei support told me multiple times to _"contact the developer of the app, because it must be on their site"_ (basically). I now wonder if this new notification setting thing is an Android standard or so? I mean: yes, before the last bigger K9 update, the notifications could be set up in K9. Now the setting has to be made in the Android settings. So I guess this must follow some kind of _Android specification_, right? Is there something I could hint the support to to show them that K9 is doing everything right?

**Comment by ByteHamster** [comment]
Setting notification sounds using the Android settings menu does not work with other apps on your device either, right?

> So I guess this must follow some kind of Android specification, right?

The Android specification for notification channels would be this: https://developer.android.com/training/notify-user/channels. On the screenshots there, a channel has a sound setting.

**Comment by Tagirijus** [comment]
> Setting notification sounds using the Android settings menu does not work with other apps on your device either, right?
Yes. I also told the support, but no response to this specific info . . .

Thanks for the link regarding this specification; I'll forward it to the support and we'll see!

**Comment by Tagirijus** [comment]
So: I had a K9 reset today again. I absolutely did nothing but technically restarting my device (as I do every day, since I turn it off over night).

Update regarding the Huawei support: they are totally stubborn. I literally had contact to 4 or 5 **different** support people and they did not seem to really read my mails, but liked to post copy&paste texts into the mail and wanted me to rate their support (from the first mail on). People: **never ever** buy Huawei . . .

Best thing, when I asked if they could maybe tell me the root pasword so that I maybe could dig deeper into the system and fix things on my own they told me that they don't do that, becaue _"they want to assure the best user experience"_ yeah ... because everything is so fine for me right now wow! ... they are so unbelievable stu.... eh, _"unlogical"_. It drives me sooo crazy sorry for that -_-

I guess in case nobody else will have such an issue, the issue is maybe good to close. I guess I hve to buy a new phone to fix this; how ridiculous. )=

**Comment by gburel** [comment]
Hello,

I had already 3 or 4 such resets too. They seems to come out of nowhere (not even restarting the device). Fortunately I have now exported my settings so I can import them, but I have to reenter the passwords, which is very annoying with Yahoo's application passwords that need to be regenerated.

The thing is that I own a Huawei P8 Lite 2017 too, so there may be a hint there. 

Concerning the sound notification problem, when I am redirected to the Android settings, I can choose to be notified by a sound, but I cannot choose which sound, or at least not there. Since I am not interested by changing it, I never cared.

Environment:

-  K-9 Mail version: 5.807
-  Android version: 8.0.0
-  Device: Huawei P8 Lite 2017
-   Account type: IMAP

**Comment by Tagirijus** [comment]
Wow ... this really sound like it might have something to do with the P8 Lite 2017 ... oh bummer. )= Thanks for your comment after all! (=

**Comment by cwchristerw** [comment]
This affects also my Honor 8.

**Comment by cketti** [comment]
For losing all account data see #750. Check out the latest beta version to see if this fixes the issue.

Notifications and working around various vendor bugs is a focus of the 5.9xx versions. Starting with K-9 Mail 5.912 you can configure a notification sound inside the app.

**Comment by Tagirijus** [comment]
Thanks for the info, cketti! Looking forward to the next updates then. <3

**Comment by Tagirijus** [comment]
Thanks for the latest update! Custom notifications are working again. Great! (=
