### ISSUE TITLE
Push notifications refer to wrong email

### ISSUE THREAD

**Issue by lewri** [thunderbird/thunderbird-android#5762]
**Describe the bug**
On my phone, when a push notification from K9-Mail comes through to my lock screen it often references the oldest new message rather than the actual new message.
Note: This isn't the notifications in the pull-down notification bar, that is normal (see image examples below)

E.g. Message 1 comes into my inbox and notifies me. I do not read it (or read it on another platform).
Message 2 then comes in, but notifies me about Message 1 instead.

**To Reproduce**
1. Open K9 App to make sure it's active
2. Go back to home screen and lock screen
3. Wait for new messages
4. See issue above

**Expected behavior**
The push notification should reference the relevant new message.

**Screenshots**
Push notification from lock screen in OxygenOS
![Screenshot_20211030-223341](https://user-images.githubusercontent.com/20030128/139559007-8d8b7e12-a701-40e2-896f-a15cc61a9fd9.jpg)

Notification drawer
![Screenshot_20211030-223651](https://user-images.githubusercontent.com/20030128/139559103-66fccaa4-0722-4fd8-b132-7df347342c13.jpg)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806
 - Android version: 11 (Oxygen OS 11.1.5.5.AC01BA)
 - Device: OnePlus Nord (1st Generation)
 - Account type: IMAP

**Additional context**
Pretty sure this error started when the new wave of development for the Google Play version started again.

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment]
This feels like a bug in the Android version you're using. The lock screen should display the summary like it does in the notification drawer (one entry that lists sender and subject of the lastest 5 messages), not an individual notification.

**Comment by lewri** [comment]
I think it also happened on my older phone on Android 9 (Honor 9), albeit the app was very out of date it still did this issue.

**Comment by lewri** [comment]
If it helps, this is the setting that makes the first image happen
![Screenshot_20211206-093859](https://user-images.githubusercontent.com/20030128/144823136-739c4798-029b-420d-ab89-7585ba43df78.jpg)

**Comment by cketti** [comment]
From K-9 Mail's point of view there's no such thing as "ambient display notifications". There's only notifications. What your Android version does with them, is not under K-9 Mail's control.
