### ISSUE TITLE
Nothing loads / Takes forever to load @ "All Messages"

### ISSUE THREAD

**Issue by dm17** [thunderbird/thunderbird-android#5772]
Android 13 - Latest K-9 from F-DROID --
Mentioned by @utack & I in this thread: https://github.com/k9mail/k-9/issues/791

I'm using Gmail + K-9. The server search wouldn't work. So I changed the settings to store all messages locally, which I would like anyway in case I need to use mail offline. Since it downloaded all messages (4000 in inbox & 20,000 All Mail), the app does not show anything. It is just blank. If I leave it open for a minute or so, then it sometimes will load. Once all the messages load (perhaps that isn't how it should be working) - the app will then hang when navigating around.

"Local Folder Size: All Messages"

**Comment by utack** [comment]
Same for me, it takes a very long time to show the message overview
This was not happening before the re-design
Also happening when I set the "preview lines" to 0 instead of 2

It seems to be resolved when I un-tick "names from adress book"
  
Latest Play Store Version 5.806 on a Galaxy S21 with Android 12

**Comment by dm17** [comment]
> Same for me, it takes a very long time to show the message overview This was not happening before the re-design
> 
> It seems to be **resolved when I un-tick "names from adress book"** in the general display options, so matching a large message DB against a large Contact DB seems to have regressed
> 
> Latest Play Store Version 5.806 on a Galaxy S21 with Android 12

I'm not seeing this setting. I see "Show contact names" - "Use recipient names from Contacts when available" ... But I never had this selected. Is this the one that solved the problem loading everything for you?

**Comment by utack** [comment]
I have the german version, It should translate to "Show contact names"

**Comment by dm17** [comment]
My "show contact names" is grayed out (unavailable). I have deselected "Show correspondent names" and "show contact pictures" - but it doesn't seem different. About 30s to load anything (when it works) it seems.

**Comment by cketti** [comment]
K-9 Mail currently loads data for all messages in a folder into memory when displaying the message list. Depending on your phone and the available memory this can lead to very poor performance.

Duplicate of #3472

**Comment by utack** [comment]
Has this behaviour changed with the material redesign?  
It was not a problem before

**Comment by dm17** [comment]
> K-9 Mail currently loads data for all messages in a folder into memory when displaying the message list. Depending on your phone and the available memory this can lead to very poor performance.
> 
> Duplicate of #3472

Well 6GB of RAM should be enough to load mail on a phone... So I'm doubting this is the only issue. I've moved back to using webmail in my phone's browser until I can get this working.

**Comment by ccpp** [comment]
> Has this behaviour changed with the material redesign? It was not a problem before

I confirm this in 2025 version 8.2.  Unified inbox loads after about 15 secs!
I can also confirm that **unticking** "Show contact names (use recipient names from Contacts when available)" solves it 

I suggest reopening this!

**Comment by kewisch** [comment]
Ah I see, this can sometimes be the case when thew Contacts app has a remote provider, so the call blocks until the remote side was queried. We might want to investigate if there is a way we can load those names more asynchronously, but what would we show in the meanwhile? I think a new issue specific to the recipient names might make more sense.

**Comment by ccpp** [comment]
Seems resolved now finally at 16.0. @dm17 agree?
