### ISSUE TITLE
Web.de mail stopped working: Command: *sensitive*; response: #2# [NO, authentication failed]

### ISSUE THREAD

**Issue by Evilbolzen** [thunderbird/thunderbird-android#5780]
**Describe the bug**
Yesterday (18.11.2021) at around 12 O'Clock I got the first time an error messages, displaying me that authentication from 4 out of 5 mail accounts were failing and that I have to check my server settings. Those 4 mail accounts all belong to german mail provider **web.de** and were configured as IMAP, the 5. account belongs to a different IMAP provider.

`Username or password is wrong. (Command: *sensitive*; response: #2# [NO, authentication failed])`

The strange thing: they worked before, to be more precise they worked since April 2020 (!!) and even after the major update with the new interface. Just to clarify: _I haven't made any changes ever since_, you know...never touch a running system and so

So my first panic was someone changes the passwords, so I checked them but they are still valid and there are no login from others devices/locations. Also checked if web.de removed the IMAP access, but it is still activated as it should be. 

So I checked the server adresses and settings mentioned by web.de, they are still the same. So I tried using mobile data, with/without vpn activated, a different wifi, still the error. So I tried a different email app, there the web.de mail works just fine. Deleted one of my mail accounts in k9 and added it again, still error messages.

**To Reproduce**
1. Just try to fetch any mails from the server and the error appears
2. Edit the server settings and pressing forward to check the settings

**Expected behavior**
On refresh loading any new mails from the server and no error messages

**Screenshots**

<img src="https://user-images.githubusercontent.com/57069516/142598973-ecfa9de1-31e1-4768-9254-18b87d1cb9ed.jpg"
width=40%>

<img src="https://user-images.githubusercontent.com/57069516/142599055-7e14e93b-8c49-4790-bd53-501ad93abc14.jpg" width=40%>

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806
 - Android version: 11 in Miui 12.5
 - Device: Redmi Note 8 Pro
 - Account type: IMAP

**Additional context**
Just tried to get mails from one mail account when I was generating the log file.

**Logs**
(removed my account names and passwords, you'll find things like "mail2" and "password2" instead)
[k9-log2.txt](https://github.com/k9mail/k-9/files/7569230/k9-log2.txt)

**Comment by cketti** [comment]
Things haven't changed in K-9 Mail either. So this was probably caused by something your provider did. The logs don't contain anything unusual. Please contact your email provider for help with this issue. We'd be happy to work around the problem in K-9 Mail once we know what exactly the provider's server doesn't like about the way K-9 Mail tries to authenticate.

**Comment by cketti** [comment]
Adding my newly created web.de test account to K-9 Mail 5.806 worked fine after [enabling POP3/IMAP access](https://hilfe.web.de/email/einstellungen/pop3-imap-einschalten.html) in the web interface. So this doesn't seem to be an issue that affects all web.de users.

**Comment by Evilbolzen** [comment]
> Things haven't changed in K-9 Mail either. So this was probably caused by something your provider did. The logs don't contain anything unusual. Please contact your email provider for help with this issue. We'd be happy to work around the problem in K-9 Mail once we know what exactly the provider's server doesn't like about the way K-9 Mail tries to authenticate.

Just could reach a tech support at web.de by phone. They were'nt aware of any issue on their side. They suggested (of course) to use their own app  or to reinstall K9 App. Did this just right now and (of course) nothing changes. They were "almost certainly sure" that it has to be K9 app, as others were still working.

> Adding my newly created web.de test account to K-9 Mail 5.806 worked fine after [enabling POP3/IMAP access](https://hilfe.web.de/email/einstellungen/pop3-imap-einschalten.html) in the web interface. So this doesn't seem to be an issue that affects all web.de users.

Tried that too, made a whole new account and this one is working after I added it to my k9, all others at this point not.....really....REALLY strange. (And as I wrote above, I had the pop/imap API activated on each account before). So I made a complete password recovery and reset of all settings on the web.de page for each of my accounts, set new passwords and also made a clean install of k9, now everything seems to work again. Just submitted this info to the web.de tech support, they wanted to know as well what the problem was. I'll post their reply if it arrives

**Comment by Evilbolzen** [comment]
Quick and most likely last update:

web.de isn't aware of any problems on their side. After I spoke to multiple people in the tech support at least one had a clue about the problem. He believes my login got "disabled" by the server as I fetched to often from my phone and pc that day (about 15 times per hour on each account). Since there is some major tracking distance between my pc and phone ip address (VPN) it sort of triggered a security mechanism that prevented me from logging in, well that's the guess of the tech support guy.

Why only K9 was bothered and even without using the vpn......don't know to be honest. Maybe some caching related issue from the server?!

So, since this won't get us any further I'll close this issue
Thanks for your feedback
