### ISSUE TITLE
One finger zoom stopped working after webview update

### ISSUE THREAD

**Issue by kripper** [thunderbird/thunderbird-android#5789]
**Describe the bug**
When viewing an email content it was possible to zoom only with the thumb by doing a double tap + drag down.
This was very handy because it allowed to hold the device and zoom the content with only one hand (while the other hand could be used to hold a bottle of beer or to assert yourself on the bus, train, etc).

It seems that after installing latest Android webview update, this feature got broken.

Two finger zoom still works fine.

**To Reproduce**

Install latest Android webview update and try a one finger zoom.

**Expected behavior**

Mail message should be zoomed.

**Environment (please complete the following information):**

 - Android webview version: 96.0.4664.45
 - K-9 Mail version: 5.806
 - Android version: 10
 - Device: redmi note 7
 - Account type: IMAP

**Comment by kripper** [comment]
I confirm that after uninstalling Android webview, one finger pinch zoom works again.

**Comment by cketti** [comment]
Zooming is handled by the WebView component itself, not K-9 Mail. There's not much we can do if they removed that feature.

**Comment by kripper** [comment]
> Zooming is handled by the WebView component itself, not K-9 Mail. There's not much we can do if they removed that feature.

Are we setting `webSettings.setBuiltInZoomControls(true);` for the messages WebView?
Please check this.

I believe Google changed the default value to false.

I tested latest versions and it's still broken.

**Comment by kripper** [comment]
Please reopen and add `webSettings.setBuiltInZoomControls(true)` which is required to enable the pinch to zoom feature that is disabled by default on modern WebViews releases.

**Comment by cketti** [comment]
@kripper: Please stop spamming the issue tracker.

K-9 Mail already enables built-in zoom controls. 
https://github.com/thundernest/k-9/blob/75989a24887fc3383d4cd2fa59ec49eb0c836146/app/ui/legacy/src/main/java/com/fsck/k9/view/MessageWebView.kt#L38

Chances are the `WebView` implementation you are using is broken. Pinch to zoom works fine for me on multiple devices and Android versions.

**Comment by kripper** [comment]
Ok. I'm going to research further, build from sources and test on more devices.

**Comment by PanderMusubi** [comment]
I would like to request one finger zoom via double tap + hold and move up or down to zoom out or in.

This is commen e.g. Firefox, CoMaps, image viewer apps and document viewer apps.

Reported for Thunderbird 21.0 installed via F-Droid.

Can this issue get reopened or should I open a new one?

**Comment by kripper** [comment]
I did some tests and confirmed that "one-finger zoom via double tap + hold, then move up or down to zoom out or in" was still suppored in latest webview versions.

The webview update was a breaking change, but the gesture is still supported in latest webview version.
The issue is that Thunderbird is embedding the UI component inside another UI component, which prevents the gesture from being handled correctly.

So in theory, Thunderbird could be adapted to support this gesture again.

**Comment by PanderMusubi** [comment]
Thanks for your reply. Can you reopen this issue?

**Comment by kripper** [comment]
@cketti
