### ISSUE TITLE
Subject MIME-encoded into multiple lines contains garbage string

### ISSUE THREAD

**Issue by dolphin6k** [thunderbird/thunderbird-android#5804]
Long subject tends to be devided into multiple lines when it is MIME-encoded.
This kind of subject appears in K-9 with garbage character included.

For example;

Subject: =?ISO-2022-JP?B?GyRCJUYlOSVIISc3b0w+JE4jTSNJI00jRSUoJXMlMyE8GyhC?=
 =?ISO-2022-JP?B?GyRCJUkkR0ojP3Q5VCRLSiwzZCQ1JGwkayRIGyhCSy05GyRCJE43bxsoQg==?=
 =?ISO-2022-JP?B?GyRCTD5JPTwoJEslNCVfJCw6LiQ2JGsbKEI=?=

![example](https://user-images.githubusercontent.com/95457218/144536795-ded8a1d9-f942-4022-9e68-1d46cc8a5b42.png)

**Comment by cketti** [comment]
What K-9 Mail version are you using? This should be fixed in 5.905. 

See #5760

**Comment by dolphin6k** [comment]
Oh, I was using v5.8 from Google Play.
Then I installed v5.905 from GitHub Releases and confirmed it is fixed.
Thank you for your very quick reply!
