### ISSUE TITLE
Email wasn't sent, no feedback

### ISSUE THREAD

**Issue by quentincaffeino** [thunderbird/thunderbird-android#5825]
So this is very unpleasant but I tried sending an email and it just disappeared into the void.

**Describe the bug**
Spent some time writing an email, minimized it couple of times (wonder why it wasn't saved to drafts...), when finished pressed send and it just disappeared without any notification or update (very very bad UX guys). Therefore I decided to check if it was even sent, and it wasn't, I checked both app and server web, email is not there. After that I tried pulling logs using adb and nothing there because probably I can access only logs during adb session. Tried sending another email and it was sent.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806
 - Android version: 11
 - Device: One Plus Nord 1
 - Account type: IMAP & SMTP

**Logs**

As I've said they are not helpful but I will post them anyways:

https://pastebin.com/chLjCq0W

Log is to big to post on github

**Comment by quentincaffeino** [comment]
I'm aware that with these logs bug is not reproducible so you can close it right way. But I feel like it needs to be posted here anyways.

**Comment by cketti** [comment]
K-9 Mail creates an error notification when there was an error sending a message. 

It looks like your K-9 Mail configuration leads to sent messages not being uploaded. So it's not too surprising that sent messages don't show up on the server. Make sure you've configured a Sent folder under *Settings > [Account] > Folders > Sent folder* and *Settings > [Account] > Sending mail > Upload sent messages* is checked.
Similarly, drafts are not saved if no Drafts folder is configured.

For providers accepting messages via SUBMIT but not actually sending them to the recipient, see https://forum.k9mail.app/t/5-8-showing-as-sent-but-not-always-arriving-at-destination/2481

**Comment by quentincaffeino** [comment]
> It looks like your K-9 Mail configuration leads to sent messages not being uploaded. So it's not too surprising that sent messages don't show up on the server. Make sure you've configured a Sent folder under Settings > [Account] > Folders > Sent folder

That might be the case, thanks, I've set those settings. Sad that they are not set by default when folder equals one to one to setting (Sent === Sent).

> and Settings > [Account] > Sending mail > Upload sent messages is checked.

It was but probability wasn't uploaded due to Sent folder not set.

Thank you for your support.
