### ISSUE TITLE
[bug] Attachments showing up on the wrong email

### ISSUE THREAD

**Issue by DanielHeath** [thunderbird/thunderbird-android#583]
I have 2 emails which both have an attachment called `external_0.jpg`.

When viewing these messages, k9 usually shows the wrong image for at least one of them.

I suspect that `FileHelper.createUniqueFile` is subject to a race condition when downloading messages and needs a mutex - I'm running on the quad-core Galaxy Note 2.

**Comment by DanielHeath** [comment]
Specifically, multiple copies of `SaveAttachmentAsyncTask` can be executing at once, and I don't see any critical section / mutex code preventing them executing concurrently.

Checking `if (!file.exists())`, then writing the file means that two threads can both return the same filepath.

**Comment by cketti** [comment]
Much of the code related to viewing attachments and saving attachments to external storage has been changed recently. What K-9 Mail version are you using exactly?

**Comment by DanielHeath** [comment]
5.0002

**Comment by cketti** [comment]
What exactly are you seeing?

- Does the attachment box show the wrong thumbnail?
- Do you see the wrong image when you click "Open"?
- Do you click "Save" and then the wrong image is opened?

5.002 doesn't actually save a copy of the attachment when you click "Open". 

Only when you click "Save" a copy of the attachment is written to external storage. But I believe the code in version 5.002 doesn't allow you to save two files simultaneously (even then, you'd have to click faster than the code can run). So a race condition in `FileHelper.createUniqueFile()` is probably not the cause of your problem.

Also, I can't find `SaveAttachmentAsyncTask` anywhere in the code base.

**Comment by DanielHeath** [comment]
It's in `src/main/java/com/fsck/k9/ui/messageview/AttachmentController.java`

**Comment by DanielHeath** [comment]
`https://gist.github.com/DanielHeath/10059376d6d7f6e215c5` has the two messages I'm seeing this on currently. 
The inline attachments display the wrong full-size image

**Comment by cketti** [comment]
Like I said, a lot has changed with that code. For version 5.002 check out the respective tag or the [5.0-MAINT](https://github.com/k9mail/k-9/tree/5.0-MAINT) branch.

That being said, displaying inline images is a completely different thing. The relevant code is in `LocalStore`. There `cid:` URIs get replaced with content provider URIs.

**Comment by DanielHeath** [comment]
Has there been a play store release since 5.004?

**Comment by cketti** [comment]
No. See [Releases](https://github.com/k9mail/k-9/releases) and [FAQ entry on version numbers](https://github.com/k9mail/k-9/wiki/FrequentlyAskedQuestions#-what-is-the-difference-between-version-40xx-and-41xx).

**Comment by DanielHeath** [comment]
Want me to try 5.105 and see if I can still reproduce?

**Comment by DanielHeath** [comment]
Regardless, `FileHelper.createUniqueFile()` looks a *lot* like it suffers from a race condition in general. 
Even if it's not the cause of the issue I'm seeing, using it anywhere which could pass the same argument twice from different threads is a bug waiting to happen.

**Comment by cketti** [comment]
We'd love a pull request for the issue in `FileHelper.createUniqueFile()`.

I can't reproduce the issue with the inline images. The `cid` URI gets correctly replaced with a `content` URI pointing to the correct attachment. Maybe it's a WebView caching issue.

Feel free to try 5.105, but it does not contain the current code to display inline images. We're in the process of restructuring large parts of the code base to enable PGP/MIME support. Currently master is too unstable to create an alpha/development release.

**Comment by DanielHeath** [comment]
Hilariously, in the 5.0-MAINT branch it's already synchronized, so someone has removed it.

Probably deserves a comment.

**Comment by cketti** [comment]
I couldn't reproduce this issue with a build from `master`.
