### ISSUE TITLE
Failed to send IMAP email

### ISSUE THREAD

**Issue by TheRealHerisson** [thunderbird/thunderbird-android#5839]
Hi.  I have added a new IMAP email address to K9 and although everything else on the account is working I can't send email.  The email smtp verified ok. debug log attached.
[k9log.txt](https://github.com/k9mail/k-9/files/7780084/k9log.txt)

**Comment by cketti** [comment]
It doesn't look like the log contains all log messages generated by K-9 Mail. See https://github.com/k9mail/k-9/wiki/LoggingErrors

The log does contain the following error message:
```text
Transaction failed. Please report this error to your system administrator (223E)
```

It is most likely the text sent by the SMTP server when it declined to accept the message for delivery. I suggest you contact your provider to ask for help.
