### ISSUE TITLE
Outbox Refreshes Once Mail Sends But Leaves Numbers With Empty Outbox

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#5851]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

If you are unsure whether or not you have found a bug please post to the support forum instead: https://forum.k9mail.app

**Describe the bug**

Outbox numeric counts says there is items being sent when the outbox is empty. Only way to remove it is by refreshing the inbox or other folder.

**To Reproduce**

1. Send mail
2. Outbox contains being sent mail and once refreshes it still contains numeric count on empty outbox
3. Refresh inbox or other folder. Refreshing outbox doesn't fix it. 
4. See error fixed in numeric count on outbox

**Expected behavior**

No numeric count on empty outbox. A refresh shouldn't need to be done on other folder to get numeric count gone on empty outbox. 

**Screenshots**

None

**Environment (please complete the following information):**
 - K-9 Mail version: 5.907
 - Android version: 10
 - Device: Galaxy S9 +
 - Account type: IMAP (Does on POP3 too)

**Additional context**

None

**Logs**

None

**Comment by cketti** [comment]
Thanks for reporting this. A fix will be included in K-9 Mail 5.909.

**Comment by GithubContributor832** [comment]
I have a question and don't know if it's necessary to open more reports. When linking a new account to K9mail why can't I display all messages in "number of messages to display" during set up? I have to change it to all messages in settings later after setup as it only gives me an option of up to a 1000 during setup. Then lastly why can't I skip adding name to identity during setup as It can be removed later via settings? It optional later down the line.

**Comment by cketti** [comment]
This issue tracker is used for bug reports and feature requests. To ask questions please use the [forum](https://forum.k9mail.app/).

**Comment by GithubContributor832** [comment]
Thanks it's understood but I won't bother. Not worth creating an account as I won't use. Figured it was bugs as makes no sense so posted here. I'll just leave in your hands.
