### ISSUE TITLE
Unread widget is now black since Android 12 Update

### ISSUE THREAD

**Issue by christop69** [thunderbird/thunderbird-android#5868]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.806

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Realme GT

### Steps to reproduce

Add the unread widget on home screen (with full black wallpaper). 

I got the Android 12 Update today (Realme UI 3) and the widget is black now

### Expected behavior

White widget like in Android 11

### Actual behavior

Widget is black, on black background, not easy to see  (look at screen capture) !

### Logs

![Screenshot_2022-01-17-21-17-25-48_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/55764547/149836118-452081c3-b5db-48d8-a4a5-14e9b3d53f25.jpg)

**Comment by cketti** [comment]
I can't reproduce this. I'm guessing this is a "feature" of the launcher you're using. Can you try using a different launcher to confirm?

**Comment by christop69** [comment]
Thanks for your answer. In fact, the wallpaper is not responsible, it's the general theme (dark or white). When it is white, the widget is white, and black when dark like me. But you should be right, it seems to be a bug of Realme UI / Colors OS in which you have special parameters for dark mode, but it doesn't change anything for the widget when the options are flaged or not. I never used alternative launcher, I am not fan of the idea, but maybe i will try. I know Nova, any other suggestion with your experience 
![2022-01-18_14-46-06](https://user-images.githubusercontent.com/55764547/149949207-3dfed7d9-0208-4d3a-ad2d-47a5dfe971e1.jpg)
?

**Comment by cketti** [comment]
I wasn't suggesting that you permanently switch to another launcher. Only to use another launcher to figure out whether it's really an issue with your default launcher. Then you could more confidently report it as a launcher bug to the vendor.

**Comment by christop69** [comment]
OK, I understand, I will try. And about the design of the widget, it does not change, in contrast to the rest of the brand new app I like in version 5. Can you imagine a cuter one in the future ? Maybe just like the icon of K9 but with the number of unread messages ? Thanks for all your work !

**Comment by christop69** [comment]
Widget perfectly clean with Nova Launcher...
