### ISSUE TITLE
With 5.909, frequent blank screen when opening a message

### ISSUE THREAD

**Issue by jikamens** [thunderbird/thunderbird-android#5873]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.909

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Pixel 6

### Steps to reproduce

1. View message list
2. Tap a message to open it

### Expected behavior

Message displays

### Actual behavior

I briefly see the loading progress bar at the top of the screen show activity, and then I am left with a completely blank screen. If I go back and tap the same message again it displays the second time.

**Comment by jikamens** [comment]
Android system status bar is still there. No K-9 Mail toolbar. It's intermittent so I will enable logging and take a screenshot and send logs if/when it happens again. It happened several times this morning but not since then.

**Comment by jikamens** [comment]
Happened again. See attached screenshot.

Is there any way I can send you the logs rather than posting them on a public GitHub ticket? There's probably nothing terribly sensitive in them but I want to be careful.

![Screenshot_20220124-084440](https://user-images.githubusercontent.com/1598067/150794613-23b5eb00-ad2f-4e2d-9dd5-1440b177e0b5.png)

**Comment by jikamens** [comment]
Obviously (from the screenshot) my memory about the toolbar was incorrect.

**Comment by jikamens** [comment]
Ping. Still happening

**Comment by cketti** [comment]
You can send the debug log to debugging@cketti.de. Though I doubt it will contain useful information in this case.

Can you try changing the WebView implementation that is used on your device? Are you using a custom ROM?

**Comment by jikamens** [comment]
Logs sent via email.
I am using stock Android 12 directly from Google (my phone is an unlocked Pixel 6 bought directly from the Google Store).
The only WebView implementation offered to me in settings is "Android System WebView 98.0.4758.87". I don't know how to add other choices to that list so I don't know how to change the WebView implementation.
Note that when this problem occurs and I go back to the message list after I get the blank screen, the message does not show up in the message list as having been opened. If I tap on the same message again it typically displays properly the second time, and then when I go back to the message list it shows up as having been opened.

**Comment by cketti** [comment]
Thanks, I received the log. Thankfully, the bug is unrelated to WebView.

The code to remove the notification when viewing a message doesn't work properly. #5905 should fix this. 
I'll release a new beta version later today or tomorrow.
