### ISSUE TITLE
broken display of

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#5882]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.9.10

### Where did you get the app from?

Other

### Android version

Android 11, Havoc OS (custom)

### Device model

OnePlus 3T

### Steps to reproduce

Open mail by Mozilla

### Expected behavior

continous layout without gaps.

### Actual behavior

There is lots of blank space between paragraphs. (several times the device height between each paragraph is just white screen space so you need to scroll very far)
This might be due to the nested table layout but without a debugger it's hard for me to figure out which html tags K9 might have removed that broke the layout this way.

If you have time at some point, then please take a look.
No high priority, I just noticed the broken layout.

I attached the email as an html file. I modified three a href attributes, the rest is unmodified.
[mail.html zipped](https://github.com/k9mail/k-9/files/7936679/mail.zip)

**Comment by cketti** [comment]
I created a command line application that modifies HTML the same way that K-9 Mail does. See #5885

Could you use this to debug the issue yourself?

**Comment by Djfe** [comment]
yes,
I finally had the time to look at this.

I tested this in Firefox and used the inspection tools in order to switch to a mobile layout (smartphone icon on the right)

The html mail starts with 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <!--[if gte mso 9]>
    <xml>
        <o:OfficeDocumentSettings>
            <o:AllowPNG/>
            <o:PixelsPerInch>96</o:PixelsPerInch>
        </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->
```

Your scripts removes everything except but keeps the naked html and head tags.
The relevant part that your script removes that breaks the layout is the doctype.

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">`
I tried out
`<!doctype html>`
while it's html5 and not html4 it also fixes the issue.

The issue being:
The layout uses divs with height:100% as the only attributed for nesting.
According to [Stackoverlow](https://stackoverflow.com/questions/1997842/why-certain-doctype-declarations-cause-100-height-tables-and-divs-to-stop-worki):
> If you have height: 100% and the height of the parent element is auto then [100% means auto](http://www.w3.org/TR/CSS21/visudet.html#the-height-property).

the new strict behavior in browser engines interpret the height differently and let the element inherit from it's parent.
Removing the doctype makes the engine go into "quirks" mode and interprets the layout/css differently. (legacy mode)
Quirks mode then actually renders this height: 100% creating lots of blank space between each element of the layout.

I don't know why these nested divs (parent element: grid-div; child element: table) even exist in the first place (maybe legacy mail clients?), but removing them instead of the !doctype also fixes the layout.

But you might want to think about keeping !doctypes intact unless this was done to prevent other mail layouts from breaking

**Comment by cketti** [comment]
Thanks for the analysis :heart: 

The doctype wasn't intentionally removed. It's the default behavior of Jsoup's `Cleaner` class.
I've added code to copy the doctype from the "dirty" `Document` instance to the "clean" `Document` instance. See #5896.
