### ISSUE TITLE
Two notifications for the same message

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#5892]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.910

### Where did you get the app from?

Other

### Android version

doesn't matter

### Steps to reproduce

Use an IMAP server that sometimes sends multiple fetch responses for a single message.

Example:
```text
RealImapConnection: conn66388302>>> 8 UID FETCH 98594 (UID FLAGS INTERNALDATE RFC822.SIZE BODY.PEEK[HEADER.FIELDS (date subject from content-type to cc reply-to message-id references in-reply-to X-K9mail-Identity Chat-Version)])
RealImapConnection: conn66388302<<<#null# [5320, FETCH, [UID, 98594, INTERNALDATE, 30-Jan-2022 18:02:23 +0100, RFC822.SIZE, 143729, BODY, [HEADER.FIELDS, [date, subject, from, content-type, to, cc, reply-to, message-id, references, in-reply-to, X-K9mail-Identity, Chat-Version]], {header fields} , FLAGS, [NonJunk]]]
RealImapConnection: conn66388302<<<#null# [5320, FETCH, [FLAGS, [NonJunk], UID, 98594]]
RealImapConnection: conn66388302<<<#8# [OK, FETCH complete]
```

### Expected behavior

The two FETCH responses should be combined and only be counted as one new message.

### Actual behavior

~~K-9 Mail's sync code currently counts this as 2 new messages and downloads the same message twice~~

~~The app will also create two notifications for that message.~~

The "new message" callback is invoked twice leading to two notifications being created.

**Comment by Showmaster3000** [comment]
I think I have the same issue using a POP3 server. If I swipe out the notification of a new message in the notification center, the same entry will show again some seconds later. After swiping out a second time, the notification disappears as expected.

Version: 5.910 from f-droid
Android: 8.1

**Comment by cketti** [comment]
@Showmaster3000: That's definitely a different problem. Please open a new issue and attach a debug log.
