### ISSUE TITLE
Push notifications show for deleted messages and do not disappear at the same time

### ISSUE THREAD

**Issue by PhoenixIV** [thunderbird/thunderbird-android#5897]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.910

### Where did you get the app from?

Google Play

### Android version

8.1.0 LineageOS

### Steps to reproduce

1. Scroll down in inbox to load new messages (~6 new)
2. Delete ~5 spam mails
3. Push notification says "5 new messages" of which it previews 4, also deleted spam. All in the same inbox!
4. Click on notification (inbox opens)
5. Now push notification says 3 new messages
6. Click again (same inbox opens)
7. Now it says 1 new message
8. Click on message (one of the deleted spams)
9. Blank white screen appears

### Expected behavior

Do not show notifications when refreshing manually from within inbox, maybe?

### Actual behavior

Described in steps to reproduce.

**Comment by PhoenixIV** [comment]
Version: 5.911

My last observation (single sample):

1. Unread mail notification did not disappear even though inbox was open
2. Unread mail notification did disappear for mails I selected and deleted in that inbox
3. Unread mail notification did not disappear for mail I selected and set to "read"

**Comment by cketti** [comment]
These are all different problems.

1. Currently notifications are only removed when a folder is opened. If a new message arrives while the message list screen is open, the notification is still created. See issue #3170.
2. K-9 Mail already removes notifications for messages that are marked as read using another client or removed from the server (once these changes have been picked up by K-9 Mail).
3. K-9 Mail currently doesn't remove notifications for messages that are marked as read or deleted locally. I created issue #5930 for that.

I'm closing this issue. If you experience any other bugs, please create one new issue per bug.
