### ISSUE TITLE
Account order in left pane

### ISSUE THREAD

**Issue by tenzap** [thunderbird/thunderbird-android#5907]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Redmi note 9s

### Steps to reproduce

Set the accounts in a specific order in the settings.
Then go to messages view and open the left pane.
The order doesn't match the order in settings

### Expected behavior

See above

### Actual behavior

Oder doesn't change

**Comment by cketti** [comment]
So it's not really about the order of the accounts, but about the account that is opened by default, i.e. after all screens of the app have been closed or the app has been killed?

In K-9 Mail 5.8xx there's a separate setting for the default account. It can be found under *Settings → [Account] → General settings → Default account*.
We removed that setting in K-9 Mail 5.903 (5.9xx are beta versions) and now use the first account in the list as the default account.
