### ISSUE TITLE
End-to-end encryption interfering with message headers

### ISSUE THREAD

**Issue by peterjanes** [thunderbird/thunderbird-android#5910]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.910

### Where did you get the app from?

Google Play

### Android version

11

### Device model

Pixel 2 XL

### Steps to reproduce

1. Enable OpenPGP support for an account.
2. Send an email to a user you have a key for (e.g. yourself) with an identifiable subject, e.g. "Test with OpenPGP".

### Expected behavior

Message should be sent with valid headers, a blank-line separator, and a body.

### Actual behavior

Two Subject: fields are included, the first followed by a blank line, e.g.:

```
Subject: 

	content-transfer-encoding:content-transfer-encoding:dkim-signature:autocrypt:autocrypt;
	bh=8hJu6e7tqjn//z3zMHsyM9YXefGS809mDB+yFNHocM4=;
...
```

The second Subject field contains the expected subject, but all of the headers past the blank line are included in the message body.

Other context:
- Things were working fine as of February 9, but have started failing since then.
- Phone uptime is ~130 hours (about 5.5 days).
- K-9 was last updated on January 25.
- Using OpenKeychain 5.7, no new keys or changed configuration for at least a year
- Manually disabling encryption for the recipient or the various settings makes no difference; only turning off OpenPGP support entirely solves the issue. I've included the various scenarios above in the logs, with the last one having encryption disabled.

### Logs

Can't see anything that seems of particular interest, but here are the logs.

[k9-log.txt](https://github.com/k9mail/k-9/files/8049803/k9-log.txt)

**Comment by cketti** [comment]
I can't reproduce this error. 

- Do you have *Encrypt message subjects* enabled?
- What language is the app/system configured to use?
- Can you provide the (redacted) message source of such an email?

We do have code in place that should crash the app when it attempts to add an invalid header line. Is it possible that a mail server breaks the message after it has left the device?

**Comment by peterjanes** [comment]
- I turned off _Encrypt message subjects_ a while back, since they're not compatible with Thunderbird (see #5108 and #5634).
- My phone language is set to English (Canada) and English (United States).
- How much do you need of the email?

I guess it's possible a mailserver has corrupted it, but I'm just sending to DreamHost (which uses `mailchannels.net`; their servers appear to use Postfix) and retrieving the messages from there with an instance of `fetchmail` that delivers directly to my IMAP server inbox; none of the pieces are misbehaving on any other messages.

**Comment by cketti** [comment]
> How much do you need of the email?

It sounds like a blank line slipped into the header. So the (redacted) header of the message should do.

You should be able to compare the message in the Sent folder to the one in your Inbox to find out if K-9 Mail created the broken message or it was messed with by your provider.
