### ISSUE TITLE
Impossible to sent attachment

### ISSUE THREAD

**Issue by B4rabbas** [thunderbird/thunderbird-android#5911]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Xiaomi Redmi Note 10S (Rosemary)

### Steps to reproduce

1. Go in sending message mode
2. Click on attachment icon
3. Choose an attachment file
4. Send the mail

### Expected behavior

5. The attachment is sent with the mail

### Actual behavior

5. No attachment sent with the mail

### Logs

```text
--------- beginning of system
02-12 08:43:51.727 22013 22013 I Timeline: Timeline: Activity_launch_request time:525927536
02-12 09:02:32.305 22013 22013 I Timeline: Timeline: Activity_launch_request time:527048114
02-12 09:02:50.269 22013 22013 I Timeline: Timeline: Activity_launch_request time:527066078
02-12 09:02:52.566 22013 22013 I Timeline: Timeline: Activity_launch_request time:527068375
02-12 09:03:15.752 22013 22013 I Timeline: Timeline: Activity_launch_request time:527091561
02-12 09:03:17.522 22013 24785 W BpBinder: Slow Binder: BpBinder transact took 221ms, interface=android.app.IActivityManager, code=22 oneway=false
02-12 09:03:32.270 22013 22013 I Timeline: Timeline: Activity_launch_request time:527108079
```

**Comment by cketti** [comment]
It doesn't look like you've enabled debug logging inside K-9 Mail. Please have another look at https://github.com/k9mail/k-9/wiki/LoggingErrors

What app are you using to pick an attachment? Can you post a screenshot?

**Comment by B4rabbas** [comment]
I've test with vanilla file manager from AOSP and with Material Files (from Fdroid too).

**Comment by B4rabbas** [comment]
`--------- beginning of system
02-15 07:32:10.580 20189 20293 W BpBinder: Slow Binder: BpBinder transact took 545ms, interface=android.app.IActivityManager, code=22 oneway=false
`

**Comment by B4rabbas** [comment]
Just in case I use K9 for many years, and for my job too, I hope I'll not have to argue that I know how sent attachment.
