### ISSUE TITLE
Needless quoted-printable encoding

### ISSUE THREAD

**Issue by DerDakon** [thunderbird/thunderbird-android#5915]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Xperia 10 II

### Steps to reproduce

1. Reply to any mail, just write "Foobar"

### Expected behavior

Since this is plain ASCII this should show up as is in the line.

### Actual behavior

When replying with "Bar" or "Baz" everything is fine. But "Foobar" is recoded to "=46oobar".

**Comment by cketti** [comment]
I can't reproduce this issue. Did you check the message in your Sent folder to make sure it was K-9 Mail who encoded the message like that?

But even if it was K-9 Mail, why report this as a bug? As far as I can tell, this has zero user impact.

**Comment by DerDakon** [comment]
Yes, it's K9 that does his. I found out that it also doe this when sending a new mail. It doesn't break anything for a user, but it could be the sign of a more serious issue.

**Comment by cketti** [comment]
I'm still not able to reproduce the issue. And I couldn't find any code that would encode `F` at the start of a line or arbitrarily encode characters that don't have to be encoded. K-9 Mail will encode `From ` at the start of the line to `From=20`. As far as I can tell that's the only special case.

Can you please try to provide instructions on how to reliably reproduce this issue? Things that might be relevant: your K-9 Mail configuration, the type of message you reply to, the length of the text body.

**Comment by DerDakon** [comment]
[k9_settings_export_2022-02-15.k9s.txt](https://github.com/k9mail/k-9/files/8072393/k9_settings_export_2022-02-15.k9s.txt)

I reproduce it with
* New message
* select a recipient
* write: "Foobar" to message field
* send

Result is:
```
Subject: Test
MIME-Version: 1.0
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

=46oobar
```

**Comment by cketti** [comment]
Thanks. I've received the credentials. Unfortunately, I still can't reproduce the issue. 

I've tried with the settings you provided. I've tried with K-9 Mail 5.807 installed from F-Droid. I've tried a version with custom logging to make sure the data sent via SMTP matches that of the message in the Sent folder. The result was always the same. `Foobar` was never encoded.

I'm out of ideas.
