### ISSUE TITLE
Beta 5.911: vibration / led on notification broken

### ISSUE THREAD

**Issue by stephanborn** [thunderbird/thunderbird-android#5922]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5911

### Android version

8

### Device model

Samsung S7 edge

### Steps to reproduce

1. enable notification
2. Set vibration to default
3. Enable notification light

### Expected behavior

When mail arrives notification should vibrate and show notification light

### Actual behavior

No vibration / notification light. Vibration was working on 5.910

### Logs

[k9mail-logs2.txt](https://github.com/k9mail/k-9/files/8075136/k9mail-logs2.txt)

**Comment by cketti** [comment]
Between K-9 Mail 5.910 and 5.911 the code to create notifications hasn't been changed. Only the code to create a `NotificationChannel` was changed. Pull request #5928 adds some logging that should help to figure out what's going on.

Once K-9 Mail 5.912 has been released, please record two debug logs:
1. Go to *Settings → [Account] → Notifications* and change e.g. the *Notification light* setting to a different value. Then save the debug log. Additionally, tap the *Messages* item on the same screen to go to the system screen to configure a notification category. Please attach a screenshot of that screen.
2. Record a debug log while receiving a message that triggers a notification.

**Comment by stephanborn** [comment]
Log after I changed color to yellow:
[k9mail-logs4.txt](https://github.com/k9mail/k-9/files/8128213/k9mail-logs4.txt)

Log after I received a mail with notification - no vibration/led visible:
[k9mail-logs5.txt](https://github.com/k9mail/k-9/files/8128216/k9mail-logs5.txt)

My notification settings in Android settings:
![20220223_210027](https://user-images.githubusercontent.com/1429312/155419671-b37143a2-e339-4539-a283-13f48d191cbb.jpg)

**Comment by cketti** [comment]
The logs don't show any unexpected values. It's possible that the configured notification light and vibration isn't used because no sounds is configured. Can you select "silent" or "none" as a notification sound?

**Comment by stephanborn** [comment]
Thanks! Yes, you where right - somehow the setting in Android changed (maybe by updating to Beta or by testing notification settings manually). When I set silent instead of no sound then vibration and LED notification works. Ticket can be closed.
