### ISSUE TITLE
Search doesn't work for Korean characters 

### ISSUE THREAD

**Issue by nottheend** [thunderbird/thunderbird-android#5927]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

F-Droid

### Android version

GrapheneOS

### Device model

Google Pixel 5

### Steps to reproduce

1. Receive a mail from a sender with Korean characters, e.g. 김범석
2. Open Inbox
3. Click on search
4. Type type or paste the Korean sender name
5. click on 'search'

### Expected behavior

Mail from Korean sender should appear in the result list

### Actual behavior

Mail is not shown, even in Inbox and exact spelling

**Comment by cketti** [comment]
This is probably a duplicate of #5776

Can you check if you still have this problem with the latest beta version? See https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68

**Comment by nottheend** [comment]
Thanks! Will check

**Comment by nottheend** [comment]
Yes, in the new version it works!
Thanks a lot for the good work🎉
