### ISSUE TITLE
Absence of sound and visual notifications, on Xiaomi.

### ISSUE THREAD

**Issue by franco27** [thunderbird/thunderbird-android#5937]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.8 and 5.9

### Where did you get the app from?

Other

### Android version

10

### Device model

Xiaomi redmi 8 (miui 11)

### Steps to reproduce

 Hello

 I wanted to let you know about a notification issue.  I never receive visual or sound notifications on my smartphone with your app.

 Since changing my mobile, I no longer receive notifications.
 And the notifications only appear when I open K9-Mail on my new Xiaomi Redmi 8, Android 10, MIUI 11 v125 phone.

 I don't receive a notification when a new email is received and your application is in the background.

 In the settings, Android Xiaomi:
 1. I activated the padlock for the K9mail window (which should prevent k9mail from closing)

 2. I turned off battery optimization.

 3. Allowed autostart.  And allowed the display in the background.

 And I enabled permanent notifications.

 4. Of course notifications are enabled.

 Any help would be welcome or a fix for this problem.  Thank you 🙏.

### Expected behavior

get visual and audible notifications

### Actual behavior

no notifications . 
Absence of sound and visual notifications, on Xiaomi.

**Comment by saber716rus** [comment]
I have no problems with notifications on redmi note 8 pro (miui 12.5.3).  Check in the notification settings, everything is enabled.

**Comment by franco27** [comment]
In the notification settings, everything is enabled.  and me, no notification!

 On the other hand, when I restarted my mobile or phone, the notifications worked until I opened K9-Mail.
 After opening it to read mails, I had no notification from K9-Mail again.

**Comment by cketti** [comment]
K-9 Mail only generates notifications when it checks for new messages. Make sure either Polling (*Settings → [Account] → Fetching mail → Folder poll frequency*) or Push (*Settings → [Account] → Fetching mail → Push folders*, see also: https://forum.k9mail.app/t/how-to-configure-push/1102) is enabled.

Regarding aggressive energy saving measures that might prevent the app from running in the background, see: https://dontkillmyapp.com/

**Comment by franco27** [comment]
Thank you for your reply.

 Notifications are enabled.

 I have already gone to see and read the recommendations of the website https://dontkillmyapp.com/.  I had already applied and enabled the requested settings.
 I also went to the Xiaomi forum.

 For "Settings → [Account] → Fetching mail → Folder poll frequency)"
 This setting is already enabled and I have requested that it regularly checks folders for new mail.

 However, I did not enable this setting.  (for "Push (Settings → [Account] → Fetching mail → Push folders")
 And since it's enabled, it's better because a K9-mail icon is always in the Android notification.
 But from time to time, this icon disappears and I no longer have notifications of new emails.  I have to open K9-mail again for the icon to reappear.

**Comment by cketti** [comment]
Sounds like a problem with your Android version rather than a bug in K-9 Mail. Closing this issue.

**Comment by franco27** [comment]
I use K9-mail in French.
 The translation of the word "Push" in French is bad.  This word should not be translated.
 In French, "push notifications".  And not "Pousser".

yet with other mail applications that I have tried. 
 I don't have this problem.

**Comment by Thordals** [comment]
I have same problem on RedMi 10s, Android 11 MIUI 12.5, K9 5.8 and 5.9.
All notifictions are actived, other notify app works, of course i have enabled notification for K9 app and disabled battery optimization.
Yet the synchronization works well, the messages are well received, there are no notifications
![k9](https://user-images.githubusercontent.com/62652167/160147303-5846fbb0-a849-4012-9ed4-8d0ee943c872.png)
I am French too ;)
