### ISSUE TITLE
Email to self, sent from a PC, does not show in k-9

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [thunderbird/thunderbird-android#5947]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Asus Zenfone 8

### Steps to reproduce

1 On a PC, send an email to myself, using Thunderbird and sending the mail from a mailfence.com to a Gmail account.
2 On the same PC, verify the email was received (and whether or not the email is marked as read seems to make no difference).
3 Open or refresh K9 on my phone.

### Expected behavior

The email-to-and-from-self should appear within K9.

### Actual behavior

The email-to-and-from-self does _not_ appear within K9.

Cf. #2101?

### Logs

[k9-log.txt](https://github.com/k9mail/k-9/files/8200189/k9-log.txt)

**Comment by cketti** [comment]
The log show there are no new messages on the server that haven't already been downloaded by K-9 Mail. Does it work as expected if you skip step 2?

**Comment by LinuxOnTheDesktop** [comment]
_'Does it work as expected if you skip step 2?' In short: no._ Here is a longer answer. I tested as follows. On a PC, I wrote an email to myself. I sent it and then exited the email application immediately, before the new email appeared within the application. (The email at issue is from one account to another, but the email app on the PC checks mail for all my accounts.) Result: in K-9 (and without a reboot) - the new email did not show (though another new email - not from me - did arrive).

Addition: I find that if I _reboot the phone_ and then open K9 then any emails-to-self, of the sort at issue, do finally appear (along with some emails that I have deleted; I've opened a thread about that latter problem on the forum; I might file a bug report on it - for it does seem a serious problem).

**Comment by cketti** [comment]
Sounds very odd. Maybe a corrupt database. Try uninstalling, then reinstalling the app.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. But that means I must reenter all the information for my email accounts, yes?

**Comment by cketti** [comment]
You can export settings under *Settings → Export settings*.

**Comment by LinuxOnTheDesktop** [comment]
OK. I will export and then tell Android to clear the 'cache' and the 'data' for the app and then uninstall and then reinstall.

**Comment by LinuxOnTheDesktop** [comment]
Done. I note that even with the export/import, and seemingly by design, I had to reenter my account passwords.

And . . the problem persists. (But one does refresh from pulling down by near the top of the app, yes?)

**Comment by LinuxOnTheDesktop** [comment]
Gmail to mailfence works, I find - but not, as said, mailfence to gmail. Let me check the settings within k9 . .

**Comment by LinuxOnTheDesktop** [comment]
I have further data. I put all my data in the table below.

| Device and program sent from | Mail account sent from | Mail account sent to | Result | 
| --------------- | --------------- | --------------- | --------------- |
| Windows PC using Thunderbird | Mailfence | Gmail | Email received by PC but not by K9 |
| Android phone using K9 | Gmail | Livemail | Email undergoes total existence failure |
| Android phone using K9 | Livemail | Gmail | Email received by PC but not by K9 |

Also: fiddling with settings did not help.

**Comment by LinuxOnTheDesktop** [comment]
I have updated the table in my previous post.

Also, and, I think, importantly: _suddenly a load of my test email appeared in K9. So it seems that **some** form of syncing - one that is periodic - is working._

**Comment by LinuxOnTheDesktop** [comment]
**_Aha!_** _I think the problem has to do at least partly with K9's configuration._ For, I notice now two somewhat old notifications from K9. (I have set K9's notifications to 'silent'.) One notification says:

> 
> Failed to send some messages. 
> Could not find a valid MX or A record for domain gmail.com

The other notification:

```
Waiting for new emails
Tap to learn more.
```

Upon tapping, there is a message that is hard to understand about 'pushing' and 'pulling'. Please advise me on the following. How can I have K9 detect new email quickly but (1) without (if possible) showing a permanent notification and (2) without showing notifications when K9 is not running in the foreground? For, you see, I want to hear about my email only when I run K9 or (if K9 must run constantly in the background) only when I switch to the K9 screen.

Also, we do have a bug here (even aside from the possible problem sending with gmail) or at least a documentation problem. For, it seems that, if the user sets all K9 notifications to silent, then havoc ensues - the havoc exhibited or comprised by this issue report.

**Comment by cketti** [comment]
Please don't spam the issue tracker. A lot of people receive notification emails for every comment you post. Not every new piece of information is a breakthrough that has to be shared immediately. Do your experiments, think about what you've done and what else you could do, wait a few hours, and if you can't think of anything else to add, post your findings.

I've had another look at the log. If shows that you've checked the Mailfence account for new messages (and there were none). If you expect a new message in the Gmail account, you'll have to check that account.

How exactly are you checking for new messages in K-9 Mail? Do you open the Inbox of the Gmail account and pull down on the message list to check for new messages?

For instructions on how to configure Push see https://forum.k9mail.app/t/how-to-configure-push/1102

**Comment by LinuxOnTheDesktop** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;Thank you for your help. I apologise for the spamming.  Shall I use GitHub's 'hide' function to hide some of my previous messages?

&nbsp;&nbsp;&nbsp;&nbsp;'How exactly are you checking for new messages in K-9 Mail? Do you open the Inbox of the Gmail account and pull down on the message list to check for new messages?' I open the 'unified inbox' and pull down. For, my expectation was that

1) Pulling down on the Unified Inbox would check for new messages on all my accounts.

I had the following expectation too.

2) Merely opening the Unified Inbox would check for new messages on all my accounts.

Perhaps expectations 1 and 2 are false.

&nbsp;&nbsp;&nbsp;&nbsp;Thank you for the instructions about configuring Push. Having read them, and having experimented, it seems that via Push one can achieve 2 or something equivalent to it. It seems further that Push allows the meeting of the following expectation (/desideratum/use-case).

3) Whilst I am viewing any account in K9 then I will see - in near real-time - any newly arriving emails for that account.

I find further that one can have 3 without being bombarded by notifications. That is good.

&nbsp;&nbsp;&nbsp;&nbsp;I continue to have problems with deletions being unsynchronised between devices, and perhaps with emails from other folders (or with other Gmail 'tags') appearing in my K9 inbox. Perhaps I can solve these problems via the documentation and/or experimentation and/or via the forum.

&nbsp;&nbsp;&nbsp;&nbsp;Still, I think that some users will have expectations 1 and 2. So: if those expectations are false then that is something of a problem. Also, I remain concerned about the failure to send the Gmail message. Still: I think that I have learned how one can configure K9 such that one sees such error messages without seeing notifications about newly arriving mail.
