### ISSUE TITLE
Not receiving mails after changing to POP3

### ISSUE THREAD

**Issue by DanielTheGreat** [thunderbird/thunderbird-android#5971]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

5.0.1

### Device model

Samsung S4

### Steps to reproduce

Deleted IMAP account (not working as desired) and set up POP3 account instead.
Incoming and outgoing server checks passed.
Sent test e-mail (from a PC) to the account eddress.

### Expected behavior

E-mails should appear no later than 15 minutes after sending (K-9 poll interval set to 15 minutes)

### Actual behavior

No e-mails in K-9 Inbox.

### Logs

Enabled debug logging and exited K-9 app (still runs in background, I assume).
Sent a test e-mail from a PC.
After ~20 minutes, connected phone to PC, but Windows 7Pro64 reports "device driver was not successfully installed", so I can't use adb to retrieve log.

**Comment by cketti** [comment]
I don't see enough evidence to believe this is a bug. Please use the [forum](https://forum.k9mail.app/) for support requests.
