### ISSUE TITLE
Second account is partly in English despite settings

### ISSUE THREAD

**Issue by hman2** [thunderbird/thunderbird-android#5973]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.913

### Where did you get the app from?

F-Droid

### Android version

9 (FP Open OS 21.12.0-rel.1)

### Device model

Fairphon 2

### Steps to reproduce

1. Create a second mail account and select it
2. Go to folders of second account

### Expected behavior

This should be entirely in system language (this is the default):

### Actual behavior

The folders "Sent", "Spam" and "Trash" are in English. Changing the settings of the second account from system default to German doesn't change this.

I did check whether or not these folders are in German on the IMAP server. They are...

This is merely a cosmetic error, the functionality of the folders is given.

**Comment by hman2** [comment]
I found that the folder names can be configured - but the German translation is not offered...

**Comment by cketti** [comment]
K-9 Mail uses the folder name from the server. It doesn't translate the names of special folders.

> I did check whether or not these folders are in German on the IMAP server. They are...

They most likely are not. Maybe the app you used to check this, translated the folder names.

In the future please post to the [forum](https://forum.k9mail.app/) first. If the behavior you believe to be a bug turns out to actually be a bug, you'll be redirected here. If not, a lot more people are available to help you.

**Comment by hman2** [comment]
"They most likely are not. Maybe the app you used to check this, translated the folder names."

No, they aren't. Thunderbird doesn't translate them. Thunderbird shows these folders in German for both accounts. K-9 displays them in English on the second, and it cannot be changed, both with German as the setting and system default as the setting (which is also German). So when I go into the folder name change dialog, I am given some options, one of which is labelled system default - also English....

**Comment by cketti** [comment]
Can you post a screenshot of the screen where you believe the folder names should be German, but are not?
