### ISSUE TITLE
Cannot create a folder for spam on first account

### ISSUE THREAD

**Issue by hman2** [thunderbird/thunderbird-android#5974]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.913

### Where did you get the app from?

F-Droid

### Android version

9 (FP Open OS 21.12.0-rel.1)

### Device model

Fairphone 2

### Steps to reproduce

1) Go to account listing.
2) Settings
3) Select account. Here: The first (everything WORKS on the second [except for translation, see other report]
4) Select Folder
5) The Folder setting for Spam is set to Spam

### Expected behavior

So a spam folder (named Spam) should come up in folder view. A spam folder DOES exist on the IMAP server, I checked that...

### Actual behavior

No spam folder...

**Comment by cketti** [comment]
K-9 Mail can be configured to only show a subset of folders. To show all folders in the folder list make sure that *Settings → [Account] → Fetching mail → Incoming server → Show only subscribed folders* is unchecked. Then go to the *Manage folders* screen and select *Show folders → All folders* from the (three dots) menu.
