### ISSUE TITLE
Inline data images / DataUri are not rendered

### ISSUE THREAD

**Issue by C0D3D3V** [thunderbird/thunderbird-android#5975]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Android version

Linage Os Android 10

### Device model

One Plus 3t

### Steps to reproduce

1. Recieve a Mail with an inline data/image:png:base64
2. Make sure that the image is shown in other Mail clients
3. Look at the Email in k9mail -> see that the image is not shown

Example Image Tag for testing (one simple red dot):
`<img src="data:image/gif;base64,R0lGODdhAQABAPAAAP8AAAAAACwAAAAAAQABAAACAkQBADs" />`

The Email I recieved:

![Screenshot_20220321-135823_K-9_Mail_1](https://user-images.githubusercontent.com/14315968/159266918-540f5124-9fac-4922-9f85-aa09cbd4500e.png)

Actually there should be a barcode/qr-code, if I long press the black squere I see that the image is actually there but not rendered:

![Screenshot_20220321-135903_K-9_Mail_1](https://user-images.githubusercontent.com/14315968/159267133-de6d4493-dea9-49c0-8fb6-cfdeac6260bf.png)

### Expected behavior

Would be nice if inline images could be rendered

### Actual behavior

Inline Images are not rendered

**Comment by cketti** [comment]
Works for me. This message displays fine for me in K-9 Mail 5.807 and 5.913

```email
Message-ID: <message-2022-03-21-001@k9mail.example>
Date: Mon, 21 Mar 2022 14:00:00 +0100
Subject: data: URL
From: test@k9mail.example
To: test@k9mail.example
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8

<html>
<body>
One<br>
<img src="data:image/gif;base64,R0lGODdhAQABAPAAAP8AAAAAACwAAAAAAQABAAACAkQBADs"><br>
Three<br>
</body>
</html>
```
