### ISSUE TITLE
two email accounts,  all new messages go to drafts when sent

### ISSUE THREAD

**Issue by geodude56** [thunderbird/thunderbird-android#5981]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.600

### Where did you get the app from?

Google Play

### Android version

12

### Device model

SM-G970U

### Steps to reproduce

1: open tom@tefvideo.com account in accounts window
2: Tap New message
3: fill in destination email (doesn't matter who)
4: fill in subject
5: fill in message text
6: Press send (status shows "sending 0/2"), then clears
7: goto Drafts folder, message is in there
8: select message
9: press send
10 message is actually sent this time

### Expected behavior

2 accounts don't exhibit this behavior (Mobile Only, SFC)
But  tom@tefvideo.com and Lists does.
Have attached K9 settings file & log file

### Actual behavior

![Screenshot_20220321-140959_K-9 Mail](https://user-images.githubusercontent.com/102065770/159337448-fa82645e-e644-4000-a1a4-a0b68e9202e0.jpg)
![Screenshot_20220321-141025_K-9 Mail](https://user-images.githubusercontent.com/102065770/159337506-2d6bc934-3bc9-48c7-b0bb-46d377e7b0ff.jpg)
![Screenshot_20220321-140921_K-9 Mail](https://user-images.githubusercontent.com/102065770/159337546-48b98508-85a9-418b-a22a-3cc890809fc9.jpg)
![Screenshot_20220321-140933_K-9 Mail](https://user-images.githubusercontent.com/102065770/159337582-c5d39ce5-461f-4a98-9064-daadd124e961.jpg)
![Screenshot_20220321-140948_K-9 Mail](https://user-images.githubusercontent.com/102065770/159337663-6eb59743-58a1-46af-9308-bd7160f2f5be.jpg)
[k9_settings_export_2022-03-21.txt](https://github.com/k9mail/k-9/files/8318262/k9_settings_export_2022-03-21.txt)
![Screenshot_20220321-141330_K-9 Mail](https://user-images.githubusercontent.com/102065770/159341084-752911c4-6e32-42f3-933f-73e4d90fe93e.jpg)

### Logs

[k9-log.txt](https://github.com/k9mail/k-9/files/8318342/k9-log.txt)

**Comment by cketti** [comment]
Please only report bugs that you can reproduce with recent K-9 Mail versions (5.8xx = stable, 5.9xx = beta).

K-9 Mail 5.600 is outdated and we don't backport bug fixes.
