### ISSUE TITLE
Messages throw ! error & go to Outbox when using Reply-To in identity is filled in

### ISSUE THREAD

**Issue by geodude56** [thunderbird/thunderbird-android#5982]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

12

### Device model

SM-G970U

### Steps to reproduce

1: click on compose
2: fill in destination address, subject & Text
3: press send
4: sending shows in status bar
5: Triangle with ! in center appears in droid status bar
6: goto outbox, message is in there, can't send it from there
7: move to drafts
8: Send from there OK

### Expected behavior

should send with or without Reply-To in Initial Identity filled in
Upon further troubleshooting, found problem went away if Initial Identity Reply-To field was empty.
Requirement by Mail provider service (AOL) that From Email field MUST BE same as account email but since I have my own domain name, would prefer to use my domain email address in Reply-To field.
THis problem has existed since ver 6.00

### Actual behavior

With an identity that has Reply-To filled in, message generates a warning/error symbol on notifications bar & message goes to outbox. If message is moved from outbox to draft box, it can be sent without any modification, however cannot re-send directly from outbox.
If Reply-To field in identity is empty, message goes out directly from compose when send is tapped.

### Logs

[k9_V5807_Lists-log.txt](https://github.com/k9mail/k-9/files/8319321/k9_V5807_Lists-log.txt)
[k9_settings_Lists_export_2022-03-21.txt](https://github.com/k9mail/k-9/files/8319331/k9_settings_Lists_export_2022-03-21.txt)
[k9_settings_lists-w-replyto_export_2022-03-21.txt](https://github.com/k9mail/k-9/files/8319365/k9_settings_lists-w-replyto_export_2022-03-21.txt)

**Comment by cketti** [comment]
K-9 Mail displayed an error notification because when trying to send the message the server returned the following error: `550 Request failed; Mailbox unavailable`

If this is indeed caused by the presence of a `Reply-To` header, that's a policy set by your email provider. There's nothing K-9 Mail can do about that. 
You could ask them to have the server return a more descriptive error message, though.

**Comment by geodude56** [comment]
I suppose that makes sense since the email address is to my domain redirected address but why does it work when it's sent from the drafts box without modification?
    On Monday, March 21, 2022, 05:45:17 PM EDT, cketti ***@***.***> wrote:  
 
 


K-9 Mail displayed an error notification because when trying to send the message the server returned the following error: 550 Request failed; Mailbox unavailable

If this is indeed caused by the presence of a Reply-To header, that's a policy set by your email provider. There's nothing K-9 Mail can do about that.
You could ask them to have the server return a more descriptive error message, though.

**Comment by cketti** [comment]
It's possible that the message contents in the first send attempt are different from the one is the second attempt. The log doesn't contain the actual message.

After the failed send attempt, move the message to the Drafts folder. Then use another email client to grab the raw email (the whole message including headers). Then open the message in the Drafts folder using K-9 Mail and send it again. The sent messages should be uploaded to the Sent folder. Grab that as raw email, too. Then compare the two.
