### ISSUE TITLE
crash when cutting an invalid recipient

### ISSUE THREAD

**Issue by fe60** [thunderbird/thunderbird-android#5991]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

F-Droid

### Android version

LineageOS 18.1 (Android 11)

### Device model

Motorola Moto G5 (cedric)

### Steps to reproduce

1. Start composing a new mail
2. Enter an invalid mail recipient (e.g.: my subject)
3. Tap into subject or message text
4. K-9 Mail marks recipient as invalid
5. Select invalid recipient and Cut
=>Crash and restart of app

Message text composed before gets lost.

<details>
<summary>Screenshot showing K-9 Mail right before using <b>Cut</b></summary>

<img src="https://user-images.githubusercontent.com/31078918/160756905-3ea5f0c8-dd64-40e1-bc66-537a5219c8f6.png" height="600" />
</details>

### Expected behavior

Invalid recipient can be cut out similar to a valid one.

### Actual behavior

App crashes.
Potential loss of composed message text.

**Comment by rezazarchi** [comment]
I think this is duplicated issue.
#3951
