### ISSUE TITLE
Broken quoting of plain text mail

### ISSUE THREAD

**Issue by THausherr** [thunderbird/thunderbird-android#6029]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

Google Play

### Android version

Android 12, One UI 4.1

### Device model

Samsung S21

### Steps to reproduce

Show mail. The mail is like this, it was a pure text mail:

```

Am 20.04.2022 um 04:16 schrieb XXXX YYYYYYYY:
>
> We also enjoy when people tell us that all their tests are green! It 
> gives us confidence ;-) So regardless of the tests color (red or 
> green), please do not hesitate to send me a short mail as both types 
> of feedback are useful. 

Apache PDFBox builds successfully with jdk19.

https://ci-builds.apache.org/job/PDFBox/job/PDFBox-Trunk-jdk19/

jacoco (tool for code coverage) had problems 
("java.lang.instrument.IllegalClassFormatException: Error while 
instrumenting sun/security/pkcs11/SunPKCS11") but it went away with 
their latest version

https://github.com/jacoco/jacoco/issues/1296

Best regards

Tilman Hausherr

```

(I did make an issue search for "quote", but the issues looked different)

### Expected behavior

more like this (from thunderbird)

![grafik](https://user-images.githubusercontent.com/6665575/164276881-5599500c-6d61-493c-82dd-1d5bb66aa782.png)

### Actual behavior

![grafik](https://user-images.githubusercontent.com/6665575/164277096-009c7251-10e3-4664-8350-ed59f235b2fb.png)

**Comment by cketti** [comment]
I can't reproduce the issue with the text snippet you've provided. Can you attach the (redacted) message source (including headers)?

**Comment by THausherr** [comment]
Here's the (redacted) EML file
[k9.zip](https://github.com/k9mail/k-9/files/8523702/k9.zip)

**Comment by cketti** [comment]
Thanks for providing the message source. I was able to reproduce the issue. It's a bug in the code used to "deflow" text when `format=flowed` is used.

**Comment by cketti** [comment]
We use a (stripped down) copy of the [`FlowedMessageUtils`](https://github.com/apache/james-project/blob/a6f6289562c5ed42fd7dbf8cbf8a6cb972b3a2b5/mailet/base/src/main/java/org/apache/mailet/base/FlowedMessageUtils.java) class from the Apache James project.

I've reported the bug to the James project ([JAMES-3753](https://issues.apache.org/jira/browse/JAMES-3753)) and created a pull request: https://github.com/apache/james-project/pull/972
