### ISSUE TITLE
Installation causes reboot

### ISSUE THREAD

**Issue by dashdsrdash** [thunderbird/thunderbird-android#6031]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.0

### Where did you get the app from?

Other

### Android version

10, Oxygen 10.3.8.GM21AA

### Device model

OnePlus 7 Pro

### Steps to reproduce

1. Use any of Google Play, F-Droid or direct download from Github to obtain 6.0 APK and install.
2. Phone spends 30-50 seconds in the installation phase and then reboots, leaving 5.807 installed.

To rule out a general problem, I installed updates to KOReader via F-Droid (no issue) and an update to Duolingo via Google Play (no issue).

### Expected behavior

I expected 6.0 to install properly without a reboot.

### Actual behavior

The APK is downloaded through all methods, and begins the install process. Then it hangs and reboots the phone.

**Comment by cketti** [comment]
If your device reboots, that's almost certainly a bug in your operating system. You could try contacting your device vendor. But they'll probably have a hard time reproducing the issue.

You can probably work around this error by uninstalling the app, then reinstalling it. You might want to export your settings before that (under *Settings → Export settings*).

**Comment by dashdsrdash** [comment]
cketti wrote: 
> If your device reboots, that's almost certainly a bug in your operating system. You could try contacting your device vendor. But they'll probably have a hard time reproducing the issue.
> 
> You can probably work around this error by uninstalling the app, then reinstalling it. You might want to export your settings before that (under *Settings → Export settings*).
> 


This worked.

Import of settings claimed to fail, but did not actually fail.

-dsr-
