### ISSUE TITLE
With remote Drafts folder, drafts vanish

### ISSUE THREAD

**Issue by eater** [thunderbird/thunderbird-android#605]
To reproduce:
- Choose a remote IMAP folder as the default Drafts folder.
- Put device in airplane mode.
- Compose a message and save it as a draft.
- Exit K-9.
- Exit airplane mode.
- Open K-9 and navigate to Drafts folder.
- The saved draft cannot be found.

**Comment by s3b-** [comment]
Can't confirm bug, I just tested it on my device with K-9 Mail Version 5.600. Draft message will be saved after exiting airplane mode.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with a recent K-9 Mail version.
