### ISSUE TITLE
Don't upload to sent folder by default with Outlook accounts

### ISSUE THREAD

**Issue by TippyLion28** [thunderbird/thunderbird-android#6067]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

By default, outlook accounts upload to sent folder. Outlook already handles copying sent emails to the sent folder, which results in duplicate mails in the sent folder when this option is enabled. I have disabled the option and it works fine now. 

### Suggested solution

This option should be false by default for outlook accounts

### Screenshots / Drawings / Technical details

Imagine the sent folder but every item appears twice

**Comment by cketti** [comment]
I agree that there should be a way so "Upload sent messages" is disabled automatically when using a provider that automatically puts sent messages in the Sent folder. 
However, I don't think an email client should maintain a list of such providers. There needs to be a mechanism providers can use to indicate this to clients. Maybe an SMTP or IMAP extension.

**Comment by TippyLion28** [comment]
Maybe a test email can be sent to the receiving address on setup to check? As a workaround

**Comment by kewisch** [comment]
If this can be disabled on the provider level I think it should be sufficient for now. If an IMAP/SMTP extension emerges that would allow determining this I think we can create a new issue and reconsider, but for the moment I believe it is fairly standard behavior for the client to take on the copying to sent. Thunderbird Desktop does this as well.
