### ISSUE TITLE
"Cannot connect to crypto provider" when trying to send a mail with PGP enabled and K9 was started from contacts app

### ISSUE THREAD

**Issue by schorschii** [thunderbird/thunderbird-android#6068]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

Google Play

### Android version

Android 10

### Device model

Fairphone 3

### Steps to reproduce

1. enable PGP for your account
2. open the Google contacts app and click on an email address
3. K9 mail starts and displays the selected email address in the "To" field

### Expected behavior

The email should be sent without errors

### Actual behavior

It is not possible to send the email, error message: "Cannot connect to crypto provider, check your settings or click crypto icon to retry!" (also if you try to send it unencrypted!)

![Screenshot_20220511-231116](https://user-images.githubusercontent.com/17480795/167952230-48628cc8-3a11-4493-9130-da17d79cac01.png)

This only happens when K9 was started from the (Google) contacts app. It is working fine if you manually enter the email address in the "To" field (and not use the contacts app to start K9-Mail).

Seems to be a new since v6.000.

Additional note: when starting from contacts app, K9-Mail shows the selected email address in the "To" field. I thought it showed the contact name in a previous version.

**Comment by terasolu** [comment]
It happens to me when trying to save a draft without a recipient.

This seems to be the same issue:
https://github.com/open-keychain/open-keychain/issues/2760

**Comment by life777eternal** [comment]
@terasolu This might be related to turning on "Enable Tor" on the OpenKeyChain Settings under "Network Anonymity". So we'd have to have Orbot installed from the Guardian Project, and have Orbot started.

**Comment by terasolu** [comment]
@life777eternal I doubt that, because this option isn't activated on my system.

**Comment by life777eternal** [comment]
Alright @terasolu you're probably right 👉🏻 ➡️, I just disabled the Enable Tor" setting on OpenKeyChain and the toast message still appeared without a recipient.

**Comment by terasolu** [comment]
@life777eternal I tried it with Orbot, but it doesn't change anything. I found out that the problem only occurs when I don't set a recipient. I can set any recipient, even a recipient I don't have a certificate of and it works as expected.

**Comment by kevincox** [comment]
I also found this occuring after clicking mailto links.

Maybe K9 is doing something when a recipient is added explicitly but forgets to do it when coming from contacts or a mailto link. (does contacts just use a mailto link?)

**Comment by life777eternal** [comment]
@cketti   I've been seeing this toast message once in a while still. Don't actually notice it until I'm ready to send a message and hit the send button, or hit the back button or home button. The workaround I've been doing is to highlight all of the text I had typed, copy, then discard the email and reply all again to the same email, and then paste into the body again. Although after I do that, that toast message doesn't appear for a while. But later it does appear again. 

```
4234  4234 D OpenPgpApiManager: attempting to bind to openpgp provider: org.sufficientlysecure.keychain (org.openintents.openpgp.util.OpenPgpServiceConnection@abf8c62)
4234  4234 D MessageLoaderHelper: Creating new local message loader
4234  4234 D OpenPgpApiManager: attempting to bind to openpgp provider: org.sufficientlysecure.keychain (org.openintents.openpgp.util.OpenPgpServiceConnection@abf8c62)
```

See line 340 on the attached log file. 

[k9-log.txt](https://github.com/thundernest/k-9/files/9947363/k9-log.txt)


Thank you.

**Comment by life777eternal** [comment]
This still happens once in a while, when replying to an email and sending a new email from an email link.

Although it seems that if I copy my message and discard the email and reply to the email again, and paste in my message, the email sends.
