### ISSUE TITLE
"Spam" functionality gone

### ISSUE THREAD

**Issue by NuxRo** [thunderbird/thunderbird-android#6069]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.0

### Where did you get the app from?

F-Droid

### Android version

Lineageos 19.1

### Device model

Pixel 3a

### Steps to reproduce

Open a message, try to Refile it or
Long press a message

### Expected behavior

Ability to refile message as Spam.

### Actual behavior

Can no longer see any options to mark the message as Spam. Have to manually copy it to Spam folder.
I went into Settings to enable Spam as message action etc, but doesn't look like it made any difference.

**Comment by ByteHamster** [comment]
Before you can see the spam action, you have to configure which of the folders is the spam folder (in case your email server does not support telling K-9 which folder it is). See Settings » Account » Folders.

**Comment by NuxRo** [comment]
Thanks, that did it.
Out of curiosity, how would the server tell the client which folder is the spam one?

**Comment by ByteHamster** [comment]
Using an imap extension. I think it's RFC 6154.
