### ISSUE TITLE
No notifications for new mail in folders other than INBOX

### ISSUE THREAD

**Issue by larskotthoff** [thunderbird/thunderbird-android#6072]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

Google Play

### Android version

LineageOS 19.1

### Steps to reproduce

New mail arriving in folders other than INBOX creates no notifications, even when notifications are set to "all folders". New mail is retrieved and shows up in the unified inbox/specific folder. This happened in older versions of K9 as well. I have different email accounts under the same domain that are routed to different folders.

To reproduce, set up mail provider to route mail to folder other than INBOX and set this up to be polled in K9.

### Expected behavior

Notification created for new mail in custom folder that is not INBOX.

### Actual behavior

No notification created.

**Comment by cketti** [comment]
K-9 Mail has fairly extensive logging that shows the reason why a new message doesn't trigger a notification. Please see https://github.com/thundernest/k-9/wiki/LoggingErrors
