### ISSUE TITLE
Inproper Handling of encoded-word (RFC 1342)

### ISSUE THREAD

**Issue by kevincox** [thunderbird/thunderbird-android#6084]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

Google Play

### Android version

Android 12, Lineage 19

### Device model

Pixel 4a

### Steps to reproduce

Get a message with the following from header:

```
From: =?utf-8?b?VHdpc3RlZERvb2RsZXMgLyBAdHdpc3RlZGRvb2RsZXM=?= <feed-1657@feedmail.org>
```

### Expected behavior

The from address displays as "TwistedDoodles / @twisteddoodles"

### Actual behavior

The from address displays as feed-1657@feedmail.org

### Logs

<details><summary>Logs</summary>

```
--------- beginning of main
05-25 11:35:58.569  7216  7253 D OpenGLRenderer: endAllActiveAnimators on 0xb400007df65c7c00 (MenuPopupWindow$MenuDropDownListView) with handle 0xb400007d0641f510
05-25 11:47:51.817  7216  7253 D OpenGLRenderer: endAllActiveAnimators on 0xb400007df6a1c9c0 (RippleDrawable) with handle 0xb400007d064387a0
05-25 11:47:55.095  7216  7253 D OpenGLRenderer: endAllActiveAnimators on 0xb400007df657e860 (ConstraintLayout) with handle 0xb400007d0637b650
05-25 11:49:57.494  7216  7253 D OpenGLRenderer: endAllActiveAnimators on 0xb400007df657e860 (ConstraintLayout) with handle 0xb400007d0634ab70
05-25 11:49:58.626  7216  7253 D OpenGLRenderer: endAllActiveAnimators on 0xb400007df69af930 (FrameLayout) with handle 0xb400007d06434ea0
05-25 11:50:00.724  7216 24453 I K9StorageEditor: Committing preference changes
05-25 11:50:00.731  7216 24453 I K9StorageEditor: Preferences commit took 9 ms
05-25 11:50:03.868  7216  7246 I MessagingController: Running command 'clearNotifications', seq = 4491 (foreground priority)
05-25 11:50:03.868  7216  7246 I MessagingController:  Command 'clearNotifications' completed
05-25 11:50:04.875  7216  7216 D MessageViewFragment: MessageView displaying message MessageReference(accountUuid=18e2bcdb-cea3-4377-be75-568492a62d41, folderId=3, uid=1616)
05-25 11:50:04.877  7216  7216 D MessageLoaderHelper: Creating new local message loader
05-25 11:50:04.897  7216  7216 D MessageLoaderHelper: Creating new decode message loader
05-25 11:50:04.947  7216  7216 D Utility : External images found
05-25 11:50:08.359  7216  7246 I MessagingController: Running command 'clearNotifications', seq = 4492 (foreground priority)
05-25 11:50:08.361  7216  7246 I MessagingController:  Command 'clearNotifications' completed
05-25 11:50:10.980  7216  7253 D OpenGLRenderer: endAllActiveAnimators on 0xb400007df657e860 (ConstraintLayout) with handle 0xb400007d063c3aa0
05-25 11:50:12.397  7216  7253 D OpenGLRenderer: endAllActiveAnimators on 0xb400007df6acda40 (FrameLayout) with handle 0xb400007d063c3aa0
05-25 11:50:15.844  7216  7253 D OpenGLRenderer: endAllActiveAnimators on 0xb400007df66840c0 (RippleDrawable) with handle 0xb400007d063c3aa0
```

</details>

**Comment by kevincox** [comment]
It looks like the problem is because the `@` is treated as an `specials` ([RFC 5322: Internet Message Format](https://www.rfc-editor.org/rfc/rfc5322#section-3.2.3)) which would be invalid as a `word` or `phrase`. However according to [RFC 1342 - Representation of Non-ASCII Text in Internet Message Headers](https://datatracker.ietf.org/doc/html/rfc1342) an `encoded-word` can be used "as a replacement for a `word` entity within a `phrase`" which would make the encoding in the mentioned header correct.

**Comment by kevincox** [comment]
And as an appeal to authority Thunderbird handles this fine.

**Comment by cketti** [comment]
K-9 Mail should decode this encoded word just fine. We don't show display names that contain an `@` character (minus a few exceptions). That's to avoid confusion about the sender address e.g. with a `From` header line like this one:

```eml
From: "alice@domain.example" <mallory@evil.example>
```

**Comment by kevincox** [comment]
Ah, I see. So this is an "over active" security feature. Are there any configurations available for this? Or can we consider tweaking it? For example I think usernames referenced like @foobar are pretty common in this day and age so maybe we can consider exempting things that match `\s+@[a-zA-Z_-]` or similar?

**Comment by kevincox** [comment]
Or we could consider other options like some sort of indicator that this is a name vs email or also displaying the email below the name (maybe only if the former looks like the latter?)

**Comment by cketti** [comment]
We only allow a few exceptions, see 

https://github.com/k9mail/k-9/blob/859e7c541733d71ab729a065c18ab2230faa823d/app/core/src/test/java/com/fsck/k9/helper/MessageHelperTest.java#L97-L109

As a workaround you can add the sender to your contacts and give it any name you like, including one that contains an `@` character.

**Comment by kevincox** [comment]
I see `toFriendly_nameStartingWithAtShouldNotTriggerSpoofPrevention` is pretty close to the space before @ workaround that I proposed. Are you against extending that rule to be start or after space?

**Comment by cketti** [comment]
The problem is that spaces are easy to overlook. Depending on the font, they might be very easy to overlook.

And `TwistedDoodles / @twisteddoodles` is a syntactically valid email address if you ignore the spaces.

**Comment by kevincox** [comment]
Ok, I guess we aren't going to agree then. I guess the options are just close this as working-as-intended or to rework the UI that this confusion between name and email isn't an issue. However given the space-limited constraint on the UI doing that may be difficult.

**Comment by cketti** [comment]
The plan is to change the UI to allow the user to expand the header to see the display name and email address of the sender and all recipients. However, in the collapsed state only the display name (or email address, depending on the configuration) will be displayed. So the same security consideration applies to the collapsed state of this future UI.

Given there's a way for users to work around this, I don't think this issue warrants additional effort.
