### ISSUE TITLE
Wrong file attachments from recorded audio on whatsup

### ISSUE THREAD

**Issue by PeopleInside** [thunderbird/thunderbird-android#609]
Hi,
If I record an audio file on whatsup with the microphone and after sent in whatsup I select the audio message and share in K9-mail the email is Sended with danaged file. The file audio Sended by Android 5.0 on Samsung galaxy S5 with whatsup share function then K9-mail arrive danaged. For send correctly and share I must use Gmail app with Gmail account.

Please fix this on k-9 mail so I can send by email audio recorded message via WhatsUp to email

**Comment by cketti** [comment]
Issue #744 contains more information.
