### ISSUE TITLE
Added support for using OAuth 2.0 with Google accounts still won't work

### ISSUE THREAD

**Issue by werano** [thunderbird/thunderbird-android#6117]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v6.100

### Where did you get the app from?

Other

### Android version

12

### Device model

Oneplus 10 pro

### Steps to reproduce

Retrieve mail in common file

### Expected behavior

Pull mails from Gmail.com

### Actual behavior

Failure

**Comment by ByteHamster** [comment]
What error message?

**Comment by werano** [comment]
Authetification failure
