### ISSUE TITLE
Deleting email from notification doesn't work

### ISSUE THREAD

**Issue by EbonJaeger** [thunderbird/thunderbird-android#6123]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.100

### Where did you get the app from?

Google Play

### Android version

Android 10

### Device model

Motorola Moto G7 Optimo Maxx (XT1955DL)

### Steps to reproduce

1. Get a new email notification
2. Tap the "Delete" notification action
3. Confirm the delete operation in the popup
4. Go to provider's webmail (or just open the app), and see the email is still there

### Expected behavior

The email should be deleted.

### Actual behavior

The email is still present, both in the client and on the server.

### Logs

After I turned on debug logging, I could not reproduce the issue with my first test email. I'll try again and see if I can get anything from it, but it might take a bit.

In any case, that would indicate that the issue might be intermittent, even though I could very consistently (as far as I know, every time) reproduce the issue before.

**Comment by EbonJaeger** [comment]
There wasn't a general information field, so I'll add some info here as a comment.

The email provider I'm using is Vivaldi email (same organization as the web browser, vivaldi.net) via IMAP. In the past week or so that I've been using K-9, I've tried to delete several emails from the notification, and I don't recall any of the deletions having gone through, until turning on debug logging.

**Comment by cketti** [comment]
Closing this for now. I can reopen this issue once you can provide a debug log, so we have a chance to find out what was going on.
