### ISSUE TITLE
Emails are never send and neither found in Drafts, nor Send, nor Outgoing folder

### ISSUE THREAD

**Issue by yennor** [thunderbird/thunderbird-android#6130]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.100

### Where did you get the app from?

F-Droid

### Android version

Arrow Os 11

### Device model

Poco X3

### Steps to reproduce

1. Create new mail
2. write some text
3. click send

### Expected behavior

Email would be send

### Actual behavior

The E-mail sending scree disappears, everything seems to be allright.
But the mail never gets send. Doesn-t appear in the sent folder nor drafts, nor outgoing (To be honest, I can't find the outgoing Folder in K9...)

On the mailserver nothing appears in the logs, seems like k9 didn-t even try to half way properl connect.

Activated debug mode in k9, but theres also nothing in logcat

The same behaviour with k9 6.000. I can-t tell with what version it started, since it took me a while to notice... No idea if it is related to:
https://github.com/thundernest/k-9/pull/6049

The mail is send over transmission port (587) using starttls.

### Logs

[logcat_06-22-2022_09-54-16.txt](https://github.com/thundernest/k-9/files/8958829/logcat_06-22-2022_09-54-16.txt)

**Comment by cketti** [comment]
Please make sure to check *Settings → General settings → Debugging → Enable debug logging* before trying to send a message. Then export another debug log.

Outgoing messages are saved in K-9 Mail's "Outbox" folder. It should be displayed right below the Inbox in the folder list. If for some reason it is not present, K-9 Mail won't be able to send messages. In that case try removing the account and adding it again.

**Comment by yennor** [comment]
The outbox folder wasn't there.
I'deleted the account and readded it. Now everything is working

**Comment by cketti** [comment]
Do you remember which version of K-9 Mail you used to initially set up that account?

**Comment by yennor** [comment]
ok that's a though one.
I remember that at one point I installed 5.7xx but I don't remember if it was able to take over my account from the previous 5.600 version, or if I needed to readd it. I think I didn't need to readd it, but I'm not sure anymore. So it was either in 5.7xx or in 5.600 or previous. Sorry. I really don't remember it more exactly.
