### ISSUE TITLE
Duplicate Notifications

### ISSUE THREAD

**Issue by runninghamster0** [thunderbird/thunderbird-android#6132]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.100

### Where did you get the app from?

Other

### Android version

ColorOS 11

### Device model

Oppo A52

### Steps to reproduce

1. Add Google Account/s using new OAuth 2.0 log-in feature
2. Enable Push for all folders
3. Exhibit multiple notifications for a single e-mail.

### Expected behavior

Display a single notification for the e-mail that is fetched.

### Actual behavior

The application is sending out duplicates of the same notification. This varies from 2 or 3 duplicates, probably related to the number of Google accounts linked (I have 3 accounts linked via OAuth 2.0 and push enabled for all three accounts).

I have provided screenshots of some sample notifications. The duplicates are only for the notifications, opening the app displays the fetched e-mails correctly.

**Comment by runninghamster0** [comment]
![picture-1](https://user-images.githubusercontent.com/52240313/175457052-6f0d7080-1854-4784-b048-87b1302ea345.jpg)
![picture-2](https://user-images.githubusercontent.com/52240313/175457060-ebadd571-3739-4657-b8ee-98887b7629ec.jpg)

**Comment by cketti** [comment]
For others finding this issue through search: Don't enable notifications for Gmail's "All mail" folder. Every message in the Inbox can also be found in the "All mail" folder. But for K-9 Mail these are distinct messages.

**Comment by mpeter50** [comment]
> Don't enable notifications for Gmail's "All mail" folder.

how does one do that? "settings > account A > Notifications > notification folders" only allow selecting it by some kind of level, it does not allow per-folder.

the same applies to the setting of which folders to sync. I would rather also turn off syncing the "all mail" folder because it does not make sense.
