### ISSUE TITLE
Excessive battery consumption when in airplane mode with IMAP push

### ISSUE THREAD

**Issue by mahdi1234** [thunderbird/thunderbird-android#6133]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.100

### Where did you get the app from?

F-Droid

### Android version

LOS 17.1

### Steps to reproduce

As soon as phone goes to Airplane mode battery consumption increases significantly. While it can be around 1% for the 16h working day, it takes 3-4% over remaining 8 hours during night.

I'm having 4 accounts all using IMAP push.

### Expected behavior

No consumption during airplane.

### Actual behavior

![k9_airplane](https://user-images.githubusercontent.com/1097047/175524967-b4802f83-220a-4884-b08b-7828c77bd537.jpg)

### Logs

[k9_2.log](https://github.com/thundernest/k-9/files/8975773/k9_2.log)

**Comment by cketti** [comment]
Does the ongoing notification that is displayed when Push is active read "Waiting for new emails"? It looks like the app is trying to connect to the server, failing, then trying again 5 minutes later. However, if the device is in airplane mode the OS should have notified the app that there's no connectivity. In that case the notification should display "Sleeping until network is available". Either there's a bug in K-9 Mail's connectivity listener code or your Android version is not properly handling this situation.

Please record a debug log while switching to airplane mode.

**Comment by mahdi1234** [comment]
After upgrading to LOS 19.1 the problem is gone, so it might have been indeed related to that particular ROM. Closing the issue. fyi @cketti
