### ISSUE TITLE
Can't switch account from POP3 to IMAP

### ISSUE THREAD

**Issue by TonyGravagno** [thunderbird/thunderbird-android#6134]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

Google Play

### Android version

11

### Device model

Pixel3

### Steps to reproduce

1. Open settings for an account configured for POP3
2. Switch to IMAP, configure.
3. Tap Next for test.

### Expected behavior

Connection to IMAP server.

### Actual behavior

It's still using the Pop3Connection to connect to the IMAP port. So all test connections fail, with a display of the list of Capabilities returned from the IMAP server.

### Logs

```
at com.fsck.k9.backend.pop3.Pop3Backend.checkIncomingServerSettings(Pop3Backend.kt:128)
at com.fsck.k9.controller.MessagingController.checkIncomingServerSettings(MessagingController.java:1726)
at com.fsck.k9.activity.setup.AccountSetupCheckSettings$CheckAccountTask.checkIncoming(AccountSetupCheckSettings.java:504)
```

> D Pop3Connection: <<< QUIT BAD Error in IMAP command received by server.
> E AccountSetupCheckSettings$CheckAccountTask: Error while testing settings

The IMAP server is returning a set of RFC-valid Capabilities. It's obvious that it used the wrong protocol to query the server. I think I did completely exit/close the app and then re-enter to get the same results. So, as I recall, it doesn't seem to reset whatever flag is used to determine the POP3/IMAP protocol until after a successful test is done.

My solution was simply to create a new account, as IMAP and remove the POP3 account. This eliminated any possible issues related to local folders versus remote folders. This might be the best solution, although in the process, account settings for reading and writing are lost.

So one approach to resolving this might be to prevent us from changing the protocol type of an existing account between POP3 and IMAP.
Another approach would be to address the protocol selection, and check folder settings to make sure existing POP3 folders and their settings are not lost in the process of loading resources from a new IMAP server.

**Comment by cketti** [comment]
Changing the account type is not supported. You'll have to delete the account from K-9 Mail and add it again using the desired protocol.

> So one approach to resolving this might be to prevent us from changing the protocol type of an existing account between POP3 and IMAP.

K-9 Mail doesn't support changing the protocol. It sounds like you just changed the host name and port. While uncommon, it is possible to run a POP3 server on a host called `imap.domain.example` using e.g. port 993. K-9 Mail makes no attempts to derive the protocol from the host name and/or port number.
