### ISSUE TITLE
autocrypt dialog has a broken link

### ISSUE THREAD

**Issue by otherart** [thunderbird/thunderbird-android#6135]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

build from source git c4e9ae40 (6.101 ish)

### Where did you get the app from?

Other

### Android version

Android 12 API level 31

### Device model

Emulator

### Steps to reproduce

Go to End-to-end encryption settings

Tap Autocrypt mutual mode

Tap the link "click here"

### Expected behavior

I expect a useful documentation page

### Actual behavior

I get sent to a 404 at https://k9mail.github.io/2018/02/26/OpenPGP-Considerations-Part-III-Autocrypt.html

**Comment by cketti** [comment]
Thanks. I've recreated the [k9mail/k9mail.github.io](https://github.com/k9mail/k9mail.github.io) repository to redirect to the proper URL.

Next step: Updating the source code to use the new URL: https://k9mail.app/2018/02/26/OpenPGP-Considerations-Part-III-Autocrypt.html
