### ISSUE TITLE
Folder listed multiple times

### ISSUE THREAD

**Issue by patricktokeeffe** [thunderbird/thunderbird-android#614]
While figuring out #613 I noticed three folders named "Outbox". One was the remote folder but two entries led to the same local folder. After trying 'recreate' on the account's data, I ended up with triplicate entries for the spam folder. 

I ended up deleting and re-creating the account; it's working fine now. Still wanted to report the behavior though.

**Comment by strk** [comment]
It's happening for me right now. My trash folder is duplicated. I think I interrupted the first sync, in case that matters. Using version 5.007

**Comment by madworm** [comment]
Using 5.008 and trying to get rid of duplicate trash and outbox folders.

**Comment by philipwhiuk** [comment]
Closing as older duplicate of #1220

**Comment by Wikinaut** [comment]
Workaround/solution: Long-tap on the account in the accounts list.
