### ISSUE TITLE
[regression] "mark as read" deselects messages

### ISSUE THREAD

**Issue by steelman** [thunderbird/thunderbird-android#6159]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.200

### Where did you get the app from?

F-Droid

### Android version

Android 12/LineageOS 19.1 

### Device model

Motorola G7 (river)

### Steps to reproduce

1. Go to an INBOX
2. Select one or more unread messages
3. Mark them as read (the open envelope icon)

### Expected behavior

Messages are marked as read but are still selected.

### Actual behavior

Messages are marked as read and deselected.

This behavior was apparently introduced in 6.200 and it breaks my workflow to mark messages as read before sending them to spam (see #5767).

**Comment by cketti** [comment]
Thanks for reporting this bug :+1:

We'll fix this in an update soon. In the meantime you should be able to work around this by opening a message first, then returning to the message list before selecting multiple messages. Also, changing the device orientation before selecting multiple messages should work around the bug.
