### ISSUE TITLE
Account setting "Delete from Server" lost after SSLError

### ISSUE THREAD

**Issue by slowjack2k** [thunderbird/thunderbird-android#616]
Hi,

ever and anon I get an SSLCertificate error with my provider gmx.net.
When this happens the account settings changes and mails will be no longer
deleted from the mail server after they are deleted localy. I have to change the settings by hand back.

regards
dieter

**Comment by cketti** [comment]
I can't reproduce this.

What K-9 Mail version are you using?
What protocol are you using (IMAP, POP3, WebDAV)?

Maybe unrelated but still interesting: why do you get SSL errors?

**Comment by slowjack2k** [comment]
1.) I use version 5.004 with a Galaxy S5
2.) Protocol Pop3
3.) I haven't seen any details. In the last days it didn't happen. I guess a Mail-Server within the cluster with an invalid certificate. But I don't know for shure.

**Comment by cketti** [comment]
Is this still an issue?

**Comment by slowjack2k** [comment]
Yes. It still happens from time to time. But it appears only a small message tls error without a code or so. I have a dialog where I can change my settings. There I prest next. I get a connection to my mail provider.  But I still need to change the delete option after this. Is it possible to extend the  ssl error message? Or having a last error log without turning on debug log?

**Comment by slowjack2k** [comment]
Nice. Thx. I think this will fix it :+1:
