### ISSUE TITLE
Same profile avatar displayed for different accounts

### ISSUE THREAD

**Issue by strayhatpirat** [thunderbird/thunderbird-android#6179]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.201

### Where did you get the app from?

Google Play

### Android version

Lineage OS unofficial (Android 10)

### Device model

Samsung Galaxy A3 (2017)

### Steps to reproduce

1. Open the side menu by sliding from the left border of the screen 
2. Click on the arrow to open the accounts dropdown menu

### Expected behavior

I have 5 different accounts : 
- 3 from Gmail 
- 1 from Google Workspace (pro account) 
- 1 from Outlook 

I expect every account to display its own profile avatar if set.

### Actual behavior

Th 3 Gmail accounts display the same profile avatar. It's the correct avatar for one of them (the one crossed out in green on the screenshot), but the 2 others don't have their correct avatar. 

The Google Workspace account (orange profile avatar on the screenshot) is supposed to have an avatar as well, but it isn't displayed on K9. 

The Outlook account doesn't have any avatar, so it's normal to see the default avatar. 

![image](https://user-images.githubusercontent.com/16545424/180392394-12a11ead-38d5-4fc5-9116-f304407c4911.png)

### Logs

I activated the debug mode and reproduced the steps at 10:03
[k9mail-logs.txt](https://github.com/thundernest/k-9/files/9165923/k9mail-logs.txt)

**Comment by cketti** [comment]
This is not a bug (but annoying/confusing). See #5509
