### ISSUE TITLE
Resource leak -- file not closed -- found by Facebook's static analyzer

### ISSUE THREAD

**Issue by dulmarod** [thunderbird/thunderbird-android#618]
Hello,
This resource leak report, included with comments below, were found by running

Facebook's Infer static analyzer on K-9.

Regards,
Dulma Rodriguez
Facebook Static Analysis Tools Team

File: k9mail/src/androidTest/java/com/fsck/k9/helper/HtmlConverterTest.java

Report: Resource Leak: resource acquired by call to FileWriter(...) at line 143 is not released after line 147.

Remarks: The problem seems to be that out.write(...) can throw an exception, in which case out.close() won't get called. A simple fix is to put the call to close in a finally clause.

**Comment by cketti** [comment]
Thanks for reporting this!

Is this just a taste of what the tool can do or did you really not find another issue like this in the K-9 code base?

**Comment by dulmarod** [comment]
Our tool did find more bugs. Some of them may be false positives, some may be legit. If you are interested I can send you the list.

**Comment by jberkel** [comment]
@dulmarod is the static analyzer publicly available or is it an internal FB tool?

**Comment by dulmarod** [comment]
@jberkel It is an internal FB tool. But it is OK for us to send a list of bugs.

**Comment by cketti** [comment]
@dulmarod: I'd love to see the list of found issues. If you don't mind subscribing to our developer mailing list, send to k-9-dev@googlegroups.com, otherwise to cketti@gmail.com and I'll forward to the list.

**Comment by dulmarod** [comment]
Hi, 
Facebook's Infer static analyzer, the tool that we used to find these issues, is open source now! Check it out! (http://fbinfer.com/).

**Comment by jberkel** [comment]
@dulmarod nice! maybe we can integrate it into the CI process
