### ISSUE TITLE
Notifications not showing when notification sound is manually set to default sound

### ISSUE THREAD

**Issue by FloEdelmann** [thunderbird/thunderbird-android#6186]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.201

### Where did you get the app from?

Google Play

### Android version

9

### Device model

Samsung Galaxy S8

### Steps to reproduce

1. Set the default system notification sound to "Pollux"
2. Set the K-9 notification sound to "Pollux" (not "default notification sound"), with any other sound the problem does not occur
3. Enable push notifications (but the behavior is the same without this step)
4. Send an email from another device

### Expected behavior

The incoming email should trigger a notification.

### Actual behavior

There is no notification. When opening the app, the new email is shown as expected.

**Comment by cketti** [comment]
Can you please provide more details in the steps to reproduce? How do you "Set the K-9 notification sound to "Pollux"" exactly?

Did you try enabling debug logging and have a look at the log? If K-9 Mail decided not to show a notification for a new message, the reason should be mentioned in the log. See https://github.com/thundernest/k-9/wiki/LoggingErrors

**Comment by FloEdelmann** [comment]
It was not my phone, so it's not easy to reproduce. Also, apparently a new version fixed this a few days ago, so I'll close this issue.
