### ISSUE TITLE
IllegalStateException no outbox_state entry for message when deleting into Trash (IMAP)

### ISSUE THREAD

**Issue by rubo77** [thunderbird/thunderbird-android#6188]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.201

### Where did you get the app from?

Google Play

### Android version

8

### Device model

shiftphone Shift 6m

### Steps to reproduce

1. delete an email in your IMAP inbox
2. reload and get this error:
![signal-2022-07-25-211450_001](https://user-images.githubusercontent.com/1591563/180860532-d7863835-fa17-4456-968a-c0db96cb812f.png)

(in Thunderbird it all works fine) 

### Expected behavior

the email should be moved into trash

### Actual behavior

The email seems to be gone at first, but after a reload it reappears, where it was. So I cannot delete any email in K9 any more.

**Comment by rubo77** [comment]
This seems to be the same error her: https://forum.k9mail.app/t/k9-beta-5-734-no-outbox-state-entry/1011

**Comment by cketti** [comment]
This is not related to deleting messages. Something went wrong when trying to send a message.

Try deleting all messages from the Outbox. If that doesn't help, please remove the account from K-9 Mail and add it again.

**Comment by cketti** [comment]
There's little chance of finding the bug unless you can provide instructions on how to reliably reproduce this error. We only know your account is in a broken state. We don't know how it got there.

**Comment by rubo77** [comment]
deleting all messages from the Outbox didn't help.

**Comment by rubo77** [comment]
deleting all messages in Trash helped though ;-/ ???

**Comment by alex9099** [comment]
Perhaps a way to get the message by id would help to narrow it down?

**Comment by vdbhb59** [comment]
This has resurfaced today. Unable to identify which email address this is related to, as I have multiple accounts added.

**Comment by immutable-pro** [comment]
This is still happening. My outbox is empty. I only have one gmail account setup. 

![Image](https://github.com/user-attachments/assets/242b0376-e917-471c-80b4-b7d6a037334a)

**Comment by kewisch** [comment]
@immutable-pro do you have any logs you could share? Can you reproduce this with a different email account and maybe have some steps to reproduce to share?

**Comment by immutable-pro** [comment]
Sure. Can you guide me to documentation about how to debug or catch logs? I'll share those ASAP.

-------- Original Message --------

**Comment by kewisch** [comment]
https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors

**Comment by vdbhb59** [comment]
> Here you have! To reproduce it, I just need to trigger a re-sync.
> 
> [thunderbird-log.txt](https://github.com/user-attachments/files/20256253/thunderbird-log.txt)

Mate, remove your email id from the logs and reattach.

**Comment by immutable-pro** [comment]
Thanks for noticing. Could you delete your own last message, please? It still links to the file.

**Comment by immutable-pro** [comment]
[thunderbird-log-redacted.txt](https://github.com/user-attachments/files/20257151/thunderbird-log-redacted.txt)
