### ISSUE TITLE
OAuth with outlook failed with "server_error"

### ISSUE THREAD

**Issue by calad0i** [thunderbird/thunderbird-android#6195]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.201

### Where did you get the app from?

F-Droid

### Android version

12, Graphene OS

### Device model

Pixel 5

### Steps to reproduce

1. Try login with any @outlook.com account
2. Redirect to the webpage in an external browser (Bromite), enter login credentials 
3. Being redirected to the app

### Expected behavior

Logged into the account

### Actual behavior

"Authorization failed with the following error: server_error"

### Logs

[37453F24055879E10A73E9E65D33BDC4AC61EDDD324508902C7F37725B2F1AC6.txt](https://github.com/thundernest/k-9/files/9197362/37453F24055879E10A73E9E65D33BDC4AC61EDDD324508902C7F37725B2F1AC6.txt)

**Comment by cketti** [comment]
This doesn't sound like a bug in K-9 Mail. The server is returning an error. Please contact the outlook.com support to find out why that is.
