### ISSUE TITLE
Contact groups can't be recipient

### ISSUE THREAD

**Issue by gtxaspec** [thunderbird/thunderbird-android#620]
https://code.google.com/p/k9mail/issues/detail?id=1996

this has been an issue that I am starting here based off the abandoned google code issue.  From 2010, still updated on that site this year.  

In K9 mail, can not select contact groups to send a group email to.  Only individual contacts.  If a group is selected to send a new email in the contact manager, then k9 selected as email client group data is populated.  

but if we try to forward a message, there is no way to select a group.  see link above for details.

**Comment by cketti** [comment]
There's no standard intent to pick a contact group. So to add this feature someone needs to implement a custom UI that offers the option to select both individual contacts and contact groups (not necessarily at the same time).

**Comment by TomFernandes** [comment]
+1
Not sure if it is possible to vote for this enhancement somewhere else. So I would like to add here that I also miss this feature.

**Comment by k0377** [comment]
:+1:

**Comment by philipwhiuk** [comment]
Contact groups don't exist in Marshmallow. This will require testing on later APIs if it is implemented.

**Comment by sgparry** [comment]
I have a Samsung Note 4 running Marshmallow (6.0.1) - I have contact groups - is this a Samsung only feature? I cannot see why G would just drop contact groups as a feature...

**Comment by PanderMusubi** [comment]
Please, also test for contact groups that exit via CardDAV.

**Comment by francwalter** [comment]
Is that feature request in work, will that be implemented some day?
Or is there another mail client for Android which could handle that?
Forward an email to a group in the address book or define a address group in that client to use it directly as forward recipient?
Thanks.
