### ISSUE TITLE
Incorrect behaviour of Lock Screen Notifications

### ISSUE THREAD

**Issue by tdboorman** [thunderbird/thunderbird-android#6229]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.300

### Where did you get the app from?

Other

### Android version

12 SKQ1.211006.001

### Device model

Xiaomi 11T Pro

### Steps to reproduce

1. Go to Settings.
2. Click on General Settings.
3. Click on Notifications.
4. Click on Lock Screen Notifications.
5. Choose any of Application name, New message count or Message count and senders.

### Expected behavior

Lock Screen Notifications would only contain the relevant content.

### Actual behavior

Lock Screen Notifcations were the same as when the screen was unlocked.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/9284178/k9mail-logs.txt)
![Screenshot_2022-08-08-19-24-47-986_lockscreen](https://user-images.githubusercontent.com/110849704/183488055-1db2a16b-b0f7-4b78-87ef-0ac974f55a4d.jpg)

**Comment by cketti** [comment]
K-9 Mail only configures notifications with this data. It's the system that actually displays the notifications. For the "lock screen notifications" setting in K-9 Mail to have any effect you need to a) configure a "screen lock" and b) select the system option "show sensitive content only when unlocked".

**Comment by tdboorman** [comment]
Unfortunately MIUI only has the option Show notifications but hide content, so the lock screen notifications still do not behave correctly.

**Comment by cketti** [comment]
Sounds like a problem with MIUI then. I don't want to reimplement functionality in K-9 Mail that should have been provided by the OS.

**Comment by sebathomas** [comment]
I have the same issue on a Pixel 4a and Nokia XR20. I don't think it's specific to MIUI.

**Comment by cketti** [comment]
@sebathomas: Are you sure that you have enabled a lock screen and configured Android to "show sensitive content only when unlocked"? Do all other apps show only redacted notifications (or no notifications at all) when the lock screen is active? Is it only K-9 Mail that is showing the full notification contents when the device is locked?

**Comment by sebathomas** [comment]
Actually, it looks like it's working now. After turning both the OS setting and the K-9 setting off and on again, I do get redacted notifications on the lock screen.
Sorry for the false alarm. I'm pretty sure I wasn't able to make it work in the past.

Also tested it on both devices and both work fine.

**Comment by tdboorman** [comment]
It actually does work in MIUI too when the somewhat misleading option Show notifications but hide content is selected.
