### ISSUE TITLE
Returning from message view scrolls the message list

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#6239]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.301

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Pixel 4a

### Steps to reproduce

1. have unread messages that cover more than one screen
2. Have unread messages being displayed always at the top of the list
3. Read the top message
4. Return to message list
5. message list scrolls down to the now read email

### Expected behavior

Previously it stayed at the top of the list which seems more sensible to me. The view scrolling potentially somewhere way down after reading an email at the top of the unread pile is certainly unexpected.

### Actual behavior

Message list scrolls to the bottom of the unread pile/top of the read pile.

**Comment by BubuOT** [comment]
It's actually not necessary to have more than one unread email for this to trigger. it just needs to be sorted on top as unread but further down in the list in it's read state to trigger the scrolling,

**Comment by zootboy** [comment]
I found the commit that introduced this behavior: https://github.com/thundernest/k-9/commit/8b546cadd6e23d64d88814f3fdf37b4c1fd6331a

I too am frustrated by this new behavior. Can it please be gated by a setting? I really don't want my message list to auto-scroll at all, as it messes with my muscle memory when rapid-firing though lots of messages.

**Comment by cketti** [comment]
Is this still a problem in K-9 Mail 6.400?

**Comment by zootboy** [comment]
I'm not able to test 6.400 right now since it hasn't hit F-droid yet, but I tested 6.312 and the issue is not present in that version.

Thanks!

**Comment by BubuOT** [comment]
> but I tested 6.312 and the issue is not present in that version.

Same here!
