### ISSUE TITLE
<a> "name" attribute is sanitized

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#6241]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

Other

### Android version

Havoc OS 4 (Android 11)

### Device model

Oneplus 3T

### Steps to reproduce

teltarif.de sends newsletters with a table of contents at the top.

In Thunderbird I can click on these headlines and it forwards me to the corresponding article/section down below.

K9 currently sanitizes name attributes of links though, so the webview(?) component doesn't know where to move the viewport to (no link with a corresponding name attribute below)

`<A NAME="a1"></A>`
is sanitized to
`<a></a>`

The corresponding link in the table of contents looks like this:
`<a href="#a1">`
You've probably seen countless websites like wikipedia who use this feature as well.
usually they use the id of an element though not an actual <a> tag with a name attribute, which is obsolete in newer html versions, I think (not that it matters for mails)

### Expected behavior

K9 shouldn't remove the attribute

### Actual behavior

K9 removes the attribute

**Comment by cketti** [comment]
I'll change the sanitizer to keep the attribute. However, this won't make anchor links work. See #2494.

**Comment by Djfe** [comment]
interesting
Well maybe you will find a workaround at some point or you are able to get rid of the scrollview somehow.
So it's good to already fix the sanitizer
I'll close this issue once the commit is merged and then follow #2494
