### ISSUE TITLE
Swiping between to a new message and back leads to a different message

### ISSUE THREAD

**Issue by Bubu** [thunderbird/thunderbird-android#6246]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.301

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Pixel 4a

### Steps to reproduce

I suppose that's connected with sorting unread messages on top (and perhaps additionally thread view?).

Opening a message, swiping right (to a message that's unread... I don't know how to set this up, but I continuously trigger that setup accidentally), swiping back left confusingly leads to a different message than you started at. This is especially bothersome if you triggered the swipe gesture only accidentally and just wanted to go back.

The path to fix this is to swipe right again, mark that message as unread and then left again.

### Expected behavior

Swiping back and forth gets you back to the message you started from.

### Actual behavior

See above

**Comment by cketti** [comment]
If you enable split screen mode you can see what's going on.

Opening a message will mark it as read and update the message list to reflect this change. If your message list is sorted by read/unread, the position of the currently opened message changes in the list. Moving to the next/previous message is consistent with that new list position (but not what users would expect).

Thunderbird on desktop handles this differently. When sorting by read/unread the app will only sort the list when opening the folder. Subsequent changes to the message read state will not change the position of that message in the list. That nicely sidesteps this problem. 
However, it requires keeping track of all messages. I was hoping we could use dynamic paging for the message list in the future (so not all messages will be loaded into memory, only the ones currently displayed in the list, plus some extra before and after).

What we could do is keep the old position of the currently opened message. That way the previous and next message won't change when marking the message as read on opening. However, the message would change its position in the list once you navigate away from it. So, when reading unread messages, swiping right to open the next message and then swiping left again won't open the previously displayed message.

Any other ideas on how to fix this?

**Comment by cketti** [comment]
I've implemented a "sort cache". Currently only the last 3 opened messages are remembered.

https://user-images.githubusercontent.com/218061/188182565-72282c30-6e21-4751-b69a-0f4f0e70ba7f.mp4

@Bubu: What do you think?
