### ISSUE TITLE
Verschlüsselungsdienst dauernd nicht erreichbar.

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#6247]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

 6.202

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Nokia 6

### Steps to reproduce

K9 kann den Verschlüsselungsdienst nicht erreichen 😠

### Expected behavior

Verschlüsselung 

### Actual behavior

Fehlermeldung kann den Verschlüsselungsdienst nicht erreichen!

### Logs

Nur ein Mini Pop-up vorhanden keine Fehler Protokolle gefunden! Pop-up Infos können nicht im Screenshot aufgenommen werden 😩

**Comment by cketti** [comment]
Probably the same as #6068
