### ISSUE TITLE
Autoconfig does not work correctly

### ISSUE THREAD

**Issue by williamdes** [thunderbird/thunderbird-android#6250]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

Google Play

### Android version

12, Using MIUI 13.0.3 stable

### Device model

Redmi Note 10 Pro

### Steps to reproduce

- Add a new email
- Enter email and password
- It does not fill auto-detect settings correctly because it calls domain.tld and not autoconfig.domain.tld first

### Expected behavior

It should try all options described in https://wiki.mozilla.org/Thunderbird:Autoconfiguration

### Actual behavior

No autoconfig can be fetched

**Comment by williamdes** [comment]
Near to every app looks into autoconfig.domain.tld. You can see in the code comments of this autoconfig project: https://github.com/wdes/mail-autodiscover-autoconfig/blob/main/src/routes/autoconfig.rs

**Comment by williamdes** [comment]
Code to blame:
https://github.com/thundernest/k-9/blob/6.202/app/autodiscovery/thunderbird/src/main/java/com/fsck/k9/autodiscovery/thunderbird/ThunderbirdAutoconfigFetcher.kt#L25-L36
https://github.com/thundernest/k-9/blob/6454d350fb81ff7af2da5167c534f3cda5b78c03/app/autodiscovery/thunderbird/src/main/java/com/fsck/k9/autodiscovery/thunderbird/ThunderbirdAutoconfigFetcher.kt#L25-L36

**Comment by cketti** [comment]
This code isn't used right now. See #865.
