### ISSUE TITLE
Crash when viewing specific email(s)

### ISSUE THREAD

**Issue by creeble** [thunderbird/thunderbird-android#6251]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.301

### Where did you get the app from?

Google Play

### Android version

7.0

### Device model

Lenovo tb-8304f1

### Steps to reproduce

Select email (Digital Music News daily newsletter is one, NYTimes daily update is another).

App crashes while attempting to display.

### Expected behavior

Not crashing.  Display email.

### Actual behavior

Crash with no message (system message "App stopped").

### Logs

[1038.txt](https://github.com/thundernest/k-9/files/9389688/1038.txt)

**Comment by cketti** [comment]
This looks like the WebView system component (that K-9 Mail is using to display messages) is crashing. Try updating Chrome and/or "Android System WebView".

**Comment by creeble** [comment]
Both Chrome and Android System Webview were updated on 2022-08-16, currently version 104.0.5112.97.

I have other apps that use webviews, but only K9 crashes, and only on certain emails (but 100% repeatably).

I guess this is a NOFIX then?
