### ISSUE TITLE
No lockscreen notification at all

### ISSUE THREAD

**Issue by choco-latin** [thunderbird/thunderbird-android#6260]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

Google Play

### Android version

9 PKQ1.180904.001 with MIUI 11.0.3

### Device model

Xiaomi Redmi Note 5

### Steps to reproduce

[Disclaimer] my app is in french so I'm traducing the menus on-the-fly, it might not be exactly the english equivalent

1. Go to the account XX parameters > notifications > and set
  - notifications for incoming mail ON
  - Notification folders ALL
  - Vibration ON
  - Light ON (system default)
2. Go to general parameters > notifications and set
  - notifications on lockscreen "identical to the unlocked screen"
3. Turn off the screen
4. send an email to XX from YY

### Expected behavior

1. The phone vibrates, turns on the light
2. When turning on the phone (still locked), a notification is there
3. When unlocking the phone, a notification is there

### Actual behavior

1. The phone vibrates ✔️ but the light doesn't turn on (not really a big deal for me but I mention it just in case) ❌ 
2. When turning on the phone (still locked), there is NO notification ❌ 
3. When unlocking the phone, a notification is there ✔️ 

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/9452715/k9mail-logs.txt)

NB : I removed my email adresses from the logs.

**Comment by cketti** [comment]
It's unlikely that this is a bug in K-9 Mail. This behavior is controlled by your Android version. Make sure you didn't configure Android to never show notifications on the lock screen. On my Android 12 device this option can be found under *Settings → Notifications → Notifications on lock screen*.

**Comment by choco-latin** [comment]
Hi and thanks for your answer!
Unfortunately I already checked that (I saw it mentioned in an other issue) and the parameters at the "global" level and "K-9 app" level are to display every notifications on the lock-screen. 
For the record, I have been receiving notifications on the lock-screen from all my apps since years without problem.

**Comment by cketti** [comment]
Do K-9 Mail notifications show on the lock screen when there is more than one new message?

**Comment by choco-latin** [comment]
Got it! The problem was indeed a matter of Android parameters! The point is that between my install of the app, me trying to get notifications, trying to look for Android's parameters, I actually never rebooted the device.
After a reboot the notifications appear on the lock-screen as intended!

Thanks again for your fast answer which forced me to think more about it! 

a (satisfied) new K-9 user
