### ISSUE TITLE
Keeps asking for contacts permission on startup

### ISSUE THREAD

**Issue by robsmith11** [thunderbird/thunderbird-android#6261]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Huawei Mate 20 X

### Steps to reproduce

1. Open k-9
2. Deny contacts permissions and confirm in Android settings that it is marked denied.
3. Open k-9 again.

### Expected behavior

No nagging pop-up asking for contact permission.

### Actual behavior

Pop up

### Logs

There was a previous post about this where the suggested fix was to temporarily enable contacts and then deny later, but that is not a good workaround because then the app has already read all of my contacts.  A proper fix should be implemented in k-9.

**Comment by cketti** [comment]
You could force stop the app before granting, then revoking the permission. That should prevent the app from ever running with the contacts permission. 
However, K-9 Mail will not read all of your contacts and do something nefarious with the data. It will only use the permission to load contact pictures and to offer auto-completion when entering email addresses in the compose screen. 

I created issue #6262 to work around buggy Android versions that will always show the permission prompt no matter how often users declined to grant the permission.
