### ISSUE TITLE
Mark all read on IMAP accounts also marks unseen messages as read

### ISSUE THREAD

**Issue by willamowius** [thunderbird/thunderbird-android#6269]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

Google Play

### Android version

Android 11

### Steps to reproduce

When marking all mails as read, K9 will mark all mails on the server as read, including those not yet seen by the user. 

1. select a not to frequent mail fetch interval, eg. manually for testing
2. fetch mails, scan all mail subjects, decide nothing is important
3. send another mail to the server
4. mark all mails a read

This latest mail will now be marked as read, even so no even the subject was visible on the user device,

### Expected behavior

It should only mark those as read that have already been downloaded.

### Actual behavior

All mails on server are currently  marked as read by the function.

**Comment by cketti** [comment]
This is the intended behavior. The app is even showing a confirmation dialog, so you don't accidentally use this action.

If you want to mark all downloaded messages as read, use "select all" from the menu, then the "mark as read" action.
