### ISSUE TITLE
No push when using mobile data

### ISSUE THREAD

**Issue by Maetts** [thunderbird/thunderbird-android#6274]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.301

### Where did you get the app from?

Google Play

### Android version

Android 11 / EMUI 12

### Device model

Huawei P30 Pro NE

### Steps to reproduce

Setup mail account
Poll settings setup to push 1st class folders
Check if it works via wifi
If no
Correct settings until it works with wifi
If yes
Turn off wifi and use mobile data
Wait for push to receive mails

### Expected behavior

Mails should be pushed as with wifi

### Actual behavior

No real push, mails come in with huge delay hours later or when connecting back to wifi

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Maetts** [comment]
Ok. What data is collected via this log (without sensitive logs)?

**Comment by cketti** [comment]
Why don't you have a look and redact it if necessary before posting it here? It's plain text.

**Comment by Maetts** [comment]
I will check and tune it once logged..
