### ISSUE TITLE
"Strip signatures on reply" does not work

### ISSUE THREAD

**Issue by FueLee** [thunderbird/thunderbird-android#6279]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Samsung Galaxy S22

### Steps to reproduce

1. Add outlook account 
2. Edit identity
3. Check "Use Signature"
4. Write a signature
5. Check the default setting of "Strip signatures on reply". It is checked.
6. Write an email to myself
7. Reply to myself
8. Reply again

### Expected behavior

Signatures will be removed from quoted messages

### Actual behavior

```text
Hi,

This is the second reply.

On September 7, 2022 10:41:26 AM GMT+02:00, "User" <user@outlook.com> wrote:
Hi,

This is the first reply.

On September 7, 2022 10:40:11 AM GMT+02:00, "User" <user@outlook.com> wrote:
Hi,

This is it.
--
Regards,
User
--
Regards,
User
--
Regards,
User
```

### Logs

![image](https://user-images.githubusercontent.com/95375431/188836344-282793bf-a3b1-4630-ab51-ccea738d191a.png)

**Comment by cketti** [comment]
K-9 Mail only detects the standard signature delimiter. That's two dashes followed by a space on its own line. Such signatures will also be displayed slightly differently when viewing a message.

![image](https://user-images.githubusercontent.com/218061/188838300-7ce56654-9c33-4b86-a81d-1048ffa7f957.png)

**Comment by FueLee** [comment]
Hi,

I repeated the test with the standard signature delimiter, and it is slightly different, however still not removed.

![image](https://user-images.githubusercontent.com/95375431/188840604-f74c54ff-61e9-4f6b-b124-8ad13cba90ba.png)

**Comment by cketti** [comment]
That's unexpected. The signature is detected when displaying the message, but not stripped when replying to the message. It seems to work fine for `text/plain` parts, but not for `text/html` parts.

Anyway, I can reproduce this. That should be enough to find and fix the bug. Thanks for reporting it :+1:

**Comment by FueLee** [comment]
Thanks for the fix! 👍🏻
