### ISSUE TITLE
6.304 crash immediately

### ISSUE THREAD

**Issue by plegrand1** [thunderbird/thunderbird-android#6306]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.304

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Xiaomi MI 9

### Steps to reproduce

Launch K9 mail

### Expected behavior

---

### Actual behavior

Hello,
since the last update (6.304) the application doesn't launch anymore, it crashes right away without me being able to see anything.
Via Fdroid, it is impossible for me to downgrade to the previous version (6.303)
Any idea where the problem could come from?
Thanks for your help
Pascal

**Comment by SubSi** [comment]
Same issue on Huawei Mate 20 HMA L29, Emui 12, Android 10 via f-droid
Stopping the App via system settings worked at first but but then k-9 keeps crashing again.

**Comment by cketti** [comment]
When reporting crashes, please always include a debug log. https://github.com/thundernest/k-9/wiki/LoggingErrors

This particular crash is probably the one we fixed in 6.305. See https://github.com/thundernest/k-9/pull/6304

**Comment by plegrand1** [comment]
As the application crashes immediately, it is impossible to retrieve the logs either from the application itself or via adb
