### ISSUE TITLE
"Show next message after delete" no longer opens previous message when there is no next message

### ISSUE THREAD

**Issue by FeZoli** [thunderbird/thunderbird-android#6315]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.305

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Motorola g52

### Steps to reproduce

Prerequisite:
Set "Display next message after deletion" to on in General Settings/Interaction

1. Go to a mail folder
2. Set the order by date
3. Scoll down to the last item in the list
4. Open that mail
5. Delete that mail

### Expected behavior

In the previous version the system displyed the next mail (aka. the more recent one)
Note, I might remember there was an arrow in the header, to switch direction if I wanted to go one mail down or up when in the mail reading pane.

Please pull this useful function back.

### Actual behavior

The system displays the list instead of the next mail (the more recent one)

The direction change arrow is also missing now.

**Comment by cketti** [comment]
Thanks for the bug report. We'll restore the old behavior to open the previous message when there is no next message that could be opened.

The arrow icons were removed because you can now swipe left and right to move to the previous and next message.

**Comment by FeZoli** [comment]
Thank you guys. You re just awesome :)
