### ISSUE TITLE
Sent messages not uploaded

### ISSUE THREAD

**Issue by gregorymarchal** [thunderbird/thunderbird-android#6321]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.304

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Nokia 5.3

### Steps to reproduce

Write an e-mail and send it.

### Expected behavior

The e-mail is sent and a copy of the sent e-mail is uploaded in the 'Sent' folder, even if this option is checked in *Settings*.

### Actual behavior

The e-mail is sent *but* a copy of the sent e-mail *is not* uploaded in the 'Sent' folder.

Tried with two different accounts, didn't work as expected on both. The corresponding option is checked for both accounts.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/9624467/k9mail-logs.txt)

**Comment by njeyaakili** [comment]
in: 

   settings/[account]/folders/sent folder"

does the selection match the "sent" folder name on the server?

this is really a "support" question, so if this doesn't point to a resolution of your issue you should probably take further discussion to the user forum <https://forum.k9mail.app/>, where a search will turn up a number of items on this.
