### ISSUE TITLE
Polling notification gets stuck spinning after network is disconnected

### ISSUE THREAD

**Issue by bbhtt** [thunderbird/thunderbird-android#6322]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.305

### Where did you get the app from?

Google Play

### Android version

Android 7

### Device model

A1-0301

### Steps to reproduce

IMAP account set to manual polling, no push.

1. Open K9Mail while being connected to network
2. Pull to refresh the email list, see the "Checking new mail" spinner appears
3. Disconnect from network
4. See that the spinner continues to spin and the notification doesn't get dismissed. (I have to force stop at this point)

I suspect this has something to do with [pfDNSFilter](https://github.com/IngoZenz/personaldnsfilter) which runs as a local VPN and waits for the network to come back up.

### Expected behavior

The notification should get dismissed immediately

### Actual behavior

It doesn't get dismissed.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/9625681/k9mail-logs1.txt)

**Comment by fereshtehamiri** [comment]
hello @bbhtt 
I have been trying to reproduce the issue you described( in Samsung A32, Android 13) , But this bug didn't happen for me.
when i refresh the email list i did not any notification and just see the spinner continues to spin.
I was wondering if you could provide me with more information (picture or video) on the scenario you experienced in order to help us resolve the issue.

I appreciate your attention.

**Comment by bbhtt** [comment]
I don't have the Android 7 device any more, and it doesn't happen on my Android 10 phone.

**Comment by williamdes** [comment]
This looks like #4747
It loops for ever and drains all the battery, does someone else also confirm the battery drain and phone heat up ?

**Comment by bbhtt** [comment]
Yea looks like that one. Although I always force closed through Android settings so I had no battery drain.

I'm closing this since it looks like a dupe.
