### ISSUE TITLE
Unread mail disappearing after reading one unread message

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#6326]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.306

### Android version

13 - GrapheneOS TP1A.220905.004.A1.2022091400

### Device model

Pixel 6

### Steps to reproduce

1) Navigate to mailbox - ensure there are multiple unread messages
2) Sort mail by Read/Unread
3) Read the first unread message
4) Swipe/navigate back to mailbox
5) All other unread messages disappear until you force close and restart the app

### Expected behavior

Unread messages should stay in view 

### Actual behavior

Unread messages are disappearing/vanishing

**Comment by cketti** [comment]
Are you sure the messages disappear from the message list? Could it be the following issue?
- #6239

**Comment by bootlesshacker** [comment]
Apologies - I didn't find this other issue when searching. #6239 is what I'm observing so closing this as a duplicate
