### ISSUE TITLE
Message list does not scroll to newest messages after "pull down" gesture

### ISSUE THREAD

**Issue by oh2kku** [thunderbird/thunderbird-android#6332]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.307

### Android version

OxygenOS 11.1.2.2

### Device model

OnePlus 6T

### Steps to reproduce

In a messsge list view, for example inbox, updating the message list manually by "pull down" gesture does not scroll to show the new messages in the folder automatically anymore. This used to work a version or few back.

Now I have to scroll the list manually after the pull down gesture mailbox update finishes to see if there are new messages or not. This is bad usability.

I'm using "sort by" arrival, newest messages on top. IMAP server is Dovecot 2.2.36 and has not changed when the automatic scrolling after mailbox update stopped working in K9.

### Expected behavior

See above

### Actual behavior

See above

**Comment by mpas97** [comment]
It's annoying yes. I already often thought there is nothing new..

**Comment by cawauk** [comment]
Same problem here. I don't use automatic polling or push. I open K9 when I want to check emails and scroll up (finger swipe down) when at the top of my inbox list, forcing K9 to check my mailboxes. Emails get retrieved from server, but new messages do not appear on screen. To see whether I have new messages after the poll, I need to scroll up (finger swipe down) again. If no new messages, this causes K9 to check my emails again. If new messages, unified inbox list scrolls up to new messages. Very frustrating. Never happened before this/last week's update.

**Comment by Siggy007** [comment]
Same issue since 6.07 beta

**Comment by darkknight1812** [comment]
I am also having this issue on 6.308 and 6.307 Android beta.

**Comment by cketti** [comment]
This bug hasn't been fixed yet. So it's not surprising that it's still an issue in recent versions of the app. There's no need to report this fact.

**Comment by cketti** [comment]
The fix for this is included in K-9 Mail 6.309.
