### ISSUE TITLE
Pre-release APKs fail to imstall

### ISSUE THREAD

**Issue by Meche697** [thunderbird/thunderbird-android#6333]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.30x

### Where did you get the app from?

Other

### Android version

13

### Device model

Pixel 6 pro

### Steps to reproduce

I have 5.202 installed and working
APKPure shows an updated version (latest 5.307)
Try to install 5.30X fails

I don't recall if I installed K9 from APKPure or FDroid. APKPure is the only one that shows the pre-release.  I also tried downloading the APK from here (GitHub) and it did not install

### Expected behavior

Install APK on mobile

### Actual behavior

Apak install, for pre-release, fails

### Logs

NA

**Comment by cketti** [comment]
That's a security feature. You can only upgrade an app if the APK is signed using the same key that was used to sign the initial version you installed. For historical reasons the F-Droid version is signed using a different key than the version on Google Play and GitHub. So you can't switch between those versions. If you initially installed from F-Droid you need to wait for updates to be available on F-Droid.

Even though Android checks signatures on app updates, you should avoid downloading APKs from random websites (e.g. APKPure).
