### ISSUE TITLE
Scroll bar in Unified Inbox view looks different from rest of UI and is janky

### ISSUE THREAD

**Issue by mishrashutosh** [thunderbird/thunderbird-android#6336]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

LineageOS 19.1 (Android 12)

### Device model

Poco X3

### Steps to reproduce

1. Setup multiple email accounts.
2. Open Unified Inbox view.
3. Notice the scrollbar on right while scrolling through mails, and compare it to scrollbars on other screens of the app.

### Expected behavior

Unified Inbox view should use the same scrollbar as rest of the app screens.

### Actual behavior

The scrollbar in Unified Inbox is different from the ones in other screens of K-9. It resembles native Android scrollbars of KitKat (4.4) instead of the modern scrollbar design in newer Android versions. Design aside, the particular scrollbar is also quite janky and doesn't scroll smoothly.

![IMG_20220930_114858](https://user-images.githubusercontent.com/6448741/193204358-e1a90d6a-7fef-4c79-aa00-60e68bcc05f0.jpg)

**Comment by cketti** [comment]
The UI widget used to display the message list has been replaced in K-9 Mail 6.306 (beta). So this will no longer be an issue in the next stable version.
