### ISSUE TITLE
screen reader won't say unread for unread message #accessibility

### ISSUE THREAD

**Issue by techexplorers123** [thunderbird/thunderbird-android#6348]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.307

### Where did you get the app from?

Google Play

### Android version

android 12

### Device model

oneplus nord ce5g

### Steps to reproduce

step 1, enable a screen reader such as talk back.
step 2, open k9mail and focus an unread message

### Expected behavior

the screen reader should say if the message is unread 
e.g. unread, sender time subject messagepreevue

### Actual behavior

the screen reader  will not say unread for unread messages
e.g. sender time subject messagepreevue

**Comment by cketti** [comment]
Is this something that has worked in previous versions of K-9 Mail?

**Comment by techexplorers123** [comment]
I don't know I just started using k9mail recently

On October 5, 2022 2:00:58 PM GMT+05:30, cketti ***@***.***> wrote:
>Is this something that has worked in previous versions of K-9 Mail?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/thundernest/k-9/issues/6348#issuecomment-1268118481
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Best regards, varun.

**Comment by techexplorers123** [comment]
This is not fixed yet@cketti

**Comment by bijaykumarpun** [comment]
looking into this..

**Comment by bijaykumarpun** [comment]
@cketti Can assign me this please? I'd like to work on this.
Will prepend email subject with `Unread email` for talkback to read.

**Comment by cketti** [comment]
@bijaykumarpun: We don't typically assign issues to non-team members. But please feel free to work on this issue.
