### ISSUE TITLE
K9-Mail crashes when touching area of attached mail and quickly trying to type

### ISSUE THREAD

**Issue by StefanBrand** [thunderbird/thunderbird-android#642]
What steps will reproduce the problem?
1. Tap in the reply area, so the keyboard opens
2. Tap in the area of the attached message
3. quickly start typing before the keyboard disappears -> K9mail has stopped working.

What do you expect to have happen?
- No crash, or that keyboard disappears more quickly, or that current message gets saved before K9-Mail crashes.

What version of K-9 are you using?
- 5.005

What is your device and what version of Android are you using?
- Fairphone FP1 (MT6589 chipset)
- Android 4.2.2

What else should we know?
- The crash produces no entry in the log (using CatLog on the rooted phone).
- We have discussed this in the Fairphone Forum and the issue seems quite reproducible: https://forum.fairphone.com/t/k9-mail-crashes-when-trying-to-type-in-area-of-attached-mail/5899

**Comment by cketti** [comment]
Without a stacktrace there's not much we can do. The user who posted one in the linked forum seems to use the Xposed framework. If you use that you're on your own.
Anyway, this is most likely a bug in your firmware, not a K-9 Mail bug.

**Comment by newluck77** [comment]
Thank you for your reply. We will try to elaborate this further and keep you posted!

**Comment by newluck77** [comment]
> Workaround for people who are annoyed by this error: In K9, go to [Settings][Account settings] [Sending mail], tap [Message format], choose Plain Text (remove images and formatting).
I think we can live with that. Maybe it is also related to [this bug in the Fairphone firmware](https://forum.fairphone.com/t/firefox-problem-with-touch-events/5843/24?u=stefan), so I will close this topic. Thank you!
