### ISSUE TITLE
Render in HTML <tt> with monospaced font

### ISSUE THREAD

**Issue by dilyanpalauzov** [thunderbird/thunderbird-android#6423]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

12

### Steps to reproduce

I (send and) receive an email containing:
```
--example.org=_3175999=_1666532806=_1948217805_A
Content-Type: text/html; charset=utf-8
Content-Disposition: inline

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head><title></title></head><body>
<b>You have received an updated invitation from <a href="mailto:abc@example.org">A B C</a></b><p>
<table border cellpadding=5>
<tr><td><b>Summary</b></td><td>Hokus Pokus</td></tr>
<tr><td><b>Location</b></td><td>somewhereL2</td></tr>
<tr><td><b>Start</b></td><td><tt>Thu,&nbsp;27&nbsp;Oct&nbsp;2022&nbsp;07:00&nbsp;UTC<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;10:00&nbsp;Europe/Sofia&nbsp;</tt></td></tr>
<tr><td><b>Attendees</b></td><td>&#8226; <a href="mailto:gggg@example.int">Ombre</a>
  <br>&#8226; <a href="mailto:1@mail.aegee.org">fff@example.be</a></td></tr>
<tr><td><b>Description</b></td><td>Long text, no meaning.</td></tr>
</table></body></html>
```

### Expected behavior

I expect that the text bewenn `<tt>` and `</tt>` is rendered with monospaced font.

### Actual behavior

No monospaced font, the lower line is aligned to the upper line

**Comment by cketti** [comment]
Our HTML sanitizer removes all tags that are not explicitly allowed. `<tt>` is deprecated and hence wasn't on the allow list. I'll add it. But you might want to let the sender know that they should switch to alternatives. You could point them to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt

**Comment by dilyanpalauzov** [comment]
When I replace `<tt>` with `<samp>` the text is also not monospaced and `<samp>` is not deprecated.  Looking at the change, `<pre>` and `<code>` seem also to be stripped.

Moreover, in 
```
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<html><body><table><tr><th scope="column" colspan="2"
style="color:#000;background-color:#ffd700"
>ZZZ</th></tr></table></body></html>
```
the foreground and background colors are not displayed by K9 mail.

**Comment by cketti** [comment]
> When I replace `<tt>` with `<samp>` the text is also not monospaced and `<samp>` is not deprecated. 

`<samp>` was indeed not on the allow list. I'm guessing mainly because it is not very commonly used. Same goes for `<kbd>` and `<var>`. I'll add them to the list.

> Looking at the change, `<pre>` and `<code>` seem also to be stripped.

Those two are not stripped. If you used "ZZZ" for your tests, it's hard to see the difference between regular and monospaced text, though.
To find out what the sanitized HTML looks like you could clone the repository, make sure you have a JDK installed, then run
`./html-cleaner input.html` in the root of the repository.
 
> Moreover, in
> 
> ```
> Content-Type: text/html; charset=UTF-8
> Content-Transfer-Encoding: 8bit
> 
> <html><body><table><tr><th scope="column" colspan="2"
> style="color:#000;background-color:#ffd700"
> >ZZZ</th></tr></table></body></html>
> ```
> 
> the foreground and background colors are not displayed by K9 mail.

Works fine for me. The values are overridden when using the dark theme, though. See #4198.

**Comment by dilyanpalauzov** [comment]
`style="color:#000;background-color:#ffd700"` is indeed honoured, when using light theme.

In my case the user can select any colour as background and the software sets black or white for the foreground text, depending on which of black/white has higher contrast to the background.

Since it cannot be assumed that emails are read/composed on white background, the background-color should either be always ignored, or always considered.  K9 shall assume that the sender knows what it is doing by setting `style="color:#000;background-color:#ffd700"` (as in my case).
