### ISSUE TITLE
Notifications on new emails reappear after removal (notification bar)

### ISSUE THREAD

**Issue by Yukusoona** [thunderbird/thunderbird-android#6426]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

Google Play

### Android version

10

### Device model

Samsung S9

### Steps to reproduce

Notification on new email(s) appears in the notification bar. 
I open the notification bar and see details on all new emails reported by K9. 
When I delete the notification (either by swiping away or by pressing the x) it returns as new notification after 1 or 2 seconds. 
When I delete the notification a second time it stays gone for good. Although, in some (?) cases the notification will pop up again together with another notification on newer emails at a later time point. 

### Expected behavior

Dear Sir or Madam, 
I am writing at your advice from the K9-Forum. Link to the thread: 
https://forum.k9mail.app/t/notifications-on-new-emails-reappear-after-removal/5451
In short: Every email notification appearing in the status bar reappears a second time after I have removed it (mostly swiped away but not only). After its reappearance I usually remove them by swiping them away a second time. And after that they stay gone. 
This applies to all my 6 different email accounts I use in K9. Some of them sync via POP3 and some via IMAP. 
Expected behavior should be: deleted notifications should stay deleted after their first removal.  
Can you help me? I am adding the log file. 
Thank you!
Yukusoona

### Actual behavior

In short: Every email notification appearing in the status bar reappears a second time after I have removed it (mostly swiped away but not only). After its reappearance I usually remove them by swiping them away a second time. And after that they stay gone. 
This applies to all my 6 different email accounts I use in K9. Some of them sync via POP3 and some via IMAP. 

### Logs

[221001-k9mail-logs.txt](https://github.com/thundernest/k-9/files/9852075/221001-k9mail-logs.txt)

**Comment by Lordsem** [comment]
same issue here with Samsung Galaxy A51

**Comment by cketti** [comment]
K-9 Mail 6.202 doesn't contain enough logging to track down notification issues like this. Please install K-9 Mail 6.311 or newer and record a debug log when this is happening. See https://github.com/thundernest/k-9/wiki/LoggingErrors

Please include a description of what you saw when you recorded the log. Example: received three new messages, swiped away the notification for the first message (the notification disappeared), tapped the second notification to open the message (the notification disappeared), went back to the message list inside the app and the two notifications reappeared.

**Comment by gbenson** [comment]
[k9mail-logs.txt](https://github.com/thundernest/k-9/files/10079547/k9mail-logs.txt)

Here's a log, I left it running until the error occurred, so the interesting bit will be towards the end (around 2130). I was in some other app and a mail notification appeared; I swiped it away, then the same notification reappeared. I swiped that away too and it didn't come back. Then I went into K-9 and saved the log. IIRC there were other notifications earlier in the day that didn't reappear.

I've redacted the log some, but I have the original in case I redacted too much!

**Comment by cketti** [comment]
The problem seems to be triggered by your Android version aggressively killing K-9 Mail's process. 

When you dismiss a notification, the OS has to (re)start the app to notify it about this event. However, K-9 Mail also restores notifications when the app process is started. It looks like the dismiss event arrives before the app has read the information about notifications from its database. So the dismiss event is ignored because at that point the corresponding message can't be found. Afterwards the app loads information about notifications from the database and creates/restores system notifications based on that data.

We'll have to change the code to make sure the information about active notifications is always loaded before the app handles the dismiss event.

In the meantime you could try to exempt K-9 Mail from being killed all the time. See https://dontkillmyapp.com/

**Comment by cketti** [comment]
> Anyway, I'm using 6.400 now, and I've turned off as much of the power management as I could find (it's in at least two places) but the issue is still there—should it have gone away?

No. The issue is still open. The bug hasn't been fixed yet.

**Comment by Yukusoona** [comment]
Thank you very much for looking into this problem. If you see a chance to fix this problem and there is a prospect of fixation in the future, I for myself am going to "endure" this behaviour and eagerly wait for a future update with a fix. 
Thanks a lot!
