### ISSUE TITLE
Protonmail: Unable to establish connection with IMAP server.

### ISSUE THREAD

**Issue by Rafee-M** [thunderbird/thunderbird-android#6440]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.309

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

OnePlus 9RT

### Steps to reproduce

Attempting to login to Protonmail through IMAP.

### Expected behavior

Successfully logging in.

### Actual behavior

Showing error cods: unable to establish connection with IMAP server.

**Comment by cketti** [comment]
Protonmail does not support IMAP. You need to use the "Proton Mail Bridge". See https://proton.me/support/imap-smtp-and-pop3-setup

In the future please use the [forum](https://forum.k9mail.app/) for support requests.
