### ISSUE TITLE
Certificate error not reported to the user

### ISSUE THREAD

**Issue by SR-gh** [thunderbird/thunderbird-android#6444]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Galaxy S21

### Steps to reproduce

When using a secured connection to a SMTP server, if the certificate becomes invalid, the error is not reported to the user.
The mail is silently kept in the folder "to be sent".

If you go to your account parameters, then sending server parameters, you just have to validate the data without changing a thing in order for an error to pop-up.

You confirm the security exception and that's OK.

Please note that the same applies to IMAP server, but you can see that something goes wrong because you receive no more emails on a particular account.

### Expected behavior

I think that the certificate error should be reported at least once each time you run K9.run 

### Actual behavior

No error is reported, people that send you emails get upset and that's a drama.

**Comment by zootboy** [comment]
The same issue happens when importing an account settings export to a fresh install. If there is a certificate error (e.g. from a self-signed certificate on the IMAP server), no user-visible notification is made, the account just silently fails to load any messages. Going through the Account settings -> Fetching mail -> Incoming server flow allows you to see the error and accept the cert.

Tested on Android 13 (Lineage 20), K-9 v6.602.

**Comment by cketti** [comment]
When an untrusted server certificate is encountered the app should display an error notification. Apparently that's not always working. It would be helpful if someone could provide step by step instructions on how to reproduce the error (using concrete hostnames) or a debug log.

**Comment by SR-gh** [comment]
I do not have a step by step scenario to reproduce, but here is a more detailled description of how I think it happens in a case :
* smtp server host : smtp.myprovider.com
* smtp server has self-signed certificate that expires
* your domain : yourdomain.com
* in your domain DNS, alias smtp.yourdomain.com to smtp.myprovider.com
* configure smtp.yourdomain.com in K9
* successfully send emails, you will have to accept the security exception for the certificate on the way
* wait for the certificate to expire
* try to send an email : you get no error report, the email is not sent
* go to your preferences in order to « refresh » your conf
* the security exception has to be accepted anew
* try to send an email : the email is sent

**Comment by cketti** [comment]
When an invalid certificate is accepted by the user, the app only makes sure it's the same certificate every time a connection is established. Whether or not the certificate is expired doesn't matter and is not treated as a certificate error. A certificate error will only be reported if the server certificate changes to a different invalid certificate.

The send error might have been unrelated to the server certificate. Anyway, there's not much we can do without more information. The next time this happens, please record a debug log while trying to send a message and open a new issue.
