### ISSUE TITLE
Push folder configuration setting not accepted / persisted

### ISSUE THREAD

**Issue by hooger** [thunderbird/thunderbird-android#6461]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

LineageOS 19.1 build: 20221101, Android 12 

### Device model

ONEPLUS A6003

### Steps to reproduce

- Settings
- Accounts
- SZTAKI (account name)
- Download mails (Levelek letöltése in Hungarian)
- Push folders
- Set from None, to All, or All but 2nd level (tried some others)
- Change seems to be okay.
- Back
- Download mails again
- Push folders settings is back to None

The experienced behaviour is the same as in #5568, however the fix landed in 5.8 so the reason is different I think,

### Expected behavior

Push folder settings should stay as set.

### Actual behavior

Push folders settings changes back to None.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/9944329/k9mail-logs.txt)

**Comment by cketti** [comment]
You should try to avoid enabling Push for all folders. See https://forum.k9mail.app/t/how-to-configure-push/1102/1

The email server for the account "SZTAKI" doesn't seem to support the IDLE extension. So it's not possible to use Push with that account.
