### ISSUE TITLE
K9.Mail silently stops IMAP sync if IMAP server chanegs its ssl key

### ISSUE THREAD

**Issue by toralf** [thunderbird/thunderbird-android#6468]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

Google Play

### Android version

11

### Device model

Samsung

### Steps to reproduce

1. create an account
2. wait a year (eg. for Hetzners IMAP service)
3. be annoyed

### Expected behavior

I should be asked to accept new keys.

### Actual behavior

I'm forced to delete an account an re-create them.

**Comment by cketti** [comment]
If you have to manually accept a server certificate either the server or the client (or both) are misconfigured. You should never have to do that. Please ask your server admin for help.

K-9 Mail 6.311 and newer should show an error notification when a certificate error is encountered during sync.

Even in earlier versions there's no need to delete and re-create an account. You can go to *Settings → [Account] → Fetching mail → Incoming server* and press the *Next* button. This will show a prompt to manually accept an invalid server certificate.

**Comment by toralf** [comment]
I used K9 Mail now since years - and I had to recreate the Hetzner accounts every year due to invalid certificate.

I recreated the affected accounts. During that I was asked to accept a cert which was marked as invalid.

**Comment by cketti** [comment]
That's most likely because you're using a hostname that isn't included in the server's TLS certificate. If you used the proper hostname, the app wouldn't ask you to accept an invalid server certificate. Please talk to Hetzner to get the proper server settings to enter in K-9 Mail.

**Comment by toralf** [comment]
> That's most likely because you're using a hostname that isn't included in the server's TLS certificate.
Indeed.
Thunderbird behaved better in this area, it had chosen the name mail.your-server.de whereas K9 choosed imap.zwiebeltoralf.de when I specified the email address hetzner@zwiebeltoralf.de.
