### ISSUE TITLE
Can't be dark widget on the dark mode

### ISSUE THREAD

**Issue by xmha97** [thunderbird/thunderbird-android#6480]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Xiaomi 11T

### Steps to reproduce

1. Change Theme

### Expected behavior

Widget became dark

### Actual behavior

Widget can't follow system theme.

**Comment by cketti** [comment]
Duplicate of #3728
