### ISSUE TITLE
font size of the folder name, folder status fields don't changed

### ISSUE THREAD

**Issue by mhf1998** [thunderbird/thunderbird-android#6483]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.313-SNAPSHOT

### Where did you get the app from?

Other

### Android version

8.1

### Device model

emulator

### Steps to reproduce

1. Go to drawer menu
2. go to "Settings"
3. go to "General settings"
4. go to "Display"
5. in "Global" go to "Font Size"
6. in "Folder lists" click on "Folder name"
7. change checkbox item to "Tiniest"

### Expected behavior

It is expected that in the folder list in the drawer menu, or in the folder list in the "Manage folders", the font size of folders name will be changed.

### Actual behavior

There is no change in the font size

**Comment by cketti** [comment]
The fact that nobody has reported this as a bug before is a good indicator that this doesn't seem to be an important feature. I think I'd rather remove those settings.

**Comment by mhf1998** [comment]
> The fact that nobody has reported this as a bug before is a good indicator that this doesn't seem to be an important feature. I think I'd rather remove those settings.

Thank you for your quick response
