### ISSUE TITLE
Add a duplicate account

### ISSUE THREAD

**Issue by mhf1998** [thunderbird/thunderbird-android#6495]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.313-SNAPSHOT

### Where did you get the app from?

Other

### Android version

8.1

### Device model

emulator

### Steps to reproduce

1. Login
2. Go to the drawer menu
3. Go to settings
4. Click on add account
5. Enter the account information of the same account that exists, and login again

### Expected behavior

Show a warning that you are already logged in with this account. And don't allow re-login and duplicate account creation

### Actual behavior

It is logged in without problems and two duplicate accounts are created.

**Comment by cketti** [comment]
Especially for debugging purposes it's sometimes useful to add the same account twice.

I don't think a lot of people will add the same account twice on accident. So I don't see much value in adding a "warning" message.
