### ISSUE TITLE
OAuth2 app permissions on Office365

### ISSUE THREAD

**Issue by FlorentCoppint** [thunderbird/thunderbird-android#6517]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

13

### Steps to reproduce

When we use k9 for an Office365 e-mail account, we must use Oauth2 authentication.
But for some domain, administrator must "allow" an app on his domain.

And an administrator just told me that K9 app is asking for a specific permission, not compatible with his company security rules : "Display basic user profiles" (translated from french : "Afficher le profil de base des utilisateurs").
He told me that app could get all users database with this permission. And he doesn't know the app, so he doesn't allow it.

I don't have any problem with Thunderbird for this company.

Could it be possible to reduce permissions asked for K9 on Office365 cloud to minimum ?

### Expected behavior

K9 app allowed with low permissions policy.

### Actual behavior

K9 app not allowed because of a specific permission.

**Comment by cketti** [comment]
K-9 Mail doesn't explicitly request the "profile" scope. Maybe it is tied to the email scopes we do request ("https://outlook.office.com/IMAP.AccessAsUser.All", "https://outlook.office.com/SMTP.Send", "offline_access").

The "profile" scope "Allows the app to see your users' basic profile (name, picture, user name)." (see https://learn.microsoft.com/en-us/graph/permissions-reference or https://learn.microsoft.com/fr-fr/graph/permissions-reference)

K-9 Mail doesn't make use of that. But it doesn't feel dangerous for an email client to have access to information about the user of the email account. It does NOT give access to the name, picture, and user name of all users of the domain.
