### ISSUE TITLE
Archive feature does not work for manually created Archive folders

### ISSUE THREAD

**Issue by emes81** [thunderbird/thunderbird-android#6528]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

11 (Lineage OS)

### Device model

OnePlus 3T

### Steps to reproduce

1. Open email account with posteo.de
2. Create a folder named "Archive"
3. Send an email to the new posteo.de account. In message view, there will be no option to archive the email; in message list, swipe-to-archive gesture will not be available

### Expected behavior

Archive icon is shown/swipe-to-archive gesture is available in message list.

### Actual behavior

No archive icon, no swipe-to-archive gesture for this email account.
(Tested to establish that this is not a Posteo issue. Mails from a posteo.de account can be archived into manual Archive folder in other email apps, AquaMail for instance, or Geary/Mailspring on desktop. Thunderbird on desktop ignores the existing Archive folder and creates its own folders: .../Archive/2022/ etc).

### Logs

--------- beginning of main
12-11 12:45:21.513 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:23.514 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:25.515 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:27.517 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:29.519 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:31.521 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:33.523 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:35.525 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:37.527 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:39.529 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:41.531 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:43.533 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:45.535 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:47.536 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:49.280 17112 28278 I K9StorageEditor: Committing preference changes
12-11 12:45:49.310 17112 28278 I K9StorageEditor: Preferences commit took 29 ms
12-11 12:45:49.537 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:51.539 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:53.542 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:55.148 17112 17135 I MessagingController: Running command 'clearNotifications', seq = 88 (foreground priority)
12-11 12:45:55.150 17112 17135 V NotificationController: Removing some notifications for account a5f41fb5-63c1-442e-8433-9d2c701f800f
12-11 12:45:55.150 17112 17135 I MessagingController:  Command 'clearNotifications' completed
12-11 12:45:55.542 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:57.543 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:45:57.836 17112 17112 D MessageViewFragment: MessageViewFragment displaying message MessageReference(accountUuid=a5f41fb5-63c1-442e-8433-9d2c701f800f, folderId=2, uid=5351)
12-11 12:45:57.838 17112 17112 D MessageLoaderHelper: Creating new local message loader
12-11 12:45:57.921 17112 17112 D MessageLoaderHelper: Creating new decode message loader
12-11 12:45:57.946 17112 17135 I MessagingController: Running command 'markMessageAsOpened', seq = 89 (foreground priority)
12-11 12:45:57.947 17112 17135 V NotificationController: Removing notification for message MessageReference(accountUuid=a5f41fb5-63c1-442e-8433-9d2c701f800f, folderId=2, uid=5351)
12-11 12:45:57.957 17112 17135 I MessagingController:  Command 'markMessageAsOpened' completed
12-11 12:45:58.064 17112 17112 D Utility : External images found
12-11 12:45:59.545 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:00.524 17112 17135 I MessagingController: Running command 'clearNotifications', seq = 90 (foreground priority)
12-11 12:46:00.525 17112 17135 V NotificationController: Removing some notifications for account a5f41fb5-63c1-442e-8433-9d2c701f800f
12-11 12:46:00.526 17112 17135 I MessagingController:  Command 'clearNotifications' completed
12-11 12:46:01.546 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:03.548 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:05.551 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:07.555 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:09.559 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:11.561 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:13.563 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:15.067 17112 17140 D OpenGLRenderer: endAllActiveAnimators on 0x76e0c74f90 (MenuPopupWindow$MenuDropDownListView) with handle 0x7600a46a70
12-11 12:46:15.565 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:17.566 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:19.567 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:21.568 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:23.568 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:25.571 17112 17124 E com.fsck.k9: failed to connect to jdwp control socket: Connection refused
12-11 12:46:26.341 17112 28213 V LogcatLogFileWriter: Writing logcat output to content URI: content://org.nextcloud.documents/document/f77cdbb3f873d1b27d6cb0f212bd6894%2F1399

**Comment by cketti** [comment]
Did you forget to select the newly created folder as archive folder under Settings > [Account] > Folders > Archive folder?

**Comment by emes81** [comment]
No, I did not forget to do this. I was totally unaware it was an option, thanks for the heads up!
