### ISSUE TITLE
Swiping often stays on the same email

### ISSUE THREAD

**Issue by staples1347** [thunderbird/thunderbird-android#6531]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Samsung S10

### Steps to reproduce

Open an email
Attempt to swipe to the next email
Sometimes it swipes to the same email

### Expected behavior

I expect swipe to always progress to the next email

### Actual behavior

Swipe shows the same email

**Comment by cketti** [comment]
Can you record a video of this behavior and attach it here?

**Comment by staples1347** [comment]
Okay, it will probably be a few days before I can do that.

**Comment by staples1347** [comment]
Here is a better way to test:
Create a test folder on an imap server
Send yourself 10 test emails (or maybe 20)
Move those test emails to the test folder
Mark all the test emails as unread
Now open the first test email
Swipe as fast as possible through all the test emails

My version of k9mail sometimes glitches to the same email twice when doing this while doing the "server update" animation at the top.  It doesn't seem to have the problem if all the test emails are read.

**Comment by cketti** [comment]
If it's still an issue with recent beta versions, please open a new issue and don't forget to include a video.

**Comment by staples1347** [comment]
oh okay.  Sorry, I just googled and didn't realise how easy it is to make a video of the screen in Android.  I am now waiting for the play store to give me access a beta version of k9mail.
