### ISSUE TITLE
Messages with 0, 1 or 2 preview lines have the same height

### ISSUE THREAD

**Issue by SebiderSushi** [thunderbird/thunderbird-android#6569]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.501

This issue didn't exist in 6.400. I did not try 6.500 because F-Droid skipped that version.

### Where did you get the app from?

F-Droid

### Android version

LineageOS 15.1 (Android 8.1)

### Device model

Xiaomi Redmi 4X

### Steps to reproduce

1. Go to `General settings` > `Display` > `Message lists`
2. Change the `Preview lines` option to any value out of `0`, `1` or `2`
   Other options are:
   - [X] Show stars
   - [ ] Show correspondent names
   - [X] Correspondent above subject
   - [ ] Show contact pictures
   - [X] Change colour when read
   - [X] Threaded view
3. Check the message height in any folder

### Expected behavior

Lowering the number of preview lines reduces their height to fit more messages on the screen at the same time.

### Actual behavior

Messages on lists are given the same height when the number of preview lines is either `2`, `1` or `0`, leaving vacant layout space if 1 or 0 preview lines are shown. Increasing the height above 2 increases the message height to fit that exact number of preview lines as expected.

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/after-updates-the-list-of-messages-is-no-longer-as-compact-as-before/5993

**Comment by SebiderSushi** [comment]
Thanks for the link. Would it be appropriate to change the bug template so that it prompts to search the forum as well? Because i wasn't aware of the forum at all when i openend this issue.
