### ISSUE TITLE
Cannot send emails out of my Domain

### ISSUE THREAD

**Issue by JoelBHorton** [thunderbird/thunderbird-android#6578]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.501

### Where did you get the app from?

Other

### Android version

13

### Device model

Samsung Galaxy S22 Ultra

### Steps to reproduce

1. Click on Compose
2. Enter Email address of Recepient  (scraven@mariettaga.gov)
3. Entered Subject line as "Test Email Debugging"
4. Entered Message Text as "Test Email Debugging, Please respond if you get this email"

 I made 2 messages to same email address at 7:24PM EDT, and 7:20PM EDT.

I found "scraven@mariettaga.gov on 2 lines in log:
Line  7689: 01-14 19:20:46.723 30842 30879 D SmtpTransport: SMTP >>> RCPT TO:<SCraven@mariettaga.gov>
Line  9310: 01-14 19:24:41.321 30842 30879 D SmtpTransport: SMTP >>> RCPT TO:<SCraven@mariettaga.gov>

Attached Log [file.[](url)](url)

### Expected behavior

I should be able to make and send a message to email addresses out side of my domain.  I have tested with several of my customers, such as schools, city goverments, and manufactuers and all emails are never received by my customers.

I CAN send emails between my devices on my domain (southcomm.net).  I have email addresses for my wife's iPhone 11, iPad 2, Windows 10 Desktop running Thunderbird, and Linux Desktop runing Thunderbird.

### Actual behavior

Since I am the Website and email admin for southcomm.net I looged into my web hosting server "arrvixe".  I log into cPanel and log into my personal email (they use a email client named Horde), and I can see the 2 emails sitting there in the sent folder of Horde with the correct time stamps.

I will attach a jpeg screenshot below:

![CPanel_Horde_Screenshot 2023-01-14](https://user-images.githubusercontent.com/66179674/212504134-1c9078b1-8712-4746-a168-c05b8c5bd1c4.jpg)

So I assume it is getting to the arvixe server, but the email server does not like something about the email?  I have never seen anything like this before.

I am considering deleting and adding back K-9.    I have issues with the setup.   In setup I entered everything correctly, but the "NEXT" button at the bottom of the page was always greyed out.   So I have to enter wrong information intially to get the NEXT button to take it, and modify later to the orginal correct SMPT Outgoing settings.   Maybe somethng is corrupted?

FYI, this is a new Samsung Galaxy S22 Ultra, and I transfered data over from my iPhone XR.  "Hummm?"

### Logs

[Log removed]

**Comment by cketti** [comment]
The log contains the following protocol exchange. Lines prefixed by `S:` is data sent by the server. Lines prefixed by `C:` is data sent by the K-9 Mail.

```text
S: 220-shared101.arvixe.com ESMTP Exim 4.94.2 #2 Sat, 14 Jan 2023 18:24:40 -0600 
S: 220-We do not authorize the use of this system to transport unsolicited, 
S: 220 and/or bulk e-mail.
C: EHLO [127.0.0.1]
S: 250-shared101.arvixe.com Hello [redacted]
S: 250-SIZE 52428800
S: 250-8BITMIME
S: 250-PIPELINING
S: 250-PIPE_CONNECT
S: 250-AUTH PLAIN LOGIN
S: 250 HELP
C: AUTH PLAIN [redacted]
S: 235 [omitted]
C: MAIL FROM:[redacted] BODY=8BITMIME
C: RCPT TO:[redacted]
S: 250 OK
S: 250 Accepted
C: DATA
S: 354 Enter message, ending with "." on a line by itself
C: [data]
C: .
S: 250 OK id=1pGqpF-0038V7-BS
C: QUIT
```

The log shows that the server accepted the message for delivery without any error. Please contact your email provider to find out why the message isn't delivered to the recipient. It might be a problem on their end or a problem with the mail server of the recipient. In any case, it's not a problem with K-9 Mail. From its point of view, everything is working like it should.
