### ISSUE TITLE
Opening message and hitting archive doesn't mark the email as read.

### ISSUE THREAD

**Issue by woj-tek** [thunderbird/thunderbird-android#6581]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

13 / OneUI 5.0

### Device model

Samsung Galaxy A52s 5G

### Steps to reproduce

This happens rarely

1. Open any unread message
2. Hit archive

### Expected behavior

The message should be marked as read and archived.

### Actual behavior

Sometimes (I havent found any pattern yet) some messages are archived but are still in unread state. I think it started with 6.400 version. I noticed it when opening Thunderbird on my computer and noticing that "archive" folder is in bold, indicating that there are unread messages (and I only archived read messages). I'm positive that those messages were archived using mobile/k9-mail. I'm fairly certain I did that when away from home, thus using mobile connection. I think it could be due to either poor network coverage or possibly it could happen when switching from wifi to mobile data.

**Comment by cketti** [comment]
The archive action only moves the message to the archive folder, but doesn't mark it as read. So it's unlikely that archiving the message is part of the problem. It sounds like opening the message sometimes doesn't mark it as read. Can you enable debug logging and export a log the next time this happens? See https://github.com/thundernest/k-9/wiki/LoggingErrors

**Comment by woj-tek** [comment]
Well, it just happened :D Luckily I managed to enable the debugging right before though - is there a way to share the logs privately? I think GitHub doesn't allow "private issues"...

One observation that could be relevant - I think it happens when I open k9-mail from notification (when there are multiple messages thus opening mail view instated message directly).

**Comment by cketti** [comment]
You can send the log to debugging@cketti.de

**Comment by woj-tek** [comment]
Sent :-)

**Comment by cketti** [comment]
It looks like the operations are performed out of order. Somehow the archive operation is executed before the message is marked as read on the server.

**Comment by woj-tek** [comment]
Concurrency issue? Steps are the same: k9mail mail list -> open message (which should mark it as read) -> hit archive button. Possibly there is an issue with rendering/opening activity when opening from notification?

**Comment by woj-tek** [comment]
> It looks like the operations are performed out of order. Somehow the archive operation is executed before the message is marked as read on the server.

OK, _I think_ I know what may be happening - when I'm archiving those messages I'm doing it _*very*_ fast -- tap on the message and even before it finishes the sliding/opening animation hit archive. It seems that "mark as read" is executed when the animation is finished hence I'm able to archive the message before it's being fully opened. 

Though, mark-as-read action should be executed either way against the message, whether it's in the Inbox or in Archive.

One possible solution would be to make the sliding animation way faster (?!)

**Comment by woj-tek** [comment]
I updated to 6.601 and this issue is fixed but I ran into another one which is very similar - opening a message (one in a set of unread messages) and then quickly swiping across the set (without animation fully finishing) yields same result - some of the messages being left unread.

Should I open new issue with it?
