### ISSUE TITLE
The application crashes when viewing emails

### ISSUE THREAD

**Issue by shomov** [thunderbird/thunderbird-android#6584]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.502

### Where did you get the app from?

Google Play

### Android version

12

### Steps to reproduce

1. Click to email
2. Crash!

### Expected behavior

Crash

### Actual behavior

WebView 107.0.5304.105(530410503)(7.0-13.0)

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/10429563/k9mail-logs.txt)

**Comment by cketti** [comment]
This is a crash in the WebView component on your device, not K-9 Mail. Make sure to update to the latest WebView version available for your device. If that doesn't fix the issue, report this as a bug to the creator of the Android version on your device.
