### ISSUE TITLE
GMail+OAuth 2.0 not available for custom gmail domain names

### ISSUE THREAD

**Issue by akanok** [thunderbird/thunderbird-android#6585]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.501

### Where did you get the app from?

FDroid

### Android version

12

### Steps to reproduce

1. `Settings` --> `Add account`
2. Enter GMail email adress with custom domain
3. `Next` --> `POP3`
4. There is no way to use OAuth 2.0 here, only avaible Autentication metods are `Encrypted` or ` Normal` password. 

Also if, at sept 3, I choose `Maunual Setup` --> `POP3` ant then set *pop3 server* to `pop3.gmail.com`

### Expected behavior

You should be able to use OAuth 2.0 with custom GMail domains.

### Actual behavior

There is no way to use OAuth 2.0 with GMail emails that have domain different form `@gmail.com`.

**Comment by cketti** [comment]
K-9 Mail doesn't support OAuth 2.0 with POP3.

To learn how to add a Google Workspace account, see https://forum.k9mail.app/t/how-do-i-add-a-google-workspace-account/5087
