### ISSUE TITLE
.life (dot)life domains not accepted

### ISSUE THREAD

**Issue by gpl-life** [thunderbird/thunderbird-android#659]
Hello,
Just tried to add my email using your add account function and putting in for example test@gpl.life and I can not continue. The next and Manual entry buttons are greyed out.  If i put .com as the email I can continue.  Can you add .life so I can add my email accounts to K-9.

**Comment by ocdtrekkie** [comment]
In a more general sense, it's no longer appropriate to limit gTLDs to a specific length or certain ones.

**Comment by gpl-life** [comment]
True because if the user keys the wrong email address it will not be accepted so your right, no longer appropriate.

**Comment by jomo** [comment]
In a more general sense, it's never appropriate to limit email addresses to anything (e.g. TLDs) as long as there's a valid user- & host separated by an @-sign ;)

**Comment by jkdf2** [comment]
Why is this marked as an active issue? I checkout a commit as far back as April 30th and it seems to be working fine. 

![](mtp://[usb:007,002]/Internal%20storage/Pictures/Screenshots/Screenshot_2015-06-19-18-10-47.png)

**Comment by gpl-life** [comment]
Sorry but its not true.  When i key the same information you show above - my 'NEXT' button is greyed out. This is the issue. If i change it to .com the next is highlighted to continue. Here is the screenshot

![Uploading Screenshot_2015-06-21-08-50-58.png…]()

**Comment by gpl-life** [comment]
Not sure how to show the screenshot. But this shows that unlike your image I can not click continue. If i change the domain to a .com I can continue. This has been the issue.
![screenshot_2015-06-21-08-50-58](https://cloud.githubusercontent.com/assets/12604608/8269927/70f2124c-17f4-11e5-826a-58cb462a3d55.png)

**Comment by gpl-life** [comment]
Found that if I copy/paste the values then it wont let me pass. But if I manually key both the values, then i can continue.
