### ISSUE TITLE
An email can stay stuck in the "sending box" indefinitely

### ISSUE THREAD

**Issue by Massedil** [thunderbird/thunderbird-android#6601]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.503

### Where did you get the app from?

F-Droid

### Android version

LineageOS 18.1 / Android 11

### Device model

Samsung Galaxy S5

### Steps to reproduce

- Create a new email
- Sent the email when there is a network problem : the phone says there is network, but in fact no (may be DNS problem)
- try a certain number of time to send the email by refreshing the inbox folder

After some times there is a notification saying "Retries exceeded" : 
![Screenshot_20230123-183919_Courriel_K-9_Mail](https://user-images.githubusercontent.com/20357783/214111974-c305437e-43f9-4815-8833-9eab7a540ff1.png)

After some times, internet is now working fine.

### Expected behavior

I can send the email when refreshing the inbox.

### Actual behavior

The email is now stuck in the "sending box" without any way to send it again.

Each time I try to refresh the inbox the notification "Retries exceeded" comes back, but I can't do anything to correct the problem.

If I go to the "sending box" and try to manual do `3 dot menu` > `Sent all emails`, it is not working either.

**Comment by cketti** [comment]
This is covered by #4602.
