### ISSUE TITLE
Certain sender names display as "Unknown Sender"

### ISSUE THREAD

**Issue by Player701** [thunderbird/thunderbird-android#6602]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

Google Play

### Android version

Android 12

### Steps to reproduce

Import the following message to your inbox: [repro.zip](https://github.com/thundernest/k-9/files/10487614/repro.zip) (extract eml from zip)

### Expected behavior

In this particular case, K-9 Mail should display the sender as "Josh @ FreeDNS"

### Actual behavior

Instead, K-9 Mail displays the sender as "Unknown Sender":

![image](https://user-images.githubusercontent.com/9046118/214244206-1a5fc158-3009-4022-be79-33c4960e6ca8.png)

Note: Other clients such as Roundcube seem to display the sender name correctly:

![image](https://user-images.githubusercontent.com/9046118/214245126-b3897835-c2f1-448c-ab33-e0ef78ea02f5.png)

**Comment by cketti** [comment]
The message contains the following header line:

```
From: Josh @ FreeDNS <dnsadmin@afraid.org>
```

The display name is not properly encoded. A valid encoding would be this:

```
From: "Josh @ FreeDNS" <dnsadmin@afraid.org>
```

You might want to contact FreeDNS and let them know they're sending out broken emails.

**Comment by Player701** [comment]
Thanks, I will do that.
