### ISSUE TITLE
Missing folders with IMAP

### ISSUE THREAD

**Issue by josborne-tactable** [thunderbird/thunderbird-android#6611]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.503

### Where did you get the app from?

F-Droid

### Android version

LineageOS 20

### Device model

Xperia 5 ii

### Steps to reproduce

add a new gmail account to k9 mail.

### Expected behavior

All folders should be available to sync with the K9 client.

### Actual behavior

I've been using this app as long as I can remember and have never had this problem before.  I've recently flashed my phone with Lineage 20 (android 13), and reinstalled k9 from fdroid.  App is looking great by the way!

When I add my google account, I am unable to see anything outside of my inbox; I have multiple labels set up in gmail and they are all present, but I cannot see the "bin" or the "sent" folders at all, I've tried everything, including enabling all folders under manage folders.  No matter what I do, I cannot get those additional labels or folders to appear.

When I send a mail, it goes through fine, and it does actually appear in my sent items on gmail, I just cannot figure out a way to have them appear in the K9 app.

I've tried using the older authentication method (google app password) and that did not help either.

Any idea what is going on here?

Thanks.

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/thundernest/k-9/wiki/LoggingErrors
