### ISSUE TITLE
Content not displaying

### ISSUE THREAD

**Issue by MartinHusemann** [thunderbird/thunderbird-android#6614]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

Google Play

### Android version

8.0.0

### Device model

Samsung Galaxy A3 (2017)

### Steps to reproduce

A mail with 8bit encoding but "unusual" charset like this:

```
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-8859-1
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
User-Agent: Mutt/1.7.2 (2016-11-26)
X-UIDL: h#;"!EF3"!ag1!!N;0"!
Status: RO
Content-Length: 81
```

does not display anything at all in the mail reading view. You get Subject, from and to at the top and an empty lower part of the screen.

When selecting reply the full text shows up properly (quoted with "> " prefix) in the editor. I can probably send test mails easily to arbitrary addresses if you need a hands on example. My locale, mutt and mail server configuration seem to cooperate to generate this type of encoding easily as soon as I use german umlauts in the text.

### Expected behavior

Plain text view in the lower part of the message view, as if this were plain-text/ascii encoding.

### Actual behavior

No text displayed.
The start of the text displays properly in the message list.

**Comment by cketti** [comment]
Can you attach a complete message failing to display? Feel free to redact sensitive content. But please make sure the redacted message still fails to display properly.

**Comment by MartinHusemann** [comment]
Trying:
[example.txt](https://github.com/thundernest/k-9/files/10529940/example.txt)

This is how it looks like for me:
![Screenshot_20230129-150005_K-9 Mail](https://user-images.githubusercontent.com/13184974/215332224-d63689a3-4939-45b3-887c-95aa47c6cc43.jpg)
![Screenshot_20230129-150012_K-9 Mail](https://user-images.githubusercontent.com/13184974/215332226-faff5076-333a-4b3d-b69c-6cb0bea3800d.jpg)

**Comment by cketti** [comment]
Are you sure this is a problem with messages using `charset=iso-8859-1`? The preview is decoded properly. The message displays fine in my tests. Maybe there is a problem with the WebView component (that is used to display the message contents) on your device? Does the message display correctly if you remove the non-ASCII characters?

**Comment by MartinHusemann** [comment]
I'm puzzled - indeed nothing seems to be displaying any more (independent of the charset) - maybe the WebView component got updated and breaks things?

It has been updated last week and I now have 109.0.5414.118

**Comment by cketti** [comment]
Unfortunately, this happens from time to time. Usually bugs like these in Android System WebView are fixed relatively fast. Until then I believe your only option is to uninstall WebView updates to return to the version that shipped with your device.

**Comment by MartinHusemann** [comment]
Indeed, it went away after some more updates and now works just fine
