### ISSUE TITLE
[EPIC] Material You/Material 3 Design

### ISSUE THREAD

**Issue by seniorm0ment** [thunderbird/thunderbird-android#6617]
Would be very nice to see the app with a more modern feel.
My suggestion is to bring it up to par with Material You design.

Also in the actual screen that displays the mail you are reading ,that screen feels very inconsistent and outdated to the other menus already. Especially if viewed as plaintext only.

**Comment by Wave6677** [comment]
A material you coat of paint over K-9 Mail would be lovely, especially with the Thunderbird integration coming up

**Comment by MXC48** [comment]
yes, this will allow for better integration into the Android system

**Comment by joshuajeschek** [comment]
This would be so great!

**Comment by rezazarchi** [comment]
It should be noted that Material 3 is dependent on migration of the entire UI to Jetpack Compose, which constitutes a substantial amount of work. It seems that this constitutes a long-term plan for K-9, although it is acknowledged that there are some tasks involving rewriting some parts of the application (#6974, #6975).

**Comment by cketti** [comment]
What makes you think the entire UI needs to be migrated to Jetpack Compose?

**Comment by rezazarchi** [comment]
> What makes you think the entire UI needs to be migrated to Jetpack Compose?

I recently came across information in Google documents indicating that Material 3 can be applied with Jetpack Compose using the MaterialTheme but didn't find any official information about Material 3 in the XML way. some parameters like dynamic color scheme and other modern Material You UI components are available in compose library.

**Comment by W1zardK1ng** [comment]
waiting for the Material You version of k9 mail.

**Comment by Cwpute** [comment]
I'd like to say i'm not interested in a Material You design for this app, as Material You uses more space on the screen for the same amount of information.
For users like me who have a phone with a not so big screen, this is not good news.

**Comment by flexagoon** [comment]
@Cwpute k9 has a compact view, and nothing in M3 says you can't have a compact view in a M3 app

**Comment by tamirat67** [comment]
Hello dear certification issue not possible to me, it say warning ⚠️
invalid certificate ohhh

**Comment by cketti** [comment]
> Hello dear certification issue not possible to me, it say warning ⚠️ invalid certificate ohhh

@tamirat67: Please use the [forum](https://forum.k9mail.app/) for support requests.

**Comment by S0ulf3re** [comment]
I would also love to see material you as well

**Comment by rezazarchi** [comment]
> I would also love to see material you as well

Material Design 3 and Material You are the same, and it is in the development plan as you can see onBoarding and log in pages rewrited and redesigned in the recent changes.

**Comment by gmankab** [comment]
> I'd like to say i'm not interested in a Material You design for this app, as Material You uses more space on the screen for the same amount of information. For users like me who have a phone with a not so big screen, this is not good news.

you can change scale in settings -> display -> display size and text

**Comment by seniorm0ment** [comment]
I feel like it'd make most sense to take a look at how Google does Gmail first. Very similar based off the pictures.
https://play.google.com/store/apps/details?id=com.google.android.gm

But either way yes, agreed. It makes things feel a lot more consistent with Android 14

**Comment by A1X5H04** [comment]
I would like to contribute to designs, I would like to create updated screens

**Comment by Henry-Hiles** [comment]
Well, material 3 seems to be here, and I'm assuming material you is coming soon!

**Comment by Henry-Hiles** [comment]
Only thing right now is message view is still black-and-white

**Comment by TwoF1nger** [comment]
> k9 has a compact view, and nothing in M3 says you can't have a compact view in a M3 app

The compact view affects only the message list, which is not M3.

The UI elements that were *actually* changed for M3 do waste space. For example, I now have to scroll in the sidebar in order to see some of the folders. My phone is not small at all.

Some other gripes I have with the recent UI changes:

- the "mark read" button doesn't change based on the read status of the message (I think it did before, but I might be wrong)
- the envelope in Android status bar is now hollow and is harder to recognize as such. The old icon was filled.
- almost half of my screen height is taken by the headers of the message. (Not too bad, as it is scrollable. In Jira, half of my screen is *always* taken by UI chrome I never use.)

**Comment by ThatOneCalculator** [comment]
None of what you complained about has anything to do with MD3 or MY.

**Comment by wmontwe** [comment]
Status upate: The Material 3 theme in 6.9xx versions is currently in an alpha state. Our priority is to establish Material 3 support, followed by improvements to the overall theme. At the moment, we're still using a mix of Material 1 and 2 components and styles throughout the app, which needs to be addressed first. Material You is blocked by until we finish the Material 3 integration.

**Comment by Feuerswut** [comment]
Is the background of messages changeable?

Currently it's either white on black or black on white.
not white on material background, like in other apps.

**Comment by wmontwe** [comment]
The background of messages is currently not changeable, but we updated the colorscheme for a little improvement. We plan to do another iteration especially on the dark theme contrast.

**Comment by wmontwe** [comment]
We have implemented Material 3 for Thunderbird for Android and K-9 Mail. I'm closing this issue and would like to follow up on Material You in a separate epic: #8340. Please file separate issues for Material 3 related findings.
