### ISSUE TITLE
Slow startup and slow opening e-mail from notification

### ISSUE THREAD

**Issue by imagoiq** [thunderbird/thunderbird-android#6620]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Samsung S10 (SM-G973F/DS)

### When opening a message from a notification
1. Open a notification for a new e-mail
2. Wait until the message is displayed (take > 5 seconds)

### When opening the app:
1. Close all apps
2. Open k-9 mail
3. Wait until messages are displayed (see screenscast)

### What I tried so far:
For the issue about notification:
* Use an empty e-mail (except of the title) as in the screencast
* Send an e-mail from a folder or receive from a folder (same result)

In general:
* Delete all app data and reinstall completely (by using the import of e-mail configuration)
* Disabled energy saving mode

### Note
I have 4 accounts in my k9-mail (1: ~2000 e-mails, 2: ~2531 e-mails, 3: ~10 e-mails, 4: ~10 e-mails).

The issue is not new, it's like that since months (I cannot recall, but perhaps since the redesign), but I'm seriously getting annoyed by that. I thought that it will be fixed at some point.

### Expected behavior

Show almost immediately the messages.

### Actual behavior

https://user-images.githubusercontent.com/12294151/216140107-7e30ec35-c3f4-41e2-a310-a7c6735d6738.mp4

https://user-images.githubusercontent.com/12294151/216134932-2293af61-b453-4986-8770-c95e726d1609.mp4

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/10560800/k9mail-logs.txt)

**Comment by cketti** [comment]
Do you have *Settings→ General settings → Display → Show contact names* enabled? If so, does disabling it make a difference?
