### ISSUE TITLE
Can not log into gmail (with OAuth 2)

### ISSUE THREAD

**Issue by dumblob** [thunderbird/thunderbird-android#6626]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

7.1.1 (original from Samsung)

### Steps to reproduce

1. Open "Settings"
2. Select "Add account"
3. Fill in "youraccount@gmail.com"
4. Select "Next"
5. Select "Sign in with Google"
6. Select "Allow" (as answer to whether to allow K-9 access to Google account)
7. Observe the "loading bar" to fully load and then switch back to K-9 intent.
8. nothing happens - K-9 only shows the text "To use this email accountt with K-9 Mail, you need to sign in and grant the app access to your emails." with a "reload" icon underneath.

Same thing happens when in step (4) instead of "Next" I choose "Manual Setup" and then select "IMAP" and then change Authentication to "OAuth 2.0" in which case I again successfully log into my gmail account but in the step (8) there nothing happens (the text says "Authenticating..." instead of the long sentence above, but that is the only difference).

### Expected behavior

Step (8) should not exist and instead K-9 shall log me in as it does with non-Google email accounts.

### Actual behavior

K-9 stays in step (8) indefinitely no matter what I do. Pressing the "reload" icon has zero effect (even when combined with long waiting for minutes, repeated pressing of the "reload" icon etc.) - the log in for m does not show up any more.

I can only go back (to previous intent) using the Android's "Back" button action. Then I can start the steps as described above with identical results (i.e. log in form shows up again but after return to K-9, nothing happens).

Because I use Fennec as my default web browser I initially suspected this to be similar to https://github.com/thundernest/k-9/issues/670 . But after closer examination, the opened webview intent is from "Samsung Internet". When I try logging into web interface of gmail through Samsung Internet, it works flawlessly.

So for some reason, K-9 seems to not receive the login tokens or whatever is necessary to proceed.

Any hints?

### Logs

Prior to step (1) I have turned both logging options in K-9 on and after the last step from above I have exported the logs to a file (and then turned logging off). The file has 0 bytes. So I am not including it.

**Comment by cketti** [comment]
Can you record a video of the process and add it to this issue?

**Comment by Efreak** [comment]
[Maybe related?](https://github.com/M66B/FairEmail/blob/master/FAQ.md#user-content-faq6) Try using an app-specific password instead.

**Comment by dumblob** [comment]
@cketti will try once I get access to another smartphone or recording device. Btw. is there any way to get some detailed logs or debugging info from the login process?

@efreak it seems app-specific password can be used only when 2-factor authentication is enabled. But I do not have (and never had) it enabled (I never - consciously - submitted my phone number to Google).

I actually want to switch from FairEmail to K-9 (Thunderbird). But one of my accounts is a Google account and thus this is a show-stopper for now.

**Comment by xNS5** [comment]
Have you tried with the Google Play Store version?

**Comment by dumblob** [comment]
@xNS5 great idea! I exported K-9 settings, uninstalled the F-Droid variant of K-9, installed the Google Play variant, killed FairMail, ran K-9, imported settings, and finally tried to add the Google account.

Unfortunately the observable behavior is identical.

I will leave the Google variant on my phone for now until I get across a good camera/phone to record how it looks like.

**Comment by cketti** [comment]
No additional information provided.

**Comment by dumblob** [comment]
I plan to provide the info - it might take months though. If that is no problem, feel free to reopen.
