### ISSUE TITLE
Microsoft Outlook accounts had bad outbound defaults for manual setup

### ISSUE THREAD

**Issue by Ampflower** [thunderbird/thunderbird-android#6627]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

Pixel Experience 12 (SP2A.220405.003) (Stock but old ROM)

### Device model

Pixel 4

### Steps to reproduce

With setting up a Microsoft account, optionally has 2FA enabled as I did:

 - Enter in your login email
 - Tap manual setup (required if you're using 2FA, OAuth seems to not give K-9 the ability to authenticate correctly when the account has it enabled.)
 - Enter in details for inbound then continue
 - Check details of outbound. Note that it uses SSL/TTS by default, which seems to be unsupported by Microsoft.

### Expected behavior

Ideally to be defaulting to `STARTTLS` for `@outlook.com`, `@hotmail.*`, `@live.com` and `@msn.com`.

### Actual behavior

K-9 is instead defaulting to `SSL/TTS`, which the Microsoft servers seem to not support for outbound. The client hangs indefinitely as it tries to connect to the server and seems to not get a response.

*I know this is rather minor, but it could be a slight improvement to UX if there can be known good defaults for such things. Ideally, the OAuth setup would be sufficient for allowing quick setup even with 2FA enabled on the accounts.*

**Comment by cketti** [comment]
Improving account setup is on the roadmap. But even now, automatic setup for these domains should work fine. The fact that authentication for the outgoing server currently doesn't work, is a bug on Microsoft's side. See https://forum.k9mail.app/t/outlook-com-mail-settings/6154/6

I don't see us adding support for auto-detecting server settings when the user has explicitly selected manual setup.

**Comment by Ampflower** [comment]
Fair. It was more necessarily pointing out that the SSL/TLS route is generally broken for Microsoft's stuff, not about generally being unable to send.

Tho, it does seem that the OAuth2 route likely does need a bugfix for accounts with 2FA enabled.
Should I create a new issue for that, or would that also fall under the same forum post you linked?

**Comment by LoneFenris** [comment]
Possibly related to the account setup issue? 

https://blog.thunderbird.net/2023/01/important-message-for-microsoft-office-365-enterprise-users/
