### ISSUE TITLE
drawer switch account inconsistent behavior

### ISSUE THREAD

**Issue by rms-joe** [thunderbird/thunderbird-android#6646]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.506

### Where did you get the app from?

F-Droid

### Android version

13

### Device model

pixel 4a

### Steps to reproduce

1. have a setup with two Accounts
2. open drawer
3. switch between accounts (dropdown or via icons don't matter)
4. towards one account the drawer always stays open
5. towards the other account drawer always closes

### Expected behavior

drawer remains open when switching accounts (i guess),
at least consistent

### Actual behavior

inconsistent

**Comment by cketti** [comment]
The behavior depends on whether or not you've selected a folder under *Settings → [Account] → Folders → Auto-expand folder*.

**Comment by rms-joe** [comment]
thanks for clarification and the hint.
i'm not 100% sure but i think this behavior changed from 6.4.
i think both behaviors have their pros and cons.
on step less if u switch into your pref folder immediately, vs a quick overview of all your folders after switching on the cost of extra step.
guess no right or wrong here.
anyhow why i wrote all that...what i want to say is, the behavior feels weird (personal opinion, and if u know what's going on, it's better, hahaha).

thanks again!
