### ISSUE TITLE
Asks to save unchanged draft

### ISSUE THREAD

**Issue by opk12** [thunderbird/thunderbird-android#6651]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

7.1

### Steps to reproduce

1. Click the pencil to make a draft.
2. Add a recipient and a body.
3. Press Back and tap `Save as draft`.
4. Open this draft.
5. Do not change anything, just press Back.
6. You are asked to save or discard changes.
7. If you did **not** set a recipient in step 2 (only set a message body), then step 6 has the expected behavior, i.e. you are **not** asked to save or discard changes.

### Expected behavior

The app should notice that the message was unchanged and do not ask to save or discard changes.

### Actual behavior

The app asks to save or discard changes.

**Comment by cketti** [comment]
I was able to reproduce the behavior using the provided steps just fine.
