### ISSUE TITLE
Most mail received lists "Initial Identity" as one of the recipients

### ISSUE THREAD

**Issue by justdave** [thunderbird/thunderbird-android#6669]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.507

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Samsung Galaxy S10+

### Steps to reproduce

1. Receive an email that includes you in the recipients
2. view the email

### Expected behavior

The header of the email should indicate that it's addressed to me

### Actual behavior

The header lists "Initial Identtiy" as the recipeint instead.

This is confusing as to what this even means to most people. Since I actually have multiple identies defnied, I realize it's trying to tell me which identity matches the recipient of the email, but a lot of people would probably never figure that out and just be confused.

I suggest putting my name there first (either the globally configured one for that account or the one specific to that identity if it has one set), and then put the identity name in parens after it.

**Comment by cketti** [comment]
The name of the identity is only displayed if there's more than one. If there's only one, "me" is displayed instead.

**Comment by njeyaakili** [comment]
additionally, it will sometimes fail to display any recipient name/identity - just showing "to". in the cases where i'm seeing this there is an identity defined for the recipient address in question, it's just not (technically) defined under the account/mailbox that the message is viewed in -- it's listed as being under some other of the accounts i have configured.

despite what gmail may do, i would like to see the actual email address that the message is addressed to, whether i have an identity set up for the address in question or not.

K9 6.506

**Comment by cketti** [comment]
> additionally, it will sometimes fail to display any recipient name/email address/identity - just showing "to"

@njeyaakili: Please create a new issue for this an try to provide instructions on how to reproduce the issue.

> i would like to see the actual email address that the message is addressed to, whether i have an identity set up for the address in question or not.

You can configure the app to always show email addresses instead of the display name. We're not planning to add yet another setting to allow different configuration for sender and recipient addresses. You can now see the full display name and email address if you open the message details screen.
