### ISSUE TITLE
IllegalStateException no outbox_state entry for message

### ISSUE THREAD

**Issue by ntlspck** [thunderbird/thunderbird-android#6680]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.507

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

OnePlus Nord

### Steps to reproduce

Unfortunately I don't know, I just updated K-9 from 6.506 to 6.507 and then suddenly I received the message:
`Nachrichten konnten nicht gesendet werden
IllegalStateException: No outbox_state entry for message with id xyz`

I have three different mailboxes configured, so I do not know to which account this message refers to. I also saw that the message id the errer refers to is changing. So there seems to be a general issue I am not able to resolve.

I found two older issues regarding this message, but wasn't able to find a resolution. 

I used K-9 for many years now and never had any issues, unfortunately I do not know how to track the issue down, since I dont know which account (of the configured 3 mailboxes) this is refering to. 
I am able to send and receive emails via K-9 with all three configured accounts. 

I just can't get rid of this IllegalStateException messages. 

I seems I am no longer able to delete a message from my mailbox. It disappears from the Inbox for a short time and then reappears again in the Inbox.

The issue seems to start as I started to switch into other folders like: 'send' and 'trash' and refreshed the folder and also scrolling down and click the 'bis zu 50 weitere abrufen' button.

Any help would be much appreciated.
Thanks in advance.

### Expected behavior

Deleted messages should be moved to 'trash' folder and should not reappear in Inbox

### Actual behavior

Deleted messages won't be moved to trash

**Comment by ntlspck** [comment]
I just saw that in the Folder settings for one account there is a total mess for the folder assignments, I copied this out of the current backup:
```
        <value key="autoExpandFolderName">Entwürfe</value>
        <value key="archiveFolderName">Papierkorb</value>
        <value key="draftsFolderName">Gesendet</value>
        <value key="sentFolderName">PSN</value>
        <value key="spamFolderName">Rechnung</value>
        <value key="trashFolderName">Urlaub</value>
```

I never changed the assignment by myself , but I saw that Archive is assigned to Papierkorb (trash) and Drafts to Gesendet(Sent) etc.

I corrected this with hope that this will fix the issue, but unfortunately the issue is also happening with correct folder assignments.

**Comment by cketti** [comment]
There's a good chance there was a data corruption somewhere. The safest and probably fastest way to get rid of this issue is to uninstall the app, then reinstall and import settings.

**Comment by ntlspck** [comment]
Thank you very much for the fast response. Your recommendation fixed the issue. I just found an old backup from 2022 where the folder assignment were correct:

```
        <value key="autoExpandFolderName">INBOX</value>
        <value key="archiveFolderName">Archiv</value>
        <value key="draftsFolderName">Entwürfe</value>
        <value key="sentFolderName">Gesendet</value>
        <value key="spamFolderName">Spam</value>
        <value key="trashFolderName">Papierkorb</value>
```

So when did you think could the data corruption happend? Could this be at the time updating from 6.506 to 6.507?
Is there a chance to break things link that?

**Comment by cketti** [comment]
I don't think it's a bug in the app. We'd get more reports if that was the case. Plus, we haven't changed that part of the code in a while.

Random memory and/or storage corruption is something that happens regularly given the huge number of mobile devices and the different environmental conditions they are operated in. Given that there's a near-infinite number of broken states, it's incredibly hard to identify what exactly went wrong and then fix the data (and possibly code) on the affected device to get to a non-broken state. Uninstalling, then reinstalling the app usually does the trick. Trying to find out what went wrong is usually futile.

**Comment by FMorschel** [comment]
Just as a note: Galaxy S23 Ultra - Android 14, version 6.714 (probably updated last night automatically). Same error, I'll reinstall the app.
