### ISSUE TITLE
Since 6.500: Message list without Contact Pictures not dense anymore

### ISSUE THREAD

**Issue by m1027** [thunderbird/thunderbird-android#6683]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.507

### Where did you get the app from?

F-Droid

### Android version

13

### Steps to reproduce

1. Settings / General settings / Display / Preview lines: 0
2. Settings / General settings / Display / Show contact pictures: off
3. Settings / General settings / Display / Show stars: off.

Now watch your inbox: The displayed messages are shown dense (good).

Then change the settings so that stars are *enabled* (see 3. above).

Now watch your inbox again: The displayed messages each use too much height, as if there was a blank line between (bad).

This behaviour is new since version 6.500. In 6.4xx the displayed lines keep beeing dense even if the stars are enabled.

### Expected behavior

Keep inbox view dense even if stars are enabled (and no contact pictures and preview lines: 0).

### Actual behavior

Since version 6.500, when enabling stars (and no contact pictures and preview lines: 0) the inbox message view consumes too much space per email so that you can display approx. only 7-8 messages per screen, while with version 6.4xx there were 10-11 displayed without scrolling.

**Comment by cketti** [comment]
We have plans to change the appearance of the message list a little bit. However, the space the star requires won't change significantly. It is a clickable element and as such needs a minimum size so it can be hit comfortably using a finger.

Optimizing the message list for a very dense view is currently not a priority. If you want list items to be as small as possible, you'll have to disable stars.

**Comment by m1027** [comment]
Thanks for you friendly feedback.

Let me add:

Agreed, the star needs room to be clickable via fingers. However, as this was possible in the more compact style of the earlier 6.4xx version, so I believe this should be okay for 6.5xx, too.

And maybe we can think of two UI directions: One group of users who want a dense view, who set preview lines to 0, no contact picutres etc, and others who want it all.

Would be nice to get the dense message list back. If not, sight, close this. Thanks

**Comment by m1027** [comment]
In version 6.509 things seem to have improved here:

In 6.4xx: I had approx 10-11 stared mails listed on a single screen.
In 6.50x: Decreased to 7-8 lines.
In 6.509: Increased to 8-9 lines.

Additionally, the space above and below each line semms to be more evenly applied.

All in all I find this WFM.

Thanks for awesome k9.
