### ISSUE TITLE
Sent messages are not copied to sent folder

### ISSUE THREAD

**Issue by skylarmt** [thunderbird/thunderbird-android#6685]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

12 (LineageOS 19)

### Steps to reproduce

1. Send an email
2. Email sends
3. Email does not appear in sent folder, despite "Upload sent messages" being checked
4. Email does not appear in sent folder in other clients either

### Expected behavior

Sent emails should be copied to Sent folder.

### Actual behavior

Messages sent normally but were not copied to sent folder.

### Logs

[Logs when sending an email](https://github.com/thundernest/k-9/files/10773100/k9mail-logs.txt)

In particular, this line stands out to me:  
`02-17 21:40:54.735 30814 30836 I MessagingController: Not uploading sent message; deleting local message`

**Comment by skylarmt** [comment]
I erased all of K-9's app data and set up my email account from scratch and it didn't solve the problem.

**Comment by cketti** [comment]
Make sure there's a folder selected as Sent folder under *Settings → [Account] → Folders → Sent folder*?

By default K-9 Mail uses the settings provided by the IMAP server. It looks like you're using Dovecot. See https://doc.dovecot.org/configuration_manual/namespace/#core_setting-namespace/mailbox/special_use
