### ISSUE TITLE
Authentication Error SMTP Server M365 Accounts

### ISSUE THREAD

**Issue by Maetts** [thunderbird/thunderbird-android#6687]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.508

### Where did you get the app from?

Google Play

### Android version

10

### Device model

Huawei P30 Pro NE

### Steps to reproduce

1. Setup M365 Mail-Account
2. Send an E-Mail from this Account 

### Expected behavior

1. E-Mail will be sent

### Actual behavior

1. Error Message Unsuccessful Authentication
2. Mail is not sent and there is a Request for Update of the Server Settings
3. Issue on all M365 Accounts even after Reinstallation of the App

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/outlook-com-mail-settings/6154
