### ISSUE TITLE
Wrong mime type to open .csv file with onlyoffice app

### ISSUE THREAD

**Issue by ASLLR** [thunderbird/thunderbird-android#6705]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

None

### Android version

12

### Device model

Fairphone 4

### Steps to reproduce

1. Use Onlyoffice android app as défault text editor of the mobile
2. receive a mail with a .csv attached
3. Try to open it directly in k9 mail (not save the file)
4. Have the message unsupported format

### Expected behavior

Open the .csv doc like the other format.

### Actual behavior

Error message when we open a .csv. That work's when we save the file on the phone and reopen after. 

### Logs

Onlyoffice has debug this and say this "It is related to the fact that K9 sends a non-standard mime-type."

**Comment by cketti** [comment]
When opening an attachment for viewing, K-9 Mail passes the MIME type from the email to Android. If that doesn't work, chances are the sender of the email used the wrong MIME type.
When the file is saved first, this MIME type is often ignored by the system.
