### ISSUE TITLE
K9 is failing to build over at F-droid 

### ISSUE THREAD

**Issue by uniquePWD** [thunderbird/thunderbird-android#6718]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.509

### Where did you get the app from?

F-Droid

### Android version

13

### Steps to reproduce

1. Go to https://gitlab.com/fdroid/fdroiddata/-/pipelines/793212750/failures
2. Look at the failure

### Expected behavior

It should build perfectly

### Actual behavior

It's failed and F-droid is stuck on an older version.

**Comment by cketti** [comment]
To me it looks like there was an error building the F-Droid index. I don't think this has anything to do with building K-9 Mail.

From the build log:
```
OSError: [Errno 28] No space left on device
```

**Comment by cketti** [comment]
The app build was successful: https://monitor.f-droid.org/builds/log/com.fsck.k9/35009#site-footer

It looks like the updated APKs haven't been deployed yet: https://monitor.f-droid.org/builds/deploy
