### ISSUE TITLE
URL links open in K-9 instead of browser

### ISSUE THREAD

**Issue by quikeagle** [thunderbird/thunderbird-android#673]
Not sure what is going on, but just lately, URL links in emails want to open directly in K-9 instead of opening a browser - unless I long-press the link and choose "open link".  What happened?  I cleared all default actions for K-9 without anything changing.  K-9 5.005 on Lollipop 5.0.2 LG G2

**Comment by quikeagle** [comment]
Also on my 5.1.1 Nexus tablet...

**Comment by squilter** [comment]
Same here. I hope this is a bug, not a feature.

**Comment by jkingdon** [comment]
I'm seeing this with K-9 5.005 on a Nexus 6 running Android 5.1.1.

**Comment by cketti** [comment]
Please check out v5.006 and report back if this fixes the issue for you: https://github.com/k9mail/k-9/releases/tag/5.006

**Comment by quikeagle** [comment]
that fixed it for me!

**Comment by jkingdon** [comment]
5.006 fixes it for me too. Thanks.
