### ISSUE TITLE
K9 doesn't copy a new sent mail in the sent folder using IMAP 

### ISSUE THREAD

**Issue by joebleau7** [thunderbird/thunderbird-android#6779]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

latest installed yesterday

### Where did you get the app from?

Other

### Android version

12

### Device model

Samsung Flip

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Logs

.

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/upload-sent-messages-to-sent-folder-after-sending-not-working-with-imap/5248

Please use the [forum](https://forum.k9mail.app/) for support requests.
