### ISSUE TITLE
Correspondent above subject does not work anymore

### ISSUE THREAD

**Issue by delphi1702** [thunderbird/thunderbird-android#6782]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.510

### Where did you get the app from?

Google Play

### Android version

10

### Steps to reproduce

General Settings --> Display --> setting "Correspondent above subject" does not work anymore.
Since an update (beta version) a few weeks ago the subject is always displayed above the correspondent.

### Expected behavior

The correspondent should be above the subject when I use this setting.

### Actual behavior

General Settings --> Display --> setting "Correspondent above subject" does not work anymore.
Since an update (beta version) a few weeks ago the subject is always displayed above the correspondent.

**Comment by cketti** [comment]
Works for me. Can you please export your general settings and attach the file here?

**Comment by delphi1702** [comment]
O.k., I think I misunderstood this setting.
I thought that this setting is also for the behaviour inside the e-mail window.
Is there in the current version any possibility to display the correspondent above the subject also in the e-mail window?
In previous versions I think this was the default behaviour (and for me also the better one).

![Screenshot_20230325-172730](https://user-images.githubusercontent.com/128755152/227730916-90f1e1e0-e44d-478e-bb4d-c3918ac421d3.png)

**Comment by cketti** [comment]
No, there never was such an option. In the message view, the subject was always displayed at the top.

We're not planning to add a setting to change the order. It would require a separate layout that also wouldn't work well when we add a conversation view where all messages of a conversation are displayed in one screen.

FWIW: I think the default of using different font sizes greatly helps to make this screen look better and more easily glanceable.
