### ISSUE TITLE
Dark Theme Inconsistency between main page and mails

### ISSUE THREAD

**Issue by louim-lbs** [thunderbird/thunderbird-android#6785]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6-400

### Where did you get the app from?

Google Play

### Android version

13

### Steps to reproduce

Chose dark theme. 

### Expected behavior

The same background colour everywhere. 

### Actual behavior

Main background is more grey, while mails view is dark black (Amoled). However, in the settings both settings are the same "dark mode".

**Comment by fereshtehamiri** [comment]
Hello louim-lbs
We have thoroughly tested and replicated the bug scenario, and it has occurred for us on the following device and software configuration,
device model: Samsung A32
Android Version: 13
K9 App Version: 6.702

**Comment by mhf1998** [comment]
> 
Hello @cketti 
My question is, which one of the colors should be the background on these two pages (or other pages)?
Dark black (Amoled) ?  or Grey?

**Comment by louim-lbs** [comment]
I'm not @cketti, but personally I would definitely prefer Dark Black (Amoled) 😇

**Comment by cketti** [comment]
The goal is to use the theme's regular background color.

What needs to be done:
- Remove the theme attribute `messageViewBackgroundColor` and all code associated with it.
- Change `DisplayHtml.cssStyleTheme()` and `MessageWebView.configure()` to set the WebView's background color to the theme background color, not black.

**Comment by mhf1998** [comment]
> The goal is to use the theme's regular background color.
> 
> What needs to be done:
> 
> * Remove the theme attribute `messageViewBackgroundColor` and all code associated with it.
> * Change `DisplayHtml.cssStyleTheme()` and `MessageWebView.configure()` to set the WebView's background color to the theme background color, not black.

@cketti.
Hello Dear 
Thank you.

I am fixing the bug.
Regarding the second change you mentioned, please tell me what attribute you mean by "theme background color" exactly?

**Comment by cketti** [comment]
> Regarding the second change you mentioned, please tell me what attribute you mean by "theme background color" exactly?

`android:windowBackground`
