### ISSUE TITLE
splash screen is blurry

### ISSUE THREAD

**Issue by ericJrdn** [thunderbird/thunderbird-android#6801]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.51

### Where did you get the app from?

F-Droid

### Android version

android 13 personal build of lineageos 20

### Device model

redmi note 7

### Steps to reproduce

1 kill any running k9 instance.
2 launch k9. On android 13, there is some kind of splash screen during launch of all apps: a white screen with the app icon, centered

### Expected behavior

The icon should be rendered correctly

### Actual behavior

For k9 (and not for any other app on the phone) this icon is blurry. This is not comfortable. Seems that a small resolution icon is interpolated to be at the requested size.
![Screenshot_20230308-185251_Courriel K-9 Mail](https://user-images.githubusercontent.com/64037055/229356658-a7b06251-b32b-4bac-96b7-75e2343b1d08.png)

**Comment by mhf1998** [comment]
Hello @cketti .
We have thoroughly tested and replicated the bug scenario, and it has occurred for us on the following device and software configuration:

Phone Model: Samsung A32
Android Version: 13
K9 App Version: 6.702
App Source: F-Droid

**Comment by mikailyusuf** [comment]
@mhf1998 I would love to fix this issue, Do you have a launch icon with High-quality that I can use. 
Thanks

**Comment by mhf1998** [comment]
> @mhf1998 I would love to fix this issue, Do you have a launch icon with High-quality that I can use. Thanks

Hello Mikail.
Sorry, I don't have this file.
But @cketti can help you

**Comment by mikailyusuf** [comment]
@cketti can you help with the icon
