### ISSUE TITLE
"Invalid sasl argument" error connecting to Zoho IMAP server 

### ISSUE THREAD

**Issue by mfschumann** [thunderbird/thunderbird-android#6814]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.511

### Where did you get the app from?

Other

### Android version

13

### Device model

Pixel 7

### Steps to reproduce

On a fresh install I try to add my Zoho mail IMAP account in the setup wizard:
- server imappro.zoho.eu
- port 993
- SSL
- authentication type plain text password

I am using a username and password that works fine with other IMAP clients.

### Expected behavior

K-9 mail should connect to the IMAP server.

### Actual behavior

Setup does not complete and I get this error:

Command: AUTHENTICATE PLAIN; response: #2# [BAD, [CLIENTBUG], syntax: Invalid sasl Argument

I get the same error in the latest stable 6.400 and in the latest preview 6.511 releases.

**Comment by cketti** [comment]
Can you enable *Settings → General settings → Debugging → Log sensitive information* and record a [debug log](https://github.com/thundernest/k-9/wiki/LoggingErrors )?

Please note that this will include your password in the log. It's necessary to see what authentication command exactly is sent to the server. **Before posting the log, please change your password on this server.**
Alternatively, if any password generates this error message, use a dummy password when trying to set up the account while recording a debug log.

If this is your first account, you won't have access to the settings screen yet. In that case ignore the errors during account setup and continue. Afterwards, enable debug logging, change the *Log sensitive information* setting, then go to *Settings → [Account] → Fetching mail → Incoming server* and press the *Next* button. This will check the server settings (again) and should lead to the same error.
