### ISSUE TITLE
Inconsistent recipient names when composing a message

### ISSUE THREAD

**Issue by jkufner** [thunderbird/thunderbird-android#6816]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

13

### Steps to reproduce

1. Have a contact with the nickname different from the name.
2. Create a new message in K9
3. Start typing in "To"
4. If you type the nick name and use the autocomplete/sugestion, the e-mail is in the form of `"Nickname" <email@example.com>`
5. If you type the name and use the autocomplete/sugestion, the e-mail is in the form of `"Firstname Lastname" <email@example.com>`

### Expected behavior

No matter how I find the contact, the recipient address is always in the same form `"Firstname Lastname" <email@example.com>`.

### Actual behavior

Depending on which field of the contact was matched the name changes.

### Logs

_Not relevant_

**Comment by mhf1998** [comment]
Hello @cketti .
We have thoroughly tested and replicated the bug scenario, and it has occurred for us on the following device and software configuration:

Phone Model: Samsung A6
Android Version: 10
K9 App Version: 6.702
App Source: F-Droid

**Comment by cketti** [comment]
This behavior is intentional. I guess people can disagree on whether it's expected behavior. I, too, lean towards making the change and always use the display name.
