### ISSUE TITLE
Upgrade to 6.6 removes home screen widget

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#6826]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.6

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Samsung S20+

### Steps to reproduce

1. Ensure you have pre-6.6 installed whatever the last version was distributed in the play store.
2. Add a K-9 widget, I use the first one to give number of unread message badge.
3. Update to 6.6
4. Observe that widget was removed.

### Expected behavior

Upgrade should not remove home screen widget.  If it's not possible to fix (I assume it's an Android thing) then you should mention it in the changelog.

### Actual behavior

K-9 widget was removed from my home screen when the app was upgraded to 6.6.  As I have my home screen locked this means it's a handful steps to restore how I want to the app.

**Comment by man1001** [comment]
I have the same problem on my Galaxy S10+ since the update to K9 Mail 6.6. The Android version of my phone is 12.

**Comment by cketti** [comment]
Can you please check if K-9 Mail 6.601 fixes this issue for you: https://github.com/thundernest/k-9/releases/tag/6.601

**Comment by man1001** [comment]
K-9 Mail 6.601 fixed it for me.

**Comment by cketti** [comment]
Thanks for checking :+1:

**Comment by ILPlais** [comment]
I've got a Fairphone 4 with Android 12 (FP4.SP25.B.058.20230318), and the widget on the home screen is gone with the release 6.601. Someone else have the same trouble?

**Comment by cketti** [comment]
The widget might have been removed when the app was updated to 6.600. You should be able to add it again using K-9 Mail 6.601.

**Comment by cketti** [comment]
It's working fine on my Fairphone 4. Try rebooting. If that doesn't work try uninstalling, then reinstalling the app.
