### ISSUE TITLE
Auto-complete email addresses not working

### ISSUE THREAD

**Issue by gun4qmm7h** [thunderbird/thunderbird-android#6839]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.601

### Where did you get the app from?

F-Droid

### Android version

Grapheneos android 13

### Device model

Pixel 6

### Steps to reproduce

Compose an email
Enter half of the email you want to use

### Expected behavior

It should auto completed
Example
"Company" -> "CompanyName@Email.com"

### Actual behavior

It doesnt auto complete

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
