### ISSUE TITLE
Notifications issue

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#6842]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.601

### Where did you get the app from?

F-Droid

### Android version

12 SP1A.210812.016

### Device model

MIUI 13

### Steps to reproduce

No steps, just don't receive notification until I open the app or restart the phone

### Expected behavior

To get notifications when receiving a mail

### Actual behavior

Don't get notifications.
I followed don't kill my app tips but still don't receive notification, this also happened with other apps from fdroid like feeder.
The only apps from fdroid that works fine is that depends on ntfy
Could you give me any tips that can help or add support for ntfy soon?

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
