### ISSUE TITLE
Valid e-mail recipient specification rejected (special characters)

### ISSUE THREAD

**Issue by xhajt03** [thunderbird/thunderbird-android#6843]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.600

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

QX1050 (FX Technology Pro1x)

### Steps to reproduce

1) Either copy e-mail address together with the sender name containing accented characters from a received e-mail (using the new functionality for displaying sender details) and paste it into the recipient address of a newly composed message, or type such an address anew - as an example, use something like: `"Tomáš Marný" <tomas@example.com>` (starting with the quote mark and finishing with the greater than sign).

2) Press "Tab" key, or change to a different field.

3) An exclamation mark appears next to the provided address. Clicking on the exclamation mark results in displaying "Special characters are not supported at the moment" (actually, I see a localized version of this message, thus the real English version of this message may be slightly different).

The point is - the recipient specification written this way is perfectly valid (even copied by K9 from a received message), but K9 refuses it.

### Expected behavior

No exclamation mark is displayed, provided address is used for the "To" header of the composed message and sent to the address between the "less than" and "greater than" signs after user sends the message.

### Actual behavior

The recipient specification is refused as described above.

### Logs

[k9mail-logs_230421.txt](https://github.com/thundernest/k-9/files/11299477/k9mail-logs_230421.txt)

**Comment by mhf1998** [comment]
> ### Checklist
> * [x]  I have used the search function to see if someone else has already submitted the same bug report.
> * [x]  I will describe the problem with as much detail as possible.
> 
> ### App version
> 6.600
> 
> ### Where did you get the app from?
> F-Droid
> 
> ### Android version
> 11
> 
> ### Device model
> QX1050 (FX Technology Pro1x)
> 
> ### Steps to reproduce
> 1. Either copy e-mail address together with the sender name containing accented characters from a received e-mail (using the new functionality for displaying sender details) and paste it into the recipient address of a newly composed message, or type such an address anew - as an example, use something like: `"Tomáš Marný" <tomas@example.com>` (starting with the quote mark and finishing with the greater than sign).
> 2. Press "Tab" key, or change to a different field.
> 3. An exclamation mark appears next to the provided address. Clicking on the exclamation mark results in displaying "Special characters are not supported at the moment" (actually, I see a localized version of this message, thus the real English version of this message may be slightly different).
> 
> The point is - the recipient specification written this way is perfectly valid (even copied by K9 from a received message), but K9 refuses it.
> 
> ### Expected behavior
> No exclamation mark is displayed, provided address is used for the "To" header of the composed message and sent to the address between the "less than" and "greater than" signs after user sends the message.
> 
> ### Actual behavior
> The recipient specification is refused as described above.
> 
> ### Logs
> [k9mail-logs_230421.txt](https://github.com/thundernest/k-9/files/11299477/k9mail-logs_230421.txt)

Hello @cketti .
We have thoroughly tested and replicated the bug scenario, and it has occurred for us on the following device and software configuration:

    Phone Model: Samsung A6
    Android Version: 10
    K9 App Version: 6.702
    App Source: F-Droid


![5](https://github.com/thundernest/k-9/assets/34542204/e45edc2d-339b-4792-b428-dadac0483cdf)

**Comment by mhf1998** [comment]
Hello @cketti 
My attempt to fix this problem led me to this part of the code below in function **defaultObject**, class **RecipientSelectView**:

```
 if (!CharsetUtil.isASCII(completionText)) {
            setError(getContext().getString(R.string.recipient_error_non_ascii));
            return null;
        }
```
In merge request #1535, which was for Issue #1328, this code was added to solve that issue.
Of course, it is mentioned there that: "This doesn't fix #1328, but it improves error handling a bit."


In light of these things, what approach do you suggest I take to fix this bug?

**Comment by xhajt03** [comment]
> Hello @cketti My attempt to fix this problem led me to this part of the code below in function **defaultObject**, class **RecipientSelectView**:
> ```
>  if (!CharsetUtil.isASCII(completionText)) {
>             setError(getContext().getString(R.string.recipient_error_non_ascii));
>             return null;
>         }
> ```
> In merge request #1535, which was for Issue #1328, this code was added to solve that issue. Of course, it is mentioned there that: "This doesn't fix #1328, but it improves error handling a bit."
> 
> In light of these things, what approach do you suggest I take to fix this bug?

As far as I can see, there are two issues:

1) The check added in MR #1535 ignores the difference between the real address (provided between the "<" and ">" characters) and the display name included in quotes preceding the real address. Only the real address should be used within the SMTP control communication; the display name is just provided in the message header and the SMTP server shouldn't have any issues with it. This part seems to be a regression compared to situation before MR #1535.

2) The original issue described in issue #2633 related to international domain names (IDN) and international e-mail addresses which requires special handling of such characters within the SMTP communication (e.g. conversion of these addresses to UTF-8 among others).

Solving the first one should be rather simple and can be done independently from the second one. Solving the second one probably requires much more effort and possibly might depend on support within underlying components used in K-9.

**Comment by cketti** [comment]
Right now we don't have a dedicated parser for a user-entered address list that could be used to make the distinction between the name and the email address. The parser that is currently used doesn't support (unencoded) special characters anywhere in the input. That's why the error message was added.

**Comment by xhajt03** [comment]
Thanks for your response. I may be wrong, but it seemed to me that the 
original issue (preceding the patch implementing the error message) was 
related to a special character within the domain of the e-mail address. 
I don't know whether there would be some problem if the special 
character appeared in the display name part, but I wouldn't think so - 
the message from the mail server administrator mentioned a particular 
extension of a SMTP protocol, but I don't think that this extension 
would be necessary for handling special characters in the display name 
part of the address. Am I wrong?

Tomas

**Comment by xhajt03** [comment]
Thank you, I'll test your fix as soon as the change becomes available in the F-Droid repository. :-)
