### ISSUE TITLE
No mails fetched after every update until I open the app

### ISSUE THREAD

**Issue by King555a** [thunderbird/thunderbird-android#6844]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.601

### Where did you get the app from?

Google Play

### Android version

9.0

### Device model

Samsung Galaxy S8+

### Steps to reproduce

Update K-9 Mail to any newer version (only tested automatically in the background), the last time was today on my phone. This bug occured every time in the past, at least since the major UI change some time ago, but maybe also before.

### Expected behavior

Normal operation, fetching mails and notify about them as before.

### Actual behavior

The app does not fetch any new mails and shows no notifications. I have to open the app once and then the app works again. Maybe it has something to do with showing the release notes after every update (which I activated).

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
