### ISSUE TITLE
Sent folder is no longer detected automatically

### ISSUE THREAD

**Issue by Standard8** [thunderbird/thunderbird-android#6847]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.601

### Where did you get the app from?

Google Play

### Android version

12

### Steps to reproduce

1. Add my IMAP account to K-9 email
2. Send an email to another person.

### Expected behavior

Save the email in the sent folder.

### Actual behavior

The email was not saved, no warnings were given.

For sending messages, I have "Upload sent messages" checked, but I have since found that under Folders -> Sent Folder it says "Automatic (none)".

The bug due to the lack of warning is covered in the issue #6276.

However, this bug is due to the lack of detection.

At sometime in the past (maybe before the major update last year), the sent folder was detected correctly. This stopped happening at some stage.

If I set a specific folder rather than using automatic detection, then email is correctly saved.

In Thunderbird my special folders for my IMAP server are all listed as sub-folders of the inbox. Whereas something like gmail they are all listed as top-level folders. Maybe the issue is that K-9 is not detecting sub-folders?

### Logs

I'm happy to try and provide logs, but I will need advice as to when the automatic folder detection takes place, and how to trigger it.

**Comment by ByteHamster** [comment]
The detection does not work because your email provider does not support it. Ask your email provider to support the IMAP SpecialUse extension. Closing this since the warning is already covered in https://github.com/thundernest/k-9/issues/6276.

**Comment by Standard8** [comment]
> The detection does not work because your email provider does not support it. Ask your email provider to support the IMAP SpecialUse extension. Closing this since the warning is already covered in #6276.

@ByteHamster I appreciate the desire to adhere to standards and I will ask our provider.

However it is frustrating that Thunderbird supports this server fine and has done for years, and I'm pretty sure K-9 used to as well.

Doubly frustrating is that as I mentioned in #6276 it is only being treated as an enhancement, and not the data loss bug that it actually is.
