### ISSUE TITLE
Translation issue for french for name of default folders

### ISSUE THREAD

**Issue by MINBL** [thunderbird/thunderbird-android#6848]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.601

### Where did you get the app from?

F-Droid

### Android version

/e/OS 1.10 Android R

### Device model

Sansumg A5 2017 (a5y17lte)

### Steps to reproduce

1. Open the app and click on the 3 stacked lines at the top left
2. the list of default folders appears: inbox, outbox, drafts, sent, ...
3. In french, the folders Draft, Sent, Trash, are not translated. 
We should have: Draft = Brouillon, Sent = Envoyés, Trash = Corbeille

### Expected behavior

Get the right translation for the folders Draft (Brouillons), Sent (Envoyés) & Trash (Corbeille)

### Actual behavior

![image](https://user-images.githubusercontent.com/122700577/233869776-6788eb7c-7adc-4aab-8631-b1dba0391e58.png)

**Comment by ByteHamster** [comment]
K-9 does not translate folder names on purpose. See #6799
