### ISSUE TITLE
Translation issue for size unit for french

### ISSUE THREAD

**Issue by MINBL** [thunderbird/thunderbird-android#6849]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.601

### Where did you get the app from?

F-Droid

### Android version

/e/OS 1.10 Android R

### Device model

Sansumg A5 2017 (a5y17lte)

### Steps to reproduce

1. Go to "Settings > Account > recover mails > Recover e-mails unti"
2. You can see a list of different sizes and the unit used is Kio or Mio

### Expected behavior

In french or even in other languages, I would expect Ko instead of Kio and Mo instead of Mio.

### Actual behavior

![image](https://user-images.githubusercontent.com/122700577/233870223-b3d54ede-b13a-433e-856f-82b0ee133f2c.png)

**Comment by ByteHamster** [comment]
There is a difference between KB and KiB. A KiB is 1024 bytes, while a KB is 1000 bytes.

**Comment by Iey4iej3** [comment]
According to https://www.lemagit.fr/definition/Mebioctet-Mio-miB, `Mio`, an acronym of mébioctet, is the correct translation of `MiB` in English.
