### ISSUE TITLE
App crashes, when an email, that hasn't been opened previously, is opened.

### ISSUE THREAD

**Issue by duanin2** [thunderbird/thunderbird-android#6851]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.601

### Where did you get the app from?

F-Droid

### Android version

13

### Device model

vivo Y33s

### Steps to reproduce

1. Click on an e-mail, that hasn't been opened yet, either through the widget, or through the app.
2. Get a crash

### Expected behavior

App opens the e-mail normally, even though, it hasn't been opened yet.

### Actual behavior

App crashes, when an e-mail, that hasn't been opened previously is opened.

**Comment by dusan-till** [comment]
I am sorry. but whatever method I try to get the debug log, it's just an empty file, so I don't think it would help wiťh resolving these issues anyways.

**Comment by cketti** [comment]
The app doesn't crash for all users when opening messages. So we need more information to be able to reproduce the bug. Without this, there's nothing we can do.

Feel free to open a new issue once you can provide more information.
