### ISSUE TITLE
Make sure all server settings discovery mechanism are GDPR-compliant

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#6872]
This mostly means not sending the email address to autoconfig servers without the user's permission.

**Comment by williamdes** [comment]
And I would say, if possible let the user say not to ask autoconfig from Mozilla database.
That would leak the IP and more personal informations.
Fallbacking on the the standard domain autoconfig methods (if setup by the provider).

**Comment by cketti** [comment]
For now we've configured the app to never send the email address to any autoconfig server.

https://github.com/thunderbird/thunderbird-android/blob/6a47453465d3415282c58c264ea7d8bb3169cba0/feature/autodiscovery/service/src/main/kotlin/app/k9mail/autodiscovery/service/RealAutoDiscoveryService.kt#L22

In the future we might want to add a mechanism so the server can request the email address and the client will prompt the user to check if it's okay to send the email address to the server in a second request.

> And I would say, if possible let the user say not to ask autoconfig from Mozilla database.

We've not added a setting to opt out of the ISPDB fallback. That's clearly a very niche setting for very privacy-sensitive expert users. Instead of doing that, we could probably add a way to skip looking up server settings and drop the user into the manual setup flow instead. Such a feature might also be useful for people who know from experience that autoconfig doesn't work for them.
For now this can be accomplished by putting the device in airplane mode until the "configuration not found" message is displayed.

> That would leak the IP and more personal informations.

It would only "leak" the IP address because there's no way to establish a connection without it. The only other privacy-relevant piece of data that is transmitted is the email domain. However, the domain is not considered personal information.
