### ISSUE TITLE
Yahoo IMAP servers are wrong

### ISSUE THREAD

**Issue by chipechop** [thunderbird/thunderbird-android#6879]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.601

### Where did you get the app from?

None

### Android version

12

### Steps to reproduce

1. create a Yahoo IMAP account, using the wizard.
2. You'll see that the wizard will use wrong servers.

The right servers, are (https://help.yahoo.com/kb/SLN4075.html):
Incoming Mail (IMAP) Server
Server - imap.mail.yahoo.com
Port - 993
Requires SSL - Yes
Outgoing Mail (SMTP) Server
Server - smtp.mail.yahoo.com
Port - 465 or 587
Requires SSL - Yes
Requires authentication - Yes
Your login info
Email address - Your full email address (name@domain.com)
Password - Generate App Password
Requires authentication - Yes

While K-9 uses instead the wrong imap.yahoo.com and smtp.yahoo.com

### Expected behavior

That K-9 didn't fail to autoconfigure YAHOO MAIL servers.

### Actual behavior

K-9 fails to autoconfigure YAHOO MAIL servers.

**Comment by cketti** [comment]
K-9 Mail uses `imap.mail.yahoo.com` and `smtp.mail.yahoo.com` for Yahoo. However, it currently only knows about the following Yahoo domains:
- yahoo.com
- yahoo.de
- ymail.com
- rocketmail.com

In all other cases automatic setup doesn't work and you'll be asked to manually provide the server settings. To save time the app will populate the *IMAP server* field with `imap.<domain part of the email address>`. This is a suggestion that works well for many small email providers. It is **not** the result of an autoconfiguration mechanism.

This will no longer be a problem once #865 is implemented. We're working on that right now.
