### ISSUE TITLE
Switching apps destroys draft rather than saving it

### ISSUE THREAD

**Issue by Meteor0id** [thunderbird/thunderbird-android#6887]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.701

### Where did you get the app from?

Google Play

### Android version

Android 10, not a custom ROM

### Device model

Motorola Moto G7 Plus

### Steps to reproduce

1. start writing an email
2. switch apps
3. switch back to k9

### Expected behavior

k9 either shows the draft still when switched back to k9, or it has saved the draft to drafts, or both.

### Actual behavior

k9 does not show the draft when brought back on the screen, nor has it been saved to drafts. The log shows the app is crashing.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/11423091/k9mail-logs.txt)

**Comment by Meteor0id** [comment]
It might be a duplicate of https://github.com/thundernest/k-9/issues/6863 . Maybe this is already fixed in a newer version?

**Comment by cketti** [comment]
Yes. Please update to at least K-9 Mail 6.702.
