### ISSUE TITLE
fdroid is presently Does Not install

### ISSUE THREAD

**Issue by aplatypus** [thunderbird/thunderbird-android#6892]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

all

### Where did you get the app from?

None

### Android version

13

### Device model

galaxy a73 5g

### Steps to reproduce

Go yo fdroid
Click on k9
Press install

### Expected behavior

Instapp the app

### Actual behavior

Not installed

**Comment by cketti** [comment]
You might want to ask for help in the [F-Droid forum](https://forum.f-droid.org/).
