### ISSUE TITLE
Multiple notification for the same mail

### ISSUE THREAD

**Issue by katastrophe92** [thunderbird/thunderbird-android#6900]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

F-Droid

### Android version

Android 13

### Device model

Galaxy M12

### Steps to reproduce

Activate K-9 Mail notifications
Wait for new mails

### Expected behavior

If it notified me that I have a new mail, next time is searching for new mails should not notify me for the same mail I didn't read the last time it searched
Get only 1 notification for each mail

### Actual behavior

It notified me multiple times for the same mail if I didn't read the new mail last time it notified.

### Logs

![signal-2023-05-08-204329_002](https://github.com/thundernest/k-9/assets/103950507/6e927c33-b5b9-40b3-827b-7cc36d14b574)

**Comment by cketti** [comment]
This is most likely a configuration issue. Please check the forum, e.g. https://forum.k9mail.app/t/duplicate-notifications-being-generated-for-some-messages/2543

**Comment by katastrophe92** [comment]
Hey @cketti . Thanks for you're answer. I looked into what you sent me but I do not know/understand what 1st and 2st Class Mails are. Many people are confused also and couldn't find a explanation about it. Could you explain what are those? Ty!
