### ISSUE TITLE
Overlapping menu texts when changing accounts

### ISSUE THREAD

**Issue by ZeldosID** [thunderbird/thunderbird-android#6905]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

F-Droid

### Android version

8.1

### Steps to reproduce

This is not really a bug, but an ugly UI appearance and a cosmetic matter

1. If there are more then 3 mail accounts and
2. you have to switch the accounts via the left menu bar (not with the 3 icons on the top),
3. then the manu text (mail account1, mail account2 etc. and inpox, outbox, drafts etc.) is overlapping in an ugly way.
This behavior has been occurring for several versions.

### Expected behavior

see above

### Actual behavior

see above

**Comment by cketti** [comment]
Can you provide a screenshot?

**Comment by ZeldosID** [comment]
Sorry, it appears only for a short moment (less then a second), but clear visible.
There are two textparts overlapping for a short moment e.g. **Name Mailaccount** etc. of the mail account list and **Inbox** etc. of the mail account itself.

**Comment by cketti** [comment]
This should no longer be an issue with the new drawer.
