### ISSUE TITLE
No possibility to open links from email

### ISSUE THREAD

**Issue by Sommergoldhaehnchen** [thunderbird/thunderbird-android#6910]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.702

### Where did you get the app from?

F-Droid

### Android version

OxygenOS 13.1

### Device model

OnePlus 8 Pro

### Steps to reproduce

1. Open an email with links within
2. Click on that link
3. Browser opens without opening the link

2. Long press on that link
3. The link is not shown for copy and paste

### Expected behavior

Either opening the links in browser or show a possibility to copy the links

### Actual behavior

Neither links were opened in browser nor copyable from context menu.

**Comment by cketti** [comment]
In general opening links with K-9 Mail 6.702 works just fine. It's possible that links in an email are broken or that the WebView component on your device has a bug.

Can you provide the source of the message you're having trouble with?

**Comment by Sommergoldhaehnchen** [comment]
Earlier it was indeed possible to open links.
The source is ***@***.***
The links guide you to the products.

Am 22. Mai 2023 14:39:05 MESZ schrieb cketti ***@***.***>:

**Comment by cketti** [comment]
You have to use GitHub's web interface to attach a file.

**Comment by Sommergoldhaehnchen** [comment]
Sorry, but I don't know what to attach.
The email contains personal data such as price and address. Furthermore the hyperlinks in that emails are hidden behind text. Long-pressing that text either shows the web link to the picture (href-picture) or it shows nothing as nothing happens when clicking on the href-text.
I don't know what to show at the screenshot.

Kind regards
Andre

Am 22. Mai 2023 15:20:35 MESZ schrieb cketti ***@***.***>:

**Comment by Sommergoldhaehnchen** [comment]
Issue solved. There was actually a malformed email. In newer emails from the same sender hyperlinks are working.
Sorry for inconvenience.

**Comment by Sommergoldhaehnchen** [comment]
Issue solved. There was actually a malformed email. In newer emails from the same sender hyperlinks are working.
Sorry for inconvenience
