### ISSUE TITLE
"Sign in with Google" Button text not readable in dark mode

### ISSUE THREAD

**Issue by sivasubramaniamv** [thunderbird/thunderbird-android#6924]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

Google Play

### Android version

Android 11

### Device model

Realme 3 Pro

### Steps to reproduce

1. Enable system-wide dark mode
2. Do a fresh install and open the app
3. Click "Next" on Welcome Screen
4. Enter a Gmail address and click "Next"
5. Notice that the button text ("Sign in with Google") is not readable

### Expected behavior

The button text should be in a dark color

### Actual behavior

The button text color is white

### Logs

![oauth_sign_in_button](https://github.com/thundernest/k-9/assets/112970189/b7b87857-048a-4bf2-ad79-60fc5a3c3169)

**Comment by siva-subramaniam-v** [comment]
@cketti I fixed this bug locally in a new branch, pushed it to my fork on GitHub, and went on to create a pull request.

- **Does not contain merge commits. Rebase instead.**

This was mentioned on the pull request page. I looked up what **rebase** is in Git and learned that it is a mechanism to combine changes from one branch into another, a potentially better alternative to merging.

But I'm confused about what I should do on my side as merging/rebasing is concerned with maintainers and not contributors. 

Can you help me?

**Comment by siva-subramaniam-v** [comment]
Thank you :)
