### ISSUE TITLE
k-9mail的网络连接需要等待

### ISSUE THREAD

**Issue by biange200** [thunderbird/thunderbird-android#6950]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.704

### Where did you get the app from?

F-Droid

### Android version

originos3

### Device model

vivo iqooz7

### Steps to reproduce

1.我的k-9mail每天都是一天到晚挂后台运行 
2.在晚上睡觉的时候，我会把手机上的网络都关闭了
3.第二天早上起来我会打开手机数据流量连接上网

### Expected behavior

我以为k-9mail会和其他软件一样，会立刻连接上网络 

### Actual behavior

但实际上其他软件都连接上了 ，k-9mail等待2-5分钟都没连接成功
之后才连接上
![Screenshot_20230602_062957](https://github.com/thundernest/k-9/assets/37582806/bacde3ed-6158-41f9-83c0-3e469e6aeda2)
![Screenshot_20230602_062748](https://github.com/thundernest/k-9/assets/37582806/a94369c6-e30a-4414-ae74-55b87f63ec32)

**Comment by cketti** [comment]
Please use English to report bugs. Use a translation tool if necessary.

K-9 Mail uses an Android system component to schedule periodic syncs. If that doesn't work as expected, please contact your device vendor or creator of your ROM.

**Comment by biange200** [comment]
> Please use English to report bugs. Use a translation tool if necessary.
> 
> K-9 Mail uses an Android system component to schedule periodic syncs. If that doesn't work as expected, please contact your device vendor or creator of your ROM.


I suspect it's a k9 version issue as I can connect to the network immediately with 6.602 when I turn on data traffic
After upgrading to version 6.704 it takes a while
