### ISSUE TITLE
Message temporarily unread after download

### ISSUE THREAD

**Issue by patricktokeeffe** [thunderbird/thunderbird-android#697]
After pressing 'Download complete message' to retrieve a read message, that message will be rendered as unread until the next sync/refresh. Seen on 5.006.

**Comment by Trogel** [comment]
I can still reproduce this bug with a fresh build from the head. I just had to disable "Mark as read when opened" in the account settings and then manually mark the message as read in the message view, before clicking "Download complete message". See issue #2475 for more information. Pull request #2808 seems to fix this bug.

**Comment by cketti** [comment]
Fixed by #2808
