### ISSUE TITLE
Improve Splash Screen

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#6998]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.706

### Problem you are trying to solve

This issue is useless since Splash Screens usually display app icons in an animated/static form. I am just creating this issue to keep in mind that this has to be implemented before the rebranding.
All the suggestions are completely my opinion based on what I think is beautiful and useful.

### Suggested solution

I would suggest to implement different ( I mean the background colours) splash screens that switch based on the selected OS theme(dark/light).
Also the New Thunderbird logo seems like it would be perfect for an animated Splash Screen.
Also make sure to not keep some kind of circular background around the icon rather just keep the icon in front of the background and with some animation.

**Comment by comradekingu** [comment]
Possibly a botted account, but some before shots and mockups of proposals would do nicely for those playing at home.

**Comment by pudup** [comment]
+1 for this
Light theme client has a black splash screen
This isn't true for K9
