### ISSUE TITLE
Cannot find Notification sound byte to play

### ISSUE THREAD

**Issue by antcdp** [thunderbird/thunderbird-android#7002]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.706

### Where did you get the app from?

Google Play

### Android version

9

### Device model

HTC U11 plus

### Steps to reproduce

Send a test emmail and wait for the email to arrive and so be notified
I get an error saying unable to play the notification sound as cannot find the file.
Yet, I gio back to apply the sound, which works at that point and is on the fone!

### Expected behavior

a sound should be played to alert me to fact new emails have arrived

### Actual behavior

got the error notification on the fone screen (will attempt to screenshot next time and add)

### Logs

tried to use adb to get the logs but adb does not even see my device!!!!

**Comment by antcdp** [comment]
![Screenshot_20230619-130706~2](https://github.com/thundernest/k-9/assets/64377148/5437783e-d865-4354-b41b-2314d77981ba)
pic of the error!

**Comment by antcdp** [comment]
![Screenshot_20230619-204318~2](https://github.com/thundernest/k-9/assets/64377148/d8261bb1-4de0-4642-93ba-a9da32e9ab3b)

**Comment by cketti** [comment]
This is most likely a bug in the Android version on your device. To work around it, try to avoid changing the following settings inside K-9 Mail:
- *Settings → [Account] → Notifications → New mail ringtone*
- *Settings → [Account] → Notifications → Vibration*
- *Settings → [Account] → Notifications → Notification light*

If you do change any of them, go to the system screen to configure notifications directly afterwards and select the notification sound again (you might have to switch to a different one, then back to the one you actually want).

**Comment by antcdp** [comment]
hi @cketti 
Thanks for the usggestions - I havd tried these but seems to not make any difference. Also, the Status Bar Notification does not wkrk either, I have used AquaMail for a long time and it always worked.
I beta test TB, have for years, and been waiting for an Android version of TB, been chasing Wayne Mery about it, and found out last week on the cummunity call this development is on beta. 
Not sure its an Android bug, some reason K-9 knows it has a sound byte set but cannot find it, even though the "setting" report in the Notification Log says none selected, yet the Settings pane shows it is. Maybe there is an issue with the folder setting and the sounbd does not get moved to a specific folder for k-9 to use it

**Comment by cketti** [comment]
What happens is that K-9 Mail is trying to create a notification for a new message, but the system is returning a `SecurityException`. K-9 Mail is then creating a different notification letting you know that it failed to create a new message notification. Because the most likely reason for the error is a problem with accessing the notification sound, this second notification is posted to a notification group without a notification sound configured. The information you gathered is about the second notification, not the one that couldn't be created.

To get more information about the error, enable [debug logging](https://github.com/thundernest/k-9/wiki/LoggingErrors), export the log then search for "Failed to create a notification for a new message".

**Comment by antcdp** [comment]
report says cannot acces folder, so have copid the file to the notifications folder and see if that helps

**Comment by antcdp** [comment]
that did not makje any difference, log still reports that no sound or vibration set, and visibility Private!

Here is the log report
06-20 13:52:32.394 15736 15758 E NotificationHelper: Failed to create a notification for a new message
06-20 13:52:32.394 15736 15758 E NotificationHelper: java.lang.SecurityException: UID 10190 does not have permission to content://media/external/audio/media/1076 [user 0]
06-20 13:52:32.394 15736 15758 E NotificationHelper: 	at android.os.Parcel.createException(Parcel.java:1954)
06-20 13:52:32.394 15736 15758 E NotificationHelper: 	at android.os.Parcel.readException(Parcel.java:1922)
06-20 13:52:32.394 15736 15758 E NotificationHelper: 	at android.os.Parcel.readException(Parcel.java:1872)

In the end no notification seems to work, no lights, vibration or sound. I have aquamail runnning and that does all these fine

**Comment by cketti** [comment]
Have you tried first disabling the notification sound and then selecting a notification sound in this screen? 

![](https://user-images.githubusercontent.com/64377148/246826558-94f1e31d-41e4-4127-8151-d7a154ca5fa1.JPEG)

Make sure to **not** change any of the previously mentioned notification settings inside K-9 Mail afterwards.

**Comment by antcdp** [comment]
the setting above are within k9 for each email account, whoch is named at the top. So I have dset all the sounds in each account on the noticiation main screen to default and then, as above, the actual sound for each under this sub section and will see what happens

**Comment by antcdp** [comment]
I followed your approach, set the accounts new mail ring to default, and vibrate, then in same account used the Notification Catagories-Messages to set up sound (as per the graphic above, I dont get the error anymore, but no sound or vibrate or led flash

**Comment by antcdp** [comment]
I note that as much as not getting the sound or vibrate, what started to work was the notification on lock or general and each account has a bar for new emails, which is cool

Though now I have a bigger concern - firstly folders on my accounts started to show only ONE email (another bug) and now the Unified which says has 26 emails, is not showing any - its empty in the view!!!!

**Comment by antcdp** [comment]
I do appreciate that we are beta development mode here, so comments/feedback here are made to help understand some nuances!

Rather than carry this bug on further, as sort of resolved - in that the Notifications situ is a bit unstable, working at the moment, somehow - i suggest we close it, but note comment above.

On a general note, I do have a number of thoughts/comments/feedback Iwould like to write somewhere, @cketti where would you advise I do this? Thanks

**Comment by cketti** [comment]
You can use the forum for general comments: https://forum.k9mail.app/
