### ISSUE TITLE
Wrong folder names for special-use folders with IMAP namespace prefix

### ISSUE THREAD

**Issue by atetzner** [thunderbird/thunderbird-android#701]
K9 seems to choose wrong names for special-use folders when the IMAP namespace has a prefix.

I'm using a Dovecot Server with the following configuration:

```
namespace {
  type=private
  prefix = INBOX/
  separator = / 
  inbox = yes 

  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }

  [...]
}
```

With this settings, K9 correctly recognizes every folder: The folder names in the list of all folders are shortened by the namespace prefix and I get folders like "Inbox", "Junk" and e.g. "Archives/2015". The real IMAP folder names are "INBOX", "INBOX/Junk" and "INBOX/Archives/2015".

K9 also reads the configured special-use flag but here, the namespace prefix isn't stipped. Instead of using e.g. the "Junk" folder, K9 uses folders that are listed as e.g. "INBOX/Junk" in K9 (due to prefix stripping) and are effectively named "INBOX/INBOX/Junk".

After setting up a new account in K9 with the server-settings mentioned above, the "wrong" folder names are also visible in the settings: Under `Account settings -> Folders` the special folders are listed as e.g. "INBOX/Junk" which redirects to the wrong folder as mentioned above. If you manually select the Junk folder, K9 will only display "Junk" in the settings.

**Note** that I'm not too deep into Dovecot configuration and therefore this could also be a wrong configuration in Dovecot. But after playing around with the server settings, I think this is a K9 issue.

**Comment by klada** [comment]
This is not only related to Dovecot, as it also happens with Cyrus and possibly all other IMAP servers (@see the older bug on Google Code: https://code.google.com/archive/p/k9mail/issues/6491)

The reason for this is that `autoconfigureFolders` does not know anything about IMAP namespaces (@see: https://github.com/k9mail/k-9/blob/master/k9mail-library/src/main/java/com/fsck/k9/mail/store/imap/ImapStore.java#L512)
