### ISSUE TITLE
DuckDuckGo Browser blocked tracking

### ISSUE THREAD

**Issue by Roever1** [thunderbird/thunderbird-android#7013]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

None

### Android version

Shift OS

### Steps to reproduce

Use DuckDuckGo Browser app

### Expected behavior

No tracking.

### Actual behavior

Tracking?

### Logs

For a few days now Im using the DuckDuckGo Browser to block tracking via local vpn and it just told me that it blocked a facebook tracker from K9. How can that be?  Misstake? Hidden tracker? I will attache a screenshot tmr from my pc.
I would appreciate some input.
Thanks

**Comment by cketti** [comment]
Currently K-9 Mail doesn't attempt to block any trackers (for that, see e.g. #6125). Loading remote content is disabled by default. However, if you tap the "show remote images" button, all referenced remote content (including tracking pixels included by the sender of the message) will be loaded. This is not a bug.
