### ISSUE TITLE
swipe too quick to delete

### ISSUE THREAD

**Issue by velocity08** [thunderbird/thunderbird-android#7015]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

F-Droid

### Android version

13

### Device model

pixel 7 pro

### Steps to reproduce

Turn on swipe function
Set delete swipe left or right
Go to email list
Swipe to delete
Email is deleted.

The issue is when you accidentally touch an email that shouldn't be deleted, the slitest swipe will delete the email.

The swipe is to sensitive and should have a delay or require longer swipe motion to activate the desired function especially for deleting an email.

Too many emails have been deleted accidnetly due to the existing implementation and over sensitivity of the gesture.

### Expected behavior

Longer swipe with decreased sensitivity.
More like apple mail swipe gesture.

### Actual behavior

A screen shot isn't needed please follow the steps laid out and test asndiscribed.

**Comment by KomtGoed** [comment]
Where can I vote for this bug? Rather annoying, especially if you are used to Outlook for work mails...

**Comment by fishchimp** [comment]
Hi, I'll have a go and try to fix this issue.

**Comment by bobmorane06** [comment]
I'm still unintentionally deleting too many emails (which didn't happen with fairmail), even though I see this closed. @velocity08, is the problem solved for you?
