### ISSUE TITLE
Missing oauth support for outlook.fr

### ISSUE THREAD

**Issue by Damaj301damaj-lol** [thunderbird/thunderbird-android#7030]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.707

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Samsung Galaxy a71

### Steps to reproduce

1. Go to add email
2. Add an email that ends with outlook.fr (valid domain from Microsoft)

### Expected behavior

It should have redirected me to authorize with outlook, like if it was outlook.com, that works as well.

### Actual behavior

It asks for a password, instead of redirecting me to the microsoft login page.

**Comment by cketti** [comment]
K-9 Mail currently doesn't recognize outlook.fr automatically. So you have to manually provide the appropriate server settings. Following these instructions should work: https://forum.k9mail.app/t/how-do-i-add-an-office365-account/5072
