### ISSUE TITLE
Buttons disabled in Account Setup Basics when rotating

### ISSUE THREAD

**Issue by rezazarchi** [thunderbird/thunderbird-android#7061]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.707

### Where did you get the app from?

Other

### Android version

11

### Device model

Emulator

### Steps to reproduce

1. Open the app for the first time
2. Click on Next
3. Enter your email address (make sure it's a valid email address and buttons are enabled)
4. Rotate the device

### Expected behavior

You should still see buttons enabled

### Actual behavior

Buttons become disabled again. they remain disabled until we clear some character and write it again.

https://github.com/thundernest/k-9/assets/8654398/12878d57-c714-422c-bfa2-001d86b3ce35

**Comment by cketti** [comment]
I'm able to reproduce this behavior. However, we're currently rewriting the account setup. So we're not going to fix this bug in the old code.
