### ISSUE TITLE
No notifications on Android 13 on Pixel 6 Pro and Pixel Watch

### ISSUE THREAD

**Issue by tbclark3** [thunderbird/thunderbird-android#7082]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Pixel 6 Pro

### Steps to reproduce

1.  Turn on alerts
2. Receive new email by IMAP idle

### Expected behavior

The phone should provide an audible alert and vibration in accordance with the K-9 alert settings.  Other apps on my phone function as configured, sending audible alert or vibration or both to the phone and/or watch.

### Actual behavior

The phone receives the new mail silently, with no audible alert and no vibration. It does show briefly on the lock screen and does display the new email icon in the status bar.  The watch displays an unread alert dot, but also does not provide an audible alert and does not vibrate.

### Logs

I have changed the username to "user" and the actual domain to "domain".

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/12113102/k9mail-logs.txt)

**Comment by tbclark3** [comment]
Update: I just discovered a setting "Don't ring/vibrate notifications on your phone while wearing watch" and disabled it.  K-9 now delivers notifications correctly on the phone, though still not on the watch. It's still a bug because all of the other apps on my phone that are allowed to send notifications do so correctly to the phone or the watch.

**Comment by cketti** [comment]
According to the log the app creates the notification just fine. Make sure the notification category is properly configured (you can get to the system configuration screen from the app via *Settings → [Account] → Notifications → Messages).

Setting vibration/sound on the notification directly has been deprecated (all notifications now have to belong to a category and the category defines the vibration/sound settings). If the software sending the information to the watch requires this information to also be set on the notification itself, I'd consider this a bug in the watch software, not K-9 Mail.

**Comment by tbclark3** [comment]
Thanks for your fast reply! Your answer makes sense. The software sending the notification to the watch is written by Google, so you would think they would follow standards, but apparently not.
