### ISSUE TITLE
[BUG] K-9 Mail Notification Shows email with obscure characters for almost every email

### ISSUE THREAD

**Issue by vdbhb59** [thunderbird/thunderbird-android#7093]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.707 / 6.602

### Where did you get the app from?

F-Droid

### Android version

Vivo A13

### Device model

Y35

### Steps to reproduce

Scroll for notification, and the K-9 Mail app notification shows almost all the emails which arrive with some sort of obscure characters. However, when you open the email (either via notification, or directly via pp), the email shows properly in English/Selected language without any issues.
See the 2 images. First of the notification with preview showing obscure characters, and the second image of the email app itself without any issues there. This I have been facing both in Stable as well as Beta versions for quite some time now. The email itself have no issues, it only happens in K-9 Notifications.

### Expected behavior

The notification should show the proper characters, example English, Spanish, German, basically he way email is.

### Actual behavior

Notification showed email preview with some sort of illegible language characters.

![K-9 Notification_Obscure](https://github.com/thundernest/k-9/assets/60728004/ec652a5f-c0b3-4abe-85bd-d7ab303ef71b)

![K-9 App_No_Issue_Here](https://github.com/thundernest/k-9/assets/60728004/f94524b4-0e6a-4b66-a01d-32186afc6e6e)

### Logs

See the attached images above.

**Comment by cketti** [comment]
Does the preview text in the notification match the preview text in the message list?

**Comment by vdbhb59** [comment]
> Does the preview text in the notification match the preview text in the message list?

Did not try translating it. Next time I receive similar one, will check it.

**Comment by vdbhb59** [comment]
> Does the preview text in the notification match the preview text in the message list?

Yes, the message has the same details as the notification. Have checked in the last 45-50 mails and they match upon translating.

**Comment by cketti** [comment]
Sorry, I wanted to know whether the preview text that is displayed in the message list screen is the exact same text that is displayed in the notification.

<img src="https://github.com/thundernest/k-9/assets/218061/51baa3d3-dfb1-4f20-88f6-e80f75267069" alt="k9mail__message_list__annotated" width=300>

It sounds like it isn't. But that the text displayed in the notification is a translated version of the text displayed in the message list screen. 

K-9 Mail doesn't have a translation feature. So I'm guessing translating the text of notifications is a feature of either your Android version or an app you have installed. It's not something K-9 Mail is doing.
