### ISSUE TITLE
Website https://k9mail.app/ isn't working

### ISSUE THREAD

**Issue by PanderMusubi** [thunderbird/thunderbird-android#7098]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

n/a

### Where did you get the app from?

F-Droid

### Android version

n/a

### Steps to reproduce

1. Go to Website https://k9mail.app/

### Expected behavior

Website https://k9mail.app/ works

### Actual behavior

Website https://k9mail.app/ isn't working

**Comment by njeyaakili** [comment]
i just tried a range of approaches for getting to the site, including using the urls you included above, and they all worked. you need to be more specific about your "isn't working". how are you trying to open this, e.g., from the link on the app's "about" screen or something else. if from the k-9 app, what browser is defined as the default on your device (or what browser is being used to try to open the url)?

**Comment by PanderMusubi** [comment]
I'm getting in Firefox:

    Hmm. We’re having trouble finding that site.
    
    We can’t connect to the server at k9mail.app.
    
    If you entered the right address, you can:
    
        Try again later
        Check your network connection
        Check that Firefox has permission to access the web (you might be connected but behind a firewall)

**Comment by cketti** [comment]
Works for me. Also, several sites that check whether a website is down don't report any errors. This must be a problem on your end.

**Comment by PanderMusubi** [comment]
Not it works again, so fine ti is closed. Thanks for the future refence.
