### ISSUE TITLE
Loading infinity "Retrieving account information", after rotating this page

### ISSUE THREAD

**Issue by mhf1998** [thunderbird/thunderbird-android#7107]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.707

### Where did you get the app from?

F-Droid

### Android version

10

### Device model

Samsung A6

### Steps to reproduce

1. Go to 'Add Account'
2. Enter the Email address
3. Click on 'Next'
4. Enter the password and Login with the OAuth2 method in the browser
5. return to the app
6. Rotate screen In the "Retrieving account information" page

### Expected behavior

There should be no problem with the performance, "Retrieving account information" is done correctly and the login is completed

### Actual behavior

We see that the loading "Retrieving account information" never ends and it continues indefinitely.
And the login is not completed.

https://github.com/thundernest/k-9/assets/34542204/b51ce144-06a0-48a1-8f62-a31800926336

**Comment by cketti** [comment]
We're currently rewriting the account setup code and won't fix bugs in the old code.

**Comment by rezazarchi** [comment]
> We're currently rewriting the account setup code and won't fix bugs in the old code.

I understand that the team is currently in the process of rewriting the account setup code. This is an area we are particularly interested in and would like to contribute to.

Could you kindly let us know if the new codebase has been made available in a separate branch or repository? We are eager to review it and potentially propose some enhancements or fixes, should that align with your plans for this portion of the project.
