### ISSUE TITLE
Drafts of encrypted mails are saved in plaintext

### ISSUE THREAD

**Issue by felly** [thunderbird/thunderbird-android#711]
## Description:

When sending an encrypted mail the message may be saved in plaintext on the server (as draft). The actual sent mail is encrypted.
## Steps to reproduce:
- Make sure to have two mail accounts configured (both have public/secret keys)
- Send it to yourself (or to another one - just tested it by sending it to myself)
- Check Encrypted checkbox
- Write some Subject and "encrypted" message
- Change to the other mail account
- Toast appears which says the message is saved as draft
- Send the mail
- Sent mail is encrypted
- Draft of mail (found in trash folder) is unencrypted

**Comment by gappleto97** [comment]
How high a priority is this?

**Comment by Valodim** [comment]
I'm not sure on the specifics, but there is some code in current master which refuses saving a draft if encryption is enabled. I'm not sure if this is a very wise decision usability-wise, I might switch to simply encrypting drafts if that is a better way to go.

**Comment by gappleto97** [comment]
Alright. If you have anything simple for me to do, I'm more than willing to help. (More a lack of Android knowledge than Java. Got plenty of that.)

**Comment by lbdroid** [comment]
Maybe just keep drafts for encrypted messages stored locally? The local filesystem on newer devices (starting with Nexus 6) is encrypted by default, so this wouldn't be particularly serious of a vulnerability.

**Comment by Valodim** [comment]
That's the way it already is since bbc52b32650bad805cbc13e44a45ea87badb26d4 and 64ab769034d370b39a8fd0309148be73cc21b62f

**Comment by rugk** [comment]
Why not (additionally) encrypt the mails when stored as a draft, so one can easily decrypt and continue writing them?

When you introduce an option to sync them, users can even start writing an encrypted mail on their Android device and continue writing this mail on their desktop (or vice versa).
IMHO this would be great (and better than to just store the mails locally).

**Comment by rugk** [comment]
Actually I could reproduce this issue too! (The drafts are **not** only saved locally!) Why has not this been fixed before the 1.5 release? It's a huge vulnerability.

A user can reasonable expect the draft to be saved in a safe way when writing PGP-encrypted messages, but even with v1.5 of K9 mail such drafts are saved in plain-text in the drafts folder (when I e.g. go back from the new mail screen), which is really irresponsible as it completely defeats the purpose of the end-to-end-encryption.

The solution is easy: Just PGP-encrypt all mails (with your own public key) when saved as drafts.

**Comment by cketti** [comment]
@rugk: The current version of K-9 Mail is v5.201. Are you sure you're not using a K-9 Mail clone with a different versioning scheme?

**Comment by rugk** [comment]
I could reproduce this issue with the official F-Droid built of K9 mail, which shows me it's v5.200

**Comment by rugk** [comment]
I can actually constantly reproduce this bug with all mails. I am using IMAP and I can find all my saved mails in the "drafts" directory in the web interface of the provider I am using.

**Comment by rugk** [comment]
Maybe you are determining the status of an *encrypted* message in the wrong way as one cannot be sure whether it will be encrypted before the message is actually sent. (I usually use the middle position of the slider.)
However there is no problem in just encrypting all drafts.

**Comment by sporkwitch** [comment]
This issue is still present in current beta version.  Shoving encryption down our throats the way it does now, it's rather amusing that it continues to consistently save all drafts in plaintext, even when that abysmal slider is set all the way to the right.

**Comment by rugk** [comment]
> even when that abysmal slider is set all the way to the right.

The slider is very nice! I like it very much, but let's do not get of-topic.

I'd like to add that it worked previously before the v5 release of K9 mail. It was not a very nice way of doing it, but there at least encrypted mails could not be saved as drafts and K9 mail would show you a message stating that it declined to save the message as a draft.

**Comment by Valodim** [comment]
Found the bug, writing tests to nail down the behavior correctly, bugfix release soon. Thanks for your report.

**Comment by rugk** [comment]
Awesome! So what will be the future behaviour: save locally only/encrypt drafts to PGP-supported receivers or encrypt all drafts?

(I would prefer the latter, or, optionally, offer configuration abilities)

**Comment by cketti** [comment]
Fixed with #1983

**Comment by rugk** [comment]
Followup in https://github.com/k9mail/k-9/issues/2107
