### ISSUE TITLE
The recipient address <xxx@gmail.com/> is not a valid RFC-5321 address.

### ISSUE THREAD

**Issue by Goooler** [thunderbird/thunderbird-android#7112]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v6.602

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Moto X40

### Steps to reproduce

Edit a mail, input the recipient address end with a `/`, then send it.

https://github.com/thundernest/k-9/assets/10363352/cbb7a99a-b348-4f88-adc3-3fccc1f4ba29

### Expected behavior

We can check the mail address before sending it, toast a message to tell the user that the address is invalid, or show a dialog like Gmail did below:

<img src="https://github.com/thundernest/k-9/assets/10363352/30cb95a2-4b2e-4a38-a691-9e758a9ca5c1" width="33%" height="33%">

### Actual behavior

Sending it, and showing the failure.

**Comment by mhf1998** [comment]
Hi @Goooler 

I'm happy to let you know that the issue with invalid email characters has been fixed and merged into the project. Thanks to @cketti  and the team for their support.

At [arissystem](https://github.com/arissystem), we're always eager to contribute and collaborate on this project. We're looking forward to more opportunities to work together.
