### ISSUE TITLE
Account added even though I didn't finish setup

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/thunderbird-android#7118]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.708

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Galaxy S23

### Steps to reproduce

Set up an account but don't hit "Done" on the last screen (I backed out of it with the back button).

Email from the new account shows up in Unified Inbox and I get notifications for the new account. But it doesn't show up in the account list in the drawer or in settings (under accounts) - so I can't remove it.

### Expected behavior

Preferably if you don't hit done, an account should not be added. But if it is, it should show up in the account list and the settings.

### Actual behavior

I now have a ghost account that I cannot manage.

**Comment by cketti** [comment]
This won't be an issue with the new account setup. I don't see us fixing this in the old account setup.
