### ISSUE TITLE
I see just blank mails

### ISSUE THREAD

**Issue by Domx93** [thunderbird/thunderbird-android#7122]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

F-Droid

### Android version

EMUI 12.0.0

### Device model

Huawei mate 10 pro 

### Steps to reproduce

Open k-9 mail
Open a mail
See the message as totally empty 

### Expected behavior

I should see properly the messages 

### Actual behavior

![Screenshot_20230813_092303_com fsck k9](https://github.com/thundernest/k-9/assets/30021637/5b2c6de0-c7ec-4555-ac3e-bd90cf7e937c)

**Comment by ByteHamster** [comment]
Update the "Android System WebView" app and restart your phone

**Comment by Domx93** [comment]
> Update the "Android System WebView" app and restart your phone

It worked, thank you!
