### ISSUE TITLE
Add yahoo.fr to Oauth

### ISSUE THREAD

**Issue by a128a** [thunderbird/thunderbird-android#7132]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

F-Droid

### Android version

13

### Steps to reproduce

Try to register to your <username>@yahoo.fr account in K9-mail.

### Expected behavior

K-9 mail should authorize using @yahoo.fr email accounts

### Actual behavior

This does not work. Even using "manual configuration" then Oauth does not work.

I found a way to add my yahoo account : logging in using <username>@yahoo.**com** email address works.
Then in K9-mail settings, it is possible to replace all "yahoo.com" by "yahoo.fr".
But K9-mail should authorize @yahoo.fr emails.
Moreover, Oauth does not seem to work on POP servers.

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/how-do-i-add-a-yahoo-account/3848#manual-setup-for-unsupported-domains-2

**Comment by a128a** [comment]
Thanks.

**Comment by wmontwe** [comment]
Should be fixed and testable with our next beta version.
