### ISSUE TITLE
Duplicated messages in "sent" folder with Outlook using

### ISSUE THREAD

**Issue by Goooler** [thunderbird/thunderbird-android#7134]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v6.602

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Moto X40

### Steps to reproduce

Send a mail with an Outlook account, go to the "sent" folder, and refresh this folder, you'll see 2 mail with the same content.

https://github.com/thundernest/k-9/assets/10363352/042cb5d9-77a5-47b5-ba41-e9d4adb535bd

### Expected behavior

1 mail should be shown in the sent folder.

### Actual behavior

2 mail shown.

**Comment by cketti** [comment]
Outlook is saving a copy of sent messages automatically. Uncheck *Settings → [Account] → Sending mail → Upload sent messages* to prevent K-9 Mail from uploading an additional copy.

In the future please use the [forum](https://forum.k9mail.app/) for support requests.

**Comment by jew4blackberry** [comment]
@cketti You are on point. Thanks!
