### ISSUE TITLE
New account UI needs to be pushed to Transifex

### ISSUE THREAD

**Issue by AO-L10N** [thunderbird/thunderbird-android#7136]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.710

### Where did you get the app from?

Other

### Android version

12

### Steps to reproduce

1. Tap "Settings"
2. Tap "Add account" 

### Expected behavior

The UI should be shown in the user’s preferred language.

### Actual behavior

UI is in English.

**Comment by wmontwe** [comment]
We're working on it and I added it to our roadmap.

**Comment by wmontwe** [comment]
We changed our translation tool from Transifex to Weblate. The new accoutn ui translations are now available at: [tb-android](https://hosted.weblate.org/projects/tb-android/)
