### ISSUE TITLE
Cannot set up outlook office365 mail

### ISSUE THREAD

**Issue by debie-A320FL** [thunderbird/thunderbird-android#7141]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

F-Droid

### Android version

Android 11 /  CrDroid

### Steps to reproduce

Try to register an outlook office 365 mail

### Expected behavior

K-9 mail should use OAuth 2.0 to be able to log in.

### Actual behavior

I never succeed to set up my mail with Imap

**Comment by kubuntu-newbie** [comment]
Following the instructions in the link by ByteHamster

Using app version 6.603, on Graphene OS / Android 14

incoming server:
outlook.office365.com
SSL/TLS
993
OAuth 2.0

outgoing server
smtp.office365.com
STARTTLS
587
OAuth 2.0

When setting up the server while using Auto-detect namespace I get an error:

Setup could not finish
Cannot connect to server
(Command: NAMESPACE; response:
#4# [BAD, User is authenticated but not connected.]]

If I turn off auto-detect namespace (tried blank, INBOX. etc) , the app allows creating of the server but I can't get any emails pulled down.

And when setting up smtp.office365 outgoing server:

"Setup could not finish
Cannot connect to server.
(Unable to open connection to SMTP server.)"
