### ISSUE TITLE
new account setup in 6.710 has too small text input

### ISSUE THREAD

**Issue by steko** [thunderbird/thunderbird-android#7146]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.710

### Where did you get the app from?

F-Droid

### Android version

8

### Device model

WAS-LX1

### Steps to reproduce

1. Start creation of new account
2. New screen with text input is shown
3. Start writing the email address 

### Expected behavior

The text input should be entirely visible and expand to fill all needed vertical space 

### Actual behavior

![Screenshot_20230829-200651](https://github.com/thundernest/k-9/assets/40545/5df91e7a-3360-4977-8326-44018fa32091)

The keyboard eats up most vertical space and the large header won't scroll to leave room for the text input.

![Screenshot_20230829-200702](https://github.com/thundernest/k-9/assets/40545/ec7dbfe2-f934-4c05-b500-b27c51347aba)

The address can be written even when the input is not visible and when the keyboard is closed it's perfectly aligned vertically.

**Comment by wmontwe** [comment]
@steko Thanks for reporting this issue. Added it to our roadmap for the new account setup.
