### ISSUE TITLE
Can't add Outlook-based emails (Universiteit van Amsterdam): OAuth not working

### ISSUE THREAD

**Issue by tobiasBora** [thunderbird/thunderbird-android#7147]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.100

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Xcover 4s

### Steps to reproduce

The University van Amsterdam (UvA) uses an outlook-based email client. Unfortunately, when I try to connect, I get an error saying that this client is not.
1. Add an account
2. Add the user like `me@uva.nl` and click on "manual configuration"
3. Select Imap
4. Change the imap server to `outlook.office365.com` (this is what Thunderbird successfully uses), SSL/TLS (port 993), user `me@uva.nl`
5. Click on Authentication `OAuth 2.0` (other methods fail)
6. Press Next
7. Observe the error like `OAuth 2.0 is not configured for this provider`.

### Expected behavior

I expect to be able to connect.

### Actual behavior

I get an error `OAuth 2.0 is not configured for this provider`. I guess it is somehow related to https://github.com/thundernest/k-9/issues/6152 but I found no workaround until this issue is solved, and the domain `outlook.office365.com` should already be added I guess.

**Comment by wmontwe** [comment]
Did you follow this [guide on how to setup an Office365](https://forum.k9mail.app/t/how-do-i-add-an-office365-account/5072) account?

If that doesn't work #6152 would be needed.

**Comment by Iey4iej3** [comment]
It works on v6.602 (F-Droid): a webpage pops out. Your app version might be too old (the guide says that you need at least v6.201).

**Comment by wmontwe** [comment]
Yes, Office 365 OAuth 2.0 support was added in [6.201](https://github.com/thundernest/k-9/releases/tag/6.201). So older versions won't work.

**Comment by tobiasBora** [comment]
Thanks, I tried with the latest version 6.710, and I can go one step further: now I get redirected to outlook, but now it tells me that my admin needs to validate my request (I had no such thing when connecting from thunderbird)… not sure why thunderbird does not need this validation. Hopefully it will work once the admin validate my request. For now, the message I get is:
```
Authorization failed with the following error: AADSTS65004: User declined to consent to access the app.
```

**Comment by wmontwe** [comment]
I'm sorry to hear that. I guess that Thunderbird for Desktop was already added as an exception. We plan to provide better Microsoft exchange support, but this won't happen this year.

**Comment by tobiasBora** [comment]
Nice, thanks a lot!

**Comment by Iey4iej3** [comment]
> I'm sorry to hear that. I guess that Thunderbird for Desktop was already added as an exception. We plan to provide better Microsoft exchange support, but this won't happen this year.

When Thunderbird for Android is released, will the client ID be the same as that on desktop? I mean, will it be automatically accessible, given that TB for Desktop is on the list?

**Comment by helsingi** [comment]
> > I'm sorry to hear that. I guess that Thunderbird for Desktop was already added as an exception. We plan to provide better Microsoft exchange support, but this won't happen this year.
> 
> When Thunderbird for Android is released, will the client ID be the same as that on desktop? I mean, will it be automatically accessible, given that TB for Desktop is on the list?

I really hope so

**Comment by tobiasBora** [comment]
Same, just to motivate it a bit more, I wrote to the IT department, long story short, they don't want to add K9-mail because their is not enough demand apparently, and most importantly it needs to be approved by multiple security persons and I guess they do not want to lose time on this.

**Comment by Iey4iej3** [comment]
> > > I'm sorry to hear that. I guess that Thunderbird for Desktop was already added as an exception. We plan to provide better Microsoft exchange support, but this won't happen this year.
> > 
> > 
> > When Thunderbird for Android is released, will the client ID be the same as that on desktop? I mean, will it be automatically accessible, given that TB for Desktop is on the list?
> 
> I really hope so

Unfortunately, this is not the case. However, it might be customizable in the future: #6176
