### ISSUE TITLE
dark mode: "no client certificate" text is black on Grey background

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#7153]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.710

### Where did you get the app from?

Other

### Android version

13

### Device model

Pixel 7 Pro

### Steps to reproduce

Open mailserver settings for an account (inbox or outbox)
I can barely make out the string "No client certificate" (it's German in this screenshot) 
![Screenshot_20230902-130955](https://github.com/thundernest/k-9/assets/5685512/2cb99b78-9d1d-4dd8-9e07-07ab0cbbdd15)

### Expected behavior

bright font color like all other strings

### Actual behavior

black font color on Gre background (low contrast)

**Comment by wmontwe** [comment]
@Djfe We rewriting the account setup UI, where this issue won't happen again. If you try our latest [beta version](https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68). It is already available for adding new accounts. Editing of existing settings will follow shortly.

**Comment by Djfe** [comment]
Well in that case this won't matter. Good :)
also, I am using 6.710 already 😊
but thanks for sharing the forum thread
