### ISSUE TITLE
Yahoo Mail (OAuth) does not work: "Developers: Please specifiy a valid request"

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#7159]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.710

### Where did you get the app from?

F-Droid

### Android version

13

### Steps to reproduce

1. add acount
2. enter yahoo mail address*
3. Configuration found (expanding it shows correct imap and smtp settings)
4. sign in

*I have a @yahoo.de address. I've read and tried the advice on https://forum.k9mail.app/t/how-do-i-add-a-yahoo-account/3848#manual-setup-for-unsupported-domains-2 though manual configuration doesn't seem to be necessary as it is already correct.

### Expected behavior

Successful login

### Actual behavior

error message "oops! apparently an error occured. please try again later. developers: please specify a valid request and submit again" (have tried later, error occurs since more than a week)

setting up the same account via oauth in thunderbird works fine.

![Screenshot_20230907-083228](https://github.com/thundernest/k-9/assets/75673035/2b52f22a-74d6-48e9-8756-e1bbc9c0aa9b)

**Comment by wmontwe** [comment]
I replicated the issue with our current 6.710 version and also with our production release.

Seems something changed. We have a look.

**Comment by wmontwe** [comment]
Our OAuth configuration is correct, but we're not allowed to request the email scope. Seems that our Yahoo Dev account is the reason.

**Comment by malahx** [comment]
Hello, I have the same issue with an aol email. With the same screen error.

When I opened the authorization url and I can see an error message inside the url:

`https://api.login.aol.com/oauth2/error?client_id=XXXXX&error=invalid_request&error_description=invalid+code+challenge+or+method`

**Comment by malahx** [comment]
After some search and some test I can access to an aol login page with this parameters:
`https://api.login.aol.com/oauth2/request_auth?client_id=dj0yJmk9dUNqYXZhYWxOYkdRJmQ9WVdrOU1YQnZVRFZoY1ZrbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PWIw&response_type=code&code_challenge_method=S256&code_challenge=qjrzSW9gMiUgpUvqgEPE4_-8swvyCtfOVvg55o5S_es&redirect_uri=com.fsck.k9%3A%2F%2Foauth2redirect`

I added the parameters: `code_challenge_method=S256&code_challenge=qjrzSW9gMiUgpUvqgEPE4_-8swvyCtfOVvg55o5S_es`
`code_challenge_method` seems to be a constants.
The value I put in `code_challenge` is a copy-past of a value I found, but I don't think it is a propellant value.

**Comment by wmontwe** [comment]
@malahx Thanks for your investigation, that helped a lot. It seems that Yahoo only supports OAuth 2.0 using Authorization Code with PKCE now. We used to have plain enabled and that stopped working.

**Comment by wmontwe** [comment]
Should be fixed and testable with our next beta version.
