### ISSUE TITLE
handling of embedded .eml files - inline vs attachment

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#7165]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.7.10

### Where did you get the app from?

Other

### Android version

13

### Device model

Pixel 7 Pro

### Steps to reproduce

[dmarc-embedded-as-eml.zip](https://github.com/thundernest/k-9/files/12558942/dmarc-embedded-as-eml.zip)

### Expected behavior

K-9 shows embedded mail like a quoted mail below the actual mail text.
K-9 allows me to see Names and Mailaddresses of all recipients.

### Actual behavior

I can't view/see the Mailaddresses of recipients of the quoted mail.

Ok in this case they are the same due to it being a dmarc protected mail, but you get the point.
If people forward you any email as embedded, then you should be able to read the addresses in it :)
(maybe even view the headers at some point but that's low prio to me)

Also there is the issue, that K-9 just drops the .eml on regular forward.
Only forwarding the .eml as an attachment works.

Though K-9 forwards mails as attachment like this:
```
------CRKHS6K8IK0190Y3APDX7NBAFZT2CK
Content-Type: message/rfc822;
 name="Re: Implementing bluetooth speakers on OpenWrt?.eml"
Content-Disposition: attachment;
 filename="Re: Implementing bluetooth speakers on OpenWrt?.eml";
 size=11297
```

For comparison, what the mailing list did:
```
--===============2691111782005021451==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: inline
```

What do you think about forwarding mails as an attachment using `Content-Disposition: inline` instead of `Content-Disposition: attachment;`?

**Comment by Djfe** [comment]
Interesting fact: Thunderbird shows embedded .eml files whether they are inline or attachments
Thunderbird also allows me to save the .eml file even when it's inline (K-9 does not)

**Comment by cketti** [comment]
The problem is that email addresses with a display name are formatted like `Display name <user@domain.example>`. This was then included in the display HTML without HTML-encoding the text, i.e. the email address in angle brackets was treated as HTML tag.

The fix should be included in the next beta.

**Comment by Djfe** [comment]
ah I see,
please make sure to escape the string correctly so it renders as text (`<pre>` might be enough?)

in that regard: it's kind of interesting, what counts as a valid mail address:
```<`wget${IFS}r.vc/ghe`@ryanc.org>```

see https://github.com/openwrt/openwrt/pull/12209#issuecomment-1475351663
