### ISSUE TITLE
with any other font than Roboto, sender's name overlaps subject in notifications

### ISSUE THREAD

**Issue by alis0nc** [thunderbird/thunderbird-android#721]
When I use any other font than Roboto, the sender's name overlaps the subject line in the notifications. This makes them look kind of ugly and difficult to read the last character of the sender/first character of the subject. It's almost as if the bounding box for the sender text (excuse bad terminology, I'm not an Android dev...) was defined using Roboto's metrics, and since Samsung Sans and Frutiger are wider fonts, it overruns that. Refer to the below screenshots while using Frutiger, Samsung Sans, and Roboto, as compared to how the Gmail app shows the notifications. (Samsung Galaxy Note 3, Android 4.4.2)

![frutiger_notification_screenshot](https://cloud.githubusercontent.com/assets/4296609/8881089/2fdc8748-320b-11e5-97f7-7902668eba0d.png)
![samsungsans_notification_screenshot](https://cloud.githubusercontent.com/assets/4296609/8881090/2fded8b8-320b-11e5-845b-e62978ea6b25.png)
![roboto_notification_screenshot](https://cloud.githubusercontent.com/assets/4296609/8881091/2fded980-320b-11e5-8ddb-307f48cc9ab2.png)

**Comment by cketti** [comment]
Looking at our code I don't see an obvious reason for this. Someone needs to check AOSP Email to see what they do differently.

**Comment by alis0nc** [comment]
@cketti The other example notifications are not the AOSP mail app, they're the (latest update as of when i took the screenshots) Gmail app. I'll try sideloading [the KitKat AOSP email app](http://www.androidpolice.com/2013/10/31/apk-download-heres-the-default-email-app-from-android-4-4-with-gmail-style-ui-and-a-slide-out-menu/) and test this in a bit.

**Comment by alis0nc** [comment]
The AOSP email app behaves the same as the gmail app so it would be a good basis for comparison to how K-9 handles notifications.. (Yes, that is the AOSP email app, i have no idea why the notification icon is the same as the gmail app.)

![screenshot_2015-07-25-23-17-48](https://cloud.githubusercontent.com/assets/4296609/8892416/ca2e1744-3323-11e5-91b3-6ebc18fc965a.png)

**Comment by maniac103** [comment]
The code of the AOSP mail app (which is very likely to be shared with Gmail) that generates this line is here, FWIW:
https://github.com/CyanogenMod/android_packages_apps_UnifiedEmail/blob/cm-12.1/src/com/android/mail/utils/NotificationUtils.java#L1459

**Comment by denim2x** [comment]
@alis0nc Please consider backing this issue at [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=24900116)](https://www.bountysource.com/issues/24900116-with-any-other-font-than-roboto-sender-s-name-overlaps-subject-in-notifications?utm_source=24900116&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by cketti** [comment]
Closing due to age. Hopefully time has solved this issue. If not, feel free to open a new issue.
