### ISSUE TITLE
OAuth failed yahoo mail

### ISSUE THREAD

**Issue by lexterror** [thunderbird/thunderbird-android#7213]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.710

### Where did you get the app from?

Other

### Android version

13

### Device model

Motorola

### Steps to reproduce

Tried login in to yahoo with Bromite and Chrome

### Expected behavior

Be able to sign in to yahoo

### Actual behavior

failed to login

**Comment by wmontwe** [comment]
This is related to #7159 and should be fixed with our next beta version.

**Comment by cketti** [comment]
[K-9 Mail 6.711](https://github.com/thundernest/k-9/releases/tag/6.711) is available now.

**Comment by lexterror** [comment]
It works, thank you so much!!!
