### ISSUE TITLE
Subjects with characters outside the BMP sometimes get mangled

### ISSUE THREAD

**Issue by philippelatulippe** [thunderbird/thunderbird-android#723]
When I reply to a message with a subject containing characters outside the BMP, occasionally one of the characters will get split into two characters which render as a question mark. Characters outside the Basic Multilingual Plane are 4 bytes wide when using UTF-8, and it looks like they sometimes get chopped in half when the header is encoded. The MIME encoded-word stops right in the middle of the character, and then starts with the other half.

This happens every 2 dozen or so message (threads), with subjects that are more than 3-4 characters longs. It only happens on replies. I'm guessing because with the addition of "Re:", the 4-byte characters no longer align to the boundary of the MIME header encoder.

**Comment by cketti** [comment]
Can you provide the encoded header line?

**Comment by philippelatulippe** [comment]
I've managed to get it to reproduce reliably, and this time even in the initial message, not just in the reply.

`Original subject: 🐕🐶🐩🐈🐱🐀🐁🐭🐹🐢🐇🐰🐓🐔🐣🐤🐥🐦🐏🐑🐐`

    Subject: =?UTF-8?B?8J+QlfCfkLbwn5Cp8J+QiPCfkLHwn5CA8J+QgfCfkK3wn5C58J+Qoj8=?= =?UTF-8?B?P/CfkLDwn5CT8J+QlPCfkKPwn5Ck8J+QpfCfkKbwn5CP8J+QkfCfkJA=?=

Shows up as `🐕🐶🐩🐈🐱🐀🐁🐭🐹🐢??🐰🐓🐔🐣🐤🐥🐦🐏🐑🐐`

After sending a reply, it gets worse

    Subject: =?UTF-8?B?UmU6IPCfkJXwn5C28J+QqfCfkIjwn5Cx8J+QgPCfkIHwn5Ct8J+QuT8=?= =?UTF-8?B?Pz8/8J+QsPCfkJPwn5CU8J+Qo/CfkKTwn5Cl8J+QpvCfkI/wn5CR8J+QkA==?=

Shows up as `Re: 🐕🐶🐩🐈🐱🐀🐁🐭🐹????🐰🐓🐔🐣🐤🐥🐦🐏🐑🐐`

**Comment by philipwhiuk** [comment]
I reckon I've fixed this in #2722

**Comment by cketti** [comment]
PR #2722 adds support for reading such broken headers. But we need to fix K-9 Mail to not generate them.
