### ISSUE TITLE
Fetch Contacts and Photos

### ISSUE THREAD

**Issue by seniorm0ment** [thunderbird/thunderbird-android#7248]
I use K-9 for my work Gmail, and I notice It doesn't seem to fetch contacts that my server provides. Also their Google photos. 

For example, if I go on Gmail, I can start typing "Joh" and I should see all names in my business. John, Johnny, etc.
Without them being in my local contacts.

And on Gmail, people have their profile pictures.
In K-9, it doesn't fetch those if you have photos enabled. 

It only fetches stuff from local contacts. 
Also I think if this is introduced, a clear distinction between your saved/local contacts and the server contacts is important.

**Comment by cketti** [comment]
K-9 Mail doesn't manage contacts. It uses Android's contact database. 

If you want to sync Google contacts, add the Google account to your device (under Android settings, "Passwords & accounts" or similar), then enable sync for "Contacts".

**Comment by seniorm0ment** [comment]
That's a very unfortunate situation for users who are using K-9 for privacy reasons and do not wish to have the Google account logged into their phone.
It also does not resolve the issue that it cannot pull the same from Outlook as well.
