### ISSUE TITLE
Optional Ad Blocking

### ISSUE THREAD

**Issue by seniorm0ment** [thunderbird/thunderbird-android#7255]
The ability to set ad blocking per account would be nice.
Hide ads, but at minimum deal with tracking urls.

This may break a lot of unsubscribe links, so an option to "allow temporarily" maybe or something similar to how uBlock Origin functions.

**Comment by wmontwe** [comment]
Thanks for your suggestion regarding extended ad blocking features in our email app. While we currently don't have plans for this, contributions are welcome. Your idea of per-account ad blocking and dealing with tracking URLs has been acknowledged. Feel free to contribute or share more ideas.

**Comment by osering** [comment]
Apps, like AdAway is quite effective no Android. Why not use one?

**Comment by pedroapero** [comment]
Hello; the ability to create email management rules would be nice also (like «automatically delete all messages from this sender», eg. blacklisting senders manually).

**Comment by kewisch** [comment]
Hi folks, thank you the ideas! For enhancement suggestions like this, would you mind posting them over on [Mozilla Connect](https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird%20android)? This is a great place for the community to discuss and help shape new ideas together, and is something we review regularly to determine the future roadmap.

I believe there is already a post on email filter rules, if you search for "Thunderbird Android Filter" or something similar you might find it.

To get the most out of your post, check out [this quick guide](https://connect.mozilla.org/t5/discussions/how-to-submit-a-great-idea-in-five-easy-steps/m-p/24) on crafting impactful suggestions. Focusing on the problem your idea solves and how it could help others can really make it stand out!

I’ll be closing this issue to keep our GitHub focused on active development, but I hope to see your idea over there. Thanks again for your input—it means a lot!
