### ISSUE TITLE
Messy Formatting

### ISSUE THREAD

**Issue by seniorm0ment** [thunderbird/thunderbird-android#7256]
My Gmail HTML Mailbox has very weird formatting. All text is pushed to the left side of the screen, and feels really unnatural to read.
Some of the signatures are centered, so the body is to the left, signatures center.

**Comment by wmontwe** [comment]
The 6.6xx versions are our stable versions and all 6.7xx are beta versions for previewing latest mostly stable changes to the project.

**Comment by wmontwe** [comment]
This should be solved by the theming changes for Material 3.
