### ISSUE TITLE
Unified inbox search does not display old emails

### ISSUE THREAD

**Issue by Polymerkemisten** [thunderbird/thunderbird-android#7258]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Oneplus 10T 5g

### Steps to reproduce

Add a minimum of 2 email adresses (issue noticed on IMAP) 
Choose an old incoming email to search for
Set emails to fetch to local folder so that the email will not be listed (local folder size 50, email in question Being number 51 or further back) 
Select an account other than the one that received the email
Go to unified inbox
Use that search menu to search for the email

### Expected behavior

The app should search all inboxes, folders etc all the way back in time. Or it should display the same "search everywhere" option and the magnifying glass (server search?) it displays when doing this in the account that contains the email. 

### Actual behavior

App seems to only search available fetched results including results that have previously been fetched through server search using the normal inbox view. Using the non unified inbox of the email address that received the email and searching using server search is able to fetch old emails, however this requires the user to know which email address received said email, or search every address individually. "search everywhere" and server search in a different email address' inbox search menu will also not fetch the email. 

This would not be an issue if the app did not also lag severely with large inboxes if one sets inbox to fetch all emails from the address to local inbox ( issue #3472 ) 

I have looked through settings and am unable to find anything that allows unified inbox search to server search all accounts. Unsure if this is a bug, a feature not implemented or I have missed a way to enable this.

**Comment by cketti** [comment]
This is not exactly a bug. Right now a search is performed locally at first. To also search on the server the remote search icon (magnifying glass with a cloud) has to be pressed. However, that button is only available when (it's an IMAP account and) the message list of a regular folder is displayed. That's because the app currently doesn't support searching in multiple remote folders and aggregating the results.

Adding support for this is part of issue #4513.
