### ISSUE TITLE
Rename GitHub repository

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#7263]
We're planning to rename the repository to `thunderbird-android` soon.

This issue tracks what we need to do before and after the move.

### Before

- [x] Merge translations from Weblate
- [x] Lock translations on Weblate

### After
- [x] Update Weblate to use the new repository URL and remove the translation lock
- [x] Update [F-Droid metadata](https://gitlab.com/fdroid/fdroiddata) to use the new repository URL
- [x] Update link in the Play Store description
- [x] Update links in this repository (incl. the about screen of the app)
- [x] Update links on the website ([k9mail/k9mail.app](https://github.com/k9mail/k9mail.app) repository)
- [x] Update links in the [k9mail/k9mail-docs](https://github.com/k9mail/k9mail-docs) repository
- [x] Update link in the [k9mail/.github](https://github.com/k9mail/.github) repository
- [x] Update links in the wiki of this repository
- [x] Developers: Update the remote entry in your local copy of this repository
- ~~Update links on blog.thunderbird.net~~

**Comment by williamdes** [comment]
- [ ] Update code occurrences (https://github.com/search?q=repo%3Athundernest%2Fk-9%20%22thundernest%2Fk-9%22&type=code)

**Comment by wmontwe** [comment]
F-Droid changes are pending: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13979

The organisation name has been changed already.

**Comment by cketti** [comment]
Done.
