### ISSUE TITLE
translated strings for "Drafts", "Sent" and "Trash" not shown

### ISSUE THREAD

**Issue by Sgn-32** [thunderbird/thunderbird-android#7283]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

7.1.1

### Steps to reproduce

Open hamburger menu.

### Expected behavior

The translated strings "Entwürfe", "Gesendet" und "Papierkorb" are displayed.

### Actual behavior

The translated strings "Entwürfe", "Gesendet" und "Papierkorb" aren't displayed.
Entwürfe = Drafts
Gesendet = Sent
Papierkorb = Trash

https://github.com/thundernest/k-9/blob/c9834abfaf23aa347541380b91371b90e3be9a24/app/ui/legacy/src/main/res/values-de/strings.xml#L152-L156

![k9](https://github.com/thundernest/k-9/assets/49990901/ac8e8e00-7f09-466e-bb62-3718b6dc2cf5)

**Comment by cketti** [comment]
This behavior is intentional. See #6799.
