### ISSUE TITLE
Temporary authentication failure in LOS 20

### ISSUE THREAD

**Issue by maninthemiddle01** [thunderbird/thunderbird-android#7287]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.711

### Where did you get the app from?

F-Droid

### Android version

LOS 20-20231015-NIGHTLY

### Device model

a52sxq

### Steps to reproduce

1. Open K9 Mail and try to connect to the email server.
2. Observe the error message "ImapResponseParser: conn18649319<<<#1# [NO, [UNAVAILABLE], Temporary authentication failure."

### Expected behavior

The email account should be able to connect to the email server and Mails and Mail folders should load without any issues.

### Actual behavior

The email account is unable to connect to the email server and the K9 Mail interface is not loading properly. The error message "ImapResponseParser: conn18649319<<<#1# [NO, [UNAVAILABLE], Temporary authentication failure." is displayed.

**Notes:**

I have also tried using K9 Mail version 6.711 on another device running LOS 19 and it is able to connect to my email server without any issues. The only difference between the two devices is that the device experiencing the issue is running LOS 20. On the latter the same issue occurs also in version 6.603.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/13063865/k9mail-logs.txt)

**Comment by cketti** [comment]
The server sends a negative response to the authentication command. The response indicates that the server is currently unavailable. The error message the server returns is `Temporary authentication failure. [dipendenza:2023-10-21 04:31:30]`.

I suggest you wait a while for your email provider to fix whatever problem they're currently experiencing. If the error persists, contact them to find out why you're getting this error response.

This doesn't look like a bug in K-9 Mail. Closing the issue.
