### ISSUE TITLE
Google Advanced Protection Support

### ISSUE THREAD

**Issue by starsoccer** [thunderbird/thunderbird-android#7303]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

I am trying to use k-9 on a google account that has advanced protection enabled

### Suggested solution

Ideally K-9 Should be a support application just like Microsoft Outlook, and Thunderbird is

**Comment by cketti** [comment]
Are you using OAuth 2.0 to connect to that Google account? What error message are you getting? Can you post a screenshot?

**Comment by starsoccer** [comment]
Yes using OAuth 2.0 to connect. Screenshot below
![image](https://github.com/thunderbird/thunderbird-android/assets/1938666/636c001d-0d70-41b9-b0d6-be415c2a166c)

**Comment by cketti** [comment]
It doesn't look like there's a lot we can do. Google seems to hand pick the apps that are allowed when Advanced Protection is enabled. Your domain admin should be able to add K-9 Mail to the allowlist, though. See https://support.google.com/a/answer/7281227

**Comment by starsoccer** [comment]
Yeah my hope is that as K-9 transitions to thunderbird it will be allowed since thunderbird on desktop is currently allowed.

As for the other suggestion on the allow list. This is a regular/personal gmail account. There is no domain admin as far as Im aware. This is basically just any regular email account just with advanced protection enabled.

**Comment by cketti** [comment]
You'll have to wait for Thunderbird for Android to be available. Then your best bet is probably to ask Google to allow the app, and hope that enough other users are doing the same.

Closing this issue because it's not actionable.

**Comment by starsoccer** [comment]
I mean ideally K-9 or when it transitions, mozilla should be asking. I dont think it should be end users responsibility to request this from google. I am not sure how thunderbird on desktop got on the list but I assume they spoke with google.

**Comment by Sancus** [comment]
We can always try but it's impossible to make any promises. The Advanced Protection data access list [seems to not include any third party Android apps at all](https://support.google.com/accounts/answer/7539956?hl=en#zippy=%2Ccan-i-use-non-google-apps-services-or-apps-script-with-advanced-protection), period. Only Apple first party apps, Thunderbird, and other desktop email clients are exempted.

**Comment by starsoccer** [comment]
Agreed, I do think its worth a try. Also will just clarify that outlook does work on android which is what I am currently using to get around k-9 not supporting it

**Comment by starsoccer** [comment]
+1 I dont know how outlook does it, but right now I have to use outlook for all my gmail accounts as the only other option is to use the gmail app natively.

**Comment by starsoccer** [comment]
> > +1 I dont know how outlook does it, but right now I have to use outlook for all my gmail accounts as the only other option is to use the gmail app natively.
> 
> Pretty sure Outlook is whitelisted by Google. Also pretty sure as the Author of the issue you can reopen this issue, but I'll tag @cketti since they could probably help.

Sadly I cant as I didnt close the issue.

**Comment by Sancus** [comment]
I mean, whether this issue is open or not, there's little we can actually do about it. It's not within our power to change Google's policies, and we don't have any special contacts there for this sort of thing. It's not a program that developers can apply to, either.

**Comment by Sancus** [comment]
> Using the same oauth keys as the Desktop app would make it work most likely since it works on the desktop client

Google has very stringent requirements to use the restricted scopes(eg full IMAP access). You have to send them a video of your app, showing all functionality, follow many guidelines, etc. And they do actively reverify every year or two. Doing what you suggest would carry a high risk of having our registration revoked at some point, potentially without warning.

**Comment by starsoccer** [comment]
> > Using the same oauth keys as the Desktop app would make it work most likely since it works on the desktop client
> 
> Google has very stringent requirements to use the restricted scopes(eg full IMAP access). You have to send them a video of your app, showing all functionality, follow many guidelines, etc. And they do actively reverify every year or two. Doing what you suggest would carry a high risk of having our registration revoked at some point, potentially without warning.
> 
> Given there are millions of Thunderbird desktop users using Google accounts, that's not an acceptable risk for us.

This logic doesnt make much sense honestly.

If thunderbird for desktop works(which it does), then I would assume they have to go through this process already. So the question then is what is the big deal with doing this process for mobile too?

**Comment by kewisch** [comment]
To my knowledge, Thunderbird Desktop was simply added, we didn't go through a process to get ourselves added. Let's revisit this when Thunderbird for Android is released and we have something to point to. This makes it easier to maybe find someone who can help us get on board.

OAuth apps are not per company, they are per application. We can't go on and use keys for the desktop app also on mobile. The right way to approach this is to see if we can find a way to get included into the program, not trying to make use of a technical loophole.

I appreciate that folks would like to make use of Google Advanced Protection together with Thunderbird!
