### ISSUE TITLE
Export/Import doesn't transfer Preview Lines setting

### ISSUE THREAD

**Issue by PhotoKevin** [thunderbird/thunderbird-android#7304]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Moto Play 2023

### Steps to reproduce

I was transferring to a new phone.
1) Export settings on old phone.
2) Copy file to new phone.
3) Import settings.
4) Enter passwords
5) Look at Unified Inbox. Old phone showed 1 line of preview, New shows 2.

### Expected behavior

The Preview lines from the old phone should have moved to the new.

This is obviously an incredibly trivial issue.

### Actual behavior

It used the default value of 2 lines for preview.

**Comment by wmontwe** [comment]
This is fixed and available in our beta version: [6.711](https://github.com/thunderbird/k-9/releases/tag/6.711)

If you are interested, you could become a [tester](https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68) to get an early look at new versions.
