### ISSUE TITLE
Update information in `AboutFragment`

### ISSUE THREAD

**Issue by wmontwe** [thunderbird/thunderbird-android#7306]
The section on libraries in the `AboutFragment` is outdated and requires an update to accurately represent the currently used dependencies. This could be an ideal chance to automate the tracking of dependencies in use.

**Comment by u3frajaeian** [comment]
I can fix this issue

**Comment by wmontwe** [comment]
This depends on #7311 where I cleaned up the AboutFragment code style. Once merged this is open for contribution.

**Comment by u3frajaeian** [comment]
Okay thanks, when it's ready for a contribution please inform me.

**Comment by Aditya13s** [comment]
Hey @wmontwe , can I work on this?

**Comment by wmontwe** [comment]
We added `dependencyGuard` that nicely reports all used dependencies by our release app. You could find them here: [releaseRuntimeClasspath.txt](https://github.com/thunderbird/thunderbird-android/blob/main/app-k9mail/dependencies/releaseRuntimeClasspath.txt). This should make the task easier.

Contributions are welcome
