### ISSUE TITLE
Target Android 13 or higher

### ISSUE THREAD

**Issue by jcperil** [thunderbird/thunderbird-android#7307]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.711

### Problem you are trying to solve

Android 13 has been here for a while and Android 14 is already on the verge of rolling out.

### Suggested solution

Can you please target Android 13 or higher?

**Comment by wmontwe** [comment]
We are working on Android 13 support and will soon publish an update.

**Comment by cketti** [comment]
I'm curious. Why are you asking us to target Android 13? It shouldn't make a difference to users.
