### ISSUE TITLE
Unable to add a GMail account: disallowed_useragent

### ISSUE THREAD

**Issue by ksiezak** [thunderbird/thunderbird-android#7316]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.771 and 6.603

### Where did you get the app from?

F-Droid

### Android version

LineageOS 20-20231015-microG-river

### Device model

Motorola Moto G7

### Steps to reproduce

1. Try to add GMail account
2. Press Sing in with Google (slightly different UI with 6.603, but it doesn't matter)

### Expected behavior

Being able to login via Google OAuth.

### Actual behavior

There is an error page form Google saying that access is denied. Request from K-9 is not compliant with Google policy regarding safe browsers.

Error 403: disallowed_useragent

**Comment by a-name-not-taken** [comment]
I'm not sure where you're getting "Sign in with Google", but the incoming server should be set up as an IMAP server with options like the attached screens hot (V6.603).

![Screenshot_20231102-154701_K-9 Mail](https://github.com/thunderbird/thunderbird-android/assets/33181918/c268c2dc-0070-4d57-820a-b226c0c67ab3)

**Comment by cketti** [comment]
It's up to Google to set the policy of which browsers it finds acceptable. If your browser doesn't work, you could try to contact Google about that. But realisticly there's not much you can do besides installing a browser they do find acceptable. It works fine with Firefox from Google Play. 

In the future please use the [forum](https://forum.k9mail.app/) for support requests.

**Comment by a-name-not-taken** [comment]
> It's up to Google to set the policy of which browsers it finds acceptable. If your browser doesn't work, you could try to contact Google about that. But realisticly there's not much you can do besides installing a browser they do find acceptable. It works fine with Firefox from Google Play.
> 
> In the future please use the [forum](https://forum.k9mail.app/) for support requests.

He's using K-9, not a browser. See the version numbers (6.771 and 6.603)

**Comment by cketti** [comment]
The OAuth 2.0 flow will open the browser to allow the user to sign in.

**Comment by a-name-not-taken** [comment]
Important detail. 🙂
