### ISSUE TITLE
k-9 regularly gets stuck for several seconds

### ISSUE THREAD

**Issue by fahim44** [thunderbird/thunderbird-android#7317]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

F-Droid

### Android version

13

### Steps to reproduce

1. configure account/accounts which have ~20,000 mails totals in the inboxes
2. open the `unified inbox` page

### Expected behavior

App loads the list smoothly

### Actual behavior

UI regularly freezes for several seconds

**Comment by kewisch** [comment]
Can you check if this is still the case in Thunderbird for Android?
