### ISSUE TITLE
My k9 does not verify Sign after download

### ISSUE THREAD

**Issue by fustalol** [thunderbird/thunderbird-android#732]
If I compile K9 and install on my phone, select the OpenKeyChain provider, and my key and then receive a Signed Mail, K9 says me that the mail is signed but he does not have the key, so i presso "lookup", it searchs the key, download It (via OpenKeyChain) and when it turn back to K9, my mail is not "signed" yet, but if i exit the mail view fragment and re-open the mail, now it see the key on OpenKeyChain and verify the Sign, just like if It returns after download It does not refresh the fragment view.
How can I fix that? please help, I'm going crazy .

**Comment by cketti** [comment]
Generally, if you want a working version of K-9 Mail build from the stable branch. Currently, PGP-related functionality in master is not working 100%.

**Comment by philipwhiuk** [comment]
@Valodim If you Lookup the public key, find one and then import it, does K-9 get an Intent back that a key was found and the activity (which it opened from a PendingIntent presumably?) was successful? If not would you accept an OpenKeychain enhancement to add it to the API?

**Comment by Valodim** [comment]
I think that info is not explicitly returned. It should be though, since it's supposed to trigger a redisplay of the message. So sure, PRs welcome. Otherwise I'll get to it somewhere down the line :+1:

**Comment by Valodim** [comment]
fix for this is part of #1299
