### ISSUE TITLE
Calendar and contacts for K-9 synced to Thunderbird on the PC

### ISSUE THREAD

**Issue by NotepadPlusUser** [thunderbird/thunderbird-android#7321]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

22631.2428

### Problem you are trying to solve

I want to sync Calendar and Contacts in Thunderbird for PC directly with Calendar and Contacts  in the new Thunderbird for Android when it appears.  

I do not want my data to go through Google in any way, and I have not the training to use CalDAV. 

### Suggested solution

1.  Add Calendar and Contacts to the new Android Thunderbird.
2.  Sync them with Calendar and Contacts in Thunderbird on the PC.

Perhaps this is already planned, but I could not find any note about it.

### Screenshots / Drawings / Technical details

I am using currently using The Bat! for Email on the PCs, Maildroid for Email on the Androids, Tutanota for synced Calendars on the PCs and Androids, Windows Contacts on the PC, and far too occasional export of Contacts from the PCs to the Androids.

I am fed up with it all.  I want a single software solution, and I would much prefer not to use Microsoft.  Surely Email+Calendar+Contacts, securely out of reach of privacy invaders, is the foundation of home computing.

**Comment by cketti** [comment]
We have no intention of adding client to client synchronization. Neither Thunderbird nor K-9 Mail are designed to work this way.
