### ISSUE TITLE
Crash when creating a new email account with a & ( Ampersand ) 

### ISSUE THREAD

**Issue by 87113** [thunderbird/thunderbird-android#7327]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.711(37011)

### Where did you get the app from?

F-Droid

### Android version

eOs 1.16 / android 12

### Device model

Fairphone 3

### Steps to reproduce

1. Go to the start screen (first launch) 
2. Click on start and type an email adresse with a & in it like you&me@email.org 
3. the app crash 

### Expected behavior

The app should go to the next screen

### Actual behavior

The app crash

Here in the file the logs from Logcat 
[k9-crash.txt](https://github.com/thunderbird/thunderbird-android/files/13270305/k9-crash.txt)

**Comment by cketti** [comment]
The crash has been fixed by #7219. The input not being recognized as valid email address should be fixed by #7340.
