### ISSUE TITLE
Use same button corner radius in Compose and XML layouts

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#7335]
The default button corner radius of the two libraries are different. Pick one and use it everywhere.

**Comment by bernhard-fp** [comment]
@cketti If you think this is an issue which could be solved by a starter, I could have a try on it.
Therefore I would need a hint of an xml view which is still in use and has the correct corner radius.
I would try to create/edit a button style to use in composables.
Please provide as many information as possible :-)

**Comment by cketti** [comment]
I was under the impression that we're using the default values of the Compose Material library. But that doesn't seem to be the case.

The Material defaults can be found here: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/Shapes.kt;l=44-58;drc=696caaf1f75d83dc5fbe4ec30434021db31668e8

Our defaults are set here: https://github.com/thunderbird/thunderbird-android/blob/2c1b6636e6cfab5eab2157f42316495651952278/core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/Shapes.kt#L12-L14

Fixing this issue should be a simple matter of changing the default value of `Shapes.small` in `core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/Shapes.kt`

**Comment by bernhard-fp** [comment]
@cketti Here is the pr: https://github.com/thunderbird/thunderbird-android/pull/7389

I found another manual set RoundedCorner but do not know if it should be changed also.

k-9/feature/account/oauth/src/main/kotlin/app/k9mail/feature/account/oauth/ui/view/SignInWithGoogleButton.kt
`Surface(
                shape = RoundedCornerShape(2.dp),
                color = Color.White,
            )`

**Comment by wmontwe** [comment]
I think the Surface shape is not needed anymore within `SignInWithGoogleButton`.
