### ISSUE TITLE
K9 mail doesn't display any attachments

### ISSUE THREAD

**Issue by gaining** [thunderbird/thunderbird-android#7356]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.711

### Where did you get the app from?

F-Droid

### Android version

13 - Trebble

### Device model

Moto g8 plus 

### Steps to reproduce

Try to open any email with an attachment, k9 mail will not display it.

### Expected behavior

Thought it would display the attachments

### Actual behavior

It does not display the attachments

**Comment by cketti** [comment]
1. Are you using IMAP or POP3?
1. Does the message view show a "Download complete message" button at the bottom of the screen? 
   1. If so, do attachments show up after the whole message has been downloaded?

**Comment by gaining** [comment]
I'm using imap, oh thanks, it shows when clicking "Download complete message". I missed it because it (the attachment) was all the way at the bottom of the email, is it possible move the attachments to the top of the email? As you can see in the screenshot, the email is very long and a lot of new users would most likely miss it.

![Screenshot_20231115-154221_K-9 Mail](https://github.com/thunderbird/thunderbird-android/assets/7690230/d165f8f5-5be8-4f8f-b610-ee41509fe649)

**Comment by cketti** [comment]
The way we display attachments, especially image attachments doesn't really work well at the top of an email.
