### ISSUE TITLE
Disable autocorrect in server settings input fields

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#7361]
Disable autocorrect for all input fields in the incoming and outgoing server settings screens.

**Comment by wmontwe** [comment]
There is a flag for doing so but according to [KeyboardOptions:autoCorrect](https://developer.android.com/reference/kotlin/androidx/compose/foundation/text/KeyboardOptions#KeyboardOptions(androidx.compose.ui.text.input.KeyboardCapitalization,kotlin.Boolean,androidx.compose.ui.text.input.KeyboardType,androidx.compose.ui.text.input.ImeAction,androidx.compose.ui.text.input.PlatformImeOptions)) it could be changed but might be ignored for [KeyboardType.Text](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/input/KeyboardType#Text())

**Comment by bernhard-fp** [comment]
Added pr https://github.com/thunderbird/thunderbird-android/pull/7372
