### ISSUE TITLE
Figure out what to do about using (exact) alarms for refreshing push connections

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#7363]
To refresh a push connection, we need to wake up the device. Currently we're using [AlarmManager.setExactAndAllowWhileIdle()](https://developer.android.com/reference/android/app/AlarmManager#setExactAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent)). We don't really need exact alarms for this. A window could work. The alarm being triggered early is fine, being triggered late isn't. Unfortunately a `AlarmManager.setWindowWithHardDeadlineAndAllowWhileIdle()` method currently doesn't exist.

The use of exact alarms is denied by default on Android 14. See https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

We'll have to figure out whether we can switch to using inexact alarms and still being woken up when the device has entered [doze mode](https://developer.android.com/training/monitoring-device-state/doze-standby#understand_doze). If not, we'll have to continue to use exact alarms and then need to add code to guide users to add the app to the exemption list.

**Comment by cketti** [comment]
It doesn't look like there's a good way around this. So the app has to ask for the permission to schedule alarms when Push is enabled.

**Comment by TrilIiard** [comment]
Would be great to get this working asap, thanks for your work so far. Shouldnt be a problem for users to grant one more permission when the App asks to.

**Comment by cketti** [comment]
We still use [`AlarmManager.setExactAndAllowWhileIdle()`](https://developer.android.com/reference/android/app/AlarmManager#setExactAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent)) and now ask for the permission to schedule exact alarms.

**Comment by Goooler** [comment]
I'm wondering if we can migrate to WorkManager to replace `setExactAndAllowWhileIdle` usages.

**Comment by cketti** [comment]
See the discussion in #5372 for why that's not an option.

**Comment by Goooler** [comment]
From my understanding, we use ForegroundService to keep the APP alive and keep TCP connections, and some periodic idle refreshing has been handled by `AlarmManager#setExactAndAllowWhileIdle`, we can replace the periodic part with WorkManager. From Android official instructions, calendar and alarm clock apps should declare `USE_EXACT_ALARM`.

> [Calendar or alarm clock apps](https://support.google.com/googleplay/android-developer/answer/12253906?hl=zh-cn#exact_alarm_preview) need to send calendar reminders, wake-up alarms, or alerts when the app is no longer running. These apps can request the [USE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission?hl=zh-cn#USE_EXACT_ALARM) normal permission. The USE_EXACT_ALARM permission will be granted on install, and apps holding this permission will be able to schedule exact alarms just like apps with the [SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission?hl=zh-cn#SCHEDULE_EXACT_ALARM) permission.

**Comment by cketti** [comment]
- WorkManager doesn't do exact alarms. If it did, we'd still need to use the `SCHEDULE_EXACT_ALARM` mechanism.
- The [`USE_EXACT_ALARM` documentation](https://developer.android.com/reference/android/Manifest.permission#USE_EXACT_ALARM) is very explicit:
   > **This is only intended for use by apps that rely on exact alarms for their core functionality.** You should continue using `SCHEDULE_EXACT_ALARM` if your app needs exact alarms for a secondary feature that users may or may not use within your app.
