### ISSUE TITLE
Enabling Push on Android 14 crashes v6.712

### ISSUE THREAD

**Issue by Maetts** [thunderbird/thunderbird-android#7395]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.712

### Where did you get the app from?

Other

### Android version

Android 14

### Device model

Pixel 8 Pro

### Steps to reproduce

Open App
Wait for referesh Outlook, Google, other imap account 
Refresh takes about 5 - 10 sec
App crashes

### Expected behavior

No crash and running app

### Actual behavior

Open App
Wait for referesh Outlook, Google, other imap account 
Refresh takes about 5 - 10 sec
App crashes

**Comment by Maetts** [comment]
What sensitive data is in the log? Should I remove something of it?

**Comment by cketti** [comment]
Let's start with the stack trace and see if that's enough to find out what's going on. It should look similar to what you can see e.g. here: #7392 (under "Logs").

If the error message contains sensitive data, feel free to redact it.

**Comment by Maetts** [comment]
--------- beginning of crash
11-30 21:14:37.982  9569  9812 E AndroidRuntime: FATAL EXCEPTION: ImapFolderPusher-Microsoft Account
11-30 21:14:37.982  9569  9812 E AndroidRuntime: Process: com.fsck.k9, PID: 9569
11-30 21:14:37.982  9569  9812 E AndroidRuntime: java.lang.SecurityException: Caller com.fsck.k9 needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3041)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3024)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2966)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:311)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at android.app.AlarmManager.setImpl(AlarmManager.java:1084)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at android.app.AlarmManager.setImpl(AlarmManager.java:1044)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at android.app.AlarmManager.setExactAndAllowWhileIdle(AlarmManager.java:1312)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.helper.AlarmManagerCompat$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.helper.AlarmManagerCompat.scheduleAlarm(AlarmManagerCompat.kt:10)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backends.AndroidAlarmManager.setAlarm(AndroidAlarmManager.kt:62)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.BackendIdleRefreshManager.setAlarm(BackendIdleRefreshManager.kt:66)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.BackendIdleRefreshManager.onTimeout(BackendIdleRefreshManager.kt:93)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.BackendIdleRefreshManager.resetTimers(BackendIdleRefreshManager.kt:42)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.ImapBackendPusher.onPushEvent(ImapBackendPusher.kt:187)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.ImapFolderPusher.performInitialSync(ImapFolderPusher.kt:99)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.ImapFolderPusher.runPushLoop(ImapFolderPusher.kt:59)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.ImapFolderPusher.access$runPushLoop(ImapFolderPusher.kt:15)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.ImapFolderPusher$start$1.invoke(ImapFolderPusher.kt:36)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at com.fsck.k9.backend.imap.ImapFolderPusher$start$1.invoke(ImapFolderPusher.kt:33)
11-30 21:14:37.982  9569  9812 E AndroidRuntime: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by cketti** [comment]
Thanks. 

The problem is caused by the app trying to use exact alarms when Push is enabled. Android 14 requires the user to manually grant permission for this. We did have on our radar that we need to do additional work to guide users to grant that permission. However, I failed to notice that the app will crash (as opposed to Push not working) in its current state.

You should be able to avoid the crash (and make Push work) by allowing the app to use "Alarms & Reminders" in Android's *app info* screen for K-9 Mail.

**Comment by Maetts** [comment]
Allright, I was able to set "Allow setting alarms and reminders" manually and now it workes again. As you described. Thanks!
