### ISSUE TITLE
Add support for IOS

### ISSUE THREAD

**Issue by kacperpaczos** [thunderbird/thunderbird-android#7422]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

16

### Problem you are trying to solve

I need K9 on IOS

### Suggested solution

Make it on this platform

**Comment by cketti** [comment]
There will be a Thunderbird for iOS. Some early information can be found here: https://blog.thunderbird.net/2023/05/thunderbird-is-thriving-our-2022-financial-report/

However, it won't be based on K-9 Mail's code base.
