### ISSUE TITLE
Ignore "fts-flatcurve" folder

### ISSUE THREAD

**Issue by epsilon-0** [thunderbird/thunderbird-android#7439]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

When using self hosted dovecot as imap provider and with the fts-flatcurve setup for server side searches, K-9 pulls in all these folders, which only contain indexing data and pollute the folders list.

### Suggested solution

K-9 should ignore fts-flatcurve folders or allow ignoring folders based on a pattern (like [mbsync](https://isync.sourceforge.io/mbsync.html) does with `![pattern]`).

**Comment by cketti** [comment]
There's a good chance your server is misconfigured if a directory containing index files is exposed via IMAP.

K-9 Mail already supports a (admittedly not great) way to hide folders. See https://docs.k9mail.app/en/6.400/settings/folder_classes/
(We'll eventually get rid of folder classes and make it easier to hide folders. See #2669.)

I don't see us adding a feature to hide folders matching a pattern.
