### ISSUE TITLE
F-droid is reccomending older versions of the app.

### ISSUE THREAD

**Issue by LantashTheTokra** [thunderbird/thunderbird-android#7441]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.713, 6.712

### Where did you get the app from?

F-Droid

### Android version

GrapheneOS Android 14

### Device model

Google Pixel 7

### Steps to reproduce

1. Download an F-droid client.
2. Search for K-9 Mail.
3. The F-droid suggested version is an older version.

### Expected behavior

The newest version is the suggested version. (Screenshot from Tuta Mail page)
![Screenshot_20231218-132648](https://github.com/thunderbird/thunderbird-android/assets/84555704/bd498993-616b-49d4-863f-d0dcb344f2d2)

### Actual behavior

The older version is the suggested version.
![Screenshot_20231218-131820](https://github.com/thunderbird/thunderbird-android/assets/84555704/076a8b92-ad42-4e92-b336-bf4f5515cde1)

### Logs

N/A

**Comment by cketti** [comment]
K-9 Mail 6.603 is the latest stable version. K-9 Mail 6.7xx are beta versions.

**Comment by LantashTheTokra** [comment]
> K-9 Mail 6.603 is the latest stable version. K-9 Mail 6.7xx are beta versions.
Could you add "beta" to the end of the version name to make this more clear for new users? Exampke:
![Screenshot_20231218-133524](https://github.com/thunderbird/thunderbird-android/assets/84555704/7e6318cf-392a-467b-bc4a-860e427adb3d)
