### ISSUE TITLE
Poll frequency "When received"

### ISSUE THREAD

**Issue by FMorschel** [thunderbird/thunderbird-android#7442]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.713

### Problem you are trying to solve

With Gmail and Samsung Email (and others), there is an option to receive notifications (when the server has that ability - e.g. Gmail, Outlook, etc) to get the notification of the email when it arrives on the server.

I'd like to propose that same ability on Thunderbird for Android.

### Suggested solution

Samsung mail sync schedule has an example with an option "Auto (when received)":

Similar to the "Allow immediate server notifications when new messages arrive" check on the Thunderbird Desktop App.

Both are represented in the screenshots below.

### Screenshots / Drawings / Technical details

Screenshot examples:

<img src="https://github.com/thunderbird/thunderbird-android/assets/52160996/8f7c8441-47c9-4eb5-be90-919c00fe368a" width="400"/>

![Thunderbird Desktop app with server settings](https://github.com/thunderbird/thunderbird-android/assets/52160996/d619bb7f-f629-4947-a842-a7c912310d7f)

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/how-to-configure-push/1102

**Comment by FMorschel** [comment]
Thanks a lot! So my question here would be: Shouldn't this be reviewed UI/UX-wise? 

I as an end user (who even has some background to know how to look/ask for things) had to come all the way here because I didn't know that this option was named "Push folders" (I had no idea what that meant before this answer). 

Could this be reviewed to help users who are not that familiar with this kind of email configuration? 

- I suggest making it default for starters;
- Maybe to have an option to configure this globally;
- Make this "folder approach" configuration under advanced (right below);

**Comment by cketti** [comment]
Absolutely, the current UX isn't great. We're working on getting rid of folder classes in general (see #2669). 

Once that's done, we can think about making Push the default. It has some drawbacks when people want to sync a lot of folders. So we probably need to display a warning message when users try to sync "too many" folders via Push.

Closing this issue because we don't need it to keep track of the work.
