### ISSUE TITLE
Automatic O-Auth detection is missing for some alternative Outlook TLDs

### ISSUE THREAD

**Issue by ChiefArug** [thunderbird/thunderbird-android#7454]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

8.1.0 (Color OS 5.2, which came with the phone)

### Device model

OPPO A7

### Steps to reproduce

Upon initial setup, or in the add account menu, enter an outlook.co.nz domain email address. This may happen with other outlook tlds, but I do not have any others to test with. A list of some of them and the link to get one is in the answers here: https://answers.microsoft.com/en-us/outlook_com/forum/all/get-a-country-specific-outlook-email-address-like/6dcb9569-cf7b-41e4-9c78-5f25f9fc43bb

### Expected behavior

It redirects to Microsoft O-Auth, like an outlook.com email address.

### Actual behavior

It asks for a password, then opens the 'is this an IMAP or POP3 account' question. 

### Logs

I exported the logs from Settings —> General Settings —> Debugging but they were empty 🤷‍♂️

**Comment by ChiefArug** [comment]
Did some searching in the thunderbird org, at a guess this might be caused by outlook.co.nz being missing in this file:
https://github.com/thunderbird/autoconfig/blob/257d706e56c915fd9003922437b21cf452683854/ispdb/hotmail.com.xml

**Comment by cketti** [comment]
K-9 Mail 6.603 doesn't support autoconfig. See https://forum.k9mail.app/t/how-do-i-add-an-office365-account/5072

**Comment by ChiefArug** [comment]
Thats weird, because i have an outlook.com address attached to the same account and if I use that to sign in it redirects me to Microsoft O-Auth, but my outlook.co.nz address doesn't redirect me there.

**Comment by ChiefArug** [comment]
I still don't think this is resolved as the behaviour for outlook.com emails is different to outlook.co.nz emails, despite being the same provider and even account.

**Comment by ChiefArug** [comment]
This has been fixed at some point, my outlook.co.nz address now redirects to OAuth to sign in.
