### ISSUE TITLE
Exchange support

### ISSUE THREAD

**Issue by dot166** [thunderbird/thunderbird-android#7455]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.713

### Problem you are trying to solve

The place I work in uses Microsoft Exchange for eMail

### Suggested solution

I would like k9 mail to support Microsoft exchange

**Comment by kewisch** [comment]
I'd love to see this as well! Could you cast your vote on https://connect.mozilla.org/t5/ideas/support-exchange-web-services-protocol-in-k-9-mail/idi-p/31613 ? We're moving to capture product ideas such as this one over on connect, so I'm going to close this issue in favor of that thread. Thank you for taking the time to file this issue.

**Comment by Queuecumber** [comment]
According to this video the answer is that it's happening: https://youtu.be/7jNV1J2pdPc?si=hc-qYS-cxMSh78sa I'm curious if there is a communication issue between teams going on here
