### ISSUE TITLE
Pictures are not displayed properly

### ISSUE THREAD

**Issue by maprix** [thunderbird/thunderbird-android#7459]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

14, build UQ1A.231205.015

### Device model

Pixel 6 Pro 

### Steps to reproduce

1. Open an e-mail containing pictures.
2. Some pictures are not displayed properly but others are. See screenshot. Flix logo is displayed but QR code not.
![Screenshot_20231225-115035](https://github.com/thunderbird/thunderbird-android/assets/15447261/54a5c065-5443-4384-b982-8ba9fc4286b4)

### Expected behavior

All pictures must be displayed.

### Actual behavior

Some pictures are not displayed properly but others are. See screenshot. Flix logo is displayed but QR code not.
![Screenshot_20231225-115035](https://github.com/thunderbird/thunderbird-android/assets/15447261/c4703fe8-b99f-4b47-8a55-e9a37769395b)

**Comment by njeyaakili** [comment]
as noted by the line included at the bottom of your screenshot, the complete message hasn't been downloaded. without the full message it's a tad hard to do complete/accurate rendering.

try downloading the full message and see if you still have an issue.

also note, depending on settings, you may need to explicitly load remote images.

**Comment by cketti** [comment]
In the future please use the [forum](https://forum.k9mail.app/) for support requests.
