### ISSUE TITLE
In the mail notifications some text fields are hardcoded to black

### ISSUE THREAD

**Issue by hsiktas** [thunderbird/thunderbird-android#746]
While the rest of the notification fonts adjust to the current theme the recipient or the subject is always displayed in black. This ruins the readability on dark system themes.
Examples are attached.

![screenshot_2015-08-12-12-28-12](https://cloud.githubusercontent.com/assets/4571159/9222013/c0874840-40ee-11e5-8863-a66ff2f30b6d.png)
![screenshot_2015-08-12-12-27-51](https://cloud.githubusercontent.com/assets/4571159/9222014/c09c6414-40ee-11e5-819a-e08746a21b09.png)
![screenshot_2015-08-12-12-27-05](https://cloud.githubusercontent.com/assets/4571159/9222016/c0bf2fee-40ee-11e5-9b78-b203e1fc6af5.png)
![screenshot_2015-08-12-12-26-22](https://cloud.githubusercontent.com/assets/4571159/9222015/c0b0f690-40ee-11e5-991b-482a781c9c53.png)

**Comment by maniac103** [comment]
The emphasis style likely needs adaptions for L. Something like this: https://github.com/maniac103/HoloIRC/commit/d16ede4b14c25ede2eb025f31c3016fc2dcba778

**Comment by philipwhiuk** [comment]
I think the Material thing change @maniac103 mentions is probably relevant for the material_design work. But https://github.com/philipwhiuk/k-9/commit/231d60fc6da6c9be4492b69dc1229e8120152cf0 should fix this bug for dark themes. I don't have a device at the moment so I can't test this though.
