### ISSUE TITLE
Reduce The Complexity Of Compose UI Components Using Groups

### ISSUE THREAD

**Issue by Mukuljangir372** [thunderbird/thunderbird-android#7460]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.714-SNAPSHOT

### Problem you are trying to solve

**Issues With Compose UI components Hierarchy**
Too many files (compose UI components) makes very large hierarchy that is difficult to scale and read.

### Suggested solution

To Reduce the complexity of composable components files, We should group them using `Objects` i.e all the text related composables comes under Texts `Object` to reduce the complexity.

### Screenshots / Drawings / Technical details

<img width="370" alt="Screenshot 2023-12-27 at 6 36 44 PM" src="https://github.com/thunderbird/thunderbird-android/assets/64830777/378c75ad-29f1-4967-92c7-759b29dc9f54">

**Comment by malirauf** [comment]
Hey, I want to work on this.

**Comment by wmontwe** [comment]
> To Reduce the complexity of composable components files, We should group them using Objects i.e all the text related composables comes under Texts Object to reduce the complexity.

What do you mean with `Objects`? Put all text related code in one file or something different?

**Comment by wmontwe** [comment]
Thank you for your suggestion, we'll stick to the current approach.
