### ISSUE TITLE
Continue crash

### ISSUE THREAD

**Issue by Fedix0** [thunderbird/thunderbird-android#7465]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 7a

### Steps to reproduce

1.open k-9
2. Select multiple mails
3. Click "mark as read"
4. The app crashes

Or

1.open app
2. Open one mail
3. Swipe to the next or previous mail
4. Repeat 3 times
5. The app crashes

### Expected behavior

The app doesn't crashes 

### Actual behavior

Unstable app, continuous crashes 

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/13798314/k9mail-logs.txt)

**Comment by cketti** [comment]
The debug log shows the same crash as reported in issue #7395. See https://github.com/thunderbird/thunderbird-android/issues/7395#issuecomment-1836106195 for how to work around it.

However, this should only be an issue in K-9 Mail 6.712, not in K-9 Mail 6.603 (or 6.713). Can you double check the app version under *Settings → About*.

**Comment by Fedix0** [comment]
I confirm my app version is 6.603.
I add that the app seems to crash after few seconds when open, regardless of the actions i do.
I tried to apply the suggested workaround but i don't see the authorization in the info section of K-9, i only see notifications and contacts permissions. 
![Screenshot_20231230-184017](https://github.com/thunderbird/thunderbird-android/assets/111634068/0e83cbe0-eba3-46dd-a7de-0d34bffd71df)

**Comment by cketti** [comment]
"Alarms & Reminders" can be found at the bottom of Android's app info screen for K-9 Mail (not under "Permissions").

I've tested K-9 Mail 6.603 on Android 14 and the permission to set exact alarms was granted automatically. So either you manually disabled this or something odd is going on with your device/Android version. 

In either case, there's nothing we can do about it in K-9 Mail 6.6xx. We'll deal with this issue in the next K-9 Mail version (see #7363).
