### ISSUE TITLE
Auto refresh when starting the app

### ISSUE THREAD

**Issue by K0-RR** [thunderbird/thunderbird-android#7479]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.713

### Problem you are trying to solve

Most of the time I open the app I need that one fresh email with an account confirmation link or code.
That means no matter to how frequent the background refresh is set, I still need to refresh manually.
Other email clients will pull content when the app starts.

### Suggested solution

like the title :)

**Comment by rafaelazvdo** [comment]
I sent a similar request a few months ago and they didn't even respond.  #7257

**Comment by RDKRACZ** [comment]
Yeah, it's basically the same, I tried to look for duplicates but [Github's search sucks](https://github.com/thunderbird/thunderbird-android/issues?q=Auto+sync+is%3Aopen)... 
Sad they didn't even respond. I really thought that after Thunderbird have taken over K-9 they would speed up the development etc.

**Comment by kewisch** [comment]
We're in this together, with Thunderbird taking over we won't be able to drastically speed up development even with a slightly growing team. I can confirm though this would be great to have in Thunderbird for Android, if someone has time to look.
 
I'm going to close this one in favor of #7257, thank you for taking the time to report this!
