### ISSUE TITLE
The spam folder doesn't refresh automatically (in the background) 

### ISSUE THREAD

**Issue by K0-RR** [thunderbird/thunderbird-android#7480]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.713

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Motorola Edge 30 Neo

### Steps to reproduce

Kinda hard to reproduce on request - You need to receive some spam and check it in some other client. Then wait till the next refresh in K-9 and notice that the inbox was updated but SPAM not.

### Expected behavior

SPAM should refresh like the inbox folder

### Actual behavior

Same as the title

**Comment by cketti** [comment]
You need to configure your spam folder to be checked automatically. See https://docs.k9mail.app/en/6.400/settings/folder_classes/

If you have further questions, please use the [support forum](https://forum.k9mail.app/).
