### ISSUE TITLE
K9mail 6.714 cannot be installed

### ISSUE THREAD

**Issue by HelmutL** [thunderbird/thunderbird-android#7481]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.714 

### Where did you get the app from?

Google Play

### Android version

10

### Device model

Honor view 20

### Steps to reproduce

Update via Google play store or manual download of the apk

### Expected behavior

K9mail 6.713 should be able to update to version 6.714

### Actual behavior

Update/installation fails

**Comment by cketti** [comment]
Android only allows app updates when the new APK is signed using the same key as the installed APK. F-Droid is using a different signing key. So you won't be able to update an installation from F-Droid with an update from Google Play or GitHub.

In the future, please include the exact error message(s) when reporting a bug. Simply stating that "it's not working" is usually not enough to guess what's going wrong.

**Comment by HelmutL** [comment]
After de-installation and new install from Google Play it is running again.

BTW:
is the signing key of the versions in GitHub and F-Droid the same?

Thanks

**Comment by cketti** [comment]
No, F-Droid is using their own signing key. The APKs from GitHub and Google Play are signed using the same key.
