### ISSUE TITLE
Annoying prompt for access to contacts

### ISSUE THREAD

**Issue by ninernet** [thunderbird/thunderbird-android#7485]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

I am not using a custom ROM.

### Device model

Motorola G Pure

### Steps to reproduce

In numerous different situations I am prompted to allow K9 access to my contacts. There doesn't seem to be a way to stop these prompts by saying "never". The only way an app will ever get access to my contacts is if it constantly prompts me, and one day it catches me off guard. Perhaps that is K9's/Thunderbird's/Mozilla's intent, but I sure hope not.

### Expected behavior

No means no. Once I say no, that should mean no forever unless there is an option under "settings" that allows me to change my mind. I've looked for that option and I don't see it.

### Actual behavior

I am constantly badgered by K9 to allow access to my contacts.

### Logs

I don't think log are really necessary. Surely this is just an oversight.

Android 12.

**Comment by cketti** [comment]
We already changed the way we're asking for permissions in the beta version. See also https://blog.thunderbird.net/2023/12/thunderbird-for-android-k-9-mail-november-december-2023-progress-report/

**Comment by ninernet** [comment]
Thanks. Good to know. Appreciate the change.
