### ISSUE TITLE
Firefox opens in background

### ISSUE THREAD

**Issue by DecoderBox** [thunderbird/thunderbird-android#7487]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

None

### Android version

6.01

### Device model

Samsung Galaxy J5

### Steps to reproduce

1. Open K-9 Mail
2. Read mail
3. Close K-9 Mail
4. Open Samsung phone Smart Manager
5. Go to RAM
6. Expand Others on Background Apps

### Expected behavior

Won't open background app.

### Actual behavior

Open Firefox browser in background.

**Comment by DecoderBox** [comment]
1. Open K-9 Mail
2. Read mail
3. Close K-9 Mail
4. On Samsung Galaxy J5 phone, open Smart Manager
5. Tap on RAM
6. Tap Others, then you'll see that Firefox opens in the background

**Comment by cketti** [comment]
That's just repeating what you already wrote. I don't see how Smart Manager opening Firefox is related to K-9 Mail.

**Comment by DecoderBox** [comment]
> That's just repeating what you already wrote.
I repeated the details because you don't understand. 

> I don't see how Smart Manager opening Firefox is related to K-9 Mail.
If I didn't open K-9 Mail, Firefox wouldn't open in the background. And last time I checked, Mozilla who owns Firefox, also owns K-9 Mail.

Closing an issue without giving another chance to comment is considered rude.
