### ISSUE TITLE
Mail status not synced

### ISSUE THREAD

**Issue by Ram-Z** [thunderbird/thunderbird-android#7504]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.707

### Where did you get the app from?

F-Droid

### Android version

GrapheneOS Android 14

### Device model

Pixel 5

### Steps to reproduce

1. Sync mail
2. Change the status of a message
   - mark as starred
   - mark as read
   - ...
3. Sync again

### Expected behavior

The status of the message should not revert to what it was on the server and save the status set on K9 instead.

### Actual behavior

Status is reset to server value, i.e. read might go back to unread, starred might reset to unstarred...

Note that this does not happen when K9 has just been started, i.e. closed in app drawer then started fresh. After a while however it will never sync the status again.

### Logs

Here are two logs, the buggy behaviour and the working behaviour after a fresh start of K9.
* Buggy behaviour: [k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/13931149/k9mail-logs.txt)
* Worknig behaviour: [k9mail-logs-works.txt](https://github.com/thunderbird/thunderbird-android/files/13931159/k9mail-logs-works.txt)
  * (this actually also contains the buggy behaviour at the beginning of log)

**Comment by Ram-Z** [comment]
This is similar (or maybe even identical) to https://github.com/thunderbird/thunderbird-android/issues/5869.

Same as https://github.com/thunderbird/thunderbird-android/issues/5869#issuecomment-1139344858, this is with a Mailfence account, I do not have another account to try this with.

I've had this issue now for several years.

**Comment by cketti** [comment]
This seems to be a server bug.

K-9 Mail sends a command to mark some messages as flagged:
```text
32 UID STORE 31484,31502,31458:31469,31471:31477,31489:31492,31494:31495 +FLAGS.SILENT (\Flagged)
```

The server acknowledges the command with a positive response.
```
32 OK STORE Completed
```
At this point the messages should be marked as flagged on the server. However, fetching the flags right after reveals that's not the case.

Please contact your email provider to let them know their server is misbehaving.

**Comment by Ram-Z** [comment]
Thanks for having a look, I will forward this to my email provider.

Any idea why it misbehaves only after K9 has been running a while, and not straight after it is started?

**Comment by Ram-Z** [comment]
@cketti I've created a new [log](https://github.com/thunderbird/thunderbird-android/files/14056011/k9mail-logs2.txt) in a folder with a single email, which removes a lot of the noise. 

Here's an extract that seems a bit odd to me:
```
01-25 16:56:31.676  3125  3172 V RealImapConnection: conn138959173>>> 41 UID STORE 1 -FLAGS.SILENT (\Flagged)
01-25 16:56:31.824  3125  3172 V ImapResponseParser: conn138959173<<<#41# [OK, STORE Completed]
[...]
01-25 16:56:32.643  3125  3172 V RealImapConnection: conn12357675>>> 34 UID FETCH 1 (UID FLAGS)
01-25 16:56:32.728  3125  3172 V RealImapConnection: conn12357675<<<#null# [1, FETCH, [FLAGS, [\Flagged, \Seen], UID, 1]]
01-25 16:56:32.729  3125  3172 V RealImapConnection: conn12357675<<<#34# [OK, FETCH Completed]
```

You'll note that the IMAP tags 41 and 34 are out of order.

**Comment by cketti** [comment]
We start tags with 1 for every connection. These are two different connections (`conn138959173` vs. `conn12357675`).

**Comment by Ram-Z** [comment]
OK, I did see that there were different connections, but thought that tags would still need to be unique, it seems not.

Anyway, I've written a quick python script to try to reproduce this and I see the same behaviour when using 2 clients. It works fine with a single client.

Is it possible to run k9 with a single connection? I could not find a relevant setting.

<details><summary>Python script (click to expand)</summary>

```python
#!/usr/bin/env python3

import sys
from imaplib import IMAP4_SSL

# Update these with valid values
USER = "USER"
PASS = "PASSWORD"
MBOX = "test-sync"

HOST = "imap.mailfence.com"

# redirect stdout to stderr to print in order
sys.stdout = sys.stderr

def init(client):
    client.debug = 4
    client.login(USER, PASS)
    client.select(MBOX)

def run_test(num_clients = 2):
    try:
        print(f"##### init {num_clients} imap clients ####")
        c1 = IMAP4_SSL(HOST)
        init(c1)

        if num_clients == 1:
            c2 = c1
        elif num_clients == 2:
            c2 = IMAP4_SSL(HOST)
            init(c2)
        else:
            raise ValueError("num_clients must be 1 or 2")

        print("##### init complete ####")

        print("##### fetch state of message in both clients ####")
        _, c1d1 = c1.fetch("1:1", "(UID FLAGS)")
        _, c2d1 = c2.fetch("1:1", "(UID FLAGS)")
        print(f"##### c1: {c1d1} ####")
        print(f"##### c2: {c2d1} ####")

        print("##### flag/unflag message in c1 ####")
        flagged =  b"Flagged" in c1d1[0]
        if flagged:
            c1.store("1", "-FLAGS", '\\Flagged')
        else:
            c1.store("1", "+FLAGS", '\\Flagged')

        # adding a noop here makes c2 receive the correct flag below
        # c2.noop()

        print("##### fetch state of message in both clients ####")
        c1t1, c1d1 = c1.fetch("1:1", "(UID FLAGS)")
        c2t1, c2d1 = c2.fetch("1:1", "(UID FLAGS)")
        print(f"##### c1: {c1t1} {c1d1} ####")
        print(f"##### c2: {c2t1} {c2d1} ####")
        if c1d1 != c2d1:
            print("######## Flags DO NOT match #######")
    finally:
        c1.shutdown()
        if c1 != c2:
            c2.shutdown()

# print("#####################################################")
# print("##### Run test with 1 client, works as expected #####")
# print("#####################################################")
# run_test(num_clients=1)

print("################################################################################")
print("##### Run test with 2 clients, second client does not receive updated tags #####")
print("################################################################################")
run_test(num_clients=2)
```

</details>

```
<snip>
##### fetch state of message in both clients ####
  55:25.80 > b'DICL3 FETCH 1:1 (UID FLAGS)'
  55:25.88 < b'* 1 FETCH (FLAGS (\\Flagged \\Seen) UID 1)'
  55:25.88 < b'DICL3 OK FETCH Completed'
  55:25.88 > b'IMNG3 FETCH 1:1 (UID FLAGS)'
  55:25.95 < b'* 1 FETCH (FLAGS (\\Flagged \\Seen) UID 1)'
  55:25.95 < b'IMNG3 OK FETCH Completed'
##### c1: [b'1 (FLAGS (\\Flagged \\Seen) UID 1)'] ####
##### c2: [b'1 (FLAGS (\\Flagged \\Seen) UID 1)'] ####
##### flag or unflag message in c1 ####
  55:25.95 > b'DICL4 STORE 1 -FLAGS (\\Flagged)'
  55:26.03 < b'* 1 FETCH (FLAGS (\\Seen))'
  55:26.03 < b'DICL4 OK STORE Completed'
##### fetch state of message in both clients ####
  55:26.03 > b'DICL5 FETCH 1:1 (UID FLAGS)'
  55:26.11 < b'* 1 FETCH (FLAGS (\\Seen) UID 1)'
  55:26.15 < b'DICL5 OK FETCH Completed'
  55:26.15 > b'IMNG4 FETCH 1:1 (UID FLAGS)'
  55:26.22 < b'* 1 FETCH (FLAGS (\\Flagged \\Seen) UID 1)'
  55:26.22 < b'IMNG4 OK FETCH Completed'
##### c1: OK [b'1 (FLAGS (\\Seen) UID 1)'] ####
##### c2: OK [b'1 (FLAGS (\\Flagged \\Seen) UID 1)'] ####
######## Flags DO NOT match #######
```

The STORE will eventually propagate and subsequent runs of this script will first see the message as flagged then not-flagged. This is different from how k9 behaves, where I never see the changes on the server.

If I insert a `c2.noop` between setting the flag in c1 and fetching the flag in c2 (see script), the expected results are returned:

```
##### flag/unflag message in c1 ####
  01:52.56 > b'OPCM4 STORE 1 +FLAGS (\\Flagged)'
  01:52.65 < b'* 1 FETCH (FLAGS (\\Flagged \\Seen))'
  01:52.65 < b'OPCM4 OK STORE Completed'
  01:52.65 untagged responses dump:EXISTS: [b'1']
		RECENT: [b'0']
		UIDVALIDITY: [b'1460005536']
		UIDNEXT: [b'2']
		FLAGS: [b'(\\Deleted \\Seen \\Answered \\Recent \\Draft)']
		PERMANENTFLAGS: [b'(\\Deleted \\Seen \\Answered \\Flagged \\Draft \\*)']
		READ-WRITE: [b'']
  01:52.65 > b'IGGA4 NOOP'
  01:52.72 < b'* 1 EXISTS'
  01:52.72 < b'* 1 FETCH (FLAGS (\\Flagged \\Seen))'
  01:52.72 < b'IGGA4 OK NOOP completed'
##### fetch state of message in both clients ####
  01:52.72 > b'OPCM5 FETCH 1:1 (UID FLAGS)'
  01:52.80 < b'* 1 FETCH (FLAGS (\\Flagged \\Seen) UID 1)'
  01:52.80 < b'OPCM5 OK FETCH Completed'
  01:52.80 > b'IGGA5 FETCH 1:1 (UID FLAGS)'
  01:52.88 < b'* 1 FETCH (FLAGS (\\Flagged \\Seen) UID 1)'
  01:52.88 < b'IGGA5 OK FETCH Completed'
##### c1: OK [b'1 (FLAGS (\\Flagged \\Seen) UID 1)'] ####
##### c2: OK [b'1 (FLAGS (\\Flagged \\Seen))', b'1 (FLAGS (\\Flagged \\Seen) UID 1)'] ####
```

**Comment by cketti** [comment]
> Is it possible to run k9 with a single connection? I could not find a relevant setting.

There's no such setting. 

The initial log from K-9 Mail shows that the changes weren't visible in the same connection that issued the UID STORE command. So apparently only using one connection doesn't always help. In any case, this is a server bug that should be fixed. Not something to be worked around by the client.
