### ISSUE TITLE
Unread widget missing

### ISSUE THREAD

**Issue by HagenTronje** [thunderbird/thunderbird-android#7505]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.714

### Where did you get the app from?

Other

### Android version

14

### Device model

Samsung Galaxy Tab S9+

### Steps to reproduce

I successfully added my GMail account to K-9 Mail and wanted to add an "Unread widget" for this account to my start screen. The widget selection dialog only offers a  "Message list"-widget and an "Accounts"-widget.

However I do already have two "Unread widgets" on my start screen for accounts I created using version 6.713 (or even earlier).

### Expected behavior

The widget selection dialog should offer a  "Message list"-widget, an "Accounts"-widget plus an "Unread"-widget.

### Actual behavior

The widget selection dialog only offers a  "Message list"-widget and an "Accounts"-widget.

### Logs

Android device currently not available.

**Comment by HagenTronje** [comment]
Today I installed K-9 Mail v6.715 (from https://github.com/thunderbird/thunderbird-android/releases/tag/6.715) on

- Samsung Tab S9+
- Google Pixel 7a

Both devices run Android 14.

The Pixel 7a offers an "Unread"-widget.

The Samsung Tab S9+ does **not** right away offer an "Unread"-widget. However if I use the search function while in the widget list and search for "K-9 un" I'm offered  an "Unread"-widget and can place it successfully on my start screen.

Looks like the problem is related to Samsungs Android 14.

**Comment by cketti** [comment]
Please report this as a bug to Samsung.
