### ISSUE TITLE
[Account setup] Always display progress indicator in transient screens

### ISSUE THREAD

**Issue by ByteHamster** [thunderbird/thunderbird-android#7525]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.714

### Problem you are trying to solve

Now that I didn't do any code contributions for K-9 for quite a while, I just switched from an old `debug` version to the official beta version on Google Play. So far, the new account setup looks quite nice. I'm sure it will help many new users. However, I noticed a few problems that I will be creating issues now.

When creating a new account, after typing the IMAP server details and pressing "ok", I got to a screen with the full-screen message "inbox server settings are valid". This message disappeared after a few seconds. However, it was displayed long enough that it confused me quite a bit. I expected a "next" button or something similar. I ended up clicking the screen randomly (the icon, the location where I would expect a "next" button, etc). While this confusion didn't last long (screen gets redirected soon, at least if you don't end up pressing the back button), I think this short confusion is not a nice first impression to the app for new users.

### Suggested solution

Keep showing the progress indicator below the "inbox server settings are valid" message. This indicates that the app is still doing something (eg redirecting to the next settings page) and that I don't need to click anything to continue.

**Comment by cketti** [comment]
In a design meeting we've decided to continue showing the progress indicator along with the success message. That will hopefully make it clear that no user input is expected on this transient screen.

We'll also experiment with reducing the timeouts so the screen isn't displayed for too long, but also not so short that it appears like a flash.
