### ISSUE TITLE
Cannot add a attachments as popup "Choose an action" is empty

### ISSUE THREAD

**Issue by bokysan** [thunderbird/thunderbird-android#7535]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Onyx Tab Ultra C Pro

### Steps to reproduce

 1. Stat writing a message
 2. Click on attach icon

### Expected behavior

You can attach a file.

### Actual behavior

A popup opens, which shows "Choose an action" title, but nothing can be selected / chosen. Only possible action is clicking on big X in the corner.

Might be related to #7423.

![PSX_20240120_102710](https://github.com/thunderbird/thunderbird-android/assets/4567693/af38a3b6-f831-4d6d-a8bc-d460f6a433aa)

Do note that:
- K-9 is running from the Work profile
- Work profile was created using [Shelter](https://f-droid.org/packages/net.typeblog.shelter/)
- K-9 was installed in the Private profile and copied to Work profile via Shelter
- The same issue happens either when composing a new or replying to an existing email

**Comment by cketti** [comment]
Does the app work as expected in the personal profile? If so, it's probably a problem with how the work profile is configured. It doesn't seem to be a general Shelter problem. Because it works fine for me.

If the problem is also present in the personal profile, it's most likely a problem with the Android version on your device. In that case, please contact the vendor (or developer of the custom ROM, if you're using one).

**Comment by bokysan** [comment]
It works as expected in the personal profile. Clicking on the attach icon brings up file picker.

**Comment by bokysan** [comment]
I've tried uploading a file from another app (Slack) and it works as expected.

**Comment by cketti** [comment]
> It works as expected in the personal profile. Clicking on the attach icon brings up file picker.

In that case it's probably a Shelter configuration issue. Please contact the author of that app.
