### ISSUE TITLE
[Onboarding] Change text in welcome screen

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#7541]
Change the text in the welcome screen to better describe the current state of the app rather than an aspirational goal.

Currently the text reads: 
> Welcome to K-9 Mail, the Android email client designed for enhanced security, easy customization, and seamless management of all your email accounts.

![image](https://github.com/thunderbird/thunderbird-android/assets/218061/c0263257-8cf4-4a8c-8009-fb29690e7fa8)

**Comment by kewisch** [comment]
Referencing https://www.figma.com/design/3Xx6EzwsVgbudJECshgwL2/TBAndroid_2024_Q3_CrossDevice_v01.0?node-id=4219-7276&t=pLFQEVw9GQRJW5pa-4 so it is easier to find

**Comment by kewisch** [comment]
Nice to have for 8.0, I know @cketti is adjusting the FTUE this week so this might be a good drive-by fix.
