### ISSUE TITLE
[Onboarding] Disable Unified Inbox if there's only one account

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#7556]
Disable the Unified Inbox by default and ask the user if they want to enable it after they have set up their second account.

**Comment by Aditya13s** [comment]
Can i work on this? @cketti

**Comment by cketti** [comment]
Hi Aditya13s :wave: Thanks for wanting to contribute.

The "needs design" label indicates that this feature needs a UI and/or UX design before it can be implemented. However, this feature is not something that is a high priority for us right now. So we'd rather not spend the time right now to give you something to work with.

An easier way to get started contributing to the project is by trying to fix bugs. Often the required change for a bug fix is isolated and doesn't require any architectural decisions or UI/UX design.
