### ISSUE TITLE
Opening an attachment and sharing it back to K-9 Mail fails

### ISSUE THREAD

**Issue by DimitriJunker** [thunderbird/thunderbird-android#7557]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6603

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Samsung Galaxy S23

### Steps to reproduce

1. Open a Mail with an Attachment (for Example an immage)
2. Open the Attachment
3. use the "share to" and select K9 as target
4. K9 opens with an empty Mail with the immage as target
5. complete the mail
6. send it

### Expected behavior

The Picture should be forewarded with the new Mail

### Actual behavior

The Mail is send with no attachment. I suppose, that on 2 only a temporarry File is created, which is not available anymore on 6. 
I would at least expect an error message on 6. But even better some easy way to foreward an attachment, either seperate for each attachmant or on the menue where you can reply, foreward,.. the mail add "foreward attachments"

**Comment by cketti** [comment]
Works for me.

K-9 Mail creates a copy of the content that is shared to the app. If the attachment box is displayed in the compose screen, it should be attached to the outgoing message. If no attachment box is displayed, that probably means the app sharing the content is not quite doing the right thing.

Can you record a video while reproducing this issue and post it here?

**Comment by DimitriJunker** [comment]
I`m not sure how to create a Video, do you mean with an external camera or as a kind of screenshot? But anyway maybe this is enough: I did some more tests. I used both the galerie apps from google and samsung.
I do it on a german phone, so I translate what I seet to english here
1) I Open the mail, I received with the picture, click on it, than "Open with" opens
2) I select Galerie and click on "Only this time" The Image is shown in the Galerie App.
3) If I click on the share icon and select K9. An empty Mail is opened. Here I was mistaken in the original post. So there is no attachment, which I didn't realised, so K9 can not send it. 

If on 3) I choose Skype instead of K9 I can send the picture, So there is some Misunderstanding between the Galerie apps and K9, And since I don't expect Galerie to use a different way to share with K9 or skype, I think the problem is in K9

**Comment by cketti** [comment]
I tried using another viewing app and was able to reproduce the problem. The source of the problem is a security mechanism in K-9 Mail. We'll disable it for this specific case.
