### ISSUE TITLE
Outlook.com Email sync error

### ISSUE THREAD

**Issue by Cameron356** [thunderbird/thunderbird-android#7591]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.714

### Where did you get the app from?

Google Play

### Android version

Android version 13 

### Device model

Samsung Galaxy S20 Ultra 5g

### Steps to reproduce

Add an Outlook.com email utilizing an "app password"

The password will work in the email setup wizard along with everything else

If you then try to manually sync the email via the method of pulling down from the top of the screen it will not always work 
Sometimes it will error out stating that the authentication failed. 

It seems to happen more if you continually refresh/sync

### Expected behavior

It should sync with no errors if the authentication is valid.

### Actual behavior

It will error out in some cases, I have not been able to find what will reliably make the error happen every time or in a pattern

It does seem to increase in frequency if you sync more often

This issue caused me to believe I or Microsoft had messed up my app passwords so I deleted them and made a new one. The problem would come back.

Sometimes the error will say authentication but that's not always the error note

But if I say on the screen to re set up the email I can make no changes and just try setting up the email over and over. After a few trys it all resyncs as if there were no issues.

**Comment by Cameron356** [comment]
This is my first big report. If I have done this incorrectly I would appreciate the criticism, so I can be a helpful end user in the future.

**Comment by Cameron356** [comment]
I have seen this bug for a while and never submitted a big because I always expect that I am doing something wrong and it's not the softwares fault. 
I also have expected that it is a Microsoft account issue, but I was advised that it's still beneficial to your team to know that it exists.

**Comment by Cameron356** [comment]
> Please provide a debug log. See https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors
> 
> But if sync sometimes works and sometimes doesn't, there's a good chance this is a problem with Microsoft's servers, not a bug in K-9 Mail.

I will enable this and when I get the bug to trigger I will add the log 

Would you require the "log sensitive information"
If so I can make a throw away to run the testing again

**Comment by cketti** [comment]
No, "log sensitive information" shouldn't be required.

**Comment by mdyer1** [comment]
Hi,

 

Just pointing this out incase this matters, I have seen this happen in thunderbird desktop and suspect this is a outlook.com issue.  Outlook has been having issues as for a little over a week now.  My outlook account is tied to an Microsoft 365 subscription.  Thanks..

 

 

 

Matthew Dyer

Sent from outlook365

Follow me on mastodon at  ***@***.***> ***@***.***

**Comment by cketti** [comment]
Please post a debug log or close the issue if it's no longer a problem.

**Comment by minecraftchest1** [comment]
Microsoft is discontinuing support for basic auth, mandating OAuth2 authentication. That may be part of your issue.

**Comment by Cameron356** [comment]
i meant to close this a while ago. the issue was resolved
