### ISSUE TITLE
Don't delay showing the "next" button after testing a server connection

### ISSUE THREAD

**Issue by allo-** [thunderbird/thunderbird-android#7596]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.714

### Where did you get the app from?

F-Droid

### Android version

14

### Steps to reproduce

After testing the settings of an IMAP server, the screen displays "Successfully tested server" and the same "Back" button as during the test. The "Next" button is not visible and only appears with a (about) five second delay, and pressing the "Back" button does *not* save the credentials.

Probably the "Next" button should always be shown and grayed out while the test is not successful, but otherwise you could also save the credentials (that were already entered on the previous screen) when hitting "Back" after a successful test, or redirect back to the settings screen and automatically save the changes.

It could also be useful to label the "Back" button with "Cancel" to make more clear, that it does *not* save the new credentials.

**Comment by wmontwe** [comment]
@allo- We changed the bahavior in 6.715 which is available as [GitHub release](ttps://github.com/thunderbird/thunderbird-android/releases/tag/6.715) at the time of writing. Google and F-droid releases are still pending.

Have a look and comment if that solves your issue.

**Comment by wmontwe** [comment]
@allo- any update on this? The F-Droid release is available
