### ISSUE TITLE
Accessing Office365 Account Error: "SMTPClientAuthentication is disabled for the tenant"

### ISSUE THREAD

**Issue by BalooRJ1** [thunderbird/thunderbird-android#7597]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.715

### Where did you get the app from?

F-Droid

### Android version

GrapheneOS

### Device model

Pixel 6a

### Steps to reproduce

While setting up a new Outlook account from work (emails are custom domain but otherwise hosted by outlook) I am able to access IMAP just fine using OAuth 2.0 authentication. However, when attempting to do the same for SMTP, I get the following error.

![Screenshot_20240201-185134](https://github.com/thunderbird/thunderbird-android/assets/66956924/1eb4b945-4d0a-453b-9704-5ef3868db2e7)

I am using the following SMTP settings for Office 365:

server: smtp.office365.com
Security: StartTLS
Port: 587
Authentication: OAuth 2.0

### Expected behavior

I would like it to authenticate my account to send emails.

### Actual behavior

K-9 mail does not let me advance in the setting up new account wizard.

**Comment by wmontwe** [comment]
@BalooRJ1 Did you follow [how do I add an Office365 account?](https://forum.k9mail.app/t/how-do-i-add-an-office365-account/5072)

It might be that your organisation disabled SMTP auth. You could ask your admin for help, but usually it's disabled for compliance reasons.

For reference: https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission

**Comment by vtstanescu** [comment]
> [@BalooRJ1](https://github.com/BalooRJ1) Did you follow [how do I add an Office365 account?](https://forum.k9mail.app/t/how-do-i-add-an-office365-account/5072)
> 
> It might be that your organisation disabled SMTP auth. You could ask your admin for help, but usually it's disabled for compliance reasons.
> 
> For reference: https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission

Does Thunderbird for Android support a OAuth authentication to Office 365 instead of SMTP AUTH? So we don't need to enable SMTP AUTH in Microsoft Exchange.
