### ISSUE TITLE
MessageList started twice after adding new account

### ISSUE THREAD

**Issue by wmontwe** [thunderbird/thunderbird-android#7598]
I noticed that when you add a new account, the MessageList is started twice. First the global inbox ist started and on top the newly added account inbox. Just hit back after adding an account and you need to do it twice to leave the app.

**Comment by cketti** [comment]
This behavior is intentional. Pressing back in the message list will always switch to the Unified Inbox before exiting the app.

**Comment by wmontwe** [comment]
I checked and it respects the setting to show or hide the unified inbox
