### ISSUE TITLE
[FR] Store reply in folder of original message rather than "Sent"

### ISSUE THREAD

**Issue by AleXSR700** [thunderbird/thunderbird-android#7599]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.714

### Problem you are trying to solve

Every email written as a response is stored in the "Sent" folder (or whichever folder the user specifies).
This causes a hige amount of messages in one folder that all need manual sorting.

### Suggested solution

Add an option to store the response in the same folder as the initial message, i.e. if an email is replied to that is located in the subfolder "Family", the response email is also stored in "Family" rather than in "Sent".

Ideally this would also apply to the inbox.

**Comment by wmontwe** [comment]
@AleXSR700 We're planing to add a "Conversation View", see #6197. That's maybe what would solve your issue.

**Comment by AleXSR700** [comment]
It would help but it would still store the emails in the Sent folder.
The idea is to "physically" store the messages in the same folder.

I know this feature from work (Outlook) and it is very useful in helping to stay organized.
Especially when threads and conversations are not working (Threads e.g. seem to be broken in K-9 at the moment).

**Comment by janwill2024** [comment]
Yes please integrate this function in the app like in the TB desktop version!!!
