### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#7600]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

None

### Android version

14

### Device model

Vivo v27 funtouch os 14

### Steps to reproduce

Open app  
open a mail  
long press on a otp code

### Expected behavior

Bsjwvshsn

### Actual behavior

Snbsjs

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14149057/k9mail-logs.txt)

**Comment by bar82max** [comment]
It was around 7:00 am 3 feb  , if you are looking in logs

**Comment by cketti** [comment]
This seems to be a bug in WebView. Try updating System WebView and/or Chrome.
