### ISSUE TITLE
MiniDNS OSCommand

### ISSUE THREAD

**Issue by SvSky** [thunderbird/thunderbird-android#7604]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.715

### Problem you are trying to solve

Presence of OSCommand execution in the org.minidns library : 

org/minidns/dnsserverlookup/AndroidUsingExec.java

Set parseProps = parseProps(new LineNumberReader(new InputStreamReader(Runtime.getRuntime().exec("getprop").getInputStream(), StandardCharsets.UTF_8)), true);

### Suggested solution

I tried to exclude ( + add 'minidns-core = "org.minidns:minidns-core:1.0.4"' in libs.version.toml) : 

implementation(libs.minidns.hla) {
        exclude("org.minidns", "minidns-client")
}
implementation(libs.minidns.core) 

It works if user's account allready exists, but crash if a new account is created

**Comment by cketti** [comment]
I don't see how this is a problem in an unmodified version of K-9 Mail.

Are you working on a custom version of K-9 Mail for yourself? If so, why report your development problems to us?

**Comment by cketti** [comment]
Please add enough information so the issue can be understood without requiring additional private context.

What are you trying to do? Why?

K-9 Mail is not using `ProvidersXmlDiscovery` anymore. Are you sure this is related to K-9 Mail 6.715?

**Comment by SvSky** [comment]
ProvidersXmlDiscovery is not related to 6.715. It's just the last version i build for work was the 6.710 and it was in.

But since this version, we have new security control and OSCommand are no longer ok.

I was trying to figure out with Wolf Montwe how i can put my custom providers inside the new version (waiting to have operational OAuth), and i talk him about OSCommand
________________________________

**Comment by wmontwe** [comment]
The issue with MiniDNS is that it is executing system commands. This is considered harmfull by some security tools and therefore reported. This is problematic as it leads to not beeing able to use K-9 in environments where such checks are enforced.

So we should at least evaluate if there are alternatives to `minidns` that work for mobile and are not executing system commands.

**Comment by SvSky** [comment]
Hello, 
I builded the 6.800 and no OS Command was found
Thank you
