### ISSUE TITLE
Google work account setup fails

### ISSUE THREAD

**Issue by jayb-g** [thunderbird/thunderbird-android#7606]
While setting up a Google work account(foo@bar.com), it ends up with following error during the setup process. 

![](https://i.postimg.cc/T1FMHnfw/Screenshot-20240207-142455-1.png)

Android 14
no-GMS
K9 v6.715

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors

**Comment by jayb-g** [comment]
I don't know why this happened, but after posting this issue and trying again, it worked as expected.

**Comment by cketti** [comment]
Then we'll close this for now. If you run into this again, please try to record a debug log and post it here.
