### ISSUE TITLE
Google Gmail 系统连接超时

### ISSUE THREAD

**Issue by bujinimeiyandongren** [thunderbird/thunderbird-android#7610]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Other

### Android version

否

### Device model

vivo

### Steps to reproduce

![Screenshot_20240208_171553](https://github.com/thunderbird/thunderbird-android/assets/59303388/2746dbff-8bf5-4f31-8e2b-b91f1843067f)

### Expected behavior

希望修复这些问题

### Actual behavior

1

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.

Make sure to provide as many details as possible so others are able to help you. What's your email provider? Which server settings did you use?
