### ISSUE TITLE
Malformed email error

### ISSUE THREAD

**Issue by coetzeec2380** [thunderbird/thunderbird-android#7617]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

None

### Android version

13

### Device model

Samsung A71

### Steps to reproduce

Create of forward email to multa dot domain ie ccoetzee@arrow.altech.co.za 

### Expected behavior

Just send the mail out

### Actual behavior

Flanes the mail as mal formed and left it in the outbox

### Logs

Will log data

**Comment by cketti** [comment]
Please provide a debug log and/or the exact error message from the notification.
