### ISSUE TITLE
Mailto links should focus subject, not address

### ISSUE THREAD

**Issue by LorenzHo** [thunderbird/thunderbird-android#7618]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

When opening a mailto link, I would expect to type the subject and body of the email. However, when K9 opens, the address field is focused, so finishing and sending the mail needs one unneccessary click.
 
example: [mailto:user@example.com](mailto:user@example.com) 

Additionally, when I open a mailto link with the subject already filled, I would expect to type the body, but the address is focused.
example: [mailto:user@example.com?subject=subject%20already%20filled](mailto:user@example.com?subject=subject%20already%20filled)

When replying to an email within K9, it directly focuses the body with the address and subject already filled. This is the behaviour I would expect also for mailto links.

### Suggested solution

When opening an email from a mailto link, directly focus the subject if just the email address is given, and the body if the email address and subject is given.

**Comment by cketti** [comment]
We might not get to this anytime soon. But we'd welcome pull requests to implement the suggested behavior.

**Comment by cketti** [comment]
It's possible to have a mailto URI without a recipient <mailto:?subject=text>. What should happen in such a case? Focus on the "To" field or the message body?

**Comment by LorenzHo** [comment]
Very valid point, focus should be on the first empty field of "To", "Subject" and body in that order. 

However this is a little more complex to implement as I currently understand it, as it seems with my (limited) understanding of the codebase that in [`addRecipientsFromAddresses`](https://github.com/thunderbird/thunderbird-android/blob/176a520e86bfe6875ad409a7565d122406dc7550/app/ui/legacy/src/main/java/com/fsck/k9/activity/compose/RecipientPresenter.kt#L489) actually loading the "to" addresses is put off to a RecipientLoader until the field is rendered. 

So, there seems to me to be no direct way to access if any email address is going to be loaded into the "To" field from where the distribution of focus [currently happens](https://github.com/thunderbird/thunderbird-android/blob/176a520e86bfe6875ad409a7565d122406dc7550/app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageCompose.java#L457), but I might just be missing it.
Both `recipientMvpView.getToAddresses()` and `recipientPresenter.getToAddresses()` turn up empty at that point

**Comment by cketti** [comment]
Thanks for looking into it. This feels too complicated address right now. So I merged your PR as is.

We need to clean up the way recipients are handled anyway. That should make it easier to implement the desired focus logic afterwards.

**Comment by LorenzHo** [comment]
Actually I've looked into this again and how it is now, it causes a regression apart from the edge-case mailto link without a "to" address: When a user tries to share a file by K9, now the subject field is focused, while the "to" field is unfilled. This is I would say a valid use case.
No hurt feelings if you cancel my original PR. 
I'll try to find an easy way to manage focus somewhere where the to addresses are available, maybe during composing the UI. Let's handle this in the issue #7635 you created.

**Comment by cketti** [comment]
Thanks for staying on this. I'll revert the change, so we don't change the behavior when handling share intents.
