### ISSUE TITLE
[BUG] Cannot save sent mail in Sent box on receive only account

### ISSUE THREAD

**Issue by kiplingw** [thunderbird/thunderbird-android#7641]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

20-20240209-microG-lake

### Device model

moto g(7) plus

### Steps to reproduce

If you have multiple accounts, one of which is a send only account, there is no way to select in its Folders setting another account's IMAP Sent folder. 

### Expected behavior

It would be better if there was a way to select another account's IMAP Sent folder if the current account does not have any IMAP folders available because it's configured as a send only account.

### Actual behavior

As a result records of sent mail are lost.

**Comment by cketti** [comment]
No, cross account references will only lead to problems when it comes to importing/exporting settings etc. The proper way to enable this, is to allow multiple outgoing servers per account. See #1117.

As a work-around you could configure your "send only" account to use the incoming server whose Sent folder you want to use. Configure that account to never check folders automatically. That way uploading sent messages should work as expected.

**Comment by kiplingw** [comment]
I should clarify that both accounts, the send/receive account and the send only account both are using the same server. The latter account when it receives mail has a server side forward that automatically forwards to the former. I just want to ensure that when I send mail via the latter account a copy is saved in the Sent folder for the first one.
