### ISSUE TITLE
[UX] Automatically trigger OAuth during Account Setup if the email is from one of the common providers

### ISSUE THREAD

**Issue by Alecaddd** [thunderbird/thunderbird-android#7649]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.715

### Problem you are trying to solve

During initial account setup, if I input my Gmail account I get a screen with the server settings found and a button to login via OAuth.

### Suggested solution

If the user inputs a plan Gmail, Microsoft, Yahoo, or similar type of account that doesn't use a custom domain:
- We should skip the "server settings found" screen and directly trigger the OAuth popup view.

**Comment by kewisch** [comment]
Hey Alex, we talked about this issue in triage. While reducing clicks is a good idea generally, I believe the status quo is sufficient for the current experience. I'd rather tackle this as part of a future account setup alignment between desktop/mobile, in which case we'd look at the bigger picture. Let me know if you have more specific needs around this issue!
