### ISSUE TITLE
Export folder-settings only works for top level folders

### ISSUE THREAD

**Issue by wweich** [thunderbird/thunderbird-android#765]
I have a folder structure with 3 or 4 levels of (sub-)folders in my IMAP account.

After configuring all the folders (display class, sync class, push class, ...) I exported the settings and imported them on my new phone, but only the settings for the top level folders where transferred.
I checked the k9s file and saw that only the top level folders where exported.
I edited the file and added all my folders (with a script) and imported that file after clearing the K9 data. 
This time, all settings were imported.

So the export skips sub-folders but the import (fortunately) does not.

Sub-folders should also be exported.

I tested this with v5.006 and v5.107 on Nexus 5 with stock Android 5.1.1.

**Comment by cketti** [comment]
K-9 Mail doesn't know the concept of subfolders. But it looks like the problem manifests for all folders with a "." character in the name.

The problematic lines are:
https://github.com/k9mail/k-9/blob/583a637d79fe7bfd083a97c0208b6acade6cb47d/k9mail/src/main/java/com/fsck/k9/preferences/SettingsExporter.java#L294

https://github.com/k9mail/k-9/blob/583a637d79fe7bfd083a97c0208b6acade6cb47d/k9mail/src/main/java/com/fsck/k9/preferences/SettingsExporter.java#L322
