### ISSUE TITLE
Google configuration issue

### ISSUE THREAD

**Issue by airi019** [thunderbird/thunderbird-android#7656]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.716

### Where did you get the app from?

F-Droid

### Android version

Lineage OS 18.1 Android 11

### Device model

Moto G5S

### Steps to reproduce

1.Lineage os without gapps
2.fdroid from official website
3.k-9 mail
4.try to login gmail

### Expected behavior

Until a few days days ago there was no such popup and it does oath instantly

### Actual behavior

I don't know if login like is safe

### Logs

![Screenshot_20240219-200004_K-9_Mail](https://github.com/thunderbird/thunderbird-android/assets/155326638/ad54ef49-0047-449f-bbdd-b8f0de9fe0ac)

**Comment by airisama019** [comment]
nevermind, fixed on 6.717
