### ISSUE TITLE
Email address in setup wizard autocapitalizes name

### ISSUE THREAD

**Issue by CodingItWrong** [thunderbird/thunderbird-android#7665]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.716

### Where did you get the app from?

Other

### Android version

10 (QP1A.190711.020)

### Device model

Pixel 2 XL

### Steps to reproduce

- Begin adding a new account from a fresh install or from Settings > Add account
- Type "josh" (all lowercase" in the email address field
- Type "."

### Expected behavior

I see exactly what I typed, "josh."

### Actual behavior

I see "Josh." with the J capitalized

![Screenshot_20240223-064216](https://github.com/thunderbird/thunderbird-android/assets/15832198/b7e87ef4-4ec4-4d1a-94c6-09fa0c8f2f13)

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14384801/k9mail-logs.txt)

**Comment by CodingItWrong** [comment]
Very minor, of course, but this did result in my saved email address starting with capital J, and it made me wonder if email recipients would see it that way, since it's atypical to see a capitalized email address.

**Comment by wmontwe** [comment]
The problem is caused by the autocomplete function of the keyboard. As of now, there is no simple solution to block this on our end. Google has announced a new text input tool that promises to improve that behavior. Sadly it's not in a production ready state yet.

**Comment by wmontwe** [comment]
For reference: [Version 1.7.0-alpha03](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.7.0-alpha03)

Once `BasicTextField2` is available in a production version of `androidx.compose.foundation`, we should change our`TextField` to it.
