### ISSUE TITLE
K-9 6.717 F-Droid battery consumption too high

### ISSUE THREAD

**Issue by vdbhb59** [thunderbird/thunderbird-android#7669]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.717

### Where did you get the app from?

F-Droid

### Android version

13

### Device model

Vivo Y35

### Steps to reproduce

Since 6.717 update, the battery consumption and heating is very high. I keep getting OS based notification of very high battery consumption. The phone is also heating too much.
I have checked for every other app, and I always keep a tap on these stuff. K-9 6.717 is causing this.

It is showing 70.4 mAh for today.

![K-9 Power Consumption](https://github.com/thunderbird/thunderbird-android/assets/60728004/92b1ecc8-e9ec-4756-becf-fb9065a070a2)

### Expected behavior

Battery consumption should not be so high.

### Actual behavior

Snapshot above shows 70.4 mAh as today's consumption.

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors

**Comment by vdbhb59** [comment]
Closing out as seems the system upgrade (OS) was what was causing this high rise in consumption.
