### ISSUE TITLE
Don't allow passwords containing line breaks

### ISSUE THREAD

**Issue by williamdes** [thunderbird/thunderbird-android#7670]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.717

### Where did you get the app from?

None

### Android version

X

### Steps to reproduce

Start configuring your icloud.com email

### Expected behavior

Password checks and it goes to next step

I did the setup on FairEmail at the same time and it worked. 

### Actual behavior

Server error: unmatch quote

### Logs

```
02-24 22:58:27.993 20341 10889 V RealImapConnection: conn72600286 <<< #null# [OK, [CAPABILITY, XAPPLEPUSHSERVICE, IMAP4, IMAP4rev1, SASL-IR, AUTH=ATOKEN, AUTH=PLAIN], (2409B40-f42d5d1bd981) mr36p00im-tygg11200301.me.com]
02-24 22:58:27.994 20341 10889 D RealImapConnection: Saving [IMAP4, AUTH=PLAIN, XAPPLEPUSHSERVICE, SASL-IR, AUTH=ATOKEN, IMAP4REV1] capabilities for conn72600286
02-24 22:58:27.995 20341 10889 V RealImapConnection: conn72600286>>> 1 AUTHENTICATE PLAIN 

02-24 22:58:28.166 20341 20341 D InsetsController: show(ime(), fromIme=true)
02-24 22:58:28.223 20341 10889 V RealImapConnection: conn72600286<<<#+# []
02-24 22:58:28.651 20341 10889 V ImapResponseParser: conn72600286<<<#1# [NO, [AUTHENTICATIONFAILED], Authentication Failed]


RealImapConnection: conn72600286>>> 2 LOGIN "myusername" "ykkl-xxx-xxxt-kkki
02-24 22:58:28.655 20341 10889 V RealImapConnection: 
02-24 22:58:28.655 20341 10889 V RealImapConnection: "
02-24 22:58:28.848 20341 10889 V ImapResponseParser: conn72600286<<<#2# [BAD, unmatch quote]
```

**Comment by williamdes** [comment]
There is some code and tests on GitHub 

https://github.com/Kopano-dev/vmime/blob/431305e11d847d93b6d67da8867d272d872c127a/tests/net/imap/IMAPParserTest.cpp#L68

`AUTH=ATOKEN` maybe means apple token. I have no idea. Seems like they have a difference in the protocol implementation

**Comment by cketti** [comment]
Are you using a password manager or some other tool that somehow managed to enter a password containing two line breaks at the end?

**Comment by williamdes** [comment]
Hmm, indeed maybe my copy paste from their website did this

**Comment by williamdes** [comment]
Yeah that was it !
But the password input does not reflect such characters, FairEmail input does. That's how I did see that I needed to use "paste in raw format"
