### ISSUE TITLE
SMTP for forward-only addresses

### ISSUE THREAD

**Issue by tlhackque** [thunderbird/thunderbird-android#7683]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

SMTP-only accounts and per-identity SMTP support have been requested previously, but this use case hasn't been satisfactorily addressed.

Here's the problem:

I have an e-mail forwarding account provided by a professional organization.  It has NO inbox.  All mail sent to that account is forwarded to a server I control and appears in the inbox of my server.  That server has several traditional identities that use a local SMTP server.

The local SMTP server can not send from the forwarded address - it fails spf/dmarc and recipients such as gmail bounce any attempt to do so.  Instead, I'm required to send using a SMTP server associated with the professional organization.  (Actually, they outsource to mailroute.net, but it's the same thing.)

In K-9 ("the app"), I can setup an account for this identity that uses the correct SMTP server.  But there is no INBOX.  That leaves me with specifying an invalid IMAP server and setting Poll to never.  And so there is ONLY an OUTBOX.

I can read e-mail to the forwarded address from the account on my server.

But to send from the forwarded address, I have to switch accounts.  Compose/send.  But I can't see the inbox.  So then switch back to see replies or other mail that I need to respond to.

I can't "upload sent messages" because there's no Sent folder - again, just an Outbox.  So I have to Bcc myself, and then manually move the Bcc to Sent..

This is a lot of manual work just to be able to send from the correct identity.

### Suggested solution

SMTP servers should be first class objects, as in Desktop Thunderbird.

Identities should be able to be associated with any SMTP server.

In my case:

The forwarding address would be an identity under my server.  Outbound mail from that identity would use the special SMTP server.  Inbound mail for that identity would appear in the target inbox via it's IMAP server.

Then I can read the mail associated with that identity, and respond all from the same account.  Switching would only be necessary to among identities, not accounts, 

(I do not use a "unified inbox"; my identities are distinct.)

**Comment by cketti** [comment]
> SMTP-only accounts and per-identity SMTP support have been requested previously, but this use case hasn't been satisfactorily addressed.

The use case you describe is covered by #1117. I don't think we need a separate issue for this.

You can improve on your work-around by using the same incoming server with both accounts. Configure the second one to never sync. That will still allow you to upload sent messages.

To send a message from a different account you don't have to switch accounts. You can start a new message in account A, then switch to the sending identity from account B by tapping the sender email address/name next to "From".
