### ISSUE TITLE
Launch screen mistakenly displayed in Italian

### ISSUE THREAD

**Issue by PhilC813** [thunderbird/thunderbird-android#7703]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.800

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Motorola Edge+ (2020)

### Steps to reproduce

1. Assuming that this issue only occurs with my specific configuration; set your device language to "English (Canada)" in first priority and "French (Canada)" as second.
2. Install the app from Google Play. If it is already installed, clear the app data from Android settings (equivalent of a reset) or reinstall it from scratch.
3. Open the app. The launch screen will be shown.

### Expected behavior

Show the launch screen in the default language set in Android settings, which in my case, is English.

### Actual behavior

The launch screen was displayed in Italian.

![Screenshot_20240307-190827](https://github.com/thunderbird/thunderbird-android/assets/94257099/6f1d3a82-5afd-459a-917b-cd36a3e45e59)

The following screens were correctly displayed in English.

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14533170/k9mail-logs.txt)

**Comment by cketti** [comment]
The en_GB translation was broken. This has been fixed and will be included in K-9 Mail 6.801.
