### ISSUE TITLE
Improve automatic folder detection for iCloud email addresses

### ISSUE THREAD

**Issue by PhilC813** [thunderbird/thunderbird-android#7704]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.800

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Motorola Edge+ (2020)

### Steps to reproduce

In the initial setup, configure an iCloud email address. This requires a previously configured app-specific password on the Apple ID website.

### Expected behavior

All folders should be detected automatically, for iCloud and all major email services, considering the larger Thunderbird release that is to come and the new user base that it will bring.

Here's the full list of native folders in iCloud:
![Native folder list (iCloud com)](https://github.com/thunderbird/thunderbird-android/assets/94257099/6f3370fb-6553-4233-82a4-7b9be96e7134)

With that in mind, this is how the folders should be configured by default in K-9:
![Corrected config](https://github.com/thunderbird/thunderbird-android/assets/94257099/2fc97ea3-4860-474a-b370-75f9ce2f4b49)

### Actual behavior

Only 2 of the folders are detected automatically, being the "Sent" and "Trash" folders. The other ones are set to "None".

I would share the screenshot but I deleted it by mistake; it can easily be replicated by configuring an iCloud email address.

**Comment by cketti** [comment]
With my iCloud test account I get the following during account setup:

![image](https://github.com/thunderbird/thunderbird-android/assets/218061/749020d2-507a-4c8f-ae06-ce5fb480b688)

There's an IMAP extension to communicate which folders are associated with special roles. The iCloud IMAP server does support this extension, but (in my case) only returns information about the Sent folder. This is behavior that should be fixed on iCloud's side. 

We currently have no plans to add provider-specific non-standard ways to find special folders. You should file a bug against iCloud.

**Comment by Philippe-Choquette** [comment]
Thank you for your response!

I have submitted a feedback with Apple. I believe it would have been in your team's best interest to file a ticket on your end tho, since the average user who's looking for an Android email client will make its decision on what works best "out of the box".
