### ISSUE TITLE
Crash when modifying user for SMTP server

### ISSUE THREAD

**Issue by wweisz** [thunderbird/thunderbird-android#771]
### Expected behaviour

After having set up the first mail account server, I wanted to set up the SMTP server, which is different from the incoming mail server and uses a different user name and password.
### Actual behaviour

The SMTP server is changed (no unexpected behaviour), and then when I modify the user name or start to modify the password the screen gets black or freezes and then gets black. The message that K-9 stopped appears.
### Steps to reproduce

1.Setup first incoming mail account
2.Trying to setup the SMTP server account K-9 Mail crashes.
3.
### Environment

K-9 Mail version: 5.006

Android version: 4.1.2 (no newer version provided by my ISP)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Can you please try to get the stack trace written to Android's system log. For instructions see here: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by wweisz** [comment]
I wasn't able to create a single account. So I have no accounts screen where to set the debug option.

**Comment by cketti** [comment]
As mentioned on the wiki page, don't bother with enabling debug logging when K-9 Mail is crashing. Crash information is always written to Android's log.

**Comment by wweisz** [comment]
Sorry, for the time being I'm too busy for the preparation steps needed to provide you with the debug informations. I've found a way around: I created the incoming account as coming from the server used for SMTP; so I didn't have to modify user name and password. Then I changed the server data for the mail account on my Android device.
So I could create the intended environment - be it with a not so time-consuming detour.
At your discretion, you may close this issue, or leave it open, as the problem is still there.
Thank you for having reacted so quickly.
