### ISSUE TITLE
When choosing an email account to see the profile pictures shown are wrong. 

### ISSUE THREAD

**Issue by asder216** [thunderbird/thunderbird-android#7710]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.800

### Where did you get the app from?

F-Droid

### Android version

Android 14

### Device model

Samsung S23+

### Steps to reproduce

1. Open the hamburger menu and try to switch email account. 
2. The profile pictures shown are wrong. 

### Expected behavior

Only the first account to the left should have that picture, the other two accounts don't have any picture set up. 

### Actual behavior

![Screenshot_20240312_004951_K-9 Mail](https://github.com/thunderbird/thunderbird-android/assets/62883417/2f86eb2d-987c-4ef7-a7f5-048a802cf851)

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14565608/k9mail-logs.txt)

**Comment by cketti** [comment]
We haven't made any changes to this code in the recent past. So this is unlikely to be a bug. K-9 Mail uses the picture of the system contact associated with an account's email address. If you add all of your email addresses to a single contact, all accounts in K-9 Mail will show the same image. For a feature request to change this behavior, see #5509.

**Comment by asder216** [comment]
I see, thanks for replying!
