### ISSUE TITLE
6.800 no longer remembers 'direction' when deleting emails

### ISSUE THREAD

**Issue by siccovansas** [thunderbird/thunderbird-android#7714]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.800

### Where did you get the app from?

F-Droid

### Android version

14

### Steps to reproduce

1. Open an email
2. Swipe right (to see a previous email)
3. Delete the email

### Expected behavior

I would expect to see the following previous email.

Before 6.800, K9 would remember which direction I was swiping, which was useful because I sometimes move up and sometimes move down through my inbox.

### Actual behavior

I see the next email (the one I originally opened).

**Comment by cketti** [comment]
We intentionally no longer support the "magic" mode of going to the next or previous message depending on the last navigation direction.

You can pick whether you always want to go to the next or previous message under *Settings → General settings → Interaction → After deleting or moving a message*.

**Comment by siccovansas** [comment]
Thanks for the explanation! I indeed noticed the 'After deleting or moving a message' setting. I loved the 'magic' mode though! I guess I'll have to get used to moving through my inbox in one direction now :).

If there are others who would like the 'magic' mode to be added back as an option, give this issue/comment a thumbs up :+1:.

**Comment by rvk01** [comment]
@cketti Wouldn't it be possible to add the "magic" option to the "After deleting" setting?

What was otherwise the reason behind removing this feature?

Before there wasn't an option. Now that the is, setting it to magic should be clear for the users who set it to that manually. There would be no confusion. I miss it a lot too.
