### ISSUE TITLE
Decide on prefixes for app-specific classes/function names

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#7718]
We need to decide on prefixes for app-specific classes for both K-9 Mail and Thunderbird for Android. This is mostly for app-specific implementations of an interface. But maybe also for app-specific compose functions, e.g. `K9Theme` and `TbTheme` (although in this case maybe having them called `K9MailTheme` and `ThunderbirdTheme` is not a big deal, because those are usually used on a single line together with only an opening brace).

I'm suggesting `K9` for K-9 Mail and `Tb` for Thunderbird for Android. These have the advantage of being short. Which feels important when the interface name already has 3+ components, e.g. `OAuthConfigurationFactory` (→ `K9OAuthConfigurationFactory`/`TbOAuthConfigurationFactory` vs. `K9MailOAuthConfigurationFactory`/`ThunderbirdOAuthConfigurationFactory`).

**Comment by beradeep** [comment]
Agree with this!
