### ISSUE TITLE
IMAP: Delete (move to trash) no longer issues EXPUNGE command

### ISSUE THREAD

**Issue by PRBUK** [thunderbird/thunderbird-android#7721]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.712

### Where did you get the app from?

Other

### Android version

12 and 14 - Manufacturer Shipped (Samsung) 

### Device model

Samsung Galaxy Tab S4/9 and phone S10+

### Steps to reproduce

Delete a message (say from Inbox) using K9 Client

### Expected behavior

The message is moved (ie: deleted from Inbox) and placed in Deleted Items (Trash) 

### Actual behavior

In version 6.711 deletion works as expected.  
In version 6.712 a copy is placed in Deleted Items and the original email only marked for deletion in Inbox, when viewed on Webmail.  It no longer displays in K9, however the email still counts towards the number of emails held in the K9 Inbox. (Probably the move is performed but the delete from Inbox partially fails - marked for delete rather than deleted).

The Server is running legacy software from a company that is no longer trading, so the change in 6.712 'Added support for the IMAP MOVE extension' may be the root cause.  I am unable to update the software if this new IMAP extension was added after the last server software release.  

Accepting that a move to a new platform is ultimately inevitable, but is a longer term requirement,  is it possible to detect the failure of the new command (or test whether the server supports the command) and fall back/revert to the previous method if not - which has been working perfectly for a long time!?

A debug log of a successful deletion under 6.711 and a subsequent failed deletion after upgrading to 6.712 is attached (APKs retrieved from GitHub Assets)

The issue was discovered when the latest version (6.800) was pushed from the Google Play Store.  The ticket relates to a posting of a similar title in the support forum

### Logs

[V6.711 08-40 k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14614927/V6.711.08-40.k9mail-logs.txt)
[V6.712 08-50 k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14614929/V6.712.08-50.k9mail-logs.txt)

**Comment by cketti** [comment]
No longer issuing an EXPUNGE command when moving a message ("delete" is moving a message to the trash folder) was an intentional change. See #7366.

However, I can now see that this was a mistake. When a trash folder is used and the expunge policy is set to "immediately" there's never a situation where a regular EXPUNGE command is issued (in folders other than the trash folder).

Side note: You should look into updating your server software. Not supporting the MOVE or UIDPLUS extensions makes for a subpar user experience.

**Comment by PRBUK** [comment]
Your Side Note: acknowledged in my original 'Actual Behaviour' comments - but as the supplier is no longer trading, there is no upgrade path.  The platform provides more than email and still meets our needs.  I need to find another solution and work out a migration plan!

Do I take it from your comments that a future release will be able to once again co-exist with my platform?  If so, Thank You!!

**Comment by cketti** [comment]
This should be fixed in K-9 Mail 6.802.
