### ISSUE TITLE
Push not working anymore: "The app can't schedule timers"

### ISSUE THREAD

**Issue by OrkoGrayskull** [thunderbird/thunderbird-android#7725]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.801

### Where did you get the app from?

F-Droid

### Android version

14

### Device model

Google Pixel 8

### Steps to reproduce

Enable push for mail account.

### Expected behavior

Push works.

### Actual behavior

Since the last version push mails stopped working. I searched the logs and found:

"ImapBackendPusher for Account because the app can't schedule timers"

Maybe this helps. I'm using GrapheneOS.

### Logs

PushController: ..Starting PushController for accounts: [16272ae7-c1e8-4711-bba2-006530a33723]
03-17 23:58:09.536 26393 26441 V AccountPushController: AccountPushController(16272ae7-c1e8-4711-bba2-006530a33723).start()
03-17 23:58:09.536 26393 26441 V ImapBackendPusher: Not starting ImapBackendPusher for Account because the app can't schedule timers
03-17 23:58:09.536 26393 26441 V PushController: ..Running PushControllers: [16272ae7-c1e8-4711-bba2-006530a33723]
03-17 23:58:09.536 26393 26441 V PushServiceManager: PushServiceManager.start()
03-17 23:58:09.536 26393 26441 V PushServiceManager: ..PushService already running

**Comment by TrilIiard** [comment]
Same here on Pixel 8, Stock Android 14, March 2024 Security Patch, February Google Play Systemupdate, App Version 6.801 installed from Github
