### ISSUE TITLE
Cannot add Yandex email address - complains about imap

### ISSUE THREAD

**Issue by BD9Max** [thunderbird/thunderbird-android#7726]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.801

### Where did you get the app from?

F-Droid

### Android version

11

### Steps to reproduce

Settings add account
Enter yandex.com email
Complains imap
See screenshot
![Screenshot_20240318-113114_1_1](https://github.com/thunderbird/thunderbird-android/assets/82726385/da19bbdd-82c6-4fce-b604-8096fe186ebf)
![Screenshot_20240318-113138_1](https://github.com/thunderbird/thunderbird-android/assets/82726385/bf979310-0137-4555-bfc6-635aa6584291)

### Expected behavior

Login

### Actual behavior

Error

**Comment by cketti** [comment]
Please contact your email provider about that. It sounds like you need to enable IMAP for your account and/or create an app-specific password.
