### ISSUE TITLE
k9 gmail 401

### ISSUE THREAD

**Issue by wrduane** [thunderbird/thunderbird-android#7727]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.08

### Where did you get the app from?

None

### Android version

14

### Steps to reproduce

Login to Gmail prompts 401 error

### Expected behavior

Login to Gmail prompts 401 error

### Actual behavior

Login to Gmail prompts 401 error

**Comment by cketti** [comment]
Please contact your email provider, Gmail, about that.
