### ISSUE TITLE
move form/to folders missing

### ISSUE THREAD

**Issue by MrC-** [thunderbird/thunderbird-android#7733]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.801

### Where did you get the app from?

F-Droid

### Android version

10

### Device model

OnePlus 5T

### Steps to reproduce

1 Go to an account -> trash (or any folder of single account) -> select one or more messages

Same thing for any folders.

### Expected behavior

show the options for move messages between folders (restore from trash, ...)

### Actual behavior

only delete or mark as read/unread and ... menu with add star or select all shown

![Screenshot_20240322-190141](https://github.com/thunderbird/thunderbird-android/assets/1180373/b4dd85cd-96b5-402e-8041-66c4790c8790)
![Screenshot_20240322-190230](https://github.com/thunderbird/thunderbird-android/assets/1180373/dda342ba-6184-45ff-bca6-5d0280116a6e)
![Screenshot_20240322-190236](https://github.com/thunderbird/thunderbird-android/assets/1180373/120cce03-6a08-453a-b83d-4e5fd5fcc6cb)

**Comment by cketti** [comment]
Did you set up your account using POP3? Not being able to move messages from the Trash folder to the Inbox is a known limitation because the app doesn't properly support local folders or messages (see #648).

For the foreseeable future the focus of the app will be to manage email on the server. Try using IMAP instead.

**Comment by MrC-** [comment]
I cannot use IMAP since servers have space (or sometimes others) limitations
Like
https://github.com/thunderbird/thunderbird-android/issues/648#issuecomment-121171280
I need offline copies of messages on pc, nb, phone, without leaving on server(s).
It is very annoying if you cannot recover a delete message (ie for mistake) or moving its between folders.

**Comment by cketti** [comment]
You should use a different email client then. K-9 Mail doesn't really support this use case. For example, there's no way to export downloaded messages that have been removed from the server. You won't be able to transfer them to a new device etc.
