### ISSUE TITLE
App crashes when adding new Email

### ISSUE THREAD

**Issue by Perondas** [thunderbird/thunderbird-android#7739]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.801

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Google Pixel 6 Pro

### Steps to reproduce

Try to add `fakemail@technikum-wien.at`

### Expected behavior

The account creation proceeds as normal.

### Actual behavior

The app crashes.

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14791669/k9mail-logs.txt)

**Comment by Perondas** [comment]
I first tried this on the non beta version in the Play Store. Same result.

**Comment by cketti** [comment]
Thanks for reporting this. It looks like the DNS library we're using doesn't properly cope with the broken(?) DNSSEC setup of `technikum-wien.at`.

**Comment by Perondas** [comment]
Thanks for looking at this. Thunderbird desktop works just fine with the domain.

**Comment by cketti** [comment]
The crash is fixed in K-9 Mail 6.802.

**Comment by Perondas** [comment]
Thanks. I already tried it. Works great!
Tho the configuration it automatically loaded was wrong. But that is a different issue.
