### ISSUE TITLE
Yahoo mail

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#7740]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.801

### Where did you get the app from?

None

### Android version

6.801

### Device model

ixomi redmi Note 9s

### Steps to reproduce

Yahoo mail add problem

### Expected behavior

Yahoo mail add problem _solution_

### Actual behavior

Yahoo mail add problem

### Logs

Yahoo mail add problem

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
