### ISSUE TITLE
When using an ALPHA-type hardware keyboard, display of the the special-character selector box is unreadable.  

### ISSUE THREAD

**Issue by claude0001** [thunderbird/thunderbird-android#7751]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.801

### Where did you get the app from?

F-Droid

### Android version

Lineage 16, Lineage 20

### Steps to reproduce

1. Connect an [ALPHA-type](https://source.android.com/docs/core/interaction/input/key-character-map-files#keyboard-type-declaration) hardware keyboard.
2. In K9-Mail, compose a new e-mail and select the message body for editing. 
3. On the hardware keyboard, long-press any character that exists in accented variants (e.g. 'A').
4. An on-screen selector box appears, that _should_ allow one to pick the desired accented variant of the character. However, in K9-Mail, the selector box is displayed in an unreadable and distorted way. See first screenshot attached.
5. Note that, despite the distorted graphics, the selector does actually allow one to pick an accented character at random: Tap any of the blank "character" boxes and the respective letter indeed appears in the message body. It is only the unreadable display that makes the character selector box useless. 

### Expected behavior

The accented character selector box should be displayed in a readable way. The second screenshot shows a different app (QKSMS) properly supporting the feature on the same device.

### Actual behavior

![Screenshot_20240409-140147_K-9_Mail](https://github.com/thunderbird/thunderbird-android/assets/86627658/0f05260f-b742-4d61-b00a-d679cb5e94bb)
![Screenshot_20240409-140411_QKSMS](https://github.com/thunderbird/thunderbird-android/assets/86627658/aae9b008-fa14-4852-bec1-4656e63cf0f2)

**Comment by cketti** [comment]
This UI is rendered by the OS, not the app. This is most likely a bug in Android that only affects some apps. Please report this in the Lineage bug tracker.
