### ISSUE TITLE
"<unknown sender>" when the sender name has a ":"

### ISSUE THREAD

**Issue by dddns** [thunderbird/thunderbird-android#7752]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

latest

### Where did you get the app from?

None

### Android version

10

### Device model

samsung

### Steps to reproduce

Howdy,

If the sender, has in it's client the name as "email: john" and send's an email to me, and i see it in K9, K9 translated the sendername to "unknown server",
If you need any further indo let me know, i saved the messaged.

![image](https://github.com/thunderbird/thunderbird-android/assets/13902147/cf4537bb-6592-4435-a328-82439071446f)

![image](https://github.com/thunderbird/thunderbird-android/assets/13902147/e1245271-dea0-4315-956b-8b31eda457d6)

### Expected behavior

Display name as it is

### Actual behavior

wrong displayed information

### Logs

sdfg

**Comment by dddns** [comment]
Hum, K9 is coding the header, the real, is indeed in quoted printable

From: =?utf-8?Q?Email:_Dire=C3=A7=C3=A3o?= <direccao@-----.pt>

**Comment by cketti** [comment]
This is an invalid encoding. The display name needs to be an [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322) phrase. A `:` is only allowed in a quoted string or in encoded form in an [RFC 2047](https://datatracker.ietf.org/doc/html/rfc2047) encoded word.

Did you use K-9 Mail to create this email? Or did some other email client create this header?

**Comment by cketti** [comment]
In my tests K-9 Mail encoded names containing `:` correctly. 

Closing this issue because no further information was provided.
