### ISSUE TITLE
Jump up when email deleted

### ISSUE THREAD

**Issue by supersarma** [thunderbird/thunderbird-android#7832]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.803

### Where did you get the app from?

F-Droid

### Android version

LineageOS 20 / Android 13

### Device model

Xiaomi A1

### Steps to reproduce

1. Go to settings
2. General settings
3. Interactions
4. Swipe actions
5. Leftswipe or right = Delete
6. Back to inbox
7. Scroll dawn and remove one email

### Expected behavior

The app should stay at the same position where the email was removed. 

### Actual behavior

The app jump all the way up, at the beginning.
Same behavior occurs when long press on email and clic on delete icon. It brings me at he beginning.

**Comment by cketti** [comment]
K-9 Mail 6.803 hasn't been released yet. I'm assuming this was a typo and you're using 6.802.

The list position is typically kept when deleting a message. It's possible that the app crashes when you delete a message. Modern Android versions simply restart the app when that happens. The user is only notified about the app crashing when it happens multiple times in a row. Try performing a couple of delete operations and see if Android displays a crash dialog. If so, please record a debug log while deleting a message and attach it here. See https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors

**Comment by cketti** [comment]
Closing this since no additional information was provided.
