### ISSUE TITLE
Vietnamese translation issue

### ISSUE THREAD

**Issue by ngocanhtve** [thunderbird/thunderbird-android#7848]
Dear, 

The Vietnamese translation has been 98% completed through hosted.weblate for many months. And I have also seen many commits that update the Vietnamese strings.xml into the source code.

But for some reason, I don't see Vietnamese appearing in the app display language selection list in the K-9 Mail.

I once encountered a similar situation with Stremio, their dev forgot to add a language array, causing Vietnamese not to appear even though it was in the source code. Please check it with K-9 Mail.

**Comment by cketti** [comment]
Thanks for reporting this :+1:

The Vietnamese translation will be included in the next beta version (6.902).
