### ISSUE TITLE
Account Inbox email adress truncated bottom 

### ISSUE THREAD

**Issue by hollisticated-horse** [thunderbird/thunderbird-android#7854]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.803

### Where did you get the app from?

F-Droid

### Android version

14

### Device model

Google Pixel 6a

### Steps to reproduce

Go to Inbox view for a specific account, not Unified view

### Expected behavior

Below the Inbox title, have a un-truncated email adresse.

### Actual behavior

The bottom of the adresse is truncated just a little bit. It's cosmetics.
 
![signal-2024-05-17-210413](https://github.com/thunderbird/thunderbird-android/assets/76632257/e9fb8156-4770-44c1-aae3-011cfaed64a2)

**Comment by cketti** [comment]
This seems to be a bug in the Toolbar component. See https://issuetracker.google.com/issues/135865267

It looks like Google isn't going to fix this. So we'll have to add a workaround to the app.
