### ISSUE TITLE
Last update crashes when starting the app 

### ISSUE THREAD

**Issue by acutbal** [thunderbird/thunderbird-android#7855]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Poco F5

### Steps to reproduce

After the update I try to open the app

### Expected behavior

Open the app and check my mail

### Actual behavior

The app crashes and doesn't start.

### Logs

![Screenshot_2024-05-18-23-17-58-480_com miui bugreport](https://github.com/thunderbird/thunderbird-android/assets/2278584/4f34d951-a903-4f32-b9d4-ae2407a91657)
![Screenshot_2024-05-18-23-18-06-220_com miui bugreport](https://github.com/thunderbird/thunderbird-android/assets/2278584/cd62369f-6699-456c-8cf3-9d40f282eeb9)

**Comment by vishalg** [comment]
Uninstalling and reinstalling worked for me but I had to setup all the accounts again.

**Comment by acutbal** [comment]
Yes, you're right, uninstalling and reinstalling again fixes the issue. 
Thank you very much.

**Comment by cketti** [comment]
In the past the app accidentally allowed the user to enter usernames and passwords containing line breaks. Newer app versions automatically strip line breaks when the user enters a username or password. We also added a check to make sure username and password in server settings never contain line breaks.
My assumption was that having a line break in the username or password will lead to a failure when checking server settings. So there won't be any existing accounts we have to fix during an upgrade. Apparently I was wrong. This crash also shows up for some beta users on Google Play.

Steps to reproduce:
1. Install K-9 Mail 6.803
2. Import the settings in [issue_7855_settings.zip](https://github.com/thunderbird/thunderbird-android/files/15499309/issue_7855_settings.zip) (dummy account containing line breaks in username of incoming and outgoing server settings)
3. Update to K-9 Mail 6.901 → App crashes during start
