### ISSUE TITLE
More theme colors

### ISSUE THREAD

**Issue by NCC1701M** [thunderbird/thunderbird-android#7856]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.901

### Problem you are trying to solve

Many might not like the new color theme. Add more colors for users to choose from.

### Suggested solution

Add more themes or colors tho choose from.

### Screenshots / Drawings / Technical details

More colors than the strange looking red/brown whatever

**Comment by Jojoba24** [comment]
Yes please

**Comment by SteffoSpieler** [comment]
I'd also love to have the Material You colors.

**Comment by cketti** [comment]
We currently have no plans to add additional themes. The plan is to support dynamic (system) colors on Android versions that support this. See #6617.

**Comment by Jojoba24** [comment]
Could you at least change the current default colour in the dark theme to a pure black or dark grey like it was before? (Would also be nicer for OLED)
There are probably many devices without dynamic colours and the current colour isn't very nice imo.

**Comment by NCC1701M** [comment]
I agree, I also think the current color scheme wasn't the best decision. 

Also, the users with Android versions without dynamic colors should also have the opportunity to change colors.
