### ISSUE TITLE
Can only log in using Google Oauth if on a Google domain

### ISSUE THREAD

**Issue by benjistokman** [thunderbird/thunderbird-android#7866]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

Can't see because I can't log in...

### Where did you get the app from?

F-Droid

### Android version

Graphene OS 14

### Steps to reproduce

1. Try to log in with any email that is handled by Gmail but isn't explicitly a Google email.
2. See how you can't log in.

### Expected behavior

IDK maybe have an option when manually configuring for loggin in with oauth?

### Actual behavior

It only gave me the option to use POP/IMAP and I can't use that because it's a manage account...

**Comment by wmontwe** [comment]
@benjistokman Coul you please try: [How do I add a Google Workspace account](https://forum.k9mail.app/t/how-do-i-add-a-google-workspace-account/5087)

**Comment by benjistokman** [comment]
That worked, thank you. That's just... it's not that important but it should be changed or the instructions should be linked somewhere.

**Comment by wmontwe** [comment]
Your're welcome. I added your suggestion to our task backlog #7879
