### ISSUE TITLE
Delete icon can hardly be seen due to low contrast

### ISSUE THREAD

**Issue by HelmutL** [thunderbird/thunderbird-android#7868]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Other

### Android version

10

### Device model

Honor View 20

### Steps to reproduce

Open received mail

### Expected behavior

the icons at top should be see clearly

### Actual behavior

very often, the delete icon (trashbin) can hardly be seen due to low contrast.
This does not happen always, but very often. I could not find the conditions when it occurs,

To come back to normal behaviour set the dive to dark mode and view the message again.
The reset the device dark mode. It seem to continue as expected.
![K9Mail](https://github.com/thunderbird/thunderbird-android/assets/17042607/5ae4109e-797a-47fa-aeea-c1acef264993)

**Comment by HelmutL** [comment]
Another way to return to "Normal": 
terminate k9mail and clear it from memory (Swipe)
restart k9mail

**Comment by HelmutL** [comment]
I have seen a red trash in today. Otherwise the same behavior as above.

I am quite sure I did not see this bug in versions up to 6.803

**Comment by cketti** [comment]
This is probably caused by the `MessageListSwipeCallback` setting a tint on the drawables provided by `SwipeResourceProvider` without calling `mutate()` first.

![image](https://github.com/thunderbird/thunderbird-android/assets/218061/127cc7c1-60ed-4304-8c97-6fce9c6ab1d9)
