### ISSUE TITLE
Lack of full information display, for network error message

### ISSUE THREAD

**Issue by mhf1998** [thunderbird/thunderbird-android#7870]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.803

### Where did you get the app from?

Other

### Android version

10

### Device model

Samsung A6

### Steps to reproduce

1. Go welcome screen
2. Click on START
3. Enter an email address
4. Click Next and quickly Turn off the Internet while loading the configuration
5. Click Next

### Expected behavior

We expect the error message to be displayed with full details so that the user can clearly understand the details of the error.

### Actual behavior

In the second line where the error message is shown (network), we see that it lacks full details and the error message is merely a single word, without any explanation...

![photo11660144268](https://github.com/thunderbird/thunderbird-android/assets/34542204/7a8f2d20-2627-4018-b4d2-88c1dd379194)

**Comment by mhf1998** [comment]
I also have another suggestion; I think if this message is going to stay as it is (single-word), at least the positions of the title and the message should be switched. That is, the message, since its text is shorter, should come above, and that title text should go below.

**Comment by Monikasuhagiya** [comment]
We can display message Please check your connection status and try again instead of just Network.

**Comment by mhf1998** [comment]
> I think we need to expose some more information to help identify underlying issues. The network was a placeholder for more fine grained feedback.

Hi @wmontwe 
Could you please clarify the latest status of this issue?
Do you just want to add more details instead of the word 'network'? Can I do this, or would you prefer to suggest the description text yourself?

**Comment by wmontwe** [comment]
@mhf1998 I wanted to add more details, but due to time constraints, I won't be able to work on this soon. You could change it as you suggested.
