### ISSUE TITLE
Unable To Add Folders

### ISSUE THREAD

**Issue by uniquePWD** [thunderbird/thunderbird-android#7885]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 8 Pro

### Steps to reproduce

There's no method to add a folder

### Expected behavior

You should be able to add a folder pretty much anywhere you can interact with them

### Actual behavior

You can't add any folders.

**Comment by cketti** [comment]
Duplicate of #1389
