### ISSUE TITLE
Increase default value for "Fetch messages up to"

### ISSUE THREAD

**Issue by uniquePWD** [thunderbird/thunderbird-android#7892]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 8 Pro

### Steps to reproduce

I received an email from Uber just now and I'm like WTF? So I open the email, scroll to the bottom looking for the unsubscribe link and its not there, instead I see a download full message email. Huh? I'm confused as to what the reasoning for not giving full emails is? 

### Expected behavior

Full emails should be fetched by default. If anything there should be a preference for a minimalist broken experience. 

### Actual behavior

Not even being able to unsubscribe from uber emails because I can't see the bottom of the email.

**Comment by MillionsToOne** [comment]
It's a feature. Not everybody has the bandwith to download possibly tens of emails a day.

**Comment by cketti** [comment]
I don't think we'll change the default to always download complete messages. But we might change it to something larger than 32 KiB. We'll discuss this internally.
