### ISSUE TITLE
why this piggy pink color :-)    -   a function to choose your own color would be great

### ISSUE THREAD

**Issue by He-Zu** [thunderbird/thunderbird-android#7894]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.901

### Problem you are trying to solve

in ver 6.803 the color of the header was gray, which was still acceptable. in 6.901 it is now pink, which looks ugly to me. a setting where you can choose the color yourself would be great - i love gray-blue. 

### Suggested solution

a function for custom color design of the app would be great

### Screenshots / Drawings / Technical details

![Unbenannt](https://github.com/thunderbird/thunderbird-android/assets/116963345/b7a36963-c7af-43db-b8d0-9c2a7cf3c440)

**Comment by linuxct** [comment]
That's part of the Material You implementation from 6.900. I think it would be great if the application would pick up the phone's predominant colour. Probably achievable with `@android:color/system_neutral2_50` or `@android:color/system_accent1_100` or `@android:color/system_accent1_700`, to give a few examples. Or perhaps by inheriting `Theme.Material3.DynamicColors(.Dark)`  :-)

**Comment by wmontwe** [comment]
The theme in 6.9xx versions is currently in an alpha state. Our priority is to establish Material 3 support, followed by improvements to the overall theme. At the moment, we're still using a mix of Material 1 and 2 components and styles throughout the app, which needs to be addressed first.

**Comment by wmontwe** [comment]
I'm closing this and please have a look at #6617 for status updates.

**Comment by flexagoon** [comment]
@He-Zu if you don't like this color you can change it in your phone settings

**Comment by linuxct** [comment]
> @He-Zu if you don't like this color you can change it in your phone settings

Not really, that's the whole point of my comment. Thunderbird does not yet implement Material You, thus the "pink" color is "hardcoded"
