### ISSUE TITLE
Adding Corsican on the list of supported languages

### ISSUE THREAD

**Issue by Patriccollu** [thunderbird/thunderbird-android#7913]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.901

### Problem you are trying to solve

**Corsican** is not yet available on the list of supported languages.

### Suggested solution

Hello,

I would like to contribute to this very interesting project!

That's why I translated the [Weblate files](https://hosted.weblate.org/projects/tb-android/-/co/) in **Corsican (co)**. The localization is now complete!

I also noticed that @cketti prepared Pull Request #7912 to add this brand new language to the list of supported languages. Great!

I look forward being able to test the localization on my Android device ;-)

Best regards,
Patriccollu.

**Comment by Patriccollu** [comment]
@cketti 
Hello,

I would like to know when **Corsican** will be distributed in a future release (which one?) so that I will be able to check the localization.

As I'm newbie on this repository, feel free to tell me if I need to open a new issue for that question or raise it on the [K-9 Forum](https://forum.k9mail.app/).

Best regards,
Patriccollu.

**Comment by cketti** [comment]
The Corsican translation should be included in the next beta version, K-9 Mail 6.902.

**Comment by Patriccollu** [comment]
@cketti
Great! Thank you.
Patriccollu.
