### ISSUE TITLE
open and/or save attachment

### ISSUE THREAD

**Issue by kolAflash** [thunderbird/thunderbird-android#7916]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.803

### Problem you are trying to solve

Sometimes I'm reading a mail and there's a PDF or an image attached, at which I just like to have a quick look. Sometimes looking at one attachment, then looking back at the mail text and then at the other attachment. But I have to need to save it anywhere to the filesystem.

In other occasions there might be a file attached which I like to save but NOT to open. Maybe even a file that looks suspicious to me and I only like to save it for further inspection, but I really don't want to open it.

So when reading a mail, there should be a choice to open and/or save attachments.  
Currently there's only the choice to save attachments. _(tested with PDF attachments in k9mail-6.803 on Android-12)_

_When I say "open" I mean, that the file is being opened by the corresponding app for that file type, not by K-9 Mail itself. Although it might also be OK if some basic file formats like PDFs and images are opened by K-9 Mail itself. The later one is how Thunderbird on the desktop deals with this._

### Suggested solution

Offer some kind of choice. I'd vote for at least two basic options:
- Open the attachment without saving.
- Save the attachment.

Attachments should NOT be opened automatically on save. This was changed many years ago and as I explained above, there's a good reason for that. See also #1256 and #1409 .

### Screenshots / Drawings / Technical details

Related:
- #509 _Open attachment improvements_
- #1256 _attachments opening_
- #1409 _Attachment opening_
- #7557 _Opening an attachment and sharing it back to K-9 Mail fails_
- #7160 _save an attachment k9-mail crashes_

**Comment by cketti** [comment]
K-9 Mail will ask Android to open an attachment for viewing when you tap anywhere in the attachment box except for the save button in the lower right corner. The app will save the attachment when you tap the save button.

**Comment by kolAflash** [comment]
> K-9 Mail will ask Android to open an attachment for viewing when you tap anywhere in the attachment box except for the save button in the lower right corner. The app will save the attachment when you tap the save button.

I just realized that. Sorry for the noise.
