### ISSUE TITLE
mime with multiple text parts

### ISSUE THREAD

**Issue by nanderer** [thunderbird/thunderbird-android#7926]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.802

### Where did you get the app from?

F-Droid

### Android version

10

### Device model

shiftphone

### Steps to reproduce

Open a mail with multiple text parts
See how it shouldnt be
Compare with correct working software like thunderbird

### Expected behavior

All parts shown inline

### Actual behavior

Second part is given as download that cant be opened with any app cause it dosnt contain .txt (generating extensions from mime type for extention less filenames is also a thing that a good MUA dose on operating Systems that require souch backwards thinking stuff like Android, stupid that even a Linux based os shares ms-dos conversation from the 1980s)

See here
![Screenshot_20240611-110027_K-9_Mail](https://github.com/thunderbird/thunderbird-android/assets/45161625/56d17200-6cf9-48b0-a7bd-9de0b964e4a6)

**Comment by cketti** [comment]
The attached file is probably of type `message/rfc822`. K-9 Mail should display contents of this type if the sender meant for it to be an inline part. If it is marked as attachment by the sender, K-9 Mail will only offer to save the file.

We use #733 to track adding support for viewing `message/rfc822` files/attachments.
