### ISSUE TITLE
Don't load sent folder messages "Boîte d'envoi" in french,  with a xxx@laposte.net account ( it's working with thunderbird on windows )

### ISSUE THREAD

**Issue by Superkenel** [thunderbird/thunderbird-android#7934]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

Other

### Android version

iodé os ( based on Android 12 AOSP )

### Device model

Xperia XA2

### Steps to reproduce

1. suscribe to a free email accound on https://laposte.net/inscription?origin=lapostefr
2. put your xxx@laposte.net in K-9 Mail
3. put your code
4. follow K-9 Mail the config is automatic

### Expected behavior

"Boîte d'envoi" send folder don't load its emails from the server.

### Actual behavior

"Boîte d'envoi" send folder must  load and show its emails from the server.

**Comment by dtcmdtcm** [comment]
i'm getting the same problem, my sent folder is not refreshed when i'm sweeping down.
Please find attached the logs.
Thanks in advance for your support.
[k9mail-logs.txt](https://github.com/user-attachments/files/15846217/k9mail-logs.txt)

**Comment by cketti** [comment]
@dtcmdtcm: It looks like you're using Yahoo, not laposte.net. And the log shows your "Envoyés" folder is synced just fine. There just were no new messages on the server.

@Superkenel: Please note that K-9 Mail doesn't automatically check for new messages when you open a folder. Swipe down on the message list to refresh the folder. If that doesn't work, please record a debug log while refreshing the Sent folder.

**Comment by dtcmdtcm** [comment]
Hi cketti, 
i ensure you that i had about a dozen of messages in the sent folder that were not appearing, even sweeping down many times.

i tried something :
send to myself a new one from my phone, sweep down again, and then miracle !! the dozen messages appear !!
That looks like a bug ! no ?!

06-15 10:03:38.721 13400 13421 I ImapSync: Synchronizing folder yahoo:Envoyés
06-15 10:03:38.722 13400 13421 V ImapSync: SYNC: About to get local folder Envoyés
06-15 10:03:38.728 13400 13421 V ImapSync: SYNC: About to get remote folder Envoyés
06-15 10:03:38.729 13400 13421 V ImapSync: SYNC: About to open remote folder Envoyés
06-15 10:03:38.744 13400 13421 D RealImapConnection: Connecting to imap.mail.yahoo.com as imap.mail.yahoo.com/212.82.101.24
06-15 10:03:38.747 13400 13421 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
...

**Comment by cketti** [comment]
@dtcmdtcm: Apologies! What I meant was "from the perspective of an IMAP client everything looked like it should". The server reported 80 messages in the Envoyés folder, and the app had already downloaded all of them. No additional sent messages were visible via IMAP. Maybe that's because they were sent using a different email app and it hadn't uploaded those messages to the server yet. Or it's a problem on Yahoo's side were not all sent messages are immediately available via IMAP. It doesn't appear to be a problem where K-9 Mail is doing the wrong thing.
