### ISSUE TITLE
Mail sent two times with office 365

### ISSUE THREAD

**Issue by debie-A320FL** [thunderbird/thunderbird-android#7938]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v6.803

### Where did you get the app from?

F-Droid

### Android version

CrDroid7 GSI

### Steps to reproduce

1. Set up a microsoft office 365 account
2. Send a mail with the microsoft office 365 account (for instance to yourself)
3. Go in sent mail : two mail are shown "sent"
4. Go in inbox : only one mail is shown

### Expected behavior

Only one mail should be sent

### Actual behavior

Actually two mails are sent (one with K9 mail "your name" (from composition sending mail>defaults settings>Your name) in "header" ; another with the microsoft office name (external to K9 app)).

By setting both name to the same name, it stills send two mail (in sent box)

Note : The other person only receive a single mail / if we delete the received mail, only one mail appears in the trash box

Note2 : I also have a Gmail account in k9 mail, and it works fine (only one mail sent)

![image](https://github.com/thunderbird/thunderbird-android/assets/79523414/d8d445c2-c79c-4279-aed7-232ffa8a8ce8)

**Comment by ByteHamster** [comment]
The problem is that Microsoft behaves in a nonstandard way. For every other provider, the mail client places the sent mails in the "sent" folder. Microsoft creates a copy automatically. That's why you get two copies. You can turn off the option to upload sent messages in K-9 to work around Microsoft's behavior. Then you get only the copy that Microsoft creates automatically.

**Comment by cketti** [comment]
You can find the relevant K-9 Mail setting under *Settings → [Account] → Sending mail → Upload sent messages*.
