### ISSUE TITLE
Unified Sent, Trash and Spam folders just like inbox

### ISSUE THREAD

**Issue by gilluc** [thunderbird/thunderbird-android#7940]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.803 on android 14 pixel 7

### Problem you are trying to solve

No problem, just request.
I just uninstalled BlueMail because of newly discovered severe bugs.
But I miss the feature of unifying any folders...
This would save me time ....
gilles.

### Suggested solution

manage unifying as a new account with merged folders of normal accounts...

**Comment by cketti** [comment]
Duplicate of #6596
