### ISSUE TITLE
Accepting or rejecting appointment requests is not possible

### ISSUE THREAD

**Issue by Markoise** [thunderbird/thunderbird-android#7945]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 7

### Steps to reproduce

1. appointment invitation comes by e-mail
2. buttons for accepting or declining the appointment not available

### Expected behavior

Accepting and rejecting an appointment should be done via buttons that appear accordingly.

### Actual behavior

You can only open the attached .ICS files and add them to the calendar.
However, if you receive a cancellation of the appointment, you have to search for and delete the appointment in the calendar yourself, as K9-Mail unfortunately does not offer any tools for this.

**Comment by ByteHamster** [comment]
Please use the search function before posting issues. This was already requested in #930

**Comment by Markoise** [comment]
Yes, for 9 years. Does this mean that we can no longer expect this functionality?

**Comment by ByteHamster** [comment]
Did you believe creating a duplicate issue would make it any faster? Dealing with duplicates just costs the developers time that they can't spend on actual app development.
