### ISSUE TITLE
Opening the context menu of an email address where a linebreak is right at the place of a dash will replace the dash by a dot

### ISSUE THREAD

**Issue by mags0ft** [thunderbird/thunderbird-android#7957]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.803

### Where did you get the app from?

Google Play

### Android version

GrapheneOS (Android 14) 2024061400

### Device model

Google Pixel 7a

### Steps to reproduce

Open an email where an email address is mentioned that meets the following criteria:

- the address is long, so inside of the context menu where it is printed bigger, it needs to be wrapped onto the next line
- right at the place where the wrap happens, there is a dash in the address

_The image of a problematic address, irrelevant private information overwritten in red:_
![E-Mail in Text](https://github.com/thunderbird/thunderbird-android/assets/113589312/e8d0dab4-316b-4f76-9186-8397355df7a8)

Note how the dash after the "des" is still there.
Now, press and hold this address to open the context menu, which allows you to copy the address, send an email etc.
You will see something like this:

![E-Mail buggy context menu](https://github.com/thunderbird/thunderbird-android/assets/113589312/43a15e9d-d4aa-4f5f-a051-3a964f2a4fbc)

The dash from before is suddenly a dot. **THIS IS NOT JUST VISUAL**. For example, pressing the copy button will copy the FAULTY address. Pressing the "send email" button will open the email editor with the FAULTY address in the header. This can quickly get dangerous if you don't proofread what you copy-paste or send.

_I have verified that the address in the context menu is wrong, not the address in the email text._

### Expected behavior

The context menu displays and shows the correct email address, without any dash truncated by a dot, and it will also behave correctly when doing actions like 

### Actual behavior

K-9 will show a modified, faulty email address with the dash which got wrapped onto the next line replaced by a dot and all actions performed from the context menu will use this wrong address too.

**This is critical because an adversary may be in possession of the newly generated, wrong email address and capture emails by people who don't double check their mails before sending.**

**For example:**

1. Trusted, correct email is: example@long-address-truncated.com
2. Domain by the trusted sender is therefore: long-address-truncated.com
3. Domain by an adversary: truncated.com with a mail server running on the subdomain "long-address"
4. Faulty generated address by K-9: example@long-address.truncated.com
5. This mail address now points to the server of truncated.com, subdomain "long-address", so if the user is not all to careful, they will send the mail to the adversary.

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/15877073/k9mail-logs.txt)

**Comment by cketti** [comment]
K-9 Mail currently doesn't linkify email addresses unless they include the schema part, e.g. `mailto:user@domain.example`. It doesn't look like that's the case in your screenshot. That leads me to believe it's an HTML email. In that case the link text doesn't have to match the actual link. Are you sure it's not a problem in the message itself? Something like…

```html
<a href="mailto:example@long-address.truncated.com">example@long-address-truncated.com</a>
```

**Comment by mags0ft** [comment]
This is indeed an interesting point. I will look into it and come back with the result shortly.

**Comment by mags0ft** [comment]
@cketti Yes, indeed the fault lay in the sender of the email who accidentally misplaced a dot there. There is no Bug in K-9. Sorry for the confusion and thanks for the quick help!

I wish you a great day :)

**Comment by cketti** [comment]
Thanks for checking and reporting back :+1: 

FYI, there's an open feature request to warn users if the link text doesn't match the link URL. See #5014. That functionality would have helped to flag this mismatch.
