### ISSUE TITLE
Account on K-9 forum waiting for validation from an administrator

### ISSUE THREAD

**Issue by Patriccollu** [thunderbird/thunderbird-android#7966]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

n/a

### Where did you get the app from?

None

### Android version

n/a

### Device model

n/a

### Steps to reproduce

Hello,

This request concerns the K-9 community forum but I can't find another place to raise my question. Please transfer my request to the appropriate team or give me the instructions to do that.

I'm Corsican translator and I recently completed the translation of K-9/Thunderbird for Android. I also subscribed to the K-9 forum.

But when I tried to reply to [one of the posts](https://forum.k9mail.app/t/traduction/8811), which was asking some help about translation, I received an error message saying that a new user could not create a post containing more than two external links. So I reduced my post to contain only two links but I received a second error message saying that my account was temporarily on hold and waiting for a validation.

Please can you check?

Best regards,
Patriccollu.

### Expected behavior

I would like to reply to an existing post and/or create a new post!

### Actual behavior

Forum's account blocked.

EDIT: I can sign in to the Forum but I'm still not able, either to Create a new post, or to Reply to an existing post.

When I clicked on _Notifications_ icon and selected _Account temporarily on hold_ , it opened a [Private page](https://forum.k9mail.app/t/account-temporarily-on-hold/8842) and I was just able to reply to this page.

**Comment by wmontwe** [comment]
@Patriccollu Is it working now?

**Comment by Patriccollu** [comment]
Hello @wmontwe 

Yes, I was able to reply to the post I was taking about. My reply is now waiting for an approval... but it's probably normal.

Thank you,
Patriccollu.
