### ISSUE TITLE
K9 opens to "Error" "Folder not found"

### ISSUE THREAD

**Issue by acarrico** [thunderbird/thunderbird-android#7971]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

Google Play

### Android version

10

### Device model

moto g(7)

### Steps to reproduce

1. Open K9 by clicking on the robot mail dog icon
2. See the error

### Expected behavior

Expected to see my IMAP folders.

### Actual behavior

See the screenshot below. I've used K9 for years with no trouble. It was working yesterday, and I'm not aware of any change on my phone overnight. I checked with other people in the household and their K9 is normal, no error, one person on 6.802, and one on 6.804, we all have the same IMAP provider.

If I click the three lines icon, I do see my account listed, and if I click on the account it returns to the Error screen. That's about all the data I have. Thank you!

![Screenshot_20240622-111429](https://github.com/thunderbird/thunderbird-android/assets/1452440/ba1eb6d5-f655-43cb-9e22-b7f22879d711)

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/15937257/k9mail-logs.txt)

**Comment by acarrico** [comment]
One more note: I do have fdroid installed on my phone, but it looks like the K-9 version there is also 6.804.

**Comment by cketti** [comment]
The log shows a database error. It's possible that there was a storage error and the database has been corrupted. It's also possible there was a memory error and now the code to access the database is corrupted and doesn't work like it should. Try rebooting the device. If that doesn't help, try uninstalling the app, then reinstalling.

**Comment by acarrico** [comment]
Weird. Was that database on the internal or external storage? I assume internal, but I saw a k9 dir listed in both, perhaps leftover from the old days? I wonder if I should fsck my external card, but I haven't seen any other issues.

Anyway I did reboot with no change, so I uninstalled. I reinstalled from fdroid and setup my account. 

@cketti, thanks for looking at my issue.
