### ISSUE TITLE
Split Screen Causes Crash

### ISSUE THREAD

**Issue by Ryushin** [thunderbird/thunderbird-android#7987]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.902

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Samsung Tab S8 Ultra (SM-X900)

### Steps to reproduce

In settings, change display to split screen and as soon as it goes back to the email message, the K-9 crashes.  Hold the tablet in portrait and not having split screen K-9 displays the message.  As soon as the tablet is rotated to landscape view K-9 crashes.

### Expected behavior

Split screen showed message list on the left and the open message on the right.

### Actual behavior

K-9 crashes when split screen is enabled.

**Comment by xhajt03** [comment]
Ditto here - Android 11 in my case, the same K9 version from F-Droid. Application crashes immediately either when started in landscape mode or when switching from portrait to landscape.

**Comment by xhajt03** [comment]
[k9mail-logs-240627.txt](https://github.com/user-attachments/files/15997003/k9mail-logs-240627.txt)
Log from my device attached.

**Comment by wmontwe** [comment]
Thanks for the log, we're investigating the issue.

**Comment by xhajt03** [comment]
Unfortunately, still crashing with 6.903.

**Comment by cketti** [comment]
The fix is included in K-9 Mail 6.904.
