### ISSUE TITLE
Translation of first option is truncated on Settings > General > Interaction

### ISSUE THREAD

**Issue by Patriccollu** [thunderbird/thunderbird-android#7996]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.904

### Where did you get the app from?

Other (downloaded from GitHub)

### Android version

11 RP1A.200720.011

### Device model

Xiaomi Redmi Note 8

### Issue details

This issue concerns the option `Volume key navigation in message view` which is the first line on `Settings` > `General settings` > `Interaction`.

I'm Corsican translator for K-9 Mail / Thunderbird for Android and I noticed a problem with its translation.

The problem is that the _field for the translation_ is too small!

### Steps to reproduce

1. Go to `Settings` > `General settings` > `Display` > `Language`
2. Select `Corsu` (Corsican)
3. Go back to `Parametri generali` (General settings)
4. Select `Interazzione` (Interaction)

### Expected behavior

The first option should be displayed as: `Navigà cù u tastu di vulume nant’à a vista di i messaghji`

### Actual behavior

The first option is truncated and displayed as: `Navigà cù u tastu di vulume nant’à a vi...`

In order to reduce the string size, I temporarily changed the translation to:
	`Navigà cù vulume in a vista di messaghji`

Is there a way to increase the string size, for example, to allow the translation on multiple lines? Another suggestion would be to add - just below this option - a comment that could accept multiple lines, to better explain what the option does.

**Comment by kewisch** [comment]
How about something like this? This would allow for a shorter title string with a longer description.

<img src="https://github.com/user-attachments/assets/49bb654a-828f-4c82-b18c-2e3037f1cc07" height="900">

**Comment by Patriccollu** [comment]
Adding a long description is perfect! But how to reduce the title length?
