### ISSUE TITLE
Only one-way syncing for one specific outlook account

### ISSUE THREAD

**Issue by Donkey-Doug** [thunderbird/thunderbird-android#7997]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.903

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Xiaomi Mi 9T Pro

### Steps to reproduce

I have three outlook accounts set up in k9 mail. Two of the accounts work flawlessly, but one is problematic. The issue is that it only syncs one-way. Actions performed in the outlook web interface are synced to K9 mail, but anything done in the K9 mail app for this one specific outlook account is nullified. 

It appears K9 mail fails to sync to outlook for this one specific account.

**Examples**

DELETING MAILS
- If I delete the email in the outlook web interface, this is synced and also deleted in the K9 mail app.
- If I delete the email in the K9 mail app, it appears to be deleted. I can also find it in the deleted folder on the K9 mail app. However, if I wait or refresh manually, the deletion is undone.

READING MAILS
- If I read the email in the outlook web interface, this is synced and it is also marked as read  in the K9 mail app.
- If I read the email in the K9 mail app, it appears to be read at first. However, if I wait or refresh manually the email is again marked as unread.

### Expected behavior

Since I have all settings set such that the app should sync, I expect it to sync. Note that I have 3 outlook accounts set up, all with the same settings. Only one account fails to sync.

### Actual behavior

Any action in K9 mail is never synced to the server and is nullified.

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
>  Note that I have 3 outlook accounts set up, all with the same settings. Only one account fails to sync.

It seems like you used  1 POP(with delete forbidden on the server side) and 2 IMAP.   
Ensure your promise `all with the same settings`  again.

**Comment by Donkey-Doug** [comment]
Could you maybe educate me and tell me where to fix this?
Is this something on outlook's end or in the K9 app?
