### ISSUE TITLE
Enable autofill option for email addressess

### ISSUE THREAD

**Issue by Donkey-Doug** [thunderbird/thunderbird-android#7998]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.903

### Problem you are trying to solve

When I am trying to send an email, I am not able to find anybody's email address. This means I will either have to log into the web interface or the another mail client to be able to determine the email address of the receiver. Other email clients autofill the receiver when starting to type the name.

### Suggested solution

When typing the name of the receiver, provide suggestions.

### Screenshots / Drawings / Technical details

For example, suppose I want to send an email to John_Doe@outlook.com. If I start typing "Jo", then K9 mail should suggest the full email address.

**Comment by cketti** [comment]
If granted the permission to access contacts, K-9 Mail searches local contacts to auto-complete recipients. There's also an "Add from Contacts" action in the menu when composing messages. If this is not working for you, you've probably not synced contacts to your Android device. K-9 Mail doesn't include this functionality. You'll have to use a different app for that.
