### ISSUE TITLE
Email message rendered incorrectly

### ISSUE THREAD

**Issue by tdboorman** [thunderbird/thunderbird-android#8009]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.904

### Where did you get the app from?

Other

### Android version

14

### Steps to reproduce

Open an email message affected by this issue.

### Expected behavior

Email message is rendered correctly.

### Actual behavior

Email message is rendered incorrectly - there is just a row of dots displayed
![Screenshot_20240712-163537_K-9 Mail](https://github.com/user-attachments/assets/096286e7-382d-4570-9461-bf2948bdcbef)
.

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/16196349/k9mail-logs.txt)

**Comment by cketti** [comment]
Please provide the message source of such an email.

**Comment by tdboorman** [comment]
I have uploaded the message source as requested.
[Message_Source.txt](https://github.com/user-attachments/files/16196722/Message_Source.txt)

**Comment by cketti** [comment]
The message renders fine for me in K-9 Mail 6.904.
![screenshot_message_redacted](https://github.com/user-attachments/assets/928abe59-7ccc-4011-913a-16c5cdf6c785)

**Comment by tdboorman** [comment]
I guess it must be a device specific issue then.

**Comment by tdboorman** [comment]
If I copy the message to another folder using Thunderbird, the copied message renders correctly in K-9 Mail.

**Comment by cketti** [comment]
Maybe something went wrong while downloading the message initially. Try clearing local messages under *Manage folders → [Folder] → Clear local messages* (in the menu), then re-download.

**Comment by tdboorman** [comment]
Thank you, that resolved the issue.
