### ISSUE TITLE
Add option to include Sent messages in Unified inbox

### ISSUE THREAD

**Issue by djp101** [thunderbird/thunderbird-android#8012]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.904

### Problem you are trying to solve

There is no option to include Sent messages in Unified inbox.

### Suggested solution

Add option to include Sent messages in Unified inbox, like i.e. Aqua Mail.

**Comment by cketti** [comment]
You can already include sent messages in the Unified Inbox by going to *Manage folders → [Sent folder name]*, then enabling the "Unify" option.

**Comment by djp101** [comment]
> You can already include sent messages in the Unified Inbox by going to _Manage folders → [Sent folder name]_, then enabling the "Unify" option.

I looked for it everywhere but there, thank you!

**Comment by djp101** [comment]
Option was already implemented in manage folders section.
