### ISSUE TITLE
Rogue Feature That Automatically Converts Plain Text Emails to HTML-look Should Not Be Happening

### ISSUE THREAD

**Issue by Lesita** [thunderbird/thunderbird-android#8017]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

(latest version on Google Play as of 21/7/2024)

### Where did you get the app from?

Google Play

### Android version

13 with Lineage OS

### Steps to reproduce

Open a received email message which has plain text with at least one single line containing only equal signs (=) on K-9 Mail. The email will have a HTML look with a line separator instead of multiple equal signs, which suggests that HTML instead of plain text  was used on that email.

### Expected behavior

Plain text emails should only have characters displayed. This design will cause misunderstanding between the sender and recipient.

### Actual behavior

A line separator is displayed for plain text emails having only euqal signs on at least one line in the context.

### Logs

NOTICE: This bug report was submitted using the new GitHub issue form, and the tag "unconfirmed" cannot be edited by the poster. This has been confirmed as a bug or an intentionally-designed rogue feature.

**Comment by cketti** [comment]
This is done intentionally. See https://github.com/thunderbird/thunderbird-android/blob/b67649dd4201949a86cfe87c425e468317a870c6/legacy/core/src/main/java/com/fsck/k9/message/html/DividerReplacer.kt

The app is converting a plain text body to HTML before displaying it. During that conversion quite a few changes are made, e.g. quote characters are removed and quoted text is turned into (nested) block quotes. That's done to improve the usability of plain text messages. While this behavior may have resulted in a misunderstanding in your case, it is appreciated by a lot of users.

I don't see us adding a setting to turn off this behavior. If you need an email client that displays plain text bodies as-is, K-9 Mail is probably not the right choice for you.
