### ISSUE TITLE
Send the file name with extension when sharing/opening to another app

### ISSUE THREAD

**Issue by williamdes** [thunderbird/thunderbird-android#8045]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

Google Play

### Android version

14

### Steps to reproduce

- Go to an email with a PDF attachment 
- Click it
- Open with a PDF viewer (google pdf viewer or GrapheneOS's PdfViewer)  (https://github.com/GrapheneOS/PdfViewer/issues/334)
- Click on share and use K-9 mail, write an email and notice the attached file has no extension

if you actually send the email thinking you attached a PDF, without any file extension the recipient will not be able to use it.

Maybe this is related to https://github.com/thunderbird/thunderbird-android/issues/2789

### Expected behavior

Have the .pdf extension

### Actual behavior

No extension

I actually thinked it was due to GrapheneOS's PdfViewer: https://github.com/GrapheneOS/PdfViewer/issues/334
But they said it is in K-9 mail and say it also can be reproduced by using google pdf viewer

**Comment by Mino260806** [comment]
I'm able to reproduce it. I'll take the issue
