### ISSUE TITLE
Plain appended PGP encrypted mails destroys mail body due OpenKeychain result

### ISSUE THREAD

**Issue by bitstreamout** [thunderbird/thunderbird-android#807]
I had written a mail to service@oppodigital.com and the answer is visible for a second or less and will be overlain by the result of OpenKeychain.  The reasone seem to be that in the answer mail from oppodigital.com, there is a line with "________________________________________" and after this my orignal mail starting with "From: bitstreamout bitstreamout@gmail.com", the line with the Sent date as well as the To, the Subject line, an empty line , and the "-----BEGIN PGP SIGNED MESSAGE-----" causes that k9mail starts OpenKeychain to verify the signature (which is OK) but then erase the mail body with the result.  This I've tested also with the alpah version v5.107.  If required I can attach a compressed version of the orignal mail.

bitstreamout

**Comment by bitstreamout** [comment]
After converting the orignal mail from gmail into mbox format mutt 1.5.24 can do the job ... including verifying the PGP signature ;)

bitstreamout

**Comment by Valodim** [comment]
It's not obvious what the correct way to handle this would be. I thought about this for a while, and I think as a general rule, the first part of an email should be treated as its primary content, which means I would treat a pgp/inline part which occurs in the middle of an email as an encrypted attachment, and display the text before as the primary content of the email.

To get rid of the short term problem here, we could simply anchor the search pattern for pgp inline blocks to the beginning of the text. Given that this is a very rare use case to begin with (caused mostly by K9 itself), and that my roadmap includes a lot of time to work on this area in general, this approach seems like a reasonable effort/gain tradeoff for now.

**Comment by cketti** [comment]
A proper solution should probably split the message into multiple parts for display, e.g. unsigned prefix, signed part, unsigned suffix.

The short term solution sounds good to me.

**Comment by alanthehat** [comment]
I recall there being a [Verify] button in the top-right of the message. Does this only appear when using APG?
