### ISSUE TITLE
In-App "User Manual" Link/Destination Broken; Receive a 404: Not Found" Error

### ISSUE THREAD

**Issue by Horseshoes-and-Handgrenades** [thunderbird/thunderbird-android#8082]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

Google Play

### Android version

14 (Build Number: AP2A.240805.005)

### Device model

Pixel 8 (Standard, NOT Pro)

### Steps to reproduce

1. Tap hamburger menu
2. Select ***Settings***
3. Under the **Miscellaneous** section heading, tap ***User Manual***

### Expected behavior

Open a user manual docs site, e.g. a GitHub pages site, containing end-user documentation.

### Actual behavior

 - [User Manual Link](https://docs.k9mail.app) opens in default or selected web browser
 - Site response from GitHub Pages is "404: Not Found"
![Screenshot_20240825-160249](https://github.com/user-attachments/assets/d7118d02-ae2c-4112-b050-719391a1211b)

**Comment by Horseshoes-and-Handgrenades** [comment]
### Update/Addition
The in-app link appears to be the intended link to the User Manual, but the Manual is what's actually broken as I noticed [the same User Manual link is in the thunderbird-android repo README](https://github.com/thunderbird/thunderbird-android?tab=readme-ov-file#need-help4)

#### Small Apology Regarding Filing Location of this Issue
If the repo that powers the GitHub Pages site is not this one and is publicly accepting issues, then I apologize for not filing this issue in that repo, instead.

**Comment by cketti** [comment]
We've abandoned the user manual because we don't have resources to keep it up-to-date. However, I've now restored the last version and added a deprecation notice: https://docs.k9mail.app/en/6.400/

The in-app link to the user manual will be removed in the next stable release.
