### ISSUE TITLE
Compose shortcut for frequent contacts

### ISSUE THREAD

**Issue by orschiro** [thunderbird/thunderbird-android#8086]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

Latest

### Problem you are trying to solve

Hi team, 

Wonderful app!

Could a shortcut feature be added to this screen by which you can quickly start composing a message to frequent contacts?

### Suggested solution

Similar apps such as Fairmail and Gmail provide this feature, too.

![image](https://github.com/user-attachments/assets/8403240d-2118-4229-a1c0-85ef7c061fbf)

**Comment by orschiro** [comment]
Example Fairmail:

![image](https://github.com/user-attachments/assets/4fb9f3be-432c-4829-a036-772fcd12c2c8)

**Comment by kewisch** [comment]
This would make a great feature suggestion people can vote on at https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird%20android . Would you mind posting it there instead? Much appreciated!
