### ISSUE TITLE
Add setting for app telemetry

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#8089]
Add a setting to disable app telemetry.

Since telemetry will only be added to Thunderbird for Android, not K-9 Mail, the setting should only be visible in Thunderbird. However, our code is currently not prepared to support app-specific settings. Because we want to ship Thunderbird for Android sooner rather than later, we're fine with taking a shortcut now and implementing a proper solution later.

**Comment by ilikenwf** [comment]
Are we sure that K-9 doesn't include any telemetry?
