### ISSUE TITLE
Report a possible race issue

### ISSUE THREAD

**Issue by baigd** [thunderbird/thunderbird-android#809]
Hi, Developers of k9mail/k-9,

I am writing to report a race issue on use of ConcurrentHashMap. The issue is reported by our tool in an automatic way. Although manually confirmed, it would be a false positive, given we do not know the specification of the program. We would very appreciate if you could check below for details and confirm with us whether it is a real problem. For more information, please refer to our website: http://sav.sutd.edu.sg/?page_id=2845

File: k9mail/k-9/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java
Location: Line (4600/4603, 5131)
Description: 
The get-then-put operations (line 4600, 4603) in method "getNotificationData" are synchronized on lock "notificationData". If the intention is to guarantee the atomicity of the get-then-put operations, then the remove operation in line 5130 may break this atomicity. Relying on the ConcurrentHashMap to ensure exclusive access is dangerous since ConcurrentHashMap has no guarantee of exclusive access.

**Comment by cketti** [comment]
Thanks for doing the research and reporting this! The issue found by your tool is indeed a bug.

On a small side note: It would have been helpful if you had included the Git SHA of the revision you were analyzing.

The surrounding code also contains a few concurrency issues. But almost all of it was rewritten in PR #795. If you have some time it'd be awesome if you ran the analysis again after the feature has been merged.

**Comment by cketti** [comment]
The new notification code was merged.
