### ISSUE TITLE
Disable background service when Android synchronization is off

### ISSUE THREAD

**Issue by Massedil** [thunderbird/thunderbird-android#8092]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.904

### Where did you get the app from?

F-Droid

### Android version

LineageOS 21 / Android 14

### Steps to reproduce

Set : 
- Parameters
- General parameters
- Network
- Background sync : `when automatic sync is enabled`

Now disable automatic sync in Android parameters.

### Expected behavior

K9 sees that automatic sync in Android is disabled and stops the background service (same as K9 parameters > General parameters > Network > Background sync : `never`) .

When automatic sync in Android is enabled, K9 starts the background service (same as K9 parameters > General parameters > Network > Background sync : `always`).

### Actual behavior

K9 background service is started even if Android sync is off.

![22](https://github.com/user-attachments/assets/9d60463c-6685-4b1d-95f8-8d167fd3cad5)
![21](https://github.com/user-attachments/assets/fdde426b-0a81-46e3-871a-e0b97bcf5098)

**Comment by cketti** [comment]
We want Push to be resumed when background sync is enabled again. The only way to accomplish that is to keep the Push service "running". However, it's not doing anything while background sync is disabled. So there's no negative impact on battery life.

**Comment by cketti** [comment]
It's not impossible to be notified when the Android background sync setting is changed. However, if K-9 Mail is in the background at that time, it is not allowed to start the foreground service that is necessary for Push. Keeping the service around avoids this problem.
