### ISSUE TITLE
Archive message direct from notification

### ISSUE THREAD

**Issue by orschiro** [thunderbird/thunderbird-android#8094]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

Latest

### Problem you are trying to solve

Would be nice to archive a message directly from this screen:

### Suggested solution

![image](https://github.com/user-attachments/assets/45a89d86-0591-4a74-bd07-c8174c601706)

**Comment by cketti** [comment]
See #3530
