### ISSUE TITLE
Message body not displayed

### ISSUE THREAD

**Issue by mikhirev** [thunderbird/thunderbird-android#8114]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804, 6.904

### Where did you get the app from?

F-Droid

### Android version

GrapheneOS 13

### Device model

Pixel 4a

### Steps to reproduce

I don't know what triggered the error. Everything worked perfectly until recent. I didn't change any settings or install K-9 updates before that. After the bug appeared I updated it from 6.804 to 6.904 but that didn't help. The only updates I installed these days were Vanadium browser and Vanadium WebView. The new Vanadium version is 128.0.6613.127.0.

1. Open any e-mail.

### Expected behavior

Display the e-mail text.

### Actual behavior

E-mail text is not displayed. Even if it was shown in a notification.

9.804:
![Screenshot_20240905-215518](https://github.com/user-attachments/assets/135523f3-8988-4879-81e3-21216e135c49)
![Screenshot_20240905-215531](https://github.com/user-attachments/assets/daf65899-cbb7-4032-bdc6-440208a42a55)
9.904:
![Screenshot_20240905-222953](https://github.com/user-attachments/assets/be40217d-ac74-42b6-8519-b8fedd5567ba)

### Logs

This error repeated many times:
```
09-05 22:22:59.343 30414 30451 E OpenGLRenderer: Unable to match the desired swap behavior.
```

This part could be related to recently updated WebView:
```
09-05 22:23:10.513 30414 30414 I WebViewFactory: Loading app.vanadium.webview version 128.0.6613.127.0 (code 661312733)
09-05 22:23:10.517 30414 30414 W ziparchive: Unable to open '/data/app/~~8lGjfZ-G4A97ongGGXNoig==/app.vanadium.trichromelibrary_661312733-bie30ZUsnMmcIJ24z6KfxQ==/base.dm': No such file or directory
09-05 22:23:10.517 30414 30414 W ziparchive: Unable to open '/data/app/~~8lGjfZ-G4A97ongGGXNoig==/app.vanadium.trichromelibrary_661312733-bie30ZUsnMmcIJ24z6KfxQ==/base.dm': No such file or directory
09-05 22:23:10.517 30414 30414 W com.fsck.k9: Entry not found
09-05 22:23:10.538 30414 30414 E WebViewLibraryLoader: can't load with relro file; address space not reserved
09-05 22:23:10.568 30414 30414 I cr_WVCFactoryProvider: version=128.0.6613.127 (661312733) minSdkVersion=29 isBundle=false multiprocess=true packageId=2
09-05 22:23:10.594 30414 30568 W System  : ClassLoader referenced unknown path: 
09-05 22:23:10.610 30414 30414 I cr_LibraryLoader: Successfully loaded native library
09-05 22:23:10.611 30414 30414 I cr_CachingUmaRecorder: Flushed 6 samples from 6 histograms, 0 samples were dropped.
09-05 22:23:10.616 30414 30414 I cr_CombinedPProvider: #registerProvider() provider:WV.f7@de9c763 isPolicyCacheEnabled:false policyProvidersSize:0
09-05 22:23:10.617 30414 30414 I cr_PolicyProvider: #setManagerAndSource() 0
09-05 22:23:10.647 30414 30414 I cr_CombinedPProvider: #linkNativeInternal() 1
09-05 22:23:10.647 30414 30414 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10129; state: ENABLED
09-05 22:23:10.648 30414 30414 I cr_AppResProvider: #getApplicationRestrictionsFromUserManager() Bundle[EMPTY_PARCEL]
09-05 22:23:10.648 30414 30414 I cr_PolicyProvider: #notifySettingsAvailable() 0
09-05 22:23:10.648 30414 30414 I cr_CombinedPProvider: #onSettingsAvailable() 0
09-05 22:23:10.648 30414 30414 I cr_CombinedPProvider: #flushPolicies()
```

No other errors in log.

**Comment by mikhirev** [comment]
The issue has wonderfully fixed after reboot. I feel myself like in good old win95 times.

**Comment by mikhirev** [comment]
@cketti why you closed this issue? There's some bug in code that caused it. The problem is solved for me, the bug persists.

**Comment by cketti** [comment]
It was most likely a problem with GrapheneOS's custom WebView implementation. But even if it was something else, without any way to reproduce the issue there's nothing we can do.

If someone can provide actionable details we can reopen this issue.
