### ISSUE TITLE
Wrong folders listed for account

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird/thunderbird-android#8137]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.904

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Samsung Galaxy S23

### Steps to reproduce

1. Go to navigation drawer.
2. Folder list doesn't match the folder list for the selected account (screenshot attached)
![Screenshot_20240912_061523_K-9 Mail](https://github.com/user-attachments/assets/7b8ea39f-57d8-4c3c-871d-db982b6da662)

### Expected behavior

The drawer should list the selected account's folders.

### Actual behavior

While viewing an IMAP account with only the most basic folders, my Thunderbird.net (Google workspace account) folders were displayed instead. selecting another account and re-selecting the original caused the proper folders to populate. I have now seen this happen twice over the last two days.

**Comment by wmontwe** [comment]
@ryanleesipes while working on the drawer I discovered that this could happen in some cases. The new drawer implementation should fix this. Worth testing again when we fixed the remaining tasks of #8100

**Comment by ryanleesipes** [comment]
Thank you for this background @wmontwe - appreciate it!

**Comment by wmontwe** [comment]
@ryanleesipes Do you still experience this issue?

**Comment by ryanleesipes** [comment]
😅

I'm not sure because I moved to Thunderbird for Android. I don't experience it there.

**Comment by wmontwe** [comment]
Okay, I'll close this one and we could open it again if fails again.
