### ISSUE TITLE
Import settings not working in Thunderbird Daily APK

### ISSUE THREAD

**Issue by Alecaddd** [thunderbird/thunderbird-android#8138]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

0.1a1

### Where did you get the app from?

Other

### Android version

14 - One UI 6.1

### Device model

Samsung S22

### Steps to reproduce

1. Have K-9 installed and configured on your device
2. Install Thunderbird Daily APK
3. Launch TB without any existing profile
4. Select import settings (you can also do it from the Settings page if you can't start with a fresh profile)
5. Select "Import from app"
6. Select K-9 Mail from the list of available apps

### Expected behavior

Settings should be imported

### Actual behavior

An error appears at the bottom left stating `Failed to read settings file`.

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/16982758/k9mail-logs.txt)

**Comment by da-anda** [comment]
just had the same issue testing beta1 on Android14

**Comment by cketti** [comment]
This is because the installed K-9 Mail version doesn't support the export functionality. For this feature to work at least K-9 Mail 8.0b1 needs to be installed.

**Comment by da-anda** [comment]
sorry, in case you already got a notification - I was signed in to the wrong github account before (work account).

so you first have to update K-9 to 8.0b1 (= same codebase as Thunderbird b1) so that you can import into Thunderbird b1. Good to know, thanks.

**Comment by develroo** [comment]
Perhaps that step needs to be fleshed out in the blog or FAQ? As the error makes it non-obvious that K9-mail is not the latest version.

**Comment by ordex** [comment]
K9 is stuck on version 6.804.
Where can we find version 8.0b1?

I joined as beta tester for k9, but there is no update whatsoever.

**Comment by vvirtues** [comment]
this repo, under the thunderbird android release there's the k9 beta

**Comment by Taomyn** [comment]
When is the updated beta APK going to be released through Play Store for beta users?
