### ISSUE TITLE
Add alternative app icon

### ISSUE THREAD

**Issue by kryptobolt07** [thunderbird/thunderbird-android#8141]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.904

### Problem you are trying to solve

The current K9 Mail app icon has a unique and peculiar appearance, which may not be favored by all users. To provide a more customizable experience and cater to different preferences, I suggest offering additional app icon options.

**Similar issues/feature requests:**

- #5509 

### Suggested solution

For example, an option to switch to the **Thunderbird desktop client icon** or a more **generic email client icon** could give users more flexibility in how the app appears on their devices.
Or maybe allow setting an account icon as the app icon.

This would enhance the user experience by allowing personalization of the app’s visual appearance, aligning it with individual aesthetic preferences or other email clients users may be familiar with.

**Suggested Features:**
- Add multiple alternative app icons.
- Include icons such as the Thunderbird desktop client or other commonly recognized generic email icons or either allow account icons to be set as app icon.
- Provide a simple way in settings to switch between different icon styles.
Thank you!

**Comment by kewisch** [comment]
If you'd like to see the Thunderbird icon please check out Thunderbird for Android. https://play.google.com/store/apps/details?id=net.thunderbird.android.beta

I think it would add too much complexity to switch app icons at this time, though we might consider a theming approach in the future where people who prefer the K-9 looks could apply a theme to Thunderbird to make that happen.

For now I am closing this issue, but I'll keep this in the back of my mind when we look into theming. Thanks for reporting!
