### ISSUE TITLE
[EPIC] Funding

### ISSUE THREAD

**Issue by wmontwe** [thunderbird/thunderbird-android#8154]
Implement a basic financial contribution appeal in Thunderbird for Android, allowing users to contribute to the project's funding.

This initial implementation will use Google Play Billing and is only enabled for apps distributed through the Google Play Store. Other distribution channels (e.g. sideloading, F-Droid) will default to a no-op.

Tasks:

- https://github.com/thunderbird/thunderbird-android/issues/8152
- https://github.com/thunderbird/thunderbird-android/issues/8160
- https://github.com/thunderbird/thunderbird-android/issues/8161
- https://github.com/thunderbird/thunderbird-android/issues/8162
- https://github.com/thunderbird/thunderbird-android/issues/8163

Reference:

- [Integrate Google Play Billing Library](https://developer.android.com/google/play/billing/integrate#kts)

**Comment by shuvashish76** [comment]
> Other distribution channels (e.g. sideloading, F-Droid) will default to a no-op.

> https://gitlab.com/fdroid/fdroiddata/-/blame/master/metadata/com.fsck.k9.yml#L9

For F-Droid the donation link is already mentioned in metadata but still maybe redirect to this link when the user click such _option from the app_?

**Comment by shuvashish76** [comment]
> https://pointieststick.com/2024/08/28/asking-for-donations-in-plasma/

Maybe add similar behavior... something like
1. Add a floating dialog with description for donation
2. Under that two options/_chip_
   - Donate (redirect the user to website for donation)
   - No thanks (reappear this dialog in every month)
3. -  [ ] "Never show this again" checkbox. If the user click the checkbox then perform either of the chip action then this donation dialog wouldn't appear ever in future. Still the option to find the donation link will be in "Settings > About" section of the app.
