### ISSUE TITLE
Implement subscription ui flow

### ISSUE THREAD

**Issue by wmontwe** [thunderbird/thunderbird-android#8163]
Design:

![Support -_ Choose amount v01 1](https://github.com/user-attachments/assets/bcf35dc3-ac5c-4ffa-a8d5-530918771509)

**Comment by MillionsToOne** [comment]
Will this also be enabled for first time installs like the desktop version of Thunderbird does? And will it pop up regularly or will it just be there?

**Comment by kewisch** [comment]
We haven't worked out the cadence yet, but the first time install might be a bit too early. Folks need to have a chance to use the app before they make this decision. On desktop it works because there is more screen space and the message does not get in the way.
