### ISSUE TITLE
"Sent” folder: Missing space between "To" and address

### ISSUE THREAD

**Issue by AS98765** [thunderbird/thunderbird-android#8170]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

None

### Android version

GrapheneOS

### Steps to reproduce

Imo not necessary.

### Expected behavior

Space.

### Actual behavior

Missing space.

![Screenshot 2024-09-25 143623 - ss](https://github.com/user-attachments/assets/c4cb1785-2874-47e0-9e06-4155072c7330)

**Comment by kewisch** [comment]
Thanks for reporting, can confirm. This should be a super easy fix if all goes well, would you be interested in looking into it?

**Comment by alvar0liveira** [comment]
Hey! 

I'm interested in contributing to this issue.

I already found a solution but I don't if a good way to solve it.

I changed the `getRecipientDisplayNames` in `MessageHelper.kt` in line 37 to append a whitespace before append the recipients list.

Also I saw that you don't have unit tests for this method, if you agree I can write some

Hope to get your feedback.

Thanks!

**Comment by kewisch** [comment]
@alvar0liveira I'm excited you're ready to contribute! Why don't you go ahead and send a pull request with what you have? The team will take a look and review. Unit tests would be great!
