### ISSUE TITLE
forward a mail with attachment failed 

### ISSUE THREAD

**Issue by bigger945** [thunderbird/thunderbird-android#819]
### Actual  behaviour

there's two cases:
1.get a mail with inline images
2.get a mail with attachment

Two mail has been down fully in my k9 client.  
When forward,both toast:"Some attachments cannot be forwarded because they have not been downloaded.".
 If ignore this error to forward,the inline images or attachment can not be send to others.
### Expected behaviour

The two case should forward correctly
### Steps to reproduce

1.forward a mail to somebody with inline images or with attachment.
2.both toast "Some attachments cannot be forwarded because they have not been downloaded.".
3.click forward btn ok
4.login in somebody's mail to get these two mails
5.images inline can not show and also without attachements
### Environment

K-9 Mail version:
check out from github  on 28.9.2015

Android version:
4.3
Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by jiang11958** [comment]
IMAP also has this problem

**Comment by Valodim** [comment]
assigned this to myself, this will be fixed as part of decrypted reply when the source message is loaded using MessageLoaderHelper
