### ISSUE TITLE
Unable to see all folders, only the Outbox folder shown

### ISSUE THREAD

**Issue by csarven** [thunderbird/thunderbird-android#8194]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Other

### Android version

14 (LineageOS 21)

### Steps to reproduce

1. Export K-9 Mail settings (to file)
2. Import K-9 Mail settings in Thunderbird Beta v8.0b1
3. Enter email password

### Expected behavior

The UI should show all folders, e.g., inbox, drafts, sent, junk (as in K-9 Mail)

### Actual behavior

The UI only shows the Outbox folder. The "Manage folders" setting only lists Outbox. The option to show all folders had not effect. The "Folders to display" setting is "All" under Account settings/Folders

**Comment by csarven** [comment]
@imjuzcy Of course I typo'd the password. All okay now. Thanks!

**Comment by csarven** [comment]
Perhaps worthwhile to throw the error to the user so they can retry authenticating. I didn't get such error so assumed it was fine. Only on doublechecking the password under the settings helped me to correct it.

**Comment by aubertc** [comment]
> There's something wrong with the connection of the server and failed silently.

Yes, I had the exact same issue. The connection was deemed unsecure but Thunderbird-android showed no warning and failed silently. 

> Go to Settings -> Account settings (for each account) -> Fetching mail -> Incoming server, then Next, it'll verify the server settings and notify you of any errors.

This workaround worked, but it took me a while to figure it out. Reporting connection issues would be best, I would suggest to re-open this issue.
