### ISSUE TITLE
Thunderbid Beta cannot be installed on Android 5.1.1

### ISSUE THREAD

**Issue by ramonagavrilescu** [thunderbird/thunderbird-android#8198]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

5.1.1

### Device model

Galaxy Tab A(2016)

### Steps to reproduce

1. Search Thunderbird Beta on Google Play
2. Install it.

### Expected behavior

2.Thunderbird successfully installed.

### Actual behavior

2. Your device is not compatible with this version message is displayed, even if Thunderbird app should support Android 5.0 and up.

#### Notes
Tried to install K-9 mail on the same device and it worked.

**Comment by ThePillenwerfer** [comment]
The version from here installs on my Fifth Generation Kindle Fire running Android 5.1.1.

**Comment by ramonagavrilescu** [comment]
Installed the new version 8.0b2 on Galaxy tab  A, Android 5.1.1 and it was successfully installed.

**Comment by kewisch** [comment]
I'm suspecting this is due to old architectures not supported anymore, possibly mips. I think we'll just have to live with this, the architecture has been deprecated since 2018 or so. Thank you for reporting though, and @ThePillenwerfer for confirming it works on other Android 5 devices!
