### ISSUE TITLE
Switching to another language doesn't change the interface

### ISSUE THREAD

**Issue by Fjoerfoks** [thunderbird/thunderbird-android#8200]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

10

### Device model

Samsung A7

### Steps to reproduce

1. Got to Settings
2. General settings
3. Display
4. Language
5. Change to another language different from the default Android language

### Expected behavior

Interface to appear in the selected language.

### Actual behavior

Thunderbird stays in the default language.
BTW: K-9 Mail 6.904 does this properly.

**Comment by wmontwe** [comment]
@Fjoerfoks It should work, but based on the selected language it might not be fully translated. Our current threshold to integrate translations is 70%. What language did you try?

**Comment by Fjoerfoks** [comment]
I have tried Frisian, Italian and German, all to no avail.
I assume the translation are the ones from K-9 Mail at https://hosted.weblate.org/projects/tb-android/#languages?

**Comment by wmontwe** [comment]
Yes, the translation are taken from Weblate and are similar to K-9 Mail. 

Your case looks like an error, could you try the to enable [LoggingErrors](https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors) and post the debug log here?

**Comment by Fjoerfoks** [comment]
[k9mail-logs[1].txt](https://github.com/user-attachments/files/17204003/k9mail-logs.1.txt)

**Comment by cketti** [comment]
I was able to reproduce this behavior with the app installed via Google Play and switching to a language that is not configured as device language.

My guess is that the APK built for the device simply doesn't include additional languages. Switching to the AppCompat mechanism for app languages probably fixes that problem. See https://developer.android.com/guide/topics/resources/app-languages
