### ISSUE TITLE
Accounts Are Confusing To Navigate From Drawer

### ISSUE THREAD

**Issue by uniquePWD** [thunderbird/thunderbird-android#8205]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 8 Pro

### Steps to reproduce

1. Open Thunderbird
2. Click Account Name

### Expected behavior

There should be an indication that there's other accounts and what they are. You can toggle through the accounts but there's no suggestion that there's a way to pick specifically. On top of that, when you have multiple accounts from the same domain, they all just display the same thing, so there's no way to know which account you're trying to select, even when you press Show Accounts, which should be true by default. 

### Actual behavior

See above.

**Comment by fnxweb** [comment]
Indeed, this is awful. You can set a colour for each account, buy the name assigned to each account is simply ignored in the selection list until it is selected. I have three accounts against the same domain name but different TLDs, and each only appears as the first two letters of that domain, so therefore the same two letters three times! 

Additionally, and maybe it's just me, the account selection seems _deeply_ counter intuitive. I'm still not sure entirely how account selection works, I think maybe clicking one pushes it up to the top but... I dunno, they seem to keep moving around. Maybe it would be more obvious if I didn't have three near identical account circles with the same 2 letter “name” to select from.

**Comment by kewisch** [comment]
There are a few other issues filed that should cover this, we definitely need to make some changes
* The accounts drawer is shown by default now
* #8381 covers the letters

Thanks for bringing this up!
