### ISSUE TITLE
Back button on Import Settings screen has no accessible name

### ISSUE THREAD

**Issue by dankeck** [thunderbird/thunderbird-android#8217]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 5

### Steps to reproduce

1. Start with a fresh install of Thunderbird Beta.
2. Start the Android TalkBack screen reader.
3. Open Thunderbird Beta.
4. Click "Import settings" on the introduction screen.
5. Use TalkBack to navigate to the back arrow button at the top of the Import settings screen.
![An Android screen titled Import settings. To the left of the title, an arrow pointing left is highlighted.](https://github.com/user-attachments/assets/b143df9e-05f5-498e-9387-56ab23f67b6d)

### Expected behavior

TalkBack says the purpose of the button, such as "back".

### Actual behavior

TalkBack just says "button" and does not convey the purpose of the button.

**Comment by kewisch** [comment]
This should be fixed by #8172 in the next beta. Thank you for caring about accessibility in Thunderbird for Android!
