### ISSUE TITLE
Star button on message reading screen has no accessible name 

### ISSUE THREAD

**Issue by dankeck** [thunderbird/thunderbird-android#8218]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 5

### Steps to reproduce

1. Start the Android TalkBack screen reader.
2. Open Thunderbird Beta.
3. Open an email message.
4. Use TalkBack to navigate to the star icon to the right of the email message subject.
![Thunderbird Beta email message screen. The subject is visible, which reads New app(s) connected to your Microsoft account. To the right of the subject is an icon of a star outline.](https://github.com/user-attachments/assets/d269da16-9746-427c-8d05-6aba057bd587)

### Expected behavior

TalkBack says the purpose of the button, such as "star" or "favorite".

### Actual behavior

TalkBack says "unlabeled button" and does not convey the purpose of the button.

**Comment by fatemahKordy** [comment]
could i solve this issue

**Comment by sahishnu111** [comment]
**“I am new to this, but I would like to contribute to resolving this issue. May I give it a try?”**

**Comment by kewisch** [comment]
@sahishnu111 Great that you'd like to contribute. I missed your message, but in the future feel free to let people know you're getting started and then send a pull request when you are ready. You do not need permission to contribute :)

**Comment by Yogeshjindal** [comment]
This issue is fixed by PR#8246 , So this issue can be closed from here.
