### ISSUE TITLE
Allow for moving mail from the Unified Inbox

### ISSUE THREAD

**Issue by uniquePWD** [thunderbird/thunderbird-android#8220]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b

### Where did you get the app from?

Google Play

### Android version

14

### Device model

P8P

### Steps to reproduce

1. Open Thunderbird
2. Scroll through mail 
3. Go to move mail to relevant folders

### Expected behavior

Should be simple

### Actual behavior

Option is missing as you're in unified inbox mode

**Comment by cketti** [comment]
Duplicate of #5709
