### ISSUE TITLE
"Next" button in permission screen can't be selected when TalkBack is enabled

### ISSUE THREAD

**Issue by jackf723** [thunderbird/thunderbird-android#8224]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

Android 15 Beta

### Device model

Pixel8Pro

### Steps to reproduce

Bugs encountered while using TalkBack:
Bug number 2: Improve the Experience Screen
1. Enable contacts sync.
2. Enable notifications.

### Expected behavior

Expected behavior: The app enters the inboxes.

### Actual behavior

Actual Behavior: The "Improve the Experience" screen continues to appear, and the back button doesn't work. The only way to get past this screen accessibly is to close the app and restart it.

**Comment by cketti** [comment]
To make it easier to keep track of bugs, please create one issue per bug. I edited the description to remove the first bug. It's already tracked under #8217.

As for the second bug. Granting all permissions does not automatically advance to the next screen. For that to happen you have to press the "Next" button in the bottom right of the screen. I can confirm that it can't be selected when TalkBack is enabled.
