### ISSUE TITLE
Configuration of riseup accont is not automatic 

### ISSUE THREAD

**Issue by yodatak** [thunderbird/thunderbird-android#8229]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

lineageos 14

### Device model

Google pixel 8

### Steps to reproduce

Add a account xxxx.riseup.net
And it canot find autoconfig

### Expected behavior

Autoconfig

### Actual behavior

No autoconfig

**Comment by cketti** [comment]
Their Autoconfig at https://autoconfig.riseup.net/mail/config-v1.1.xml uses a deprecated value of "plain" for the authentication type. I've contacted them with information on how to update the configuration.

We could add support for the deprecated value to the app. However, we want the ecosystem to move forward, not backwards. I'm confident Riseup will update their config and resolve this issue for you.

**Comment by cketti** [comment]
Riseup adjusted the configuration and Thunderbird for Android & K-9 Mail are now able to automatically find the server settings.
