### ISSUE TITLE
Package aab contains all package ids

### ISSUE THREAD

**Issue by kewisch** [thunderbird/thunderbird-android#8240]
Feel free to close this if it isn't a problem, but I randomly noticed the b1 AndroidManifest from the aab contains all of these lines. Shouldn't it just be one?

```
    <package android:name="com.fsck.k9"/>

    <package android:name="net.thunderbird.android"/>

    <package android:name="net.thunderbird.android.beta"/>

    <package android:name="net.thunderbird.android.daily"/>
```

**Comment by cketti** [comment]
This is necessary to be able to import settings from another of our apps. See https://github.com/thunderbird/thunderbird-android/blob/e2097fce73da38cf72cd8e933590b2b6a2416d6a/feature/settings/import/src/main/AndroidManifest.xml#L7-L13
