### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by tino1003870** [thunderbird/thunderbird-android#8244]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b1

### Problem you are trying to solve

please include a Lightning-approach in Android version too.

### Suggested solution

include calendar part

**Comment by kewisch** [comment]
Thanks so much for sharing your idea—I really appreciate the time you put into it. For enhancement suggestions like this, would you mind posting them over on [Mozilla Connect](https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird%20android)? This is a great place for the community to discuss and help shape new ideas together, and is something we review regularly to determine the future roadmap.

To get the most out of your post, check out [this quick guide](https://connect.mozilla.org/t5/discussions/how-to-submit-a-great-idea-in-five-easy-steps/m-p/24) on crafting impactful suggestions. Focusing on the problem your idea solves and how it could help others can really make it stand out!

I’ll be closing this issue to keep our GitHub focused on active development, but I hope to see your idea over there.
