### ISSUE TITLE
Parity With GitHub and System Version String

### ISSUE THREAD

**Issue by scientiac** [thunderbird/thunderbird-android#8245]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Other

### Android version

Android 14, Blaze OS (Custom Rom)

### Device model

Xiaomi Redmi Note 9 Pro Max (Excalibur)

### Steps to reproduce

1. Check GitHub Version String.
2. Check Version String in system settings.
3. They don't match.
4. Hence it's difficult to track the version of the app with respect to github.

### Expected behavior

The string on GitHub and that shows up in app settings in android needs to be the same. 

### Actual behavior

Though they are the same version Obtainium (A package manager which relies on GitHub) shows that the new version is 'THUNDERBIRD_8_0b1' and the installed Version is '8.0b1' and asks me to update indefinitely.

![Screenshot_20241007-060919](https://github.com/user-attachments/assets/89b85dc9-bff3-4d82-b162-51feb3415e5a)

**Comment by cketti** [comment]
We never intended for the Git tag to match the version name used inside the app exactly. Occasionally we diverted from this pattern already (see e.g. [6.711-fdroid](https://github.com/thunderbird/thunderbird-android/tree/6.711-fdroid)).

As far as I can tell, we currently don't need a machine-readable mapping between Git tags and version names, and so we're not maintaining one. It'll be up to the Obtainium project to maintain such a mapping. It should be rather easy to derive the version name from the tag name.

**Comment by scientiac** [comment]
Thanks for the clarification.
