### ISSUE TITLE
Folder assignments not correctly imported from K-9

### ISSUE THREAD

**Issue by qftlzxfz** [thunderbird/thunderbird-android#8260]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

14

### Steps to reproduce

1. Clear all app data to start from scratch.
2. Import settings from K-9.

### Expected behavior

All IMAP folders have to same assignments as in K-9. So, for each account the inbox, outbox, sent box, etc. are correctly assigned with their proper icon.

### Actual behavior

It appears that the automatic detection was used, because all folders were marked with "automatic" in Manage folders.

Also, various folders, including inboxes!, were not correctly detected and there is no option to assign the inbox in Manage folders.

**Comment by cketti** [comment]
Steps to reproduce:
- Import at least two IMAP accounts including passwords

Importing the first account calls `Preferences.loadAccounts()` which creates an `Account` instance. Importing the second account also calls `Preferences.loadAccounts()` which creates another `Account` instance for the first account. However, the first `Account` instance is already used by the backend code. The frontend code will use the second instance that is out of sync with the first instance and doesn't have special folders set.

**Comment by qftlzxfz** [comment]
That makes sense. There are 6 IMAP accounts. Thank you!

Will the fix also enable assigning the inbox, which is now unassigned? Or should I open another report?
