### ISSUE TITLE
Use different icon for server-side search

### ISSUE THREAD

**Issue by ramonagavrilescu** [thunderbird/thunderbird-android#8266]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Oppo a58

### Steps to reproduce

1.Open Inbox folder.
2.Tap on search icon.
3.Enter some data into search field and tap  enter.
4.Check Emails that match the data entered are displayed.
5.Check keyboard is closed and search icon is no longer displayed.

### Expected behavior

4.Emails that match the data entered are displayed.
5. Keyboard is closed and search icon is no longer displayed.

### Actual behavior

4.Emails that match the data entered are displayed.
5.Search icon is displayed next to Search results, if you tap on search icon again "Sending query to server" message is displayed and the search icon disappears.

https://github.com/user-attachments/assets/ff742090-36ba-447e-b06c-92eabee07308

### Logs

[search logs.txt](https://github.com/user-attachments/files/17293384/search.logs.txt)

Checked also on K-9 and it doesn't reproduce

**Comment by cketti** [comment]
The search icon displayed during a search will extend the search to the server, i.e. perform a server-side search. However, I can see how using the regular search icon can be confusing. Previous versions of the app used an icon showing a cloud symbol inside the magnifying glass. It looks like this got lost when we switched to the new Material icon set.
