### ISSUE TITLE
Incoming server menu

### ISSUE THREAD

**Issue by TeHoDenN** [thunderbird/thunderbird-android#8271]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

Android 14

### Device model

Pixel 9

### Steps to reproduce

1 - Open the application settings
2 - Go to an email account
3 - Open Email Pickup
4 - Open "Incoming Server"

### Expected behavior

Hello, I just noticed a small bug on the latest version 8.0b2. It is impossible to edit the information of the incoming server. When you enter the "Incoming server" menu, in "Email collection", the configuration screen for a new account is displayed. If you go to the end of the procedure, it actually creates a new account.
I have attached a screenshot of the K9 application, for the same menu, we have the options to modify for the incoming server.
Thank you all, good luck :)

https://github.com/user-attachments/assets/50233f4f-e349-48ba-8b5f-2f16ee5c290c

### Actual behavior

In K9 mail, we have this screen: 
![Screenshot_20241008-174539~2](https://github.com/user-attachments/assets/bb1058d2-6917-4bc8-8153-caea60752e41)

**Comment by exstntlmsnthrp** [comment]
Brilliant. Happy to see this fix coming. Thought I was going crazy.
