### ISSUE TITLE
Review English (and translated) strings for use of K-9 Mail in Thunderbird

### ISSUE THREAD

**Issue by NicolasWeb** [thunderbird/thunderbird-android#8278]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Xiaomi Note 10 Pro

### Steps to reproduce

1. Click on Hamburger menu button
2. Go to Settings main panel
3. Check the last section (other maybe in EN-US)
4. Click on `About (Email) K-9 mail`

### Expected behavior

The menu item and about title window should be `About Thunderbird (for Android)`

### Actual behavior

The branding still mention K-9 mail

### Logs

![IMG_20241008_205945](https://github.com/user-attachments/assets/a8aa4179-577a-429d-a5c7-152f37bd106c)

**Comment by NicolasWeb** [comment]
![Screenshot_2024-10-08-21-13-59-992-edit_net thunderbird android beta](https://github.com/user-attachments/assets/0612d6f1-0a0a-4cb8-9840-738e86600dd7)

**Comment by NicolasWeb** [comment]
![Screenshot_2024-10-08-21-16-16-463-edit_net thunderbird android beta](https://github.com/user-attachments/assets/296219a1-87a5-4df6-894b-1b034d9f4134)

**Comment by kewisch** [comment]
Thanks for filing! On the "Authors" section, we'd like to keep The K-9 Dogwalkers, as they play an important part in bringing Thunderbird for Android where it is today. The website link we were looking to change once we launch the mobile portion of thunderbird.net, which we hope to be later this month (before the release). The header line and item in the settings should however say Thunderbird for Android.

**Comment by sens-sens** [comment]
Changing the following line
```xml
<string name="about_action">À propos de Courriel K-9 Mail</string>
```
to
```xml
<string name="about_action">À propos de Courriel Thunderbird</string>
```
 in the `values-fr` resource can fix it.

Can I make the changes?

**Comment by wmontwe** [comment]
The changes need to be done on [Weblate](https://hosted.weblate.org/projects/tb-android/), as we edit only source string in the project. And that doesn't incldue an app name: `<string name="about_action">About</string>`. 

I noticed that there are a couple of other translations that still include K-9 Mail. I think we need to do a Weblate cleaning session.

**Comment by kewisch** [comment]
If you head over to https://hosted.weblate.org/translate/tb-android/app-strings/fr/?checksum=ed5d179994f0a3e4&q=about_action&sort_by=-priority%2Cposition  you should be able to change it yourself. Feel free to suggest a change there, and if you have some extra time maybe go through the French strings to see if there are any other occurrences of K-9 Mail that aren't in the English strings.

I've morphed this bug into doing a pass on the strings, which should be something anyone could pick up:
* Go through all English string translations and check if there are occurrences of K-9 Mail
* Adapt the calling code to add the brand name as a placeholder
* Consider if it makes sense to remove the brand name from the string

**Comment by kewisch** [comment]
@NicolasWeb Would you mind making the change for French?
