### ISSUE TITLE
IMAP search and the trailing whitespace problem

### ISSUE THREAD

**Issue by lightonflux** [thunderbird/thunderbird-android#828]
Steps to reproduce:
1. Find a mail that ends with a unique string from some time ago. So it is not local on the phone and you don't get confused by "false positives". 
2. Go your account inbox
3. Click on the search icon
4. No local results. 
5. Click on the IMAP search button (search glass + cloud)
6. Wait and find nothing.

Example: 

Email Subject: "Pictures from Timbuktu"
An IMAP search for "Timbuktu" returns the result. But a search for "Timbuktu " does not. This is a really big problem. Because many android keyboards easily add a trailing whitespace when you don't want it, or when you use the word completion to save a few letters typing.

**Comment by cketti** [comment]
This is already fixed in the development version.

https://github.com/k9mail/k-9/commit/9c7776d289ea9c54b5c789eef0c06fd28a1240d9
