### ISSUE TITLE
Export file name branding should be Thunderbird not K-9 mail

### ISSUE THREAD

**Issue by NicolasWeb** [thunderbird/thunderbird-android#8280]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Xiaomi Note 10 Pro

### Steps to reproduce

1. Go to `Settings/Export settings`
2. Clic `Export` button
3. Check the name proposed for the export file

### Expected behavior

thunderbird_settings_YYYY

### Actual behavior

k9_settings_YYYY

**Comment by sens-sens** [comment]
Would you like to change that?

The relevant location is:
`legacy/core/src/main/java/com/fsck/k9/preferences/SettingsExporter.kt`

In line 489, you can find:
```kotlin
private const val EXPORT_FILENAME_PREFIX = "k9_settings_export"
```
You can change it to:
```kotlin
private const val EXPORT_FILENAME_PREFIX = "thunderbird_settings_export"
```
Can I make this change and submit a pull request?

**Comment by cketti** [comment]
The suggested change will lead to K-9 Mail using `thunderbird_` as filename prefix. So it doesn't solve the problem. It just shifts the problem from Thunderbird to K-9 Mail.

**Comment by NicolasWeb** [comment]
As for https://github.com/thunderbird/thunderbird-android/issues/8278#issuecomment-2401751883 , it seems some strings should be adapted in [Weblate](https://hosted.weblate.org/projects/tb-android/), so the filename prefix could adapt to both products.

**Comment by kewisch** [comment]
As we're shifting our focus towards Thunderbird I'd rather have it look right on the Thunderbird side and accept that it might not be 100% correct for a niche thing like the filename here, but obviously the better approach would be to make it different per app. I'm suspecting this shouldn't be too difficult to do, would love to see someone give it a try!
