### ISSUE TITLE
No server search with Zimbra/IMAP

### ISSUE THREAD

**Issue by parrenin** [thunderbird/thunderbird-android#8283]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

14

### Device model

OnePlus 8T

### Steps to reproduce

I have set up Thunderbird on my Android phone with IMAP/SMTP.
The problem is that apparently, there is no access to server search (no button appears to search on the server).
I can only search the emails stored locally, but not the ones on the server, which is limiting.
My Gmail can search the emails on the server, although it is configured with the Exchange protocol.

### Expected behavior

It should be possible to search on the server.

### Actual behavior

There is no button to search on the server.

**Comment by cketti** [comment]
Server search is only available for regular IMAP folders. It's not available in the unified inbox. See also #8266.

**Comment by parrenin** [comment]
Thanks for the tip! I will know it now.
It is not super intuitive that server search is not available for the unified inbox, which is the default folder if I am not mistaken.
