### ISSUE TITLE
Unicode support in Thunderbird for Android (beta)

### ISSUE THREAD

**Issue by tomdark78** [thunderbird/thunderbird-android#8285]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

Android 14

### Device model

Oneplus 8T

### Steps to reproduce

1. Open a specific message from a French sender (with French charachters) 
2. The correct charachter set is not shown and many question marks appear instead

### Expected behavior

I would expect the message is shown correctly as it happens in other email clients on Android (tested ok in Gmail app and in Aquamail app)

### Actual behavior

See attached screenshot and the full email as txt file

![Screenshot_2024-10-05](https://github.com/user-attachments/assets/9643e2fc-fc63-4715-8e81-8bec2a9f4acf)

**Comment by tomdark78** [comment]
[Votre Fast Check-out.txt](https://github.com/user-attachments/files/17305398/Votre.Fast.Check-out.txt)

**Comment by cketti** [comment]
This is because the `text/plain` part doesn't specify a character set, so US-ASCII is assumed. Try to get the sender to fix the software that was used to generate this message.

**Comment by tomdark78** [comment]
But Thunderbird for Windows shows the message correctly: isn't there a way to replicate the same behaviour in TB for Android?

**Comment by cketti** [comment]
That will just shift the problem to the next email app that implements the standard and doesn't try to work around broken messages. The problem needs to be fixed at the source.
