### ISSUE TITLE
IMAP Parser bug: Unexpected character: * (42)

### ISSUE THREAD

**Issue by ElizabethWega** [thunderbird/thunderbird-android#8289]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

F-Droid

### Android version

Custom ROM: MIUI V14.0.7.0.TKKCNXM | stable from xiaomi.eu

### Device model

Xiaomi Mi 11i 5G

### Steps to reproduce

1. Go to 'Settings'
2. Click 'Add account'
3. Enter university e-mail and type in IMAP configuration for the incoming and server found on Outlook's official page.
4. Wait for OAuth 2.0 to authenticate Thunderbird.
5. Type in the same IMAP configuration for the outgoing server
6. Wait for OAuth to autheticate.
7. Authentication fails and the error that the application returns is _Unknown error Unexpected character: * (42)_

I consulted the bug tracker within the app as advised by Thunderbird's community within Matrix. This is the output I got while Thunderbird was trying to authenticate the outgoing server (see attachment).

Thank you all in advance for any attempt to solve thid issue!

### Expected behavior

After seeing the step no. 6 on my screen, I'd expect that Thunderbird authenticates the outgoing server and successfully adds my Outlook Exchange account to the mail addresses list.

### Actual behavior

![Screenshot_2024-10-09-12-44-36-192_com fsck k9](https://github.com/user-attachments/assets/6dd91ae9-1549-4091-9fe8-2502a48c1f22)

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/17309000/k9mail-logs.txt)

**Comment by cketti** [comment]
You need to enter the SMTP server settings for the outgoing server.
