### ISSUE TITLE
Not possible to edit email address in configuration without erasing server settings

### ISSUE THREAD

**Issue by spacecowboy** [thunderbird/thunderbird-android#8295]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

ae30928

### Where did you get the app from?

Other

### Android version

Emulator API 34

### Steps to reproduce

1. Start a fresh install of Thunderbird / K9
2. In configuration wizard, input an adress where a configuration will be found
3. Try to edit the email address (because that's not my actual login)

### Expected behavior

After a configuration has been found, a user should be able to edit the email field without erasing the server configuration

### Actual behavior

Editing the email address will remove any server configuration

**Comment by cketti** [comment]
The server settings could be specific to the email address. So changing the email address invalidates the server settings. 

Why is this an issue? Does finding server settings not work with your real email address?

**Comment by spacecowboy** [comment]
> The server settings could be specific to the email address. So changing the email address invalidates the server settings.
> 
> Why is this an issue? Does finding server settings not work with your real email address?

Correct. It does not find the settings if I use my fastmail.com address (which is my login).

But I can enter an address for my custom domain (kalderstam.se) configured with fastmail and the settings are found. But i need to change the address in that case.

**Comment by cketti** [comment]
We're working on fixing the situation with fastmail.com addresses.

In the meantime you could use the custom domain to find server settings, then select "edit configuration", change the username for incoming and outgoing server settings. After the account has been set up, you need to change the email address under *Settings → [Account] → Sending mail → Composition defaults → Your email address*.
