### ISSUE TITLE
F-Droid update request: com.fsck.k9 6.904 -> 8.0b2

### ISSUE THREAD

**Issue by devurandom** [thunderbird/thunderbird-android#8298]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.904

### Problem you are trying to solve

I would like to see K-9 Mail 8.0b2 (39006) in F-Droid, so I can update and migrate to Thunderbird Android, which I installed from Google Play.

See-also: https://gitlab.com/fdroid/fdroiddata/-/issues/3396

### Suggested solution

Update https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.fsck.k9.yml from 6.904 (39004) to 8.0b2 (39006).

**Comment by wmontwe** [comment]
We're soon to release a beta update for K-9 Mail, which will allow you to begin the migration process, similar to the current Thunderbird beta version. Meanwhile, the file-based export and import functionality between the two apps already works seamlessly.

**Comment by devurandom** [comment]
Thanks for that hint!  It worked perfectly.

(I originally wanted to help ["Test the K-9 Mail to Thunderbird for Android Transfer"](https://blog.thunderbird.net/2024/09/help-us-test-the-thunderbird-for-android-beta/).)
