### ISSUE TITLE
Crash when opening app - K9WorkerFactory

### ISSUE THREAD

**Issue by Touhounewpeople** [thunderbird/thunderbird-android#8299]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

Thunderbird Beta 8.0b2 (5)

### Where did you get the app from?

Other

### Android version

14

### Device model

Honor 50 pro

### Steps to reproduce

1. update thunderbird for android from 8.0b1 to 8.0b2
2. click the app
3. app crash

### Expected behavior

app opened

### Actual behavior

app crash

### Logs

[crash-net-thunderbird-android-beta-10_10-01-40-44_867.zip](https://github.com/user-attachments/files/17322378/crash-net-thunderbird-android-beta-10_10-01-40-44_867.zip)

**Comment by bakamake** [comment]
same question from honor 80 pro.

**Comment by wmontwe** [comment]
Thanks for reporting this crash. It helped us to identify the issue.
