### ISSUE TITLE
Show number of unread emails per account

### ISSUE THREAD

**Issue by ordex** [thunderbird/thunderbird-android#8300]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b2

### Problem you are trying to solve

When having multiple account configured, it's impossible to determine which account has unread emails.
Only the total amount of unread messages is shown next to the "Unified inbox" label, but if unread messages are in subfolders, you need to go through all accounts in order to find where they are.

In K9, when opening the account list, you can see a counter next to each account name telling you how many unread messages er account there are.

### Suggested solution

Similarly to K9, it'd be useful to show a number next to each account badge in the account list.

### Screenshots / Drawings / Technical details

I am imagining something along the lines of this screenshot (I am no graphic designer - forgive my roughness)
![Screenshot_20241010-093541](https://github.com/user-attachments/assets/823c994c-0db4-47d6-bf7b-954c2408dd4e)

**Comment by sebbu2** [comment]
The badge "plus de 99" is big and hide the 2 letters of the account in question. Can this be fixed ?
