### ISSUE TITLE
App crashes when I tap on "show accounts" in sidebar

### ISSUE THREAD

**Issue by Chartman123** [thunderbird/thunderbird-android#8301]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

14 (patch level 09-24)

### Device model

Oneplus Nord 3 5G

### Steps to reproduce

1. Go to "show accounts" in sidebar
2. See that app crashes

### Expected behavior

Account menu should be shown

### Actual behavior

App crashes

### Logs

[log_2024_10_10_10_19_11.log](https://github.com/user-attachments/files/17324855/log_2024_10_10_10_19_11.log)

**Comment by wmontwe** [comment]
Thanks for reporting this issue. I was able to reproduce it.

**Comment by wmontwe** [comment]
@Chartman123, I was wondering why this was happening and I thought it might be due to one of your accounts having no email set up or a format that our current code can't understand. We attempt to split the email at the @ sign and use the first 2 characters of the domain name. I added a fix, but I'd love to know what actually caused the issue, was it indeed an empty email field or an unexpected domain format? Maybe you could report back and let me know what you've found out?

**Comment by Chartman123** [comment]
Yes, this might be the reason... I edited one of my accounts and removed the mail address and name as I wanted to only use my created Identities. After that change the app worked still fine until the next start of the app

**Comment by wmontwe** [comment]
Thanks, the fix should work for your specific use case.

**Comment by cketti** [comment]
I've created issue #8303 for the bug that allowed removing the email address from the default identity.

**Comment by cketti** [comment]
@Chartman123: You can remove an identity completely by going to *Settings → [Account] → Sending mail → Manage identities*. Long-press the identity you want to remove and select *Remove* from the popup menu.

**Comment by Chartman123** [comment]
@cketti yes, but I wanted to use it the other way round because in the Identities dialog you have more options than in the default settings of the account.

**Comment by cketti** [comment]
I don't understand. Can you elaborate?

**Comment by Chartman123** [comment]
Not at the moment as I can't show you the screenshots because of the bug ;) But I'll post them as soon as possible :)

**Comment by Chartman123** [comment]
@cketti @wmontwe  Thanks for the quick fix :)

I could now have another look and saw that I just got a little confused by the two ways to edit the default identity:

- message composition options (here only BCC)
- manage identities (here only reply-to)

I think it would be better to have only one location to manage the default identity (and then best in manage identities) 🙂
