### ISSUE TITLE
can we import data from thunderbird pc to android?

### ISSUE THREAD

**Issue by Owned67** [thunderbird/thunderbird-android#8307]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

beta 8.0

### Problem you are trying to solve

can we import data from thunderbird pc to android?

### Suggested solution

can we import data from thunderbird pc to android?

**Comment by kewisch** [comment]
Yes, we're actively working on this. The feature just made it into beta 2, and by beta 3 you should be able to test it in Thunderbird Daily. We aim to have everything ready by the release. I'm going to close this issue since we have a bunch of others open around it.
