### ISSUE TITLE
Always mark read when archiving email messages

### ISSUE THREAD

**Issue by fifty-six** [thunderbird/thunderbird-android#8309]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.804

### Problem you are trying to solve

I'd love some way to mark things as read when archiving.

Generally, when archiving something unread, it's because I have sufficient information from the subject line/already roughly know the contents - or know I don't care too much about it, but still want it "just in case". I like being able to filter by unread though, especially if it's something I want to get back to later and refile - but don't want in my inbox because it's not really a priority. 

### Suggested solution

An option to mark things read when archiving, like what's done with spam, would be great. Alternatively I think it'd be similarly nice to have one of the possible swipe actions be "mark as read and archive" together.

**Comment by kewisch** [comment]
Honestly I think this should be the default. I can't think of a use case to archive a message and not also mark it read.

**Comment by cketti** [comment]
Generally we try to avoid changing the behavior of existing accounts. However, that's not possible if we don't also want to add a setting.

We've discussed this internally and decided to test the new behavior in beta for a while. At the same time we don't want to be blocked from doing releases. So a feature flag needs to be added to switch between the current behavior (will be used on the `release` branch) and the new behavior (will be used in all other branches).

**Comment by imjuzcy** [comment]
Any reason to not add a setting but forcing this to be an always behaviour?

A sudden change in behaviour (that is not a bug fix) could confuse users and degrade the user experience, imo (even though it is written in the changelog). It makes the user feel not in control of their own mails.
