### ISSUE TITLE
Added "Check for Updates" feature in Thunderbird Android

### ISSUE THREAD

**Issue by Shura23** [thunderbird/thunderbird-android#8316]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b2

### Problem you are trying to solve

Added "Check for Updates" feature in Thunderbird Android。When you check that there is a new version, you can directly click Update. Firefox android doesn't have an update check function, and then if I want to update the new version of Firefox, I have to go to google play to download the update, but I'm in China, and I need to use a vpn to use Google play, which is very troublesome, so in order to avoid this from happening to thunderbird, I need to add the check update function

### Suggested solution

Thunderbird needs to automatically detect updates like Firefox windows and download updates if they are available ...

**Comment by shuvashish76** [comment]
Note that for F-Droid [Tracking](https://f-droid.org/en/docs/Anti-Features/#Tracking) Anti-Feature tag needed if the update checker will be enabled default.

> - Checking for updates without your knowledge or permission
>
>Examples of where **it would not be applied** - any of the above, **if the functionality is opt-in** (i.e. you are asked before it happens) **and disabled by default**.

And auto-updater/downloaders are strictly against F-Droid' [inclusion policy](https://f-droid.org/docs/Inclusion_Policy/).

> The software must not download additional executable binary files (e.g. addons, auto-updates, etc.) **without explicit user consent**. **Consent means it needs to be opt-in** (it must not be harder to decline than to accept or presented in a way users are likely to press accept without reading) and structured in a way that **clearly explains to users that they’re choosing to bypass F-Droid’s checks if they activate it**.

**Comment by spider1163** [comment]
You can simply use FFUpdater
https://f-droid.org/packages/de.marmaro.krt.ffupdater/

**Comment by kewisch** [comment]
I've made a pull request to FFUpdater to support this. I don't think we should be maintaining a separate update check feature within Thunderbird for Android.

https://github.com/Tobi823/ffupdater/pull/642
