### ISSUE TITLE
Thunderbird for Android edit account settings issue

### ISSUE THREAD

**Issue by Corwyn717** [thunderbird/thunderbird-android#8321]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Google Pixel 7 Pro

### Steps to reproduce

1. Go to settings
2. Click on already configured account
3. Click Sending mail or Fetching mail
4. Click Outgoing server or Incoming server

### Expected behavior

Should show the account configuration already setup.

### Actual behavior

Brings to New account setup wizard.

**Comment by mutaunt** [comment]
I have this issue too on my ancient LG V30 Android 9 phone.

**Comment by cketti** [comment]
Duplicate of #8271
