### ISSUE TITLE
Cannot manage other email accounts configured in Android

### ISSUE THREAD

**Issue by parrenin** [thunderbird/thunderbird-android#8323]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

14

### Device model

OnePlus 8T

### Steps to reproduce

Steps to reproduce:
- configure a mail account in Android (e.g. a Google account)
- open TB
- => the mail account does not appear in TB, you have to reconfigure it locally

### Expected behavior

Other already configured email accounts should appear directly in TB.

### Actual behavior

No email account appears in TB.
You have to reconfigure it right in TB.

Sorry for the basic question, I searched on the web and on Github, but could not find an answer to this question.

**Comment by cketti** [comment]
I'm not sure I understand what you are reporting. By "TB" do you mean Thunderbird for desktop? Are you saying that you expect accounts added to the Android app to automatically show up on Thunderbird on your desktop? If so, that's not supported. It will be possible once we add [Thunderbird Sync](https://github.com/thunderbird/thunderbird-android/issues/8033).

**Comment by parrenin** [comment]
No, by TB I mean Thunderbird (for Android).
My issue is, when you have configured an email account (e g. a Google account), why it does not show up in Thunderbird for Android?
Maybe this has to do with Oauth but I am not sure.

**Comment by cketti** [comment]
This might be bug #8260. It'll be fixed in 8.0b3 (should be released tomorrow).

**Comment by parrenin** [comment]
I have the impression this is not the same as #8260.
Are you sure this is really the bug you wanted to mention?

**Comment by cketti** [comment]
It may not sound like it from the description. But the underlying problem is causing all kinds of symptoms. If it's something else and you're still experiencing this problem with 8.0b3, we'll need more detailed steps to reproduce the problem.

**Comment by kewisch** [comment]
@parrenin can you confirm this issue is resolved?

**Comment by parrenin** [comment]
No, the problem does not seem to be resolved.
For example, if I have Google accounts configured in Android, they don't automatically appear in TB.

**Comment by kewisch** [comment]
Ah ok, thanks for clarifying!

**Comment by kewisch** [comment]
For enhancement suggestions like this, would you mind posting them over on [Mozilla Connect](https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird%20android)? This is a great place for the community to discuss and help shape new ideas together, and is something we review regularly to determine the future roadmap.

To get the most out of your post, check out [this quick guide](https://connect.mozilla.org/t5/discussions/how-to-submit-a-great-idea-in-five-easy-steps/m-p/24) on crafting impactful suggestions. Focusing on the problem your idea solves and how it could help others can really make it stand out!

I’ll be closing this issue to keep our GitHub focused on active development, but I hope to see your idea over there.
