### ISSUE TITLE
K-9 8.0b1 Fails to Install

### ISSUE THREAD

**Issue by SarraceniaWilds** [thunderbird/thunderbird-android#8333]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

8.0b1, 6.804

### Where did you get the app from?

Other

### Android version

10

### Steps to reproduce

Download apk for v8.0b1 from relases page
Install

### Expected behavior

Installed version 8.0b1

### Actual behavior

Dialog box fail to install, version remains 6.804
![Screenshot_20241015-103745_Package installer](https://github.com/user-attachments/assets/b97ebfc7-ec56-47f7-a80b-278492df04aa)

**Comment by kewisch** [comment]
Does it work if you try to install via the play store pre-releases? Can you check that you've set the respective permissions to install third party apps? What method are you using to install the apk?

**Comment by SarraceniaWilds** [comment]
I do not have play store. Yes, it would not be possible for it to fail installing without the permissions. The method is I downloaded the apk, I open it, it fails.

**Comment by kewisch** [comment]
Is this only b1, or does it also fail with b2 and b3? We built them slightly different.

**Comment by ckardaris** [comment]
All 3 pre-release versions of K9-Mail fail to install for me with the above message. 

I managed to install Thunderbird b1 correctly from the PlayStore. 

Currently I am on version K9-Mail 6.904, which was installed directly from the GitHub releases apk.

**Comment by kewisch** [comment]
I had this recently while switching between play store vs github builds, so it might be related to that. Glad it works now!
