### ISSUE TITLE
Email Addresses added as default BCC address are not saved

### ISSUE THREAD

**Issue by CherylAoife** [thunderbird/thunderbird-android#8347]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b3

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Samsung SM-5237VL

### Steps to reproduce

1. Go to any account settings
2. Go to Sending Mail
3. Go to Composition Defaults
4. Enter an email address in "Bcc: all messages to"
5. Click on Save
6. Reopen Composition Defaults and there is no email address in the "Bcc: all messages to" field
7. When I go to send an email, I have to manually enter a BCC address

### Expected behavior

It should save the email address entered as the default BCC address

### Actual behavior

It did not save any address in the field after an address was entered and saved

### Logs

I don't have any logs for this.

**Comment by cketti** [comment]
Thanks for the report. This should be fixed in the next beta.

**Comment by EJB4T** [comment]
Thank you, @cketti !
