### ISSUE TITLE
K9 8B1-3 email attachments problem

### ISSUE THREAD

**Issue by AHK0** [thunderbird/thunderbird-android#8349]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

8.0 beta1, beta 2 and beta3

### Where did you get the app from?

None

### Android version

10

### Steps to reproduce

app download from github, install is normal, email list is normal, all other functions are normal.

however, attachments in any emails cannot be opened and displayed correctly. 
after downloading, the attachements (e.g., pdf, doc, or other formats) are opened by the defaul app, but all are empty (with a warning, "path error")
should note that K9 6.904 works well for the same emails and the same attachments in the same phone.

have tried this many times. always the same results: the three beta versions of 8.0 do not work, while 6.904 version works normally.

### Expected behavior

attachments in any emails cannot be opened and displayed correctly. 
after downloading, the attachements (e.g., pdf, doc, or other formats) are opened by the defaul app, but all are empty (with a warning, "path error")
should note that K9 6.904 works well for the same emails and the same attachments in the same phone.

### Actual behavior

attachments in any emails cannot be opened and displayed correctly. 
after downloading, the attachements (e.g., pdf, doc, or other formats) are opened by the defaul app, but all are empty (with a warning, "path error")
should note that K9 6.904 works well for the same emails and the same attachments in the same phone.

**Comment by AHK0** [comment]
it seems this has problem been seen by others -- there is a post in the k9 forum about the same issue

**Comment by cketti** [comment]
I can't reproduce this problem. Can you please record a video demonstrating what this looks like on your Android device?

**Comment by AHK0** [comment]
some screenshots are shown here, the same mobile the same email server the same email and document

for 8.0b1-b5 and the recent 8.0, it always like in the attahced: file path error! while in 6.904 and earlier versions, there was no problem with the document. the same for any attached documents in emails. so I am using 6.904 now
![aa](https://github.com/user-attachments/assets/4f670d51-5efa-4e97-8069-879493779542)
![ab](https://github.com/user-attachments/assets/45e5532a-7578-4e28-9892-288b9da8c76a)

**Comment by AHK0** [comment]
the same mobile, and the same android and the same hardware, and also the same pdf browser for downloading and opening the same document in the same email

**Comment by cketti** [comment]
A recent bugfix changed the way attachment URIs look like. See <https://github.com/thunderbird/thunderbird-android/issues/8045>. However, the new URI is still in a format that every Android app should support. 

I installed "Yozo Office" and can confirm that it doesn't open an attachment from K-9 Mail. I don't think there's anything our app is doing wrong. It looks like a bug in the Yozo viewer to me. Please contact them to look into this. Other document viewers work fine.
