### ISSUE TITLE
"None available" and no contribution values are displayed for a short period upon launch - especially on low ends

### ISSUE THREAD

**Issue by VladLucaci** [thunderbird/thunderbird-android#8354]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b3

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Galaxy Tab A9+

### Steps to reproduce

Preconditions:
Have at least one account added.
Make sure the application is closed

Steps: 
1. Launch TB.
2. Go to Hamburger Menu
3. Tap Show accounts
4. Tap the Settings cogwheel.
5. Tap Support Thunderbird Beta

### Expected behavior

The page is loaded and all information and values are displayed.

### Actual behavior

Page is accessed and "None available" is displayed as payment type while no contribution values are displayed.
This issue occurs an all of our available devices, but it is especially visible on lower end devices where the waiting period is above 1 second(s)

### Logs

https://github.com/user-attachments/assets/92180d23-a6aa-445e-a260-f22816f65351

**Comment by kewisch** [comment]
![image](https://github.com/user-attachments/assets/fa0d1d9f-6a7c-4c76-a12e-62edd233a6c5)
![image](https://github.com/user-attachments/assets/1cfad29f-2b03-4ce3-8f8f-ce79ec05fd8f)

Here are my makeshift design suggestions. This would be good to look into given the billing library is so fragile.

The link to thunderbird.net should contain an utm campaign noting there was an error loading the amounts. It doesn't matter which error, but just the fact that this happened might give us a bit data there is an issue.

**Comment by kewisch** [comment]
Design provided a much better version of the right screen. It doesn't look like we have the left screen yet, where we'd instead show the typical loading indicator. Would be good to work this out until the release.

**Comment by wmontwe** [comment]
This is fixed by #8375, please reopen if it still doesn't work.
