### ISSUE TITLE
Make more clear that the contribution thank you screen is a thank you screen

### ISSUE THREAD

**Issue by VladLucaci** [thunderbird/thunderbird-android#8357]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b3

### Problem you are trying to solve

At the moment the user is only presented with the option to "Help keep Thunderbird alive" when finishing up a donation transaction.

### Suggested solution

As per the [Figma Design documentation](https://www.figma.com/design/BWHQ2Dd3s0Ejrsb9d25EEx/TBAndroid_2024_Q3_Appeal_v01.0.0?node-id=2135-499&node-type=frame&t=xii3dnFhgREk2Gxa-0) I would suggest to consider implementing a Cancel button for the one-time contribution screen, like it is for the subscription option.
This would greatly increase the overall UX and the overall continuity of the screens displayed (unlike currently one screen that has it and one that does not have it).

### Screenshots / Drawings / Technical details

![Screenshot_20241017_162343_Thunderbird Beta](https://github.com/user-attachments/assets/0eef4b75-9676-4c29-a651-0f552ab25162)

**Comment by kewisch** [comment]
I think we have to make some adjustments to this screen. This version is meant to be the "thank you" screen. You've made a contribution, you get the golden heart to show you've last made an Essential Contribution. Aside from the text you see there I think we should have a more general thank you for contributing text, and maybe also the amount of the essential contribution shown.

The "Help keep Thunderbird alive" button should bring you back to making another contribution, as it was a one time contribution before.

**Comment by kewisch** [comment]
@wmontwe Suggested static text across all types of contribution:

> Thank you for your generous donation! Your support directly strengthens Thunderbird, and we’re grateful to have you by our side on this journey.

Button Text:

> Make another impactful contribution


cc @inattee in case you'd like changes we can add them for an update.

**Comment by wmontwe** [comment]
@kewisch should the static text be above or below the existing one?

**Comment by kewisch** [comment]
Above is good

**Comment by wmontwe** [comment]
Done
