### ISSUE TITLE
Contribution successful screen is displayed even though no purchase was actually made

### ISSUE THREAD

**Issue by VladLucaci** [thunderbird/thunderbird-android#8358]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b3

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Galaxy Tab A9+

### Steps to reproduce

Preconditions:
Have at least one account added.
Make sure that this is the first launch.

Steps:
1. On first launch, the Support Thunderbird (as it is described in [Figma](https://www.figma.com/design/BWHQ2Dd3s0Ejrsb9d25EEx/TBAndroid_2024_Q3_Appeal_v01.0.0?node-id=2135-98&node-type=frame&t=xii3dnFhgREk2Gxa-0) ) is displayed.
2. Choose any purchase value (let's say the lowest one-but it happens with each one)
3. The Essential Contribution screen is already displayed behind the Google Play purchase confirmation prompt, even though I haven't yet made the actual purchase 
4. In the Review and Agree Google play prompt press Agree
5. in the Google Play 1-tap buy tap back (or outside the prompt)

### Expected behavior

The contribution successful screen is not displayed when no purchase was actually made.

### Actual behavior

Contribution successful screen is displayed even though no purchase was actually made

### Logs

https://github.com/user-attachments/assets/d5d93730-8c70-4c41-9f80-21222e99bff3

**Comment by kewisch** [comment]
@wmontwe brought this up as well. It is possible this is because we have you added as a license tester, so the response that the transaction has succeeded comes earlier than usual. We should test this with a real contribution, I'll see if there is someone willing to test this who wants to support us anyway.

**Comment by cketti** [comment]
I'm also seeing this on a device that doesn't have a license tester enabled account set up. The state changes as soon as the payment bottom sheet appears.

**Comment by kewisch** [comment]
@VladLucaci This should be fixed in b4, can you re-test?

**Comment by wmontwe** [comment]
This is fixed by #8375, please reopen if it still doesn't work.
