### ISSUE TITLE
The first Support Thunderbird screen is no longer displayed after purchase (latest purchase screen displayed instead)

### ISSUE THREAD

**Issue by VladLucaci** [thunderbird/thunderbird-android#8359]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b3

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Galaxy Tab A9+ 

### Steps to reproduce

Preconditions:
Have at least one account added.
Make sure that this is the first launch.

1. On first launch, the Support Thunderbird (as it is described in [Figma](https://www.figma.com/design/BWHQ2Dd3s0Ejrsb9d25EEx/TBAndroid_2024_Q3_Appeal_v01.0.0?node-id=2135-98&node-type=frame&t=xii3dnFhgREk2Gxa-0) ) is displayed.
2. Choose any purchase value (let's say the lowest one-but it happens with each one)
3. The Essential Contribution screen is already displayed behind the Google Play purchase confirmation prompt, even though I haven't yet made the actual purchase
4. In the Review and Agree Google play prompt press Agree
5. In the Google Play 1-tap buy prompt tap Buy.
6. Tap on the "Help keep Thunderbird alive"

### Expected behavior

Upon returning to the Support Thunderbird section, I would expect the screen to be back to the one displayed upon first launch(before purchase),

### Actual behavior

The Support Thunderbird screen is no longer displayed, only the latest purchase screen.
Deleting/reinstalling the application, re-importing the accounts and returning to Support Thunderbird beta displays the first Support Thunderbird screen for a split second.

### Logs

https://github.com/user-attachments/assets/efe8b296-42d9-4e39-b947-04f8580b1bbc

**Comment by kewisch** [comment]
This is on purpose, we want to show the user has made a contribution. I think this should be covered by what we do in #8357.
