### ISSUE TITLE
Fastmail OAUTH2: unable to configure

### ISSUE THREAD

**Issue by andbenn** [thunderbird/thunderbird-android#8368]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android 8.0b3
K-9 6.804

### App version

Thunderbird Android 8.0b3
K-9 6.804
### Where did you get the app from?

Google Play

### Android version

Android 14

### Device model

Pixel 6a

### Steps to reproduce

1. Settings
2. Choose my Fastmail account
3. Fetching mail
4. Incoming Server
5. Change Authentication from Normal Password to OAUTH2
6. Next
7. Please sign in ... Sign in
8. OAuth sign in failed.  Oauth 2.0 is currently not supported with this provider

### Expected behavior

I have OAUTH2 in Thunderbird desktop configured.  I know it works.

Their server is mail.messagingengine.com
My username is my core account, and is using one of their other domains they own, not the same as their server.

I'd like to migrate off of my application password to OAUTH2.

This also occurs in K-9.

### Actual behavior

OAuth sign in failed
OAuth 2.0 is currently not supported with this provider
Retry

**Comment by cketti** [comment]
Use these settings: https://autoconfig.fastmail.com/mail/config-v1.1.xml

### Incoming server
Server: imap.fastmail.com
Security: SSL/TLS
Port: 993
Authentication: OAuth 2.0

### Outgoing server
Server: smtp.fastmail.com
Security: SSL/TLS
Port: 465
Authentication: OAuth 2.0

**Comment by andbenn** [comment]
Wow, my config predates the current service documentation.  Imagine that.  Thanks @cketti 

I'm able to get OAuth2 working in Thunderbird Android 8.0b3.  Success and thanks!

However, K-9 6.804 still shows me the OAuth signin failed / ... not supported after tapping the Sign In button in the settings/config.  Autoconfig issue perhaps?  A future K-9 release for this to work?

Thank you!!

**Comment by cketti** [comment]
OAuth with Fastmail is only supported since 8.0b3
