### ISSUE TITLE
Can not register to forum

### ISSUE THREAD

**Issue by rafnov** [thunderbird/thunderbird-android#8372]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### Steps to reproduce

I fill in all the forms with proper data and K-9 tells me will send confirmation email.
NO email comes for whole a day even after i pressed resend it button.
Of corse I have checked spambox - email is not there.
Why? How to fix?

### Expected behavior

Confirmation email received

### Actual behavior

No forum registration, no account registration confitmation email received.

**Comment by rafnov** [comment]
https://forum.k9mail.app/

**Comment by kewisch** [comment]
@cketti can take a look at this. What information are you looking to get there? For support please visit https://support.mozilla.org/en-US/products/thunderbird-android

**Comment by rafnov** [comment]
I needed to know relation between Thunderbird beta from Google Store to K-9 called thunderbird-android. Now I now TB comes from K-9, but still don't get the split and declaration to maintain both apps, instead putting them together with an effort of making 1 app better than 2 separate.

**Comment by kewisch** [comment]
The apps are the same, we build with different branding and the one or other feature disabled/enabled. It isn't a big burden to maintain both at the moment, as we want to organize features into feature modules anyway. We might revisit this decision, but we didn't want to just drop K-9 Mail on day 1. Does that answer your question?
