### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by rclz151** [thunderbird/thunderbird-android#8373]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

80b3

### Where did you get the app from?

Google Play

### Android version

11

### Device model

SM T720

### Steps to reproduce

Pop3.mail.mailo.com

### Expected behavior

Connect to mail.mailo.com 

### Actual behavior

Does not recognition server: mail.mailo.com

### Logs

U

**Comment by kewisch** [comment]
I believe mail.mailo.com is the correct server, but I wonder where you got Pop3.mail.mailo.com from. Did you enter this manually, or was it auto-detected?
