### ISSUE TITLE
k9mail frequently crashes when deleting mail (bulk or individual) secure IMAP more than 1000 emails in inbox

### ISSUE THREAD

**Issue by Mikeya7** [thunderbird/thunderbird-android#839]
When I set to sync IMAP with less than 100 emails, no problem. 
But I need to find older emails so I sync with approx 2500 emails in the inbox.
I'm using an SSL IMAP connection. 
Frequently the app crashes. 
I'm running the latest version of k9mail on android 4.2.2 on a Samsung Galaxy Note 8 GT-N5100.
I don't have root, so logs are inaccessible due to permissions.
When I have time I'll connect to my Linux box and try to obtain logs for you.

**Comment by cketti** [comment]
No debug log/stack trace provided.
