### ISSUE TITLE
Download attachment button has incorrect accessible name

### ISSUE THREAD

**Issue by dankeck** [thunderbird/thunderbird-android#8401]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b4

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 5

### Steps to reproduce

1. Turn on the TalkBack screen reader.
2. Open Thunderbird.
3. Open an email message with an attachment.
4. Navigate with TalkBack to an attachment's download button, which has an icon of a down arrow.

![A button with an icon of a down arrow is indicated, under an image of the Thunderbird logo its file name and file size](https://github.com/user-attachments/assets/c89a2474-0bf9-4069-8a5e-e38fbb508f58)

### Expected behavior

The download button is announced with an accurate name, like "download attachment".

### Actual behavior

The download button is announced as "remove attachment".

**Comment by cketti** [comment]
Thanks for the report.

The layout was copied from the message compose screen where the attachment box has a button to remove the attachment from the draft. 
The button on attachments in the message view screen allows users to save the attachment as an external file. I therefore went with "save attachment" as the content description (see #8404).
