### ISSUE TITLE
Hide the waiting for new emails notification without losing notifications of actual emails

### ISSUE THREAD

**Issue by gabrielambuehl** [thunderbird/thunderbird-android#8418]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

Latest Beta

### Problem you are trying to solve

Getting rid of the Waiting for new emails notification while retaining the notification when emails actually arrive.

### Suggested solution

I assume using a different notification channel might work but I am not altogether sure why it's there in the first place, other apps seem to be able stay running without (thinking of the Garmin app here)

**Comment by ByteHamster** [comment]
Just tap the notification and read the text that gets shown

**Comment by gabrielambuehl** [comment]
Aight Samasung's wording is less than clear, it implies all notifications would disappear... Thanks a lot!
