### ISSUE TITLE
Add an AMOLED theme

### ISSUE THREAD

**Issue by LorenDB** [thunderbird/thunderbird-android#8432]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b4

### Problem you are trying to solve

Thunderbird currently doesn't provide an AMOLED theme (i.e. a theme with a pure black background). Since my phone has an OLED display, I prefer to use AMOLED themes where possible since they look pretty good on an OLED.

### Suggested solution

Add a theme option to use AMOLED colors. I've seen other apps implement this in two different ways:

1. As a standalone option in the themes combo box
2. As a switch that can be used to modify the dark theme

**Comment by kewisch** [comment]
I think we might be able to handle this via #8340, if you can set custom colors via Material You, you should be able to set a full black.

**Comment by KiruPoruno** [comment]
> I think we might be able to handle this via ..., if you can set custom colors via Material You, you should be able to set a full black.

Not the greatest solution, most ROMs don't let you pick the entire palette, and it usually requires root to enable such a feature on those ROMs. Simply having a toggle in the app, that makes the dark background parts of the palette forcibly black would however work.

**Comment by MillionsToOne** [comment]
It should be on OxygenOS and OneUI also.

**Comment by KiruPoruno** [comment]
> It's on most ROMs in the dark mode menu. At least on LineageOS, where there's an option to enable pure black mode

Keyword here: most

Not all... Phone's stuck below Android 11 straight up can't have this option, not without some modification, and most Android 12 ROMs don't have this either. There's no actual good reason to not have a separate option. No downsides to adding it, only upsides.

**Comment by 0-BlackSpectrum-0** [comment]
> It should be on OxygenOS and OneUI also. 

Can Confirm that pure black option is not on One ui! Not through Android 11 to Android 14 atleast.

**Comment by MillionsToOne** [comment]
> > It should be on OxygenOS and OneUI also. 
> 
> Can Confirm that pure black option is not on One ui! Not through Android 11 to Android 14 atleast.

Phone?

**Comment by 0-BlackSpectrum-0** [comment]
> > > It should be on OxygenOS and OneUI also. 
> > 
> > Can Confirm that pure black option is not on One ui! Not through Android 11 to Android 14 atleast.
> 
> Phone? 

I'm on M series phone, but I checked and even S series phone don't have such setting!
