### ISSUE TITLE
Split up email list by date

### ISSUE THREAD

**Issue by LorenDB** [thunderbird/thunderbird-android#8433]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b4

### Problem you are trying to solve

I'm migrating to Thunderbird from Outlook. In Outlook, conversations are grouped by the date they were sent. The current day's conversations are grouped at the top with no heading, then there are groups for Yesterday and any other days for the current week, then Last Week, This Month, etc.

### Suggested solution

Add some sort of support for grouping conversations by date. It wouldn't need to be as complex as Outlook's version; just making a group for each day would be fine.

**Comment by kewisch** [comment]
Thank you for reporting! Would you mind filing this as an idea on Mozilla Connect? https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird%20android

I'm going to close it off here so we can organize the ideas a bit more efficiently.
