### ISSUE TITLE
Adding Office 365 account error 

### ISSUE THREAD

**Issue by jew4blackberry** [thunderbird/thunderbird-android#8440]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Other

### Android version

14

### Device model

Pixel 9 Pro Fold

### Steps to reproduce

Login to Office 365 account and I get an error that says user is authenticated but not connected. 

### Expected behavior

To be able to log into my account

### Actual behavior

Gives me an error
![1000172591](https://github.com/user-attachments/assets/3ba4c5c6-11c7-43e6-a152-d933415b16d9)

**Comment by kewisch** [comment]
Could you provide logs via https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors ?

**Comment by jew4blackberry** [comment]
It started working now. Thank you!

**Comment by kewisch** [comment]
Glad it magically works now, thanks for reporting back!
