### ISSUE TITLE
Import from K-9 v6.804 not working

### ISSUE THREAD

**Issue by BillH99999** [thunderbird/thunderbird-android#8442]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Samsung S21 FE

### Steps to reproduce

Download and install release version of Thunderbird for Android (8).
Click on Get Started.
Click on Import your account settings now (under Moving from another app or device).
Click on Import from app.

### Expected behavior

Should import settings from K-9.

### Actual behavior

Get an error:

K-9 Mail
App version not supported.

**Comment by jamaa** [comment]
Same here

**Comment by halfbytecode** [comment]
I see the same error. I feel this may not be supported, considering the error message.

However, manually exporting settings and e-mail accounts to a file from K-9 Mail, and then importing them into Thunderbird seems to work.

See: https://support.mozilla.org/en-US/kb/thunderbird-android-import#w_how-to-import-email-account-settings-using-a-settings-file-from-thunderbird-or-k-9

**Comment by kewisch** [comment]
Indeed, this feature is only supported with K-9 Mail 8.0 and above. You should be receiving the update soon, they have been rolled out yesterday and today. The file export is a good workaround.
