### ISSUE TITLE
Thunderbird Android crashes when trying to import multiple email accounts by scanning a QR code

### ISSUE THREAD

**Issue by Apromixately** [thunderbird/thunderbird-android#8443]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Samsung Galaxy S10 G973FXXSGHWC2

### Steps to reproduce

1. Start Thunderbird
2. Open export feature on desktop Thunderbird with more than one account
3. Point camera at QR code
4. (nothing happens...)
5. Click "Scan" -> App closes/crashes/disappears

### Expected behavior

It should import the accounts as it did when I went back in the desktop menu and only selected a single account. Importing both accounts individually worked fine so I guess it's nothing about the accounts.

### Actual behavior

see above

### Logs

lmk if you cannot reproduce I can't get logs atm

**Comment by kewisch** [comment]
Could you see if the debug log shows anything special?

https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors

Does it say anything about  java.util.AbstractList$Itr.checkForComodification or java.util.ConcurrentModificationException ?

**Comment by NithinMJose** [comment]
I have the same issue.
I have multiple accounts synced in my windows version.
While i am trying to import the settings to android phone, scanning qr code does nothing for me. 
Here are the step i followed.
1. Install Thunderbird (stable)
2. Go to import settings
3. Scan QR Code

This basically does nothing. QR Code is not recognized. There is only a "done" button , but clicking it does nothing.(tried both stable and beta versions)
Device spec:
 Nothing phone 2
 Android 14


Attaching my debug logs below.
[k9mail-logs.txt](https://github.com/user-attachments/files/17596370/k9mail-logs.txt)

**Comment by kewisch** [comment]
@NithinMJose does it just not work, or does the app crash? This issue is more specifically about the crash. I don't see a stack trace int he logs you've provided. @Apromixately would you happen to have a log handy?

**Comment by NithinMJose** [comment]
@kewisch app doesn't crash. When I click scan QR code and scan the QR, it doesn't do anything. I tried in 2 different phones and the same behaviour in both.

**Comment by cketti** [comment]
@NithinMJose: QR codes not being scanned is tracked under #8464. 

@Apromixately: It's hard to track down such a crash without a debug log. Please try to record one.
