### ISSUE TITLE
Importing via QR Code does not import Umlauts in sender name correctly

### ISSUE THREAD

**Issue by morbatex** [thunderbird/thunderbird-android#8444]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

14

### Device model

FairPhone5

### Steps to reproduce

* Create an account where umlauts (or other non ascii characters like Ø) are part of the sender name on a PC
* Create an QR code to export the account to Thunderbird for Android in Thunderbird on PC
* Check the QR code with a generic QR code scanner to see the umlauts are correctly included in the QR code
* Import the account into Thunderbird for Android via the QR code
* Check the imported sender name in Thunderbird for Android

### Expected behavior

Thunderbird for Android should correctly import the sender name

### Actual behavior

Thunderbird does not import the sender name correctly but shows the unicode replacement character "�" instead of umlauts

**Comment by mkmelin** [comment]
Should be fixed with https://bugzilla.mozilla.org/show_bug.cgi?id=1928114

**Comment by morbatex** [comment]
I just tested the new version and can confirm, that it works when using it
