### ISSUE TITLE
Export QR code cannot be read with dark theme enabled

### ISSUE THREAD

**Issue by kaivol** [thunderbird/thunderbird-android#8445]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

12

### Steps to reproduce

1. Activate dark theme in Thunderbird Desktop
2. Follow steps to import settings from Thunderbird Desktop: https://support.mozilla.org/de/kb/thunderbird-android-import#w_export-thunderbird-desktop-settings
3. Try to scan the QR code (whose colors are inverted)

### Expected behavior

Thunderbird for Android should be able to detect and read the QR code even with inverted colors.
(OR Thunderbird Desktop should not invert the QR codes colors with the dark theme enabled) 

### Actual behavior

Thunderbird for Android doesn't detect the QR code.

**Comment by kewisch** [comment]
This sounds like a desktop issue, I see there is https://bugzilla.mozilla.org/show_bug.cgi?id=1928234 which is similar. I'll let them know about this issue so they can fix it there.

**Comment by kewisch** [comment]
@kaivol would you mind chiming in on the linked bug with steps to reproduce?
