### ISSUE TITLE
trigger swiping gesture when using the android back gesture

### ISSUE THREAD

**Issue by thalheimrob** [thunderbird/thunderbird-android#8476]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

15

### Device model

Google Pixel 7 Pro

### Steps to reproduce

1. Go in message overview
2. Using back gesture

![WhatsApp Image 2024-11-02 at 21 08 32](https://github.com/user-attachments/assets/0b76b53f-87d1-44d2-a18f-b72b65469604)

### Expected behavior

just go back without doing or showing anything else

### Actual behavior

Trigger the "mark as unread gesture". When i open the app again the message is than marked as unread then.

**Comment by Agreborig** [comment]
Update: The bug isn't there anymore, the issue can be closed. Maybe just a temporary bug, maybe even a problem with the android system itself, as I have several issues with an unstable system in the last days.

**Comment by Agreborig** [comment]
Update: The bug isn't there anymore, the issue can be closed. Maybe just a temporary bug, maybe even a problem with the android system itself, as I have several issues with an unstable system in the last days.
