### ISSUE TITLE
Lost all K9mail messages

### ISSUE THREAD

**Issue by bovergaauw** [thunderbird/thunderbird-android#8477]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b5

### Where did you get the app from?

F-Droid

### Android version

10

### Steps to reproduce

Not applicable, my messages are lost!

F-Droid suggested me to upgrade from K9mail to the latest Thunderbird beta, the upgrade process repeatedly requested if I wanted to upgrade without losing anything, and when I accepted the message repeated itself. This happened several times so in the end I had to cancel. F-Droid allowed me to open the app anyway, but no icon anywhere. When went back to F-Droid to open it again it was no longer installed to I reinstalled Thunderbird. Thunderbird started as a new app, but allowed me to import my old K9mail settings. No messages though. As I had used K9mail with POP3 in the past, this means at least my sent messages are gone. Extremely annoying an disappointed for a Mozilla app.

### Expected behavior

Being able to read my old messages

### Actual behavior

All messages gone

**Comment by cketti** [comment]
How did you import the settings from K-9 Mail? From a settings file that you have previously exported from K-9 Mail? Or did Thunderbird detect that K-9 Mail is already installed and allowed you to import the settings from the app? If it's the latter, K-9 Mail is still installed and your messages should still be there.
