### ISSUE TITLE
F-Droid: update from K-9 to Thunderbird is suspicious

### ISSUE THREAD

**Issue by iheinrich** [thunderbird/thunderbird-android#8479]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

F-Droid

### Android version

10

### Device model

Samsung A40

### Steps to reproduce

With a pre-8.0 version of K-9 installed check for updates on F-Droid.

### Expected behavior

Definitely:
* Thunderbird app description to contain prominent information that K-9 has become Thunderbird. Ideally with a link detailing the change.

Possibly also:
* Thunderbird app title (on F-Droid) could have been "Thunderbird (formerly K-9)".
* K-9 version screen of previous versions could have included "K-9 will become Thunderbird".

If any of the above would have been present the update would not have come as such a big surprise. At least to me.

### Actual behavior

Users of K-9 are getting an **unexpected** notification from F-Droid that an update of Thunderbird is available.

**Comment by kewisch** [comment]
This is a mistake in our release automation. The listing is wrong and we're trying to fix this ASAP.

**Comment by kewisch** [comment]
#8478
