### ISSUE TITLE
K9 Mail IMAP password length limit

### ISSUE THREAD

**Issue by gtellalov** [thunderbird/thunderbird-android#8488]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b5

### Where did you get the app from?

F-Droid

### Android version

HyperOS 1.0.10

### Device model

Xiaomi Redmi 12S

### Steps to reproduce

1. Create a new account
2. Fill in the IMAP password field with more than 25 characters (same for SMTP)
3. The newest characters > 25 cause a shift in the password where characters from the beginning are cut

### Expected behavior

Accepting passwords of unlimited length.

### Actual behavior

Accepting only a 25 characters long passwords.

**Comment by ByteHamster** [comment]
There is no length limit. You can just scroll to the left to see the beginning of the long password
