### ISSUE TITLE
Why the Breton language has been removed?

### ISSUE THREAD

**Issue by ILPlais** [thunderbird/thunderbird-android#8496]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0

### Problem you are trying to solve

I noticed that the Breton language (brezhoneg) had been removed from the application. Even though it's still present on [Weblate](https://hosted.weblate.org/projects/tb-android/app-strings/br/).
Is there a reason for this?

### Suggested solution

Put back in place the Breton translation of the application.

**Comment by kewisch** [comment]
https://hosted.weblate.org/projects/tb-android/-/br/ is where you can help. We'd love to see you as a contributor for Breton, let us know if you need help getting started.
