### ISSUE TITLE
Import from desktop: folder settings are not imported

### ISSUE THREAD

**Issue by Iey4iej3** [thunderbird/thunderbird-android#8499]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

F-Droid

### Android version

Android 14 (LineageOS 21)

### Steps to reproduce

1. Import from Thunderbird Desktop (Linux)
2. Check folder settings

### Expected behavior

Folder settings are correctly imported

### Actual behavior

For example, for me, the customized folder for "Archives" is not correctly imported (it is "Automatic" there).

**Comment by Iey4iej3** [comment]
> (i don't use push mail)

For push mails, you have to enable them one by one as well: by default, it is disabled for every folder.

**Comment by kewisch** [comment]
There is only so much space in a QR code, so we've limited the import to some basic information. There are some ideas on how we could do this better in the future (e.g. something like Mozilla Sync, where you can simply keep all your settings in sync), but this is outside of scope for the QR code import.

We're going to update https://support.mozilla.org/en-US/kb/thunderbird-android-import soon with the limitations.

**Comment by ragectl** [comment]
I just ran into this problem with Archives folder not being set when importing settings to Android from Desktop.

Given these are all standard folders that in my case are all set to 'automatic' it's crazy to say these cannot be supported.
