### ISSUE TITLE
Can't import accounts in Thunderbird app using QR code

### ISSUE THREAD

**Issue by blogdemoi** [thunderbird/thunderbird-android#8506]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

TB v8

### Where did you get the app from?

F-Droid

### Android version

Android 15 with GrapheneOS up to date

### Device model

Pixel 7

### Steps to reproduce

I generate a QR code from my TB desktop (128.4.0esr (64-bit)) (Manjaro)
I click on "Import parameters" in the TB Android app
It opens a camera view and I can see the QR code in it
Nothing happens, no import

### Expected behavior

The TB Android app should scan the QR code and import accounts.

### Actual behavior

I generate a QR code from my TB desktop (128.4.0esr (64-bit)) 'Manjaro)
I click on "Import parameters" in the TB Android app
It opens a camera view and I can see the QR code in it
Nothing happens, no import

**Comment by kewisch** [comment]
Hi, can you check some of the troubleshooting steps at https://support.mozilla.org/en-US/kb/thunderbird-android-import ? Try holding the camera a bit further away, and if you have dark mode enabled on desktop maybe disable it so the QR code is black/white.

**Comment by VladLucaci** [comment]
@kewisch Can confirm that we have encountered the same issue using 8.1, 8.0 and 8.0.b5. Changing the OS theme to light was the correct workaround in order for the device to properly scan the QR code.

**Comment by gitrazorhub** [comment]
Same issue for me on Android.

-Desktop TB version 128.4.1esr (64-bit) Ubuntu Mate.
-Android 14
-Pixel 5

After the step 'Select Import settings' the camera opens and a DONE button is shown but pressing it does nothing but move to the next page without any settings transferred.

**Comment by kewisch** [comment]
Can you confirm this issue is fixed in Thunderbird Desktop 128.5.0esr or later?

**Comment by gitrazorhub** [comment]
Working on 128.5.0esr

**Comment by kewisch** [comment]
Super, thank you!

**Comment by technosf** [comment]
Light theme works, dark does not - 128.5.2esr

**Comment by trenchant6912** [comment]
It doesn't work for me with 128.6.0esr, android version 8.2. Light and dark themes are all failed.

**Comment by Holly-49-blip** [comment]
I just used a snipping tool, copied the picture, send it to me via email, opend it on my ipad and held the Android phone again in front of the picture...from there it worked perfectly...seems that my laptops monitor is just too old
