### ISSUE TITLE
Very faint QR code does not scan in App

### ISSUE THREAD

**Issue by bad1080** [thunderbird/thunderbird-android#8507]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

8.0

### Where did you get the app from?

F-Droid

### Android version

Android 13 / crDroid 9.15

### Device model

Redmi Note 10

### Steps to reproduce

1. in Thunderbird 128.4.1esr (64-bit) for Arch Linux go to "Export to mobile" 
2. then click "Export"
3. the generated QR code is so faint the phone can't scan it (see attached image)
4. i tried switching to light mode in themes to see if that had anything to do with it but to no avail

### Expected behavior

a nice crisp QR code would be displayed which the phone is able to scan

### Actual behavior

the generated QR code is so faint the phone is not able to scan it

### Logs

![image](https://github.com/user-attachments/assets/ddcdeccf-9a3b-469f-a2bc-e6b0ae0ba8ca)

**Comment by kewisch** [comment]
@freaktechnik Looks like the colors are still not great on dark mode. Can you have a look?

**Comment by bad1080** [comment]
> @freaktechnik Looks like the colors are still not great on dark mode. Can you have a look?

like i said i tried light mode too and it is the same problem. 
![image](https://github.com/user-attachments/assets/18c9c602-be2e-477a-8584-43b41729bb2e)

**Comment by kewisch** [comment]
I've heard from the team that a fix that will likely also fix this will be in 128.4.2 or one point release after.

**Comment by bad1080** [comment]
> Alright, thank you. I'll check again with the desktop team. Do you have any custom themes, or is this the standard dark mode? Do you have any OS high contrast or other related settings enabled? Are there any color settings in your OS that use that grey? What desktop environment do you have?

-this is the standard dark mode from thunderbird, yes. ![Image](https://github.com/user-attachments/assets/ed8fd665-49af-4166-ad6d-cfd9fbe14a80)
-the desktop environment is KDE plasma also in dark mode called Vapor. ![Image](https://github.com/user-attachments/assets/64142419-4ac2-443d-a2e3-05f0cb9cc626)
-i am not using any high contrast modes and i am not aware of any related options nor the question about the grey.

**Comment by kewisch** [comment]
Ah apologies, I missed that this wasn't actually merged on ESR yet. It should work on Thunderbird Desktop Beta, could you try there?

**Comment by bad1080** [comment]
> Ah apologies, I missed that this wasn't actually merged on ESR yet. It should work on Thunderbird Desktop Beta, could you try there?

in the beta version the QR code looks as expected: ![Image](https://github.com/user-attachments/assets/a8222b67-0a0b-4c56-b568-cad862f01e91)

**Comment by cketti** [comment]
Thanks for letting us know. Closing this issue because it's about the desktop app and the bug is already fixed in beta.
