### ISSUE TITLE
Incomplete sync with IMAP-Inbox

### ISSUE THREAD

**Issue by M1ster-T** [thunderbird/thunderbird-android#851]
I have a somehow strange behaviour since a couple of weeks: The inbox of my imap-mail-account (at 1&1) is not correctly synced any more. With Thunderbird or the 1&1-Webmail, I can see all my mails, but K9 only shows a few. When I get new mails, K9 does not show most of them, only some.

This seems to be limited to the inbox. Other IMAP-folders can be synced and seem to display all mails.

I tried to clean up the inbox-folder ("expunge" with K9 and according operations with thunderbird/webmail client), but no effect.

I use the current version of K9 (v5.006) under Android 5.0 on two different Samsung devices. Is there any more information I should provide that could help?

**Comment by cketti** [comment]
Please try to record a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors
