### ISSUE TITLE
"Configure manually" distracts users to hit the "Next" button

### ISSUE THREAD

**Issue by davidhedlund** [thunderbird/thunderbird-android#8512]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

10

### Device model

LG G7 ThinQ

### Steps to reproduce

Open Thunderbird
* Prompt 1:  Click on "Add an email account now"
* Prompt 2: Enter an email address to a custom server (not gmail, hotmail, etc)
* Prompt 3: Click on "Configure manually"
![image](https://github.com/user-attachments/assets/56ac9d5a-0d51-4b01-8d53-957a8d5c8d7d)

* Click "Next"
* Prompt 4:
![image](https://github.com/user-attachments/assets/3c088db5-50bd-4f53-ad8f-4f5b154fc1ac)

### Expected behavior

1: The background color should remain unchanged when clicking on "Configure manually" since it is not a button.
2: The text "Configure manually" should be black, as it's just text

These issues have led some users to believe that manual configuration of Thunderbird is not possible, as they may overlook the "Next" button. For example, see the comment at https://blog.thunderbird.net/2024/10/thunderbird-for-android-8-0-takes-flight/#comment-5773.

### Actual behavior

1: The background color is changed to gray when you click on "Configure manually" which indicates that it's a button
2: The text "Configure manually" is blue, this color suggests it is a link intended to open the manual configuration prompt.

**Comment by kurisufriend** [comment]
yep, just got bit by this. awful UX.
