### ISSUE TITLE
QR Code includes not all accounts

### ISSUE THREAD

**Issue by fuste76** [thunderbird/thunderbird-android#8515]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Xiaomi Mi 10 Lite 5G

### Steps to reproduce

1 select all accounts
2 created QR code
3 scan QR Code
4 not all accounts were imported

### Expected behavior

The QR Code should include all accounts at once. 

### Actual behavior

Tried to migrate 4 Accounts from Thunderbird Desktop to Thunderbird Android. Only 3 of 4 were migrated. Had to migrate the 4th Account via a second QR Code.

**Comment by kewisch** [comment]
Can you take a look here if any of these situations apply to you? https://support.mozilla.org/en-US/kb/thunderbird-android-import#w_not-seeing-all-your-email-accounts

**Comment by fuste76** [comment]
Thanks for your answers. I think, the link does not apply to me. I have 3 gmx accounts, all configured with the same Server settings and one Gmail account. I had to migrate twice. The first one migrated 2 gmx and Gmail, with the 2nd round i migrated the 3rd gmx account. Its not a big thing. Once if its done , its running well.

**Comment by cketti** [comment]
If you have more than 3 accounts Thunderbird typically creates multiple QR codes. You'll have to press the "Next" button on Thunderbird desktop to move to the next QR code. After scanning the first QR code the Android app will display a message showing you how many QR codes you've scanned already and how many there are total (e.g. "Scanned 1 of 2").

**Comment by fuste76** [comment]
Oh...yes i have seen a message like scanned 1 of 2. Maybe i should have given it more attention. This entry can be closed, as this is no failure in Thunderbird. Sorry.
