### ISSUE TITLE
Not getting any notifications

### ISSUE THREAD

**Issue by phantomromano** [thunderbird/thunderbird-android#8537]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Nokia G42 5G

### Steps to reproduce

Enable notifications in Thunderbird. Disable any kind of power saver features for Thunderbird, grant Thunderbird the permission to send push notifications

### Expected behavior

Every time thunderbird checks my e-mails, I should receive a notification if I have received any new emails.

### Actual behavior

I have not gotten a single notification from Thunderbird ever. I use the app since it was released.

### Logs

No specific path to reproduce this problem, so no logs. However, I did notice that Thunderbird does not show up in the accounts section in android settings. Maybe it has something to do with that? No clue.

**Comment by pvones** [comment]
See my bug #8549 Maybe it is the same issue.

**Comment by PhoenixIV** [comment]
You need to manually enable push: Open your menu / sidebar > At the bottom "Manage folders" > Choose Inbox > Enable Push

@ Thunderbird: This should be possible to automatically set up when adding the account

Note: Now it **should** work, but it does not for me! See https://github.com/thunderbird/thunderbird-android/issues/8549#issuecomment-2467925200 in the ticket that was just already mentioned.

**Comment by kewisch** [comment]
Let's centralize this into #8549. Thanks for reporting!
