### ISSUE TITLE
Difference in F-Droid icon size between net.thunderbird.android and net.thunderbird.android.beta

### ISSUE THREAD

**Issue by leoheitmannruiz** [thunderbird/thunderbird-android#8538]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Steps to reproduce

Visit https://search.f-droid.org/?q=thunderbird&lang=en

### Expected behavior

That the icon of net.thunderbird.android and net.thunderbird.android.beta is the same, except for the "BETA" badge.

### Actual behavior

Icon for net.thunderbird.android.beta is smaller.

**Comment by kewisch** [comment]
@laurelterlesky is this an issue we should fix? I know you like consistency :)

**Comment by wmontwe** [comment]
Seems like an export issue, here are the app icons in similar size: https://github.com/thunderbird/thunderbird-android/tree/main/images/thunderbird
