### ISSUE TITLE
Adaptive Junk Filtering

### ISSUE THREAD

**Issue by DazzaJay** [thunderbird/thunderbird-android#8539]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0

### Problem you are trying to solve

Desktop Thunderbird has fantastic adaptive spam filtering. Please bring this feature to android. 

### Suggested solution

Implement an adaptive junk filtering system similar to the PC version of Thunderbird, complete with [Junk] and [Not Junk] buttons.

**Comment by kewisch** [comment]
Thanks so much for sharing your idea. For enhancement suggestions like this, would you mind posting them over on [Mozilla Connect](https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird%20android)?

To get the most out of your post, check out [this quick guide](https://connect.mozilla.org/t5/discussions/how-to-submit-a-great-idea-in-five-easy-steps/m-p/24) on crafting impactful suggestions. Focusing on the problem your idea solves and how it could help others can really make it stand out!

In the past we've been avoiding spam filtering as this is a task much better suited for the email service, but we can certainly look into this if there is a strong demand.

I’ll be closing this issue to keep our GitHub focused on active development, but I hope to see your idea over there.
