### ISSUE TITLE
K-9 fails to install in "Private Space"

### ISSUE THREAD

**Issue by Suika** [thunderbird/thunderbird-android#8545]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

8.0 - 05.11.2024

### Where did you get the app from?

F-Droid

### Android version

GrapheneOS Release 2024110700 - Android 15

### Device model

Pixel 8

### Steps to reproduce

1. Setup Private Space in Android
2. Download and install F-Droid in private space
3. Install K-9 (8.0 - 05.11.2024) from the F-Droid store in private space
4. Installation will be interrupted due to "unknown error"

If the package is downloaded from f-droid and is installed via android board tools, the installation will be interrupted with the error being "invalid package".

### Expected behavior

Being able to install K-9 into private space like one does with the default profile.

### Actual behavior

K-9 fails to install due to unknown error.
Strangely, the "Thunderbird (8.0 - 02.11.2024)" version installs without any issues.

**Comment by ByteHamster** [comment]
My guess would be that you already have K-9 installed outside the private space, but there you got the app from Google Play instead of from F-Droid. You can't use the same app from different sources in a private space because the signature is different. Either install both from F-Droid or both from Google Play.

**Comment by Suika** [comment]
Your guess is on point. It slipped my mind as to where from it was installed.
