### ISSUE TITLE
accounts missing from TB desktop->mobile account export/import

### ISSUE THREAD

**Issue by pgnd** [thunderbird/thunderbird-android#8554]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b5 TB/android;  128.4.2esr TB/linux

### Where did you get the app from?

Google Play

### Android version

multiple devices/versions

### Steps to reproduce

i use TB, on desktop
```
	Name 	Thunderbird
	Version 	128.4.2esr
	Build ID 	20241105224936
	OS 	Linux 6.11.5-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 20:11:15 UTC 2024
```

i installed TB/beta 8.0b5 from PlayStore, on Android

in TB Desktop, I have 11 inbound/IMAP accounts
```
		userA@example1.com
		userA@example3.com
		userB@example2.net
		admin@int.example3.com
		postmaster@example1.com
		postmaster@example2.net
		myUser@externalMailService.com
		gmUser1@gmail.com
		gmUser2.test@gmail.com
		userC@example1.com
		userD.out@example2.net
```

where

	example1.com
	example3.com
	example2.net
	int.example3.com

are all 'my' owned domains, with mail hosted on the same, local server.

gmail.com & externalMailService.com are externally hosted services.

i want to import all those accounts into TB/Mobile.

@
```
	Settings -> Export for Mobile -> Export accounts to Thunderbird Mobile
```

displays only 6 accounts.
```
	Select which accounts to export:

		Email accounts
			userA@example3.com
			myUser@externalMailService.com
			gmUser1@gmail.com
			gmUser2.test@gmail.com
			userC@example1.com
			userD.out@example2.net
```

QR codes *ARE* generated -- there are two.

importing both stepwise into TB/Mobile completes without any obvious error.
those 6 accounts are correctly imported, and seem to function as expected. as far as i've checked, anyway.

the missing accounts are in the SAME DOMAINS, on the same server(s), and similarly configured, as others that ARE offered for export.

the issue is:

  those *other* 5 accounts aren't being presented/available for export.

*closest* found issue match,

 "QR Code includes not all accounts #8515"
   https://github.com/thunderbird/thunderbird-android/issues/8515

doesn't address the issue here.

the missing accounts can be added manually.
this issue reproduces -- with obviously different accounts -- for (so far) 4 different users+TBDesktopInstances+AndroidDevices.

### Expected behavior

export/import all accounts from TB Desktop

### Actual behavior

failed to export/import all accounts from TB Desktop

**Comment by cketti** [comment]
See [Not seeing all your email accounts?](https://support.mozilla.org/en-US/kb/thunderbird-android-import#w_not-seeing-all-your-email-accounts). If that still doesn't explain why some accounts don't show up, please open a bug for Thunderbird desktop: https://bugzilla.mozilla.org/describecomponents.cgi?product=Thunderbird
