### ISSUE TITLE
Checking incoming server settings failed

### ISSUE THREAD

**Issue by papaDoc** [thunderbird/thunderbird-android#8567]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.1

### Where did you get the app from?

Google Play

### Android version

15

### Device model

Pixel 7a

### Steps to reproduce

Before I was able to see my new mail and now I can. Nothing append
I found that I have an error message while fetching the email
1- Open the hamburger menu while in an account
2- Select the setting wheel
3- Select one account (I have only one)
4- Select Fetching mail
5- Se3lect Incoming server
6- Verify that all the field are good (There were working before an update)
7- Select Next
8- The following message is displayed

Checking incoming server settings failed
Network error
Details:
readStringUntuil(): end of stream reached. Read: "" while waiting for ' '

N.B. I have the same setting for K9 and I can fetch the email and I don't have this error message while testing the configuration.

I have a personal web server running under raspbian and running courier-imap

### Expected behavior

Should be able to complete the fetching test with out error.

### Actual behavior

I have the following error message:
Checking incoming server settings failed
Network error
Details:
readStringUntuil(): end of stream reached. Read: "" while waiting for ' '

### Logs

[https://drive.google.com/file/d/1bb5HRYuOSi3MVapvcLOfdqDBao_plGqG/view?usp=drive_link](My Logs)

https://drive.google.com/file/d/1bb5HRYuOSi3MVapvcLOfdqDBao_plGqG/view?usp=drive_link

**Comment by cketti** [comment]
Please attach the log to the GitHub issue instead of uploading it to Google Drive.

**Comment by papaDoc** [comment]
Finally there was a problem on the server side and it was fixed.
