### ISSUE TITLE
K-9/Thunderbird does not show all the headers

### ISSUE THREAD

**Issue by hman2** [thunderbird/thunderbird-android#8572]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

F-Droid

### Android version

10, Fairphone Open OS 10 23.02.0-rel.0 (latest AOSP, with full support from the manufacturer)

### Device model

Fairphone 2

### Steps to reproduce

1. Open any e-mail
2. Click on the three dots
3. Select "show headers"

### Expected behavior

Seeing all headers of that particular e-mail

### Actual behavior

Seeing just *some* headers, but not all of them

### Logs

I think I don't need a log here.

**Comment by hman2** [comment]
I especially miss the header line "envelope-to:". This is omnipresent, without that, the e-mail would not have arrived. This is the actual designated recipient address for the mail, not the to: header.

Why is that important if it is omnipresent? Isn't that just the address of the account just opened? No, it isn't.

If you use "disposable addresses" as a mechanism to fight spam, then you have multiple mail addresses that you shell out whenever some business or service asks for your mail address. All those are redirected (at your ISP) to your real mail addresse, so you only have to check one inbox. And should that business or service sell your mail address to some evil spammers, or got hacked, you simply look at the disposable address and turn it off, after informing the business or service.

But K-9/Thunderbird does not show me this info. I also suspect that *lots* of other headers are left out, because I see spam in my inbox with just five or six header lines, which is implausible. Many mail transfer services along the path of the mail insert some sort of spam check results. Those are missing, too.

**Comment by cketti** [comment]
All headers are currently only available after the complete message has been downloaded. See #5240.
