### ISSUE TITLE
Thunderbird 8.1 still identifies as "Thunderbird Beta" in notifications.

### ISSUE THREAD

**Issue by rarog** [thunderbird/thunderbird-android#8573]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.1

### Where did you get the app from?

Google Play

### Android version

14

### Device model

OnePlus 9 Pro

### Steps to reproduce

1. Get an email
2. Look in list of Android notifications.

### Expected behavior

Just "Thunderbird" without beta.

### Actual behavior

Showing "Thunderbird Beta".

**Comment by cketti** [comment]
Thunderbird and Thunderbird beta are separate apps. If you installed the beta, but want to use the release version, you have to install the release version. Its Google Play page can be found here: https://play.google.com/store/apps/details?id=net.thunderbird.android

**Comment by rarog** [comment]
I was unaware or ignorant. Thx. Then this can be closed.
