### ISSUE TITLE
Change K-9 funding link

### ISSUE THREAD

**Issue by wmontwe** [thunderbird/thunderbird-android#8604]
We need to use the `k9mail` campaign for funding links to Fundraiseup

https://www.thunderbird.net/donate/mobile/?form=k9mail

**Comment by wmontwe** [comment]
@kewisch Could you confirm that this is the full link?

https://www.thunderbird.net/donate/mobile/?form=k9mail&amp;utm_source=%s&amp;utm_medium=android_app&amp;utm_campaign=inapp_appeal_v1

**Comment by kewisch** [comment]
Yes, looks good!

**Comment by leobard** [comment]
In  case someone wonders why a donation just came in with ÷s still in the link: I googled for "thunderbird k9 donate" as I had to renew my k9 donation and found this thread and clicked above link. 

Kthxbai
