### ISSUE TITLE
update the readme about ffupdater

### ISSUE THREAD

**Issue by tetify** [thunderbird/thunderbird-android#8615]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.1

### Where did you get the app from?

Other

### Android version

Android 14

### Device model

Samsung galaxy S22

### Steps to reproduce

The developer released an [new version](https://github.com/Tobi823/ffupdater/releases/tag/79.3.0) that support thunderbird on stable and beta version as you can see here:
![install page](https://github.com/user-attachments/assets/b8e1df4a-6506-4304-9612-afdddc1d74b3)

And it works
![home](https://github.com/user-attachments/assets/aec0920b-bcdc-4ae2-a0c5-d5b8a3f4d748)

### Expected behavior

An readme update to add an link to download ffupdater (or an tutorial on how to download and update)

### Actual behavior

The readme still saying that its coming soon

**Comment by kewisch** [comment]
Thanks for the reminder, I wasn't sure if the release was ready yet :) I sent a PR to update the README

**Comment by tetify** [comment]
Thanks
