### ISSUE TITLE
`x in Subject rendered as grave accent

### ISSUE THREAD

**Issue by dilyanpalauzov** [thunderbird/thunderbird-android#8629]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

8.1

### Where did you get the app from?

None

### Android version

14

### Steps to reproduce

With K9 8.1 I receive an email about https://github.com/rust-lang/rust/issues/133614 with
```
Subject: Re: [rust-lang/rust] dash: `x.py install` removes rustc and cargo,
 without installing them (Issue #133614)
```
K9 replaces the backtick and x with an x with [grave accent](https://en.wikipedia.org/wiki/Grave_accent). ( I cannot type x with grave accent on my computer keyboard)

### Expected behavior

Subject should be rendered as
> dash: `x.py …

### Actual behavior

Subject contains x with grave accent.

**Comment by dilyanpalauzov** [comment]
![Image](https://github.com/user-attachments/assets/26bfcaec-94d7-4db1-ade4-01ca074e055f)

**Comment by cketti** [comment]
I can't reproduce this on my test devices. It might be related to the system font on your device. Can you try switching to a different font and see if the subject is then displayed correctly?

**Comment by dilyanpalauzov** [comment]
Yes, this happens with font families Default or Square.  With font families Android or Slab the problem disappears.
