### ISSUE TITLE
Cannot create account on Android mobile

### ISSUE THREAD

**Issue by MollyMagic** [thunderbird/thunderbird-android#8635]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.1

### Where did you get the app from?

Other

### Android version

I don't understand this question but I am using Fairphone 4's de-googled OS

### Device model

Fairphone e/os

### Steps to reproduce

Download either thunderbird android or K9 mail
Click start and add email address (I have a yahoo email)
Complete the I Am Not A Robot picture test
Click verify
Error message returned that says I have had too many attempts

This error msg occurred on the 1st attempt
I tried several sgsin but to no avail
I waited until the next day and tried again and got an error on 1st attempt again

### Expected behavior

After completing thdvrobot test I expected the acc to be added

### Actual behavior

The app returned  a 'too many attempts' error msg. This is rubbish: I completed the test carefully

**Comment by cketti** [comment]
This is not an error message generated by the app. The sign-in process is handled by Yahoo. Please contact them for support.
