### ISSUE TITLE
Loop when decrypting PGP/MIME mail

### ISSUE THREAD

**Issue by phoerious** [thunderbird/thunderbird-android#864]
Using the current master branch I'm trying to decrypt PGP/MIME mails using OpenKeychain.
When I open the message, K9 correctly starts OpenKeychain which lets me enter my PIN and then asks me to hold my YubiKey NEO to the NFC scanner.
After the decryption is done, I remove the key and OpenKeychain gives control back to K9 which in turn opens OpenKeychain again. This repeats forever. When I click "Cancel", it stops the loop but also crashes K9 (probably issue ##588).

**Comment by petervnv** [comment]
I can confirm this exact same behaviour, except in my case the yubikey holds the keys while openkeychain holds the stubs
