### ISSUE TITLE
No Forward and Forward as attachment function in the K-9 Mail available

### ISSUE THREAD

**Issue by baack** [thunderbird/thunderbird-android#8643]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

8.1

### Where did you get the app from?

F-Droid

### Android version

10

### Steps to reproduce

1. Open Inbox in any account.
2. Select any message (or don't, it does not matter)
3. Press 3 vertical dots button in the right upper corner of the screen

### Expected behavior

There would be an ability to Forward the letter, Forward as attachment.

### Actual behavior

Only Move, Copy, Add star, Spam and Select All are available.
I failed to find the way to forward the letter, it is ridiculous.

**Comment by cketti** [comment]
The app currently only supports forwarding a single message. You can find the functionality by opening a message, then expanding the menu next to the reply button.

A feature request to add support for forwarding multiple message already exists. See #6557.

**Comment by baack** [comment]
> The app currently only supports forwarding a single message. You can find the functionality by opening a message, then expanding the menu next to the reply button.

Oh, thank you. Then it must be a usability bug, because I was trying to find this function it so many times, I even search internet and K-9 Mail documentation for it.
User does not expect 2 different vertical dots buttons, that's too unusual to be good. Why not move all functions to the upper menu button?

**Comment by cketti** [comment]
That's in preparation of having a conversation view where multiple messages are displayed in the same screen. It's also consistent with how other email apps on Android do it (Gmail, Outlook, etc.)
