### ISSUE TITLE
mails won't delete

### ISSUE THREAD

**Issue by RazielKanos** [thunderbird/thunderbird-android#8668]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.1

### Where did you get the app from?

F-Droid

### Android version

14

### Device model

Samsung Glalaxy S23 Ultra

### Steps to reproduce

Swipe to delete a mail
mail gets deleted
open thunderbird on a different device (in my case my tablet) or open a different app (in my case Fair Mail)
check mails
deleted mail is still in my postbox

### Expected behavior

the mail should be deleted from the server

### Actual behavior

the mail just isn't shown anymore on the device you used to delete it. even if you refresh, it doesn't show the deleted mail
It acts as if moves the mail to the trash folder, i can see it in thunderbird in the trash folder, but when i cech directly on my server it's still in the post box

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/18112280/k9mail-logs.txt)

**Comment by cketti** [comment]
Your app is configured to not delete messages on the server. This can be changed under *Settings → [Account] → Fetching mail → When I delete a message*.

**Comment by RazielKanos** [comment]
Thanks - yes that was the issu. but whay is that the default, very confusing :D
