### ISSUE TITLE
Cannot be used with VPN

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#8669]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.2

### Where did you get the app from?

None

### Android version

15

### Steps to reproduce

1. vpn
2. login mail
3. `failed to connect to imap.gmail.com/ 142.251.2.108 (port 993) from /10.8.40.88 (port 56498) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)`

### Expected behavior

I suspect the reason is that Thunderbird does not use 127.0.0.1 (port 56498)..

from /10.8.40.88 (port 56498)

### Actual behavior

failed to connect to imap.gmail.com/ 142.251.2.108 (port 993) from /10.8.40.88 (port 56498) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)
![Image](https://github.com/user-attachments/assets/5bcb8151-0266-4ed3-a732-09d63c712937)

**Comment by kewisch** [comment]
It is possible that the Gmail app uses their API via https and not IMAP, which would explain that circumstance. Can you test a random other email client that uses IMAP? You may need to configure your VPN to allow tunneling port 993.
