### ISSUE TITLE
Missing special charachter in "Your name" after QR code migration from PC

### ISSUE THREAD

**Issue by Pato98** [thunderbird/thunderbird-android#8689]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.2

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Oneplus LE2123

### Steps to reproduce

1. Set a special character to "Your name" on the PC version of Thunderbird like "á" (Hungarian character)
2. Scan the migration QR code from the phone app
3. You will see "?" instead "á" in "Your name" at the phone app settings under Manage identities/e-mail address/Your name.
4. I can fix it easily if I delete the "?" mark and modify it to "á", but a basic user maybe can't solve this problem

### Expected behavior

It's need to migrate the "Your name" with special character too, but now it's didn't work.

### Actual behavior

![Image](https://github.com/user-attachments/assets/4ae6325c-4df0-455a-adac-852894489a3e)

**Comment by cketti** [comment]
Do you remember which Thunderbird desktop version you used to export the accounts via QR code? There used to be a problem with non-ASCII characters. But it should be fixed since 128.4.2 (see https://bugzilla.mozilla.org/show_bug.cgi?id=1928114)
