### ISSUE TITLE
Crash during reading of an email

### ISSUE THREAD

**Issue by GuillaumeSmaha** [thunderbird/thunderbird-android#871]
I receive an email which crashes the app.
After some research, I found that mBody for the file Version_texte.txt is null (LocalBodyPart with minetype "text/plain") and OpenPgpUtils.parseMessage crashes with a null value.
I also tried a new email with this file but mBody is not null.
So I think the issue is located in the loading process.

You can find the mail here : http://guillaume.smaha.net/contrib/k9mail/TestCrashEmail.eml

**Comment by GuillaumeSmaha** [comment]
Ok, the data is also NULL in database.
See export CSV of message_parts from database (first line with the error and secon without)

    id;type;root;parent;seq;mime_type;decoded_body_size;display_name;header;encoding;charset;data_location;data;preamble;epilogue;boundary;content_id;server_extra

    243;0;239;239;4;text/plain;290;Version_texte.txt;"Content-Type: text/plain;
     CHARSET=""ISO-8859-1"";
     NAME=""Version_texte.txt""
    Content-Disposition: attachment;
     filename=""Version_texte.txt"";
     size=290
    Content-Transfer-Encoding: BASE64
    ";;;0;;;;;;2

    257;0;253;253;4;text/plain;212;Version_texte.test.txt;"Content-Type: text/plain; charset=ISO-8859-1; name=""Version_texte.test.txt""
    Content-Disposition: attachment; filename=""Version_texte.test.txt""
    Content-Transfer-Encoding: base64
    X-Attachment-Id: f_igb8kwmg0
    ";base64;;1;"DQpCb25rb3VyDQoNCk5vdXMgYXZvbnMgYmllbiBwcmlzIG5vdGUgZGUgdm90cmUgY29tbWFuZGUg
    c3VyIHh4eCBldCBub3VzIHZvdXMgcmVtZXJjaW9ucyBkZSB2b3RyZSBjb25maWFuY2UuDQoNClZv
    dXMgdHJvdXZlcmV6IGNpLWRlc3NvdXMgbGUgZOl0YWlsIGRlIHZvdHJlIGNvbW1hbmRlIDogDQoN
    Ci0gRGF0ZSBkZSBsYSBjb21tYW5kZSA6ICAwNyBvY3RvYnJlIDIwMTU=";;;;;

**Comment by Valodim** [comment]
Seems to be a simple matter of a missing null check
