### ISSUE TITLE
Draft not saved when using mailto: link

### ISSUE THREAD

**Issue by sirtet** [thunderbird/thunderbird-android#876]
Saving a Massage works when creating a new one inside of k9, but not when started from a mailto: link, eg. In a browser. Using save in the menu shows the "Massage saved" overlay, but i can't find it in the drafts folder.

**Comment by s3b-** [comment]
Device: Nexus 5 with Cyanogenmod 12.1 (Android 5.1.1)
k-9 version: 5.006

1. Using mailto-link in default browser, select k-9 mail, saved with menu save -> mail got saved in drafts

2. Using mailto-link in default browser, select k-9 mail, saved with go back button -> mail got saved in drafts

3. Using mailto-link in opera mini browser, select k-9 mail, saved with menu save -> mail got saved in drafts

4. Using mailto-link in opera mini browser, select k-9 mail, saved with go back button -> mail got saved in drafts

Couldn't reproduce the problem. Is this still a bug?

**Comment by sirtet** [comment]
No, works now... Can't See a difference in the Setup...
