### ISSUE TITLE
issues with saving to drafts

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#886]
K9 doesn't save the signature in the draft.
Therefore it forgets changes in the signature that were made for this particular email.

And it saves quotations from previous emails to the draft even if you clicked on the x to not include them.
If you reopen the draft with K9 Mail the signature will be the default one again.
If you open it with another email program (IMAP) it won't display any signature at all (at least Thunderbird didn't)

**Comment by cketti** [comment]
K-9 Mail saves the signature in a header field when you make changes to your default signature. That header also contains the information on whether or not to include the quoted text. That allows you to later change your mind when reopening the draft.
The chances are high that this information is lost when you edit the draft using another client.

I created issue #902 to change the way K-9 Mail handles drafts.
