### ISSUE TITLE
multipart issue with empty body

### ISSUE THREAD

**Issue by cziebuhr** [thunderbird/thunderbird-android#889]
I periodically receive a newsletter with following (simplified) content. 

```
Content-Type: multipart/alternative; boundary="-----7D81B75CCC90D2974F7A1CBD"

-------7D81B75CCC90D2974F7A1CBD
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable


-------7D81B75CCC90D2974F7A1CBD
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<HTML><BODY>Some html text</BODY></HTML>
-------7D81B75CCC90D2974F7A1CBD--

```
### Expected behaviour

Html part displayed
### Actual behaviour

Nothing displayed
### Environment

K-9 Mail version: 5.006
Android version: 5.1.1

It works when there is text or an additional empty line in the plaintext part.

**Comment by cketti** [comment]
In 5.0xx the message preview is always generated from the text part. But viewing the message should work fine.
The provided snippet worked for me. Can you upload the message source of an actual mail?

**Comment by cziebuhr** [comment]
I just tried with a second account on the same server and couldn't reproduce it there. Thought it may have been an IMAP issue when fetching individual mime parts. But it still occurs in my first account. Do you have an idea what else I can check? Messages < 32kb are automatically fetched in both accounts.

**Comment by cketti** [comment]
Can you uninstall then reinstall the app and check if this still happens? Recording a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors) while fetching the message from the server could help with tracking down the issue.

**Comment by cziebuhr** [comment]
I found it: The issue only occurs when Account settings -> Message composing -> Formatting is set to Plain-Text.

**Comment by cketti** [comment]
To clarify: where does the message not render? In the message view screen or the compose screen?

**Comment by cziebuhr** [comment]
In the message view screen.

**Comment by cziebuhr** [comment]
Have you been able to reproduce the issue or do you need any more information?

**Comment by cketti** [comment]
Thanks. I could reproduce this issue with the instructions you provided.

It looks like K-9 Mail behaved like this since 2012. The code around message loading in 5.0xx is very ugly and quite fragile. So I'd rather not change it in the 5.0xx line.
For the next major version we'll change much of the code dealing with messages anyway. And it looks like this particular bug is already fixed.
