### ISSUE TITLE
backslash in username does not work for IMAP login

### ISSUE THREAD

**Issue by mmehnert** [thunderbird/thunderbird-android#899]
I need to access an exchange server via IMAP. My username has the form username@domain\special_mailbox .
Authentication with just username for the personal mailbox works fine but not for the special mailbox with the backslash syntax above.
I tried two backslashes since I suspected some java string escaping problem, but that did not work either.

**Comment by cketti** [comment]
Works fine for me. The backslash gets properly escaped when using the `LOGIN` command.
```
LOGIN "username@domain\\special_mailbox" "password"
```

Can you log in using another IMAP client?
Have you tried selecting another authentication mechanism?
What version of K-9 Mail are you using?

**Comment by mmehnert** [comment]
The login with Thunderbird and the AquaMail android app works flawlessly.
For thunderbird the setting is SSL/TLS+Normal password, for AquaMail it's SSL+Prefer compatibility.

I tried the Maildroid android app without success, too.

I'm using the latest K-9-app that is available on the google app store.
The server only supports SSL so I've always set security in K9 to SSL/TLS and authentication to "Normal password" since that is the setting that also works in Thunderbird. "Encrytped password" does not work either - but that did not surprise since it also does not work in thunderbird.

**Comment by mmehnert** [comment]
Perhaps I can succeed capturing the login traffic of thunderbird vs. k9 with stunnel and wireshark. Would that be worth a try to get a comparison of what is going on?

**Comment by cketti** [comment]
You can enable debug logging + sensitive logging in K-9 Mail and check the system log to find out what the authentication command K-9 Mail sends looks like exactly. See https://github.com/k9mail/k-9/wiki/LoggingErrors

That should be enough to see the problem. A comparison with Thunderbird won't hurt though.

**Comment by mmehnert** [comment]
During the setup of the account I get the following:

    01-10 13:55:57.553 D/k9      ( 3012): Connecting to exchange.the-domain.de as exchange.the-domain.de/xxx.xxx.xxx.xxx
    01-10 13:55:57.753 V/k9      ( 3012): conn592799248<<<#null# [OK, The Microsoft Exchange IMAP4 service is ready.]
    01-10 13:55:57.753 I/k9      ( 3012): Did not get capabilities in banner, requesting CAPABILITY for conn592799248
    01-10 13:55:57.753 V/k9      ( 3012): conn592799248>>> 1 CAPABILITY
    01-10 13:55:57.793 V/k9      ( 3012): conn592799248<<<#null# [CAPABILITY, IMAP4, IMAP4rev1, AUTH=PLAIN, AUTH=NTLM, AUTH=GSSAPI, STARTTLS, UIDPLUS, ID, CHILDREN, IDLE, NAMESPACE, LITERAL+]
    01-10 13:55:57.793 V/k9      ( 3012): conn592799248<<<#1# [OK, CAPABILITY completed.]
    01-10 13:55:57.793 D/k9      ( 3012): Saving 13 capabilities for conn592799248
    01-10 13:55:57.793 V/k9      ( 3012): conn592799248>>> 2 AUTHENTICATE PLAIN
    01-10 13:55:57.833 V/k9      ( 3012): conn592799248<<<#+# []
    01-10 13:55:57.903 V/k9      ( 3012): conn592799248<<<#2# [NO, AUTHENTICATE failed.]
    01-10 13:55:57.903 E/k9      ( 3012): Failed to login, closing connection for conn592799248
    01-10 13:55:57.903 E/k9      ( 3012): Error while testing settings
    01-10 13:55:57.903 E/k9      ( 3012): com.fsck.k9.mail.AuthenticationFailedException: Command: AUTHENTICATE PLAIN; response: #2# [NO, AUTHENTICATE failed.]    01-10 13:55:57.903 E/k9      ( 3012):   at com.fsck.k9.mail.store.ImapStore$ImapConnection.saslAuthPlain(ImapStore.java:2729)
    01-10 13:55:57.903 E/k9      ( 3012):   at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2530)
    01-10 13:55:57.903 E/k9      ( 3012):   at com.fsck.k9.mail.store.ImapStore.checkSettings(ImapStore.java:703)
    01-10 13:55:57.903 E/k9      ( 3012):   at com.fsck.k9.activity.setup.AccountSetupCheckSettings$1.run(AccountSetupCheckSettings.java:125)


So it seems as if I cannot log the exact authentication that was sent. :-(

**Comment by mmehnert** [comment]
I created a transcript of the IMAP chatter. Apparently the MS Exchange server has problems with the base64 encoded login. Thunderbird successfully reverts back to plaintext. 

K9-Mail

    * OK The Microsoft Exchange IMAP4 service is ready.
    1 CAPABILITY
    * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI STARTTLS UIDPLUS ID CHILDREN IDLE NAMESPACE LITERAL+
    1 OK CAPABILITY completed.
    2 AUTHENTICATE PLAIN
    +   
    <base64-encoded-login-here>
    2 NO AUTHENTICATE failed.


The base64-encoded-login had the form (java string):
"\000"+"username@domain\mailbox"+"\000"+password



Thunderbird:

    * OK The Microsoft Exchange IMAP4 service is ready.
    1 capability 
    * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI STARTTLS UIDPLUS ID CHILDREN IDLE NAMESPACE LITERAL+
    1 OK CAPABILITY completed.
    2 authenticate plain
    +   
    <base64-encoded-login-here>
    2 NO AUTHENTICATE failed.
    4 login "username@domain\\mailbox" "password"
    4 OK LOGIN completed. 
    5 ID ("name" "Thunderbird" "version" "38.5.1")
    * ID ("name" "Microsoft.Exchange.Imap4.Imap4Server" "version" "15.0")
    5 OK ID completed
    6 select "INBOX" 
    * 5 EXISTS
    * 0 RECENT
    * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
    * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
    * OK [UIDVALIDITY 14] UIDVALIDITY value
    * OK [UIDNEXT 4161] The next unique identifier value
    6 OK [READ-WRITE] SELECT completed.
    7 UID fetch 1:* (FLAGS) 
    * 1 FETCH (FLAGS (\Seen) UID 4154)
    * 2 FETCH (FLAGS (\Seen) UID 4157)
    * 3 FETCH (FLAGS (\Seen) UID 4158)
    * 4 FETCH (FLAGS (\Seen) UID 4159)
    * 5 FETCH (FLAGS (\Seen) UID 4160)
    7 OK FETCH completed.
    8 expunge
    * 5 EXISTS
    8 OK EXPUNGE completed.
    9 IDLE
    + IDLE accepted, awaiting DONE command.
    DONE
    9 OK IDLE completed. 
    10 noop
    10 OK NOOP completed.
    11 UID fetch 4161:* (FLAGS)
    * 5 FETCH (FLAGS (\Seen) UID 4160)
    11 OK FETCH completed.
    12 IDLE 
    + IDLE accepted, awaiting DONE command.


It's quite interesting since K9 successfully completes the login with a plain username and fails with the username@domain\mailbox form. Perhaps something is odd with the way the username gets converted to the base64 encoding. On the other hand, Thunderbird has to revert to plaintext instead of base64, too. So it might be easiest to just do the same.

**Comment by mmehnert** [comment]
Perhaps the problem is the difference between username@domain\mailbox  and username@domain\\mailbox. Both Thunderbird and K9 use the single backslash In the base64-encoded login and Thunderbird succeeds with with a double backslash in plaintext...

**Comment by bernhardschmidt** [comment]
To add some context here... 

Access to shared mailboxes in Exchange used to work with <domain>\<ownaccount>\<sharedaccount> or <logonname>\<sharedaccount> and your personal password for both AUTH PLAIN and LOGIN.

Technically AUTH PLAIN supports specifying both an authorization id (mailbox you want to access) and an authentication id (user you want to access it with) in the form

> /* RFC 4616.2. PLAIN SASL Mechanism.                
> The mechanism consists of a single message, a string of [UTF-8]
> encoded [Unicode] characters, from the client to the server.  The
> client presents the authorization identity (identity to act as),
> followed by a NUL (U+0000) character, followed by the authentication
> identity (identity whose password will be used), followed by a NUL
> (U+0000) character, followed by the clear-text password.  As with
> other SASL mechanisms, the client does not provide an authorization
> identity when it wishes the server to derive an identity from the
> credentials and use that as the authorization identity.
> 
> message = [authzid] UTF8NUL authcid UTF8NUL passwd

At some point in time Exchange 2013 IMAP was changed, so that you explicitly have to specify authzid to access shared mailboxes. Using an empty authzid and specifying both in authcid does not work anymore. Since LOGIN does not support such a distinction it continues to work fine.

This has been debugged in a Microsoft forum (https://community.office365.com/en-us/f/158/t/163878) for Office 365 back in 2014, but the code seems to have reached hosted Exchange by now. I can't tell when.

**Comment by ujos** [comment]
Hello, could you please check this issue:

```
06-29 09:32:00.191 E/k9      ( 7860): Failed to login, closing connection for conn267666768
06-29 09:32:00.191 E/k9      ( 7860): Unable to open connection for Gmail:INBOX/MessagingController/conn267666768
06-29 09:32:00.191 E/k9      ( 7860): com.fsck.k9.mail.AuthenticationFailedException: Command: AUTHENTICATE PLAIN; response: #2# [NO, System Error (Failure)]
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapConnection.saslAuthPlain(ImapConnection.java:416)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapConnection.saslAuthPlainWithLoginFallback(ImapConnection.java:385)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapConnection.authenticate(ImapConnection.java:335)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:121)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:648)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:631)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:620)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:145)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.mail.store.imap.ImapFolder.open(ImapFolder.java:114)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:841)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
06-29 09:32:00.191 E/k9      ( 7860):   at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
06-29 09:32:00.191 E/k9      ( 7860):   at java.lang.Thread.run(Thread.java:818)

```
