### ISSUE TITLE
k9mail frequently crashes when deleting mail (bulk or individual) IMAP Inbox: BUG

### ISSUE THREAD

**Issue by Mikeya7** [thunderbird/thunderbird-android#901]
K9 mail client crashes almost every time I delete mail from my inbox.
Especially bulk delete.

I've done the basic things one would do to fix.
Reinstall, delete and recreate account.
There is plenty of disc space on my device. 
I've enabled debugging. 

I don't know what else to do.
Can you help please?

**Comment by cketti** [comment]
What K-9 Mail version are you using? Can you provide the debug log?

Could it be the same as issue #814?

**Comment by gunterkoenigsmann** [comment]
Did just see that this bug was mentioned in my bug report => Attached a crash report to Bug #814.
