### ISSUE TITLE
Links incorrectly highlighted in message body

### ISSUE THREAD

**Issue by BigRodent** [thunderbird/thunderbird-android#913]
The closing angle bracket included in the link passed to the browser:
<http://example.com/standard-link-notation-not-handled-properly>

An opening square bracket terminates link recognition:
<http://example.com/square-brackets-not-handled[properly]>

**Comment by s3b-** [comment]
I can't confirm the first one.

![image](https://cloud.githubusercontent.com/assets/523178/11572185/4a9f5990-9a00-11e5-8253-8bd14e1a066b.png)

**Comment by huzaifaiftikhar** [comment]
@cketti  I want to work in this bug as a part of "one patch" rule. I tried to replicate the bug by copying the above two links and then sending it to someone using the K-9 app, the receiver receives the first link properly however the second one causes the problem and the link is broken as it encounters an opening square bracket which terminates the link recognition. (same case as the screenshot posted above 
by @s3b-) 

Android : 5.0.2
K-9 Mail : 5.206

Can I get any starting point from where I can start fixing this issue ?

**Comment by markcapella** [comment]
UriLinkifier.linkifyText() isn't matching regex |(?:^|[ (\n><])(http:|rtsp:|bitcoin:|https:|ethereum:)|
(non capturing group required followed by a recognized schema)

Additionally, a significant leading "<" trying to be decoded from a message has first been converted to |&lt;| in HtmlConverter.textToHtml() complicating things.

Changing ALLOWED_SEPARATORS_PATTERN = "(?:^|[" + SCHEME_SEPARATORS + "])?"
(making the non-capturing group optional) is a quick fix that seems to work.

Changing ALLOWED_SEPARATORS_PATTERN = "(?:^|[" + SCHEME_SEPARATORS + "]|&lt;)"
(adding the expected transient value) also seems to work.


The embedded bracket issue will remain, and might be isolated into it's own bug.

**Comment by markcapella** [comment]
Bah, the second suggestion is to change to "(?:^|[" + SCHEME_SEPARATORS + "]|&lt;)"

**Comment by markcapella** [comment]
Bah, github comments changed on the fly? Use    &lt;   vs the "<" in the final suggestion

**Comment by markcapella** [comment]
UriLinkifier.linkifyText() isn't matching regex |(?:^|[ (\n><])(http:|rtsp:|bitcoin:|https:|ethereum:)|
(non capturing group required followed by a recognized schema)

Additionally, a significant leading "<" trying to be decoded from a message has first been converted to |<| in HtmlConverter.textToHtml() complicating things.

Changing ALLOWED_SEPARATORS_PATTERN = "(?:^|[" + SCHEME_SEPARATORS + "])?"
(making the non-capturing group optional) is a quick fix that seems to work.

Changing ALLOWED_SEPARATORS_PATTERN = "(?:^|[" + SCHEME_SEPARATORS + "]|\&lt;)"
(adding the expected transient value) also seems to work.

The embedded bracket issue will remain, and might be isolated into it's own bug.

**Comment by markcapella** [comment]
Hope this is typo free :-)

UriLinkifier.linkifyText() isn't matching regex |(?:^|[ (\n><])(http:|rtsp:|bitcoin:|https:|ethereum:)|
(non capturing group required followed by a recognized schema)

Additionally, a significant leading "<" trying to be decoded from a message has first been converted to |\&lt;| in HtmlConverter.textToHtml() complicating things.

Changing ALLOWED_SEPARATORS_PATTERN = "(?:^|[" + SCHEME_SEPARATORS + "])?"
(making the non-capturing group optional) is a quick fix that seems to work.

Changing ALLOWED_SEPARATORS_PATTERN = "(?:^|[" + SCHEME_SEPARATORS + "]|&lt;)"
(adding the expected transient value) also seems to work.

The embedded bracket issue will remain, and might be isolated into it's own bug.

**Comment by markcapella** [comment]
Hope this is typo free :-)

UriLinkifier.linkifyText() isn't matching regex |(?:^|[ (\n><])(http:|rtsp:|bitcoin:|https:|ethereum:)|
(non capturing group required followed by a recognized schema)

Additionally, a significant leading "<" trying to be decoded from a message has first been converted to |\&lt;| in HtmlConverter.textToHtml() complicating things.

Changing ALLOWED_SEPARATORS_PATTERN = "(?:^|[" + SCHEME_SEPARATORS + "])?"
(making the non-capturing group optional) is a quick fix that seems to work.

Changing ALLOWED_SEPARATORS_PATTERN = "(?:^|[" + SCHEME_SEPARATORS + "]|\&lt;)"
(adding the expected transient value) also seems to work.

The embedded bracket issue will remain, and might be isolated into it's own bug.

**Comment by markcapella** [comment]
Woot! Sorry for bug spam, had to fuss with git's HTML editor formatting

**Comment by cketti** [comment]
@markcapella: You created a pull request against your own repository. If you want us to merge the fix you'll have to open a pull request against our repository.

**Comment by cketti** [comment]
This should be fixed.
