### ISSUE TITLE
Don't create an account until account creation is actually completed

### ISSUE THREAD

**Issue by lhinderberger** [thunderbird/thunderbird-android#922]
Hi guys, this one is really trivial ;)

When trying to delete a freshly created account for which the creation wizard did not run all the way through, the confirmation dialogue displays "null" instead of a meaningful value (i.E. the email address).
This does not occur when the account creation wizard was completed to the last page.

Steps to reproduce:
1. Create a new email account by clicking the "Plus" button.
2. Enter your email address and your password. Then abort the wizard _before_ anywhere before getting to the last page (where you're asked for the account name) by pressing back.
3. You return to app's "Accounts" screen. The account has been created (though not completely configured)
4. Delete it by touching it for two seconds and selecting "Remove account" from the menu displayed.
5. You should see the confirmation dialogue as shown in the attached screenshot.

It seems the cause of this is because the account name string is not properly initialized until the last page of the account creation wizard shows up. That should be easy to fix ;)

Keep up your great work, I really enjoy that application! :)
Regards - Lucas

Screenshot:
![screenshot_2015-12-01-22-41-44](https://cloud.githubusercontent.com/assets/5623987/11515230/20922b5c-987d-11e5-85f4-25bfd818f4f9.png)

**Comment by cketti** [comment]
We love pull requests for issues that are "easy to fix".

**Comment by lhinderberger** [comment]
Sorry, won't touch your code as I neither already know in which file that Bug is sitting nor do I have a ready testing environment or any previous experience with K9's code so it would probably take me much more time to get started than you.

I just wanted to point you guys to this issue in your code, as apparently noone else bothered to take the time to report it. Neither will I in future, when all I get as a response is basically a "fix it yourself" :(

**Comment by cketti** [comment]
I'm sorry if you had that impression. It's a valid bug and was marked as such. Thanks for reporting it. We'll get to it eventually.

Given that you made a statement about the difficulty of a fix one could assume you knew what you were talking about. In that case it should have been easy for you to just create a pull request with a fix. I now see that this is not the case :)

**Comment by lhinderberger** [comment]
:+1: Thanks!
I probably should have had pointed out in my original report that I did not actually look into the code but made the assumption based on the app's behaviour. Sorry ;-)
