### ISSUE TITLE
Can't find folders begining with 00=[

### ISSUE THREAD

**Issue by Vachha** [thunderbird/thunderbird-android#933]
Fails to find IMAP folders beginning with 00=[

Tested with Dovecot IMAP server 2.2-2.1.  The affected folders were tested and visible under other IMAP clients such as Thunderbird, Roundcube, Squirrel mail, stock Android Email client, and GMail.

**Comment by cketti** [comment]
This should be fixed by PR #825. The fix will be included in the next major stable version (5.200).
