### ISSUE TITLE
Mails not appearing in the inbox

### ISSUE THREAD

**Issue by gunterkoenigsmann** [thunderbird/thunderbird-android#941]
This is kind of hard to trigger. But it can be triggered at least on a Wiko Bloom and a Samsung Galaxy Note I:
- Read something in full-screen mode using the kindle app
- As soon as you get a notification for a mail that is part of a thread you have other mails of in your inbox tap the middle of the screen (which causes the notification bar to display) and while the notification bar animation showing the mail title mail by mail is still shown open the notification bar and tap on the notification from k9.
- As soon as the mail appears: Press the home button.

After that the mail is still in the inbox (Thunderbird will see it, the webmailer, too). But K9 Mail cannot see it anymore: It has disappeared from the inbox and the search function won't be able to find it, neither.

**Comment by cketti** [comment]
Can you please record a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors) when this happens again.
