### ISSUE TITLE
Can't read the full subject on long email subjects

### ISSUE THREAD

**Issue by axelsimon** [thunderbird/thunderbird-android#946]
Hi,

I'm using K9 v 5.007 (from F-Droid) and realised there's no way to display the full titles of long emails except by opening it and then requesting to see the full headers.
I would have expected to be able to touch, or maybe long touch the subject to see it in full.

Hope this helps, a quick search didn't return any open issues about this.

Cheers

![screenshot_2015-12-11-15-09-04](https://cloud.githubusercontent.com/assets/1172256/11745779/db564c12-a01a-11e5-9749-c85656a60530.png)

**Comment by cketti** [comment]
That shouldn't happen. The subject is usually displayed in the content area when it has to be ellipsized in the action bar. It works fine on my devices.

What device and Android version are you using?

**Comment by axelsimon** [comment]
Sorry, missed your reply and didn't update with the needed info.

I saw this bug on a Xperia Z3 Compact running Lollipop (5.1), if the info is still useful.
Thanks for answering in any case.
