### ISSUE TITLE
Email incorrectly sent from personal account with busness name 

### ISSUE THREAD

**Issue by aucklander** [thunderbird/thunderbird-android#961]
nexus 5 k9mail 5.007 previously on 5.006 - no issues prior.

to make it simple. 2 email accounts affected, one business and one personal. (personal default), both gmail.

i composed a new email switched to my business account, it saved to draft a few times as i as was trying to find the cheque book, i didnt leave the screen.

i sent the email only to find it was sent from my personal email with the business account name.
saved to my personal sent folder but with the business name/email being displayed,

the replied message displays it was sent from personal so k9mail was not displaying the correct email sent from.

seems like a rare occurrence and i dont know how to reproduce it.
i looked in the catlog (nothing), i realized i should of enabled extra debugging.

i will update if it happens again

**Comment by odbol** [comment]
Is this similar to issue #1064 ?

**Comment by philipwhiuk** [comment]
No feedback in several months, on the 5.x branch. Closing
