### ISSUE TITLE
widget is 2x2 instead of 1x1

### ISSUE THREAD

**Issue by ailin-nemui** [thunderbird/thunderbird-android#966]
would like to use it like an appicon, the actual space it uses is only 1x1, but it instead centers itself in a 2x2 space, making it look write
quite ugly too. (works properly on my old Sony)

**Comment by ailin-nemui** [comment]
![tmp_4909-screenshot_2015-12-20-00-18-33-174303419](https://cloud.githubusercontent.com/assets/5665186/11915632/445fb50a-a6af-11e5-8ffe-b872a5d550e5.png)

**Comment by philipwhiuk** [comment]
Seems fixed in master...

**Comment by ailin-nemui** [comment]
Is this supposed to be fixed in any released version?
