### ISSUE TITLE
Blank emails using Wi-Fi / No problem using cell service

### ISSUE THREAD

**Issue by Soiltasun** [thunderbird/thunderbird-android#971]
Thought this was an internal 'ghost' email but ABD & k9-log.txt file seemed to prove that incorrect. The message fetch size is set to "Any Size" and the messages ONLY come through when cell service is selected. Once Wi-Fi is put on [no change on Wi-Fi  or its config before/since update] messages come in as blank. Message list solely says (No subject) inclusive of parens - see images attached. Message itself has a greyed out "Text" in body of email, no recipient information or subject.

The time stamps are a minute off from my Outlook so I was able to coordinate them to each other - even though they were blanks. I forwarded received emails in Outlook via same and different accounts to test the theory. All emails passed through to K9 when on cell service and all fail/do as above when on Wi-Fi. Again, no change to Wi-Fi configuration before or after K9 update and K9 has worked with this wireless config for at least two years.

Phone: Galaxy 5S 'SM-G900V' [not rooted]
Android Version: 5 [as per Verizon 'about phone']
Wi-Fi AP: Tomato Firmware v1.28.1816

![img_20151221_134948](https://cloud.githubusercontent.com/assets/16326684/11938627/2fc83ab8-a7ea-11e5-8e2f-471db702dc27.jpg)
![img_20151221_134834](https://cloud.githubusercontent.com/assets/16326684/11938628/2fca308e-a7ea-11e5-8cf0-80f6376a7b8e.jpg)
![screenshot_2015-12-21-13-37-16](https://cloud.githubusercontent.com/assets/16326684/11938630/3467a3e2-a7ea-11e5-8811-e234d4b13144.jpg)

**Comment by cketti** [comment]
Please record a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors) when this happens again.
Also, what account type are you using? (POP3, IMAP, WebDAV)

**Comment by gdt** [comment]
FWIW, I have in the past occasionally seen messages like this in K-9, but not in any other IMAP client and not in the server filesystem, and I never figured it out.  For me, it was not repeatable, and it seemed like a message I had already received would turn to empty once in a while.  Android 4.4.2ish, K-9 from f-droid, IMAP.  I don't think I've seen it happen in at least 6 months.

**Comment by cketti** [comment]
No debug log provided.
