### ISSUE TITLE
Hide alternate email address popup when user continues to type

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#979]
When using a hardware keyboard it's possible to continue writing text while the dialog to select alternate email addresses is displayed. The can lead to the auto-complete popup being drawn on top of the alternate address popup.

![k9mail_alternate_addresses_and_autocomplete](https://cloud.githubusercontent.com/assets/218061/12011470/65e96034-acce-11e5-9080-ef8da2e78795.png)

**Comment by rishabh7m** [comment]
Hi @cketti I am unable to re-create this issue. Can it be platform specific?

**Comment by cketti** [comment]
You need to have an external keyboard connected since the soft keyboard will be hidden when the popup is displayed. I was using an emulator that allowed me to use the host system's keyboard.

**Comment by rishabh7m** [comment]
I am still unable to re-create the issue. As soon as I press space or hit enter the auto complete pop becomes invisible.

**Comment by Valodim** [comment]
this is about the alternate addresses popup

**Comment by daquexian** [comment]
I recreated this issue, and I'd like to work on it :)
