### ISSUE TITLE
Settings Export/Import 

### ISSUE THREAD

**Issue by rwinkelspecht** [thunderbird/thunderbird-android#990]
I have 3 accounts in K9 and performed an export from an old device to a new device. Only one account (IMAP) worked afterwards. The two POP3 accounts did not work after import. I had to delete and recreate the accounts for the two POP3 mailboxes in order for them to work. I can provide the settings file (privately) if needed.

**Comment by cketti** [comment]
What version(s) of K-9 Mail were you using?
How did "did not work after import" manifest itself?
Please record a debug log while trying to import the settings. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by rwinkelspecht** [comment]
I was unable to receive messages on my pop3 accounts, while the imap
account worked fine. To try to reproduce this problem, I deleted all the
accounts, turned on debugging, then re-imported the same settings that I
had used previously. This time it did work. The only error I had was
related to my IMAP account, which doesn't use SSL (had to change the
configuration to make it work). I've attached the log file for review, but
I doubt it will be helpful. I'd be willing to uninstall K9 / reinstall if
you think that might make a difference. I have several devices at my
disposal, if you would like me to do a factory reset. The device I'm using
as my primary is a Nexus 6p running Android 6.0.1. Please let me know
if/how I can be of assistance.

**Comment by cketti** [comment]
Maybe it was a typo in the password. Currently K-9 Mail doesn't notify the user of authentication errors. That issue is tracked in #879.

Since it seems to be working now I'm closing this issue.
